### ISSUE TITLE
zmq for everyone

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1]
In order to connect to any Jupyter kernel, they rely on zmq for reliable interprocess communication. The node bindings, which are quite stable (and awesome), are a bit persnickety to install on some platforms (as with anything relying on native bindings to C). In order for a developer to build, e.g., an Electron app that relies on zmq, they tend to need these items:
- zmq headers
- ~~(optionally) libsodium for encryption~~ TweetNACL is built in now!
- C compiler
- pkg-config
- for every version of Electron and node that come out, these need to be rebuilt
- rebuild for each version

[Releasing multiplatform precompiled binaries for node modules is completely doable](http://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/), though care has to be taken to allow users to use their local version of libzmq + libsodium as well.

If you dig through issues on zmq, you'll find quite a few about [installation issues](https://github.com/JustinTulloss/zeromq.node/issues/360). Currently there are bundled Windows binaries _in_ the repository for libzmq (for linking against).

**Comment by max-mapper** [comment]
I recommend https://github.com/mafintosh/prebuild for the binaries part, it even has a feature to upload the binaries to GitHub Releases for you

**Comment by rgbkrk** [comment]
Awesome. Do you think I should just create a `zmq-prebuilt` for now, similar to `electron-prebuilt`?

**Comment by okdistribute** [comment]
Seems like a good idea

**Comment by rgbkrk** [comment]
Seems like I'll need Electron support in prebuild: https://github.com/mafintosh/prebuild/issues/61

For now I've submitted a PR to zmq relying on node-pre-gyp (https://github.com/JustinTulloss/zeromq.node/pull/486), now that node-pre-gyp supports Electron directly.

**Comment by captainsafia** [comment]
I think this can be closed now?

**Comment by rgbkrk** [comment]
Now that zmq-prebuilt exists (though not finished), yes!

**Comment by rgbkrk** [comment]
Re-opening until we fully resolve this for nteract/nteract. We made a release with a built binary for some platforms, yet it requires that you still have zmq headers installed.

**Comment by jdfreder** [comment]
:astonished:

**Comment by rgbkrk** [comment]
Current pre-built status:

![image](https://cloud.githubusercontent.com/assets/836375/18696863/d0f0e574-7f81-11e6-9da3-8c8c5f4fe7bf.png)

**Comment by lgeiger** [comment]
I tested zmq on windows with nteract and can manually reproduce this error.

It turns out zmq has to be built with electron headers on windows even for electron < 1.1.3 to make it work.

**Comment by rgbkrk** [comment]
and so it is, we must trudge these waters of electron builds for the future of all of us

**Comment by lgeiger** [comment]
Status on windows:
Still no prebuilts for electron but working if you build from source: https://github.com/nteract/nteract/pull/903

**Comment by rgbkrk** [comment]
@lgeiger has totally demolished this issue - from incredible cross-platform work in `zmq-prebuilt`, to creating `zmq-static`, and upstream fixes in `zeromq.node`.

We even have Windows builds now. 😄 😱 

Closing this issue with much appreciation.

**Comment by lgeiger** [comment]
@rgbkrk Since the fallback is now working in `zmq-prebuilt`, what should we do with `zmq-static`?
I think `zmq-prebuilt` is now superior in every way.

I didn't expect to get it working at the time of creating `zmq-static` 😄 .

**Comment by rgbkrk** [comment]
Leave a deprecation notice in zmq-static, pointing to zmq-prebuilt. You apparently [stirred a little bit of buzz by creating `zmq-static`](https://twitter.com/miramba_/status/784132379841404932), and if people found that over `zmq-prebuilt` we should at least do the service of redirecting it.

**Comment by lgeiger** [comment]
Great to see some people checking it out! I'll leave a notice.

**Comment by rgbkrk** [comment]
One way to "deprecate" while being backwards compatible is to make `zmq-static`'s `index.js` be:

``` js
module.exports = require('zmq-prebuilt')
```

(while also noting they should use `zmq-prebuilt` instead)

**Comment by lgeiger** [comment]
I think we can leave it as is for people who really want to keep using VS 2013.

**Comment by rgbkrk** [comment]
Ah, ok, that works.
