### ISSUE TITLE
Add example notebooks to File menu

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#1000]
After the podcast interview, @shanselman mentioned that it would be a good idea to include the example notebooks in the File > Open menu. We heard similar feedback at the NumFOCUS Summit.

Tagging this as new-contributor-friendly with mentorship from me available.

**Comment by alexandercbooth** [comment]
Hi @captainsafia

I just submitted a PR for this (#1001). Can you check it over when you get a chance and let me know what you think? For some reason, the notebooks don't always open 😕. 

Thanks!
