### ISSUE TITLE
Docker Container?

### ISSUE THREAD

**Issue by pgensler** [nteract/archived-desktop-app#1017]
Hi,

I'm pretty new to using your product, but I will say I am really excited to test this out and see how it works! Do you have any plans to put a docker container for this, for others to spin up easily? I think it could be beneficial, as I know other services like RCloud have done so, and its really easy to get up and running. Here is the link to the Docker page for public containers. Thanks!
https://hub.docker.com/explore/

**Comment by rgbkrk** [comment]
We don't have a pure-web version yet, though when we do it will probably be backed by the jupyter notebook APIs. Thanks for posting an issue!

**Comment by pgensler** [comment]
I'd look at the RCloud infrastructure for ideas, as they have a very similar concept to what you are trying to achieve, but a little more complex. This is based on R, but still pretty good example of what a notebook can achieve.
http://rcloud.social/documentation/doc/1.6/guidoc/doc.html#running-a-notebook

**Comment by rgbkrk** [comment]
Awesome, we'll keep it in mind for any future web version. I'll close this since this repo is for the native desktop app.

**Comment by jkremser** [comment]
:+1: This feature would be highly appreciated.

docker image could work also for the desktop app:
```bash
docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix 0300fca0c441 npm run start
```
`0300fca0c441` is the hash of image that was built from the Dockerfile that is currently present in to repo (and is probably outdated).

When I updated the dockerfile to be based on the `node:6.11.1` instead of `node:6.5.0` it's slightly better (`npm run build` passes) but it still doesn't work

**Comment by jkremser** [comment]
also this package was needed `libx11-xcb-dev` this is the log output when I gave up:


```bash
root@0300fca0c441:/nteract# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'spawn' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prespawn', 'spawn', 'postspawn' ]
5 info lifecycle nteract@0.2.0~prespawn: nteract@0.2.0
6 silly lifecycle nteract@0.2.0~prespawn: no script for prespawn, continuing
7 info lifecycle nteract@0.2.0~spawn: nteract@0.2.0
8 verbose lifecycle nteract@0.2.0~spawn: unsafe-perm in lifecycle true
9 verbose lifecycle nteract@0.2.0~spawn: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/nteract/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle nteract@0.2.0~spawn: CWD: /nteract
11 silly lifecycle nteract@0.2.0~spawn: Args: [ '-c', 'cross-env NODE_ENV=development electron .' ]
12 silly lifecycle nteract@0.2.0~spawn: Returned: code: 1  signal: null
13 info lifecycle nteract@0.2.0~spawn: Failed to exec spawn script
14 verbose stack Error: nteract@0.2.0 spawn: `cross-env NODE_ENV=development electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid nteract@0.2.0
16 verbose cwd /nteract
17 error Linux 4.11.11-300.fc26.x86_64
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "spawn"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error nteract@0.2.0 spawn: `cross-env NODE_ENV=development electron .`
22 error Exit status 1
23 error Failed at the nteract@0.2.0 spawn script 'cross-env NODE_ENV=development electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the nteract package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=development electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs nteract
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls nteract
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rgbkrk** [comment]
Just an update -- there is now a web version of nteract that runs on top of the jupyter server. You can [try it out on binder!](https://mybinder.org/v2/gh/nteract/vdom/master?urlpath=nteract/edit/example-notebooks)

The jupyter extension is called `nteract_on_jupyter` on PyPI and there are install instructions here: https://github.com/nteract/nteract/tree/master/applications/jupyter-extension
