### ISSUE TITLE
Kernels not connecting when missing `nteract.json` file

### ISSUE THREAD

**Issue by aterrel** [nteract/archived-desktop-app#1027]
While trying to get the install up on `master`, my kernel wasn't actually connecting. Popping up the dev tools showed that `~/Library/Jupyter/nteract.json` was missing. After creating the file with an empty object in it, the kernel connected just fine.

I would suggest that the file be automatically created if it doesn't exist, but I don't know the implications to the rest of the system.

cc @rgbkrk and @jdetle who helped diagnose the issue on slack.

**Comment by captainsafia** [comment]
Welp! This one's on me. Wasn't expecting that a failure to read in the ConfigObservable would prevent kernels from connecting. I suppose a good fix is to create the file on read failure.
