### ISSUE TITLE
Request kernel shutdown

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#103]
Same as https://github.com/nteract/ick/issues/19, we need to issue a [`shutdown_request`](http://jupyter-client.readthedocs.org/en/latest/messaging.html#kernel-shutdown) before we kill the process.

**Comment by jdfreder** [comment]
ah, yes

**Comment by captainsafia** [comment]
Safia, do this!

**Comment by betatim** [comment]
Is this the issue about kernels being alive after quitting the app?

**Comment by rgbkrk** [comment]
Yeah our cleanup isn't fully happening right now, leaving the connection files around.

**Comment by betatim** [comment]
The process seems to keep running as well. Check `pgrep -f "python3 -m ipy"` after starting and quitting `nteract` a few times.

**Comment by betatim** [comment]
Pressing `Cmd+q` is wired directly to `app.quit()` without creating a `KILL_KERNEL` action or calling `cleanupKernel()`.

We can add a `send(focusedWindow, 'menu:kill-kernel')` to the quit menu item, but then you need to delay calling `app.quit()` to give it a chance to do stuff. What is a good way of `ipc()`ing and waiting for that message to have been completed. Should we send a message back via ipc and then `app.quit()`?

**Comment by rgbkrk** [comment]
The awkward part here is the difference between OS X and all the others. cmd-q should tell each running window to close their kernel (which means `ipc`) or we'd have to track the kernels on the main thread to shut them down there (what if the `BrowserWindow` is no longer responding).

**Comment by rgbkrk** [comment]
Ok, I've noticed that `beforeunload` and `unload` events are both fired when you `ctrl-c` kill an application, as well as the rest of the quit action. What we're definitely running into though is that we've been relying on an asynchronous flow for killing the kernel. When these two are triggered, we need to handle them _immediately_.

**Comment by rgbkrk** [comment]
Basically we can't (and shouldn't) rely on dispatch for killing a kernel for forced lifecycle events. Otherwise our dispatched kill kernel won't happen because the reduction won't happen until the next tick.
