### ISSUE TITLE
Kernels not found on Windows 10 with Anaconda (Py 3.5)

### ISSUE THREAD

**Issue by tildebyte** [nteract/archived-desktop-app#1030]
This is a workaround documentation issue, though I'm not sure if it should be reported to you or Jupyter.

By default, the Jupyter installed from Anaconda works just fine. A little research (sparked by trying to get the nteract app working) shows that there are _no_ `kernel.json` files anywhere on the system; thus no joy for the nteract app.

A simple (but completely unknown to me) `ipython kernel install` from the command prompt sufficed to get things working (this generates a `kernel.json` and drops it into `C:\ProgramData\jupyter\kernels\python3`).

**Comment by rgbkrk** [comment]
Thanks for trying nteract and reporting this! There's active work to detect conda environments and have them show up as kernels -- this is certainly on our beta milestone.

I'm really happy you were able to install the ipython kernel directly. You can also install named kernels when in a conda environment like so:

```
ipython kernel install --name 'conda-kernel-myproject' --user 
```

There's also a `display-name` option (which is shown in the UI).

Closing this to defer to #357 for the conda kernel issue. Feel free to re-open if you'd like it open. Thanks again!
