### ISSUE TITLE
Using `nteract` on remote servers

### ISSUE THREAD

**Issue by chriddyp** [nteract/archived-desktop-app#1031]
Hi folks! 

Someone asked an interesting question to me about `nteract` today that I wasn't able to answer. What does the `nteract` workflow look like for users working off of a server. e.g.
- User installs spark on an AWS server 
- User SSHs into the server
- User would usually just run `$ jupyter notebook` and SSH-forwards the remote jupyter port `8888` to their local machine and then visit e.g. `localhost:8888` on their laptop's web browser.

What would this look like for `nteract`? `x11` and `xterm`?

**Comment by rgbkrk** [comment]
Great feedback!

Two long term answers:

## Remote kernels

There's a current initiative to [support kernels remotely](https://github.com/nteract/initiatives/tree/master/remote-kernels) where you can use the notebook server as the backend for your kernels. This server could be tunneled like you described or served over TLS with auth (API token or password on server).

@captainsafia is leading an effort around this.

## Web version of nteract

[Once we have the components exported](https://github.com/nteract/nteract/issues/549), we can put together components from nteract on top of the Jupyter Notebook server.

@rgbkrk is leading an effort around this.

---

In service to both of these, there is already effort to [expose RxJS bindings to the Jupyter Notebook API](https://github.com/nteract/rx-jupyter), which makes it plug in well with the rest of nteract's architecture.

**Comment by rgbkrk** [comment]
See #1346 for the current outline, progress, and direction.

**Comment by rgbkrk** [comment]
Closing since this was primarily a question and we have an issue for tracking the web app progress.

**Comment by rgbkrk** [comment]
Just an update -- there is now a web version of nteract that runs on top of the jupyter server. You can [try it out on binder!](https://mybinder.org/v2/gh/nteract/vdom/master?urlpath=nteract/edit/example-notebooks)

The jupyter extension is called `nteract_on_jupyter` on PyPI and there are install instructions here: https://github.com/nteract/nteract/tree/master/applications/jupyter-extension
