### ISSUE TITLE
"\\" does not give newline in Markdown cell LaTeX

### ISSUE THREAD

**Issue by darthoctopus** [nteract/archived-desktop-app#1037]
In Markdown cell LaTeX blocks, "\\" is not parsed as a newline (as it is in Jupyter notebook); one is required to give four consecutive backslashes ("\\\\"). When the notebook is subsequently opened in the Jupyter environment, LaTeX is then rendered differently again (which makes matrices etc. look awkward).

**Comment by lgeiger** [comment]
It's likely a problem with the commonmark parser.
In the markdown cell `\\` will always render as `\` as well.

**Comment by darthoctopus** [comment]
Jupyter itself uses [marked](https://github.com/chjj/marked). Perhaps could use that instead? Would also guarantee cross-compatibility in future.

**Comment by jkornblum** [comment]
Hello @lgeiger you're correct. It is being passed to MarkdownRenderer as "\" not "\\" via the common mark parser.

@darthoctopus may have a better idea but if we want a less elegant solution I've created a branch which uses regex to find $ - $ or $$ - $$ and then fix the issue but manually adding the additional backslashes. It worked with a few quick manual tests. I need to write some unit tests to cover any edge cases before a PR.

If people are okay with this, where exactly should this function go? I'm still trying to understand fully the program architecture with Redux, RxJS, etc.. I'm not sure the component .js file is the most appropriate place which is where I have it placed now.

You can see the code on my [branch](https://github.com/jkornblum/nteract/commit/0d9596fcd48b9062ad766174fa7f90062313f555)

![error](https://cloud.githubusercontent.com/assets/5368903/19771815/d4c078c6-9c29-11e6-82ef-ccafcdfd8fd9.png)

**Comment by sglyon** [comment]
Just ran into this over on quantecon bookshelf... http://bookshelf.quantecon.org/submission/59fa1b45145fc3772b0cef82

Any chance this can be fixed so that latex parsing/handling in nteract matches that in juptyer notebook?

**Comment by rgbkrk** [comment]
Closed by #2350.
