### ISSUE TITLE
Add "Undo" Cell delete

### ISSUE THREAD

**Issue by rornor** [nteract/archived-desktop-app#1038]
Hi guys,

I see this commit https://github.com/nteract/nteract/pull/627 but that's probably for general text undo
Is this feature on the radar (don't want to say this but i.e. like in jupyter menu edit > undo cell delete)?

Thanks

**Comment by captainsafia** [comment]
Thanks for opening the issue @rornor!

The pull request you cited actually allowed undoing cell deletion, addition, and a whole bunch of other stuff, but it was quite buggy so we ended up taking it out. We could probably add it back and  give the ability to undo cell deletions but my hope was to get it closer to a native experience and allow people to undo a variety of actions.

So yes, it'll be coming back (most likely in our release candidate) once I get the kinks figured out.

**Comment by arudhir** [comment]
A temporary fix - moving the trash icon away from the run icon (or better yet, in that drop down menu thing) might cause less users to run into the issue of accidentally deleting their cells.

This is my first time ever making a notebook, so I dunno if this totally ruins power-users' workflow or not.

Edit: Or, similar to Hydrogen, something like cmd+enter to run the cell? That sounds like something you'd eventually put in anyways and is less temporary.

**Comment by captainsafia** [comment]
@arudhir: That's quite a wonderful idea! Would you be interested in implementing this? It's quite simple and I'd be happy to mentor you through the contribution process.

**Comment by arudhir** [comment]
Ooh! I would love to try to help out!

**Comment by captainsafia** [comment]
@arudhir: Fantastic! You can join our [Slack community](https://slackin-egwcornswi.now.sh/). Once you've created an account, say "Hi!" in the general channel and I'll reach out and help you.

**Comment by rgbkrk** [comment]
We definitely still need this. Please freshen the issue stale bot.

**Comment by harlecin** [comment]
Hey there:) 

is this issue still active?

**Comment by drbh** [comment]
Please fix, this is a very bad bug to have since CTRL+D in Sublime and many other text editor is line duplication. In nterat it destroys the cell with no way to retrieve the code! 

Please Please BUMP - either remove the destructive key bindings or add a undo button.

**Comment by captainsafia** [comment]
Looking through old issues.

@drbh Can you clarify what you mean by Ctrl+D destroying cells in nteract?

I'd love to see undo for cell deletions implemented alongside universal undo/redo. I think it makes the user experience much more pleasant and editor-like.

We'll be doing a UI overhaul soon so we'll definitely try to make it less likely to press the delete button in future designs.

@fabric-8 The delete icon in the top-right of our menu is pretty easy to accidentally click and causes some users to lose their work. Our new mockups should reduce the likelihood of these accidental donations.

**Comment by drbh** [comment]
@captainsafia Ctrl+D deletes the cell and it’s code contents. 

I strongly agree that there should be a “undo cell deletion” as well as the universal undos. This would make the Ctrl+D problem much easier to fix (since you could just undo the deleted cell).

However I still think Ctrl+D should duplicate the line - and not remove the cell as many other IDE’s have as the default hotkey.

**Comment by SanGoku95** [comment]
Has there been any progress on this? Thanks!
