### ISSUE TITLE
Run kernel with python virtualenv?

### ISSUE THREAD

**Issue by jackluo** [nteract/archived-desktop-app#1041]
I was just wondering if it was possible to use nteract with a virtualenv kernel of python as to allow installing packages locally.

Thanks

**Comment by rgbkrk** [comment]
One thing you can do from the command line is activate the virtual environment then install the kernel specification from within the environment:

```
python -m ipykernel install --user --name some-env --display-name "Python (some-env)"
```

/cc @minrk @takluyver

**Comment by rgbkrk** [comment]
Closing as this can be done with a kernel for the virtual env.

After thoughts: perhaps we need some built in help that can assist users in creating kernels for virtual envs, conda environments, or generally debugging.

**Comment by eavelardev** [comment]
You can activate virualenv and run nteract with the terminal, works with the AppImage
