### ISSUE TITLE
[Bug] Trouble running tests locally

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1042]
_Problem_:
`npm run test` throws the error shown below on the freshest install for master. 

```
> @ test /Users/johndetlefs/github/nteract
> npm run test:unit
> @ test:unit /Users/johndetlefs/github/nteract
> cross-env NODE_PATH=app/node_modules/ mocha -r test/setup.js --compilers js:babel-core/register "test/renderer/**/*.js"

/Users/johndetlefs/github/nteract/app/node_modules/rxjs/observable/FromObservable.js:101
        throw new TypeError((ish !== null && typeof ish || ish) + ' is not observable');
```

_Currently using_:
node v6.7.0
npm  v3.10.3

**Comment by captainsafia** [comment]
I assume you nuked your `node_modules` and reran `npm install`?

**Comment by jdetle** [comment]
Yeah I just double checked and unfortunately its still an issue.

**Comment by jdetle** [comment]
Spitballing here but maybe it has something to do with the fact that I run node and npm locally as opposed to using `sudo`? Totally could be irrelevant, but doesn't hurt to mention.

**Comment by rgbkrk** [comment]
There are two sets of node_modules now. At the basepath and in app/

**Comment by jdetle** [comment]
You can just start calling me Patrick Star because clearly I live under a rock. Everything good after both npm installs. Thanks.

**Comment by rgbkrk** [comment]
@lgeiger make it a little easier by providing `npm run reinstall` (so we don't have to tell people to nuke and install again).
