### ISSUE TITLE
Write unit tests for main

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1047]
The main process is likely to continue to expand in what it does. As much as possible, we should pick off more bits that can be unit tested similar to the renderer/notebook process.

**Comment by HackersSpirit** [comment]
@rgbkrk  @captainsafia : can i work on the issue

**Comment by captainsafia** [comment]
Hi, @HackersSpirit! Thanks for stopping by. You can absolutely work on it. Feel free to reach out to us on this issue if you need any help.

**Comment by rgbkrk** [comment]
Wow, there were two issues for this apparently. I suppose I'll keep this one open, though we do have _some_ unit tests for main here.

**Comment by Madhu94** [comment]
@rgbkrk Is this still open ?

**Comment by rgbkrk** [comment]
Yep, we can always use new tests for main. 😄

**Comment by Nanang32** [comment]
waw
