### ISSUE TITLE
Scroll area should indicate that there's more content

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1050]
Can you tell there's more content above or below here?

![screen shot 2016-10-20 at 4 35 32 pm](https://cloud.githubusercontent.com/assets/836375/19581623/41ab2a04-96e3-11e6-80c5-b6961609176c.png)

When scrolled up it's more obvious with the content I have here:

![screen shot 2016-10-20 at 4 34 42 pm](https://cloud.githubusercontent.com/assets/836375/19581610/1f473688-96e3-11e6-8495-29739b3eaaaf.png)

We need some kind of indication that the cell has more output to scroll through (or to be expanded with the upper right context menu). Maybe borders?

I'd also love to have scroll behavior to only be enabled when you've clicked into the output area.

**Comment by jdetle** [comment]
So at work I did something like this by keeping the scrollwheel showing if scrollable:

```
::-webkit-scrollbar {
    -webkit-appearance: none;
    width: 7px;
}
::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(0,0,0,.5);
    -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
}
```

will webkit work on nteract?

**Comment by rgbkrk** [comment]
Yeah, nteract runs on chromium which accepts changing the scroll bar styling with those webkit prefixes.

**Comment by rgbkrk** [comment]
Looking at this one again, I'm thinking I'd want something at the top or bottom. Our scroll bars are styled (can't remember which PR). I'll go ahead and close this PR since it's not likely to happen anytime soon.
