### ISSUE TITLE
Windows Installer Configuration

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1060]
The exe currently gives you no options on e.g. where to install nteract or whether to install for all users or just the current user.

It would be good to allow for such configuration in the installer. Alternatively, bringing back the windows zip file would let you unzip nteract to wherever you wanted

**Comment by rgbkrk** [comment]
Thanks for chiming in on this, we went through the work of getting the Windows build setup yet don't know what choices are the best for all users.

It looks like there are options for the tool we use, `electron-builder`, via some [combination of `.build.nsis.oneClick` and `.build.nsis.perMachine`](https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions) that would end up in the [electron-builder section of our package.json](https://github.com/nteract/nteract/blob/29988e4c81792dae5c3779d8ceb839de3c2820f2/package.json#L42).

**Comment by rgbkrk** [comment]
It _appears_ like:

``` json
  "nsis": {
    "oneClick": false
  }
```

would work inside the build config. Are you able to build, try it out, and make a PR @dhirschfeld?

**Comment by dhirschfeld** [comment]
I'm away for a week and might be very busy when I get back so might not be
able to get to it for a couple of weeks...

**Comment by lgeiger** [comment]
@dhirschfeld No problem. I can test it.

**Comment by lgeiger** [comment]
Right now it isn't possible to change the install directory with `electron-builder`: https://github.com/electron-userland/electron-builder/issues/596

Though we could add a option to install nteract only for the current user.
