### ISSUE TITLE
Making plotly for R, Julia, & Python work in nteract

### ISSUE THREAD

**Issue by jackparmer** [nteract/archived-desktop-app#1061]
`embed_notebook()` (for R), `py.iplot()` (for Python), and `JupyterPlot()` (for Julia) currently don't work out-of-the-box inside _nteract_ (they work great in vanilla Jupyter notebook however).

There's currently a [workaround](https://github.com/plotly/plotly.py/pull/562#issuecomment-245078317) being proposed for Plotly's Python interface.

To help keep track, here are 3 separate issues in the repos of each language's interface:
- [x] Issue for R: https://github.com/ropensci/plotly/issues/768
- [x] Issue for Python: https://github.com/plotly/plotly.py/pull/562
- [x] ~~Issue for Julia:~~ https://github.com/spencerlyon2/PlotlyJS.jl/issues/90 ( @sglyon grabbed this)

📈  📊  ✨

**Comment by rgbkrk** [comment]
The Plotly.py one was recently completed by @theengineear. All that is left is R support.

Bonus points: Scala!?!

**Comment by jackparmer** [comment]
@rgbkrk Nice idea. @pbugnion might be interested in this, he initiated plotly's Scala client:
https://github.com/ASIDataScience/scala-plotly-client

**Comment by pbugnion** [comment]
Happy to help, though I won't have time to contribute to this directly. It's worth noting that the Scala Plotly client doesn't currently in 'offline' mode -- it dispatches to Plotly. The only way to visualise the results in interact would be through an iframe.

**Comment by jackparmer** [comment]
Nice job team. Full Plotly _nteract_ support now for R, Python, and Julia 👍
