### ISSUE TITLE
Document Cell Focus UX Design

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1065]
I'd :heart: to see us write documentation for what a notebook is in user experience terms. Right now it's a bit implicit ("it's the implementation!") -- I think we can capture different behaviors and user intents in some solid documentation/specifications. Let's tackle Cell Focus UX design first!

@captainsafia is currently solving the input focus on click in code cells problem in #1055 (our current setup is rather pesky). Hopefully we can solve all our focus problems with a clear declaration + implementation.
## Cell Focus UX

![cell focus user experience](https://cloud.githubusercontent.com/assets/836375/19669086/48b6f02c-9a11-11e6-875a-d330fdb0f900.png)

User intents, written:
### `shift enter`
- Focus on next cell (and create it if it doesn't exist)
- Scroll to next cell
- Focus Editor at top of next cell (first line) if a code cell or a markdown cell in edit mode

Note: this is the same set of changes expected with the down arrow (for focus, not execution).
### `up arrow`
- Focus on previous cell
- Scroll to previous cell
- Focus editor at bottom of previous cell (last line) if a code cell or a markdown cell in edit mode
### `down arrow`
- Focus on next cell (and create it if it doesn't exist)
- Scroll to next cell
- Focus Editor at top of next cell (first line) if a code cell or a markdown cell in edit mode
### Click editor area
- Focus clicked cell
- Don't scroll
- Don't _manually_ focus the editor, let CodeMirror do the handling
### Click display area
- Focus clicked cell
- Don't scroll
- Don't focus the editor
### Drag cell
- Focus clicked cell
- Don't scroll
- Don't focus the editor

Since I by no means think this is a decree, I've drawn my initial thoughts on cell focus UX with crayon. We should refine this as necessary and produce a document. Happy to turn this into a Sketch document when ready.

/cc @willingc and @peggyrayzis who expressed interest in this

**Comment by rgbkrk** [comment]
Hopefully outlining this helps us fix #429, #803.

**Comment by captainsafia** [comment]
I like these user intents. It's unclear to me from the diagram but is the drag cell intent directed at the gutter out of the output area or the input area or both? The current implementation does it along the entire gutter.

I closed the PR I was working on (#1055) to start off a clean slate with implementing a solution for this. It looks like we'll have to manage multiple focused states for the CodeMirror editor and the CodeCell/MarkdownCell so there is lots of fun state juggling to be done. 😛

**Comment by captainsafia** [comment]
Here are more thoughts on this. Specifically, here is how user intents would map to changes in the state. Let's assume we have a simple document with `<CodeCell id="1"/>`, `<CodeCell id="2"/>`, and `<MarkdownCell id="3"/>` . The two state elements that we have are `editorFocusedCell` for the cell that has CodeMirror focused and `cellFocused` for the `Cell` that is focused.

Let's say the user starts off with `{editorFocusedCell: 1, cellFocused: 1}`.
1. User presses `down arrow`, the state is now `{editorFocusedCell: 2, cellFocused: 2}`.
2. User presses `up arrow`, the state is now `{editorFocusedCell: 1, cellFocused: 1}`.
3. User clicks the display area on `<CodeCell id="2"/>`, the state is now `{editorFocusedCell: 1, cellFocused: 2}`.
4. User clicks the cell editor on `<CodeCell id="2"/>`, the state is now `{editorFocusedCell: 2, cellFocused: 2}`.
5. User presses `down arrow`, the state is now `{editorFocusedCell: 3, cellFocused: 3}`.
6. User presses `shift+enter`, the state is now `{editorFocusedCell: 4, cellFocused: 4}`.

There are probably other combinations of moving between editor components that need to be considered but I think this is a good representation of how the visual representation can be shown in the component state.

**Comment by rgbkrk** [comment]
> I like these user intents. It's unclear to me from the diagram but is the drag cell intent directed at the gutter out of the output area or the input area or both? The current implementation does it along the entire gutter.

The entire gutter, only because that's what we have now. As long as there's an area and that we define what it means for focus, editor focus, and scroll when dragging, I'm happy.

**Comment by rgbkrk** [comment]
Great exploration, I like this!

``` jsx
<CodeCell id="1" />
<CodeCell id="2" />
<MarkdownCell id="3" />
```

I'll explore a couple of these for a sec

> User clicks the display area on <CodeCell id="2"/>, the state is now {editorFocusedCell: 1, cellFocused: 2}.

I think we want `editorFocusedCell` to be `null` in this case. We want focus from the cursor/editor to go away (prevent accidental typing, allow other text input to be used).

> User clicks the cell editor on <CodeCell id="2"/>, the state is now {editorFocusedCell: 2, cellFocused: 2}.

Here's where it's a bit strange (and where you fixed it in #1055). We want to lose focus on any other editors (maybe it doesn't have to be explicit) and allow CodeMirror to do the focusing so the user ends up clicking exactly at the cursor position they want.

**Comment by rgbkrk** [comment]
We probably want the state structure to be something like:

``` js
{
  focusEditor: true,
  focusedCell: '1',
  scrollToFocus: true,
}
```

We run into a problem though in scrolling/focusing in which we want to make sure that we don't re-scroll as other state changes in the document (focusedCell remains set to '1' for example while scrolling around and outputs are coming in).

**Comment by captainsafia** [comment]
> I think we want editorFocusedCell to be null in this case. We want focus from the cursor/editor to go away (prevent accidental typing, allow other text input to be used).

Ah yeah! This makes way more sense.

> Here's where it's a bit strange (and where you fixed it in #1055). We want to lose focus on any other editors (maybe it doesn't have to be explicit) and allow CodeMirror to do the focusing so the user ends up clicking exactly at the cursor position they want.

Yeah. So I have a feeling I might need to pull some nasties with React to get this working right. Because we would need the `Editor` to change the state on `editorFocused` and then that change would have to bubble up the DOM tree to the parent `CodeCell`, `Cell`, and `Notebook` components.

**Comment by captainsafia** [comment]
> We probably want the state structure to be something like:
> {
>   focusEditor: true,
>   focusedCell: '1',
>   scrollToFocus: true,
> }

Yeah, this makes more sense actually. I hadn't throughly thought out how scroll would fit in with all of this.

**Comment by rgbkrk** [comment]
> Yeah. So I have a feeling I might need to pull some nasties with React to get this working right. Because we would need the Editor to change the state on editorFocused and then that change would have to bubble up the DOM tree to the parent CodeCell, Cell, and Notebook components.

There's an onClick handler for the CodeMirror component where we can set focus and yet _not_ focus the editor (codemirror is doing it) and _not_ scroll (implicitly done by user).

**Comment by rgbkrk** [comment]
That state structure likely matches the event as well (unless we turn them into discrete actions that match our roughly two events above).

**Comment by rgbkrk** [comment]
Oops! Wrong button while commenting. 👅
