### ISSUE TITLE
Convert TODOs in code base to issues.

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1072]
There are a bunch of them, we should turn them into issues. Some of them are pretty quick fixes, others are architectural in nature. Creating the issues is very friendly for people to go ahead and do (including myself).

Steps to "complete" one of these:
- Create the issue
- Make a PR deleting the TODO (or referencing the issue in a comment)

**Comment by rgbkrk** [comment]
Well that was fast, thanks @LBKinson. :smile:

**Comment by LBKinson** [comment]
@rgbkrk that's my first OSS PR...ever! would love feedback. Also would love to contribute more, I'll start scanning your issues

**Comment by rgbkrk** [comment]
Welcome to the nteract party! :tada:

> that's my first OSS PR...ever! would love feedback

Woo! You did it perfectly, so I don't have anything to add on (other than my one small comment about commit prefix). Let us know how we can help. We also have a [slack you can join](http://slack.nteract.in/).
