### ISSUE TITLE
check for sys.prefix/share/jupyter/kernels/*/kernel.json

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1075]
In `src/main/kernels.js`: already checks for `ipykernel` existence, also need to check for:
- [ ] `${condaEnvironmentSysPrefix}/share/jupyter/kernels/*/kernel.json`
- [ ] IRKernel (check if installed)

**Comment by captainsafia** [comment]
To elaborate further on this, [the code in kernels.js](https://github.com/nteract/nteract/blob/master/src/main/kernels.js#L14) currently only checks to see if the Python IPyKernel is available. Ideally, we want to iterate through all the kernels in `${condaEnvironmentSysPrefix}/share/jupyter/kernels/*/kernel.json` and check that they exist as well.

**Comment by willingc** [comment]
Closing since #3862 will track improvements for conda and kernels.
