### ISSUE TITLE
Support R kernel detection for Conda environments

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1077]
- [ ] within `createKernelSpecsFromEnvs` function in `src/main/kernels.js`, need to add support for default R kernel inside langEnvs{}
- [ ] also need to provide resource-dir inside langEnvs{}

**Comment by rgbkrk** [comment]
We definitely need to bring in the conda support all the way so we can even tackle this one. 🙃

**Comment by willingc** [comment]
Closing since #3862 will track improvements for conda and kernels.
