### ISSUE TITLE
change toggleStickyCell structure to Immutable.Set

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1086]
need to switch stickyCells structure to an Immutable.Set in `toggleStickyCell` function within `src/notebook/reducers/document.js`

**Comment by captainsafia** [comment]
I'll mark this as new-contributor-friendly since it is a pretty straightforward change to folks with experience in Immutable.JS or JavaScript.

Mentorship available from me via [our Slack](http://slack.nteract.in/).
