### ISSUE TITLE
Filename Proposal

### ISSUE THREAD

**Issue by kenwheeler** [nteract/archived-desktop-app#109]
We have disallowed using capital case at Walmart, due to OSX case insensitivity issues. Additionally, we use the .js extension instead of .jsx.

Do we have good reasons for either? On other projects we've found these patterns to be more trouble than they are worth.

Thoughts?

**Comment by jdfreder** [comment]
+1 to not use CapitalCase, I always stick to hyphen-separated-filenames for JS projects.

.js vs .jsx - would there be any reason to **not** run the react jsx transpiler against a module? i.e. any subtleties in js that don't work in jsx?

**Comment by kenwheeler** [comment]
+1 on dash-case. The JSX transpiler is the babel transpiler (its on by default) so there isn't a clear advantage to the separation.

**Comment by jdfreder** [comment]
Then +1 to also use .js everywhere, @rgbkrk ?

**Comment by rgbkrk** [comment]
I'm all about being pragmatic, this sounds like the best choice. :+1: to the refactor and setting it in a style guide.

**Comment by rgbkrk** [comment]
OMFG, while trying to fix this I'm finally seeing the case insensitivity issues on OS X. wat.

Anyway, fix coming.
