### ISSUE TITLE
determine a strategy for picking tiles 

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1093]
in `componentDidMount` function within `src/notebook/components/transforms/geojson.js`

**Comment by rgbkrk** [comment]
Now that we have a config, we could probably allow folks to set this as part of their nteract.json.

**Comment by gnestor** [comment]
I tried out the GeoJSON example notebook and I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/512354/21449349/2207e8f0-c8a1-11e6-91d6-d1c69967f118.png)

Is this related or should I open a new issue?

**Comment by rgbkrk** [comment]
That's unrelated and fixed on master now. Your theme is nteract and instead of replacing the theme name with light or dark it put the nteract name in the tile URL.

**Comment by gnestor** [comment]
I'm running master and still seeing this. Switching to "Light" or "Dark" themes fixes it.

**Comment by rgbkrk** [comment]
Alright, let me see if I can fix this.

**Comment by gnestor** [comment]
I'm going to re-open this to address the original issue which is configuring the strategy for fetching map tiles.

**Comment by rgbkrk** [comment]
Thanks!

**Comment by rgbkrk** [comment]
Our current strategy is to default to light unless the theme is explicitly set as dark. A 🆒  😎  thing we could do is to set it based on:

```js
window.getComputedStyle(el).backgroundColor
```

**Comment by gnestor** [comment]
@rgbkrk 😮
