### ISSUE TITLE
switch !kernelConnected from notification to error dispatch

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1094]
currently on no kernel connected the app sends a message via notificationSystem; need to change this to dispatch an error instead.  
in `executeCellEpic` function within `src/notebook/epics/execute.js`

**Comment by rgbkrk** [comment]
Oh yeah, that's a good one to clean up now that we have the error middleware for our redux store.

**Comment by rgbkrk** [comment]
This is now cleaned up.
