### ISSUE TITLE
move firstTimePublish observer out of gistCallback function

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1095]
need to move `firstTimePublish` conditional in `gistCallback` function within `src/notebook/epics/github-publish.js` up and out to be handled as a return on the observable

**Comment by rgbkrk** [comment]
@jdetle did you handle this recently?

**Comment by jdetle** [comment]
No, I did a different refactor inside that code. I'll tackle a refactor this weekend.

**Comment by rgbkrk** [comment]
This is a bit more cleaned up, I'll go ahead and close it since this TODO Issue is a bit ominous.
