### ISSUE TITLE
send kernel_info_request again after a timeout

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1096]
When a kernel is launched, we should ensure `kernel_info_reply` is recieved after a timeout and if not, send `kernel_info_request` again. This would likely be part of `acquireKernelInfo`.

**Comment by rgbkrk** [comment]
This affects kernels that are a bit slower to start, which includes Scala and Julia.

We primarily need to do a retry of the sending of a kernel_info_request if we don't get it in time.

**Comment by rgbkrk** [comment]
I'm going to close this one with no action since we've got various bits for pinging the kernel now.
