### ISSUE TITLE
setting cell output prefs

### ISSUE THREAD

**Issue by rornor** [nteract/archived-desktop-app#1098]
IIRC reduced cell output was introduced recently:
1. Is it possible to set preference so that by default I get expanded view for output cell instead reduced as it currently is
2. Is it possible to remove scrollbar from expanded view, as it is useless in such view?

TIA

**Comment by rgbkrk** [comment]
Yeah, I also wish for expanded by default or at the very least a bigger default collapsed version.

**Comment by rgbkrk** [comment]
The default size for expansion is bigger nowadays. We should probably revisit this one.
