### ISSUE TITLE
Spellcheck in markdown cells

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#1116]
This issue outlines a variety of thoughts on spellchecking in markdown cells in the notebook.

**Problem:** Spellchecking is currently unavailable in CodeMirror because as of CodeMirror version 4.0, CodeMirror elements are not recognized as editable content areas by the browser. As a result, the system spellchecker is not instantiated in those editable elements.

This problem is not unique to the Jupyter ecosystem and is also not unique to the CodeMirror editor.

**Solutions:**
- Implement a spellcheck extension using CodeMirror extensions and a spellcheck library like typo.js.
    - Pros: Can be used by other people in the CodeMirror ecosystem
    - Cons: Lots of maintenance overhead, hard to expand for multiple langagues, will change as CodeMirror API changes
- Use a separate editor for markdown cells
    - Pros: Don't have to worry about CodeMirror shennagins with spellcheck at all
    - Cons: Have to worry about more components being loaded on the page
        - This can be alleviated by rendering some components statically when they are not in use
    - Cons: Will make cross-cell interactions (like shifting cell focus) difficult as context has to be switched between two different types of components

I was initially leaning towards the first option, but really the second option seems more viable at this point. It limits the changes that we would have to make to our codebase only and helps us avoid having to build and maintain another library or tool (despite the fact that it is very much so needed in the CodeMirror ecosystem).

We can think about how to make the cell focus stuff play nicely with this as well since that has been a topic of thought.

**Comment by marijnh** [comment]
[This discussion](https://github.com/ProseMirror/prosemirror/issues/390#issuecomment-256846574) about a similar issue in ProseMirror might be relevant. Conclusion is: there might be hope for making spellcheck work, also in CodeMirror, at least in contentEditable mode, but it'd require an overhaul of the way we update the DOM (it has to become incremental to avoid confusing the browser). So yeah, it's probably not going to happen on the short term.
