### ISSUE TITLE
command line `nteract` just shows splash screen

### ISSUE THREAD

**Issue by desilinguist** [nteract/archived-desktop-app#1132]
When running `nteract foo.ipynb` at the command line, I just get a splash screen and nothing else seems to happen. Running the actual app seems to work fine though.

PS:  This is a fantastic app and I am so happy that someone is working on it. Love the dark theme 👍

**Comment by lgeiger** [comment]
Thanks for the feedback!

Which operating are you on?
Does it open by running just `nteract`?

**Comment by desilinguist** [comment]
I am on macOS 10.12.1. `nteract` by itself also just shows the splash screen and nothing else happens. I also noticed that I get a `zsh` process running at around 100% even after I quit from the splash screen.

**Comment by rgbkrk** [comment]
It sounds like we may be doing things in the shell script that are not fully cross-shell compliant (similar to how [dvm.sh](https://github.com/getcarina/dvm/blob/master/dvm.sh) and [nvm](https://github.com/creationix/nvm) are implemented).

**Comment by rgbkrk** [comment]
@desilinguist can you open the dev tools on the splash screen by running command-shift-i?

**Comment by desilinguist** [comment]
The only option available to me under the `nteract` menu is Quit. Cmd-Shift-i does nothing.

**Comment by lgeiger** [comment]
@desilinguist To eliminate variables, could you try `nteract` from a bash console?

**Comment by lgeiger** [comment]
Does `nteract --verbose` from your `zsh` shell work?

**Comment by desilinguist** [comment]
Just `nteract` on `bash` has the same problem.

`nteract --verbose` works on both `bash` and `zsh`.

**Comment by lgeiger** [comment]
Thanks for your fast reply!

It's definitely failing [here](https://github.com/nteract/nteract/blob/master/bin/nteract.sh#L80-L85). It seems like `nohup` doesn't correctly disconnect the process from the terminal.

@rgbkrk Any idea how to fix this? If everything fails we could spawn nteract from a node process like we do on windows.

**Comment by lgeiger** [comment]
@desilinguist Bare with me (I have no idea why it's not working), could you try if the following commands also fail:
- `nohup nteract --verbose &`
- `nohup nteract --verbose > /dev/null 2>&1 &`

**Comment by desilinguist** [comment]
No bother at all. I can see `nteract` improving my productivity immensely down the line so I am happy to help.

Yes, both of those commands also fail.

**Comment by lgeiger** [comment]
I can reproduce this in my linux VM now which means it's not a OS X specific problem and we can't use `open -a`.

I see this strange behavior: The splash screen stays open until I close the terminal, then nteract opens normally.

**Comment by lgeiger** [comment]
I can't get it to work. At this point (and since we are using a very similar script compared to Atom) I'm unsure if the problem is caused by the shell script or by the splash screen.

**Comment by lgeiger** [comment]
@rgbkrk It's a problem with the splash screen. If I start nteract from a simple node script (without `nohup` #1133 ) I get the following strange behavior.

![nteract](https://cloud.githubusercontent.com/assets/13285808/19948059/19030c44-a14b-11e6-8953-b9c05235b62e.gif)

I also would vote for removing the splash screen all together. I always have the feeling it slows down startup. But that's a general feeling I get also from other apps that use a fancy splash screen.

**Comment by rgbkrk** [comment]
Intriguing.

The splash screen's primary purpose is to deal with the slow startup that occurs when we run our `shell-env` stuff as well as the :soon: to be implemented conda kernel finder. My shell is a bit slow to start, so the splash screen has been good feedback for me. It does run in a separate process and is completely dependent on asychronous events from the requested notebook(s) - it shouldn't affect startup (at least, not much). Timing data could convince me otherwise.

If loading and running the video is straining resources, the user will have more problems with the core notebook as well.

**Comment by rgbkrk** [comment]
I'll be happy to dig into this one next week, I'm not sure I'll have enough time to fully invest in the command line interface in the next couple days.

**Comment by lgeiger** [comment]
That would be great!

**Comment by tylerwince** [comment]
@lgeiger @rgbkrk
Has there been any update on this? I am running the newest release on macOS Sierra w/ zsh and am running into the same problem. I am able to start up nteract within my virtualenv using `nteract --verbose` and then open notebooks from the menu bar as described by @desilinguist. 

Let me know how else I can help.

**Comment by rgbkrk** [comment]
I haven't played much with this, it would be cool if you're able to run from master and help us fix this @tylerwince.

**Comment by tylerwince** [comment]
When I fork the repo and `npm run start` in the repo, everything starts as expected and I am not able to run `nteract` using the master build. Any tips on being able to start nteract using the `nteract` command from master?

**Comment by lgeiger** [comment]
@tylerwince After starting nteract with `npm start` run `Install Shell Commands` from the menu bar (you should find it in one of the submenus). This should initialize the shell commands.

**Comment by tylerwince** [comment]
Thanks @lgeiger... totally forgot I had to do that before when I first installed. 

@rgbkrk, when I install from master I am able to run `nteract` and it starts as expected. In fact, the splash screen doesn't even appear. I am assuming something else that was changed since the last release has fixed this bug also!

**Comment by rgbkrk** [comment]
That's sounding great! Thank you @lgeiger and @tylerwince. Would you say the `nteract` cli is in a good state now for the purposes of this issue?

**Comment by tylerwince** [comment]
It seems to be. 
Granted that when you install from master and run `nteract` it opens up an 'electron' window and not an 'nteract' window as is the case when you install the most recent release. Hopefully that makes sense... Here is a screenshot to help my crappy explanation. 

![screen shot 2017-02-07 at 1 35 14 pm](https://cloud.githubusercontent.com/assets/17678033/22710453/97caca22-ed3a-11e6-8f9c-a8d729e822c1.jpg)

**Comment by rgbkrk** [comment]
Running from master will always show Electron, due to the fact that it's not a packaged release (that happens as part of our `npm run dist` process).

**Comment by tylerwince** [comment]
Right, makes sense. Then I would say this issue is good to be closed.
