### ISSUE TITLE
Strange alignment for indented lines

### ISSUE THREAD

**Issue by desilinguist** [nteract/archived-desktop-app#1137]
I have been using nteract with some of my existing notebooks that I have been working on and I am noticing some strange alignment issues as I am adding (indented) code/comments to a cell. The GIF below shows what I mean. I basically have to re-indent to get the alignment to match up with the code that is already there.

![nteract-comment-bug](https://cloud.githubusercontent.com/assets/161680/19973093/9e1f7ab0-a1ba-11e6-9972-5ab82fe50eac.gif)

**Comment by desilinguist** [comment]
Working with this a bit more, I now get the error:

```
TabError: inconsistent use of tabs and spaces in indentation
```

However, if I retype the code in that cell in a new cell in nteract, there's no issue. So, I think there's some problem  with opening existing notebooks that were originally _not_ created in nteract.

**Comment by desilinguist** [comment]
One last update. It looks like nteract does not properly convert tabs to spaces? Here's what a cell with re-indented code looks like in Jupyter notebook:

<img width="900" alt="screen shot 2016-11-04 at 9 34 27 am" src="https://cloud.githubusercontent.com/assets/161680/20007320/0a25696a-a272-11e6-8abb-06619492c7cf.png">

**Comment by rgbkrk** [comment]
Interesting. Sounds like I should be able to reproduce this with a notebook created in Jupyter that uses tabs instead of spaces?

**Comment by rgbkrk** [comment]
I _think_ this issue was fixed by @mpacer with a recent `<Editor />` refactor. I'd love to see if that's the case.

**Comment by rgbkrk** [comment]
This has been fixed, let us know if it's still an issue!
