### ISSUE TITLE
Support Command-/ for toggling comments

### ISSUE THREAD

**Issue by desilinguist** [nteract/archived-desktop-app#1140]
It would be really cool if nteract also supported this keyboard shortcut like Jupyter notebook does.

PS: I am sorry for filing so many issues but now that I've switched to using `nteract` as my daily notebook app, I'm finding avenues for improvement. I also hope to contribute actual code for small-ish issues like this one once I have had a chance to familiarize myself with the codebase.

**Comment by rgbkrk** [comment]
Thank you!

Please keep filing issues, we want to build a really solid experience out of the box. This feedback helps.
