### ISSUE TITLE
outputExpanded should not be in the top-level cell data

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1148]
Right now it's appearing as a sibling of `outputs`, `cell_type`, etc. when it should be under `metadata`. This is making our notebooks no longer conformed to nbformat.

**Comment by jdetle** [comment]
This definitely pertains to issues discussed in #1102.

**Comment by rgbkrk** [comment]
Two takeaways here:
1. put `outputExpanded` within a cell's metadata (note: there's already a `collapsed` flag in use across jupyter within the cell metadata)
2. introduce conformance tests by creating a notebook through nteract, possibly running through a series of actions

**Comment by captainsafia** [comment]
Similarly, we should also move `outputHidden` and `inputHidden` to metadata. I thought there was an issue open for this from a while back but it looks like this is not the case.

This would also make it much easier to clean up the notebook JSON when it is saved to an ipynb.

**Comment by captainsafia** [comment]
Also, do we wanna submit a proposal upstream to nbformat to provide more flexibility in what options can be set in the metadata field? We do run the risk of turning it into an unregulated zone for metadata but it might help to provide options beyond `scrolled` and `collapsed`.

**Comment by rgbkrk** [comment]
Last time we asked about picking some fields, @takluyver said that it was entirely the point of metadata.

What we really need to outline carefully as a project is whether something is:
- Transient (at runtime)
- Persisted (in the notebook document)

As we explore multi-user collaboration, we also need to concern ourselves with what is local transient state for that user. For now, we can largely divide between transient and persisted and learn what works with multi over time.

**Comment by captainsafia** [comment]
Nice! This would be a good thing to discuss during this week's dev meeting. Mind bringing it up and reporting back any discussions/decisions made?

**Comment by rgbkrk** [comment]
Sure.
