### ISSUE TITLE
Markdown numbering across multiple cells

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1164]
Consider the following two markdown cells:
Cell 1: `1. First Item`
Cell 2: `2. Second Item`

nteract will show:
![bildschirmfoto 2016-11-10 um 22 37 07](https://cloud.githubusercontent.com/assets/13285808/20195587/7a12cae0-a797-11e6-9d4d-990643a3714f.png)
jupyter doesn't handle this either (it shows the wrong numbering):
![bildschirmfoto 2016-11-10 um 22 38 59](https://cloud.githubusercontent.com/assets/13285808/20195608/89a30c90-a797-11e6-9e52-90854d0617e3.png)

**Comment by rgbkrk** [comment]
That's the "right" numbering since it's broken up by a cell block in between. As for the lack of numbers when there is only one element, that comes from some CSS for when there is only one item. Perhaps we should only enable that for `ul li` instead of across all `li`.

**Comment by rgbkrk** [comment]
Closing since we show the numbering now and since these are different markdown contexts they can't continue between code cells.
