### ISSUE TITLE
File save indicator is backwards

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1165]
Take a look at the red close button:
![nteract](https://cloud.githubusercontent.com/assets/13285808/20195931/bc07fcc6-a798-11e6-869e-e44c9a65b75c.gif)

**Comment by jdetle** [comment]
Hey @lgeiger did some things get cut off in this gif?

**Comment by lgeiger** [comment]
Only the saving and kernel restart dialogs are cut off.
The save notifications are also correct. I triggered them with `cmd-s`.

**Comment by rgbkrk** [comment]
Fixed in #1204.
