### ISSUE TITLE
Add One-Dark theme

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1166]
I love Atom's default UI theme and syntax coloring.
It would be great to have this theme.

Here are the color values:
https://github.com/atom/one-dark-ui
https://github.com/atom/one-dark-syntax/blob/master/styles/colors.less

**Comment by souravsingh** [comment]
@lgeiger I would like to work on the issue. How do I start?

**Comment by lgeiger** [comment]
Hey that's great! :tada:

I would start with a copy of the default or dark theme in nteract and modify the color values.

Feel free to ask here or on slack if you need more help!

**Comment by alexandercbooth** [comment]
Awesome, @souravsingh!

In addition to what @lgeiger said, some logistical things to keep in mind: you will want to follow the contributor guidelines [here](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md). 

And once you have it you can add it to the [menu](https://github.com/nteract/nteract/blob/master/src/main/menu.js) with something like:

``` jsx
  {
    label: 'One-Dark',
    click: createSender('menu:theme', 'one-dark'),
  },
```

Something to potentially keep in mind: I think the syntax highlighting from CodeMirror isn't necessarily as advanced as what you might see in something like Atom (I am thinking anecdotally/specifically of Python syntax and the variables/built-ins/keywords). Someone correct me if I am wrong here 😉. 

Could also possibly be a good opportunity for a PR over in [CodeMirror](https://github.com/codemirror/CodeMirror).

Once you finish, you will want to check for linting errors with: 

``` bash
./node_modules/.bin/eslint <Name-of-File-Changed>
```

and confirm that tests still pass with:

``` bash
npm run test
```

**Comment by rgbkrk** [comment]
I think this one is definitely open for implementing still. 😉

**Comment by Madhu94** [comment]
@lgeiger @alexandercbooth 

I started with nteract's dark theme and changed the the main-bg-color and main-fg-color to Atom's syntax-bg-color and syntax-fg-color -

```
--main-bg-color: #282C34;  
--main-fg-color: #abb2bf;
```
![image](https://user-images.githubusercontent.com/9015820/27518570-bc33a7fc-5a00-11e7-9d4c-aaa7377b13bc.png)

A shot of the nteract dark theme (a little hard to tell the difference right now) -
![image](https://user-images.githubusercontent.com/9015820/27518834-3ea5a186-5a06-11e7-9e68-42edb9b4fb78.png)

As for the rest of the colors we use - there seem to be no equivalent atom color values. Especially the values used by codemirror - for builtins, comments, defs, etc. What colors should I use for these ?

**Comment by rgbkrk** [comment]
Atom must be doing _something_ similar we can swap builtins etc. for. I'm not sure how the Atom stylesheets work though.

**Comment by Madhu94** [comment]
True - I'll figure it out from Atom's devtools then.

**Comment by lgeiger** [comment]
The colors are defined here: https://github.com/atom/one-dark-syntax/blob/master/styles/syntax-variables.less

**Comment by Madhu94** [comment]
Closing in favor of #1756
