### ISSUE TITLE
tab behavior when editing markdown cells

### ISSUE THREAD

**Issue by ivanov** [nteract/archived-desktop-app#1170]
When editing markdown, pressing a tab inserts spacing only in the rendered version, not the editor.

<img width="407" alt="screen shot 2016-11-10 at 3 25 27 pm" src="https://cloud.githubusercontent.com/assets/118211/20198585/3ef61e68-a75a-11e6-8e37-db29a0d5bab5.png">

**Comment by rgbkrk** [comment]
This is confirmed fixed on master.
