### ISSUE TITLE
Docs - Potentially add testing to contributor guide.

### ISSUE THREAD

**Issue by alexandercbooth** [nteract/archived-desktop-app#1181]
I noticed in the contributor guide, there is no mention of style testing with eslint or unit testing before submitting a PR. Is this something we want to consider adding to CONTRIBUTING.md or something preferable to continue letting CI handle and debugging after the fact?

As a new contributor, it was beneficial for me to run these things locally, but I recognize that may not be universal.

Thanks!

**Comment by alexandercbooth** [comment]
To be clear, I am not suggesting changing anything with CI, just also running these things locally to expedite PRs.

**Comment by rgbkrk** [comment]
I'm all for adding linting to the default npm run test setup!

**Comment by rgbkrk** [comment]
Oh you're saying adding some text to the contributing guide - also super cool

**Comment by alexandercbooth** [comment]
Ooh good idea, I hadn't considered adding it to default testing. Do you think something like something like this might be appropriate?

``` node
    "posttest": "npm run lint",
```

> Oh you're saying adding some text to the contributing guide - also super cool

Nice, I can add an extra step to npm run test after #5 in contributing.md

**Comment by rgbkrk** [comment]
Well, we want it to fail locally when it doesn't pass linting so we'd want:

``` json
  "test": "npm run test:unit && npm run test:lint",
```

**Comment by alexandercbooth** [comment]
Ahh good catch. Thanks Kyle!
