### ISSUE TITLE
npm install fail on zmq

### ISSUE THREAD

**Issue by Xogle** [nteract/archived-desktop-app#1189]
npm install is erroring on zmq dependency

I am running on Mac OSX Yosemite with Python 2, Node 6.9.1, and npm 3.10.8

Here is the beautiful error,
![screen shot 2016-11-14 at 17 24 45](https://cloud.githubusercontent.com/assets/6294118/20285337/48ee6096-aa8f-11e6-8da4-90393c29b5a6.png)

**Comment by willingc** [comment]
@lgeiger I ran into the same error. Discussion with @jdetle in the Slack channel. Ping me if you need info or want me to test anything. Thanks!

**Comment by lgeiger** [comment]
It looks like it's having issues because the path contains a space. I'll investigate.

**Comment by willingc** [comment]
@lgeiger Here's a pastebin of the errors I received on a fresh clone: http://pastebin.com/eN1nR3Fj

Also debug.log: http://pastebin.com/Y7i0km7U

**Comment by lgeiger** [comment]
@willingc This looks like a different error. It doesn't find your C compiler. 

Maybe there is something wrong with the xcode compilers. Could you run `xcode-select --install` and try it again?

**Comment by willingc** [comment]
@lgeiger Tried that earlier, but happy to try again ;-)

**Comment by willingc** [comment]
:-(

```
[18:55:00]$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

More info:

```
[21:30:00]$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(testact2) carol at Carols-MBP-2 in ~/code/experiments/nteract on master*
[21:30:06]$ gcc --version
gcc (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by lgeiger** [comment]
Hmm I get the same message.

Do you get a error if you run `gcc --version`?

**Comment by willingc** [comment]
Nope.

**Comment by willingc** [comment]
So I'm running in a conda environment with Python 2. Let me install python 2 from python.org and see if that solves it if I run without a virtualenv or conda env.

**Comment by lgeiger** [comment]
> So I'm running in a conda environment with Python 2. Let me install python 2 from python.org and see if that solves it if I run without a virtualenv or conda env.

I'm afraid this won't help since it fails while building libzmq.

**Comment by lgeiger** [comment]
That's interesting. You have a different `gcc` version installed. This may cause the problem.

I'm getting:

```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
lukasgeiger at LG-MacBook in ~/code/zmq prebuilt on master*
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
