### ISSUE TITLE
React render failures should not be silent

### ISSUE THREAD

**Issue by jdfreder** [nteract/archived-desktop-app#119]
While implementing cells by uuid I got to a point where the page was rendering blank and there were no error in the console.  It turns out one of the react components was failing to render.  Unfortunately this failure was logged no where.  We need to make sure asynchronous errors get logged and we will need to come up with a really good story for when we decide nteract should be able to render components from user extensions (maybe even rendering errors to the screen).

The last segment of this read, provided by @rgbkrk , is relevant: https://nylas.com/blog/react-plugins

cc @kenwheeler

**Comment by rgbkrk** [comment]
:+1:

**Comment by rgbkrk** [comment]
Since we have the main catch in index.html now, as well as the provider component from Redux I think we're in good shape here. Closing.
