### ISSUE TITLE
Cell never seems to execute

### ISSUE THREAD

**Issue by michaelaye** [nteract/archived-desktop-app#1190]
Trying out 0.0.14, loaded two example notebooks, both Shift-Enter and clicking the "Play" icon does not seem to execute the cell, at least with my Jupyter-based expectation that the asterisk should change to a number, when the cell has been executed.
The first cell with `import pandas as pd, requests, json` just stays with an asterisk.

Trying this on a 10.11.6 system, all updates.

**Comment by jdetle** [comment]
Hi @michaelaye, it sounds like a kernel isn't being started and connected to. How have you installed your python kernel?

**Comment by rgbkrk** [comment]
@michaelaye Couple things to run for diagnostics -- at a terminal run

```
jupyter kernelspec list
```

As well as

```
ls ~/Library/Jupyter/kernels/
```

Thanks for trying nteract out!

**Comment by carsonfarmer** [comment]
I'm having the same issue with `R` and `Javascript` kernels, but both Python kernels work fine:

```bash
jupyter kernelspec list
```
```bass
Available kernels:
  ir            /Users/carsonfarmer/Library/Jupyter/kernels/ir
  javascript    /Users/carsonfarmer/Library/Jupyter/kernels/javascript
  python3       /Users/carsonfarmer/Library/Jupyter/kernels/python3
  python2       /usr/local/share/jupyter/kernels/python2
```
And ideas?

**Comment by Fil** [comment]
I have only 
```
Available kernels:
  python2    /Users/fil/Library/Jupyter/kernels/python2
```

and it's not even working for some examples (e.g. download-stats.ipynb). It shows a red error with `"Kernel not connected!"`
Not sure what to do or where to look

**Comment by rgbkrk** [comment]
@carsonfarmer I am absolutely stunned that Python works and the others are running into problems. Usually it's the other way around.

What do the kernelspecs look like for your ir and javascript kernels? One reason we won't be able to launch is if the executables are not on the `PATH`.

**Comment by carsonfarmer** [comment]
@rgbkrk I'm guessing you want my JSON output?

```json
{
  "kernelspecs": {
    "javascript": {
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/javascript",
      "spec": {
        "language": "javascript",
        "argv": [
          "/usr/local/Cellar/node/6.6.0/bin/node",
          "/usr/local/lib/node_modules/ijavascript/lib/kernel.js",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "display_name": "Javascript (Node.js)",
        "env": {}
      }
    },
    "python3": {
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/python3",
      "spec": {
        "language": "python",
        "argv": [
          "/usr/local/opt/python3/bin/python3.5",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "display_name": "Python 3",
        "env": {}
      }
    },
    "python2": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python2",
      "spec": {
        "language": "python",
        "argv": [
          "/usr/local/opt/python/bin/python2.7",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "display_name": "Python 2",
        "env": {}
      }
    },
    "ir": {
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/ir",
      "spec": {
        "language": "R",
        "argv": [
          "/Library/Frameworks/R.framework/Resources/bin/R",
          "--slave",
          "-e",
          "IRkernel::main()",
          "--args",
          "{connection_file}"
        ],
        "display_name": "R",
        "env": {}
      }
    }
  }
}
```

For what it's worth, all kernels work fine via Hydrogen within Atom.

**Comment by rgbkrk** [comment]
Sorry I had not looked at this again, got caught up with some other things. How are things now? How do they behave in the jupyter notebook? Are you on master or the latest release?

We'll be getting out a release on Wednesday that is far more stable than any previous release, still more to finish up for our beta.

**Comment by carsonfarmer** [comment]
Thanks for the reply @rgbkrk. Still having trouble on above listed machine. Interestingly, another (work) machine with the following kernelspec (and `nteract` version 0.0.13) works fine.

> How do they behave in the jupyter notebook?

Things work fine in a notebook, and in Atom via Hydrogen

> Are you on master or the latest release?

I've just upgraded to current pre-release (0.0.15) and am still having the same issues.

Working machine kernelspec:
```bash
{
  "kernelspecs": {
    "javascript": {
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/javascript",
      "spec": {
        "display_name": "Javascript (Node.js)",
        "env": {},
        "argv": [
          "/usr/local/Cellar/node/6.5.0/bin/node",
          "/usr/local/lib/node_modules/ijavascript/lib/kernel.js",
          "{connection_file}",
          "--protocol=5.0"
        ],
        "language": "javascript"
      }
    },
    "python3": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python3",
      "spec": {
        "display_name": "Python 3",
        "env": {},
        "argv": [
          "/usr/local/opt/python3/bin/python3.5",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "language": "python"
      }
    }
  }
}
```

**Comment by carsonfarmer** [comment]
I seem to have solved this issue by reinstalling the kernels and re-registering them all. The only one that is still not behaving is the `R` kernel. See kernel-spec below. It looks like `R` is installed as a framework, which is perhaps why it is not being found by nteract?

```bash
{
  "kernelspecs": {
    "javascript": {
      "spec": {
        "env": {},
        "language": "javascript",
        "display_name": "Javascript (Node.js)",
        "argv": [
          "/usr/local/Cellar/node/6.6.0/bin/node",
          "/usr/local/lib/node_modules/ijavascript/lib/kernel.js",
          "{connection_file}",
          "--protocol=5.0"
        ]
      },
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/javascript"
    },
    "python2": {
      "spec": {
        "env": {},
        "language": "python",
        "display_name": "Python 2",
        "argv": [
          "/usr/local/opt/python/bin/python2.7",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      },
      "resource_dir": "/usr/local/share/jupyter/kernels/python2"
    },
    "python3": {
      "spec": {
        "env": {},
        "language": "python",
        "display_name": "Python 3",
        "argv": [
          "/usr/local/opt/python3/bin/python3.5",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      },
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/python3"
    },
    "ir": {
      "spec": {
        "env": {},
        "language": "R",
        "display_name": "R",
        "argv": [
          "/Library/Frameworks/R.framework/Resources/bin/R",
          "--slave",
          "-e",
          "IRkernel::main()",
          "--args",
          "{connection_file}"
        ]
      },
      "resource_dir": "/Users/carsonfarmer/Library/Jupyter/kernels/ir"
    }
  }
}
```

**Comment by jdetle** [comment]
Pinging @rgbkrk, if you can confirm @carsonfarmer's question I think we can close this?

**Comment by rgbkrk** [comment]
Seems like a fine spec to me, I can't tell why it's not working right in nteract. We need additional diagnostics on kernel error within our UI to make this easier to debug remotely.

**Comment by dawood95** [comment]
Try installing the kernel without `--user` option. It fixed the problem for me with a global ipykernel install.

**Comment by carsonfarmer** [comment]
That did it @dawood95! Thanks a million. Finally have all my kernels working perfectly in nteract!
For reference, I followed the install instructions [here for IRkernel](https://irkernel.github.io/installation/), and in particular, used:

```r
IRkernel::installspec(user = FALSE)
```
to install system-wide (same as installing without `--user` option when installing ipykernel).

**Comment by clouds56** [comment]
Same issue for python kernel,

> Available kernels:
  gophernotes    /Users/clouds/Library/Jupyter/kernels/gophernotes
  ir             /Users/clouds/Library/Jupyter/kernels/ir
  python3        /usr/local/share/jupyter/kernels/python3

when I try to run a cell it shows asterisk before the cell (indicating running) and no output, while status bar shows that "Python 3 | Idle".
I think the kernel should be successfully connected since it shows "Kernel Python 3 has been restarted" when I tried to restart kernel.

Any ideas?

FYI, I have my python3 kernel installed as `pip3 install jupyter ipython`, without `--user` for `pip3` parameters.

**Comment by clouds56** [comment]
it's 0.4.3 now but still not resolved on mac.

the built-in "node.js (nteract)" kernel runs well while system-wide python3 kernel fails.

**Comment by apuignav** [comment]
Same here with 0.7.1, screenshot below:

![screen shot 2018-02-19 at 08 26 13](https://user-images.githubusercontent.com/688368/36366482-9eaafd20-154e-11e8-900c-727176011542.png)

The built-in "node.js" works well.

On the other hand:

```shell
[8:24]~$ jupyter kernelspec list

Available kernels:
  python2    /usr/local/share/jupyter/kernels/python2
  python3    /usr/local/share/jupyter/kernels/python3
[8:24]~$ ls ~/Library/Jupyter/kernels/
ls: /Users/albert/Library/Jupyter/kernels/: No such file or directory
```

And `ipykernel` is up to date. Can I do anything to help debug this?

**Comment by apuignav** [comment]
It seems to have been solved in new versions, at least in my case.

**Comment by clouds56** [comment]
I'm on macOS and modify `python` in `argv` in `/usr/local/share/jupyter/kernels/python3/kernel.json` to `python3` solved this for me.

> {
 "argv": [
  "**python3**",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
