### ISSUE TITLE
Live markdown rendering change in user experience

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1215]
@scottdraves brought up that the beaker notebook live renders markdown inline, this is probably a better way of handling markdown, especially for large markdown cells. 

Creating this issue as a discussion area for improvements to the user experience.

**Comment by rgbkrk** [comment]
As a WYSIWYG editor like with [Draft.js](https://facebook.github.io/draft-js/) or how it renders when unfocused in Beaker?

While editing:

<img width="578" alt="screen shot 2016-11-19 at 1 02 29 am" src="https://cloud.githubusercontent.com/assets/836375/20453455/ec391298-adf3-11e6-9714-61dfcca44dba.png">

When editor unfocused:

<img width="576" alt="screen shot 2016-11-19 at 1 02 36 am" src="https://cloud.githubusercontent.com/assets/836375/20453456/ed9c16c6-adf3-11e6-8ce7-dc6c4b3d3f07.png">

**Comment by captainsafia** [comment]
This would tie in nicely with the spellcheck issue as well. As for editing inline, I believe he means the way that styling is added to certain elements when you are editing. For example, the italics and bolding are done here while I edit, although not rendered.

<img width="648" alt="screen shot 2016-11-28 at 1 14 11 pm" src="https://cloud.githubusercontent.com/assets/1857993/20682190/9fb2c5e2-b56c-11e6-814f-6823ff4c00a6.png">

Just kidding, CodeMirror already does this so I'm back to not knowing what this means.

**Comment by rgbkrk** [comment]
Yeah I'm unsure too. @jdetle - can you provide more context?
