### ISSUE TITLE
Merge cell icon unintuitive, action not always apparent.

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1216]
Showing the notebook off, we realized that the up arrow isn't really obvious for what it is doing, which is to merge the cell below into the cell above. I am opening this issue to discuss how to go about fixing the cell creator button to make it more first time user friendly.

**Comment by rgbkrk** [comment]
I totally agree. It's tempting to take it out until we have something sensible.

If we had multiselect of cells (again), I could imagine the cell toolbar having a "merge cells" option. No other ideas from me there.

**Comment by rgbkrk** [comment]
I'm still in favor of deleting this button entirely. 😅 

Want to tackle it @jdetle?

**Comment by jdetle** [comment]
Yes, I'll open a pr.

**Comment by jdfreder** [comment]
Sure!
