### ISSUE TITLE
No ability to stop cell code execution

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1221]
I was running code today that goes into an infinite event loop. I noticed there is no way to stop the cell execution like 'ctrl+c' or cell > stop execution.

When I tried to kill the kernel there is no response
When I try to restart kernel it displays `kernel null has been restarted`
The code continues to execute, I had to close nteract entirely.

**Comment by rgbkrk** [comment]
Just to clarify - it sounds like the discovery of the interrupt was hindered by the fact that kernel operations are under "Language". Then, beyond that, interrupt wasn't performing a true interrupt (and not providing much feedback).

**Comment by rgbkrk** [comment]
Now that I've had more experience with other notebook UIs, we should incorporate a `Cancel` button for when work is in progress or queued up.

**Comment by rgbkrk** [comment]
[Cancellable execution from the Spark Roadmap in Jupyter](https://github.com/jupyter/roadmap/blob/46d4b808b6d2e548cbbb3907e0169bca25f7f616/spark.md#cancellable-execution)

**Comment by yutaoliu** [comment]
I tried converting the busy cell to markdown by pressing `m` which effectively stops execution for that particular cell.

**Comment by rgbkrk** [comment]
> I tried converting the busy cell to markdown by pressing m which effectively stops execution for that particular cell.

Neat! Yeah we actually do have logic for stopping listening to messages for a cell when the cell type is changed.

At least as a mockup, I'd like to see what a `cancel` field would look like as well as a little hokey barbershop progress bar.

**Comment by h-vetinari** [comment]
> [...] as well as a little hokey barbershop progress bar.

I'm guessing you're aware of `tqdm`? https://github.com/tqdm/tqdm#ipythonjupyter-integration
Might be a good start. :)

**Comment by captainsafia** [comment]
@fabric-8 Another bit of design feedback. Users would like to be able to cancel the execution of a cell that is already being run.
