### ISSUE TITLE
Non-ASCII characters in USER_GUIDE.md not rendered correctly

### ISSUE THREAD

**Issue by gvwilson** [nteract/archived-desktop-app#1226]
Several quoted (gray) boxes in <https://github.com/nteract/nteract/blob/master/USER_GUIDE.md> contain non-ASCII characters that are rendered incorrectly, e.g.:
![screen shot 2016-11-21 at 1 58 13 pm](https://cloud.githubusercontent.com/assets/911566/20496373/e42fc816-aff2-11e6-8a9c-9e23081fc9a9.png)
These characters do not render correctly when viewing the raw source of the page at <https://raw.githubusercontent.com/nteract/nteract/master/USER_GUIDE.md> either.

**Comment by rgbkrk** [comment]
Thanks for reporting!

We can switch those to literal `->`, they're currently some unicode character that renders well on my Mac and Windows machines.

<img width="537" alt="screen shot 2016-11-21 at 11 21 45 am" src="https://cloud.githubusercontent.com/assets/836375/20497117/cba8b476-afdc-11e6-8baf-8d812e1cdd67.png">
