### ISSUE TITLE
Feature request: launch or prescribe update from within application

### ISSUE THREAD

**Issue by gvwilson** [nteract/archived-desktop-app#1227]
It would be really helpful if I could run nteract and have it inspect my system and tell me things like, "You don't appear to have kernels installed, here are the commands you need to run and how to run them."

**Comment by jdetle** [comment]
Yes it would! This is totally something on my todo list. The current idea would be to have some sort of setup where we could go to `help > diagnostics` and have a set of scripts ready to be ran for all sorts of common issues. In addition, the ability to post an issue to github from the desktop app if these common issue fixes don't help would be desirable. I'd love to hear your thoughts on how to best approach this problem @gvwilson!

**Comment by gvwilson** [comment]
This sounds like a job for [theme music] @wking - Trevor, any ideas on 
how best to do something like this?

**Comment by wking** [comment]
> It would be really helpful if I could run nteract and have it
> inspect my system and tell me things like, "You don't appear to have
> kernels installed, here are the commands you need to run and how to
> run them."

This is pretty much what the SWC installation scripts are [1](https://github.com/wking/swc-setup-installation-test),
although they handle “here are the command you need to run and how to
run them” by linking out to external docs [2](https://github.com/wking/swc-setup-installation-test/blob/a80817141f43d966be748c32f046bcfdfc5c4ee8/swc-installation-test-2.py#L145).

Whether that approach is feasible depends on how many packages you
need to support and how consistently you can test for them.  Testing a
hundred commands where you can use ‘$COMMAND --version’ is a lot
easier to maintain than testing 10 commands where you need per-command
hoop-jumping [3](https://github.com/wking/swc-setup-installation-test/blob/a80817141f43d966be748c32f046bcfdfc5c4ee8/swc-installation-test-2.py#L626).

I'm not sure enough about notebook kernels to know how to check them,
but I expect they'd give you a fairly consistent way to check their
existence/functionality.

**Comment by rgbkrk** [comment]
I so want a nice way for us to do this.
