### ISSUE TITLE
Offline Plotly graphs not displaying

### ISSUE THREAD

**Issue by OliverEvans96** [nteract/archived-desktop-app#1229]
The following code produces the expected output using the Jupyter Notebook, but only generates a blank output in nteract.

```
import plotly.offline as py
import plotly.graph_objs as go

# Create random data with numpy
import numpy as np

py.init_notebook_mode()

N = 500
x = np.linspace(0, 1, N)
y = np.sin(2*np.pi*x)

# Create a trace
trace = go.Scatter(
    x = x,
    y = y
)

data = [trace]

# Plot and embed in ipython notebook!
py.iplot(data)
```
Jupyter:
![image](https://cloud.githubusercontent.com/assets/15915043/20500160/59ad644a-b002-11e6-92bd-2bf0fe973c2b.png)

nteract:

![image](https://cloud.githubusercontent.com/assets/15915043/20500096/24d777ce-b002-11e6-8dfa-950f2726adf3.png)

I get the following errors from the DevTools console in nteract:
```
Installing React DevTools from /home/oliver/nteract/node_modules/electron-react-devtools
Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/home/oliver/nteract/node_modules/electron/dist/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/home/oliver/nteract/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:315:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/home/oliver/nteract/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
Uncaught ReferenceError: define is not defined
Uncaught AssertionError: path must be a string
```

I think probably the last two lines are the relevant ones.

I'm currently running this all via up-to-date ArchLinux.
Let me know if I should provide any more information.

Thanks!
Oliver

**Comment by rgbkrk** [comment]
We don't support the jupyter notebook's reliance on requirejs / `define` (AMD). We do have support for plotly embedded directly with an `application/vnd.plotly.v1+json` mimetype. An initial version of this is in https://github.com/plotly/plotly.py/pull/562 and needs to be revisited.

/cc @chriddyp - do you have cycles to finish up the plotly.py support?

In the meantime, here's a function that will work with plotly data and layout objects:

```python
import IPython
import plotly
import json

def plotize(data, layout=None):
  """Plot with Plotly.js using the Plotly JSON Chart Schema
  
  http://help.plot.ly/json-chart-schema/
  """
  if layout is None:
    layout = {}
  
  redata = json.loads(json.dumps(data, cls=plotly.utils.PlotlyJSONEncoder))
  relayout = json.loads(json.dumps(layout, cls=plotly.utils.PlotlyJSONEncoder))
  
  bundle = {}
  bundle['application/vnd.plotly.v1+json'] = {
  	'data': redata,
    'layout': relayout,
  }
  
  IPython.display.display(bundle, raw=True)
```

This is available as an example notebook in `File -> Open Example Notebooks -> Plotly`, at least on master (new release likely tonight!).

**Comment by rgbkrk** [comment]
Closing since this has been implemented in plotly.py.
