### ISSUE TITLE
Refactor tests to use builtin machinery of redux-observable. 

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1230]
In my lack of understanding of some of the builtin methods of redux-observable, I missed some opportunities to write cleaner tests.

In tests where I create a stream of observables (various epic tests), there are two lines that can be expressed in one:
```javascript
const input$ = Observable.of({type: 'ACTION', id: 'id_here'});
const action$ = new ActionsObservable(input$);
```
can be rewritten into:
```javascript
const action$ = ActionsObservable.of({type: 'ACTION'})
```
or 
```javascript
const action$ = ActionsObservable.from([{type: 'ACTION'} , { type: 'SECOND_ACTION' }]);
```

in addition, we may want to refactor some of the observable tests to remove the action buffer by converting the output of the epic to an array like so:
```javascript
  executeCellEpic(action$, store)
    .toArray()
    .subscribe(actions => {
      expect(actions).to.deep.equal([
        kernelNotConnected() // whatever action creators
      ]);
      done();
    });
});
```

If anyone who is new to rxjs, redux, or redux-observable would like to tackle this I am willing to provide mentorship and help with any testing issues.

**Comment by rgbkrk** [comment]
Neat, seems like some simple fixes.

**Comment by mstewart141** [comment]
I'd be willing to give this a shot @jdetle . I am:

(1) a new contributor
(2) definitely appreciative of advice/pointers/mentoring
(3) actually a data scientist not an eng/dev, but I know *some* rxjs and would like to learn more

Figure it can't hurt to give it a try!

**Comment by jdetle** [comment]
Awesome, writing tests have helped me tremendously in understanding the
nteract codebase. Good luck and don't hesitate to reach out to me on slack
if you need help.

**Comment by Madhu94** [comment]
@rgbkrk This one can be closed I guess?

@mstewart141 Congrats on your first PR!

**Comment by rgbkrk** [comment]
Yeah I suppose it can, can't believe I missed it. It's also ok if you want to close issues you think are done @Madhu94. I'll grab it now. :smile:
