### ISSUE TITLE
Render codemirror statically when not focused

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1235]
Within JupyterLab, @blink1073 did this with the combo of:

* https://github.com/jupyterlab/jupyterlab/pull/1123
* https://github.com/jupyterlab/jupyterlab/pull/1158

Would be really cool for us to do that here as well.

**Comment by blink1073** [comment]
This turned out to be a bad idea if you want to preserve line numbers or any other kind of gutters, so we instead used the `resize` and `refresh` methods more judicously.  cf https://github.com/codemirror/CodeMirror/issues/3364

**Comment by rgbkrk** [comment]
Awwwww.

**Comment by blink1073** [comment]
😿

**Comment by captainsafia** [comment]
Thanks for letting us know, @blink1073! I'll take a look at the resize/refresh approach.

Closing this.

**Comment by blink1073** [comment]
So much fun!  Here's the gist: https://github.com/jupyterlab/jupyterlab/pull/1158#issue-185244010.
