### ISSUE TITLE
Support SVG output

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1237]
I just realized nteract doesn't support SVG output. We should change that!

[Here](https://github.com/nteract/transformime/blob/master/src/svg.transform.js) is the implementation by @n-riesco for Hydrogen using the native DOM.

**Comment by rgbkrk** [comment]
👍 

Another way to do it, since we have a modern browser is to use a DOMParser:

```js
const domParser = new DOMParser()
const doc = domParser.parseFromString(`<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>`, 'image/svg+xml')
```

That doc is a document fragment that can be added to the DOM wherever needed.

**Comment by Fil** [comment]
I wanted to try a [d3-geo](https://github.com/d3/d3-geo/) map with ipynb, and managed to create one with jupyter notebook + IJavaScript, using the notation `$$svg$$ = '<svg>…………</svg>';`

Looking forward to be able run it with nteract.

<del>[Map of the US.ipynb.zip]</del>

**Comment by Fil** [comment]
hello @captainsafia how do you summon those powers?

**Comment by rgbkrk** [comment]
I wanted to tackle a smaller issue than my other PRs, so after seeing your comment I went for fixing this @fil. :smile:

**Comment by captainsafia** [comment]
@rgbkrk implemented an SVG renderer in #1369. To utilize it you will need to create a notebook with the following code.

```
import IPython
svg_string = """
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
"""
IPython.display.display({'image/svg+xml': svg_string}, raw=True)
```

Let me know if that helps!

**Comment by rgbkrk** [comment]
We'll certainly be including this in the next release too, amongst other features and stability improvements.

**Comment by Fil** [comment]
This is the IPython syntax, but my example is this d3-geo IJavascript notebook — does the `$$svg$$ = xxx` syntax work?

I'm sorry it seems I can't build nteract from source at this point (npm i stays stuck at `electron@1.4.15 postinstall`).… never mind, I'll wait

**Comment by Fil** [comment]
and… waiting was the solution :)  Electron finally built and ta-da!!  `$$svg$$ = ` works.

![capture d ecran 2017-01-25 21 32 54](https://cloud.githubusercontent.com/assets/7001/22308121/f4f91504-e345-11e6-989e-f38cf01345ba.png)

**Comment by n-riesco** [comment]
@Fil I think [this notebook](https://github.com/n-riesco/ijavascript/blob/dev/doc/custom.ipynb) may be useful to you. It demonstrates the new functionality in IJavascript to customise outputs.

**Comment by Fil** [comment]
I've updated the notebook with async `$$.svg()` and put it up on https://nbviewer.jupyter.org/gist/Fil/efb1c9f3f0a9092c420dfe4cef8def96

Thank you! Looking forward for more D3 notebooks :)

**Comment by Fil** [comment]
Very exciting, thanks! Here's a solution to use D3 with jsdom.
https://nbviewer.jupyter.org/gist/Fil/aec6cbf62f9b71c3407db87d5eb592e7

**Comment by n-riesco** [comment]
@Fil Thanks for sharing the solution using `jsdom`. I have a section for IJavascript tutorials [here](http://n-riesco.github.io/ijavascript/). I'd welcome a PR to add your notebook.

**Comment by dpo** [comment]
Hi. I'm trying out nteract and it seems like a great project! I've been trying to produce a SVG plot using the Julia package [TikzGraphs.jl](https://github.com/sisl/TikzGraphs.jl). Unfortunately, instead of the SVG plot, I receive a description of the underlying Julia object. I'm using the first example here: http://nbviewer.jupyter.org/github/sisl/TikzGraphs.jl/blob/master/doc/TikzGraphs.ipynb

Here's what I get in nteract:

![screen shot 2017-01-29 at 19 39 34](https://cloud.githubusercontent.com/assets/38760/22409633/097fe4d6-e65b-11e6-9e71-a570966fd29a.png)

The same example works fine in a Jupyter notebook. Any ideas?

**Comment by rgbkrk** [comment]
This is fixed in master and has not been released yet. :soon:

**Comment by rgbkrk** [comment]
We've now made a release, go grab it at https://github.com/nteract/nteract/releases!

**Comment by dpo** [comment]
Many thanks!
