### ISSUE TITLE
tab behavior should match autoindent

### ISSUE THREAD

**Issue by thomasballinger** [nteract/archived-desktop-app#1238]
![out](https://cloud.githubusercontent.com/assets/458879/20551470/82b9bd5e-b0f5-11e6-93e1-8bbf35769315.gif)

At least while editing Python code, pressing tab should result in 4 spaces. Regardless of language, autoindent should insert the type of whitespace pressing tab would give the user so they can mix automatically indented lines with lines manually indented with tab.

Related to https://github.com/nteract/nteract/issues/1137, but there may be more to that issue.

**Comment by rgbkrk** [comment]
Wow that's pesky.

**Comment by dhirschfeld** [comment]
Also, From #1256:
> It would be nice to have an option whereby tab always indented 4-spaces. It would also be nice to be able to configure whether or not to show "invisibles" e.g. spaces
