### ISSUE TITLE
Markdown cells don't render local images

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1242]
![bildschirmfoto 2016-11-24 um 22 48 59](https://cloud.githubusercontent.com/assets/13285808/20610330/39c77dd0-b298-11e6-980b-9b61396baf99.png)

~~The same happens with local images~~

**Comment by rgbkrk** [comment]
As for the absolute URL you're using there -- it needs to be without quotes.

For local images, there is a bigger problem. The page is relative to the install location, not the notebook file. We have to change our architecture to handle relative assets.

**Comment by lgeiger** [comment]
Oops You're right. But the issue with local images is still there.

**Comment by rgbkrk** [comment]
Suggestion by @smashwilson: use [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) and set the `href` to the notebook path. This would likely have to occur after we load our other assets.

**Comment by rgbkrk** [comment]
We definitely have to solve this one before the release candidate and have it kicked around during the beta or alpha stages.

**Comment by jkornblum** [comment]
I had looked at this probably a few weeks ago now and never really finished working on it.
I found this library [react-helmet](https://github.com/nfl/react-helmet), MIT licensed. 

> This reusable React component will manage all of your changes to the document head with support for document title, meta, link, style, script, noscript, and base tags.

Which made it simple to edit `<base href="">` dynamically.

**Comment by rgbkrk** [comment]
Definitely still needs a fix and we're in a good spot for where desktop is for this to be tackled.
