### ISSUE TITLE
Ability to control scroll behaviour of cells

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1257]
It seems in nteract that an output over a certain size will trigger a vertical scrollbar for the cell which is reasonable and follows the existing notebook behaviour IIRC. In the existing notebook you can toggle the scrolling and display the full cell by double-clicking in the left margin. It appears this isn't yet implemented in nteract?

In my usecase I've got a large mpl figure with several charts arranged vertically. I would like to be able to see them all together but with the current scrolling behaviour in nteract I can't do this.

**Comment by dhirschfeld** [comment]
I see that it's available in the cell dropdown. Sorry for the noise!
![image](https://cloud.githubusercontent.com/assets/881019/20782171/0231f75a-b7d5-11e6-9aa6-255a4af17ab7.png)

**Comment by jdetle** [comment]
Not noise at all! We really appreciate any user who takes the time to open (and close) an issue. Thanks very much @dhirschfeld.
