### ISSUE TITLE
Modifying styles via IPython.core.display.HTML not working

### ISSUE THREAD

**Issue by laymonk** [nteract/archived-desktop-app#1265]
Typically, one can modify default jupyter notebook styles by importing  IPython.core.display.HTML (in python) and applying styles to it .. eg:
```python
mycss = """
body {
    margin: 10;
    font-family: blah, blah1, serif;
}
"""
from IPython.core.display import display, HTML
HTML('<style>{}</style>'.format(mycss))
```
I am trying to modify the default table display styles for a pandas dataframe, but this is not working in nteract ..  

Also, trying to add new themes the recommended Jupyter way does not work, and the themes are not available in nteract

**Generally, it would help to know:**
* the recommended way to override default css styles for table elements ..
* how to add custom themes  .. I can see styles for the listed themes are defined in '<installdir>/resources/app/static/styles/' 

Sorry if this has been addressed elsewhere .. I have looked around and couldn't find this information, hence my creating an issue ..

**Comment by laymonk** [comment]
A peek in the pandas source code showed it was expecting the HTML object to be wrapped within the display object .. and the table css works fine now .. like so:
```python
display(HTML('<style>{}</style>'.format(mycss)))
```

Would still appreciate a response to my question on how to define custom styles for nteract ..

**Comment by alexandercbooth** [comment]
Hi @laymonk, thanks for your question!

If you are building from source, you can create a custom theme by adding it to  [styles](https://github.com/nteract/nteract/tree/master/static/styles) and naming it `theme-laymonk.css`. 

And once you have done that you can add it to the [menu](https://github.com/nteract/nteract/blob/master/src/main/menu.js#L358) with something like:

``` jsx
  {
    label: 'Laymonk',
    click: createSender('menu:theme', 'laymonk'),
  },
```

Then install and restart.

**Comment by laymonk** [comment]
Thanks a million, @alexandercbooth  .. the menu definitions file (menu.js) is what I was seeking really.

**Comment by alexandercbooth** [comment]
My pleasure @laymonk, thanks for using nteract 🎉.  Your feedback is really valuable!

**Comment by rgbkrk** [comment]
We definitely need to figure out how we want to allow external themes. We do have an `nteract.json` file that is placed in your jupyter config directory. It lets you swap out the theme by name, yet not a reference to (or override of) the CSS file itself. It's tempting to allow custom styles in something like a user's `nteract.css` (in the config directory). We'd need to be fairly committed to our DOM and CSS structure though.

If you think others would like your theme @laymonk, feel free to submit it for inclusion in the main app! We could generally use better default table styling, so I certainly welcome it. 😄

**Comment by rgbkrk** [comment]
I'll go ahead and close this. Feel free to re-open if you think this is still open. Seems like the question of direction was carved out. Would still love to see your theme. 😄
