### ISSUE TITLE
Export to PDF preserving styles

### ISSUE THREAD

**Issue by fbrundu** [nteract/archived-desktop-app#1267]
Hi all,
Is there any plan to provide an export to PDF, while preserving the style of the notebook?
Such as a print of the notebook. This would be nice for presenting the notebook as an article.
Unfortunately, I cannot work on it right now.

Thanks,
Francesco

**Comment by jdetle** [comment]
http://electron.atom.io/docs/api/web-contents/ <-- contents.printToPDF looks like the function we'd need to implement this. To the best of my knowledge we don't currently have it but I can work on it tonight for you @fbrundu!

**Comment by fbrundu** [comment]
Thanks :)

**Comment by jdetle** [comment]
Hi @fbrundu, I have working prototype up and this is the result I got: 
[printPDF.pdf](https://github.com/nteract/nteract/files/638367/printPDF.pdf)
It looks like the shadows are rendered rather poorly, and in my opinion I wouldn't want this on my website. There's some work we can do to create a print style sheet to avoid this, it'll take a few more days, certainly.

**Comment by fbrundu** [comment]
@jdetle ok. I think that's a nice result (shadows aside). It is not urgent, though, but I wrote to suggest a possible feature for a new release :)

Thanks

**Comment by OliverEvans96** [comment]
Does it seem that nbconvert would be helpful here? Convert to latex ->
compile. That would require users having latex or including some subset of
it with the package, perhaps neither of which would be ideal. Also, perhaps
nbconvert doesn't preserve the style as viewed in nteract in the way you
would hope.

Oliver

**Comment by fbrundu** [comment]
Yes, that was what I first thought.
The problem, as you said, is that if you prepare some document you cannot preserve the style once you go through latex. I had problem with listings, for example, with very long lines that were displayed correctly on the notebook but too long for the pdf.
However, the solution that @jdetle proposed, by using Electron API, seems to me the right way to do it, maybe enhancing the Electron API, but I'm no expert on unfortunately.

**Comment by jdetle** [comment]
@fbrundu @OliverEvans96, you're welcome to try to come up with a fix using nbconvert. I'll try to tackle that myself asap, but I just dont know very much about the project. Either way I think we'll need a special print stylesheet if you want to retain some amount of styling in a pdf.

**Comment by jdetle** [comment]
Awwww yuss! Check it out: 
[print.pdf](https://github.com/nteract/nteract/files/641469/print.pdf)

Should be up in the next few days.

**Comment by rgbkrk** [comment]
Done deal #1358
