### ISSUE TITLE
Add loading screen with fun spinning cube

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#127]
While we're launching a notebook at the start, we should have a loading screen/indicator.

**Comment by captainsafia** [comment]
The loading screen should the fun spinning cube that we currently have on nteract.io!

**Comment by mangecoeur** [comment]
@captainsafia FYI the spinning cube on the homepage is buggy in Firefox (FF45, OSX 10.11, MBP nvidia) ![nteract home](https://dl.dropboxusercontent.com/u/6613592/Screen%20Shot%202016-04-15%20at%2011.52.16.png)

**Comment by rgbkrk** [comment]
That is an impressive shattering of the cube. We can certainly pick something more sane on startup, like a fixed image.

**Comment by freeman-lab** [comment]
I sort of like it, very abstract art 😄

**Comment by betatim** [comment]
Or https://source.unsplash.com

<img src="https://source.unsplash.com/category/food/800x450" />

would make sure we keep the loading times minimal so people don't wander off because they got hungry.

(This is actually a little less cool than it should be as it should be returning a random image each time)

**Comment by rgbkrk** [comment]
> (This is actually a little less cool than it should be as it should be returning a random image each time)

Ha, I wondered so I reloaded the page. Maybe cached?

**Comment by rgbkrk** [comment]
Oh, the link shows me a github URL. GitHub proxies image loads.

**Comment by rgbkrk** [comment]
![](https://source.unsplash.com/random.png)

**Comment by betatim** [comment]
> Oh, the link shows me a github URL. They're proxying image loads.

Jupp.com, :octocat: are sneaky like that. unsplash is probably the only image host in the world that wants you to hotlink ;)

**Comment by rgbkrk** [comment]
I think GitHub does it for privacy reasons, to not expose referring host and URL path (within private repos especially).

**Comment by Carreau** [comment]
What about changing the splash screen with a Daily TIP ?

**Comment by rgbkrk** [comment]
Solid idea, I like the daily tip. Quick to load and show.

**Comment by rgbkrk** [comment]
It can be fun and quirky like the startup messages in Slack.

**Comment by rgbkrk** [comment]
This is all set, albeit with our newer animated logo. :smile:
