### ISSUE TITLE
Unexpected statusbar update behavior

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1274]
When I run code the status bar changes to "python3 | idle" to "python3 | busy" as expected.
When the code completes the status bar stays at "python3 | idle" until I edit a code cell.

This happens because of the `shouldComponentUpdate` method in `status-bar.js`. The render function is gated by a change in notebook or lastSaved prop which does not happen until code cell is edited and the notebook changes. I think the executionState is in the app model and is not affecting the notebook.

I can submit a PR removing this method. Is there a reason for using `shouldComponentUpdate` with notebook and lastSaved props? I did not observe any odd behavior when I removed the code.

**Comment by lgeiger** [comment]
Closed in #1292
