### ISSUE TITLE
Create mocks for UI of kernel indicators

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#128]
We need to post mocks and UI flows for the state of the kernel.

States:
- [x] Kernel busy
- [x] Current language
- [ ] Icon for language

**Comment by jdfreder** [comment]
#434 makes the kernel busy state available

**Comment by captainsafia** [comment]
I can work on making actual pictures, but I like the idea of having a simple indicator at the bottom of the window in the status bar.

https://github.com/atom/status-bar

**Comment by rgbkrk** [comment]
I like the Atom status bar too.

**Comment by captainsafia** [comment]
Yeah, now I just gotta see if they have an electron API for status bars.

**Comment by rgbkrk** [comment]
If you want fancy graphics (kernel logos), I'm guessing you're better off with something DOM/React based.

**Comment by captainsafia** [comment]
That makes sense. Might makes sense to also use React for the status bar since we used it for context menus...

**Comment by rgbkrk** [comment]
Gutter made this awesome. Closing.
