### ISSUE TITLE
Remove PureRenderMixin (deprecated), extend from PureComponent

### ISSUE THREAD

**Issue by peggyrayzis** [nteract/archived-desktop-app#1287]
We use the 'react-addons-pure-render-mixin' in some of our components to shallowly compare props & state in shouldComponentUpdate. This mixin is deprecated - we should extend our component classes from PureComponent instead to take advantage of this feature.

https://facebook.github.io/react/docs/pure-render-mixin.html

**Comment by rgbkrk** [comment]
Ooooh that's new to me. I had not heard of `PureComponent` yet!

**Comment by peggyrayzis** [comment]
Yeah it's pretty new! I'm willing to tackle this gradually throughout my provider refactor or offer help to a new contributor that wants to take this on. 😀
