### ISSUE TITLE
Refactor components to remove Redux logic

### ISSUE THREAD

**Issue by peggyrayzis** [nteract/archived-desktop-app#1288]
In order to keep our components modular and reusable, @rgbkrk & I discussed removing all Redux logic (dispatching, accessing the state tree) from the components themselves and moving them into providers.

Providers are HOCs that act as middlemen between presentational components & the Redux store (or any other form of data hydration). They provide presentational components with access to application level data by passing down callbacks through props.

Currently, these components are connected to the store via context. To disconnect our components, we need to:
- Remove all references to the store through context
- Abstract dispatching actions into callbacks
- Move mapping state to props into providers

These components need to be refactored:
- [ ] Notebook (saving for last)
- [x] Cell Creator Buttons
- [x] Draggable Cell (@jdetle)
- [ ] Cell (@peggyrayzis)
- [x] Toolbar (@captainsafia) - #1323 
- [x] Editor (@peggyrayzis)

When finished, this will move us closer to our goal of completely reusable components. 🎉  I will be making a PR for Cell Creator Buttons soon so you can see an example of this in action.

**Comment by jdetle** [comment]
I'll try to help out once I see your PR as a guide 👍

**Comment by rgbkrk** [comment]
We're getting there!

**Comment by rgbkrk** [comment]
Another one checked off!

**Comment by rgbkrk** [comment]
I think we're on a pretty good level with this now with the packages in `@nteract/core` and it's getting better each day. One note for historical record -- at least at the time of writing this, we've kept providers and made the "views" just be called "components". 😄
