### ISSUE TITLE
Clearing cells sets illegal 'outputs' key to markdown cells

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#1306]
This is a little bit related to #1232  and #1233 

Restarting the kernel and clearing cells sets  `outputs` keys to all cells, including markdown cells, where it is invalid.

I'm on master branch commit 974cdd2b05

## Reproducing

1. create of open any notebook with at least one markdown cell
2. use *Language > Restart and Clear All Cells*
3. save the notebook
4. opening the notebook using `jupyter notebook` or `jupyter nbconvert` will fail in the manner below

I discovered this trying to convert a notebook to markdown:

```
jarmo@lambda-epsilon:/tmp$ jupyter nbconvert --to markdown a.ipynb 
[NbConvertApp] Converting notebook a.ipynb to markdown
[NbConvertApp] ERROR | Notebook JSON is invalid: Additional properties are not allowed ('outputs' was unexpected)

Failed validating 'additionalProperties' in markdown_cell:

On instance['cells'][0]:
{'cell_type': 'markdown',
 'metadata': {'collapsed': False, 'outputExpanded': False},
 'outputs': ['...0 outputs...'],
 'source': 'this cell will have an `outputs` key which is invalid'}
[NbConvertApp] Writing 55 bytes to a.md
```

## Fix

Using a text editor to remove all `outputs` keys form cells that have `"cell_type": "markdown"` fixes the errors.

**Comment by rgbkrk** [comment]
Thank you for reporting this!
