### ISSUE TITLE
No kernels installed error  on OSX, using zipped pkg

### ISSUE THREAD

**Issue by michaelaye** [nteract/archived-desktop-app#1321]
I just tried out 0.0.15 via the zipped packaged, so i'm launching the app directly from the Downloads folder.
The app opens like this
<img width="801" alt="screenshot 2017-01-10 16 58 34" src="https://cloud.githubusercontent.com/assets/69774/21829880/42b9d482-d756-11e6-8f48-7a83fb911a34.png">

 and i get no chance to configure anything. The docs on the release page don't mention anything special to do, so I don't know what's missing. I have fully functional environments installed via conda, but launching the app from Downloads, per mouse-click, I wonder how it would find my ipython kernels?

**Comment by nicobrenner** [comment]
@michaelaye same problem here, it's easy to miss the instructions on the [Releases page](https://github.com/nteract/nteract/releases):

![image](https://cloud.githubusercontent.com/assets/2296756/21873478/83a56128-d823-11e6-8bf1-2fcb762a126a.png)
Running the commands like that didn't work on my Mac with El Capitan (10.11.6). What finally worked was, from the terminal, using [Homebrew](http://brew.sh/) (Couldn't install the python package (2.7) for some reason)

```
brew install python3
python3 -m pip install ipykernel
python3 -m ipykernel install --user
```

And then running `nteract`

**Comment by jdetle** [comment]
@michaelaye, @nicobrenner, thank you for the excellent report and quick fix. If there is extra documentation you would like to add such that future users can install and use nteract with less friction, please don't hesitate to make a pull request. We really appreciate any help we can get.

**Comment by rgbkrk** [comment]
We could switch our guidance to python instead of python3.

**Comment by rgbkrk** [comment]
Thanks for reporting the issue, we'll detect the non registered python kernel by the next release (in flight PRs that address this).

**Comment by michaelaye** [comment]
As I said, I have a fully working jupyter environment with ipykernels installed, so that's not the problem here. Any other solutions?

**Comment by rgbkrk** [comment]
What's in ~/Library/Jupyter/kernels ?

**Comment by michaelaye** [comment]
I don't have that folder? I guess because I'm using nb_conda_kernels which just auto-discovers any installed packages with jupyter kernels (so, ipykernel is definitely installed), I don't need any kernel files?

**Comment by rgbkrk** [comment]
We don't currently detect conda environments or base python installations. All kernels detected come from looking at the kernel paths for jupyter. If you want nteract to see your current conda environments, you'll need to [create a kernel for the conda environment you want to use](http://www.alfredo.motta.name/create-isolated-jupyter-ipython-kernels-with-pyenv-and-virtualenv/). We've certainly been figuring out how to support this and even have code for detecting conda environments that have `ipykernel` installed as a python package.

This comes down to two choices:

* Wait for us to finish off https://github.com/nteract/nteract/issues/357 and https://github.com/nteract/nteract/pull/1264 as well as ship it
* Run the [`ipykernel install` command inside your conda env](http://ipython.readthedocs.io/en/stable/install/kernel_install.html#installing-the-ipython-kernel):

```
source activate myenv
python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
```

Thanks for your patience as we get it all situated.

**Comment by michaelaye** [comment]
I was under the impression that pyenv and conda are not really comparable in terms of how they run things, so I'm not sure about following that link's instructions. But I'm not in a rush, just wanted to check how things are going with this, while deciding between hydrogen and nteract (but maybe you've seen that my hydrogen setup also doesn't work :/).

I'll be waiting for the detection to work, but here's a question I have related to this: If my conda setup is like this: 
1. not working in conda root
2. having a preferred enviroment in conda env `stable`
3. having a py2 environment for testing in conda env `py27`

How would a double-clicked application know to pick the correct one? Does `nteract` have a functionality where I can choose between the kernels that were found? Like it works in the browser?

**Comment by rgbkrk** [comment]
Cool, we'll keep on keeping on so that it can work for you soon.

To answer your question, encoded in the notebook metadata is information about which kernel to launch. It's the same metadata that is used by Jupyter notebook and we intend to match the implementation there so that it's a consistent experience. Our conda env detection is the same namespace setup as `nb_conda_kernels`.
