### ISSUE TITLE
Create a troubleshooting guide

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1327]
Largely speaking, the most consistent problem we run into is with kernels spawning (we have a lot of related issues for this). While we double down on fixing the core issues, we should also have a semi-handy guide (`TROUBLESHOOTING.md`) to help us help others.

Here's a starter:

## ERROR_EXECUTING Kernel not connected

* Open up the dev tools
* Report any errors seen
* Install the python kernel with `python -m ipykernel install --user`
* Fully restart nteract

**Comment by rgbkrk** [comment]
Note: I'm lacking specificity in the above example, hoping someone can collate good information in the guide.

**Comment by Fil** [comment]
thanks for opening the issue
this is where I'm stuck
![c1kmcdqxuaa7gaa](https://cloud.githubusercontent.com/assets/7001/21864045/456f563a-d840-11e6-95f1-72f74aaf0479.png)

**Comment by Fil** [comment]
OK, found "dev tools" in menu "View" :)

it looks like the notebook is looking for python3 and I have only python2 (does this make sense?)


![capture d ecran 2017-01-11 20 57 30](https://cloud.githubusercontent.com/assets/7001/21864146/c18a6912-d840-11e6-9651-e1e99e6a1a6c.png)

**Comment by rgbkrk** [comment]
Oh interesting - we need to make sure to fallback to a different python kernel if the exact one from the notebook format is not available.

Does "Python 2" show up in the Language menu?

**Comment by Fil** [comment]
Yes, "Python 2" is the only language that shows.

(I would like to install Javascript as well, but couldn't find how.)

**Comment by rgbkrk** [comment]
Does it let you switch to Python 2 via that Language menu?

**Comment by Fil** [comment]
not sure; I can click on the menu item (it's not disabled), but it doesn't seem to have any consequence

**Comment by Fil** [comment]
also if I "restart" I receive this lovely message: “Kernel null has been restarted.”

**Comment by rgbkrk** [comment]
When you create new notebooks do they work properly?

**Comment by Fil** [comment]
yes it seems they do: if I copy/paste the cells one by one from the notebook that doesn't work, I get the expected results

**Comment by rgbkrk** [comment]
Opened https://github.com/nteract/nteract/issues/1328 as the issue for falling back to a different Python kernel.

As for the app generally not working after kernel failure, we need to set up explicit recovery / "retry" flows for our epics: #1177

**Comment by rgbkrk** [comment]
One more related issue I've posted: https://github.com/nteract/nteract/issues/1329
