### ISSUE TITLE
Handle no matching kernel for notebook case

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1329]
When a user loads a notebook for which they don't have the associated kernel, they need to be informed of this (at the very least).

**Comment by rgbkrk** [comment]
Right now the error message reads `ERROR_KERNEL_LAUNCH_FAILED` with little extra detail.

Suggested changes:

* Leave the error message up longer
* Provide more details, including:
  - what kernel was launched
  - what kernels we see available
  - suggest steps to take

I'm beginning to wonder if we should devote time to investigating and designing better error interfaces within the app (likely just CSS on top of our current notification system).

**Comment by Jaykul** [comment]
See also: #1796 because sometimes you bring this upon yourselves ;-)

**Comment by rgbkrk** [comment]
This is back to being an issue due to our error notifications not showing up it seems. Would love to make sure this is happening well.
