### ISSUE TITLE
Tables not rendering in markdown cell

### ISSUE THREAD

**Issue by speakerToSystems** [nteract/archived-desktop-app#1330]
The following simple table displays properly in Jupyter, but not nteract.

| H1 | H2 |
| --- | --- |
| v1 | 0 |

**Comment by jdetle** [comment]
Copying over comments and background given by @lgeiger:

>nteract adheres to the commonmark spec: http://commonmark.org/
>Which if I recall correctly doesn’t support this syntax
>As a markdown parser we use: https://github.com/jgm/commonmark.js
>Jupyter uses https://github.com/chjj/marked which is more or less unmaintained
>An option would be to switch to https://github.com/markdown-it/markdown-it
Which also adheres to the comonmark spec and additionally supports GitHub flavored markdown with support for tables

**Comment by rgbkrk** [comment]
Trying out `markdown-it` sounds like a good option. The only thing I'd probably be wary of is how/if HTML is sanitized (or not). I really wish we had a way to go from:

```
markdown source (string) --> AST --> React Elements
```

**Comment by rgbkrk** [comment]
Closed by #2350.
