### ISSUE TITLE
[Proposal] Provide a list of Authors in Modules

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1334]
Hi, 
When working on a refactor of a module it would be nice to ask the original author for links to documentation or other miscellaneous information. In order to track who has knowledge of what parts of a codebase, it would be nice to keep a commented record in each module being edited.

The idea is that upon committing changes to a module one would add their name to a list of authors given as a comment at the top of the file. Feel free to let me know how you feel about adding this to the workflow of a standard Pull Request.

**Comment by peggyrayzis** [comment]
Facebook has something similar for their open source projects that might be easier to maintain. When you contribute (at least for React/React Native), they have a Github bot that analyzes git blame to identify and tag potential reviewers for your PR.

https://github.com/facebook/mention-bot

**Comment by rgbkrk** [comment]
> The idea is that upon committing changes to a module one would add their name to a list of authors given as a comment at the top of the file. Feel free to let me know how you feel about adding this to the workflow of a standard Pull Request.

I'm not at all interested for several reasons:

* `git blame` and GitHub's blame view are designed for this.\*
* Not everyone who has contributed is working on the project any more (it happens - they change jobs, choose something else, people die) - people tend to forget why they did things a certain way in little chunks of the code base, it's your job to figure it out and leave it better than you found it.
* This is a process that will be harder to maintain than you think.

@peggyrayzis' suggestion is spot-on for large projects that receive a lot of pull requests. We're so small that it's easy to reach pretty much everyone by posting a single issue like this -- even if it was to open a discussion about the module you're wondering about.

\* Blame doesn't always give you the best view when files are moved around, so you end up having to do a lot of extra digging if the code is really old after surviving refactors. Probably even old enough that trying to bring someone from the past to look at the new version would be disorienting.

**Comment by jdetle** [comment]
Sounds good. I'll close this when I get home.
