### ISSUE TITLE
nteract-0.0.15.exe hangs explorer.exe

### ISSUE THREAD

**Issue by jrehn** [nteract/archived-desktop-app#1340]
Tried downloading and installing nteract-0.0.15.exe but listing the file will hang and crash explorer.exe on Windows 10. Malformed binary?

**Comment by rgbkrk** [comment]
Wow, I've yet to have that happen to me though I'm downloading with Chrome on my Windows machine. I'll try it on internet explorer next (is Edge ok?).

**Comment by jrehn** [comment]
Thanks for you reply!
I've now tested with Chrome 56.0.2924.87, Edge 38.14393.0.0 and Internet Explorer 11.576.14393.0. Same result. Sorry to see that I cannot test run your project on my computer, heard about it on Hanselminutes and was really looking forward to testing it. Not impossible that that the error is on my end of course.
Glad to see that this is not a common problem!
If I were to build the project and poke around in a little the install compiler, where would you recommend me to start?

**Comment by rgbkrk** [comment]
You will need to install node.js >= 6.0 and follow [the instructions for setting up nteract in dev mode](https://github.com/nteract/nteract#development).

**Comment by rgbkrk** [comment]
Let me know if the 0.8.x release series works for you!

**Comment by jrehn** [comment]
Solved! Thank you Kyle!

Kind regards
/John

2018-04-13 17:14 GMT+02:00 Kyle Kelley <notifications@github.com>:

**Comment by rgbkrk** [comment]
Thanks @JRehn!
