### ISSUE TITLE
Create a notebook loading placeholder

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1347]
Something that I've personally enjoyed across Slack, Facebook, and _even on [nteract.io](https://nteract.io)_ is placeholder blocks:

nteract.io site hero video:

![screen shot 2017-01-17 at 3 51 47 pm](https://cloud.githubusercontent.com/assets/836375/22045034/db261d22-dccc-11e6-8c6b-85c9b85a0596.png)

Slack loading:

<img width="1548" alt="screen shot 2017-01-17 at 3 52 14 pm" src="https://cloud.githubusercontent.com/assets/836375/22045104/2d853846-dccd-11e6-8dc1-f4982aeab5f4.png">

I'd love to see if we could have a similar placeholder that reflects our cells and feels like a nice transition as the user's notebook is loaded.

**Comment by jdetle** [comment]
I would think that once we are loading a notebook from S3 or some other
remote location something like this will become even more useful, right?

**Comment by rgbkrk** [comment]
My notebooks are big enough locally that it would be an improvement even on the desktop app.

**Comment by rgbkrk** [comment]
There's now a placeholder type in our contents setup now with plans to make a placeholder notebook component.
