### ISSUE TITLE
ReferenceError: IPython is not defined

### ISSUE THREAD

**Issue by ekils** [nteract/archived-desktop-app#1359]
![screen shot 2017-01-21 at 12 49 32 am](https://cloud.githubusercontent.com/assets/16894518/22157669/8cb4218a-df73-11e6-9377-8399b47bc266.png)

I'm new for python, so there is lot of things hard for me.
Does anyone knows what is going on this issue?

I  was want to use Atom editor to show 3d plot( use %matplotlib notebook), but it seems  can not show inline with rotatable, so I use nteract notebook and try to plot 3d , then here is the problem as the photo.

**Comment by rgbkrk** [comment]
`%matplotlib notebook` doesn't work in nteract, you'll need to use `%matplotlib inline` for now.

-------------------------------------------------

## Background

It says `IPython` is undefined because matplotlib's js is expecting the javascript object IPython to exist, which definitely doesn't in nteract.

/cc @tacaswell

**Comment by ekils** [comment]
Is it still the same issue that doesn't work on Hydrogen when i use %matplotlib notebook   ?
Because it just shows: <IPython.core.display.Javascript object> in the editor ,instead of photo.

**Comment by rgbkrk** [comment]
Same issue in Hydrogen, yes.

**Comment by tacaswell** [comment]
`nbagg` / `notebook` is going to be replaced by `ipympl` which uses ipython widgets.  I am a bit unclear on how these interact with nteract still.

**Comment by BrenBarn** [comment]
What's the status on this?  I just encountered this problem.  Without nbagg, working in nteract is in some sense a step backwards from regular IPython/Jupyter.

**Comment by rgbkrk** [comment]
The core of this issue is output expecting us to have the `IPython` or `Jupyter` classic JS objects on the page. Just like JupyterLab, we don't support the old JS APIs. I'm going to close this issue and make a new issue for interactive matplotlib.
