### ISSUE TITLE
Need to be able to select text in outputs

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#136]
The current drag and drop is awesome!

I'd love to be able to select text and images in outputs and rendered markdown text, which currently conflicts with our drag handle. You can select code no problem, just nothing that's rendered.

**Comment by rgbkrk** [comment]
This _should_ come down to setting the draggable section to be the sidebar (left on code cells at least).

**Comment by jdfreder** [comment]
Actually there's a css property I think
