### ISSUE TITLE
[PDF] Hide Toolbar on Print

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1371]
The print stylesheet should set `display: none;` for the toolbar.

![screen shot 2017-01-25 at 11 14 26 am](https://cloud.githubusercontent.com/assets/836375/22305283/cbc7eeea-e2ef-11e6-8331-fe2d765fcc03.png)

**Comment by jdetle** [comment]
It was inevitable that I forgot something, this is a quick fix I'll address soon.
