### ISSUE TITLE
Make it easier to discover kernels to install

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1375]
When a user opens [nteract for the first time](https://twitter.com/denormalize/status/824472075230343168) (or any time really), they need a way to discover other kernels. I think there are multiple opportunities:

* Include a menu item for discovering new kernels (could link to a new page)
* Create our own editorial version of [Jupyter kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) that lists kernels we support well (and welcome contributions to it).

**Comment by rgbkrk** [comment]
The second part, https://nteract.io/kernels for listing our editorialized version of which kernels to promote is done.

**Comment by willingc** [comment]
There is now a help menu item for the first part to install kernels.

Closing as resolved.
