### ISSUE TITLE
plotly example notebook broken on master?

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1387]
For me, with the latest master on win64/py35, The `plotize` command in the example notebook doesn't display the chart but also doesn't appear to throw any errors. The same notebook works fine for me with the last released nteract version.

Can anyone else see/repro this? It's highly likely there may have been some issue with my build, but in case its an actual bug I thought I'd report.

![image](https://cloud.githubusercontent.com/assets/881019/22453105/0f6cf0dc-e7c8-11e6-87ae-9340057bcb48.png)

**Comment by rgbkrk** [comment]
I'm going to try out a fresh install here, this might relate to how I switched us over to freezing objects on `JSON.parse`.

**Comment by rgbkrk** [comment]
Confirmed. They load properly from a notebook but not when run. I introduced a regression, I'll fix this pronto.

**Comment by rgbkrk** [comment]
Thank you for being such a diligent tester @dhirschfeld, very happy you noticed this before a release. 😅
