### ISSUE TITLE
Add buttons for creating a new cell in between existing cells in UI

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#139]
This is a modest proposal that I'll aim to put a mock up for later.

Between each cell should be a little area where we can click to create new cells. This could also be the drop target, though I think I backed away from that idea in #135.

When you hover over the area between cells, it shows icons for creating a text or code area.

**Comment by jdfreder** [comment]
Closed by #201

**Comment by rgbkrk** [comment]
:tada:
