### ISSUE TITLE
Experiment with new completion messagespec.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#1392]
Hey, 

Sorry to re-start a thread here, but I'm working on integrating some new completion engine in IPython (jedi). I would be happy to shove new things in the `metadata` field of completion reply, and experiment with what kind of things we can get both in nteract and hydrogen. 

Right now, I can easily change the `start, stop, list[matches], metadata` to include a list of `{start, stop, replace_string, display_string, type}` dict. 

@rgbkrk  pointers ?

**Comment by rgbkrk** [comment]
Hooray! Happy to be in this thread again.

Are you wondering where to go/what to change on the nteract side to view these responses?

I'm assuming the structure is going to swap out the list of string matches with a list of these objects?

**Comment by Carreau** [comment]
> Are you wondering where to go/what to change on the nteract side to view these responses?

Yes, or work with SO that want to work on it and is familiarish with the codebase. 

> I'm assuming the structure is going to swap out the list of string matches with a list of these objects?

Yes. I'm just going to shove that list in `metadata` for now. I want to bikeshed:
- what field should be mandatory
- the naming. 
- what else do you want. 

Like I _think_ jedi can also provide a "long description" (which could be displayed only on hover, or show for the selected option ? ). 

My other bikeshedding will be, should `display_string`  be a string or a mimebundly-thing ?
Should type be a restricted enum, or a "string with recommended values".

**Comment by rgbkrk** [comment]
> Should type be a restricted enum, or a "string with recommended values".

I assume it should be a string field. What does Atom do?

**Comment by rgbkrk** [comment]
> Yes, or work with SO that want to work on it and is familiarish with the codebase.

I'm am _more than happy_ to get started on a branch we can both push to and change - I'll kick that off after I finish #1390.

**Comment by blink1073** [comment]
Thanks for working on this!

**Comment by Carreau** [comment]
I've pushed update to to my ipython and ipykernel branches that should make that easy. 

if you `c.Application.log_level='DEBUG'` it should also print the JSON in the terminal

**Comment by rgbkrk** [comment]
Oh hey this was _completed_!
