### ISSUE TITLE
interact won't execute cells after error, even after kernel restart

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1393]
If you execute a cell before the kernel is ready, an error occurs and then nteract won't respond to any further execution requests, even after a kernel restart.

Hopefully the gif below makes it clear that after the 2nd kernel restart the cells no longer execute:
![unresponsive2](https://cloud.githubusercontent.com/assets/881019/22537022/a2867ca4-e952-11e6-883d-675786701f87.gif)

**Comment by rgbkrk** [comment]
I keep noticing this while I'm in development and it totally relates to #1177. I'll make it my other big focus here.

**Comment by rgbkrk** [comment]
nteract is now much more resilient to this, I missed something obvious in how I setup our error handling originally. The UX still needs work (to show that it's not really connected any more e.g.).

Thanks again for posting this again, motivated me to figure it out. We've got to nail this experience!

**Comment by dhirschfeld** [comment]
Thanks for fixing! I'm  on master and can confirm you can now simply restart the kernel if you get an error from trying to execute before the kernel is ready which is *much* better than having to reopen a new instance.

I'm not sure if it's technically feasible but the ideal UX (IMHO) would be if interact cached the execution requests until the kernel was ready. On my machine starting a kernel takes a couple of secs so having to wait for it to start before I can execute anything interrupts my workflow (I'm frequently having to restart the kernel in nteract because I was too quick off the mark!).

It's only a minor annoyance but it would be a nice to have. As a point of comparison the current notebook does appear to cache execution requests:
![cache](https://cloud.githubusercontent.com/assets/881019/22678784/72442d8a-ed48-11e6-9659-37a0e056e3fa.gif)

Happy to open a new feature request issue for this if it's worthwhile?

**Comment by rgbkrk** [comment]
Yes, an issue about caching execution requests while waiting for kernel startup would be good. Thank you @dhirschfeld!

**Comment by dhirschfeld** [comment]
Opened #1431 to track the execution request caching issue!
