### ISSUE TITLE
Ubuntu .deb package linter errors

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#1394]
I'm working on setting up a launchpad.net PPA for distributing automatic updates via the system update mechanism on debian based linux distributions (Ubuntu)

These are some of `lintian`s Errors for the current .deb built by `npm run dist`/`electron-build`. I'd like to try fixing these, but I'm not confident removing all of them will be possible within the constraints `electron-build`. 

- [ ] `embedded-library opt/nteract/libffmpeg.so: libavutil`

    `unstripped-binary-or-object opt/nteract/resources/app.asar.unpacked/node_modules/zeromq/zmq/bin/curve_keygen`

    `shlib-with-executable-bit opt/nteract/resources/app.asar.unpacked/node_modules/zeromq/build/Release/zmq.node 0755`

    There are quite a lot of binary files in the package, which is against conventions. It still works fine, though.
    I don't think there is much that can be done to resolve these due to the nature of electron. 
    
- [ ] `missing-dependency-on-libc needed by opt/nteract/libffmpeg.so and 5 others`

    This may be resolve with amending the `depends` in the package control file
- [ ] `no-copyright-file`

    .deb packages should have a machine-readabel [copyright file](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) in the control metadata. Is the license 3-clause BSD?
- [ ] `description-synopsis-is-empty`
    another error in the contol metadata
- [ ] `dir-or-file-in-opt opt/nteract/`

    `electron-build` automatically generates a package that is installed in `/opt/nteract`. The conventional location is `/usr/lib/nteract`. I haven't found how to configure this directory in electron build.

- [ ] `non-empty-dependency_libs-in-la-file opt/nteract/resources/app.asar.unpacked/node_modules/zeromq/zmq/lib/libzmq.la`

    `incorrect-libdir-in-la-file opt/nteract/resources/app.asar.unpacked/node_modules/zeromq/zmq/lib/libzmq.la /home/jarmo/Projects/nteract/nteract/node_modules/zeromq/scripts/../zmq/lib != /opt/nteract/resources/app.asar.unpacked/node_modules/zeromq/zmq/lib`

    I have no idea what these are...

- [ ] Using 'Lock to Launcher' in the Ubuntu application launcher will lock a specific notebook to the launcher for some reason. Starting `nteract` from a launcher should open empty notebook. 

    ![screenshot from 2017-02-02 08-38-02](https://cloud.githubusercontent.com/assets/3074453/22539610/bec3f5e2-e923-11e6-9869-4f1c8341bbc4.png)

    ^ this should say `nteract`, not the path of a notebook, and clicking it should open an empty notebook.

**Comment by rgbkrk** [comment]
I'll answer the easy ones first. 😄 

> Is the license 3-clause BSD?

Yes.

> There are quite a lot of binary files in the package, which is against conventions. It still works fine, though.

That's probably going to continue. :man_shrugging: The zeromq (zmq) ones come from us (not just by introducing it here, @lgeiger and I are maintainers on [zeromq.js](https://github.com/zeromq/zeromq.js)). The amount of work that was done for zeromq + Electron cross-platform was incredibly lengthy. The other dependencies I'm not sure of. The ffmpeg one is brought in by electron itself.

I'm happy you're going through this. @chendaniely set up the Arch Linux packaging, maybe there's some good ways to collaborate across here and electron-builder too.

Thank you again.

**Comment by rgbkrk** [comment]
With our latest versions of electron + electron-builder out in the wild I'd love to have this reviewed again. 😄

**Comment by jarmokivekas** [comment]
I think it is overdue as well. I started to start reviewing how the packages get built, but the build environment has changed so much since I last worked with Nteract that I didn't manage to build any Linux distribution packages locally.  I had some broken dependencies and a little-to-no clue about how to use npm and node to fix them...

There are [some of my old notes on packaging Nteract for linux](https://github.com/nteract/nteract/blob/45b39e8091b8d7ad92d8c129a6d12ad740c86056/applications/desktop/PACKAGING-NOTES.md) available in the repo if anyone wants to try their hand at this.

I'd like to try to set up my dev environment again at some point when I have time, but don't hold your breath. :sweat_smile:

**Comment by jarmokivekas** [comment]
I think my main problem may have been not figuring out what is the current equivalent command to what used to be `npm run dist` is.

**Comment by rgbkrk** [comment]
We're on 'yarn' instead of npm directly now. You'll have to use yarn exclusively. You will likely have to delete all the node modules with yarn clean && rm -rf node_modules before you run yarn.

You'll have to trust me on saying that it's a better environment now. 😅 yarn is well integrated with the monorepo and does make dev installs much faster now.

**Comment by jarmokivekas** [comment]
I re-installed node, and now yarn works as intended. I managed to build working .debs and AppImages locally. :+1:

Can I increment the Nteract version number locally for debugging? It will avoid confusion while working if I'm not installing 0.11.6 on top of 0.11.6 every time I make a change to the package.

Thanks.

**Comment by rgbkrk** [comment]
> Can I increment the Nteract version number locally for debugging?

That should be fine. It's too bad it doesn't build with a `-dev` in the name. Come to think of it, that's what I would append in the package.json within `applications/desktop` to denote that it's a dev branch.

**Comment by jarmokivekas** [comment]
Stale-bot is right to close this. The electron deb packaging does not produce completely lint-free packages regardless of how carefully they are configured. Closing this as not-quite-done-but-fixing-it-is-far-more-work-than-value-and-would-require-major-overhaul-of-packaging-architecture.
