### ISSUE TITLE
border around hovered cell in exported PDF

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#1404]
A border line is drawn in the PDF around the cell that the cursor is hovering over when exporting a pdf using *File > Export PDF*.

![screenshot 2017-02-04 23 01 22](https://cloud.githubusercontent.com/assets/3074453/22621533/9ddaabd4-eb2e-11e6-9f8a-12eb706fe1f2.png)

Clicking the menu item leaves the cursor hovering above the topmost visible cell. The border around the active cell is removed as expected, though.

![screenshot 2017-02-04 23 02 10](https://cloud.githubusercontent.com/assets/3074453/22621534/9f0d8eb8-eb2e-11e6-9783-a63b0c19b76d.png)

I wouldn't mind fixing this one myself. Probably something to do with `@media print` in [/static/style/main.css](https://github.com/nteract/nteract/blob/master/static/styles/main.css)?

PS: I think it's awesome that you can export pdfs where the cell input is hidden for plotting code. It looks nice :sparkles:

**Comment by jdetle** [comment]
I can tackle this now or if you'd like to make the change it would be very appreciated. Thanks for the catch, I really appreciate you trying it out! Brings a tear of joy to this contributors eye :)

**Comment by jarmokivekas** [comment]
I think I got it fixed a few seconds ago. I noticed that also the `cell-creator` boxes between cells were visible sometimes.

**Comment by jdetle** [comment]
Fantastic! I will definitely merge any pull request I see addressing these issues. Thank you so much @jarmokivekas.

**Comment by rgbkrk** [comment]
Closed by #1407.
