### ISSUE TITLE
Keep cell type when created with ArrowDown

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1410]
When the last notebook cell is in focus and the down arrow is pressed a new cell is created. Currently regardless if the last cell is a markdown type or code type a code type will be created.

Any thoughts on persisting the last cell type for newly created cell types? That is, a down arrow on a markdown cell will create another markdown cell and a down arrow on a code type will create another code type cell.

**Comment by rgbkrk** [comment]
I like that idea.

**Comment by jkornblum** [comment]
This is closed with #1435
