### ISSUE TITLE
Migrate off eslint, switch to Prettier

### ISSUE THREAD

**Issue by peggyrayzis** [nteract/archived-desktop-app#1414]
Amidst all the eslint slowness issues, @rgbkrk suggested that we switch to [Prettier](https://github.com/jlongster/prettier). This is a great idea and will hopefully make our lives easier! 😀 

To achieve this, we need to:

- [ ] Close all open PRs to avoid merge conflicts
- [ ] Remove eslint, its plugins, and config.
- [ ] Add Prettier, ensure everything still works as expected

**Comment by rgbkrk** [comment]
Yay for the `gofmt` of JS!
