### ISSUE TITLE
Kernel fuzz testing

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1417]
We should put nteract through it's paces with a kernel that is not properly implemented or even one specifically designed to send weird data. The main goal would be to ensure that the notebook format is consistent and valid while also informative to the user.

**Comment by rgbkrk** [comment]
This was aspirational at best and not something I can prioritize relative to other needs. If someone wants to tackle it, feel free to go after it!

**Comment by willingc** [comment]
@rgbkrk I'm going to close this as overly optimistic in the short term :wink: 

On the positive side, the evolution of papermill makes it more possible to test notebooks going forward. I'm going to close this issue. Please feel free to open a more narrowly scoped issue on testing kernels :sunny:
