### ISSUE TITLE
Tab-indentation broken on master?

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1422]
On master, highlighting text and pressing tab will delete the text rather than indenting it!
![tab](https://cloud.githubusercontent.com/assets/881019/22679989/73850d1e-ed51-11e6-8686-e04766bb1e8e.gif)

Is anyone else seeing the same? On win64/py35.

**Comment by peggyrayzis** [comment]
That definitely could have been me, I pushed a refactor of editor yesterday. I'll take a look at it and push a quick fix this morning. 😊

**Comment by peggyrayzis** [comment]
Thank you @dhirschfeld for reporting this 🐛! What is your desired behavior for pressing shift + tab (or de-indenting)?

**Comment by rgbkrk** [comment]
Shift-tab should de-indent.

Are we overwriting something that codemirror would normally support out of the box?

**Comment by rgbkrk** [comment]
@dhirschfeld, you do such an excellent job of filing issues for what's happening on master that I've added you as a member of nteract - thank you for these contributions. Welcome!

**Comment by peggyrayzis** [comment]
> Shift-tab should de-indent. Are we overwriting something that codemirror would normally support out of the box?

Unfortunately, Codemirror doesn't support highlighting + Tab to indent out of the box. Originally, we had a tabToSpaces function that converted our tabs to spaces & took care of the highlighting + Tab. Codemirror came out with a new option (insertSoftTab) that converts your tabs to spaces for you and I didn't end up checking that it supported highlighting + Tab.

Shift + tab currently de-indents to the beginning of the nearest code block.

**Comment by dhirschfeld** [comment]
Thanks @rgbkrk - I've been meaning to enable 2-factor auth so once I've done that I'll sign up.

Not sure how much actual help I'll be as I still haven't learnt JS, but I'm happy to test on Windows.

**Comment by rgbkrk** [comment]
No worries about code contributions, it's really excellent getting all the testing feedback as a user.

**Comment by dhirschfeld** [comment]
Regarding the tab behaviour, I would expect/like tab to indent the selection 4 spaces and shift-tab to dedent 4 spaces. This is the behaviour of the current notebook.

On the latest master `v0.0.15-317-g935444c6` the tab behaviour is the same as for the released version (`0.0.15`) which is to say that tab works as above but shift-tab doesn't seem to do anything. GIF below showing nteract master vs the notebook:
![tab2](https://cloud.githubusercontent.com/assets/881019/22716221/a04faa90-ede0-11e6-8ac6-704b863749ae.gif)

**Comment by dhirschfeld** [comment]
I opened #1430 to track the shift-tab behaviour
