### ISSUE TITLE
Cache Execution Requests during slow kernel starts

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1431]
Currently in nteract if you execute a cell before the kernel is ready you get an error popup and then have to restart the kernel before continuing. It would be good if you could start executing cells immediately and have nteract cache the execution requests and only start executing the cells once the kernel was ready.

On my machine starting a kernel takes a couple of secs so having to wait for it to start before I can execute anything interrupts my workflow (I'm frequently having to restart the kernel in nteract because I was too quick off the mark!).

As a point of comparison the current notebook does appear to cache execution requests:
![cache](https://cloud.githubusercontent.com/assets/881019/22716760/06990a60-ede3-11e6-8030-b8c0b7690146.gif)

**Comment by dhirschfeld** [comment]
This sounds similar to the discussion below?
https://github.com/IRkernel/IRkernel/issues/508

**Comment by rgbkrk** [comment]
I think this one is a little easier to tackle now and should definitely be done.

**Comment by rgbkrk** [comment]
This one shouldn't have gone stale. Re-opened it.

**Comment by captainsafia** [comment]
Closing this in favor of #4762 which contains more details about a proposed solution.
