### ISSUE TITLE
Are You Sure Dialog for destructive commands

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1445]
I just learnt the hard way  that `Ctrl-R` will reload nteract which will nuke any unsaved work :sob: 

To save fat-fingered users from themselves it might be nice to have a pop-up Ok/Cancel dialog before reloading the page. To not annoy people who do want to reload the page, the Ok could be highlighted by default so that you could reload with `Ctrl-R`, `Enter`.

Similarly, for `Ctrl-W` or clicking on the window close button - both of which will kill nteract whether or not you have saved your work.

Potentially the dialog could only be shown if there were unsaved changes.

**Comment by alexandercbooth** [comment]
Related to/duplicate of #1090.

Thanks for bringing this up again. I've definitely experienced losing my work and wished I had been able to save myself from myself 😅.
