### ISSUE TITLE
Support more key shortcuts

### ISSUE THREAD

**Issue by abejenaru** [nteract/archived-desktop-app#1450]
Right now you have to use the mouse to execute one cell/all cells/all cells below (at least on Windows).
It would be nice to support key bindings (Fx keys + modifiers ?) in order to quickly run the current cell (and the other combinations), clear the output, delete cell, re-order cell, and more.
In fact, I would like nteract to be as keyboard friendly as possible.

**Comment by rgbkrk** [comment]
We support shift-enter for run cell and move down, and curl-enter for run cell in place.

We definitely need to figure out ergonomic bindings that match the notebook's fairly well, though we can pick any we want since we're in control of our renderer window.

**Comment by ajasja** [comment]
I would recommend supporting the jupyter notebook shortcuts (unless there is a good reason to deviate). In particular I miss A, B, DD in edit mode.

![image](https://cloud.githubusercontent.com/assets/19926/22951518/c906f50a-f309-11e6-99fe-cfe2c366955a.png)

**Comment by dhirschfeld** [comment]
Those are my most missed shortcuts too! Though I tend to just use `X` rather than `DD`.

In nteract because it doesn't have a command mode any commands would have to use modifier keys. At the moment `Ctrl-Shift-N` inserts a new cell below. Perhaps insert cell above could be mapped to `Ctrl-Shift-A`, delete cell could be mapped to `Ctrl-Shift-D` or `Ctrl-Shift-DEL` and to make the most  of muscle memory `Ctrl-Shift-B` could also insert a new cell below

**Comment by j6k4m8** [comment]
I'd love to double down on a suggestion for "command mode". I find myself using <kbd>esc</kbd> and then typing shortcuts in nteract all the time, and accidentally injecting letters into my code!

(Of note, <kbd>D</kbd><kbd>D</kbd> and <kbd>I</kbd><kbd>I</kbd> are particularly common for me.)

**EDIT** Would be happy to open a separate issue for command-mode, if that's out-of-scope here :)

**Comment by rgbkrk** [comment]
Command mode is discussed in #1467. For me it's in a state of "I'm personally choosing not to do it and maintain it". If someone is interested in contributing it and helping maintain the overall application, it's certainly of interest to folks.

**Comment by dhirschfeld** [comment]
I think these are actually implemented in the latest nteract?

**Comment by stormpython** [comment]
Closing this issue in favor of #4101.
