### ISSUE TITLE
Upgrade to WebPack 2

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1459]
Since WebPack 1 is [listed as deprecated](https://webpack.github.io/docs/), we should migrate to WebPack 2 soon. Our configuration is not too crazy so it may be pretty quick. _fingers crossed_

**Comment by peggyrayzis** [comment]
I can take care of this, just completed the upgrade for MLS. I'll be posting a cool Gist later today w/ our Webpack 2 config + PWA support (code splitting, 🌳  shaking, service worker). 😉  Shouldn't be too hard to figure out for nteract.

**Comment by rgbkrk** [comment]
Sweet, thanks. I need to make changes to our webpack setup to resolve more for #1458, I can finish that up after the webpack 2 updates.

**Comment by rgbkrk** [comment]
Turns out the problem I was running into wasn't webpack related - it was module loading for tests.

**Comment by rgbkrk** [comment]
We're on 3.5 at this point, so I'd say this is finished. 😄
