### ISSUE TITLE
Command Mode/Edit Mode

### ISSUE THREAD

**Issue by ajasja** [nteract/archived-desktop-app#1467]
nteract is aiming to fill a very important void; I've been looking around for desktop interface to Jupyter notebooks for a while know, so I'm very excited that nteract is being developed! Or to put it bluntly, I absolutely love this idea!:)

However, some features are not yet supported (ipywidgets, %matplotlib notebook), so I find my self using nteract for some notebooks and the original web interface for others. 
When switching I have the cognitive load of different shortcuts and behaviors regarding Command Mode/Edit Mode.

So my feature request is to *implement the command mode/edit mode and the shortcuts* of the original jupyter notebook. Perhaps there is a specific reason or design decision why this is not a good idea, but I imagine that the jupyter notebook will always have some additional features, so making the transition as smooth as possible would be beneficial.

**Comment by v3ss0n** [comment]
+1 Just tesing nteract, needs to emulate Jupyter Notebook's commands to be actually become a replacement . Looking at nteract , it is re-inventing everything ipython-notebook does in its own javascript missing many important features. i do not understand why such rewrite is even necessary.

**Comment by rgbkrk** [comment]
Thanks for the support!

For some users, the command mode is needlessly complex and for other users it doesn't do nearly enough. In the desktop app we're currently catering to the much simpler end of the UI/UX spectrum on purpose to enable users that are not familiar with command mode interfaces (students, analysts, etc.). We've been fairly deliberate in not focusing attention on implementing the command mode and edit mode.

This isn't to say that command mode is not useful - it is! nteract is not seeking to be a replacement for all users - people can and should still flock to the classic Jupyter notebook as well as JupyterLab.

**Comment by ajasja** [comment]
Hi @v3ss0n!

Yes, that were my thoughts exactly over the weekend. Using, [pywebview](https://github.com/r0x0r/pywebview) or [cefpython](https://github.com/cztomczak/cefpython) to run an `jupyter server` and close the server when the window closes should be relatively simple. Unfortunately I tried both frameworks, but they do not work reliably on windows. 

That said, I guess the nteract approach has much more flexibility and can go way beyond the browser interface.

**Comment by v3ss0n** [comment]
> For some users, the command mode is needlessly complex and for other users it doesn't do nearly enough.

please do not go Gnome way of assuming users to be dumb and limiting the functionalities. The targeted audience is data scientists who already have experience solving difficult problems .  Adding a few list of commands which going to make their lives easier won't add any more complexity (at least if you don't want it to get into the way of working , ctrl+shift+p command pallete is good enough , which jupyter already have)

**Comment by captainsafia** [comment]
> please do not go Gnome way of assuming users to be dumb and limiting the functionalities. The targeted audience is data scientists who already have experience solving difficult problems .

Our targeted audience goes beyond data scientists, this is highlighted in [our website](https://nteract.io/). nteract is a ultimately a design project, and like all design projects the problem at hand is delivering the best product to the most amount of users.

Also, please refrain from using pejoratives like "dumb" in issue comments.

**Comment by rgbkrk** [comment]
Thanks @captainsafia.

I certainly would like to have a command palette and would be amenable to implementing it someday.

**Comment by v3ss0n** [comment]
@rgbkrk  thanks , that would be good enough. 

@captainsafia  , seems you are out of loop. sorry i m old.
> please do not go Gnome way of assuming users to be dumb 
see this : https://www.reddit.com/r/programming/comments/14zy6/gnome_developers_think_users_are_idiots_says_linus/

**Comment by rgbkrk** [comment]
Reciting Linus doesn't help your case. It completely dismisses the users we are accommodating while casting negativity to maintainers. We can find a way to discuss and improve the experience without attributing malice on the efforts of the people who come together to build this.

**Comment by AlJohri** [comment]
closing in favor of #1584
