### ISSUE TITLE
File exit

### ISSUE THREAD

**Issue by ajasja** [nteract/archived-desktop-app#1468]
This is a very minor issue, but File -> Exit is missing form the command menu. I think it's very costumary way (besides the close button and the Alt+F4) on windows to close applications.

Here is the sublime menu for reference
![image](https://cloud.githubusercontent.com/assets/19926/22967907/a49fd326-f368-11e6-819e-1658fd455358.png)

**Comment by captainsafia** [comment]
Thanks for opening this, @ajasja! I think we might have missed this because most of us develop on OS X. I'll try and add this later tonight.

**Comment by ajasja** [comment]
@captainsafia Thanks! It's a minor detail, that you only notice when it's not there:)

**Comment by captainsafia** [comment]
> @captainsafia Thanks! It's a minor detail, that you only notice when it's not there:)

Great! By any chance would you like to take a stab and make a contribution to fix this yourself? It's a relatively simple fix (an if statement plus a few lines of code). If you'd like, I can also provide mentorship/guidance on our Slack.

Let me know if you're interested. If not, all good!

**Comment by ajasja** [comment]
@captainsafia Thanks! You can leave it open, and I'll try to find the time in the next few weeks (I estimate getting the development environment set up will take most of the time).
