### ISSUE TITLE
Improve Cell sidebar visibility in large code cells

### ISSUE THREAD

**Issue by ajasja** [nteract/archived-desktop-app#1469]
The only way I've found to toggle output visibility is by this sidebar 

![image](https://cloud.githubusercontent.com/assets/19926/22975553/7beedec6-f387-11e6-86c5-2b7807bf8f93.png)

If the code cell is small, this is not a problem. 
![image](https://cloud.githubusercontent.com/assets/19926/22975587/983614f0-f387-11e6-863d-6a138f7ead1a.png)

But if it is large, the sidebar is not visible.
![image](https://cloud.githubusercontent.com/assets/19926/22975637/bd0509c6-f387-11e6-973c-f897b53203a5.png)

I'm not sure what the best way to fix this is. Perhaps the sidebar could be made sticky and scroll with the cell. Or the output of the cell could have another sidebar. Or there could be a shortcut to toggle cell visibility.

**Comment by rgbkrk** [comment]
> Perhaps the sidebar could be made sticky and scroll with the cell. Or the output of the cell could have another sidebar. 

Really good point. It makes me think that a vertical bar that tracks along with the cell would be nice.
