### ISSUE TITLE
Which cells are scheduled for evaluation?

### ISSUE THREAD

**Issue by ajasja** [nteract/archived-desktop-app#1470]
If I go to Run all cells in a jupyter notebook, the cells that are scheduled for evaluation get an asterix (*).
This is not completely true in nteract
![image](https://cloud.githubusercontent.com/assets/19926/22976142/be3e98b4-f389-11e6-89be-e38aac923732.png)

This also happens if I shift+Enter through the cells:
![image](https://cloud.githubusercontent.com/assets/19926/22976162/dd5c446c-f389-11e6-8858-4ea5bb1dbe69.png)

Here is the notebook demo 
[test-run-all-1.zip](https://github.com/nteract/nteract/files/777140/test-run-all-1.zip)

**Comment by ajasja** [comment]
PS: hope I'm not submitting to many issues, I do try to check if these are duplicates, but finding the right keywords is sometimes tricky.

**Comment by rgbkrk** [comment]
Keep submitting issues, it's good to have them outlined. I think this one was mentioned in an issue yet didn't have a good issue all on its own. I'm glad you've brought this up, I face this problem too.

**Comment by dhirschfeld** [comment]
I have noticed this behaviour too and was going to open an issue but @ajasja beat me to it!

**Comment by lgeiger** [comment]
This was fixed by #1608
