### ISSUE TITLE
Kernel cleanup

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1472]
Since we don't capture the close event on the main thread (like we need for #1147), kernels don't always get shut down properly, resulting in stale connection files sticking around on disk. While developing nteract you may need to clean these up:

## OS X

```
rm -rf ~/Library/Jupyter/runtime/kernel-*.json
```

**Comment by rgbkrk** [comment]
This has gotten quite a bit better with our current kernel cleanup machinery.

**Comment by captainsafia** [comment]
Not sure if we need to re-open this. Maybe just keep it in mind as we rework kernel interactions in the new fs-kernels package.
