### ISSUE TITLE
Support notebooks with a raw cell type

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1476]
Right now I'm testing out the Airbnb knowledge-repo, the app generates the attached notebook. Currently nteract hangs on opening the notebook and doesn't give any error. I will look into this further.

**Comment by jdetle** [comment]
{
 "cells": [
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "---\n",
    "title: This is a Knowledge Template Header\n",
    "authors:\n",
    "- sally_smarts \n",
    "- wesley_wisdom\n",
    "tags:\n",
    "- knowledge\n",
    "- example\n",
    "created_at: 2016-06-29\n",
    "updated_at: 2016-06-30\n",
    "tldr: This is short description of the content and findings of the post.\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "*NOTE: In the TL,DR, optimize for **clarity** and **comprehensiveness**. The goal is to convey the post with the least amount of friction, especially since ipython/beakers require much more scrolling than blog posts. Make the reader get a correct understanding of the post's takeaway, and the points supporting that takeaway without having to strain through paragraphs and tons of prose. Bullet points are great here, but are up to you. Try to avoid academic paper style abstracts.*\n",
    "\n",
    " - Having a specific title will help avoid having someone browse posts and only finding vague, similar sounding titles\n",
    " - Having an itemized, short, and clear tl,dr will help readers understand your content\n",
    " - Setting the reader's context with a motivation section makes someone understand how to judge your choices\n",
    " - Visualizations that can stand alone, via legends, labels, and captions are more understandable and powerful\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Motivation"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "*NOTE: optimize in this section for **context setting**, as specifically as you can. For instance, this post is generally a set of standards for work in the repo. The specific motivation is to have least friction to current workflow while being able to painlessly aggregate it later.*\n",
    "\n",
    "The knowledge repo was created to consolidate research work that is currently scattered in emails, blogposts, and presentations, so that people didn't redo their work."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### This Section Says Exactly This Takeaway"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.text.Text at 0x1119e1cd0>"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.figure.Figure at 0x11151f4d0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib\n",
    "from matplotlib import pyplot as plt\n",
    "\n",
    "\n",
    "%matplotlib inline\n",
    "\n",
    "x = np.linspace(0, 3*np.pi, 500)\n",
    "plot_df = pd.DataFrame()\n",
    "plot_df[\"x\"] = x\n",
    "plot_df[\"y\"] = np.sin(x**2)\n",
    "\n",
    "\n",
    "plot_df.plot('x', 'y', \n",
    "             color='lightblue',\n",
    "             figsize=(15,10))\n",
    "plt.title(\"Put enough labeling in your graph to be understood on its own\", size=25)\n",
    "plt.xlabel('you definitely need axis labels', size=20)\n",
    "plt.ylabel('both of them', size=20)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "*NOTE: in graphs, optimize for being able to **stand alone**. When aggregating and putting things in presentations, you won't have to recreate and add code to each plot to make it understandable without the entire post around it. Will it be understandable without several paragraphs?*"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Putting Big Bold Headers with Clear Takeaways Will Help Us Aggregate Later"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Appendix"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Put all the stuff here that is not necessary for supporting the points above. Good place for documentation without distraction."
   ]
  }
 ],
 "metadata": {
  "hide_input": false,
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

**Comment by rgbkrk** [comment]
If I recall correctly, we read in raw cells with commutable. However, we don't have a cell component for raw cells.

**Comment by jdetle** [comment]
If you want to test the notebook, I've posted it in the slack.

**Comment by rgbkrk** [comment]
[knowledge_template.ipynb.zip](https://github.com/nteract/nteract/files/781689/knowledge_template.ipynb.zip)

**Comment by jdetle** [comment]
Closed by #1477

**Comment by rgbkrk** [comment]
Reopening, we'll want to do a few more things:

* Create a `RawCell` component that is merely an editor so that markdown isn't even attempted to be rendered
* Explore UI around raw cells - I intentionally left them out of the cell creator toolbar because I wanted the interface to be simple - perhaps we can put it in the top level menu (not the in-app menu)

In the future, I'm tempted to make some very tailored "cell types" that could rely on raw. The `metadata.format` field can be a mimetype (which could mean PNG, SVG, JSON, etc.) which could lead towards things [like being able to draw in the notebook itself](https://twitter.com/PaulNakroshis/status/832407912630853632).

**Comment by rgbkrk** [comment]
We now have a raw cell type, I think this is good for now.
