### ISSUE TITLE
Adding basic editor'ness

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#1481]
The notebook doesn't offer the same level of editor'ness as an editor. Having basic editor functionality would probably go a long way (doesn't have to be emacs level "an OS that happens to be an editor as well").

I was thinking of being able to have a linter run over my code cells or search&replace over code cells (only). 

Thoughts?

**Comment by jdetle** [comment]
I'm for it! There has also been discussion of implementing a better spellchecker, keeping track of history, managing keyboard shortcuts and exposing and interface to change notebook metadata. Some concerns I have over adding new features:
- Minimize the amount of config that has to be maintained by developers
- I dont know how rapidly we want to roll out new features. Generally I like moving fast and breaking things, but as we get close to a Beta and a Release Candidate I would like to keep d(Bugs)/dt negative. 

I think these are all features that should be added to the Release Candidate section of the [Roadmap](https://github.com/nteract/nteract/blob/master/ROADMAP.md), what do you think @betatim?

**Comment by rgbkrk** [comment]
Every single `<Editor>` is a standalone CodeMirror area per cell. If you enable the linting or find-replace (which we do have!), it only applies to each cell individually. What you'd have to do is create a codemirror addon that is cognizant of every single cell. I've never gotten too far on this -- when [doing find/replace I looked into it and it looked a bit overwhelming to do in any short amount of time](http://stackoverflow.com/questions/39812210/how-can-i-search-across-multiple-codemirror-instances).

**Comment by betatim** [comment]
Added this to the wishlist and #963 is related.

Not in a big hurry with this (and don't have the free brain cycles to spend on it myself). Just thought that linters are such a great thing, that we should have them for notebooks as well.

**Comment by SamRodkey** [comment]
Regex or wildcard Find /Replace and/or select/deselect next instance of a highlighted word (like ctrl+d / ctrl+u in sublime) would make a huge difference in my daily life. I'd pay money to have this like today. CASH MONEY.

**Comment by rgbkrk** [comment]
I have new thoughts about this, especially since our document has totally searchable state. Getting those to match up with CodeMirror may prove to be tricky, I think it's pretty doable though. Probably a couple weeks of dedicated work. Note that there _is_ per cell find/replace (cmd-f on mac for find, I can't recall the binding for replace).

As for CASH MONEY, the best route is through NumFocus:

* Page with all projects (so you can click through): https://www.numfocus.org/open-source-projects/
* Direct nteract page for donating through NumFocus: https://www.flipcause.com/widget/give_now/MTA5ODg=

**Comment by atoav** [comment]
I come from sublime text (and vim) and one thing I really love in sublime text is that when you are on a certain variable name hitting ```Ctrl + D``` selects all the other instances of this variable one by one. 

It was positively surprising to see that nteract already allows multiple cursors with ```Ctrl + LMB```, so adding the ```Ctrl + D``` seems like a reasonable extension from the perspective of someone with a sublime background.

However I saw that ```Ctrl + D``` is already reserved for Delete Line.

**Comment by rgbkrk** [comment]
Search and Replace is tracked in #1817 while linting is also tracked in #1790. Could we make this thread title and description only about linting @betatim?

**Comment by willingc** [comment]
Closing this as tracked in #1817 and #1790
