### ISSUE TITLE
Lerna/ Webpack Developer Experience

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1482]
Hi, currently if someone wants to edit one of our exported Lerna packages, it seems that the workflow to run the notebook with the updated changes is to `npm run reinstall`. This takes about two minutes on my machine and can be extremely frustrating (especially if there is an error in the lerna hoisting). Any chance there is a faster way to have a developer workflow?

**Comment by rgbkrk** [comment]
Right now I've been running `npm run build` inside of the package I'm modifying.

If you want to auto-build it, run

```
$(npm bin)/babel -d lib src --ignore '**/__tests__/**' --watch
```

I definitely agree this is not the best developer experience. Teeny bit better than if these were in separate repositories though. ¯\\\_(ツ)\_/¯

**Comment by jdetle** [comment]
Seems like updates to lerna and webpack have made this much faster. Huzzah!
