### ISSUE TITLE
Matplotlib inline plots are centered

### ISSUE THREAD

**Issue by ajasja** [nteract/archived-desktop-app#1498]
Matplotlib inline plots are centered:
![image](https://cloud.githubusercontent.com/assets/19926/23314769/9ef823ee-fac3-11e6-8607-78a94363a563.png)

Altair and plotly plots are all left-aligned.
Matplotlib plots are also (correctly) left aligned in jupyter notebooks
![image](https://cloud.githubusercontent.com/assets/19926/23314841/e02907ca-fac3-11e6-9044-2e9eff082c21.png)

```
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()
```

**Comment by rgbkrk** [comment]
This one gets to me too, addressed it in https://github.com/nteract/nteract/pull/1500.
