### ISSUE TITLE
Enhancement: "Embedded mode aka use notebook server"

### ISSUE THREAD

**Issue by ajasja** [nteract/archived-desktop-app#1499]
This is just a timid question/enhancement proposal (partly inspired by #1467): 

Would it be possible to have a mode or option to use the original jupyter notebook server? 
So double clicking on a ipynb would open nteract and a `jupyter notebook` server in the notebooks directory and then just display `http://localhost:8892/notebooks/xxxx.ipynb`.

All the machinery seems to be in place already, so from the technical standpoint this should not be problem. 
I realize however, that this may not align with the goals of nteract. Also it is not clear how that could be implemented in the UI. Probably a preference somewhere "Use jupyter notebook server" or something.

**Comment by rgbkrk** [comment]
We write directly to disk and work with kernels directly over zeromq. Using the notebook server as is would not be easy within nteract. This is not something I personally would want to support or maintain.

If you want to start a project using the server directly, I recommend starting with [`electron-quickstart`](https://github.com/electron/electron-quick-start), having it start up a jupyter notebook server on the main process, and embedding URLs inside of it. From there you'll be able to gauge how difficult or easy it will be to build, even without nteract.

This at least illustrates that you desire the complete and original Jupyter notebook server. My recommendation there is to get involved in Jupyter to (1) get packages exported that you can use outside of the web app and (2) create a new electron app.

**Comment by ajasja** [comment]
@rgbkrk Thanks, I'll try either electron or QtWebEngine. I also looked at pywebview, ghost and NW.js.

**Comment by rgbkrk** [comment]
Great! @minrk also pointed out to me that they're using jupyterlab and jupyter js services for rendering notebook diffs in nbdime, worth checking out!

**Comment by ajasja** [comment]
@rgbkrk Thanks for the tips; even nbdime itself is well worth checking out! ('ve forgot about it for a year and now I'm very impressed).
