### ISSUE TITLE
Creating a "header editor"

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1503]
As a follow on to #1465 for metadata keys and https://github.com/nteract/commuter/pull/58 (for listing notebooks), I'd like to see a way to edit the "header section" of a notebook. One way that I'd like to try this out is a top level header that appears above all the cells with a slight amount of animation dropping it down:

![screen shot 2017-02-24 at 1 50 20 pm](https://cloud.githubusercontent.com/assets/836375/23322333/3b1be14c-fa98-11e6-9ca3-fc01aa951a44.png)

On a technical level these fields will end up in the notebook metadata:

```
{
  "title": "Named Display Updates",
  "authors": [{"name": "Paul Ivanov"}, {"name": "Kyle Kelley"}],
  "nteract": {
    "tags": ["ipython", "display updates", "progress-bars"],
    "description": "A Progressive look at updating outputs programmatically from IPython"
  }
}
```

<details>
<summary>
Expand this to see the HTML and CSS I mocked this with
</summary>

```html

<div id="hokey-header" style="
    font-family: &quot;Source Sans Pro&quot;;
    background-color: rgb(230, 230, 230);
    margin: 0px;
    padding: 50px;
    box-shadow: 0 1px 1px 0px #c5c5c5;
"><h1 style="
    /* padding: 100px; */
    /* background-color: lightgray; */
    margin-bottom: 30px;
">Learning About Display Updates</h1>
  <h2 style="
    font-weight: normal;
">By <i>Paul Ivanov, Kyle Kelley</i></h2>  
  <div style="
    /* background: #f1f8fa; */
    /* border-radius: 8px; */
    /* display: inline-block; */
"><p style="
    font-family: SourceSansPro-Regular;
    font-size: 18px;
    color: #4078c0;
    margin: 0 0.5em 0.5em 0;
    vertical-align: middle;
    text-align: center;
    padding: 0.2em 0.9em;
    display: inline-block;
    background-color:  #f2f8fa;
    border-radius: 3px;
">ipython</p><p style="
    font-family: SourceSansPro-Regular;
    font-size: 18px;
    color: #4078c0;
    margin: 0 0.5em 0.5em 0;
    vertical-align: middle;
    text-align: center;
    padding: 0.2em 0.9em;
    display: inline-block;
    background-color:  #f2f8fa;
    border-radius: 3px;
">progress-bars</p><p style="
    font-family: SourceSansPro-Regular;
    font-size: 18px;
    color: #4078c0;
    margin: 0 0.5em 0.5em 0;
    vertical-align: middle;
    text-align: center;
    padding: 0.2em 0.9em;
    display: inline-block;
    background-color:  #f2f8fa;
    border-radius: 3px;
">display-updates</p><p></p></div>
  
<p>
  This notebook demonstrates the new name-based display functionality in the notebook. Previously, notebooks could only attach output to the cell that was currently being executed.

</p>
</div>
```

</details>

Could be a good spot for us to try out using some WYSIWYG fields.

**Comment by captainsafia** [comment]
I like this! Per your styles, I assume the header will not be sticky?

**Comment by rgbkrk** [comment]
Sticky would be really cool, since you might be halfway through your document and want to update the header information.

**Comment by captainsafia** [comment]
Ah OK. I guess in that case we'd have to play around with the height to ensure that it doesn't take up a lot of real estate on the screen.

**Comment by rgbkrk** [comment]
That's definitely a good point too. The prototypes above are about as far as I'm going to go with this in the next few days, so it's pretty open for someone to tackle.

**Comment by mpacer** [comment]
I'm intrigued by this possibility and feel like there are two aspects to this proposal. 

On the one hand, having this information in an easily editable form would be amazingly useful.  

Laying out the information like this would be great for a variety of use cases (quick publication or keeping contact information available to students throughout a tutorial or talk).

But the display and the editing don't need to be handled in exactly the same way and their unification may not be good for all use cases (e.g., I generally don't like editing text at multiple different font sizes… I don't know if others share this dispreference but I am guessing that I'm not alone in this).

Fortunately, that seems like it would be easy enough to solve by having it visible in one mode and have it editable in another (perhaps triggered with a little ✏️  type icon that indicates "edit" in other cases). 

In terms of stickiness and ease of access vs. real estate concerns: is it possible to have an event trigger this to drop down attached to a small element (perhaps the same as the edit triggering element?), and make that element sticky (as opposed to making the title display itself sticky)?

**Comment by rgbkrk** [comment]
Yeah I was thinking this would be hidden by default and exposing some way of trigger it to show/hide.

**Comment by rgbkrk** [comment]
Re: sticky, I was thinking of this like an overlay that shows up only as you edit it.

**Comment by rgbkrk** [comment]
I'd still love to see this. We've got the mocks, our models for contents are getting more refined. It's probably worth tackling this during the next quarter.

**Comment by mpacer** [comment]
I’d be interested in working on it next quarter :), so I’m looking forward to chatting more.

**Comment by stormpython** [comment]
Most of this functionality was introduced with #4122.
