### ISSUE TITLE
Create a Table Transform for application/vnd.dataresource+json

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1526]
Create a transform (within `packages/`) to accompany https://github.com/pandas-dev/pandas/pull/14904. Mimetype is `application/vnd.dataresource+json`.

Useful links:

* Top level: http://specs.frictionlessdata.io/data-resource/
  * Expectation of row oriented data and schema
* Table Schema: http://specs.frictionlessdata.io/table-schema/
* https://github.com/frictionlessdata/datapackage-js/issues/65

Round one for this component can be a simple table. Since we'll have the raw JSON we'll be able to do client side sorting (for the data available), filtering, formatting, and even light visualizations.

**Comment by lgeiger** [comment]
Closed via #1534
