### ISSUE TITLE
Move notebook-preview-demo to new repo?

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1532]
`notebook-preview-demo` adds 27 MB to our repo's installed dependencies.

Since it's a demo package should we move it to a new repo in order to reduce the repo size and install time?

**Comment by lgeiger** [comment]
Or which is even simpler, we can ignore it with lerna to not install per default: https://github.com/lerna/lerna#--ignore-glob

**Comment by rgbkrk** [comment]
I like the ignoring option.

Getting rid of the demo would make me a teeny bit sad, it was nice using `notebook-preview-demo`  to work on frontend bits with live reloading and avoiding all the other electron app build stuff.

**Comment by rgbkrk** [comment]
This package has been deleted! Also it's now part of `@nteract/showcase`. 😄
