### ISSUE TITLE
"Save successfull" even though "cancel" or "esc" was pressed. Minor but still strange.

### ISSUE THREAD

**Issue by larssb** [nteract/archived-desktop-app#1548]
ENVIRONMENT DETAILS:
- Win7 v6.1.7601 SP1 Build 7601
- nteract v0.1.0

REPRODUCE:
1. open nteract 
2. do no more
3. click on the menu "file" --> "save" / or use ctrl+s
4. click on "cancel" or hit "esc"
5. "Save successfull!" message shown even though nothing was saved.
5a. after that the ".....new kernel needs to be launced" dialog comes up.

**Comment by jdetle** [comment]
I was able to reproduce this, this is totally a bug, thanks so much for reporting it!

**Comment by larssb** [comment]
Happy to help :-D.
