### ISSUE TITLE
nteract freezes on save a notebook including folium image

### ISSUE THREAD

**Issue by essicolo** [nteract/archived-desktop-app#1550]
With nteract version 0.1.0_amd64.deb, Ubuntu 16.04 (elementary OS).

As said in the title: nteract freezes on save a notebook including [folium](https://github.com/python-visualization/folium) image. To reproduce, download folium, open an example, show a map and save. No particular message raised in the terminal.

**Comment by rgbkrk** [comment]
We should try this again on the latest 0.8.x series. Thanks for reporting this @essicolo.

**Comment by willingc** [comment]
Next step: Try running a notebook using a folium image and report current behavior. The link for folium above includes example notebooks.

**Comment by essicolo** [comment]
I couldn't reproduce it with 0.12.3.
