### ISSUE TITLE
no kernels found?

### ISSUE THREAD

**Issue by amueller** [nteract/archived-desktop-app#1553]
I installed the debian package for nteract that you provide, but no kernels apart from the nodejs one were found, even though I have multiple python kernels. I tried to run 
```
python -m ipykernel install --user
```
to no avail.

**Comment by amueller** [comment]
I installed the dev version and now I see one kernel (not sure what happened to the other ones).
What's the normal way to install a dev version so that I can open notebooks by clicking on them again?
I don't have experience with java script packaging.

**Comment by alexandercbooth** [comment]
Hi @amueller,

Thanks for testing nteract! I think the following should work, but someone else please add to it if I missed something.
## Dev install
To install the dev version so that you can just double click a notebook to open, you can run the following command,
```bash
npm run dist
```
And then install the package from the newly created `dist` directory. After that you should be able to double click a notebook.

## Kernels 
Unfortunately, virtualenv and conda env kernels are not installed by default, but you can install one in the following way,

- First, activate the env (example with conda below with env named `amueller`)
```bash
source activate amueller
```
- Then, install the kernel,
```bash
python -m ipykernel install --name amueller --display-name "Python scikit-rocks"
```
where `amueller` is the internal Jupyter name and `Python scikit-rocks` is the name that will actually be displayed.

**Comment by rgbkrk** [comment]
What was the output when you ran

```
python -m ipykernel install --user
```

What's your output when you run:

```
jupyter kernelspec list --json
```

**Comment by amueller** [comment]
now I have
```
> jupyter kernelspec list --json
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/home/andy/.local/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/home/andy/anaconda3/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ],
        "language": "python",
        "display_name": "Python 3",
        "env": {}
      }
    }
  }
}
```
so that's the one kernel I added manually and that now shows up. I was a bit surprised that nteract doesn't show the same kernels that the notebook is showing, but this command doesn't seem to show them either... huh.

**Comment by amueller** [comment]
Maybe add a note to the docs that only kernels listed by that command are found and give instructions to add other conda envs as kernels. Also, the ``npm run dist`` would be good to add to the docs for npm noobs like me.

**Comment by amueller** [comment]
This is what I get when I run ``npm run dist``:
http://pastebin.com/S5yWUSx5
logfile contains
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dist' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle nteract@0.1.0~predist: nteract@0.1.0
6 silly lifecycle nteract@0.1.0~predist: no script for predist, continuing
7 info lifecycle nteract@0.1.0~dist: nteract@0.1.0
8 verbose lifecycle nteract@0.1.0~dist: unsafe-perm in lifecycle true
9 verbose lifecycle nteract@0.1.0~dist: PATH: /usr/share/npm/bin/node-gyp-bin:/home/andy/checkout/nteract/node_modules/.bin:/home/andy/.npm-global/bin:/home/andy/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle nteract@0.1.0~dist: CWD: /home/andy/checkout/nteract
11 silly lifecycle nteract@0.1.0~dist: Args: [ '-c',
11 silly lifecycle   'npm install && npm run clean && npm run build && build' ]
12 silly lifecycle nteract@0.1.0~dist: Returned: code: 255  signal: null
13 info lifecycle nteract@0.1.0~dist: Failed to exec dist script
14 verbose stack Error: nteract@0.1.0 dist: `npm install && npm run clean && npm run build && build`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid nteract@0.1.0
16 verbose cwd /home/andy/checkout/nteract
17 error Linux 4.8.0-39-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dist"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error nteract@0.1.0 dist: `npm install && npm run clean && npm run build && build`
22 error Exit status 255
23 error Failed at the nteract@0.1.0 dist script 'npm install && npm run clean && npm run build && build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the nteract package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && npm run clean && npm run build && build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs nteract
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls nteract
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
 I was able to do ``npm run start`` without a problem though (there were some warnings but no errors)

**Comment by jdetle** [comment]
Ah! I think its your node version? A lot of us use https://github.com/creationix/nvm to manage our node envs, we require greater than or equal to Node 6.

**Comment by lgeiger** [comment]
@amueller For building a release on linux with `npm run dist` you need additional dependencies. You can install them with:
```bash
sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
```

**Comment by amueller** [comment]
I did this:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```
shouldn't that get me the newest node?

Used nvm now.

**Comment by lgeiger** [comment]
I don't think it's a problem with your node version since `npm start` works fine.
On Linux `electron-builder` needs some dependencies that aren't installed with a normal `npm install`. Try the command I mentioned above 😄

**Comment by amueller** [comment]
I did your command and got further. I also needed libreadline6, trying again now.

**Comment by amueller** [comment]
kinda silly question but so JavaScript has the same problem that python has that you can't install C dependencies with the JavaScript package manager npm? You guys should use conda ;)

**Comment by amueller** [comment]
so ``npm run dist`` creates a debian file and I can install that?
Is there a way to do development "in place"?

**Comment by rgbkrk** [comment]
There's a tradeoff here -- if you want to be able to double-click to install notebooks, you have to install a copy (afaik). If you want to use the development copy in-place, you can still open notebooks with File -> Open. You're free to figure out a way to register your local dev copy on linux as the main one. @jarmokivekas is one of the developers on Linux -- the rest of us are on Windows and macOS.

**Comment by amueller** [comment]
ok cool :) I think I'm all set for now.
