### ISSUE TITLE
Rendering of markdown changes (on redraw?)

### ISSUE THREAD

**Issue by amueller** [nteract/archived-desktop-app#1558]
So I have this string in markdown:
``$40,000 or $40,001``

Which renders fine for a second, and then gets redrawn and renders as this:

![image](https://cloud.githubusercontent.com/assets/449558/24009450/67b31122-0a4b-11e7-8272-64a19584f16b.png)

**Comment by rgbkrk** [comment]
We implement Jupyter's version of MathJax which allows for inline `\LaTeX` between `$` and `$$` for block/multi-line. To use a literal `$` on a single line you have to escape it with `\\$`. There's a longer, more detailed explanation and (hopeful) extension point on the commonmark forums here: https://talk.commonmark.org/t/mathematics-extension/457/11

**Comment by amueller** [comment]
I had not noticed the behavior in Jupyter Notebooks (possibly because mathjax gives up on my notebook), but you are right, the behavior is the same. Sorry for the noise.

**Comment by rgbkrk** [comment]
> possibly because mathjax gives up on my notebook

That's interesting. I wonder if that's because nteract does mathjax rendering per display area rather than globally.

**Comment by amueller** [comment]
Generally nteract seems to be quicker in rendering my notebooks than Jupyter Notebook is btw. At least that's my gut feeling, no data involved ;)

**Comment by rgbkrk** [comment]
:smile: That's only going to get better over time too, there are a lot of optimizations to our loading of initial assets that we haven't gotten around to yet.

**Comment by amueller** [comment]
Last question (for now): Showing how little I know about this world, what's the framework called that you're using that lets you create native apps with JavaScript? Or maybe rather: what's the gui part?

**Comment by rgbkrk** [comment]
[Electron](https://electron.atom.io/) does the native bits (menus, dialogs, ...). We make [React](https://facebook.github.io/react/) components for the notebook UI.
