### ISSUE TITLE
File -> Open -> Cancel opens empty window

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#156]
When you hit "Cancel" in the open notebook dialog you get an empty window. I'd expect nothing to happen when doing that.

**Comment by rgbkrk** [comment]
Whoops!

This comes down to fixing up the [handling of the notebook launch](https://github.com/nteract/nteract/blob/af7e34b6eb975522d19b9e32b1e6624447b39a41/main/menu.js#L33-L34) to [check if `fname` is not `undefined`](https://github.com/atom/electron/blob/master/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options-callback):

``` javascript
if(fname) {
  launch(fname);
}
```
