### ISSUE TITLE
fourth level header is smaller than normal text

### ISSUE THREAD

**Issue by amueller** [nteract/archived-desktop-app#1560]
It looks like headers with
```
##### Some Header
```
are rendered in a smaller font than the body text. Is that on purpose?

**Comment by rgbkrk** [comment]
Likely not, I'm guessing it means that CSS wasn't written for h5 onwards.

**Comment by amueller** [comment]
that was my guess ;)

**Comment by rgbkrk** [comment]
We have the styles for this colocated in one spot, it shouldn't be too bad to fix. I added some labels so I can group it with other output changes I was planning on making.

**Comment by rgbkrk** [comment]
@stormpython -- something good to look at for quick wins in the UI
