### ISSUE TITLE
IRdisplay::display_html() not working as expected

### ISSUE THREAD

**Issue by cpsievert** [nteract/archived-desktop-app#1566]
In a Jupyter notebook, I see the expected result:

![screen shot 2017-03-20 at 10 30 49 am](https://cloud.githubusercontent.com/assets/1365941/24107336/71e3e152-0d58-11e7-94cf-6081f05ea91a.png)

However, using nteract 0.1.0, I see:

<img width="433" alt="screen shot 2017-03-20 at 10 30 41 am" src="https://cloud.githubusercontent.com/assets/1365941/24107327/6e0820d4-0d58-11e7-83c2-71dd5260e9b1.png">

**Comment by cpsievert** [comment]
Whoops, my mistake, that cell wasn't being interpreted as code...

**Comment by jdetle** [comment]
No problem, thanks for checking out nteract!
