### ISSUE TITLE
Improve the Data Resource Renderer

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1572]
* [ ] Handle multiple primary keys
* [ ] Tests!
* [ ] Fix up styling in the notebook preview component
* [ ] List number of rows shown vs. number available (users need to know not _all_ the data is there)
* [x] Embed the CSS with aphrodite instead of needing to include the stylesheets in our `index.html`
* [x] Figure out _something_ better with height
* [ ] Include a README for the package so it has some [light docs + pointers on npm](https://www.npmjs.com/package/@nteract/transform-dataresource)
* [ ] light vega based visualization
* [ ] Sorting
* [ ] Filtering (search?) - could be like https://datatables.net/

**Comment by TomAugspurger** [comment]
I didn't follow #1534 too closely, but if you run into any issues that are more easily handled on the pandas side, let me know!

**Comment by rgbkrk** [comment]
No problem, it's looking pretty good on the data side. We've mostly got UI/UX work ahead of us. I know what people are going to ask for next (filtering, sorting, etc. kernel side, triggered from UI)... Not touching that anytime soon though. We'll aim for consistency first. :smile:

Thank you again so much for pushing forward with a spec and getting it out there so we can make the table experience much better across Jupyter (and likely elsewhere)!

**Comment by gnestor** [comment]
The React components no longer depend on `react-virtualized/styles.css` and I just pushed some logic for handling expanded/collapsed output areas.

**Comment by rgbkrk** [comment]
Published this component just now!

```
npm install @nteract/transform-dataresource
```

Since we're missing a README on npm, I added it to the checklist here.

**Comment by rgbkrk** [comment]
Another thing we should also do is try to get this mimetype into IRkernel and PySpark.

/cc @rdblue @flying-sheep @takluyver @janschulz @holdenk

**Comment by rgbkrk** [comment]
Updated the todo above.

**Comment by rgbkrk** [comment]
Thanks to @gnestor this renders CSVs on commuter too, demo here: https://nteract-commuter.herokuapp.com/view/test.csv

**Comment by rgbkrk** [comment]
Done in #2732
