### ISSUE TITLE
mapbox 401 auth error

### ISSUE THREAD

**Issue by AlJohri** [nteract/archived-desktop-app#1574]
hi there,

I'm getting 401 unauthorized errors when trying to render maps.

![screen shot 2017-03-22 at 2 57 17 am](https://cloud.githubusercontent.com/assets/2790092/24185798/6d276c66-0eab-11e7-805b-dfcfe1e75a49.png)

seems like this line is the culprit: https://github.com/nteract/nteract/blob/master/packages/transform-geojson/src/index.js#L63

```
'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw'
```

could you perhaps expose setting your own access token in the code that overrides the default access token bundled with nteract?

thanks!

**Comment by rgbkrk** [comment]
Yeah I'm thinking two different ways of setting it in order of least to most precedence:

* The default as is here
* An environment variable `NTERACT_TILE_SET` or `NTERACT_MAPBOX_TOKEN`
* Metadata from the output. For example, like this:

```
IPython.display.display({'application/geojson': '...'},
  metadata={'application/geojson': {
    'tile_url': 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png...'
```

However, in looking, I see that @gnestor added on to the new `IPython.display.GeoJSON` to take these fields in https://github.com/ipython/ipython/pull/10288.

We'lll need to handle this metadata in our frontend components for the shipped app.

**Comment by gnestor** [comment]
I'll submit a PR to enable this. It's already been done in jupyterlab_geojson: https://github.com/jupyterlab/jupyterlab_geojson/blob/master/component/index.js#L25-L29

The usage with ipython 6:

```py
from IPython.display import GeoJSON

GeoJSON(data={
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-81.327, 296.038]
    }
}, 
url_template="http://s3-eu-west-1.amazonaws.com/whereonmars.cartodb.net/{basemap_id}/{z}/{x}/{y}.png", 
layer_options={
    "basemap_id": "celestia_mars-shaded-16k_global",
    "attribution" : "Celestia/praesepe",
    "minZoom" : 0,
    "maxZoom" : 18,
})
```

And the result: no more 401 errors and you can map coordinates on Mars!!

![image](https://cloud.githubusercontent.com/assets/512354/23238265/f90ebfa0-f915-11e6-9fba-17928a02f6f0.png)

**Comment by rgbkrk** [comment]
Whoooooa, that's super cool.

**Comment by AlJohri** [comment]
closing in favor of #1579
