### ISSUE TITLE
README Audit

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1577]
Some of our published packages are missing READMEs. To find out which (on a *nix machine), run: 

```
while read d; do   [[ -r ${d}/README.md ]] || echo ${d}; done < <(find . -type d -depth 1 -print)
```

Current packages missing READMEs:

* [ ] [`display-area`](https://www.npmjs.com/package/@nteract/display-area)
* [ ] [`editor`](https://www.npmjs.com/package/@nteract/editor)
* [ ] [`messaging`](https://www.npmjs.com/package/@nteract/messaging)
* [ ] [`notebook-preview`](https://www.npmjs.com/package/@nteract/notebook-preview)
* [ ] [`transform-dataresource`](https://www.npmjs.com/package/@nteract/transform-dataresource)

**Comment by rgbkrk** [comment]
I've labeled this as `new-contributor-friendly` and am more than happy to guide anyone who attempts to document any of these packages.

**Comment by aunyks** [comment]
I've checked out the `editor` package and would love to help out. However, I'm unsure about what you mean by documenting the package. Would you like a README to be created that explains how the component works? @rgbkrk

**Comment by rgbkrk** [comment]
> Would you like a README to be created that explains how the component works?

Yeah, similar to how we do [transfroms](https://github.com/nteract/nteract/tree/master/packages/transforms):

* How to install the package
* Basic usage of the component

On a side note, the easiest to start with are likely `display-area` and `notebook-preview`. Admittedly, as I look at `<Editor />` myself it's pretty unwieldy. The start might be to just list install there and how it gets used in `notebook-preview`.

**Comment by aunyks** [comment]
Very well! I'll get on it. It may take me a while since I'm in school, though. @rgbkrk

**Comment by rgbkrk** [comment]
It's ok if you do them one at a time too.

**Comment by rgbkrk** [comment]
New list:

```
$ while read d; do   [[ -r ${d}/README.md ]] || echo ${d}; done < <(find . -type d -depth 1 -print)
./commuter-frontend
./dropdown-menu
./editor
./fs-observable
./markdown
./messaging
./octicons
./transform-dataresource
./types
./vega-embed2
./webpack-configurator
```

**Comment by Ankk98** [comment]
@rgbkrk 
I would like to work on this issue.
Can you guide me on this?

**Comment by rgbkrk** [comment]
Great! Start with cloning the repository and reading through our [Contributing guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md). After that, we need a basic README for each package that says how to `npm install` the package (the package name is in the `package.json`). Each of the packages is in the `packages` folder and the ones without READMEs currently are:

```
iron-icons
octicons
markdown
dropdown-menu
logos
presentational-components
connected-components
vega-embed2
directory-listing
webpack-configurator
fs-observable
messaging
outputs
monaco-editor
styleguide-components
editor
```

It would be great if each README has some light descriptions and usage, though that can always be a follow up PR. To kick things off you may have to look at what the package does by checking out source as well as looking in the `package.json`'s description field.

**Comment by captainsafia** [comment]
Making good progress on this so far! Here's the list of packages that still need readmes.

```
./octicons
./ion
./logos
./vega-embed2
./webpack-configurator
./fs-observable
./styleguide-components
```
