### ISSUE TITLE
Create new cell by clicking between two cells

### ISSUE THREAD

**Issue by david-nagy** [nteract/archived-desktop-app#1578]
Would it be possible to have clicking between two cells create a new cell? I think clicking on the tiny dropdown button requires excessive accuracy for something that is done very often (at least for me). Also, this is how it works in Mathematica.

**Comment by rgbkrk** [comment]
I wondered how discoverable / easy the in between buttons are. You're making me think it should be one long flat button with two sides for code vs. markdown.

**Comment by jdetle** [comment]
I think it should also be text as opposed to logos for clarity.

**Comment by david-nagy** [comment]
Yes I think that would be very helpful! A further alternative that I can think of would be for the buttons (maybe even at their current size) to appear around the cursor when moving it between two cells instead of in the middle.

**Comment by rgbkrk** [comment]
> to appear around the cursor when moving it between two cells instead of in the middle

Yeah, I think we need to make the hover boundary much larger and then we can have that.
