### ISSUE TITLE
__file__ not defined?

### ISSUE THREAD

**Issue by AlJohri** [nteract/archived-desktop-app#1583]
I was just doing some pythonpath import hackery and noticed that `__file__` is not defined. is this by design?

**Comment by rgbkrk** [comment]
In the interpreter, ipython console, and jupyter notebook, `__file__` is not defined as well:

```
In [1]: __file__
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-adeb0343a89b> in <module>()
----> 1 __file__

NameError: name '__file__' is not defined

In [2]:
Do you really want to exit ([y]/n)? y
$ python
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> __file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '__file__' is not defined
```

While we do have a file here, [IPython](https://github.com/ipython/ipython) has no way (currently) to identify it.

**Comment by AlJohri** [comment]
ah got it. this should probably be closed then since its not relevant to nteract. do you know what repository would be best to raise this (if its something that should be raised)?

**Comment by rgbkrk** [comment]
Likely in ipython/ipython. However, you'll probably get some push back about how jupyter takes a position of kernels not knowing what frontend they're in. _If_ it were to be supported, new messages for the jupyter protocol would have to be established to make a cross-language way of handling this.

**Comment by AlJohri** [comment]
got it, I'm going to close this as wontfix for now
