### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by AlJohri** [nteract/archived-desktop-app#1584]
I apparently have muscle memory to press `a` to insert a code cell above my current cell and `b` to insert a code cell below my current cell.

I think this is from when I was heavily using jupyter notebook.

is there any interest in adding this same keyboard shortcut to nteract?

**Comment by AlJohri** [comment]
apparently I'm also pressing `dd` on top of cells to delete them. potentially a vim muscle memory but more likely from my notebook days as well

**Comment by rgbkrk** [comment]
From #1467:

> For some users, the command mode is needlessly complex and for other users it doesn't do nearly enough. In the desktop app we're currently catering to the much simpler end of the UI/UX spectrum on purpose to enable users that are not familiar with command mode interfaces (students, analysts, etc.). We've been fairly deliberate in not focusing attention on implementing the command mode and edit mode.

As a follow-on -- someone can implement and maintain this. I've been steering clear of implementing it personally.

**Comment by AlJohri** [comment]
Good to know, thanks!

I think I might be interested in implementing the command mode at some point, I have to read the code a bit more. Do you know off the top of your head if the state for whether a cell is being edited (edit mode) or a cell is just selected (command mode) is already implemented? Seems like I would have to first implement a shortcut for `Esc` that switches to command mode and then a series of shortcuts that only work when a cell is selected.

Also, to keep with the nteract shortcuts that are appended with `Cmd-Shift` and don't require  "switching modes", perhaps adding a `Cmd-Shift-D` shortcut to delete a cell would be a quick idea. Thoughts?

**Comment by ajasja** [comment]
@AlJohri I guess shortcuts will have to become configurable when nteract start to become seriously popular. Personally I would go for the shortcuts in jupyter noteboook, although `something`+`a` and `something`+`b` might also work.

**Comment by AlJohri** [comment]
@ajasja Seems there's already `Cmd+Shift+N` for creating a new code cell below so it's already deviating a bit from standard notebook shortcuts.

I think its reasonable to have a set of shortcuts that offer limited functionality without context switching like it does right now (i.e. only insert below, not above) and still have the full-fledged command mode that might take a bit longer to implement.

**Comment by BrenBarn** [comment]
> nteract is not seeking to be a replacement for all users - people can and should still flock to the classic Jupyter notebook as well as JupyterLab.

What I'm seeking is a thing that is exactly Jupyter/IPython notebooks, but on the desktop, without a web browser.  Are you saying that's not what nteract is?

**Comment by jdetle** [comment]
@brenbarn, nobody said that. Nteract is indeed a desktop based Jupyter notebook. Before it becomes an issue this and your last comment seemed somewhat brusque and unfair to people who donate their free time to make this software. Please make an effort to be cordial when voicing concerns about our work.

**Comment by BrenBarn** [comment]
I apologize, didn't mean to sound harsh there.  I sometimes have to remind myself that issue comment threads are not one big conversation and things that might seem just part of the chatter to one audience can appear to come out of nowhere when I start commenting on a different project! :-)

Nteract looks very cool and in fact I'm using it even as we speak.  But, to ask the same question in a hopefully less abrasive way: My initial impression of nteract was that it was Jupyter wrapped in some kind of mini-browser that allows it to be used on the desktop.  I was expecting the usage to be exactly like regular Jupyter, but in this desktop interface rather than a web browser.  What this thread made me wonder is whether the scope of nteract is in fact that, or more than that (i.e., aimed at developing a richer interface), or less than that (i.e., aimed at implementing a simplified Jupyter-like interface rather than just straight-up deploying Jupyter in a desktop environment).

**Comment by jdetle** [comment]
I'm so happy to hear that. My apologies if I came off as impolite. The goal of nteract is to be a desktop based notebook that conforms with the standard UI established by jupyter while also minimizing possible sources of friction for interactive computing.

**Comment by AStupidBear** [comment]
I also miss those shortcuts in jupyter. How can I split and merge cells?

**Comment by smoofra** [comment]
+1 I miss the shortcuts too.

**Comment by darribas** [comment]
+1 on bringing Jupyter notebook key shortcuts to `nteract`. I've just given it a spin and for the first time been able to get it to recognise the conda environment I wanted it to. This is seriously cool and can see myself using it for [my course](http://darribas.org/gds16/) in next iterations!

**Comment by blas-ko** [comment]
Is there a way to see the actual `nteract` shortcuts in any place? I've been finding myself doing everything "by hand".
Thanks!

**Comment by AlJohri** [comment]
@blas-ko does this help?
![screen shot 2017-09-23 at 12 24 11 pm](https://user-images.githubusercontent.com/2790092/30775030-25f7e370-a05a-11e7-842c-90bed8c77f54.png)
![screen shot 2017-09-23 at 12 24 14 pm](https://user-images.githubusercontent.com/2790092/30775031-2878bc78-a05a-11e7-819c-5e0ef5ab1847.png)
![screen shot 2017-09-23 at 12 24 19 pm](https://user-images.githubusercontent.com/2790092/30775032-29c846e8-a05a-11e7-909a-f6eaef4a06c2.png)

**Comment by lucainnocenti** [comment]
any news on this? Is something like a `Cmd+Shift+D` to delete cells going to be implemented at some point?

**Comment by mmagnuski** [comment]
I would also like nteract to have this. The only thing that keeps me away from using nteract is lack of keyboard shortcuts - I quickly get frustrated with lack of command mode and go back to jupyter / spyder-notebook.

**Comment by willingc** [comment]
The currently implemented keyboard shortcuts are documented here: https://docs.nteract.io/#/desktop/shortcut-keys

We recognize that not all are implemented. I'm closing this issue and encourage you to open a specific keyboard shortcut request if you would like something that is not already provided. Thanks. :sunny:

**Comment by rgbkrk** [comment]
I guess we probably need an issue for web and desktop for these, as we do need hotkeys on the web app. Desktop also doesn't implement everything in jupyter classic.
