### ISSUE TITLE
Refactor CSS to use a CSS in JS library

### ISSUE THREAD

**Issue by peggyrayzis** [nteract/archived-desktop-app#1590]
Before we export our React components into their own NPM package, we should discuss how we will approach packaging our styles. One suggestion is to refactor our CSS to use a CSS in JS library. Here's a starting point - let's edit this list together based on what you all think:

### Libraries
- [Aphrodite](https://github.com/Khan/aphrodite)
- [styled-components](https://github.com/styled-components/styled-components)
- [styled-jsx](https://github.com/zeit/styled-jsx)

### Features we need
- Theming support
- Keyframes for animations
- Pseudo-selectors like :hover
- Approachable developer experience
- Server side rendering

Theming support is probably what's most important to us right now. If we go the Aphrodite route, we need to discuss if we want to package our themes with the React components. Otherwise, we would only package the default theme and let the Electron app be the implementation of our components + themes. [Here's a gist of how to do themes in Aphrodite that explains some of the tradeoffs](https://gist.github.com/peggyrayzis/4dd15c0885540f856eccd50ab1c90f28). [react-with-styles](https://github.com/airbnb/react-with-styles) is a possibility here. [Context is another](https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076#.jnewxz2m0).

I believe [styled-components supports both options](https://github.com/styled-components/styled-components/blob/master/docs/theming.md), but I need to look more into it since I've never worked with it before. [Looks promising though](http://stackoverflow.com/questions/42796584/dynamic-theme-in-styled-components).

**Comment by rgbkrk** [comment]
Thanks for putting this together!

> we would only package the default theme and let the Electron app be the implementation of our components + themes

That is sounding pretty good to me.

**Comment by Madhu94** [comment]
[Glamorous](https://github.com/paypal/glamorous) might also be worth looking at, I think it was open sourced post @peggyrayzis's update.

**Comment by rgbkrk** [comment]
Now that I've been using several of these in different capacities, I'll first admit I love styled-jsx quite a bit. What pains me though is that we're stuck with some amount of global css due to codemirror. :(

**Comment by rgbkrk** [comment]
We're on styled-jsx now, wooooo! 🎉
