### ISSUE TITLE
quasi-vi keybindings (as exist in jupyter)

### ISSUE THREAD

**Issue by currymj** [nteract/archived-desktop-app#1601]
nteract has made my life a lot easier. Thank you! It's a wonderful project. In some ineffable way, it's better than jupyter in the browser.

However, I really miss the simple vi-inspired keybindings from browser jupyter. You could hit escape to move out of editing a cell, j/k to move up and down, a/b to insert a cell above or below, and m to convert to markdown. Enter to start editing again.

Would these be difficult to add?

**Comment by AlJohri** [comment]
Hi @currymj! There's some interest. PRs would be welcome for additional keyboard shortcuts. Tracking in #1584.
