### ISSUE TITLE
Error when starting windows installer: "TypeError: Path must be a string. Received null"

### ISSUE THREAD

**Issue by DavidPowell** [nteract/archived-desktop-app#1604]
I just downloaded and installed the 0.1.0 windows binary installer for nteract. Upon running from the start menu, I get the following two windows error boxes simultaneously appearing:

![javascript_error](https://cloud.githubusercontent.com/assets/1106295/24530066/33f40ae2-15fb-11e7-862a-c3c22ed8cf2f.png)
![no_kernels](https://cloud.githubusercontent.com/assets/1106295/24530065/33ee9d5a-15fb-11e7-9052-4093bf2d7066.png)

My OS is Windows 10 x64. I have several anaconda environments installed, but none of them are included in the windows path by default.

If I open a command prompt, activate my anaconda py3.5 environment, and manually run nteract.exe, then nteract successfully starts up and the REPL appears to work fine.

So while I have a workaround, it would be great to have a much better out-of-the-box experience.

**Comment by AlJohri** [comment]
might be related to https://github.com/nteract/nteract/issues/357

**Comment by DavidPowell** [comment]
@AlJohri I agree that this issue crops up when nteract cannot find a kernel. However, in my case this error handling fails and the program cannot start. I cannot see my specific error message mentioned in #357 so it's not a duplicate.

**Comment by maphew** [comment]
related: #1513

**Comment by rgbkrk** [comment]
How's this nowadays?

**Comment by DavidPowell** [comment]
I did a fresh install of 0.4.3. The problem seems to be fixed now.
