### ISSUE TITLE
feature: expand all cells for PDF print

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1610]
I see for each cell there is a cell menu option called `Toggle Expanded Ouput`. When I have a notebook and I'd like to print to PDF, I generally want to expand all my cells before printing. I've gone ahead and wired the functionality up, but before I pull request

What would the preferred option/behavior be?
1. Dialog box asking if the user would like to expand all cells before print (Yes|No). Cells are returned to their original state after print.
2. Menu option, Cell > Expand All Cells, Cell > Collapse All Cells.
3. Other suggestions?

I prefer 1 because I like to work with collapsed cells but just want to expand them for printing.
What are everyone's thoughts?

**Comment by rgbkrk** [comment]
I think that expanded by default on printing makes complete sense. We do the same thing for notebook viewer-like things. I realize this means it's not as easy as a stylesheet with that change.

**Comment by rgbkrk** [comment]
Side / separate note -- the hidden inputs/outputs settings should remain consistent while printing though (then you can have reports backed by code that don't show the code).

**Comment by rgbkrk** [comment]
Is this one done now with the current PDF code?

**Comment by willingc** [comment]
The hidden cells are left hidden when creating a PDF. If `Cell -> Unhide Input and Output in all Cells` is selected before saving a PDF the previously hidden cells are displayed and output in the PDF.

Closing as resolved
