### ISSUE TITLE
cell-toolbar-mask 50px padding prevent click

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#1614]
See below video. The 50px padding of the cell-toolbar-mask make the corner of the cell unclickable (greenish in below video). I'm going to assume the 50px padding have a reason, it seem to still work for me without this padding. 

![ctbm](https://cloud.githubusercontent.com/assets/335567/24726757/5956f69e-1a08-11e7-95fd-2a9f8908533e.gif)

**Comment by Carreau** [comment]
Did you meant to close this? That's unrelated to the PR I submitted.

**Comment by rgbkrk** [comment]
Oh whoops, thanks.

**Comment by rgbkrk** [comment]
This is fixed on master.
