### ISSUE TITLE
Cell returning error may reproducibly leave IU blocked on "busy".

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#1621]
Append randomly here is me in a gif reproducing it by executing the same cell many times in a row. I start by restaring the kenel:
![dangling-runing](https://cloud.githubusercontent.com/assets/335567/24771985/97f6bbac-1ac4-11e7-9806-07b83dd8a0bc.gif)

**Comment by Carreau** [comment]
Well, it might not be random, the notebook that triggers this always trigger it on the same cell for me. And above example alway hang on what should be input number `9`.

**Comment by rgbkrk** [comment]
Whoa.

**Comment by Carreau** [comment]
> Whoa.

I agree. 9 Is a weird number. It's likely because it's the first non-prime odd number greater than 2.

**Comment by rgbkrk** [comment]
Now that we have better kernel management (and unique internal IDs for them) I can't reproduce this at all anymore. What do you think @Carreau?
