### ISSUE TITLE
cell-drag : double drop zone

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#1624]
There seem to be a drag target above and below every cell. Should it be only on one side ? 
![double-drop-zone](https://cloud.githubusercontent.com/assets/335567/24778204/3872337c-1ade-11e7-939c-751209a2cc24.gif)

**Comment by rgbkrk** [comment]
Ideally it would only be one. This could be fixed if we only do the area below the cell as a drop target and then have the top area as a special drop target.
