### ISSUE TITLE
"Not saved yet" for freshly opened notebooks

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#1625]
The status bar says "not saved yet"for freshly opened notebooks. I guess when we open a notebook from a file we should set the last saved date to (at least) when the notebook is opened, if not the file modification date.

**Comment by rgbkrk** [comment]
Is this still happening?

**Comment by rgbkrk** [comment]
We now set fresh notebooks to use a `new Date()` so I think this is A-OK now.
