### ISSUE TITLE
Nteract freezes on save with R kernel

### ISSUE THREAD

**Issue by jackparmer** [nteract/archived-desktop-app#1630]
Nteract seems to freeze when using the Mac shortcut *command-S* with the R kernel. Nothing shows in the dev. console and the only solution I've found is to force quit. Saving seems to work when the notebook is sitting idle and not doing anything else - no autocomplete, computation, etc. 

To replicate, try pressing tab for autocomplete, then immediately pressing *command-S* on a Mac.

Screenshot of frozen-nteract ❄️ 

![image](https://cloud.githubusercontent.com/assets/1865834/24832602/ed4c622e-1c80-11e7-905a-1a2b15af7246.png)

Using the latest version (0.1.0).

Here's partial notebook I saved successfully using File > Save: 
https://plot.ly/~jackp/17525

**Comment by rgbkrk** [comment]
How's this nowadays?

**Comment by jackparmer** [comment]
Just checked  - no issue for me with the latest version on Mac 😀
