### ISSUE TITLE
Sign windows application

### ISSUE THREAD

**Issue by codingbutstillalive** [nteract/archived-desktop-app#1638]
Hi!

Would you please comment this scan result from www.virustotal.com.

<a href="https://ibb.co/f4qdT5"><img src="https://preview.ibb.co/mVdnMQ/nteract_vt_message.png" alt="nteract_vt_message" border="0"></a><br /><a target='_blank' href='https://de.imgbb.com/'>image uploader</a><br />

Even if it's only one alert, this needs to be explained.

**Comment by rgbkrk** [comment]
Does it say any more about what or how? I'm not sure what to make of this. Does any other standalone electron app report the same?

**Comment by lgeiger** [comment]
I guess this is because we don't sign our windows application yet. Here is a similar issue on the Atom repo: https://github.com/atom/atom/issues/3927

**Comment by codingbutstillalive** [comment]
Any news on this?

**Comment by rgbkrk** [comment]
We still need to sign our windows application. If you're worried about it, build it from source.

**Comment by rgbkrk** [comment]
Closing, since it's not our issue and Windows signing is tracked elsewhere.
