### ISSUE TITLE
notebook.cellMap properties not consistent across application

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1639]
In the main project there is a property in the store `document.notebook.cellMap.metadata.outputExpanded`. When I look at packages/commutable it calls this property `cellMap.metadata.collapsed`, which is both different and inverse logic. I ran into this while using commutable for unit testing.

I can attempt to resolve this with my pr for expanding cells for PDF print. Any issues with changing the commutable library to `outputExpanded`?

**Comment by rgbkrk** [comment]
I'm not sure. This seems like something we should have in metadata, either under our own `nteract` namespace or in whatever the standard metadata is for this.

**Comment by jkornblum** [comment]
Yes sorry it's in metadata under the cellMap, I've edited my first comment.
It looks like jupyter uses cellMap.metadata.collapsed. I can follow and update nteract to use collapsed as well.

**Comment by rgbkrk** [comment]
That's great, thanks @jkornblum! We may want to have some code in that does a migration from `outputExpanded` to (`!`) `collapsed` when we load to support current nteract users.

**Comment by rgbkrk** [comment]
Something else I'd love for us to standardize on -- the `hide_input` metadata: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/hide_input/main.js

**Comment by jcb91** [comment]
mm, nothing springs to mind, although I must admit I haven't spent much time on either of those recently!

**Comment by rgbkrk** [comment]
I _think_ we've standardized this a bit better now, so I'm going to close this.
