### ISSUE TITLE
Reduce package size of @nteract/transform-plotly

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1641]
I experimented with `plotly` inside Hydrogen and got it working quite well (The few minor things which do not work, are probably blocked by Atom's content security policy. Even with using https://github.com/atom/loophole).

### Problem

`@nteract/transform-plotly` works really great but has a package size of **99MB**! Though we only require `plotly.js/dist/plotly` (a few MB).

For nteract the package size problem will probably be solved by bundling all node modules with `webpack`. But for Hydrogen AFAIK this isn't easily achievable.

### Possible solution

Create a `@nteract/plotly` package which only includes the relevant `dist` file and use this package in `@nteract/transform-plotly`.
We can easily keep the package up to date using a few Travis scripts and greenkeeper.
As a bonus this will heavily reduce the dev install size of nteract and result in a faster install.

What do you think?

**Comment by rgbkrk** [comment]
I am definitely a fan of a reduced Plotly package, like our Mathjax one. It could probably even be built from the non-dist version so that it doesn't bundle it's own versions of d3, regl, etc. (That's part of the size problem)

**Comment by lgeiger** [comment]
> It could probably even be built from the non-dist version so that it doesn't bundle it's own versions of d3, regl, etc.

👍 We can look into that in the future. For now, I think using `plotly.min.js` (2MB unpacked) is a good compromise and already a huge improvement.

What do you think about calling the repo `plotly-electron` similar to `mathjax-electron` but releasing it as `@nteract/plotly`?

**Comment by rgbkrk** [comment]
Considering even Mathjax electron is due for a name change, I'd call the repo minimal-plotly. Package name @nteract/plotly sounds good!

**Comment by lgeiger** [comment]
Closed by #1642
