### ISSUE TITLE
cannot publish to gist

### ISSUE THREAD

**Issue by AStupidBear** [nteract/archived-desktop-app#1651]
![2017-04-15_121345](https://cloud.githubusercontent.com/assets/16422976/25062621/1000d29c-2202-11e7-864c-adbc8c21d4cf.jpg)
![2017-04-15_173736](https://cloud.githubusercontent.com/assets/16422976/25062631/399b22b0-2202-11e7-8bdb-878cac9110df.jpg)

**Comment by jdetle** [comment]
Hi, this is my fault. Would you like to pair program to fix it some time
next week?

**Comment by AStupidBear** [comment]
Sorry, I don't understand the phrase "pair program". Do you mean I fix it myself?

**Comment by jdetle** [comment]
No, I mean have a video call where we work on solving it together. I can
also try to figure it out myself, just wanted to extend the invitation if
you're interested

**Comment by jdetle** [comment]
Also, thank you for the issue report, we appreciate it!

**Comment by jdetle** [comment]
Closed by restarting the github.com/nteract/oauth-server and #1672

**Comment by AStupidBear** [comment]
thanks
