### ISSUE TITLE
right-click save image does nothing on Windows

### ISSUE THREAD

**Issue by dvincentwest** [nteract/archived-desktop-app#1655]
I have the git repo version of nteract from today (Apr 18).  When doing scientific plotting with matplotlib inline plots, if I right-click the plot image, a "Save Image" button comes up.  However, clicking on it does nothing. 
 I am on Windows 7, 64-bit

![image](https://cloud.githubusercontent.com/assets/9872343/25143118/e4e75d86-242e-11e7-9c31-b49367ff77a2.png)

**Comment by joecorkerton** [comment]
Did you check your `/Downloads` folder? On Ubuntu, if I save images there is no notification to show that it worked but the images are saved there

**Comment by dvincentwest** [comment]
Yes, I see.  I had 13 download.png files in my Download folder, just as you mentioned.  Thanks very much for sharing.  Very cool project.  I hope it continues to progress

**Comment by rgbkrk** [comment]
Thanks for reporting! I had no idea this behavior was happening. It seems we'd have to provide a dialog ourselves since it's not built in.

**Comment by jkornblum** [comment]
The package we're using for our menu (electron-context-menu) is using another package (electron-dl). electron-context-menu defaults to download the image to the downloads folder (which is default of electron-dl). It looks like electron-dl has an functionality to prompt save-as as an option. It just needs to be brought upstream to electron-context-menu.

It looks like there is an issue open already for this on the electron-context-menu GitHub page
https://github.com/sindresorhus/electron-context-menu/issues/13

Once I get through finals this semester :smile: I will try to fork electron-context-menu so we can use the functionality in nteract.

**Comment by dvincentwest** [comment]
Good luck with finals.  Perhaps its on the docket already, but a very commonly used functionality (for me anyway) in the Jupyter Notebook is to right-click and then copy the image to the clipboard.  Since I am mostly limited to Python coding I have no idea what this entails, but as long as we're discussing the issue of pictures, a copy to clipboard option would be very handy for workflow reasons.

Thanks again for the discussion of the issue
