### ISSUE TITLE
Underscores in inline LaTeX should not make the source italic

### ISSUE THREAD

**Issue by belteshassar** [nteract/archived-desktop-app#1663]
The markdown editor doesn't recognize underscores in inline LaTeX as subscripts, but formats the source as though the rendered text will be italic. The rendered text is correct though, so this issue is just a minor annoyance. Example below.

![image](https://cloud.githubusercontent.com/assets/12408997/25303323/7869d876-2750-11e7-92f4-b44a78423edb.png)

**Comment by SamRodkey** [comment]
Perhaps related, but I get weird issues with some of my subscripts that causes latex to not render at all when I type something like:

`$\hat{\dot{m}_{f_{s}}}$`

It works fine when I do this in other other LaTeX systems and jupyter.  Not sure what's up?

**Comment by rgbkrk** [comment]
Closed by #2350.
