### ISSUE TITLE
Show status of kernel in input area.

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#168]
![cell transitions](https://media.githubusercontent.com/media/nteract/mocks/b035014e316dce7bb35dcfb9232928bf16aa8557/cell%20transitions.png)

We need to make sure to show the input area reflect the current status of execution, whether this means `[*]` or the spinning bracket shown above and in #41.

**Comment by jdfreder** [comment]
I believe this is closed now
