### ISSUE TITLE
How to use/install npm packages.

### ISSUE THREAD

**Issue by romans127** [nteract/archived-desktop-app#1696]
Such as if I wanted to download d3.js or jquery.

**Comment by jdetle** [comment]
Could you please elaborate on the issue?

**Comment by romans127** [comment]
I have nteract desktop installed.  I would like to know how do I include
node modules in my notebook.  I get the module is undefined error when I
try to require it.  Understandably I havent installed it.  So I'm wondering
if there is some undocumented way to add 3rd party packages within the
notebook itself.

**Comment by rgbkrk** [comment]
If this is for use with the javascript kernel, it picks up `node_modules` relative to where the notebook is created. Example:

```
my_notebook.ipynb
node_modules/
  d3/
```

To install packages, you'll have to use a terminal separately to `npm install` them as ijavascript does not support magics (iirc).

**Comment by romans127** [comment]
Ah this answers the question.  Thank you very much .

**Comment by rgbkrk** [comment]
No problem, happy hacking!
