### ISSUE TITLE
"Save successful" even if user does not have permission to save in that directory

### ISSUE THREAD

**Issue by Swarchal** [nteract/archived-desktop-app#1698]
I'm still getting the "Save successful" notification despite being unable to save, e.g if I select a directory which I do not have write permission. I also get a similar issue with File -> Export PDF.

**Comment by jdetle** [comment]
I thought I had fixed this issue, I'll look into it

**Comment by rgbkrk** [comment]
We now have a `saveFailed` action this ends up triggering.
