### ISSUE TITLE
Unicode characters not displaying correctly

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1702]
Noticed while working on #1699 though this problem isn't caused by #1699.

**master:**
![master](https://cloud.githubusercontent.com/assets/13285808/26244365/9f4432a8-3c8f-11e7-9bb7-c47ac01ffe5a.png)
**0.1.0:**
![0 1 0](https://cloud.githubusercontent.com/assets/13285808/26244364/9f3d168a-3c8f-11e7-957a-bca052d0f5ce.png)

**Comment by rgbkrk** [comment]
After the latest copies of everything, this appears to be ok now:

![screen shot 2017-05-20 at 12 03 10 pm](https://cloud.githubusercontent.com/assets/836375/26278642/83f22044-3d54-11e7-8cb6-a5cd5289949c.png)

![screen shot 2017-05-20 at 12 04 20 pm](https://cloud.githubusercontent.com/assets/836375/26278643/87a8dcd2-3d54-11e7-9dae-9c521f81003c.png)

**Comment by lgeiger** [comment]
Strange, I just checked with latest master and still see this issue.

**Comment by rgbkrk** [comment]
Seeing this even now!

**Comment by rgbkrk** [comment]
errr, actually this is a-ok.

![screen shot 2018-01-03 at 3 42 54 pm](https://user-images.githubusercontent.com/836375/34544716-c9203524-f09c-11e7-83c9-864e4402f4b4.png)

**Comment by rgbkrk** [comment]
I'm going to assume we're good here.
