### ISSUE TITLE
Popup save as dialog if filename not set within save action

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#171]
From [TODO comment](https://github.com/nteract/nteract/blob/2d492c20a68b419280175cc86756719348dc95e3/src/actions/index.js#L65):

> Pop up save as dialog if filename not set

This should happen before the `subject.next({ type: START_SAVING })` and return after dispatching to `saveAs`.

**Comment by captainsafia** [comment]
Closed.

:tada:
