### ISSUE TITLE
Windows install does not run

### ISSUE THREAD

**Issue by gdbassett** [nteract/archived-desktop-app#1725]
I attempted to install the windows alpha build last weekend and received the following errors:

![nteract1](https://cloud.githubusercontent.com/assets/1392552/26645793/fc69c4de-45fe-11e7-941f-bc1cbf52c9a1.PNG)
![nteract2](https://cloud.githubusercontent.com/assets/1392552/26645795/fdc2ed7e-45fe-11e7-891e-5df16bebed09.PNG)
![nteract3](https://cloud.githubusercontent.com/assets/1392552/26645796/ff17af52-45fe-11e7-9d7d-f63719b33dba.PNG)

I actually attempted to install both a python and R kernel using the recommended methods and still receive the error when running. This is on a fully-patched windows 10 surface pro 4.

I don't know what you need from a diagnostic perspective.  I am not a node or javascript developer so don't have such development environments, but am happy to help diagnose however I can.

**Comment by maphew** [comment]
sounds same as #1513 (though release v0.1.0 there)

**Comment by rgbkrk** [comment]
I assume this ok nowadays?

**Comment by gdbassett** [comment]
Yep. Fine to close.
