### ISSUE TITLE
Text is blurry in the work area

### ISSUE THREAD

**Issue by adamsiembida** [nteract/archived-desktop-app#1730]
I tried the current Alpha for nteract on Windows 10 and I was having an issue with blurry text. For example, if I just turn on nteract and enter `5+5`, you can see that the  text is blurry. My guess is that the blurriness has something to do with subpixel antialiasing.

It might be hard to see from the screenshots, but if you look at the `In [1]` or the `10`, it should be noticeable. _Make sure you view the images in their native resolution.

- Blurry
![blurry](https://cloud.githubusercontent.com/assets/2823875/26808806/81c967ba-4a2d-11e7-96bd-124f51b80eac.PNG)

- Not blurry
![not-blurry](https://cloud.githubusercontent.com/assets/2823875/26808866/0005b412-4a2e-11e7-940f-996d0a343592.PNG)

- Closeups side by side
![blurry2_](https://cloud.githubusercontent.com/assets/2823875/26809129/4e343454-4a30-11e7-8d15-1c221d4ba27d.PNG) ![not-blurry2_](https://cloud.githubusercontent.com/assets/2823875/26809134/590832ea-4a30-11e7-82a6-e109bf56936e.PNG)

**Workaround:** I found an interesting thing that if you do View >> Reload, that the blurriness goes away. This might help in figuring out what is causing the blurriness.

**Comment by rgbkrk** [comment]
Two things were causing this issue -- the classic theme and an overriden line-height. Now that we've removed the classic theme and the typography is not awkwardly changed, this is not an issue.
