### ISSUE TITLE
Add way to deselct a cell for printing

### ISSUE THREAD

**Issue by adamsiembida** [nteract/archived-desktop-app#1734]
Right now I am using the classing theme. This means that when a cell is selected, it has a green border around it. Other themes also have some indication of which cell is selected.

During printing (to PDF) it seems that even the cell selection indication also prints. I don't believe that cell selection has any relevance to a printed document.

I suggest adding a way to deselect all cells. For example, pressing the escape key might be a way to do that. I also find the cleaner look without having anything selected would be nice for non-interactive presentations using nteract directly (i.e., without printing).

Additionally, it might make sense to automatically deselect everything during printing as well.

**Comment by rgbkrk** [comment]
Thanks for reporting this!

The light theme has a stylesheet for printing that makes the selected cell styling not show. It seems like the same work needs to be done on the classic theme.

**Comment by Madhu94** [comment]
@rgbkrk How about the ability to choose which cells you want to print? Just like Word allows us to print specific pages of a document. Just a suggestion - don't even know if nteract already has something like this.

**Comment by rgbkrk** [comment]
@Madhu94 You can hide inputs and outputs using the cell's toolbar. Only visible cells will be printed.

**Comment by Madhu94** [comment]
Oh, right. (I think) you can add the new-contributer-friendly label to this ticket too. @rgbkrk
