### ISSUE TITLE
Ctrl + Enter should hide the code for a Markdown cell (not just Shift + Enter)

### ISSUE THREAD

**Issue by adamsiembida** [nteract/archived-desktop-app#1735]
If you are editing a Markdown cell, you see both the text that you are typing, as well as the Markdown rendering of that text. When you press `Shift + Enter`, the text entry part of the cell closes, and all you are left with is the rendered markdown.

However, `Shift + Enter` also creates another cell below, which is not always desirable. This is especially noticeable when you have a Markdown cell in the middle of the document. The only way to hide the edit box is to use `Shift + Enter`, and then manually delete the extra cell that was created.

I believe that `Ctrl + Enter` should have a similar behavior, as far as closing the edit box in a markdown cell, and leaving only the rendered Markdown... without the extra line being inserted.

**Comment by adamsiembida** [comment]
After playing with this some more, I realized that using `Shift + Enter` doesn't actually create a new cell below the current cell, it just selects the next cell. Unless you are editing the bottom cell.

I still feel that using `Ctrl + Enter` should hide the text editing box. This would also be more consistent to the Jupyter web interface, where pushing `Ctrl + Enter` means that you are done editing that markdown cell.

I guess I'd be interested to hear what other people think.

**Comment by rgbkrk** [comment]
I totally agree that ctrl-enter should hide the text editing box on Markdown. This was a regression in 0.1.0.

xref: #1444

**Comment by snotskie** [comment]
Agree as well. I'm using nteract to write Lab assignments for teaching, so most of my work is in Markdown with the occasional code cell, so it's tiring to shift-enter through everything when I only needed to fix a typo in one of the top Markdown cells.

**Comment by rgbkrk** [comment]
Since we've finished off some recent refactors I decided to go after this one, fixing it in #2327. One thing with markdown and cell focus that I'd love to have back is the ability to move between cells when markdown is in view mode still. Something to tackle later!

**Comment by rgbkrk** [comment]
Went ahead and tackled the markdown navigation issue too. We will get a release out shortly.
