### ISSUE TITLE
Can't click the hover controls when cell is at the bottom of the window

### ISSUE THREAD

**Issue by adamsiembida** [nteract/archived-desktop-app#1736]
I can't click the controls that appear when you mouse over the bottom of the cell (e.g., the new markdown or code cell) when the cell is at the bottom of the window.

You can't see my mouse in the screenshot below, but it is was over the markdown button when I took the screenshot; the button isn't highlighted like it would normally be on mouseover. Clicking on it has no effect.

![12](https://user-images.githubusercontent.com/2823875/26992423-a11490e8-4d2c-11e7-862e-a3a910c75ebd.png)

I don't have any issues when the cell isn't at the bottom of the application window.

**Comment by rgbkrk** [comment]
Is this better now that we've added more padding?

**Comment by adamsiembida** [comment]
Yeah, it's better. Doesn't seem to be an issue now!
