### ISSUE TITLE
Freeze on large output

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#1737]
Not sure if this has been addressed already, but any large output and my cells causes the entire window to lock up, can't scroll or see output.  Might be long logs + long output (< 1mb).  I remember it happening on both Windows and Mac.

I am willing to work on it if someone can point me in the right direction.  I tried the ijavascript kernel on top of nteract (as opposed to Nodejs nteract) and same problem.  I don't think it is limited to just the Nodejs (nteract) kernel.

**Comment by jdetle** [comment]
@megamindbrian, this is a known issue and something that is rather difficult to solve.

I encourage you to look into both the [jupyter messaging spec](http://jupyter-client.readthedocs.io/en/latest/messaging.html) and our own source code in `src/notebook/epics/execute`, most specifically, "handleFormattableMessages". 

What is happening is that APPEND_OUTPUT actions are piling up without being handled. https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md, checkout this link for more info on how to possibly fix this backpressure problem.

**Comment by ghost** [comment]
Strange. Certainly it's not enough text that it couldn't be stored in
memory until electron can add it to the DOM. I noticed at the end of my
HTTP notebook it says "...and 33 more lines". Is that the feature that
would need to be adapted to nteract? Adding a tagline with truncated output?

This thread talks about a config setting for how many lines to output, is
this related?

https://github.com/ipython/ipython/issues/6516

**Comment by jdetle** [comment]
Yes! It looks like you're on the right path. I think we might be able to figure out how to spawn kernels with iopub rate limited https://github.com/jupyter/notebook/pull/931, lets talk on slack. https://slackin-nteract.now.sh/

**Comment by loretoparisi** [comment]
I can confirm that this happens in version `0.10.0 (0.10.0)` with JavaScript kernel, when output has a significative number of chars, like 2-5KB.
