### ISSUE TITLE
shouldComponentUpdate optimizations

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#174]
Since we're relying on Immutable.js, we could be using the PureRenderMixin or rolling our own version of shouldComponentUpdate. The fact that we're immutable data first means we can follow the [advanced performance guidelines](https://facebook.github.io/react/docs/advanced-performance.html) in React.

**Comment by rgbkrk** [comment]
Ken Wheeler let me know about a few more options and some patterns with `shouldComponentUpdate`. Then @kenwheeler had this to say:

> Ken: Most of the time we do it by hand for micro optimization
> Kyle: Ok, I'll not worry about it for now
> Ken: Perf day will come
> Ken: Oh it will come
> Ken: You will be so glad you used immutable

On the right path then and we can keep on going until that optimization day. Great engineering mindset.

**Comment by jdfreder** [comment]
Makes sense to me

**Comment by rgbkrk** [comment]
I'll close this and when we're focused on perf, we can dive in direct with real benchmarks to motivate how we proceed.
