### ISSUE TITLE
User-defined custom themes

### ISSUE THREAD

**Issue by airdrik** [nteract/archived-desktop-app#1753]
I'd like to put together my own custom theme for Nteract (primarily changing the fonts and syntax highlighting scheme (though I am digging the "nteract" theme colors, and may not change much there)), preferably without having to download the source and add it there.
Is there currently a way to load up user-defined themes?  If so, how? If not, would you please provide a way to do so?

Thank you in advance.  
This tool looks and feels amazing.  I'm excited to see where this goes!

**Comment by rgbkrk** [comment]
I'd certainly like that to be configurable and easy to setup. I don't have the cycles for it at the moment personally though.

**Comment by airdrik** [comment]
I understand, you've got a lot going on here.  I figured I'd submit the issue and whenever it gets tackled (weeks,  months, whatever) is fine.

**Comment by Madhu94** [comment]
@rgbkrk I'll have a shot at this? If I manage to bring in #1166. We can try imitating [Mattermost ](https://docs.mattermost.com/help/settings/theme-colors.html#custom-theme-examples) here - just a suggestion because I liked this interface -
![image](https://user-images.githubusercontent.com/9015820/27502328-d83b1f5a-5890-11e7-8c12-e7928098250d.png)

**Comment by rgbkrk** [comment]
Thanks @Madhu94! We do have an `nteract.json` that gets placed in jupyter config dir you can persist to that lets you set the theme by name, which at least makes it a starting point to work at this for persisting the setting and where to read it from.

> I understand, you've got a lot going on here. I figured I'd submit the issue and whenever it gets tackled (weeks, months, whatever) is fine.

Thanks @airdrik, happy to see you're using nteract. :smile: I'll be spending more cycles :soon: so we can get the next release out. 😀

**Comment by essicolo** [comment]
I'm adding here these suggestions for improvements from version 0.2.

1. Ability to turn off markdown preview.
2. Improve markdown:
    - title numbering
    - [bibtex references](https://github.com/takluyver/cite2c)
    - equations, tables, and decorations like `<div class="alert alert-block alert-info"></div>`  are not working).

**Comment by rgbkrk** [comment]
In the time since this issue was opened we both gained new themes and then reduced back to only light and dark due to a lack of cycles to keep porting themes to new structures. We now have a declarative set of base styles and really need to figure out how we'd expose configurability for theming.

cc @theengineear

**Comment by rgbkrk** [comment]
@essicolo can you make new issues for each of those feature requests?

**Comment by ghost** [comment]
HI, Im a newbie. I want to change font and syntax color how can I do that?
A comprehensive guide will be much appreciated.

Thank you

**Comment by n49o7** [comment]
@rgbkrk Why not use simple YAML or LESS files that specify CSS ? For instance :

```
input:
    fg              : 000
    bg              : FAFAFA
    fg (selected)   : FFF
    bg (selected)   : F0F
    strings         : E1C741
    numbers         : 41E194
    booleans        : 4164E1
    keywords        : A441E1
    methods         : 333
    comments        : 888
output:
    fg              : 000
    bg              : FFF
    fg (selected)   : 000
    bg (selected)   : 0FF
```

Ideally the font would be specified in the general preferences :

```
theme:
    input:
        font          : AnkaCoder Narrow
    output:
        font          : AnkaCoder Narrow
layout:
    frame padding : 0
    cell margin   : 0.5em 0
```

**Comment by willingc** [comment]
Hi all,

As recommended by @rgbkrk, let's open more specific feature requests related to themes instead of keeping this larger, general issue open. As a first step, I've opened https://github.com/nteract/docs/issues/46 to document "themes". I'm going to close this issue.
