### ISSUE TITLE
Inconsistent pinned cell layout, no spacing for pinned cells

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1760]
When I pin more than one cell, the layout changes depending on the theme used (nteract theme has a large space). Also most themes do not have spacing between the cells which makes it not so pleasant to view.

Ideally, I would think that pinned cells would have the same layout as the notebook (i.e. a little bit of space between them). 

Here are few examples.

light theme (no space)
![light](https://user-images.githubusercontent.com/5368903/27655329-9f2a3462-5c0a-11e7-9114-85162e8d3269.png)

nteract theme (has space)
![nteract](https://user-images.githubusercontent.com/5368903/27655336-a40d2f7a-5c0a-11e7-9391-39d084a3007c.png)

classic theme (no space, better visibility due to ui)
![classic](https://user-images.githubusercontent.com/5368903/27655340-a7d9cd48-5c0a-11e7-947a-63522ccfc8a7.png)

**Comment by rgbkrk** [comment]
We've... taken out pinned cells so... I think this is fixed by virtue of there not being a feature to fix...

😬 Let me know if you badly want pinned cells back, they were a bear to maintain.
