### ISSUE TITLE
Error Output should be visibly different than Standard Output

### ISSUE THREAD

**Issue by Jaykul** [nteract/archived-desktop-app#1764]
Currently, Error output looks the same and normal plaintext output.

I like the way Jupyter notebooks show Error output with a red background -- although I don't like their shade of red, at least one can distinguish errors from success output without even reading the text...

**Comment by willingc** [comment]
Let's review this to see if this is still the case on master.

**Comment by captainsafia** [comment]
I'm gonna go ahead and close this out as no repro.

nteract represents `error` outputs from the kernel using the same ANSI-based display that Jupyter does so I'm not sure what the error means. Please re-open if this is still relevant.
