### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#177]
In addition to the notes in the contributing section, I think we should have a contributing document that specifies the following
1. What do I need to know to help?
2. How do I set up the development environment?
3. A brief explanation of how the C.4 changes our contributors cycle, since the C.4 document is a bit tough to digest in and off itself.
4. In line with 3, emphasize that we expect things that are "complete-ish" and prefer to merge and iterate than iterate and merge.

Thoughts?

cc: @rgbkrk

**Comment by rgbkrk** [comment]
Definitely agree we need this, it's scattered across the README at the moment as we figured out more we needed to say. Time to simplify and provide clean easy to read prose.
