### ISSUE TITLE
Screen jumps on "shift+enter" for pinned cells

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#1789]
When you have cell pined and run the cell through "shift+enter" the screen will jump to where that cell is located. I'm not sure what "shift+enter" should do with a pinned cell, should it create a new cell / focus next or nothing? It feels like bad UX that the screen jumps even with "shift+enter" when the cell is pinned.

Me running cell through button and then with "shift+enter"
![nteract-pinned-cell-jump](https://user-images.githubusercontent.com/5368903/28243148-94d97148-6985-11e7-8315-785551c36c8d.gif)

**Comment by rgbkrk** [comment]
Yeah I think the screen shouldn't refocus when running a pinned cell. It should stay fixed.

**Comment by captainsafia** [comment]
I'm working on fixing this right now.
