### ISSUE TITLE
New tools?

### ISSUE THREAD

**Issue by welien** [nteract/archived-desktop-app#1790]
Could you please add something for:

- code completion
- linting
- libraries docs (numpy, pandas, plotly etc.)
- new themes

Maybe you could incorporate all of this by adding some kind of nteract package manager with custom user-made plugins.

**Comment by Madhu94** [comment]
@Arcanius There are open issues for the features you are asking for. You can see 
#1753 (I'll get around to this real soon) and #1504

I couldn't find one related to linting though. @rgbkrk would you like to comment here?

**Comment by rgbkrk** [comment]
Haven't worked on any linting tools, would be nice to have.

**Comment by essicolo** [comment]
I’m adding these suggestions for improvements from version 0.2. 

1. Ability to turn off markdown preview.
2. Improve markdown:
    - title numbering
    - [bibtex references](https://github.com/takluyver/cite2c)
    - these doesn't work: equations, tables, and decorations like `<div class="alert alert-block alert-info"></div>`.
