### ISSUE TITLE
Multiple tabs in one window

### ISSUE THREAD

**Issue by astrosmith** [nteract/archived-desktop-app#1792]
Great app! It would improve my workflow if nteract allowed for multiple tabs per window.

Also, if there was a quick view previewer from finder with spacebar for Mac. Not sure how feasible that would be though.

**Comment by BenRussert** [comment]
There is a closed issue w/ discussion on this #910.

I'm a fan of having an atom + [hydrogen](https://github.com/nteract/hydrogen/) text editor running multiple tabs if needed and a second window w/ a notebook. Perhaps this would be good for you too? :smile:

**Comment by astrosmith** [comment]
Thanks for the suggestion. The atom + hydrogen is pretty cool but it looks like it only works on .py files rather than .ipynb files. Am I missing something?

I found nteract looking for a native notebook application. Working in a browser can be annoying. Why not short circuit the terminal to preview and open notebooks? nteract is just the thing! I realize this is a convenience feature request, but window organization quickly becomes unwieldy while working on different projects at once. Tabs would definitely improve the utility and attract more users. Thanks.

**Comment by rgbkrk** [comment]
As for the quick previewer, see #305. I'm certainly a fan of us having a quicklook plugin. I don't have the stomach for an XCode project at the moment though 😅.

**Comment by willingc** [comment]
I'm closing this issue. We can track additional activity on #305.
