### ISSUE TITLE
Move more base modules into monorepo

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1794]
All of these depend on `jupyter-paths` which means we end up going through a massive "migrate these packages" run through:

* [x] `enchannel-zmq-backend`
* [ ] `spawnteract`
* [ ] `jupyter-paths`
* [ ] `kernelspecs`

Let's just bring them all together.

**Comment by rgbkrk** [comment]
The way I'm currently doing this:

In the original package:

```
git checkout -b move-to-monorepo
mkdir -p packages/NAME
git mv !(packages) packages/NAME/
git mv .SOMEFILE packages/NAME # Catch the dotfiles

# Double check things first
git commit -am "preparing NAME for move to monorepo"
```

In the monorepo (on branch "another-merger")

```
git remote add tmpNAME /Path/To/NAME
git fetch tmpNAME
git merge tmpNAME/move-to-monorepo --allow-unrelated-histories
# Make commit message be:
# chore: merge X into monorepo
```

**Comment by smashwilson** [comment]
Here's a (completely untested) way to do this with a [git subtree](https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt#L243-L261):

```
git subtree add --prefix=packages/${NAME} git@github.com:nteract/${NAME}.git master
```

This gives you the option of preserving the _full_ git history for the package repo, including contributor credit, blame, and whatnot. If you just want a single commit it accept a `--squash` argument too.

**Comment by rgbkrk** [comment]
Sadly, it looks like it doesn't like when the prefix already exists:

```
 (the-subtree-ash-way) kylek@nfml-83G ~/code/src/github.com/nteract/nteract$ NAME=enchannel-zmq-backend git subtree add --prefix=packages/${NAME} git@github.com:nteract/${NAME}.git master
prefix 'packages' already exists.
```

**Comment by rgbkrk** [comment]
It should be easy to import the other 3 now, not a big deal at the moment though.

**Comment by rgbkrk** [comment]
Finally bot, I agree with you. We likely `wontfix` these. 😄
