### ISSUE TITLE
Add "Open Recent" menu in File menu.

### ISSUE THREAD

**Issue by Jaykul** [nteract/archived-desktop-app#1795]
Since there's no root window like Jupyter has, it sure would be nice to have nteract remember my most recent notebooks -- I mean, the example notebooks are neat, but only for the first day or two ;-)

You know, like this one:
![image](https://user-images.githubusercontent.com/192942/28445702-1a60f6da-6d94-11e7-937f-137ff7b6b211.png)

**Comment by dhirschfeld** [comment]
**xref:** #263

**Comment by rgbkrk** [comment]
Closing as dupe of #263, totally agree we need this. :smile:
