### ISSUE TITLE
IPython help broken

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1804]
On win64, running master from Jul 25 the IPython help doesn't seem to be working .

e.g. neither `function?` nor `?function` bring up the help for the function. `help(function)` does however seem to work.

cc: @Carreau, @rgbkrk

**Comment by dhirschfeld** [comment]
This is still the case in the latest `0.3.2`. Just pinging this issue to make sure it hasn't been forgotten...

By-and-large I find nteract pretty slick! ...but I'm hesitant to recommend it to less experienced colleagues if the standard `?` help functionality doesn't work - that's pretty important for new users.

**Comment by rgbkrk** [comment]
😢  Yeah I've been meaning to dig back into this one. For now I've resorted to `help(obj)`. I'll prioritize this for the next release.

**Comment by alekzvik** [comment]
This is not only win issue, also broken for mac

**Comment by rgbkrk** [comment]
Fixed in https://github.com/nteract/nteract/pull/1965, we'll get this shipped out within the next day or so.
