### ISSUE TITLE
Function signature tooltips not displaying?

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1805]
On win64, running master from Jul 25 I can't seem to bring up the function signature tooltip.

#1488 seems to suggest `Cmd-.` should work, but on Windows none of `Ctrl-.`, `Alt-.` nor `Win-.` appear to bring up the tooltip.

**Comment by chaoyangnz** [comment]
+1

**Comment by rgbkrk** [comment]
I wonder if this is related to the change on codepoint handling for codemirror.

**Comment by xiaoweiz** [comment]
Not working on OS X either. (version 0.3.1)

**Comment by dhirschfeld** [comment]
With the latest 0.8.4 I still can't seem to bring up the function signature tooltip

**Comment by rgbkrk** [comment]
On my mac it's <kbd>ctrl</kbd>+<kbd>.</kbd>.

**Comment by rgbkrk** [comment]
However, I can't seem to close the little popup for it. 😲

**Comment by dhirschfeld** [comment]
Do you know the key combo for windows - I can't seem to trigger it. 

It would be nice if it were Shift-Tab as in jupyterlab to better make use of muscle memory.

**Comment by rgbkrk** [comment]
> It would be nice if it were Shift-Tab as in jupyterlab to better make use of muscle memory.

Yeah I think it's about time we bring in the Tab and Shift-Tab bindings.

**Comment by rsrini7** [comment]
Its working in windows with "Ctrl + ." . But its overlapping with background cells.

![doc-string-overlapping](https://user-images.githubusercontent.com/5178105/46820502-fa72f000-cda3-11e8-8534-e5b9c14044b7.png)

**Comment by BenRussert** [comment]
Closed by #4453
