### ISSUE TITLE
Export .py as a menu option

### ISSUE THREAD

**Issue by karkraeg** [nteract/archived-desktop-app#1815]
Hi!

Will it be possible in a future Version to save as *.py file? Right now I have to use `jupyter nbconvert --to script Notebook.ipynb` from Terminal everytime I want to save a ipynb as py file.

**Comment by Jaykul** [comment]
It would need to be a more generic feature though: *Export as Script*, so that you can export a file with the appropriate extension (and/or shebang?) based on the kernel in use.  Not sure nteract needs to know which extension that is (could let the user specify the file name).

**Comment by rgbkrk** [comment]
The kernel info response usually contains this (from the kernel), so we'd be able to handle converting to a script directly.

**Comment by rgbkrk** [comment]
We now store the kernel info with the kernel object and could start using that with a new menu entry.
