### ISSUE TITLE
nteract freezes when trying to save a large plot

### ISSUE THREAD

**Issue by bluprince13** [nteract/archived-desktop-app#1819]
If I make a large plot, it works and I can see the graph. However, it freezes when I try to save it.

```
import pandas as pd
import numpy as np
import plotly.offline as py
import cufflinks as cf
cf.go_offline()

df = pd.DataFrame(
    np.random.randn(300, 100),
)

fig = df.iplot(kind='heatmap')
```

**Comment by rgbkrk** [comment]
Thanks for reporting.

Are you willing to run from master to see if this is any better?

**Comment by bluprince13** [comment]
No problem. Yep, just tried it. If I reduce the number of points to (50, 100) - it takes a few seconds to save. It takes longer if I increase the number of points. While it's saving, it freezes, and the user can't do any editing.

At (25,100) it took 4 seconds.
At (50,100) it took 10 seconds.
At (100,100) it took 30 seconds.
At (150, 100) it took 1 minute 36 seconds.

The generation of the plots is fast, O(1s),  and similar for all cases.

**Comment by jkornblum** [comment]
Yeah I'm seeing worse time than this on master on an older 1.8ghz macbook air.
The file .ipynb file generated is about 5-6 MB.

**Comment by rgbkrk** [comment]
This is still an issue, I just tried it with the latest release.

**Comment by willingc** [comment]
Next action: Try to reproduce on latest release and document results.
