### ISSUE TITLE
Documentation strategy and information architecture

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#182]
This will belong in wherever we end up collating all of this. In the meantime I'll start posting some example mocks and information architecture.

![docs-layout](https://cloud.githubusercontent.com/assets/836375/13310576/d0016758-db4c-11e5-92c7-240580e6e0e9.png)

Generally, what I'd like to see are a few narrative style guides on enchannel, commutable, and generally how one would build a notebook application (to help our own development and onboard new people).
- [x] Introduction to Immutable Documents with Commutable
- [x] Build your own REPL with enchannel-zmq-backend
- [ ] Transform mimetypes+data to HTML
- [ ] Write your own notebook application

Then we'll want to host very API-centric documentation for Commutable, Enchannel, Transformime, spawnteract, etc.

**Comment by jdfreder** [comment]
I like the layout aesthetically, but I think the information could be rearranged.  For example, instead of saying "Enchannel" and having a list of implementations, maybe say "Connecting to a Backend".

Also, any mocks for one of the doc pages (not the homepage)?

**Comment by rgbkrk** [comment]
Ah that's true. Simple easy to read language. Enchannel is just what we call it so we can ship with a short name.

**Comment by betatim** [comment]
Agree with @jdfreder that the witty names are cool but a bit tricky for newcomers. Could be solved by having something in the left hand column that uses plain language to walk you through the various parts and how they plug together so that you know the fancy names afterwards.

**Comment by captainsafia** [comment]
I think the mockup is a great design, but I would make some adjustments to the colors. For the sake of improved accessibility for vision-impaired users, we should increase the contrast in the colors that we use for the webpage. I'll cook up my thinking of the colors in Sketch.

Let me  try writing the Immutable/Commutable dev guide in the same voice as the CONTRIBUTING.md I just PRed.

**Comment by rgbkrk** [comment]
Sweet!

Something I haven't stated for why I tend to use gray in design - there's less focus on the colors and more on the contrast, layout, architecture. We definitely need more contrast in the above mock, which can even be in black and white too. This helps steer us clear of the risk of colorblind discussions when we're trying to lay out the content/prose.

**Comment by rgbkrk** [comment]
@captainsafia I'm going to create nteract/docs for now and look forward to your PR!!!

**Comment by captainsafia** [comment]
_sweats nervously_

**Comment by jdfreder** [comment]
Don't sweat @captainsafia !  I need to get around to doing a few other nteract things first, and then I can take a crack at this.  If I get to this, I'll ping you first to make sure I'm not stepping on your toes.

**Comment by captainsafia** [comment]
Harhar, no worries on that @jdfreder! I was trying (and failing) to be funny.

**Comment by rgbkrk** [comment]
One of those times I wish I could move an issue over to another repo, comments and all.

**Comment by minrk** [comment]
@rgbkrk https://github.com/minrk/migrate-issues doesn't move, but it copies.

**Comment by captainsafia** [comment]
Oh bother! I'm trying to migrate this and migrate-issues is giving me some trouble with OTP.

**Comment by captainsafia** [comment]
I'll close. We have issues open for the notebook guide and the package level docs in other repos anyways.
