### ISSUE TITLE
Optimizing the desktop app size

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1849]
As an experiment, I told electron-builder to not bundle in `node_modules` to save size (put an entry in `build.files` that is `!**/node_modules`). Immediately after building I ran into the following issue:

* the main script needs to be webpack bundled _and_ use the vendored RxJS that the frontend also uses
* some modules may need to be `require`able, based on our webpack config -- native modules and their dependencies

**Comment by lgeiger** [comment]
We want to have the following modules requireable:

```bash
> npm-remote-ls --development false jmp
└─ jmp@0.7.5
   ├─ uuid@3.1.0
   └─ zeromq@4.5.0
      └─ nan@2.6.2

> npm-remote-ls --development false github
└─ github@9.2.0
   ├─ netrc@0.1.4
   ├─ follow-redirects@0.0.7
   │  ├─ stream-consume@0.1.0
   │  └─ debug@2.6.8
   │     └─ ms@2.0.0
   ├─ https-proxy-agent@1.0.0
   │  ├─ agent-base@2.1.1
   │  │  ├─ extend@3.0.1
   │  │  └─ semver@5.0.3
   │  ├─ extend@3.0.1
   │  └─ debug@2.6.8
   └─ mime@1.3.6
```

Unfortunately `electron-builder` doesn't accept my settings 😢

**Comment by rgbkrk** [comment]
I can work on the files handler and the webpack setup for that. I can't recall why we made github separated at the top of the webpack commonjs ignores.

**Comment by lgeiger** [comment]
One thing we might want to check out is: https://github.com/electron-userland/electron-webpack

**Comment by rgbkrk** [comment]
On commit d7c0fc23e9a8948d34f40cf19d8c31d3d5c99a3d: 

* DMG size: 55M
* Unpacked Mac App: 140M

v0.2.0:

* DMG size: 75M
* Unpacked Mac App: 198M

**Comment by lgeiger** [comment]
I'll look into tree-shaking and minification after #1934
