### ISSUE TITLE
save after freezing

### ISSUE THREAD

**Issue by amn41** [nteract/archived-desktop-app#1853]
nteract version: 0.1.0
os : OS X

I wonder if it could be made possible to save a notebook even after the window freezes. 

I just spent a couple of hours on some code, then at one point I ran it and everything froze up. Looks like it's all going to be lost. Export to PDF, gist, save, save as... none of them are working. 

Are there any temporary files I could look at to find my code?

**Comment by rgbkrk** [comment]
Oh no! That's terrible to hear. There are no temp files written. We do have some additional fixes for saving in the 0.2.0 release, they may not have been enough for you though. We'll put in place some automating mechanisms and see what we can do.

**Comment by amn41** [comment]
thanks! I raised this bc might happen to someone doing something more critical than a saturday hack :)

**Comment by rgbkrk** [comment]
I think I'll defer this one to the autosaving issue #814. I'll put autosaving on the next milestone.

**Comment by willingc** [comment]
Closing this issue. Activity about autosaving and related issues can be followed at #814.
