### ISSUE TITLE
Referencing the Facebook Patent Clause

### ISSUE THREAD

**Issue by aterrel** [nteract/archived-desktop-app#1858]
As you are certainly well aware, the React license clause is causing a stir with the ASF banning it. Can Nteract let its users know that use of Nteract does tie them to the React-Patent clause?

I think something as simple as another file (LICENSE-REACT) that contains the Facebook BSD + Patent clause is enough.

**Comment by rgbkrk** [comment]
Done in 2c968db81b2f7c048200f85aaea24058239db3fb.

**Comment by aterrel** [comment]
Awesome thanks for the quick resonse!
