### ISSUE TITLE
Command line `nteract` command opens multiple nteracts

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1861]
Each time you run `nteract`, it creates a brand new nteract instance. 

<img width="229" alt="screen shot 2017-08-23 at 1 46 35 pm" src="https://user-images.githubusercontent.com/836375/29630242-837b31b4-8809-11e7-95f8-736ebdd4dac6.png">

So many nteracts

**Comment by rgbkrk** [comment]
Works well though. :smile: I was able to work with @captainsafia's https://github.com/captainsafia/jupytercon-tutorial/blob/master/1-javascript-primer/1-javascript-primer.ipynb in like zero time. Zero-to-hero is pretty strong here. :smile:

**Comment by lgeiger** [comment]
We could look at what Atom does to handle this: https://github.com/atom/atom/blob/master/atom.sh
