### ISSUE TITLE
No "nteract" menu on Linux

### ISSUE THREAD

**Issue by OliverEvans96** [nteract/archived-desktop-app#1862]
@rgbkrk was trying to show me a super cool feature available via the "nteract" menu item, but to our dismay, it's not there on linux!

![2017-08-23-120335_1362x729_scrot](https://user-images.githubusercontent.com/15915043/29633562-8be2610a-87fb-11e7-800b-5fd5df8a4116.png)

**Comment by rgbkrk** [comment]
In particular, this super cool feature was the nteract shell commands.

**Comment by lgeiger** [comment]
The menu with the app name is a typical "Mac only" behavior.

The shell commands should be under the "Help" item on Linux and Windows. Should we move it somewhere else?

**Comment by rgbkrk** [comment]
Ah ok, I was just clueless where to find it on linux.
