### ISSUE TITLE
Debounce "Save" keyboard shortcut

### ISSUE THREAD

**Issue by Madhu94** [nteract/archived-desktop-app#1865]
I think we may need to debounce the Ctrl+S/Cmd+S shortcuts ? I hold the key down a second longer and I get this -

![image](https://user-images.githubusercontent.com/9015820/29748223-74233ddc-8b2f-11e7-9fcd-e7ed59cb3328.png)

Also, where can I see the notebook name?

**Comment by rgbkrk** [comment]
Seems like something we should do. It can either be done in the bound event in `src/notebook/menu.js` or throttled in the saving epic. I think I'd prefer it being at the bound event.

**Comment by Madhu94** [comment]
I'll take a look. And do you think the notebook name/path should be shown somewhere?

**Comment by rgbkrk** [comment]
Oh hmmmm, on the mac we set the title. Not sure what's available for Linux here.

**Comment by Madhu94** [comment]
I've never worked with electron before, but I would have thought it provided some cross-platform way to set the title.. 

So all nteract devs and most users work on the Mac and so this never bothered them.  :)
