### ISSUE TITLE
Kernel Launch Failed on windows 10

### ISSUE THREAD

**Issue by Geliv** [nteract/archived-desktop-app#1867]
I've just installed `nteract` on windows 10. (Anaconda for python)

After installation, the first problem is "Access is denied.", as shown in the screenshot.
![image](https://user-images.githubusercontent.com/20089973/29777081-5dbc6a5a-8c3d-11e7-93d1-5f5794589c07.png)

This is solved by run as administrator. But when I opened a `.ipynb` file, the problem that "Error_kernel_Launch_Failed" appears.
![image](https://user-images.githubusercontent.com/20089973/29777051-45ea1e54-8c3d-11e7-8b6c-027127b90a50.png)

The `juypter notebook` works fine in Chrome. 
Anyone knows what's the problem?
Many thanks!

**Comment by Geliv** [comment]
I have found the solution myself. In order to open the `.ipynb` file correctly in `nteract`, the kernel should be set to be the default python rather than the anaconda version, as shown in the figure:
![image](https://user-images.githubusercontent.com/20089973/29874859-99d48020-8dca-11e7-98f2-f0d54618c06e.png)

But I still hope `nteract` can open correctly without administrator mode!

**Comment by rgbkrk** [comment]
Interesting, thanks for reporting this.

**Comment by rgbkrk** [comment]
When it comes down to it, this looks like an issue where we don't swap to a different kernel type if we don't recognize what's in the notebook metadata.

**Comment by willingc** [comment]
Closing this issue and tracking kernel discovery and recognition in this issue https://github.com/nteract/nteract/issues/3862
