### ISSUE TITLE
Difficult to change cell type from cell`s popup menu 

### ISSUE THREAD

**Issue by godaygo** [nteract/archived-desktop-app#1874]
It is very uncomfortable to select items from popup menu when there is a cell under it.

![1](https://user-images.githubusercontent.com/20781495/30056148-593dd4b6-923a-11e7-90cc-2a709755364b.png)

The menu becomes transparent and focus moves to the underlying cell items.

![2](https://user-images.githubusercontent.com/20781495/30056178-76bad840-923a-11e7-9edb-28b079164562.png)

So you should make tiny adjustments to choose "Toggle Input Visibility".

Win 10
nteract 0.2.0

**Comment by Madhu94** [comment]
@godaygo I'll check. Thanks for reporting this !

**Comment by rgbkrk** [comment]
This one is fixed (I think).
