### ISSUE TITLE
strikethrough markdown doesn't seem to work

### ISSUE THREAD

**Issue by adammenges** [nteract/archived-desktop-app#1875]
I've tried both `~~strikethrough~~` and `<s>strikethrough</s>`. The later works in a regular notebook setup, haven't tried the former.

<img width="301" alt="screenshot 2017-09-06 09 24 48" src="https://user-images.githubusercontent.com/817438/30122968-44d56d62-92e5-11e7-9a40-5c176d926ec0.png">

**Comment by rgbkrk** [comment]
Closed by #2350.
