### ISSUE TITLE
Switch to markdown-it for github flavored markdown

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1882]
To close in on #1557 and other markdown related issues, we should just go ahead and switch to [markdown-it](https://github.com/markdown-it/markdown-it) for all our markdown rendering. We can then bring in extensions that bring us as close to "jupyter markdown" as possible (marked implementation driven at the moment).

xref: https://github.com/jupyter/jupyter_markdown/issues/3

I'll mark this one as `new-contributor-friendly` and help anyone who wants to tackle this.

/cc @mpacer

**Comment by ProgramFan** [comment]
Any where to start? I am new to the JS world but I would like to look into the issue if it is straight forward enough.

**Comment by rgbkrk** [comment]
This is our current markdown cell:

https://github.com/nteract/nteract/blob/aaf987d14412367048e7ba960279c9375a3bed2a/src/notebook/components/cell/markdown-cell.js

and the basic function for text --> Markdown is set up here: https://github.com/nteract/nteract/blob/aaf987d14412367048e7ba960279c9375a3bed2a/src/notebook/components/cell/markdown-cell.js#L33-L37

You'll have to put `markdown-it` into `packages/desktop/package.json` and install it, followed by configuring markdown it instead of the `commonmark-react-renderer` that's used currently.

If you get stuck, feel free to post again and ask questions. I'll be out quite a bit this week, so hopefully if it's not me then someone else will be able to chime in. 😄

**Comment by ProgramFan** [comment]
It seems straight forward. I dig in and find that the MarkdownRenderer is a component to transform the outout of markdown parser to a collection of React elements. I search the internet and found no such component. The existing component outputing React elements from markdown-it parser bundle markdown-it and leaves no option to configure plugins. So is it possible to use the html result of markdown-it directly in the cell?

**Comment by ProgramFan** [comment]
OK. I find the https://github.com/sunflowerdeath/react-markdown-it code easy to understand. I can reuse the code and build a render myself in markdown-cell.js directly. I will try this when I setup the dev environment on my MBP. 😄

**Comment by ProgramFan** [comment]
Hi, I setup the dev env on my MBP and tried to integrate markdown-it. I have problem with the React part.

I created a markdown-it render `md` and replaced the `mdRender` with `md.render(input)` . The markdown cell outputs raw texts of the generated html. It is not what I want but GFM tables are already correctly parsed. But when I implement something like in  https://github.com/sunflowerdeath/react-markdown-it , the whole cell would gone if I change the type to markdown.

I guess I get the React part wrong, but find no way out. Would someone give me some pointers on how to correctly implement the component nteract want?

**Comment by aaronraff** [comment]
@ProgramFan I would be happy to help you out with this one! Did you commit your changes yet? I can take a look at them and see if I can suggest anything!

**Comment by ProgramFan** [comment]
Thanks @aaronraff. I improved my approach but the error is still strange:

The only change I made to markdown-cell.js is to replace the code mentioned by rgbkrk with:

```js
const parser = new MarkdownIt();
const renderer = new HTMLtoJSX();
const mdRender: MDRender = input => renderer.convert(parser.render(input));
```

And the rendered cells is:
```
React.createClass({ render: function() { return ( <div> <h1>This is header</h1> <p>This is content</p> <table> <thead> <tr> <th>TBL</th> <th>TBL</th> </tr> </thead> <tbody> <tr> <td>CONT</td> <td>CONT</td> </tr> </tbody> </table> </div> ); } });
```
for 
```
# This is header

This is content

| TBL | TBL |
|----|----|
|CONT|CONT|
```

Why??

**Comment by lgeiger** [comment]
Looks like `HTMLtoJSX` uses a older version of React which relies on `React.createClass`. This method was removed in React 16, that's probably why it fails 😕

**Comment by aaronraff** [comment]
What I did to get around this was to use `dangerouslySetInnerHtml` when passing into the `LatexRenderer`. I'm not sure if this is the best approach here though. Really not sure what the negative effects of doing this could be. Thoughts?

What I did:
```
<LatexRenderer>
   <div dangerouslySetInnerHTML={{__html: mdRender(this.state.source)}}>
   </div>
</LatexRenderer>
```

**Comment by rgbkrk** [comment]
As much as possible, we want markdown to be sanitized. Since the notebook can run arbitrary node code with a simple `require`, we don't want the markdown rendering to be able to control the user's computer (think word macro viruses). As much as possible, we need to lock things down.

It might be the case that we need to go from an abstract syntax tree (if using commonmark) or [markdown-it's tokens](https://github.com/markdown-it/markdown-it/blob/e6f19eab4204122e85e4a342e0c1c8486ff40c2d/docs/architecture.md#token-stream) to React elements.

In fact, [looking at markdown-it's debug output](https://markdown-it.github.io/), they even have `tag` and `children`.

As an aside (read: slight diversion), I decided to look at how the html renderer is implemented for commonmark.js and noticed that it would be pretty interesting to create a React renderer based directly on this -- https://github.com/commonmark/commonmark.js/blob/master/lib/render/html.js

**Comment by rgbkrk** [comment]
I'm a little saddened, I thought there was a react renderer for markdown-it that was up to date and used the tokens well rather than using `dangerouslySetInnerHTML`.

**Comment by aaronraff** [comment]
@rgbkrk Thanks for pointing that out. I figured that there were certainly some security concerns with that! I like the idea of possibly creating a React renderer based on the commonmark.js library! Just realized that https://github.com/sunflowerdeath/react-markdown-it hasn't been updated in quite a bit, which is what I was referencing for this.

**Comment by rgbkrk** [comment]
Heh, I just noticed that's exactly what https://github.com/rexxars/commonmark-react-renderer/blob/master/src/commonmark-react-renderer.js does, so we're pretty well situated there. We just can't handle extensions on the commonmark spec with it.

**Comment by lgeiger** [comment]
One other tool to checkout would be https://github.com/ccorcos/markdown-it-renderer.
Not a lot of people are using it though.

**Comment by ProgramFan** [comment]
So it seems we can implement a react renderer like https://github.com/rexxars/commonmark-react-renderer/blob/master/src/commonmark-react-renderer.js with the tokens.

The  https://github.com/ccorcos/markdown-it-renderer approach is also interesting. We just filter out unwanted tags by not defining its mapping.

I will try them.

**Comment by ProgramFan** [comment]
Table is just not parsed in markdown-it-renderer. And it just goes too complecated by first transforming markdown to html, then html to ast, then ast to components. Now the best option is to build our own **markdown-it-react-renderer**. It will take some time, though.

**Comment by ProgramFan** [comment]
BTW, I think this topic is not new-contributer-friendly any more. 😢

**Comment by rgbkrk** [comment]
> BTW, I think this topic is not new-contributer-friendly any more.

Yeah, I agree. Thanks for giving it a go and scoping out options. I misinterpreted the level on this one. I'll swap the labels on it. There will be other issues to tackle here. 😄

**Comment by ProgramFan** [comment]
I can contribute to this issue, the downside is that I need to learn and experiment so it takes longer time than someone experienced.

**Comment by pammacdotnet** [comment]
Any recent progress on nteract MD tables?

**Comment by ProgramFan** [comment]
I failed to allocate time for the task. Sorry.

**Comment by rgbkrk** [comment]
Closing in favor of #2350, tables + more coming soon!
