### ISSUE TITLE
Automatic conversion of iPython/Jupyter notebooks

### ISSUE THREAD

**Issue by juandesant** [nteract/archived-desktop-app#1884]
When opening old-style iPython notebooks, nteract returns an empty error. Converting the notebook using `jupyter notebook` to open them and save them works.

**Comment by rgbkrk** [comment]
How old exactly? I thought we did v3 -> v4 conversion. Anything earlier no one has attempted as far as I know. We should definitely give better error messages on v3.

**Comment by mpacer** [comment]
There's no explicit jsonschema for v1 or v2 in nbformat which probably is
part of why.

**Comment by rgbkrk** [comment]
Do you have an example notebook @juandesant?

**Comment by davidosterberg** [comment]
Example of notebook that doesn't convert

[Merge sort.zip](https://github.com/nteract/nteract/files/1925852/Merge.sort.zip)

Edit: I am running 0.8.4

**Comment by captainsafia** [comment]
I was able to open the Merge sort notebook in v0.13.0 of the notebook. It looks like that notebook is serialized using v3 of the notebook format which we support upgrading form.

I don't think it is worthwhile to explore support for notebooks older than v3 so I'm going to go ahead and close this.
