### ISSUE TITLE
Overeager check for unsaved changes before quit

### ISSUE THREAD

**Issue by pgcudahy** [nteract/archived-desktop-app#1886]
Even if I've just saved and haven't made any changes before quitting I still get the "Unsaved data will be lost. Are you sure you want to quit?" dialog. Can the application check to see if there are unsaved changes before prompting?

**Comment by rgbkrk** [comment]
There is some work in progress in #1860. It's definitely a bit annoying right now, as you always have to dismiss it. I put the current version in as a safeguard until we have the proper UX.
