### ISSUE TITLE
Document how to install the serverextension for Jupyter in the main README

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1889]
We've got some light instructions in https://github.com/nteract/nteract/tree/master/applications/jupyter-extension, we should make people get directed to the resources they need for the deployment/app they want.

**Comment by rgbkrk** [comment]
We're good on this one.

**Comment by rgbkrk** [comment]
Oh wait, no we're not.

**Comment by Ankk98** [comment]
@rgbkrk Cannot open the link in the issue.

**Comment by rgbkrk** [comment]
Updated the link above to use the right package name, thanks!
