### ISSUE TITLE
Bulleted lists inside of numbered lists need love

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1894]
![screen shot 2017-09-14 at 11 00 49 am](https://user-images.githubusercontent.com/836375/30445781-fda69454-993b-11e7-852e-7e14365ebcb7.png)

**Comment by mpacer** [comment]
Where is the markdown rendering happening in the codebase?

**Comment by mpacer** [comment]
Also if you align the * with the text above (I.e., one more space before each of them) how well does that work?

**Comment by rgbkrk** [comment]
It happens in the markdown cell (as well as in Markdown outputs) here: https://github.com/nteract/nteract/blob/master/src/notebook/components/cell/markdown-cell.js#L170

The css is separate, part of main.css -- https://github.com/nteract/nteract/blob/master/static/styles/main.css

**Comment by rgbkrk** [comment]
> if you align the * with the text above (I.e., one more space before each of them) how well does that work

Sounds like a good idea to me!
