### ISSUE TITLE
Switch Gist + GitHub Auth to GitHub Desktop style

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1905]
When opening GitHub Desktop for the first time it offers to let you authenticate via the web. When redirected to the browser, it shows that it will redirect to `x-github-client://oauth`, which means they setup a custom handler for the app:

![screen shot 2017-09-19 at 4 50 17 pm](https://user-images.githubusercontent.com/836375/30620590-21ccfe54-9d5b-11e7-98e9-ae8a3496a354.png)

We should do the same, especially if it means we'd be able to do it without having to run that separate server.

**Comment by jdetle** [comment]
Oooh, I might try to tackle this on Sunday if I find the time. Thanks @rgbkrk.
