### ISSUE TITLE
<td> elements are bold for some reason

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1908]
![screen shot 2017-09-25 at 1 12 09 pm](https://user-images.githubusercontent.com/836375/30828725-70b32146-a1f3-11e7-9bc3-15ccc60646be.png)

Our default styles are making `<td>` elements bold, that shouldn't be the case.

**Comment by rgbkrk** [comment]
Maybe I'm missing something else here... this seems fine now.

![screen shot 2017-10-05 at 7 04 55 am](https://user-images.githubusercontent.com/836375/31231372-8b705724-a99b-11e7-8b3b-e0dedcb30fd3.png)

**Comment by benslater** [comment]
In your first screenshot you set `td = vdom.createComponent('th')`

**Comment by rgbkrk** [comment]
whooooop, no wonder. What a silly mistake. Thanks for the note!
