### ISSUE TITLE
Switch all tests to jest

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1911]
Now that we're completely a monorepo and the desktop package is no longer a special case, I'd love to see all the tests switch over to jest. We'd then be able to run one big global jest run that reports coverage for us.

Bonus points: Make sure our tests are nice idiomatic jest tests instead of the old enzyme cruft we are likely carrying around

Recommended path: Do this slowly, for each package, then finally finish off the ones for `packages/desktop`.

**Comment by lgeiger** [comment]
[`jest-codemods`](https://github.com/skovhus/jest-codemods) are very helpful for doing the conversion. Unfortunately there's no sinon support yet: https://github.com/skovhus/jest-codemods/issues/68

**Comment by skovhus** [comment]
But you might not need the Sinon support. Sinon and Jest can co-exist. : )

**Comment by rgbkrk** [comment]
I think we could probably step away from sinon and our mock-require setup in favor of jest, we're mostly living in a hybrid because of the original mocha based tests for the desktop app.

**Comment by souravsingh** [comment]
@rgbkrk Are there any more tests to rewrite? I am interested in contributing to the issue.

**Comment by lgeiger** [comment]
@souravsingh That's amazing. There're still a few left: https://github.com/nteract/nteract/tree/master/packages/desktop/test/renderer

**Comment by rgbkrk** [comment]
Lukas is totally finishing this right now because he's the hero of the Sunday before the nteract winter sprints.
