### ISSUE TITLE
[vdom-transform] Put dangerouslySetInnerHTML on the block list

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1912]
React blocks use of `vdom.h('script', someScript)`, we should block accepting `dangerouslySetInnerHTML` as an attribute, otherwise it will put anything there:

```js
vdom.h('b', dangerouslySetInnerHTML={
    "__html": "<code style='color: red'>what</code>"
})
```

![screen shot 2017-09-26 at 3 24 44 pm](https://user-images.githubusercontent.com/836375/30887123-d880907a-a2ce-11e7-8f3f-0e7f1abad913.png)

**Comment by rgbkrk** [comment]
cc @gnestor -- probably something good for us to do still

**Comment by gnestor** [comment]
Would you put this logic in object-to-react.ts?

**Comment by rgbkrk** [comment]
Yeah I think so.

**Comment by rgbkrk** [comment]
I guess the yucky part is that we have to remove it on passing to the `React.createElement`. Ideally we'd strip it when we see the data come across the wire. Anyhow, the component should make sure not to render it.

**Comment by gnestor** [comment]
We could also strip it in Python. There are many things to consider but one is that there may be vdom libraries in other languages other than Python but only one transform-vdom, so putting the majority of the logic in transform-vdom would make kernel-side implementations simpler.

**Comment by rgbkrk** [comment]
Kernel side libraries should probably strip it as well to give user feedback in their language of choice. We must still strip it client side for safety.
