### ISSUE TITLE
Stuck on spash screen on macOS

### ISSUE THREAD

**Issue by Feuermurmel** [nteract/archived-desktop-app#1919]
I downloaded the current release of nteract (0.2.0) on OS X 10.11.6. When launching the app from the Finder, I just get the splash screen with the animation, but nothing else happens. The menu bar contains just the `nteract` item (besides the Apple menu). In Console.app, the only messages that seem related to nteract are the following:

```
2017-09-27 23:56:42.513 nteract Helper[8659]: GVA info: preferred scaler idx 0
2017-09-27 23:56:42.624 nteract Helper[8659]: GVA info: preferred scaler idx 0
```

When I run the binary (`nteract.app/Contents/MacOS/nteract`) from the command line, it starts right up and opens an empty notebook. As the app runs fine when run from the command line, how can I provide more information about what might cause this issue?

**Comment by rgbkrk** [comment]
I'm not sure if you still see this. If you do, then look at the logs in `~/Library/Logs/nteract/log.log` on your mac.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if you are still seeing this behavior with the latest release. Thanks! 🌻
