### ISSUE TITLE
Formatting of very long lines

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#1921]
Below a GIF for a notebook that has (very) long lines, with some indented arguments, etc. When you make the window narrower the formatting of the lines gets worse and worse. Besides arguing over what the correct length of a line is, are there ideas how to make it less horrible? I think my other editors end up scrolling horizontally. The browser based notebook does horizontal scrolling per cell.

![code-line-breaks](https://user-images.githubusercontent.com/1448859/31043419-6caa35e6-a5bb-11e7-92ce-3a0c287c8762.gif)

**Comment by rgbkrk** [comment]
> The browser based notebook does horizontal scrolling per cell.

Sounds like we should too. Seems we're missing an overflow.

**Comment by betatim** [comment]
Started looking into this. codemirror has https://codemirror.net/doc/manual.html#option_scrollbarStyle but setting it to "native" doesn't seem to do anything. Also tried https://codemirror.net/demo/simplescrollbars.html which puts scrollbars on each input area but I couldn't click on the input areas anymore to get text entered. Slowly random walking to a working solution 🗺 .

**Comment by lgeiger** [comment]
Looks like code mirror has line wrapping enabled. I'll check it out.
