### ISSUE TITLE
Releasing Packages Again

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1924]
We're in a bit of a midway transition here on some packages, namely that we've bumped `react`, `react-dom`, some related packages, and `jest`. We need to bring up `flow` and `immutable` at some point, they seem a bit tough (read: time consuming), so I'm tempted to just get these out.

The other thing I put us on the hook for is supporting the vdom transform and `object-to-react` for jupyterlab + classic notebook. Jupyterlab is easy because they use commonjs -- the only extra we should provide are typescript definitions. For notebook, I'll figure out how to produce AMD and publish to bower.

Is there anything else you can think of (@lgeiger, @BenRussert?) that you'd want to see finished for when we release the next wave of packages that Hydrogen will end up with? I'm tempted to make many of these major bumps because of the change of `React` underneath to the next major version -- we can probably cause breakage otherwise if not everything gets upgraded together.

**Comment by lgeiger** [comment]
:+1: for doing a major bump.

On the top of my head I cannot think of anything that would be a blocking issue.

**Comment by rgbkrk** [comment]
With the last Rx upgrade, I'm going to make sure things are working well with the jupyter serverextension and then do that major bump.

**Comment by rgbkrk** [comment]
![screen shot 2017-10-02 at 4 44 42 pm](https://user-images.githubusercontent.com/836375/31104292-04b0a98e-a791-11e7-9ece-defbd05acbb2.png)

We're going to need the pipe operator available on `rx-jupyter`

**Comment by rgbkrk** [comment]
🤔 I wonder if I should just bring `rx-jupyter` into the monorepo too so that Rx is versioned in tandem here...

**Comment by rgbkrk** [comment]
Ok, now that the nbextension/serverextension is fixed up, time to tackle notebook preview.

**Comment by rgbkrk** [comment]
```

Changes:
 - ansi-to-react: 1.6.1 => 2.0.0
 - @nteract/commutable: 2.1.1 => 2.1.2
 - nteract: 0.2.0 => 0.2.1
 - @nteract/display-area: 2.4.1 => 3.0.0
 - @nteract/editor: 2.3.1 => 3.0.0
 - enchannel-zmq-backend: 4.0.2 => 5.0.0
 - enchannel: 3.1.1 => 4.0.0
 - fs-observable: 1.0.0 => 2.0.0
 - @nteract/messaging: 1.2.0 => 2.0.0
 - @nteract/nbextension: 0.1.1 => 0.2.0
 - @nteract/notebook-preview-demo: 0.7.0 => 1.0.0
 - @nteract/notebook-preview: 2.5.0 => 3.0.0
 - @nteract/transform-dataresource: 1.2.1 => 2.0.0
 - @nteract/transform-geojson: 2.1.0 => 3.0.0
 - @nteract/transform-model-debug: 2.1.1 => 3.0.0
 - @nteract/transform-plotly: 2.2.0 => 3.0.0
 - @nteract/transform-vdom: 1.1.1 => 2.0.0
 - @nteract/transform-vega: 2.2.1 => 3.0.0
 - @nteract/transforms-full: 2.5.1 => 3.0.0
 - @nteract/transforms: 2.4.1 => 3.0.0
 - nteract-on-jupyter: 0.1.1 => 1.0.0

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published enchannel-zmq-backend
lerna info published ansi-to-react
lerna info published @nteract/commutable
lerna info published @nteract/messaging
lerna info published fs-observable
lerna info published @nteract/nbextension
lerna info published @nteract/transform-geojson
lerna info published @nteract/transform-dataresource
lerna info published @nteract/transform-model-debug
lerna info published @nteract/transform-plotly
lerna info published @nteract/transform-vdom
lerna info published @nteract/transform-vega
lerna ERR! publish Retrying failed publish: nteract // Not sure why the desktop one failed...
lerna info published nteract
lerna info published enchannel
lerna info published @nteract/transforms
lerna info published @nteract/transforms-full
lerna info published @nteract/display-area
lerna info published @nteract/editor
lerna info published @nteract/notebook-preview
lerna info published @nteract/notebook-preview-demo
...
```

The lerna publish ran into an issue with the `nteract` package, which is the desktop app. We should probably keep that one separate from the process.

**Comment by lgeiger** [comment]
Should we add
```json
"commands": {
  "publish": {
    "ignore": ["packages/desktop/*"]
  }
}
```
to `lerna.json` to prevent the desktop app to be published via `lerna`?

**Comment by rgbkrk** [comment]
Good idea! Also we shouldn't publish `nteract_on_jupyter` or the nteract nbextension since those are distributed on PyPI.

**Comment by rgbkrk** [comment]
Closing since we did get those published and I just published again.
