### ISSUE TITLE
saveAs dialog is able to be triggered when no notebook is open

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1930]
Steps to reproduce:

* Run nteract on macOS
* Close all nteract windows
* Click "File -> Save As"

**Comment by captainsafia** [comment]
lol.

I'll work on this.

**Comment by captainsafia** [comment]
I'm gonna extend the scope of this a little bit to affect all menu items (for example, the same thing happens when you select "File -> Publish -> User Gist" the dialog menu shows up).

Menu items should be disabled if no active notebook window is open.

**Comment by rgbkrk** [comment]
Smart! I didn't even think of that.
