### ISSUE TITLE
Remove splash screen

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1933]
It seams like Electrons startup is now faster than it used to be. Now the DOM takes longer to load than the splash screen itself. What do you think, should we remove it entirely and focus our efforts on providing a smoother initial startup?

This is 0.3.1 (the splash screen doesn't even appear):
![kapture 2017-10-04 at 12 43 56](https://user-images.githubusercontent.com/13285808/31171972-0df72cf8-a902-11e7-9ea2-77c29060893c.gif)

**Comment by rgbkrk** [comment]
Wow your system loads it fast. Mine takes a bit longer because of scattered kernels I have on my system, and the fact that the app isn't ready until we know of all the kernels that are installed.

**Comment by betatim** [comment]
Are you sure you didn't leave this on 1.25 speed when recording the GIF? 😁 This is super fast!

**Comment by lgeiger** [comment]
> Are you sure you didn't leave this on 1.25 speed when recording the GIF? 😁 This is super fast!

😂  Yeah I'm sure

**Comment by rgbkrk** [comment]
Lukas must have a turbo charged mac that isn't bogged down by a bajillion other things. 🤣
