### ISSUE TITLE
Conversion to Redux

### ISSUE THREAD

**Issue by kenwheeler** [nteract/archived-desktop-app#194]
Per convos with @rgbkrk & @StevenLangbroek:
- [x] Convert the current "rxdux" architecture to Redux
- [x] Dispatch kernel agendas directly using redux-observable
- [ ] Make the top of the state Immutable 
- [x] Potentially implement https://github.com/erikras/ducks-modular-redux 
- [ ] Add documentation on architecture

**Comment by rgbkrk** [comment]
Possibly to be superseded by #444

**Comment by rgbkrk** [comment]
#444 handled this quite well. I'll make a new issue for the top of the state being Immutable.js
