### ISSUE TITLE
Shipping v0.3.2

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1961]
The primary blockers (to me) for shipping `v0.3.2` are:

* [x] ~making sure that markdown cells wrap their text in edit mode while code cells do not~
* [x] ~bringing back the lodash config (what do you think @lgeiger, do we need to?)~

**Comment by lgeiger** [comment]
The desktop app still has the lodash plugin enabled: https://github.com/nteract/nteract/blob/master/packages/desktop/.babelrc

So for me this is not a blocker for the release.

**Comment by rgbkrk** [comment]
Just tried a `npm run dist:all`, app is looking good! I need to work on some other things, happy to make a release in a few hours though. 😄

**Comment by rgbkrk** [comment]
There is a serious amount of refactoring due for the editor files to make it simpler to pass the right option through... Guh.
