### ISSUE TITLE
v0.3.3

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1964]
* [x] Fix the pager / introspection handling https://github.com/nteract/nteract/issues/1804 (fixed in #1965)
* [x] Provide the about menu on Windows #1939

**Comment by rgbkrk** [comment]
All set, enjoy the patches!

**Comment by dhirschfeld** [comment]
Thanks for the fixes. Loving the auto-update too!
```
[2017-10-10 14:27:44.619] [info] Checking for update
[2017-10-10 14:27:48.879] [info] Update for version 0.3.3 is not available (latest version: 0.3.3, downgrade is disallowed.
```

A couple of things I've noticed though...

Whilst there is an "About nteract" menu now, it doesn't bring up any other menu or dialog or anything. There's also nothing shown in the developer tools console when you click on it.

Also, the "Interrupt Running Kernel" menu item doesn't appear to do anything. Again, there's no error in the JS console. Tested with:
```python
x = 1
while True:
    x += 1
```
...I had to restart the kernel to get out of that one.

So, sorry to be the bearer of bad news  :disappointed: 
On the plus side, nothing new is broken and the help does now work great! :smile:

**Comment by rgbkrk** [comment]
Alright then! At least that was the quickest way for us to try out those changes for windows. We'll have to make a different dialog for the versioning.

**Comment by dhirschfeld** [comment]
Always happy to test on Windows... it would probably be more useful if I tested *before* release  though :thinking:

**Comment by rgbkrk** [comment]
Yeahhhhh, I was really hoping that would work. I figured it wouldn't _explicitly_ break anything.

**Comment by rgbkrk** [comment]
Lukas has something in progress for everyone :soon:.
