### ISSUE TITLE
Update the Roadmap

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1981]
Our roadmap is a year old and no longer reflects the currently ongoing development paths. I'd like to form this roadmap together and for others to contribute to the roadmap over time as we evolve. Admittedly, much of the time I live out of issues and PRs and less in the markdown documents we create. That ends up making me personally less accessible (up in my head) and also makes it harder for people to take an at-a-glance look at the project.

We've accomplished quite a bit over the past few years:

* nteract desktop is now in beta stages
* We publish components and libraries from this repo for many others to use, including our own projects for sharing (commuter) and in-editor computational exploration (hydrogen)
* Hydrogen development has supercharged, resulting in over 50 releases since joining the organization. Hydrogen is even a [featured package](https://atom.io/packages)!
* We have a fantastic site
* We have the beginnings of a serverextension for jupyter
* Commuter uses our notebook-preview and transform components for viewing notebooks and other assets
* We have pushed several new protocols and mimetypes for the wider Jupyter ecosystem and seen them get adopted across all the frontends
* Encouraged collaboration and participation to scale our project out
* Contributed to a shared ecosystem within JavaScript and Python communities

There are some hidden technical threads we've focused on underneath the product portion:

* Shape interactions to target a wide breadth of users
* Keep state consistent, serializable, and able to move to the server side (precursors to realtime)

It's time to unify these into our overall roadmap and vision. I'm probably missing some likely things. In the interest of getting myself out of writer's block and general consternation, I'll post this issue and we can get things rolling.

**Comment by captainsafia** [comment]
That set of accomplishments gives me feels.

It might be good to bring in the things in our [initiatves](https://github.com/nteract/initiatives) repo to this conversation.

**Comment by willingc** [comment]
We've made a lot of progress on roadmaps before/after the NumFOCUS summit in September 2018. @rgbkrk @captainsafia Where's the best place to track roadmaps? Here? Elsewhere?

**Comment by willingc** [comment]
Closing as completed at NumFOCUS summit
