### ISSUE TITLE
Relicense Initiatives as BSD-3

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1983]
When `initiatives` was brought in, it retained the old license. To go through this formally, the following people need to agree to relicensing:

* [x] @captainsafia 
* [x] @betatim 
* [x] @rgbkrk

**Comment by rgbkrk** [comment]
I approve, in case that wasn't clear. 😄

**Comment by captainsafia** [comment]
Ditto.

**Comment by betatim** [comment]
LGTM

**Comment by rgbkrk** [comment]
Rockin'
