### ISSUE TITLE
Markdown syntax highlighting not working

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1987]
In a markdown cell, code in fenced blocks isn't syntax-highlighted - e.g.

![image](https://user-images.githubusercontent.com/881019/31591837-d4255f90-b266-11e7-8fa0-c702fc2e959f.png)

Seems related to #1882

**Comment by rgbkrk** [comment]
Looks like this one is not fixed in #2350, we'll probably need another remark plugin. After we finish #2350 we can investigate this one.

**Comment by rgbkrk** [comment]
How's this nowadays?

**Comment by dhirschfeld** [comment]
I'll have a look...

**Comment by dhirschfeld** [comment]
Doesn't look like it:

![image](https://user-images.githubusercontent.com/881019/43554796-e9ade9e2-9639-11e8-8f40-2fb91dc7fbf1.png)

Version `0.11.2` on `win64`

**Comment by rgbkrk** [comment]
Now that we control the way markdown elements get rendered, we could rely on our syntax highlighter from `@nteract/presentational-components`.

**Comment by rgbkrk** [comment]
If anyone is able to tackle this, the package you'll want to tackle implementing this in is `@nteract/markdown` within `packages/markdown`. 

First place to look is https://github.com/nteract/nteract/blob/master/packages/markdown/src/index.js

The `renderers` prop would likely become something akin to: 

```jsd
{
  ...props.renderers,
  math,
  inlineMath,
  code: (props) => <Source language={props.language}>{props.value}</Source>
}
```

Though whoever is implementing it probably shouldn't inline it. 😅  I wrote it that way for demonstration.

We use react-markdown under the hood and they have a demo that overrides how `code` is rendered that folks can look at:


* https://github.com/rexxars/react-markdown/blob/4e89abb7f79b6526a581160f717d81931a484cc7/demo/src/demo.js#L89
* https://github.com/rexxars/react-markdown/blob/4e89abb7f79b6526a581160f717d81931a484cc7/demo/src/code-block.js
