### ISSUE TITLE
Horizontal scrollbar in cell output not click & draggable

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1988]
As it says in the title - hopefully that's clear?

You can still scroll the output left and right with the arrow keys but you can't click, hold and drag the scrollbar.

The horizontal scrollbar for the *input* does seem to work though.

**Comment by rgbkrk** [comment]
@aaronraff want to check this one out?

**Comment by dhirschfeld** [comment]
Code for repro:
```python
from numpy.random import randn
import pandas as pd

dates = pd.date_range('01-Jan-2018', '01-Feb-2018')
df = pd.DataFrame(randn(dates.size, 3), dates, list('ABC'))
df.T
```
I'd create a gif  but it would just show my mouse cursor moving left and right :|

**Comment by aaronraff** [comment]
I'll take a look at this one!

**Comment by captainsafia** [comment]
Closing as it has been resolved.
