### ISSUE TITLE
Add more options to apply to all cells in the toolbar for the notebook or menu

### ISSUE THREAD

**Issue by Madhu94** [nteract/archived-desktop-app#1990]
We should _consider_ having a toolbar for the entire notebook, that would work on all the cells. To begin, hide input for all cells, hide output for all cells, run all cells. 

Jupyter notebook has a toolbar on top, but those are mostly per cell operations, applied on the cell active at the time.

**Comment by rgbkrk** [comment]
Would this be within the document window or in the native toolbar?

**Comment by willingc** [comment]
Hi @Madhu94 :smile:

Should we leave this open? Or do you wish to open a new issue with your current thoughts on a toolbar?

**Comment by Madhu94** [comment]
> Would this be within the document window or in the native toolbar?
I was thinking in the document window when I logged this. The primary use case was to hide all inputs.

**Comment by willingc** [comment]
So the use case would be to run a notebook. After the notebook runs, then choose to hide all of the input cells, and only display the output cells.

**Comment by captainsafia** [comment]
A top-level menu bar is part of the upcoming UX refresh so this should be implemented then. I'll keep this closed for now so that we can track new UI issues after the implementation of the UX refresh.
