### ISSUE TITLE
Check nteract UX under Linux/Windows

### ISSUE THREAD

**Issue by Madhu94** [nteract/archived-desktop-app#1991]
Right now, nteract seems to have some nice stuff for OS X users, but not for Ubuntu/Windows - like current notebook name, kernel, etc. 

I'll see what can be done for Ubuntu.

**Comment by rgbkrk** [comment]
How's this now?

**Comment by willingc** [comment]
Hi @Madhu94 :sunny:

I'm going to close this issue. Please do open issues for specific features missing in Windows/Ubuntu. Thank you :sunflower:
