### ISSUE TITLE
Scope/Roadmap

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2]
It's time to outline what we want out of an Electron application for the Jupyter notebook!
- Fully standalone desktop application (in Electron!)
- One click installers for OS X and Windows
- Integrates well with the current ecosystem of tooling
- Bundles a kernel with scientific Python packages

**Comment by rgbkrk** [comment]
As part of this, we'll want to make sure we adhere to the way that Jupyter paths work across kernels (so users can install others). This is the reason [jupyter-paths](https://github.com/nteract/jupyter-paths) exists for node - we'll need to make sure this adheres to the right spec (it was ported directly from the original Python).

**Comment by captainsafia** [comment]
> Fully standalone desktop application (in Electron!)
> One click installers for OS X and Windows

Nice!

> Integrates well with the current ecosystem of tooling

I assume you are referring to things like ipywidgets and nbextensions with this statement?

Can you run Electron apps inside Docker?

**Comment by rgbkrk** [comment]
> Can you run Electron apps inside Docker?

Electron is a desktop application framework. It can launch Docker things. What are you wondering about with regards to Electron and Docker?

**Comment by rgbkrk** [comment]
> I assume you are referring to things like ipywidgets and nbextensions with this statement?

Yup. The entire diaspora of crazy fun. @jdfreder and @sylvaincorlay recently adapted ipywidgets to work outside the notebook for these cases.

**Comment by rgbkrk** [comment]
Probably worth noting this will _not_ include nbextensions in their current form, especially those that are Python based.

**Comment by rgbkrk** [comment]
I'm going to close this one now that there's an embedded roadmap in the README + a series of issues to scope some of this out.
