### ISSUE TITLE
No syntax highlighting in newly created notebooks

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#200]
Syntax highlighting is broken in new notebooks. If you run `npm run start` without an existing notebook you get one cell connected to a python3 kernel. However no syntax highlighting in the cell.

Digging down to the `<pre class="CodeMirror-line">` via the dev console shows the code without any tags to markup what is keyword or string or ...

**Comment by StevenLangbroek** [comment]
The "default" notebook doesn't have any `metadata` at all, which is needed to get proper syntax highlighting.
