### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by fbruetting** [nteract/archived-desktop-app#2000]
Would you please also provide a Flatpak package, please?

**Comment by rgbkrk** [comment]
Does electron builder have an option for that? Flatplak seems like something that would sandbox enough that we wouldn’t be able to connect to kernels, I could be wrong though.

**Comment by fbruetting** [comment]
I don’t know anything about Electron, except that it’s slow. :P

For this, Flatpak has a concept of portals, which allows specific access possibilities – like on Android.

**Comment by rgbkrk** [comment]
It looks like there is not flatpak support yet for electron builder, which we use to build our electron desktop app: https://github.com/electron-userland/electron-builder/issues/512

I'm going to close this issue and we'll wait on upstream to support it. If you wish to engage there, you can help implement it in electron-builder.
