### ISSUE TITLE
Input toggled code cells empty space

### ISSUE THREAD

**Issue by hugo-pires** [nteract/archived-desktop-app#2001]
Hello and congratulation on this great project.

When I export my notebook to PDF, the input toggled code cells are not printed, but there is still an empty space on the file. Is it possible to remove it completely?

Thank you

**Comment by rgbkrk** [comment]
Yeah, I think the print stylesheet should be able to take into account non-shown cells by setting them as `display: none` when printed.

**Comment by hugo-pires** [comment]
Is it possible for me to edit the print stylesheet?

**Comment by rgbkrk** [comment]
My comment was about how we should likely go after this, which means changing the source for nteract itself. It's pretty easy to make a release so if you fix it then we'll get it out to all users pretty quickly.

Here's where the print CSS is: https://github.com/nteract/nteract/blob/c24d6dc30de111db5d29495a4db85d742fc4f197/packages/desktop/src/notebook/main.css#L19

I _think_ we'd have to apply some easier `className`s to those cells, I can't tell if what's in https://github.com/nteract/nteract/blob/b6168bb9db266ea83857a315f21aa3b81b850995/packages/desktop/src/notebook/components/cell/code-cell.js#L69 right now is flexible enough to make the CSS styling easy.

**Comment by rgbkrk** [comment]
Closed by #2003.
