### ISSUE TITLE
Menu items / actions not showing sometimes

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2004]
The Menu context updates work most of the time yet sometimes I've been able to get it into a state where the notebook document is focused but the menu no longer has the relevant options available.

<img width="860" alt="screen shot 2017-10-25 at 9 29 19 am" src="https://user-images.githubusercontent.com/836375/32010547-006d1528-b967-11e7-82c4-4ddafb4ea6bf.png">

I can do this reproducibly by exporting my notebook as a PDF, clicking to open my PDF, then command-tabbing back to the notebook app.

**Comment by captainsafia** [comment]
Oops. Yeah. I noticed this but couldn't consistently reproduce. I wonder if it is related to the keyboard action for focus that can't be picked up.

**Comment by rgbkrk** [comment]
Oh man, I've made this come up by trying to use the devtools too. :( I'll look into this on the weekend if I get a free chance.

**Comment by rgbkrk** [comment]
Done!
