### ISSUE TITLE
up/down cell navigation breaks when input hidden

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2005]
Steps to reproduce:

* Create some cells
* Hide the input of one of the cells
* Use the up and down arrows to move from cell to cell
* Get "stuck" scrolling the document rather than navigating cells

**Comment by captainsafia** [comment]
Hm. Let me look into this.

**Comment by captainsafia** [comment]
Figured it out. It's because when the input is hidden the `Editor` component isn't rendered and the `focusAbove` and `focusDown` events are attached to that.

**Comment by captainsafia** [comment]
A hacky solution might be to just show a disabled, empty Editor component when the input is hidden.

**Comment by rgbkrk** [comment]
> A hacky solution might be to just show a disabled, empty Editor component when the input is hidden.

With `display: none`?

How are we doing navigation between markdown cells that are in view mode? Do we register something on the `div`?

**Comment by rgbkrk** [comment]
Thank you for looking into this one by the way! I don't think it's absolutely essential right now, it was just a quirk to me.
