### ISSUE TITLE
Create a menu bar for the web app / serverextension

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2010]
Time to take apart what we support / feature for a menu bar for the nbextension. Generally we should have feature parity between the Jupyter Notebook menu bar (with some deletions) and the nteract desktop app. Here's what I think our MVP needs:

* File
  * New Notebook...
    * Kernel1
    * Kernel2 (these are generated by a call to the `/api/kernelspecs` endpoint)
  * Open
  * Save
  * Download As...
* Edit
  * Cut Cell
  * Copy Cell
  * Paste Cell Above
  * Paste Cell Below
  * Delete Cell
  * Move Cell Up
  * Move Cell Down
* Cell
  * Run All
  * Run All Below
  * Insert Cell Above
  * Insert Cell Below
  * Clear All Outputs
  * Unhide All Outputs
  * Unhide All Inputs
* Runtime (as opposed to Language, fitting with colab's choice)
  * Interrupt
  * Kill
  * Restart
  * Reconnect
  * Switch to...
    * Kernel 1
    * Kernel2 (these are generated by a call to the `/api/kernelspecs` endpoint)
* Help
  * Learn more
  * Release Notes (vX.Y.Z)

If there are mismatches to what I have above and what you find in the various frontends, lets figure out what we think our opinionated consistent "right" way to do this will be.

/cc @klebba

**Comment by betatim** [comment]
👍 for "Language" -> "Runtime". I think there should be a "Restart&run all" in that menu as well.

**Comment by dhirschfeld** [comment]
`s/Runtime/Kernel/`?

Maybe group kernels by language:
 * New Notebook
    * Python
      - Python Kernel 1
      - Python Kernel 2
    * R
      - R Kernel
    * Julia
      - Julia Kernel

  * Runtime
    * Restart & Run All
    * Restart & Clear All Outputs

**Comment by rgbkrk** [comment]
Done!

@dhirschfeld Yes! I'd love to do that. Can you open a new issue about grouping kernels? (sorry I missed this one until now).
