### ISSUE TITLE
Mathjax \begin{align} environment does not render properly.

### ISSUE THREAD

**Issue by galanakis** [nteract/archived-desktop-app#2012]
The following markdown code

```
$$
\begin{align}
a &=1 \\
b &=2
\end{align}
$$
```

should render two equations in two separate lines, with the equal signs aligned. It works this way under jupyter notebook.
Hoever in nteract it renders everything in one line.
<img width="766" alt="untitled" src="https://user-images.githubusercontent.com/2782548/32088429-96f4ecb6-bab9-11e7-9521-ffc2763b2835.png">

**Comment by darthoctopus** [comment]
see #1037: fix exists but hasn't been implemented for over a year now.

**Comment by rgbkrk** [comment]
Closed by #2350.
