### ISSUE TITLE
Highlighting TODO & FIXME

### ISSUE THREAD

**Issue by fbruetting** [nteract/archived-desktop-app#2015]
Would be nice if these two words could be highlighted via some reddish font. :)

**Comment by rgbkrk** [comment]
Here's a [CodeMirror discussion on FIXME highlighting](https://discuss.codemirror.net/t/highlighting-fixme/171). Seems it's not so simple to add them on as tokens individually, we'd probably have to add them on to all the existing modes similar to how we [define an ipython mode](https://github.com/nteract/nteract/blob/master/packages/editor/src/codemirror-ipython.js).

**Comment by rgbkrk** [comment]
Adding on to my old comment, would it be ok if this was only done in Python by extending our ipython mode?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
