### ISSUE TITLE
Versioning implementation

### ISSUE THREAD

**Issue by fbruetting** [nteract/archived-desktop-app#2016]
Would be cool if git could be implemented!

Gnome Builder does the appropriate visualization in a cool way, for example – would be very nice if the lines could have an appropriately colored bar like there! :)

I found [this](https://github.com/jupyter/notebook/issues/1410) corresponding bug report in Jupyter, linking to [this discussion](https://stackoverflow.com/questions/18734739/using-ipython-notebooks-under-version-control).

**Comment by rgbkrk** [comment]
@alexandercbooth had some starter work with this that was looking pretty good in #1649. I'd love to see that visited again. 😄

**Comment by alexandercbooth** [comment]
Thanks for the patience everyone, I will have some time tomorrow and will revisit this.

PS @rgbkrk I am PSYCHED about papermill; what a fantastic idea!

**Comment by rgbkrk** [comment]
Since we did some major refactorings underneath, you may want to start a new branch from `master` since the desktop package is now properly part of the monorepo.

**Comment by rgbkrk** [comment]
P.S. Great to see you again!
