### ISSUE TITLE
iframe entire display area

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2019]
As brought up in a call with @craigcitro and others today about colab and interop with nteract, their iframe output areas are incredibly performant, even on huge notebooks. They do rely on service workers to work, so they come with the caveat that it will only work in certain browsers. For our targets, that's not a big problem. This will cause issues for libraries like Bokeh, though I think we can cross that bridge.

I'm filing this issue to say that I'd love to switch to iframes by default in the desktop and all (\*) web frontends, so that we can keep them secure by default regardless of kernel. I know Jupyter in general has been reluctant to adopt this. I think we can do it, keeping people more secure in general.

**Comment by Madhu94** [comment]
Why should this cause an issue for Bokeh ?

**Comment by rgbkrk** [comment]
Bokeh puts itself on the page with the `output_notebook` method. It then expects to be available later on in the page everytime Bokeh is "used":

![bokeh-load](https://user-images.githubusercontent.com/836375/34321959-1048e3c2-e7d0-11e7-9142-1014092e6f8d.png)

With iframes, the assumption that you can do javascript in one cell (like loading a library like bokeh) and then using something from that same global scope is no more. Every iframe has its own sandbox.

**Comment by Madhu94** [comment]
I think, as part of their work on Jupyterlab integration(https://github.com/bokeh/bokeh/pull/6774 - seems like a WIP ), they will have an extension that renders a custom mime-type

**Comment by rgbkrk** [comment]
Nice, that'll be excellent. Then we can integrate that directly in.

**Comment by captainsafia** [comment]
Ref: https://github.com/nteract/nteract/issues/1067
