### ISSUE TITLE
Use componentDidCatch within transforms

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2026]
Especially those that execute code or create react elements directly. If `transform-vdom` creates React code that can cause React to crash, it brings down the whole app. Implement [`componentDidCatch`](https://reactjs.org/docs/react-component.html#componentdidcatch) for the transforms, especially `transform-vdom`.

* [ ] `@nteract/transform-vdom`
* [ ] `@nteract/transforms`
* [ ] `@nteract/display-area`

**Comment by mpacer** [comment]
I'm guessing that this is supposed to map on to 

* [ ] [`@nteract/transform-vdom`][transform-vdom]
* [ ] [`@nteract/transforms`][transforms]
* [ ] [`@nteract/display-area`][display-area]

But how am I to interpret the @nteract bits?

[transform-vdom]: https://github.com/nteract/nteract/tree/master/packages/transform-vdom
[transforms]: https://github.com/nteract/nteract/tree/master/packages/transforms
[display-area]: https://github.com/nteract/nteract/tree/master/packages/display-area

**Comment by rgbkrk** [comment]
That's correct. The `@nteract` is the name of the actual package as published on npm -- look in their respective `package.json`s.

**Comment by mpacer** [comment]
So there's nothing special about the `@nteract` name other than that's the convention used to describe a namespace for npm meta-packages that hold other packages? Is the `/` special? Or is it similarly just a convention?

**Comment by rgbkrk** [comment]
`@nteract` is a [namespace for scoped packages on npm](https://docs.npmjs.com/getting-started/scoped-packages) for the nteract project.
