### ISSUE TITLE
Python kernel not correctly identified when launched as a desktop app

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#2027]
Began talking with @rgbkrk about an issue I was running into where my kernel's kernelspec was not being adhered to when opened through the nteract desktop app. 

Apparently this relates to Apple's [launchctl](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/launchctl.1.html) and how it mangles environment variables.

@rgbkrk suggested eventually @lgeiger and I would be good to pair program on this.

This has been reported many times, at some point those duplicate issues should be collected so they can all be resolved at once.

**Comment by lgeiger** [comment]
I'm happy to help!

I haven't recently experienced any issues related with kernelspecs on my machine. I though this was fixed upstream by Electron.

Right now we're using [`shell-env`](https://github.com/nteract/nteract/blob/8ff67aa354d2a4be20baf97d910e22d707f09a9c/packages/desktop/src/main/prepare-env.js#L12) to get the current environment.
Recently there were quite some reports about `shell-env` starting rogue bash processes on Linux, so I think this is a good time to revisit this: https://github.com/lgeiger/ide-python/issues/20

Atom uses [`require('electron').remote.getCurrentWindow().loadSettingsJSON`](https://github.com/atom/atom/blob/master/src/get-window-load-settings.js) to load the shell env. I think we should do the same here.
