### ISSUE TITLE
Cannot get hotfix dev install working

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#2028]
Attempting to follow the instructions at 

https://github.com/nteract/nteract#install-nteract-in-dev-mode

and I'm running into some strange issues getting it going.

So if I do

```
git clean -xfd && npm install
npm run start
```
everything works fine, but I need to restart the server to see any changes in the resulting code.

So to get the watch going I'm trying to run the progressive webpack build, but when I try to run: 

```
npm run build:desktop:watch
```
in one terminal
and

```
npm run spawn
```

in a third terminal. I get the following error:

![image](https://user-images.githubusercontent.com/2482408/32198577-e6c6aec2-bd85-11e7-8382-4ee446baea84.png)

This has been pretty much a progress halting issue and i don't know js packaging well enough to know how to deal with this. 

@lgeiger, @rgbkrk suggested you might be a good person for knowing how to address this.

**Comment by mpacer** [comment]
OK, we worked it out. 

This can occur when either of the two cases happen:

1. you don't wait long enough for the `npm run build:desktop:watch` to finish before running `npm run spawn`

2. If you are running `npm run start` in a third terminal at the same time as `npm run build:desktop:watch`

So the solution is to make sure that `npm run build:desktop:watch` finishes before running `npm run spawn`. My guess is the readme should reflect that condition.

**Comment by rgbkrk** [comment]
Oh that makes sense. 🤔  I wonder if there's a way for spawn to check that the right webpack files are on disk and ready first.

**Comment by rgbkrk** [comment]
Can we close this one, now that we've updated a bunch of the initial startup gunk?

**Comment by mpacer** [comment]
it'd be better to figure out a way to delay the `spawn` before closing, since `build:desktop:watch` never really _does_ finish (as it's watching for changes and occupies the terminal).

**Comment by rgbkrk** [comment]
I _think_ this is ok now right @mpacer?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if needed. Thanks! 🌻
