### ISSUE TITLE
GeoJSON Transform needs styles to get brought in by webpack

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2034]
Similar to the rest of our CSS setup, our GeoJSON transform needs to bring in CSS properly. Additionally, it looks like we need Leaflet to be able to load some image data:

https://github.com/nteract/nteract/blob/76493806330373bce633c7c904b9e6fdcdbba59e/packages/transform-geojson/src/index.js#L16

I am completely unaware of how we should handle that...

**Comment by rgbkrk** [comment]
Totally forgot to note in this issue that our GeoJSON transform is currently _broken_ as a result.

**Comment by josephofiowa** [comment]
leaftlet geojson renderer fails; Kyle and I are taking a look

**Comment by captainsafia** [comment]
Working on this now. Now that we're on styled-components, @rgbkrk mentioned that we can use their global styles to get this set up so I'll give this a go now.

**Comment by captainsafia** [comment]
I think we can go ahead and close this since GeoJSON rendering is working now.
