### ISSUE TITLE
Page break

### ISSUE THREAD

**Issue by hugo-pires** [nteract/archived-desktop-app#2035]
Hello

Is it possible to define page break when exporting to pdf?

Thank you

**Comment by captainsafia** [comment]
Hello @hugo-pires! Thanks for submitting this issue!

Under the hood, nteract uses the same PDF generation technique that your browser uses when you save a webpage to a PDF. As a result, it's a little difficult (and out of scope) to implement this at the moment.

If you'd like to find a resolution for this and contribute it to the community, I'd be glad to help you as you draft your pull request.
