### ISSUE TITLE
LaTeX Issue with \left\{  \right\}

### ISSUE THREAD

**Issue by MasonProtter** [nteract/archived-desktop-app#2037]
In a Jupiter notebook, the markdown editor knows how to correctly handle 
```
\begin{equation}
\left\{ ... \right\}
\end{equation}
```

ie. it knows to make appropriately sized curly braces around whatever is between the `\left` and `\right`. However, it seems that nteract doesn't know how to handle it for me and the editor refuses to render the LaTeX. Furthermore, sometimes when exploring this issue it'd make my entire editor go blank and I would need to close and open the notebook to be able to see anything again.

**Comment by rgbkrk** [comment]
Same issue under the hood as #2012.

**Comment by rgbkrk** [comment]
Closed by #2350.
