### ISSUE TITLE
Suggestions: Softwrap text and drag and drop between notebooks

### ISSUE THREAD

**Issue by MasonProtter** [nteract/archived-desktop-app#2040]
* There should be an option to disallow text from continuing offscreen and make it wrap onto a new line in cell. 

* It would be very nice to be able to use the drag and drop gesture to copy a code cell to another notebook

**Comment by rgbkrk** [comment]
Thanks for reporting.

Related issues (in the opposite direction): #1940, #1921 

/cc @betatim

**Comment by MasonProtter** [comment]
I can see and understand the desire for horizontal scrolling which is why I suggested making soft-wrap optional, possibly togglable per cell?

**Comment by betatim** [comment]
I'd be cool with togglable (per cell). And because I can't remember: do we currently soft wrap for mardkown cells?

**Comment by MasonProtter** [comment]
The rendered markdown is soft wrapped but the code is not.

**Comment by betatim** [comment]
+ 💯 for softwrap in markdown cells :)
