### ISSUE TITLE
Autocomplete shuts down in some cells

### ISSUE THREAD

**Issue by MasonProtter** [nteract/archived-desktop-app#2041]
I have a somewhat sizeable notebook (on the order of 30 cells) about half markdown and half code and the autocompletion stopped working in existing cells. If I cut the text and paste it into a freshly created cell then the autocompletion works.

**Comment by rgbkrk** [comment]
I'm assuming no errors showed up to give us any more insight?

**Comment by MasonProtter** [comment]
Unfortunately not. I didn't even notice it was gone at first so I'm not totally sure what was correlated with the error. I suspect it might be related to the issue with the latex editor not treating align and curly braces properly though. Messing around with the align environment and curly braces sometimes causes my whole notebook to turn white and all cells to disappear requiring me to close the notebook and reopen it. I think (though I'm not sure) that I lost autocomplete somewhere around this time.

Note: closing and reopening a notebook or even restarting the program does not restore autocompletion, only deleting the cell and creating a new one does.

**Comment by rgbkrk** [comment]
I wonder if this is related to #1626
