### ISSUE TITLE
Unable to publish as user gists

### ISSUE THREAD

**Issue by jinxuan** [nteract/archived-desktop-app#2044]
I'm unable to publish my notebook to gists as user gists. The canvas is completely blank.

![image](https://user-images.githubusercontent.com/5571773/32416737-620a7e4a-c20b-11e7-9ca6-e5b042371eb2.png)

**Comment by captainsafia** [comment]
Hello @jinxuan! Thanks for opening this issue!

I was able to reproduce the issue! The problem is on our end and is a result of our OAuth gateway not being configured properly. I'll work on fixing it and get back to you once the issue has been resolved.

**Comment by captainsafia** [comment]
Alright! I've fixed this problem. Please let me know if you are still experiencing problems with gist publishing.

**Comment by jinxuan** [comment]
Thank you! It is fixed now!
