### ISSUE TITLE
`transient` attribute in DocumentRecord should be typed better

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#2050]
Currently, it holds the key paths that are used for output display and it can all handle any cell status data.

**Comment by rgbkrk** [comment]
Definitely warranted, along with turning the entire Notebook into a Record. I am super in love with Records now. 😄

**Comment by willingc** [comment]
Still an issue? @captainsafia @rgbkrk

**Comment by rgbkrk** [comment]
We're on Records now!
