### ISSUE TITLE
`dummyStore` should take object and extend default state

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#2052]
This is a follow up on the work done in #2051. `dummyStore` should take an object that it uses to extend a default state when generating a store.

**Comment by rgbkrk** [comment]
Now that we have record makers for all our base state now, I'm beginning to think we should have less use of the dummy module. It's got a weird interface we haven't been maintaining well. 😒

**Comment by willingc** [comment]
Should we close this? @captainsafia @rgbkrk

**Comment by rgbkrk** [comment]
Yeah, this is now in `@nteract/fixtures` thanks to @captainsafia in the past couple weeks and is much cleaner now. ✨
