### ISSUE TITLE
Remove sinon dependency from tests

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#2053]
Follow up on work done in #2051. sinon should be removed from our tests in favor of jest.

**Comment by rgbkrk** [comment]
As well as a complete switch over from the mocha based tests. 😄 We're almost there! @lgeiger did most of the conversion already, a few stragglers remain.

**Comment by rgbkrk** [comment]
This appears to be all finished off! No traces of sinon in the code base.
