### ISSUE TITLE
Dark Theme unreadable Font color

### ISSUE THREAD

**Issue by atoav** [nteract/archived-desktop-app#2083]
I use the x64 build on Windows 10. The font on the "show addition details"-pulldown is dark blue on black and essentially unreadable. See attached screenshot:  

![nteract_dark_theme](https://user-images.githubusercontent.com/6620266/33043694-976e789c-ce46-11e7-903a-78d93052adbd.png)

**Comment by rgbkrk** [comment]
This is currently fixed on `master`, we'll get a new release out :soon:. Thanks for reporting!
