### ISSUE TITLE
Copy Cell and Paste Cell Shortcuts do not work (Windows x64)

### ISSUE THREAD

**Issue by atoav** [nteract/archived-desktop-app#2086]
I know there are plans to change this. But in the current 0.3.4 (x64 on Windows 10) release the shortcuts ```Ctrl + Shift + C``` for copying cells and ```Crtl + Shift + V``` for pasting cells don't work. Cutting Cells with ```Ctrl + Shift + X``` an all the other shortcuts (I tested all of them) work however.  

I very much like that you show the shortcuts in the menu besides the commands btw.

**Comment by rgbkrk** [comment]
This should be good to go, I fixed this a few releases ago and haven't triaged all the issues to the degree I've done in the last few days.
