### ISSUE TITLE
Feature Request: Python Variables in Markdown text

### ISSUE THREAD

**Issue by atoav** [nteract/archived-desktop-app#2087]
Coming from jupyter I instantly fell in love with nteract because it integrates way better with the way I intend to use these notebooks than the CLI-/server-solution. One thing I still miss is the ability to reference python variables in the markdown text ([see nbextensions/python-markdown](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/python-markdown)).

**The general idea is quite simple:**
I want to be able to create a python notebook file, that uses the calculated information within a nicely formatted markdown text. So instead of printing for example the average power consumption manualy with something like ```print("Average power consumption: "+str(avgpower))``` we can do something in markdown like this: ```The average power consumption of XYZ is {{avgpower}} Watts``` and instead of ```{{avgpower}}``` it would insert the str() of the variable.  

**Why this would be nice:**
This allows to hide away the gory details of one's python scripting and still get the relevant calculations. The idea is to see "only" markdown and diagrams and focus on the results without the code getting into the way. This is good from a psychological perspective (less incentive to get lost in code again once it is done), but also allows for easier sharing with co-workers who are scared by code that means nothing to them.

I understand that the implementation of this is probably not easy and involves a lot of hairy details (like what to do on file export, how to signal errors, how to deal with existing code (as it sort of extends markdown), etc)

**Comment by rgbkrk** [comment]
That would be really cool! It seems like a difficult feature for us to implement and maintain, as we'd want to build a standard around it. There's already a lot of difficulty in maintaining the current markdown implementation without having competing camps of people wanting conflicting grammars in markdown.

**Comment by rgbkrk** [comment]
Adding on ~1.5 years later -- I think this makes sense as a new notebook format, either a completely new one or something for a future iteration. Since we can only reasonably support the specced formats from nbformat and jupyter_client, I'm going to close this and we can revisit it if someone ever has cycles for it.
