### ISSUE TITLE
syntax highlighting not working in the first cell

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#2092]
I'm getting this with the 0.4.0 release on Windows 7.
The first cell does not highlight Python syntax, subsequent cells do.
The code still executes fine. I haven't looked into it but I thought I'd post the issue.

![nteract-err-1](https://user-images.githubusercontent.com/5368903/33146624-85a1b12a-cf8a-11e7-9dd5-e4e24c081e0b.png)

**Comment by rgbkrk** [comment]
This one is so strange and is the next for me to tackle this morning.
