### ISSUE TITLE
Docstrings broken in 0.4.0

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2093]
In the latest version docstrings are no longer rendered correctly - e.g.

![image](https://user-images.githubusercontent.com/881019/33227931-5ba0310e-d1fa-11e7-97c6-281c9aee393f.png)

...it appears that the line-breaks aren't being respected.

**Comment by rgbkrk** [comment]
That's a regression from me doing an overall components and CSS refactoring. I'll get this one matching up and a release out in the next couple days with fixes for each of the recent bugs.
