### ISSUE TITLE
Running indicator (*) missing in 0.4.0

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2094]
As it says in the title. Here's a gif I made to demonstrate:

![nteract](https://user-images.githubusercontent.com/881019/33227987-d368f9e0-d1fb-11e7-9ea5-95e2fa1d0c02.gif)

...as can be seen, when I run the cells the output is cleared but the cell numbers (36/37) aren't replaced with a `*`.

**Comment by rgbkrk** [comment]
I'll see if I can get this one fixed too since I knocked the other recent regressions out, and then we'll make a nice happy patch release. 😄

**Comment by rgbkrk** [comment]
Ah I see, the queued state is not trickling through here. I'll work on this. Sorry about the messiness of this release, I did an overall refactor of the components to make them simpler to work with and missed quite a few edges while simplifying the components. Thank you @dhirschfeld.

**Comment by dhirschfeld** [comment]
That's fine - UI testing is *very*, *very* hard IMHO - especially in the face of large refactors. Sometimes the best you can do is to get a release out and fix the problems as they arise. Having the auto-updating makes it very easy for the users to upgrade and get any fixes. Hopefully the release process isn't too onerous for the devs!

**Comment by dhirschfeld** [comment]
Closing as fixed in 0.4.2!

**Comment by dhirschfeld** [comment]
Just reopening because I've noticed that whilst the currently executing cell is denoted with an `*`, if you queue up the execution of cells after that it's not indicated by anything. In the notebook/jupyterlab each cell you queue up gets an `*` so you know which are pending to run.

**Comment by rgbkrk** [comment]
What do you think of the new queued marker `…` and the ol' busy marker `*`?

**Comment by rgbkrk** [comment]
We now have a queued marker and a busy marker. 🎉
