### ISSUE TITLE
Classic theme prevents selecting cells

### ISSUE THREAD

**Issue by jocago** [nteract/archived-desktop-app#2099]
In version 0.4.0, after any run of a cell, no cell can be selected for editing. Clicking on a cell does nothing, though clicking on the output of a cell does allow selection of output text. Double-clicking a cell will sometime highlight the cell label text. If that text is highlighted, 2 or 3 [tab] presses will usually allow editing of the cell.

OS: MacOS 10.12.6 (16G1036)
nteract: 0.4.0
Python: 3.6.1
IPython: 5.3.0

**Comment by rgbkrk** [comment]
Wow, that does not sound good. On my copy of 0.4.0 I'm not able to reproduce this issue. Does this work with new notebook files too or maybe you have a small example notebook?

**Comment by jocago** [comment]
It is with new and existing notebooks. I could send a notebook for you, but literally, any of them are the same. I'm uploading a screenshot. It shows the cursor hovering over the cell, but not changing to the text selection tool. If that helps, at all.
<img width="1920" alt="screenshot 2017-11-26 18 49 46" src="https://user-images.githubusercontent.com/6642658/33245820-d90824cc-d2da-11e7-96eb-b5a01fc1c5b4.png">

**Comment by rgbkrk** [comment]
Oh interesting! That looks like the "classic" theme. Perhaps there's some styling interfering with the hover mask, I'll dig in. Can you try the light theme?

**Comment by jocago** [comment]
Brilliant. That works. And to verify, I changed it back to classic and it's broken again. I'll work in a working theme.

**Comment by rgbkrk** [comment]
I'm fairly tempted to only support the light and dark themes unless other maintainers work on our theming interface. I may fix parts of the classic, though it's likely that it won't look / work quite the same given our overall CSS refactoring that is going on.

**Comment by rgbkrk** [comment]
We've since deleted the classic theme due to maintenance issues. Long live the light and dark themes! Thanks for the report @jocago.
