### ISSUE TITLE
css problem with markdown cells (0.4.0)

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2100]
![nteract](https://user-images.githubusercontent.com/881019/33246179-3c643984-d35d-11e7-8d71-e49179122d54.gif)

Note: As well as showing the narrow width of the markdown cell it also demonstrates the error in #2099 which I stumbled upon accidentally. Specifically, after I change the cell to be markdown type then click in  it the cursor disappears and I can't select it. I got out of that state by using `Ctrl-Shift-N` to create a new cell which I could then select after which I could then click back into the markdown cell.

**Comment by rgbkrk** [comment]
Extremely odd, though I know the likely culprit for this. Thanks for reporting.

**Comment by dhirschfeld** [comment]
Just a note to say that both issues are present in the latest 0.4.1.

At least #2099 is fully reproducible by converting a cell to markdown then clicking on it.

**Comment by rgbkrk** [comment]
Thanks @dhirschfeld.

Note for maintainers, myself included:

`styled-jsx` has created three total class names for the editor on the markdown cell and it looks like styling just ain't happening here:

![screen shot 2017-11-26 at 7 44 45 pm](https://user-images.githubusercontent.com/836375/33250004-accb804a-d2e2-11e7-8082-6ed9737ab90d.png)

Boy did I make things difficult for this release series. The hurrah is that we have standalone components with built in styles we can use elsewhere, the OH NO is that it's completely broken the desktop app.

**Comment by rgbkrk** [comment]
All fixed and released in `v0.4.2`! Thank you @dhirschfeld.
