### ISSUE TITLE
Clear All Outputs doesn't clear execution counts

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2107]
Similar for Restart and Clear All Cells.

After clearing all outputs the execution count remains:
![image](https://user-images.githubusercontent.com/881019/33296938-fe75267e-d429-11e7-85ba-fbd9cbb98ac8.png)

I would expect the execution count to also be cleared - i.e. it should be a blank `[ ]` after clearing the cells. This is useful to clearly distinguish which cells have been run and which haven't after a restart.

**Comment by dhirschfeld** [comment]
Sorry for the trickle of bug reports but thanks for the quick fixes! I think the major issues have been addressed so no need to rush out another release for this one - it's just a mild annoyance.

**Comment by rgbkrk** [comment]
Totally cool, I'm really happy you report these and are having patience with this release series.
