### ISSUE TITLE
nteract theme colours unreadable

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2114]
I was quite fond of the nteract theme but recently something has changed with the colours making making function names / arguments very difficult to see - e.g.

![image](https://user-images.githubusercontent.com/881019/33352294-ebb55a98-d4f3-11e7-88f5-670819bc61d9.png)

**Comment by rgbkrk** [comment]
I'm going to close this since we deprecated the nteract theme. I'd like to incorporate some things from this theme into the main themes though, especially the stripe animation.
