### ISSUE TITLE
Evaluate react-markdown + remark-math plugin

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2115]
https://github.com/rexxars/react-markdown/issues/10#issuecomment-347763068

```typescript
import * as React from "react";
import * as ReactMarkdown from "react-markdown";
import MathJax from "@matejmazur/react-mathjax";
import RemarkMathPlugin = require("remark-math");

export const MarkdownRender = (props: ReactMarkdown.ReactMarkdownProps) => {
  const newProps = {
    ...props,
    plugins: [
      RemarkMathPlugin,
    ],
    renderers: {
      ...props.renderers,
      math: (props: {value: string}) =>
        <MathJax.Node>{props.value}</MathJax.Node>,
      inlineMath: (props: {value: string}) =>
        <MathJax.Node inline>{props.value}</MathJax.Node>,
    }
  };
  return (
    <MathJax.Context input="tex">
      <ReactMarkdown {...newProps} />
    </MathJax.Context>
  );
};
```

**Comment by dhirschfeld** [comment]
[Looks like](http://rexxars.github.io/react-markdown/) this might also solve #1987?

**Comment by mpacer** [comment]
as commented here: https://github.com/nteract/nteract/pull/2350#issuecomment-361791267, 

there is an issue with remark-math and consistency with the Jupyter ecosystem. Specifically it treats within paragraph `$$…$$` as being an inline element, when the rest of the Jupyter ecosystem treats it as a display element.

Here's a catalogue of ways this can diverge (in classic notebook & lab all of these would render as )

Consistent (✔️): 
(newlines) → display:
![image](https://user-images.githubusercontent.com/2482408/35600215-b5a04a2a-05e1-11e8-8a10-b28de2d0979c.png)

Inconsistent (❌):
(no newlines) → inline:
![image](https://user-images.githubusercontent.com/2482408/35600198-9b5d58f6-05e1-11e8-889d-900ebcddc718.png)

(no first newline, yes last newline) →  undefined:
![image](https://user-images.githubusercontent.com/2482408/35601159-67c884c0-05e6-11e8-8a23-5db455df67c4.png)

(yes first newline, no last newline) → display + extra `$$`
![image](https://user-images.githubusercontent.com/2482408/35601174-786b353e-05e6-11e8-9bf4-f50bedc6d908.png)

**Comment by rgbkrk** [comment]
Want to make a new issue for the idiosyncrasies between rendering on each of lab, nteract, and classic?
