### ISSUE TITLE
Provide a `<title>` to our toolbar buttons

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2117]
For screen readers, all our SVG images that are used in toolbars (and other UI elements) should use [an SVG `<title>` element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) to describe what the button does to allow screen readers to know what the functionality is.

Example (for the "right triangle" svg):

```js
<svg xmlns="http://www.w3.org/2000/svg" width="6" height="16" viewBox="0 0 6 16">
  <title>Run Cell</title>
  <path fillRule="evenodd" d="M0 14l6-6-6-6z" />
</svg>
```

**Comment by hydrosquall** [comment]
I'll pick this up, will raise PR later this weekend :)
