### ISSUE TITLE
<img> tag will not display image from local directory.

### ISSUE THREAD

**Issue by litaxc** [nteract/archived-desktop-app#2127]
Using a <img> tag in the markdown cell to source an image from the local directory will not display the desired image.
However, sourcing from the internet does the job.
<img width="467" alt="screen shot 2017-12-02 at 8 23 02 pm" src="https://user-images.githubusercontent.com/1912982/33515457-c18bc420-d79e-11e7-8447-22adaa911e36.png">

**Comment by betatim** [comment]
Speculating here: which directory did you start `nteract` in? Is there a way for you to confirm that the current working directory of the kernel(?) is the one you think it is? In a python kernel I would run `!pwd` to check.

**Comment by rgbkrk** [comment]
This is indeed an issue that we have to fix up by changing where the electron app “loads” the page. Right now it’s relative to our “index.html” which is not what users need.

**Comment by litaxc** [comment]
@betatim 
The directory is indeed in the right directory. However, it still won't display the image.
<img width="450" alt="screen shot 2017-12-04 at 6 47 22 am" src="https://user-images.githubusercontent.com/1912982/33530713-0a9f076e-d8bf-11e7-889e-d8bf3c04e68e.png">

**Comment by rgbkrk** [comment]
Thank you for the reproducible example. We've been working on some refactors that will make it likely that we'll be able to fix this for all notebooks. I'll let you know when we have updates. Thanks again for reporting @litaxc

**Comment by denisrasulev** [comment]
Got the same problem. Still not resolved? Nteract v0.12.3, macOS Mojave 10.14.1 (18B75)

**Comment by captainsafia** [comment]
This was recently fixed in v0.13.0 of the nteract desktop when https://github.com/nteract/nteract/pull/4326 was merged.
