### ISSUE TITLE
Apply for Mozilla Science Mini-Grant

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2140]
The [RFP for Second Round of Mozilla Science Mini-Grants is now open](https://science.mozilla.org/blog/2018-mini-grant-rfp) and folks should apply!

These are the main categories they're interested in:

> * Prototyping – Building tools or documentation collaboratively with others. This can be open source code, documentation, tools and technologies used in data-driven science, scientific software, discovery tools (e.g., ways of searching code, hosting services, etc.)
> * Community Building – These might include mentorship programs, workshops, meet-ups or other events that promote community engagement.
> * Curriculum – Materials might include text, visuals, and video for online or in-person training.

Within each of those, I've got some ideas. I'll leave a separate comment though so it's just part of the main thread rather than in the issue body.

Deadline is _this Sunday_, December 17, 2017.

**Comment by rgbkrk** [comment]
## Prototyping Category

Within the prototyping category, I'd like to focus efforts on discovery tools for notebooks.

Idea 1: next gen notebook viewer with indexed contents, ways to search it

## Community Building

Provide a workshop on jupyter protocol + format fundamentals. Participants will build a new frontend on top of jupyter, backed by binder, using nteract components. Beyond their own personal knowledge gain, they'll also be ready contributors to projects across the Jupyter ecosystem.

## Curriculum

@captainsafia suggested we could focus on some documentation efforts. Given that we have ourselves a nice suite of components, we could develop materials woven into our main site that provide an overall narrative and learning experience.

**Comment by rgbkrk** [comment]
Note: since I noticed the initial submission was pretty simple, I submitted the "jupyter infrastructure fundamentals workshop". Also still happy to pair or help others with other categories.

**Comment by willingc** [comment]
All of the above @rgbkrk @captainsafia 👍

**Comment by rgbkrk** [comment]
Deadline has passed, I'll go ahead and close this. We can revisit if/when we make the next round on any of our proposals.
