### ISSUE TITLE
Spaces in play.nteract.io do not appear to be monospace

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#2147]
Was looking at the code example, and while the computed style said it was a Monospace font, the characters were not actually aligned

See here:

![image](https://user-images.githubusercontent.com/2482408/33920896-713ae8d2-df75-11e7-86ed-64a5b2b1638c.png)

This comes from having `word-spacing: 1px` in Codemirror. 

I'll add a fix for this to #2141 (since it should be tiny).

**Comment by mpacer** [comment]
This actually requires fixing the value in the main [`editor/styles.js`](https://github.com/nteract/nteract/blob/932ad53154daa5e2372608a0b3e57f1e3c94da3a/packages/editor/src/styles.js) file in addition to [`play.nteract.io/index.js`](https://github.com/nteract/nteract/blob/932ad53154daa5e2372608a0b3e57f1e3c94da3a/packages/play.nteract.io/pages/index.js).

Once we set `word-spacing:0px` everything is aligned.

![image](https://user-images.githubusercontent.com/2482408/33921273-ad47e7d8-df77-11e7-81a7-739fe04f033a.png)

fixed with 3b548d9

**Comment by rgbkrk** [comment]
Thanks for fixing this one, I've been annoyed with this on the desktop app and wasn't sure what was going on.
