### ISSUE TITLE
Kernel sometimes isn't really starting

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2156]
With the desktop app, on `master`, it seems that sometimes the app acts like its connected to the kernel even though it isn't responding to messages. It _seems_ like it's a timing issue of the kernel not quite being ready. Ever since we optimized things in #2137 I've noticed this behavior. That leads me to believe that there's a readiness issue that before was a non-issue due to timing.

One other thing I noticed while doing #2137 is that it seems like registering callbacks (other than `message`) on the jmp sockets is not giving us access to the zeromq events.

/cc @captainsafia @lgeiger

**Comment by dhirschfeld** [comment]
I'm seeing this too - just hadn't worked out a reliable repro to post...

**Comment by lgeiger** [comment]
We experienced something similar in Hydrogen: https://github.com/nteract/hydrogen/issues/591

This was fixed by [initially monitoring the sockets](https://github.com/nteract/hydrogen/blob/287b710b0af9821368ed9b8b234d6fcfa9b879e3/lib/zmq-kernel.js#L115-L145) until they are connected.

**Comment by rgbkrk** [comment]
Oh interesting, you only have to do that for shell, control, and stdin?

**Comment by rgbkrk** [comment]
Soooooo even after the monitoring setup I'm running into this. In fact, it's almost _worse_ now. Things I can tell now after logging more:

* The kernel is very much alive and can be connected to with a separate `jupyter console --existing ...`
* iopub is still functioning, and is passing on through our subjects

It _seems_ like it's the `send`ing that isn't working. There _was_ a new jmp release that we went ahead with upgrading to. Is that the root of the cause?

**Comment by rgbkrk** [comment]
One definite strangeness in our app is that it _appears_ that the channels are being created twice in a row.

**Comment by rgbkrk** [comment]
Whoops, that was just on my branch...
