### ISSUE TITLE
interact broken on macOS ?

### ISSUE THREAD

**Issue by mgiugliano** [nteract/archived-desktop-app#2202]
Launching interact OSX alpha (0.4.3) on macOS (10.13.1) results in having any new cell non-editable, regardless of its type.

shift-enter on an (empty) cell does create a new cell that becomes editable until a mouse click (anywhere).

**Comment by willingc** [comment]
We're having difficulty reproducing the behavior that you are seeing. Would you please reinstall nteract and provide a GIF of the behavior? Thanks.

**Comment by mgiugliano** [comment]
See attached (through DropBox link). 

In the first <https://www.dropbox.com/s/fxc8iccfs4sl32s/Dec-20-2017%2010-47-51.gif?dl=0> GIF, I simply launch nteract but I cannot “gain the cursor/focus” of any cell I click on.
In the second <https://www.dropbox.com/s/ku5u3nwva515wn2/Dec-20-2017%2010-51-33.gif?dl=0> GIF, I open an existing notebook and clicking in an existing cell, I can type some letters but then this stops working in empty cells by the end of the notebook.

I had been using version 0.1.0 happily before yesterday, when I decided to update.

I hope it is helpful
Michele

**Comment by willingc** [comment]
Thanks @mgiugliano for the GIFs. Did you install nteract by clicking the download link on nteract.io? Or did you use another method?

cc/ @rgbkrk @lgeiger @captainsafia

**Comment by mgiugliano** [comment]
Correct. It was the download link saying "alpha" for Mac OS.

M

Sent from a microscopic (touch) keyboard.

**Comment by lgeiger** [comment]
Could you try if this is also happening with the light theme?

**Comment by mgiugliano** [comment]
I tried: 

it works with the light theme!!!!!!!!
MG

**Comment by willingc** [comment]
Thanks for helping us isolate the issue @mgiugliano.

**Comment by rgbkrk** [comment]
Now that we only have light and dark themes, I can close this since we won't support the other themes again.
