### ISSUE TITLE
The grand test timeouts

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2242]
We are currently in an unprecedented time, in which a test suite that takes 9s to run locally takes 10 min. to run on Travis.

Example build: https://travis-ci.org/nteract/nteract/builds/321284616

Last week when the renovate PRs were swamping our overall builds, we reduced our 5 test suites to one combined suite and started running into this :new: issue.

**Comment by mpacer** [comment]
It might be nice to go back to 5 suites for Travis (since it can run 5 test suites concurrently) and rennovate bot is not currently swamping the repo with PRs. It probably still makes sense to keep them 1 test for appveyor.

**Comment by rgbkrk** [comment]
Yeah I think that's smart @mpacer. Are you cool with taking that on?

I'm going to go ahead and fix some of the warnings and errors I'm seeing in the jest suite, just to make sure we don't have an undiagnosed problem in the suites that should be handled regardless.

**Comment by rgbkrk** [comment]
A few of the test cleanups:

* https://github.com/nteract/nteract/pull/2247 (ready to be merged)
* https://github.com/nteract/nteract/pull/2248 (ready to be merged)

My next step is looking into the github bits. I think I need to delete all my local github env vars to make sure I'm running the "same" suite as Travis.

**Comment by rgbkrk** [comment]
Now that we're on CircleCI and the test times are better, I think we're good.
