### ISSUE TITLE
[play] editor's highlighting language should match kernel language after switching 

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#2250]
Right now we don't have the language being extracted and propagated up to the CodeMirrorEditor component; it's just hardcoded: 
https://github.com/nteract/nteract/blob/cef76af981463d34758abec82c8cc913d444a4d4/applications/play/components/Main.js#L172

If I'm thinking about this correctly, we probably want to store this in the `currentKernel` entity.

I'm not sure what pattern is best to accomplish this though (since the relevant info is deeply nested inside `currentServer.kernelSpecs.kernelSpecByKernelName.[currentKernelName].spec.language`)… I suppose I can look at the pattern used for `currentKernelName`?

**Comment by rgbkrk** [comment]
I think it's ok to use the nested bit. What you'll probably want to do is use `mapStateToProps` to create exactly the language prop you want from the overall state.

**Comment by rgbkrk** [comment]
Something else you may end up looking into / asking about: 

* https://github.com/nteract/nteract/issues/1479

In particular, we currently pass a string for the language when ideally we'd be able to send the exact codemirror mode.

**Comment by mpacer** [comment]
For now I'm going to stick to setting the language with a string, as that we can reliably handle from the kernelspec info.

So you think this should be at the ui level? I can do that it — just seems strangely clunky that we can't set this at the same time when we set the kernelSpec info, but maybe I'm misunderstanding something.

**Comment by rgbkrk** [comment]
I don’t think it has to be at the “ui” level in the state object, only that we derive the value from the state. You can use other properties to craft this if you need to and if it’s already in the state somewhere.

**Comment by mpacer** [comment]
In this case does "properties" == `props`? Or are properties a special kind of thing in javascript like they are in python? or what exactly do you mean?

**Comment by rgbkrk** [comment]
I'm saying that you can form the state however you want in `mapStateToProps`, computing values based on other values in the state tree.

--------

An aside:

[Properties are an association of keys to values in objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects). They're what you'd call attributes with Python objects. To make matters worse (better?), HTML uses the term attributes.

```html
<a href="https://nteract.io" /> <!-- href is an attribute -->
```

```
a = document.createElement('a');
a.href = "https://nteract.io"; // href is a property that becomes an attribute on the page
```

**Comment by mpacer** [comment]
> Properties are an association of keys to values in objects. They're what you'd call attributes with Python objects. To make matters worse (better?), HTML uses the term attributes.

Actually to make matters _even_ worse(better?)… in Python, properties (as declared by the `@property` decorator or the `property` function) allow you to create functions that are treated as `attributes` on you classes. (slight hand-waving with "treated as", but I figure for asides this is an appropriate level of detail).

**Comment by rgbkrk** [comment]
Yeah they’re pretty cool! I love that you can use them to do reactive things like with traitlets.

Definitely separate concepts.
