### ISSUE TITLE
Notebook-on-next next steps

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2259]
I just spent some time going over notebook-on-next and it appears the next big task is creating our epics, styled after or wholeheartedly using parts from the desktop epics. I'm seeing a couple ways to divide this up while also building in line with play:

* [ ] Connect up the execution epic from Desktop (possibly bring it into core)
* [ ] Figure out how the binder server entities state/reducer/epic setup from play can be applied here

**Comment by captainsafia** [comment]
I'll keep this closed for now. I think the work in this task.

> Figure out how the binder server entities state/reducer/epic setup from play can be applied here

is interesting but should be addressed separately.
