### ISSUE TITLE
Search for a word in the notebook (Ctrl + F)

### ISSUE THREAD

**Issue by vhoulbreque** [nteract/archived-desktop-app#2261]
Is there any way to search for a word in the notebook ?
I tried all the panels and the 'obvious' shortcuts but none of this worked.

I am aware of #1870 but I did not see any update since then.

**Comment by eseiver** [comment]
+1 would really love this feature (cc @mpacer)

**Comment by amirhosseindavoody** [comment]
This must be one of the first features that gets implemented.

**Comment by rgbkrk** [comment]
Very much needed, I'm going to merge all the find/replace issues in #1817 and close this one.
