### ISSUE TITLE
[chore] update babel settings

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2284]
Warning on current master:

```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

I'm not sure which package is using the old preset instead of env.

**Comment by lgeiger** [comment]
We're using it in the babel config for our packages

**Comment by rgbkrk** [comment]
I wonder what our target should be then.

On another note, I'd love if styled-jsx was included in our babel config always because I want to keep the same config across all the component libs.

**Comment by rgbkrk** [comment]
All set here!
