### ISSUE TITLE
triage: label issues

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2314]
Hey all!

I need _your_ help!

It would be awesome if folks could triage issues according to the `app` or `pkg` (package) that affects them. For instance, we have an `app:play` label that I've applied to the `play` issues I've seen. Steps:

* Go through each issue that you can
* Label it with `pkg:PACKAGE_NAME` and/or `app:APP_NAME`
* If you don't know what it relates to, feel free to either skip it or comment on it to help diagnose it. It's ok to declare it as an "app" issue if you don't know what package it belongs to.

Thank you!

**Comment by willingc** [comment]
Probably makes sense to preconfigure the labels so that they are consistent and folks can just click to add to an issue.

**Comment by willingc** [comment]
FWIW: I've also found more transparent colors work better for readability than the darker colors.

**Comment by rgbkrk** [comment]
Ok, I'll work on making the labels consistent and possibly delete some of our old ones.

**Comment by rgbkrk** [comment]
Some of the labels I'm going to keep around that have issues attached and we can clean them up over time here.

**Comment by rgbkrk** [comment]
I went with what jupyterlab had as standard in their monorepo for names, though I'd be ok if the names had spaces in them. Guess I'd want to know what folks think.

> FWIW: I've also found more transparent colors work better for readability than the darker colors.

I've tried to use lighter colors in these new tags. Feel free to adjust any that you think are abhorrent. 😄
