### ISSUE TITLE
Accept data about pushdowns for dataresource

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2323]
From @holdenk in #2273:

> If we’re going to do push downs (since we don’t have callbacks right now), would it make sense to allow the backend to specify a push down which has already been run (eg buckited)?

**Comment by rgbkrk** [comment]
Probably good to link this up with #2732

**Comment by emeeks** [comment]
@rgbkrk Is this still an issue? If so could you give more context?
