### ISSUE TITLE
Turn dataresource transform more into zeppelin style

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2324]
Zeppelin has a pretty good interface for toggling between table and chart types:

<img width="1424" alt="screen shot 2018-01-04 at 2 16 35 pm" src="https://user-images.githubusercontent.com/836375/34586776-4c6362fe-f15a-11e7-9d96-8b19d0f8819c.png">

<img width="1424" alt="screen shot 2018-01-04 at 2 16 21 pm" src="https://user-images.githubusercontent.com/836375/34586720-1319e0ae-f15a-11e7-9106-6d4a96628c2d.png">

As well as a neat way to pick your "Keys" (Axes), "Groups", and "Values" on a chart

<img width="1435" alt="screen shot 2018-01-04 at 2 17 01 pm" src="https://user-images.githubusercontent.com/836375/34586721-13318e48-f15a-11e7-93ac-60574d8a7a66.png">

It's not the end all-be-all, it's a good starter though on top of what we have. We could persist the settings for the chart to metadata on the output type as well.

Some other thoughts, beyond what zeppelin is currently doing that we should think about:

* How do you filter?
* Look again at [voyager](http://vega.github.io/voyager/)
* Lightweight pivot tables as a visualization

**Comment by rgbkrk** [comment]
/cc @thomasballinger @theengineear 

Also, I just noticed zeppelin has their own little suite of viz "plugins", I'm tempted to check out more of their approach and how well users are taking advantage of it.

https://zeppelin.apache.org/docs/0.7.0/development/writingzeppelinvisualization.html#how-it-works

**Comment by rgbkrk** [comment]
Silly me, I forgot to paste the link when posting.

**Comment by theengineear** [comment]
Yup. I think we can definitely improve the user experience here. I'm happy with making updates to this as long as we make sure not to overstep. For example, if we allow too much handy filtering in the UI for the visualizations, we may end up conditioning users to just `select *` all the time from tables.

One alternative is to try to nudge users into narrowing the number of columns they request in the first place. This is a super-common problem in viz. Another manifestation is creating tooling to handle down-sampling huge sets of data into a visualization. Arguably, the sampling should be done _prior_ to visualization in many cases.

Again, I think adding more functionality is definitely appropriate here, but let's make sure we consider how any features we add will condition users to do analysis.

**Comment by emeeks** [comment]
@theengineear We could make different charts and options available to users depending on the size and structure of the dataset. A thousand points as a pie chart is horrible but split into five categories and shown as a beeswarm plot could work very well for exploration. I think there's a challenge when it comes to the select * queries and the long (broad) results but in my initial iteration I tried to deal with that by only enabling the first suitable type for each chart and then letting the user switch between them.

**Comment by rgbkrk** [comment]
This was definitely done, though in a different style. Closing!
