### ISSUE TITLE
Kernel list not updating after uninstalling conda

### ISSUE THREAD

**Issue by Svarto** [nteract/archived-desktop-app#2325]
Hi,

The list of Kernels do not update after uninstalling conda completely (i.e. including the kernels). When I then uninstall and reinstall nteract, the old kernels that don't exist anylonger still stay in the list and are tried to be loaded throwing an error_loading_kernel error.

How can I reset the list / completely uninstall nteract so that it doesn't load old settings?

thanks!

**Comment by rgbkrk** [comment]
nteract only ships one kernel built-in, which is the node.js kernel. As for all other kernels, nteract just loads all jupyter kernels installed. Run:

```
jupyter kernelspec list 
```

to see the kernel directories that you'll want to delete.

**Comment by Svarto** [comment]
Thanks! I had to go in and manually delete certain folders that where under AppData (on windows) to remove the kernels that didn't exist anylonger.
