### ISSUE TITLE
404 when publishing a gist for the same file twice

### ISSUE THREAD

**Issue by snotskie** [nteract/archived-desktop-app#2326]
Whenever I try to published a gist for a file, the first time it works, both when trying it as a user gist or an anon gist.

When I try to published the same file again (say after correcting a typo, or without making any changes at all, etc), I get the following error pop-up:
![image](https://user-images.githubusercontent.com/2658495/34616010-648cf6c2-f1fc-11e7-827b-69aa8e95146c.png)

Getting this in both versions 0.5.4 and 0.5.5 on Win10.

I'm not sure if this is related to #1473, but it seems strange that it always works the first time. Closing and re-opening the nteract does not fix the issue, but creating a new file with the same contents does.

**Comment by jdetle** [comment]
Hey I'll look into this.
