### ISSUE TITLE
npm run dist uh-oh

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2340]
I _thought_ I was going to make a release tonight. When running `npm run dist` then opening the resulting mac App, I see an error titled `Uncaught Exception: ReferenceError: a22277 is not defined`:

![screen shot 2018-01-07 at 9 42 24 pm](https://user-images.githubusercontent.com/836375/34659995-aded3b6c-f3f3-11e7-89e1-d5007bf49dd7.png)

Guess we've got ourselves a new release blocker! I can still ship the packages, I can't touch desktop though.

**Comment by lgeiger** [comment]
Good news is, the problem lies in our [production webpack config](https://github.com/nteract/nteract/blob/master/applications/desktop/webpack.prod.js) and not in the dist packaging. I can reproduce this by doing a production build and running `npm run spawn`.

**Comment by rgbkrk** [comment]
If I had to guess then, I'd say it's something with Uglify.

**Comment by rgbkrk** [comment]
Sure enough, I took the uglify plugin out and it worked. I'll see what I can tweak.

**Comment by rgbkrk** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/4359

**Comment by rgbkrk** [comment]
Not that I think it's our internal use of `mapbox-gl-js`, that was just a decent thread with what could be the right issue.

**Comment by rgbkrk** [comment]
Just for fun, I'm trying the google closure compiler now.

**Comment by rgbkrk** [comment]
With Google Closure Compiler:

![screen shot 2018-01-08 at 8 26 50 am](https://user-images.githubusercontent.com/836375/34680392-ce64a54c-f44d-11e7-9ce9-db55242717b4.png)

**Comment by rgbkrk** [comment]
And the source of the issue:

```
var d3_document=this.document;
```

_Normally_, `this` is window.

https://github.com/d3/d3/issues/1330

**Comment by rgbkrk** [comment]
Options for language with closure-compiler:

https://github.com/google/closure-compiler/blob/839656d772ae2dd5bbcc448442105422cb548ca1/src/com/google/javascript/jscomp/CompilerOptions.java#L2949

**Comment by rgbkrk** [comment]
Ok, back to using uglify and figuring out what's going wrong.

**Comment by rgbkrk** [comment]
Great thing to do when "debugging" Uglify -- set `mangle` to false in the build.

```js
  new UglifyJSPlugin({
    parallel: true,
    uglifyOptions: {
      ecma: 8,
      mangle: false
    }
  })
```

I think that's ok for us too to have in our prod build since we'd want a better error message if a user hits a catastrophic issue:

<img width="532" alt="screen shot 2018-01-08 at 9 02 57 am" src="https://user-images.githubusercontent.com/836375/34682090-bc02db26-f452-11e7-824c-669c4bc2e872.png">

**Comment by rgbkrk** [comment]
Better config for debugging:

```
  new UglifyJSPlugin({
    parallel: true,
    uglifyOptions: {
      ecma: 8,
      mangle: false,
      keep_classnames: true,
      keep_fnames: true
    }
  })
```

I need to work on other parts of the code so I think I'll leave this alone for now. Current options I'm seeing that are more workaround than solution:

* Disable uglify in general, just ship it
* Disable uglify on the webpack build of the main process'
* Keep tuning uglify parameters (possibly disabling some things) until it builds

**Comment by rgbkrk** [comment]
Running the dist now works, so I'm going to ship the app :soon:!

**Comment by rgbkrk** [comment]
annnnd the dist is still working, so I'll be shipping _again_ soon with 0.7.0 (this weekend, pending Hydrogen's compatibility with the new mathjax setup).
