### ISSUE TITLE
Plotly with default Node.js kernel?

### ISSUE THREAD

**Issue by lukejanicke** [nteract/archived-desktop-app#2345]
Is it possible to use Plotly in a notebook with just the default JavaScript/Node.js kernel?

I am looking for a way to do some basic computational mathematics in the classroom with minimal (preferably no) command line stuff, like installing other kernels etc.

**Comment by rgbkrk** [comment]
https://github.com/n-riesco/ijavascript-plotly is probably the right way to go about it, @n-riesco is the maintainer of the ijavascript kernel too (the one we bundle).

**Comment by rgbkrk** [comment]
That being said, we could probably use an example notebook that shows how to use it (and somehow includes the dependency...)

**Comment by lukejanicke** [comment]
Looks like the answer! Thank you. I’ll give it a go on the weekend and close the issue then.
