### ISSUE TITLE
Error message on switching kernel

### ISSUE THREAD

**Issue by atbug** [nteract/archived-desktop-app#2346]
I am using nteract with ipython kernel under Windows. If I switch to node.js kernel and then to ipython kernel, there's an empty error message shown below:
![image](https://user-images.githubusercontent.com/8522036/34719480-fe40ccd6-f575-11e7-9e0f-b5f83ba12dd9.png)

Everything works fine after that. However, this is kind of annoying.

More info:
nteract version: 0.5.5
ipython version: 6.1.0
python version: 3.6.2 (Anaconda)

**Comment by falbarelli** [comment]
I can reproduce this bug on macOS High Sierra as well

**Comment by atbug** [comment]
This is gone in the most recent release.
