### ISSUE TITLE
Match Jupyter Table style on HTML output

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2349]
In our `<Output>` component, we should match the table style for Pandas keeping similar parity with Jupyter:

<img width="534" alt="screen shot 2018-01-09 at 1 46 15 pm" src="https://user-images.githubusercontent.com/836375/34744881-84c69912-f543-11e7-8b91-de9374a883f9.png">

It's mostly the addition of new inline "global"-esque styles here: https://github.com/nteract/nteract/blob/83c60ae26d61c939101a255b034ad386162bff2c/packages/core/src/components/index.js#L95
  
/cc @mpacer

**Comment by rgbkrk** [comment]
IIRC, this is likely a case of needing to acknowledge the specific CSS classes defined between pandas HTML output and Jupyter. Jupyter notebook recognizes these directly, so they're a bit of an unstated CSS contract.

**Comment by rgbkrk** [comment]
We should probably still do this.

**Comment by kelleyblackmore** [comment]
I'll take a look at this one if this is still wanted unless it was already done.

**Comment by rgbkrk** [comment]
Definitely not done. The current styles you'll want to add on to are in https://github.com/nteract/nteract/blob/83c60ae26d61c939101a255b034ad386162bff2c/packages/core/src/components/index.js
