### ISSUE TITLE
Optimize performance of our components

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2362]
This is especially important for big notebooks, though it can be noticed with smaller ones as well. Here's some super light editing of a notebook in notebook-on-next, using React devtools with "Highlight Updates" checked:

![highlight-updates](https://user-images.githubusercontent.com/836375/34843855-8fdb8498-f6c4-11e7-8a32-6f30753015b7.gif)

Notice how changing one cell is causing a re-render of _all_ the cells. That should not be the case with our components. I _think_ this is because the `cellMap` is changing (as our top level prop), so then all the children have to re-render (from the `<NotebookApp/>` component).

I'm a total novice on performance optimizations here. There are components that we could actually write a custom `shouldComponentUpdate` for (or even switch some to `PureComponent`). _This_ however looks like an architectural issue possibly (?). Perhaps it's just that the cells themselves should have their own `shouldComponentUpdate` (or the components inside).

**Comment by lgeiger** [comment]
As an very simple starting point we might want to enable the [`jsx-no-bind` ESLINT rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md):
> A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary. It may also cause unnecessary re-renders if a brand new function is passed as a prop to a component that uses reference equality check on the prop to determine if it should update.

**Comment by lgeiger** [comment]
Here's a nice little tool that logs potential unnecessary renders: https://github.com/maicki/why-did-you-update

**Comment by rgbkrk** [comment]
At first I was like "that's silly, we don't do any binding anywhere that's passed through". Then I realized that all our cells are passing in arrow functions that call to dispatch with their ID... 🤔

**Comment by rgbkrk** [comment]
It turned out to be much more than the bound functions. Because the `<NotebookApp />` had `cellMap` as a prop, literally any change to any cell was causing the whole tree to render because the root was. I'm looking forward to finishing this up in #2402, it's working _really_ well now!

**Comment by rgbkrk** [comment]
I think we can declare this one as iteratively improving, though it would be super neat if we measured performance on CI someday.
