### ISSUE TITLE
YError when starting nteract 0.5.5 on Ubuntu 17.10

### ISSUE THREAD

**Issue by bgodard** [nteract/archived-desktop-app#2371]
When starting nteract 0.5.5 on Ubuntu 17.10, a popup window appear in the top right corner of the notebook with the message "ERROR" and an error message is displayed in the console (see below).

The notebook seems otherwise usable.

This happens both with AppImage and Debian package.
This does not happen with nteract version 0.4.3.

> $ nteract 
> YError: Invalid first argument. Expected boolean or string but received function.
>     at i (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:239215)
>     at c.optional.forEach.e (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:240072)
>     at Array.forEach (native)
>     at e.exports (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:239972)
>     at Object.S.version (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:916317)
>     at Object.<anonymous> (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:255879)
>     at t (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:256)
>     at /opt/nteract/resources/app.asar/lib/webpacked-main.js:1:606
>     at Object.<anonymous> (/opt/nteract/resources/app.asar/lib/webpacked-main.js:1:617)
>     at Object.<anonymous> (/opt/nteract/resources/app.asar/lib/webpacked-main.js:2:3)
> [10:46:29.260] [info] args { _: [],
>   version: false,
>   v: false,
>   help: false,
>   h: false,
>   kernel: 'python3',
>   k: 'python3',
>   '$0': '/opt/nteract/nteract',
>   verbose: undefined }
> [10:46:29.967] [warn] APPIMAGE env is not defined, current application is not an AppImage
> [10:46:30.230] [info] launching an empty notebook by default
> 

![nteract-error](https://user-images.githubusercontent.com/8047509/34906351-c40ed9fe-f863-11e7-9cbd-bcea87aaa0f1.png)

**Comment by atbug** [comment]
duplicate of #2346

**Comment by jkornblum** [comment]
duplicate #2369
