### ISSUE TITLE
Data Loss on Save for Hung Kernel

### ISSUE THREAD

**Issue by gdbassett** [nteract/archived-desktop-app#2373]
I have had this happen twice where I had a notebook.  The kernel hangs and so I attempt to save the notebook and restart.  However, saving the notebook appears delete it's content (size of 0), without writing in the new content, causing loss of all analysis content.

**Comment by rgbkrk** [comment]
Yuck. That is not sounding good. I'll see if I can reproduce that with those steps.

**Comment by gdbassett** [comment]
I apologize for not adding additional detail.   This is OS X version 0.3.4 with an R kernel saving to a locally mapped network share.  I don't know that any of those matter, but wanted to be clear.  Also, I tried interrupting the kernel first without success.

**Comment by rgbkrk** [comment]
This is the latest version of nteract too?

**Comment by gdbassett** [comment]
Humm. No, it doesn't seem to be. It looks like 0.5.5 is latest. Odd. I had thought it was auto updating. I will see if I can reproduce with the most current version tomorrow.

**Comment by rgbkrk** [comment]
I've noticed locally that on `master` that if I run "kill kernel", messages are still coming in, so our cleanup isn't completely happening.

**Comment by willingc** [comment]
Next step: Determine if this is still an issue on master branch.
