### ISSUE TITLE
Errors inside reducers are not being reported up

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2387]
Our error middleware is not noticing issues. The only way I was able to notice was via the `DEBUG=true` mode.

**Comment by jameskoch** [comment]
Which app?  I just noticed that in jupyter_extension we don't wire in the errorMiddleware. PR coming shortly for that.

**Comment by captainsafia** [comment]
I'm gonna go ahead and close this one because it seems to be resolved.
