### ISSUE TITLE
Question about unsaved data appears even if just saved

### ISSUE THREAD

**Issue by falbarelli** [nteract/archived-desktop-app#2393]
I am using nteract 0.5.5 on MacOS High Sierra.
When I quit a notebook the software always asks me if I am sure, even if I have done no edits to the file since last save, is this feature missing completely or is it a bug?

**Comment by rgbkrk** [comment]
Feature is only partially implemented, it always unconditionally asks if you've saved.

**Comment by rgbkrk** [comment]
This was fixed in the 0.8.x series.
