### ISSUE TITLE
Notebooks become unresponsive

### ISSUE THREAD

**Issue by falbarelli** [nteract/archived-desktop-app#2394]
I am using nteract 0.5.5 on macOS High Sierra.
I noticed that very often notebooks become unresponsive, i.e. I scroll but the notebook window is almost frozen. I use notebooks with some figures, but not big at all...
Does it happen to anybody else?

**Comment by rgbkrk** [comment]
We had a regression in the last release that caused performance issues on notebooks, even on smaller sizes. We're looking to get a new release out soon.

**Comment by rgbkrk** [comment]
We did get a release out and we've got another coming up that has optimized rendering a bit more.
