### ISSUE TITLE
Convert all redux state to Immutable objects

### ISSUE THREAD

**Issue by theengineear** [nteract/archived-desktop-app#2398]
The redux state we're using is currently partially `Immutable` and partially just plain JS objects. This is because we use `redux`'s `combineReducers`. However, we recently introduced `redux-immutable`, which has a `combineReducers` function that returns a `Immutable.Map` instead of an `Object`. We should change all our state over to just being Immutable so we can safely depend on everything coming from state being `Immutable` in our codebase.

Additionally, we should ensure that if we _know_ the shape of a piece of state, it should be an `Immutable.Record` and if we don't know the shape of the state (e.g., `*ById`), it should be an `Immutable.Map`.

Here are a couple examples where I think things could change:

https://github.com/nteract/nteract/blob/master/applications/jupyter-extension/nteract_on_jupyter/store.js#L39

https://github.com/nteract/nteract/blob/45b39e8091b8d7ad92d8c129a6d12ad740c86056/applications/desktop/src/notebook/reducers/index.js#L7

**Comment by theengineear** [comment]
@rgbkrk there's actually not _too_ many places where this needs changing. `play` is a big one, that was built entirely without `Immutable`, but should convert if/when it starts using `core` state managerment.

**Comment by rgbkrk** [comment]
Individual reducers are all immutable now. The only thing missing now is that our root level reducer still uses `combineReducers`.

**Comment by rgbkrk** [comment]
I think we're in a fine state nowadays. What do you think @captainsafia?

**Comment by captainsafia** [comment]
Yeah. Everything in the state is an immutable object accessible via the selectors. We’re good on this front. 👍🏽
