### ISSUE TITLE
Consistent Async ActionType Constants

### ISSUE THREAD

**Issue by theengineear** [nteract/archived-desktop-app#2400]
We should pick a convention for naming action type strings, actions, and action types 😸.

Rationale:

1. It's really nice to be able to drop into any package/app directory and have a sense of what things are doing by looking at actions.
2. It's really nice to be able to look at redux devtools and see consistent patterns as action types are logging out.
3. It'd be nice to not have to think about it when we're clicking in these boiler plate defs.

## Proposal

Let's try to standardize three things (yes, this is boiler plate-y).

### Actual type strings

How about we standardize on the following? I feel like this is a pretty common approach and I would find it helpful to have direction on this one?

```
[<PREFIX>/, ..]<VERB>_<NOUN>
[<PREFIX>/, ..]<VERB>_<NOUN>_FULFILLED
[<PREFIX>/, ..]<VERB>_<NOUN>_FAILED
[<PREFIX>/, ..]<VERB>_<NOUN>_CANCELED
```

Example:

```
CORE/FETCH_HOST
CORE/FETCH_HOST_FULFILLED
CORE/FETCH_HOST_FAILED
CORE/FETCH_HOST_CANCELED
```

### Type constants

This one's simple, and we do this already. Just use all but the prefix.

`const <VERB>_<NOUN> = "[<PREFIX>/, ..]<VERB>_<NOUN>";`

`const FETCH_HOST = "CORE/FETCH_HOST";`

### Action creator

Also simple, and we do this already. Just `camelCase` the type constant.

`const <verb><Noun> = () => { .. };`
`const fetchHost = () => { .. };`

### Action creator type

Also also simple, and we mostly do this. Just `PascalCase` the action creator name.

`type <Verb><Noun> = { .. };`
`const FetchHost = { .. };`

### Example

```
const FETCH_HOST = "CORE/FETCH_HOST";
type FetchHost = { .. };
const fetchHost = ({ .. }) => { .. };
```

### bare + postfixes

```
<VERB>_<NOUN>
<VERB>_<NOUN>_FULFILLED
<VERB>_<NOUN>_FAILED
<VERB>_<NOUN>_CANCELED
```

This sorta breaks down when you don't have a noun... `fetchInterrupt

e.g.,

```
FETCH_KERNELSPECS
FETCH_KERNELSPECS_FULFILLED
FETCH_KERNELSPECS_FAILED
```

e.g.,

```
LOAD
LOAD_FAILED
```

### bare + prefixes

```
<VERB>
DONE_<VERB>
```

e.g.,

```
SAVE_CONFIG 
DONE_SAVING_CONFIG
```

**Comment by theengineear** [comment]
@rgbkrk I didn't really intend for this description to get so lengthy. This is a pretty simple ask, and I *think* we're all likely on the same page on this one, but I figured this might be a good time to bring it up to be officially discussed?

**Comment by rgbkrk** [comment]
We haven't taken much practice and care to it before, so I'm really happy to make it standardized so it's easy to read and understand all over the place.

**Comment by rgbkrk** [comment]
I'm totally cool with the entire proposal as is, the "hidden" prefixes included and the matching action verb names.

**Comment by theengineear** [comment]
Great! I'll start adding the new action type strings / action types / actions according to that and we can create an issue to bring the other things into conformity down the road.

**Comment by rgbkrk** [comment]
> This sorta breaks down when you don't have a noun... `fetchInterrupt`

For the less REST-y ones like this maybe `issueX` makes more sense. They're more RPC than they are REST. `issueKernelInterrupt`, `issueKillKernel`. Do those seem sensible?

**Comment by theengineear** [comment]
^^ I think it'd be `interruptKernel`, `interruptKernelFulfilled`, `interruptKernelFailed`, `interruptKernelCanceled` though, right?

**Comment by rgbkrk** [comment]
Yeah that sounds good. Those _are_ the verbs. Silly me.

**Comment by theengineear** [comment]
Related to naming conventions. I'm coming from using `createAction` (https://redux-actions.js.org/) which basically locks the action form to `{type: string, payload: Object}`, but I noticed that `nteract` tends to spread out what could be considered the `payload` into the top-level action. Any reservations if _do_ envelope with `payload`?

**Comment by rgbkrk** [comment]
I'm a fan of the payload convention, it's just enough of a refactor that I haven't wanted to change things up just for the sake of doing it. There have definitely been some areas where it could have been easier to work with it.

At any rate, yeah I'm certainly open to payload envelopes.
