### ISSUE TITLE
Syntax highlighting not working for all kernels

### ISSUE THREAD

**Issue by kubark42** [nteract/archived-desktop-app#2424]
The below shows the same code, opened in both nteract and jupyter notebook.

![screenshot_1](https://user-images.githubusercontent.com/1118185/35444438-8fa68482-027c-11e8-9872-514fed7a36ed.png)

This is running Jupyter's Matlab kernel, and nteract `v0.6.2`.

**Comment by rgbkrk** [comment]
Can you post a notebook, that uses these kernels? I'd love to see what the kernel info metadata is that's stored in the notebook itself. This totally relates to the codemirror mode we're setting.

**Comment by kubark42** [comment]
Here it is. Looks like it wants jupyter to use the Octave `codemirror_mode`, which is kind of right (and kind of not, because Octave is designed to look like Matlab, and not the other way around).

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "x =\n",
      "\n",
      "     1     2     3     4     5     6     7     8     9    10\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "image/png": "<trimmed>\n",
      "text/plain": [
       "<IPython.core.display.Image object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "x = 1:10;\n",
    "y = sin(x);\n",
    "\n",
    "plot(x,y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Matlab",
   "language": "matlab",
   "name": "matlab"
  },
  "language_info": {
   "codemirror_mode": "octave",
   "file_extension": ".m",
   "help_links": [
    {
     "text": "MetaKernel Magics",
     "url": "https://github.com/calysto/metakernel/blob/master/metakernel/magics/README.md"
    }
   ],
   "mimetype": "text/x-octave",
   "name": "matlab",
   "version": "0.15.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by rgbkrk** [comment]
Ok, cool this helps. Thank you for the example notebook for us to test against!

**Comment by rgbkrk** [comment]
This might be fixed on master now that we've adapted our codemirror language settings into one central spot. Hopefully we'll have a release out this week to test.

**Comment by kubark42** [comment]
Very cool, looking forward to testing the new release.

**Comment by smarguet** [comment]
Would looove to have matlab syntax highlighting in nteract (especially with jupyter, since we cannot use the bundled chromium and still get GL support.)  Seems it's still missing?
