### ISSUE TITLE
Notebook with embedded vega-lite output doesn't show properly

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#2436]
I'm trying to use the built-in vega-lite support for the julia [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl) package. Through a lot of hoops I managed to create [this](https://gist.github.com/davidanthoff/acff2966a27c9e8833a621756f8be15c) notebook file. Don't try to run the code in that notebook, that part only works if you have a whole number of unreleased branches checked out on the julia side of things.

BUT, at the end of the day, I would have expected that if this notebook file just gets opened in nteract, that it would show the vega-lite plot. The second cell does have a data field that has the mime type ``application/vnd.vegalite.v2+json``, and inside there it does have a valid vega-lite 2 spec, so shouldn't this show the graph if I just open that file in nteract?

**Comment by rgbkrk** [comment]
Thanks for reporting, we'll take a look at this as part of our current sprint.

**Comment by davidanthoff** [comment]
Actually, don't! It was a mistake on my end, I just sorted it out this morning over at the jupyterlab issue.

**Comment by rgbkrk** [comment]
Nice, that means another issue closed for this milestone. 😄
