### ISSUE TITLE
Nteract on Windows 10 with Ubuntu

### ISSUE THREAD

**Issue by leonyeh8** [nteract/archived-desktop-app#2450]
I have successfully installed nteract on mac. Now I am going to give it try on Windows.

On windows, I use ubuntu subsystem to make it appear to be like MacOS / UNIX/

I have installed jupyter / anaconda on ubuntu for windows plus python3. 

However when I started nteract, it only show nodejs kernel. No python3, like on windows. It seems like the ubuntu is on different process or something. What did I do wrong ?

Sorry if this is a newbie question. Thanks in advance,
Leon

**Comment by jkornblum** [comment]
Are you running nteract from Windows and wanting to use your Python environments installed on your ubuntu subsystem?

**Comment by leonyeh8** [comment]
Yes, is that possible ? Do I need to install it on the windows itself ?

**Comment by jkornblum** [comment]
Should be possible I think, you will probably have to edit kernelspecs yourself.
When nteract loads it's looking for kernelspec files which define kernel details (name, location, etc).

When you load nteract on Windows I think nteract is checking the Windows location but your kernelspecs are installed on the Linux subsystem.

The Windows user location is `%APPDATA%\jupyter\kernels` which on mine is `C:\Users\<name>\AppData\Roaming\jupyter\kernels`

The Linux user location for kernelspecs is `~/.local/share/jupyter/kernels`

You can try and copy your kernelspecs from Linux location to the Windows location and then try to launch nteract again. Windows needs to be able to access and launch Python from the linux subsystem file location. Check out the kernel.json file to make sure Windows can interpret the file location.

https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernelspecs

**Comment by leonyeh8** [comment]
I tried but it is too complicated for me. I ended up using conda installed on windows partition, and it works fine. Thanks for the help

**Comment by kubark42** [comment]
I had a similar problem for a similar reason. It'd be awesome to see support for directing nteract toward a running kernel, even if it can't detect it locally.
