### ISSUE TITLE
[Feature request] autosave

### ISSUE THREAD

**Issue by kubark42** [nteract/archived-desktop-app#2466]
Just have nteract crash (due to it not being able to reassert control over a runaway python kernel and/or print command), and lost work upon reopening. Something which Jupyter typically does is save the notebook state every time a cell is run. This prevents loss work when a browser window crashes, for instance. It would be nice to see similar functionality on nteract's excellent desktop client.

**Comment by captainsafia** [comment]
Thanks for submitting this issue @kubark42!

Adding auto-saving has been one of our priorities with nteract. As per usual, we want to make sure that when we do add the autosaving feature it is a really good implementation. This requires that we refactor and clean up a lot of other things beforehand so it's taking a while to get this in.

**Comment by rgbkrk** [comment]
We now have autosave!
