### ISSUE TITLE
Auto-Completion and Suggestions with julia-0.6.2 Kernel on macOS 10.12

### ISSUE THREAD

**Issue by lostermann** [nteract/archived-desktop-app#2471]
I'm running nteract 0.6.2 with the julia-0.6.2 (coincidently the same version number) on macOS 10.12.6 and Auto-Completion or Suggestions only work if I create a new cell first. The first cell in a new document or any cell in an existing document when reopened after it has been saved do not allow for Auto-Completion or suggestions or replacements (e.g. like \alpha becoming a Greek alpha upon Tab).

![screenshot](https://user-images.githubusercontent.com/9532608/35755838-27027d6c-0869-11e8-8849-590a62a51a1b.png)

**Comment by rgbkrk** [comment]
Odd. I'll give that try to reproduce, there may be logs in the dev tools for this `View -> Toggle Developer Tools`.
