### ISSUE TITLE
LaTeX Rendering issue

### ISSUE THREAD

**Issue by paulnakroshis** [nteract/archived-desktop-app#2482]
I wanted to report what I think is a bug in the (presumably MathJax?) 
rendering in nteract. If I try to put a space in a LaTeX equation rendered as
display math (example: <$$ F = m\, a   $$>), the thin space does not render 
properly, and simply displays a comma. When I run the same equation in a 
Jupyter notebook (using Anaconda’s current version as of today), the space renders 
properly. @captainsafia 

Thanks for all your work. I have told all my students about nteract and as it matures, 
I am able to use it for more and more work. 

Best,
-paul

**Comment by rgbkrk** [comment]
In the latest 0.7.0 release (literally released 7 minutes ago), this _should_ show up well. How's this:

![screen shot 2018-02-05 at 6 18 22 pm](https://user-images.githubusercontent.com/836375/35838608-f9bfcec4-0aa0-11e8-84cb-c3c1903062b5.png)

**Comment by paulnakroshis** [comment]
Interestingly, I cannot write $$ F = m\, a $$ with a slash before the comma in this editor because the backslash doesn't render. In any case, my issue in the new version is fixed, and the backslash comma correctly renders as a thin space. Nice job on LaTeX fonts.
