### ISSUE TITLE
Restart Kernel throws exception (0.7.0)

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2486]
![image](https://user-images.githubusercontent.com/881019/35842490-2bdf7fb4-0b4e-11e8-8aaa-8f26b39e8ccb.png)

Two exceptions, actually - always two. This is on windows with the latest 0.7.0.

Let me know if there's anything else you need to track it down...

**Comment by dhirschfeld** [comment]
NB: It seems to work fine despite the errors

**Comment by rgbkrk** [comment]
Interesting! Luckily it's a failure to cleanup the old kernel during a restart, so that's probably why it seems to work afterward. Super helpful to see these messages, thank you!

/cc @theengineear

**Comment by litaxc** [comment]
Same thing happens on Mac, too.

**Comment by jkornblum** [comment]
I cannot switch kernels on ubuntu (errors out) on 0.7.0
I can file separate issue if necessary
