### ISSUE TITLE
[core] Sticky cells pass focus to next on shift-enter

### ISSUE THREAD

**Issue by theengineear** [nteract/archived-desktop-app#2506]
I noticed this when I needed to refactor a test in the `notebook-spec.js` file.

## Expected behavior

When you `shift+enter` in a sticky cell, it should execute in place and not focus the next cell.

## Actual behavior

Not ^^.

**Comment by theengineear** [comment]
@rgbkrk I wanted to link an issue in a PR I'm about to open. Have you noticed this one yet?

**Comment by rgbkrk** [comment]
I've definitely noticed this one. I think it would be far easier for us to tear out the sticky cells and come back to them as a separate feature someday -- docked (and mirrored) output or something similar.

**Comment by theengineear** [comment]
Yah, I think ripping it out would be a good idea. Any idea how much backlash there would be?

**Comment by rgbkrk** [comment]
From https://github.com/nteract/nteract/pull/2507#discussion_r167042929:

Yes! We ran [an informal poll on twitter](https://twitter.com/nteractio/status/918636485263405056) in October of 2017.

----

_Do you use "pin cell" in nteract desktop?_

|  # | % | Choice | 
|---|---|------|
| 5 | 26.3% | Never, it's so not for me  |
| 5 | 26.3% | Once for funsies |
| **7** | 36.8% | **Hardly ever** |
| 2 | 10.5% | All the time, it's my jam |

**19 respondents**

----

I'm willing to say, based on those results, that it would be ok to remove it in favor of maintainability. We can always keep the component + styling in core, just rip it out of the standalone notebook app.

**Comment by rgbkrk** [comment]
Sticky cells are now out so this is no longer relevant.
