### ISSUE TITLE
mixed latex/mathjax rendering now appears all latex/mathjax

### ISSUE THREAD

**Issue by amcdawes** [nteract/archived-desktop-app#2509]
When using the QuTiP package (which mixes LaTeX/mathjax rendering into the output) I see different behavior in 0.7.1 compared to 0.6.2 (attached image, 0.7 on top, 0.6 on the bottom). I know there were changes to mathjax and perhaps other things in the latest release so I'm curious if there is a way to add support for the kinds of output qutip generates (or I can try to update qutip to work as expected in nteract).

<img width="562" alt="screen shot 2018-02-08 at 7 56 31 am" src="https://user-images.githubusercontent.com/406657/35983423-db55963c-0ca6-11e8-927d-4038b14684f2.png">

In looking more closely, the qutip objects (qobj) define a `_repr_latex_()` method to generate the latex output, but it mixes-in regular text:
```
In [8]: basis(2,0)._repr_latex_()
Out[8]: 'Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket\\begin{equation*}\\left(\\begin{array}{*{11}c}1.0\\\\0.0\\\\\\end{array}\\right)\\end{equation*}'
```

One option is to change qutip so this whole string is valid latex and renders the text portion in a nice way. I'm not clear on what changed in nteract to make this render differently in jupyter vs nteract.

**Comment by rgbkrk** [comment]
Ah, we started passing the whole thing to MathJax to typeset within our LaTeX transform. Looks like we need to do parsing here or a MathJax setup that will only look for the right elements. I'll dive into this.

**Comment by amcdawes** [comment]
On the one had, it seems reasonable to expect the result of `_repr_latex_()` to return fully-valid LaTeX. On the other hand, that is not what packages currently do (mainly since they've just done what they needed to do in order for it to "just work" in jupyter.

**Comment by rgbkrk** [comment]
I'd certainly prefer assuming it was fully valid LaTeX with a `_repr_latex_`, though I'd have to assume we'd have no support for stylesheets, no having to use `\begin{article}`, etc.

**Comment by amcdawes** [comment]
I don't think the implications go that far back in the processing. For this specific case, simply changing `_repr_latex_` to return `'\mathrm{Quantum~object: dims = [[2], [1]], shape = (2, 1), type = ket}\\begin{equation*}\\left(\\begin{array}{*{11}c}1.0\\\\0.0\\\\\\end{array}\\right)\\end{equation*}'` fixes it... in the sense that the text looks correct. It's still parsed by mathjax (which is fine).

~~I think it's reasonable to expect things coming from `_repr_latex_()` to be stuffed into mathjax... and ask people to plan accordingly.~~

Nevermind, using `\mathrm{...}` breaks `nbconvert` so isn't likely to be a workable solution.

**Comment by mpacer** [comment]
I almost think that a nicer way to approach this would be to have a way to approach LaTeX and mathjax separately where they could play separate roles. (e.g., with `_repr_mathjax_` rendering in the browser using mathjax and allowing `_repr_latex_` to be used specifically for LaTeX). That way we could easily handle the two cases by having separate ways of specifying things depending on the appropriate format.

**Comment by mpacer** [comment]
If you wrap the first part in an in-line equation (`$…$`) does it successfully render in both cases? The issue with \mathrm in LaTeX is that it’s only valid in math mode.

**Comment by amcdawes** [comment]
I like the idea of a `_repr_mathjax` and `_repr_latex` since that respects the differences between the two systems. It seems easy enough to fallback on `_repr_latex` if there isn't a mathjax method (since that would likely do ok). A bigger issue may be why the behavior in nteract has diverged from jupyter notebook. Packages that define `_repr_latex` are likely to make sure they work in jupyter (and nbconvert). Seems like the safest bet is to replicate notebook behavior (or coordinate adoption of `_repr_mathjax` by both projects)

**Comment by amcdawes** [comment]
@mpacer wrapping with `$...$` adds literal $ around the output in nteract 0.7.1. I think this is because nteract is passing all of `_repr_latex` to mathjax in a math environment already. Essentially, that's why this issue started. It seems like earlier versions did not do that; in 0.6.2 the extra $'s do not appear, and nteract displays the resulted \mathrm formatted strings.

**Comment by rgbkrk** [comment]
We'd like to conform to the same specification for both, the implementation just released was an oversight that I'd like to fix soon. We improved our Markdown rendering and took a step backward for LaTeX outputs. In #2510 I'm using qutip's outputs for regression testing, and I'll incorporate it in a test suite.

**Comment by rgbkrk** [comment]
What the heck happened to the stale bot??!

**Comment by rgbkrk** [comment]
I'm going to pin this issue as I want to make sure this issue is well done. 😄

**Comment by amcdawes** [comment]
Ha, I just figured the stale bot was trying to drum up donations for the project... maybe it should just be adjusted to say "if you donate, I won't email you constantly for the next four hours"

Thanks for keeping this issue in sight

**Comment by rgbkrk** [comment]
> Thanks for keeping this issue in sight

No problem, I've been working on the MathJax / LaTeX bits for the last couple days so it's good for me to have issues like this fresh in mind. 🧠
