### ISSUE TITLE
Alphabetize runtime menu entries

### ISSUE THREAD

**Issue by jkornblum** [nteract/archived-desktop-app#2513]
Maybe there is a sort order to this? Not sure.
It doesn't seem to be ordered by kernel name or display name for me.
I'd prefer them to ordered by display name, what are your thoughts?

![runtime-menu](https://user-images.githubusercontent.com/5368903/36007946-776bfa58-0d0a-11e8-9302-d618e58e8ee3.png)

**Comment by rgbkrk** [comment]
Sorting by display name would be cool.

**Comment by jkornblum** [comment]
Closed with #2591
