### ISSUE TITLE
nteract.io website appears to be down

### ISSUE THREAD

**Issue by vsivsi** [nteract/archived-desktop-app#2523]
Comment says it all.

**Comment by vsivsi** [comment]
And now it works...   Blah.

**Comment by vsivsi** [comment]
Down again...

**Comment by rgbkrk** [comment]
Thanks. Yet another reminder I should switch us off of now.sh. 😞

**Comment by vsivsi** [comment]
Yeah, that's a bummer. I want to like that service.  BTW, It's down again as of right now.

**Comment by rgbkrk** [comment]
Ok I've made a fresh deployment and switched it to default scale to two nodes and never go to sleep. I'll do the same for play.nteract.io as well.

**Comment by mbdevpl** [comment]
Website seems to be down now...

**Comment by mbdevpl** [comment]
Oh. It's back again.
