### ISSUE TITLE
Just shows a blank window?

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#255]
Is it supposed to do more at this stage?

**Comment by jdfreder** [comment]
Hi @geekraver , right now an empty notebook is created.  You should see a single cell, like this:

![emptycell](https://cloud.githubusercontent.com/assets/3292874/14008166/fdd17fd4-f13a-11e5-9d63-1eec9669d771.jpeg)

If you don't see that cell, can you click  View->Toggle Developer Tools and then look at the web console.  Are there any errors there?  There are various failure modes that may cause the behavior you see.  We don't yet have a nice user facing error reporting mechanism.

**Comment by ghost** [comment]
Interestingly, I ran it on my work Mac and it worked, but on my personal Mac I get the blank window. In each case I did pretty much the same install (git clone, npm install, npm install electron-standalone). 

Console does show:

```
Uncaught Error: Could not locate the bindings file. Tried:
 → /Users/gram/nteract/node_modules/zmq/build/zmq.node
 → /Users/gram/nteract/node_modules/zmq/build/Debug/zmq.node
 → /Users/gram/nteract/node_modules/zmq/build/Release/zmq.node
 → /Users/gram/nteract/node_modules/zmq/out/Debug/zmq.node
 → /Users/gram/nteract/node_modules/zmq/Debug/zmq.node
 → /Users/gram/nteract/node_modules/zmq/out/Release/zmq.node
 → /Users/gram/nteract/node_modules/zmq/Release/zmq.node
 → /Users/gram/nteract/node_modules/zmq/build/default/zmq.node
 → /Users/gram/nteract/node_modules/zmq/compiled/5.1.1/darwin/x64/zmq.node
```

I do have zeromq installed with brew.

**Comment by rgbkrk** [comment]
That's peculiar. They're not a shared filesystem in any way are they?

In the past I've had to run `npm install` twice. If that's still an issue, then blech.

**Comment by rgbkrk** [comment]
Thank you for your time in working through what is a fairly awkward startup process for the development environment. We're looking forward to refining it, including making prebuilt zmq for node so install is _way_ easier.

**Comment by willingc** [comment]
@rgbkrk I'm getting the blank screen on OS X as well with the following message after `npm run start`

```
npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.
```

**Comment by willingc** [comment]
Output from the web console:
<img width="881" alt="screen shot 2016-04-01 at 3 48 09 am" src="https://cloud.githubusercontent.com/assets/2680980/14204965/bacc10ae-f7bc-11e5-962b-4012f4d0b8cb.png">

**Comment by rgbkrk** [comment]
@willingc you'll need to be on node 5, at least for building/installing, which apparently we nested much further in the README after saying "you need node": https://github.com/nteract/nteract#install

**Comment by rgbkrk** [comment]
Closing since the github user has disappeared and this is more of a support/help question.
