### ISSUE TITLE
φ and ϕ interchanged

### ISSUE THREAD

**Issue by fbruetting** [nteract/archived-desktop-app#2566]
Whenever I type or paste φ, I see a ϕ in Nteract, and vice-versa. Would you please correct this?

**Comment by rgbkrk** [comment]
The font looks distinctly different to me:

<img width="143" alt="screen shot 2018-03-04 at 1 00 46 pm" src="https://user-images.githubusercontent.com/836375/36950531-174d2f66-1fac-11e8-9558-9db95dda8acd.png">

However, it looks like Python treats these as the same character:

<img width="1426" alt="screen shot 2018-03-04 at 12 59 37 pm" src="https://user-images.githubusercontent.com/836375/36950528-0c1ada58-1fac-11e8-96fe-3f986a4299c6.png">

It's the same behavior for me in both Jupyter and nteract. What happens in your version of Jupyter and IPython (+ Python)?
