### ISSUE TITLE
Allow specifying the name of the root node in _repr_json_

### ISSUE THREAD

**Issue by ivanov** [nteract/archived-desktop-app#2580]
@dhirschfeld reported this on ipython/ipython#11015, but the screenshot looks like nteract, so I'm refiling it here, and re-quoting the original report below:

------

The example given in ipython/ipython#6710 does seem to work for me!
```python
class Foo(object):
    def _repr_json_(self):
        return {"foo": 3, "bar": 4}, {'expanded': True}

foo = Foo()
foo
```
![image](https://user-images.githubusercontent.com/881019/36358976-1e3ab928-1562-11e8-929d-49733d3fb2c2.png)

However, rather than having the root node always labeled `root` I'd like to be able to specify the name. In particular I would like the root node to be named `self.__class__.__name__`

Ideally, you would be able to pass in the name of the root node as part of the metadata but it seems the only metadata it understands currently is `expanded`

**Comment by dhirschfeld** [comment]
I'm not sure if this is more properly a jupyterlab issue (https://github.com/jupyterlab/jupyterlab/tree/master/packages/json-extension)
or if it's something both projects will have to solve independently.

**Comment by dhirschfeld** [comment]
To be clear, the api I'd like would be to allow specifying the root name in the metadata - e.g.
![image](https://user-images.githubusercontent.com/881019/36573901-bb4a4808-188e-11e8-90c8-93c6d2b3f66b.png)

**Comment by rgbkrk** [comment]
I'm fine with agreeing on the `root` metadata key (or even `rootName`). Originally @gnestor forked the json transform package from here for JupyterLab, so it's roughly the same implementation.

**Comment by dhirschfeld** [comment]
@rgbkrk - since I accepted your invite to the nteract organisation I feel I ought to contribute so might give this a crack! Any pointers/advice on where to look / how to tackle it would be greatly appreciated...

**Comment by dhirschfeld** [comment]
Note to self - looks like I'd have to edit:
https://github.com/nteract/nteract/blob/master/packages/transforms/src/json.js
...which uses:
https://github.com/alexkuz/react-json-tree

**Comment by gnestor** [comment]
react-json-tree has the [`hideRoot` prop](https://github.com/alexkuz/react-json-tree#more-options) which will hide the "root" label.

Additionally, you can try passing a [`keyPath` prop](https://github.com/alexkuz/react-json-tree/blob/65b5c51dc0c8d6083ee6517c3817976e78cd843e/src/index.js#L98) with a custom name to see if that works...

**Comment by dhirschfeld** [comment]
Ok, ok, ok - it's on my TODO list! It's just a long list...

**Comment by rgbkrk** [comment]
We're now hiding root, does it seem like we can close this one?

![screen shot 2018-09-03 at 9 08 23 pm](https://user-images.githubusercontent.com/836375/45009546-8b90c300-afbd-11e8-97e4-4edde9e60f30.png)
