### ISSUE TITLE
SIGTTIN error while forking nteract app

### ISSUE THREAD

**Issue by szymonmaszke** [nteract/archived-desktop-app#2582]
- **OS**: Arch Linux
- **Behaviour**: Crashes nteract and parent process
- **Why**: Detached nteract tries to read input from terminal (why would it do that? Jupyter notebook starts normally using procedure described below)

- **Required to replicate**: Neovim, AUR package (https://aur.archlinux.org/packages/nteract-bin/)

**How to reproduce**: start neovim and type in:

```vim
:call jobstart('nteract')
```

**Results**: Neovim crashes, shell returns SIGTTIN, nteract fails to start.

**Some additional informations**:
- terminal: Termite
- using tmux?: yes, true color support

**Comment by rgbkrk** [comment]
Oh interesting. Thanks for reporting. I don't know what's reading from stdin.

**Comment by szymonmaszke** [comment]
Is there any chance for fixing this issue? I wanted to incorporate your app into my plugin but this bug is blocking me.

BTW. Sometimes this bug does not appear, but I can see no underlying cause as the command stays the same.

**Comment by rgbkrk** [comment]
I'm sure we can figure it out together.

Curiosity -- what's your plugin for?

**Comment by szymonmaszke** [comment]
Vim/Neovim integration with notebooks. Basics are ready but it would be nice to have support for your app before first release.

**Comment by rgbkrk** [comment]
Re-opening as I think this is still good to go after -- we still need a great command line interface for nteract. Nothing is being invested in this area at the moment and we need help. 😄
