### ISSUE TITLE
Using nteract kernels with virtualenv/pyenv without global package install

### ISSUE THREAD

**Issue by hydrosquall** [nteract/archived-desktop-app#2586]
Hi Team,

Thanks for the great work on this application! Writing with a basic question about how to get a python kernel, as I currently only have the node.js kernel.

I've been using `jupyter` notebooks for a while, I only keep the library installed in a virtual environment via `pyenv`. I have separate environments for python2 and python3. I tried launching `nteract` from the CLI inside my python3 virtualenv (which has `ipykernel` in it), but still only found the node.js kernel.

I did a search in the issues page for mentions of `pyenv` and the closest related issue was https://github.com/nteract/nteract/issues/1321 , but I'm not sure how much of it carries over since I don't use `conda`. 

Does anyone know if there's a way to set up nteract to access python kernels without needing to install `ipykernel` to my global python package space (i.e. outside a pyenv virtualenv)?

**Comment by hydrosquall** [comment]
**Update**

This can probably be closed as I found the snippet @rgbkrk provided below:

https://github.com/nteract/nteract/issues/1041

However, perhaps this could be a snippet worth adding to the `README.md` or some installation page.

**Comment by akiross** [comment]
This snippet, without naming options, is currently available on the website kernel page: https://nteract.io/kernels
