### ISSUE TITLE
Error importing npm modules to a notebook

### ISSUE THREAD

**Issue by lihai-benhaim** [nteract/archived-desktop-app#2590]
most of the time im using runkit.com as a playground for Javascript but as it cloud based and doesnt work offline obviously I have installed nteract to create some standalone scripts.
I have noticed that only NodeJs native modules are supported (like fs, path etc..) but when trying to run this code:
```
var _ = require('lodash');
```
I get an error: 
```
Error: Cannot find module 'lodash'
```
In runkit it automatically loads the latest version of the library, without any preparation.
Should nteract work the same? how can i play with 3rd party libraries in nodejs?

**Comment by rgbkrk** [comment]
The current built in node.js runtime is [ijavascript](https://github.com/n-riesco/ijavascript) which operates in a similar fashion to node scripts -- it resolves based on local `node_modules`. You have to `npm install` dependencies "next to" your notebook files.

**Comment by loretoparisi** [comment]
@rgbkrk Hello Kyle, I did as you suggested:

```
ip-192-168-1-104:jupyter loretoparisi$ ls -l
total 32
-rw-r--r--@  1 loretoparisi  staff   960 18 Lug 20:38 HelloWorldNodeNteract.ipynb
drwxr-xr-x  13 loretoparisi  staff   416 18 Lug 20:43 node_modules
-rw-r--r--   1 loretoparisi  staff  6755 18 Lug 20:43 package-lock.json
-rw-r--r--   1 loretoparisi  staff   329 18 Lug 20:42 package.json
```

and I have restarted the kernel. then I get an error of module not found. What is wrong?

Thank you!

**Comment by rgbkrk** [comment]
Can you try to run `open HelloWorldNodeNteract.ipynb`, seeing if it works in a fresh session? It would be good to print out what the current working directory is too. Is this with the built in node kernel or a separately installed one?
