### ISSUE TITLE
Remove flow guards when KernelRefs are guaranteed.

### ISSUE THREAD

**Issue by theengineear** [nteract/archived-desktop-app#2608]
Just creating an issue to tag as I go through a current refactor. The cleanup for the PR I'm working on will require us to remove a lot of guards that need to check if an action does indeed have a `payload.ref`.

The goal is for me to reference this issue in the code like `TODO: #XYZ`

**Comment by theengineear** [comment]
@rgbkrk I tagged the code with something like `TODO: #2608`, since you're taking this on in #2616, you might find it useful to search for in the codebase.

**Comment by rgbkrk** [comment]
Thanks for making this issue and leaving comments for it to make it really easy to do a clean sweep + close this issue. 🙇
