### ISSUE TITLE
Tutorial for using styleguidist to prototype new components

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#2624]
In #2623 @rgbkrk mentioned that to work on the dashboard view he was working inside showcase to do the prototyping:

> Since showcase is now really nice for prototyping components, I've started it in there. I'll move it into core once ready.

It would be nice if there was a tutorial with a full workflow explaining how to prototype components in showcase. This would make it easier for developers less familiar with the nteract codebase to begin contributing new components to the project. 

However, as I pointed out(https://github.com/nteract/nteract/pull/2623#issuecomment-370067044), there isn't an obvious location in the monorepo to place that tutorial (there is the `doc/` folder, but all it has in it is a design document). Most of the current documention is in individual files at the top level of the repo. So, it may be necessary to think about documentation more broadly for this to really be feasible.

**Comment by mpacer** [comment]
in talking with @rgbkrk on slack I thought of a few things that might be useful to cover

- “In which directory do I need to create a new file? ”
- “What libraries will I need (e.g., React), how do I import them?” 
- “Where do I need to add an object with what structure to be able to get anything at all on the page?”
- “How do I start up the nextjs server to definitely show this prototype?” 
- “How do I know where I should be adding things into the page? Is there a good place to start adding things?” 
- “How do I figure out what data to fake (in what structure?) in order to show the prototype?”
- “Do I need to make this something that can be hooked up to redux to get actual data?”

**Comment by rgbkrk** [comment]
We've since deleted showcase. However the questions above still apply to the docs, which are run with:

```
yarn docs
```

**Comment by rgbkrk** [comment]
The main documentation for style guidist I usually point folks to: https://react-styleguidist.js.org/docs/documenting.html

**Comment by willingc** [comment]
Closing since there is now much more documentation on components.
