### ISSUE TITLE
Need "Open recent" menu.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#263]
Dont' work yet apparenlty:

https://github.com/atom/electron/issues/4028

**Comment by rgbkrk** [comment]
~~Ah, we should take it out of our menu, based on that issue.~~ (not even there).

**Comment by rgbkrk** [comment]
I'm going to go ahead and close this since there is no way for us to handle this in a nice cross platform way until Electron supports it. Re-open if/when it seems feasible.

**Comment by Jaykul** [comment]
Since VS Code is doing it, presumably we could copy whatever they're doing?

**Comment by rgbkrk** [comment]
Seems like a wise idea. It wouldn't be so bad for us to maintain our own LRU cache on disk.

**Comment by maedoc** [comment]
Even just using last notebook's directory for the Open File dialog would be handy, to avoid navigating same path in filesystem over and over. (might be a separate issue)

**Comment by izaid** [comment]
+1 to this please

**Comment by rgbkrk** [comment]
I'm going to pin this one since more than one person has weighed in over time as a major requested feature. Thanks all!

**Comment by lgeiger** [comment]
This is now supported on macos and Windows by Electron itself: https://electronjs.org/docs/tutorial/recent-documents

**Comment by captainsafia** [comment]
This is supported on both Mac and Windows now.

On Windows, users need to be sure that nteract is set as the default program for .ipynb file types via the Default Apps settings page on Windows. Then Windows will populate the jump list accordingly.
