### ISSUE TITLE
WebApp  Question

### ISSUE THREAD

**Issue by bobbych** [nteract/archived-desktop-app#2633]
is there a way to use `nteract` as `webapp`? I have read through documentation and issues but its not very clear to me.

Thanks

**Comment by betatim** [comment]
Work on nteract as webapp is [nteract-on-next](https://github.com/nteract/nteract/tree/master/applications/notebook-on-next). There is still a lot of work to be done though.

**Comment by rgbkrk** [comment]
Howdy! There's also a jupyter extension in the works, it's not ready for wide consumption yet. We'll be pushing out a new (alpha) release tomorrow as well as a wider beta in the coming weeks. You can try an old version out on binder via the example notebook(s) here: https://github.com/nteract/vdom/tree/master/example-notebooks#example-notebooks

Let me know if you'd like to contribute, I'm happy to facilitate others to join our team. 😄

**Comment by bobbych** [comment]
@betatim , @rgbkrk Thank you for your responses, i am looking forward to trying out jupyter extension. I am glad to know that you are open for contribution, I will get back to you on that, in mean time i will start playing around, so far desktop app is awesome!

**Comment by rgbkrk** [comment]
We've released a beta of the jupyter extension and are about to come out with another release of the beta super soon!
