### ISSUE TITLE
[commuter] allow filtering cells that are displayed by tags or metadata

### ISSUE THREAD

**Issue by yuvipanda** [nteract/archived-desktop-app#2641]
I was talking to @labarba and Migual (unsure what their github handle is) about a potential use case for Commuter!

In MOOC platforms like EdX, it would be great if we can embed sections of notebooks inside iframes. This would require ability to render sections of notebooks identified by some criteria. Simplest I think is tags, so if commuter can accept params on tags to show and filter by those, that'd be great way to do this!

I'm not sure if commuter does any framebusting, but if it does making that configurable would also be great.

**Comment by labarba** [comment]
cc. @mamigot

**Comment by labarba** [comment]
hey, @yuvipanda — We've just announced the Jupyter Viewer XBlock. Check it out:
https://github.com/ibleducation/jupyter-viewer-xblock

(follow the link for a video demo)
