### ISSUE TITLE
Unable to Publish to User Gist

### ISSUE THREAD

**Issue by lightsquared** [nteract/archived-desktop-app#2649]
Dialog box hangs after putting in user id and password to Github.  The green button to authorize is not active.

**Comment by ManikandanKurup-Packt** [comment]
Hello, I'm facing this same problem. This is my first time using publish to gist. I'm not sure if is it a bug or if i missed something here. Here are the system details:

Operating system: Windows 10 x64
nteract version: 0.15.0

Here is the screenshot of the same:
![image](https://user-images.githubusercontent.com/48318375/71016970-e7804c00-211b-11ea-87a1-8717c33a4e1e.png)
