### ISSUE TITLE
Support execution times in notebook per nbformat v4.4

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2660]
As [stated in the spark roadmap](https://github.com/jupyter/roadmap/blob/master/spark.md#timing-data), we want to store how long it took to run a cell. The transient information for how long execution took is available in the message spec.

[JupyterLab has started adopting it with the same metadata the `execute_time` extension was using](https://github.com/jupyterlab/jupyterlab/pull/4161#issuecomment-371929527).

**Comment by captainsafia** [comment]
I'll re-open this. Although ideally, we'd want to build this out once a standard for execution times stored within cell metadata has been established.

**Comment by BenRussert** [comment]
@aviatesk is working on an execution time feature as part of some enhancements for the hydrogen kernel monitor. Anyone with a chance to look that over we could always use feedback. 

(The difference for hydrogen is we're not talking about in terms of metadata since the value don't persist anywhere, just rendered for the user.

https://github.com/nteract/hydrogen/pull/1601

**Comment by jletey** [comment]
Hello everyone!

I would love to know the progress on this, as I love using the [ExecuteTime](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/execute_time/readme.md) extension included in the [jupyter_contrib_nbextensions](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest) package.

I would also love to know if there is anything I can do to get this implemented!

**Comment by captainsafia** [comment]
Resurrecting this now that execution times are officially part of the notebook format and we can focus our effort on adding native support for execution times in format that will be respected by all clients as opposed to a per-extension basis.

I'd like to get this change in for the February 2020 release of the desktop app so we can be briskly moving forward with changes in the notebook format. I've reviewed the spec changes and created a list of tasks we'll need to complete to get this work in.

- [ ] Add logic in @nteract/immutable to parse and serialize the `execution` metadata field
- [ ] Add a `setExecutionDate` action/reducer combination that obeys the following interface

```
interface SetExecutionTime {
  type: SET_EXECUTION_TIME,
  payload: {
    channel: "shell" | "iopub",
    field: ["some", "key path"],
    datetime: Date
  }
}
}
```
- [ ] Dispatch actions from the `executeCellStream` to update the fields, we will need to add these under the `kernelStatuses` and `outputs` filters respectively

The above outlines the state related work. We may wany to provide an interface for showing this to the users by that can be handled seperately from the state-related work.
