### ISSUE TITLE
Some LaTeX environments aren't rendering properly

### ISSUE THREAD

**Issue by tlyon3** [nteract/archived-desktop-app#2677]
I noticed this specifically in the `\begin{align*}` environment. Here is the raw source that I noticed it with:

```
\begin{align*}
- x' P_i x - \rho_i  & = \max_u - \biggl[ x'R_i x + u' Q_i u + 2 u' W_i x \cr &
              \beta \sum_j \Pi_{ij}E ((A_i x + B_i u + C_i w)' P_j (A_i x + B_i u + C_i w) x + \rho_j) \biggr]
\end{align*}
```

It could be an issue with the mathjax config.

**Comment by rgbkrk** [comment]
Is that `\begin{align}` inside of a `$$` block too (not that it should)? I think we'd need the markdown package to also treat those as latex sections if that's the expectation.

Just like how you added a way to keep the block mode as is. We'd have to extend the markdown parser to detect `\begin` etc. and send to mathjax. What's the expectation for this text in the classic jupyter notebook?

![screen shot 2018-03-14 at 11 36 00 am](https://user-images.githubusercontent.com/836375/37423763-e818fe8c-277b-11e8-85b8-9f615bee41fe.png)

**Comment by tlyon3** [comment]
That set was not inside a `$$` block. As you can see, it renders if it is wrapped inside a `$$` block. 

As far as expectations in classic jupyter, they render the exact same way:

![image](https://user-images.githubusercontent.com/7951935/37424576-2baa98ca-2797-11e8-935c-74d79ce2017a.png)

We could modify the parser to find LaTeX environments, then wrap the environment block in `$$` before it gets to the math renderer. Then it should take care of itself from there.

**Comment by rgbkrk** [comment]
cc @mpacer

**Comment by ghost** [comment]
Hi, I'm commenting on this issue because I made a gatsby plugin to parse Jupyter notebooks. When using the nteract Notebook-preview component for viewing file some maths equations are not rendered correctly.

Here's the link to this preview: https://gatsby-contrib.github.io/gatsby-transformer-ipynb/Three-Body%20Problem/

And here is the original notebook in GitHub: https://github.com/pjpmarques/Julia-Modeling-the-World/blob/master/Three-Body%20Problem.ipynb

Any thoughts on the cause of this?

**Comment by rgbkrk** [comment]
Awesome. I love Gatsby!

@tlyon3 has a PR that handles the environment rendering differently -- #2691. Could you check it out?

**Comment by ghost** [comment]
Ok I'll try the PR code and give feedback here.

**Comment by ghost** [comment]
The markdown package proposed by @tlyon3 gives the same result:
![image](https://user-images.githubusercontent.com/1004282/40586203-722bed78-61bf-11e8-8abe-e849db6683ba.png)

**Comment by tlyon3** [comment]
@benjaminabel would you mind sending me the notebook you used? Or at least a notebook with those specific cells in it?

**Comment by ghost** [comment]
The notebook is on github: https://github.com/pjpmarques/Julia-Modeling-the-World/blob/master/Three-Body%20Problem.ipynb

**Comment by ghost** [comment]
Also I would like to render the notebook-preview component on the server with `ReactDOMServer.renderToStaticMarkup(element)`, but it results in an empty string because it has some code that use `document` in the mathjax package. I'd like to provide a way to use `katex` instead of mathjax  if run on server. Should I modify the mathjax package or create a new package?

**Comment by rgbkrk** [comment]
I wonder if there's a decent way for us to allow that top level Maths context API to accept an arbitrary component or render callback so it can use KaTeX or our MathJax helper.

It's totally fine if you create a new package in the monorepo for doing it with KaTeX. It seems like KaTeX development has picked back up and they now handle a lot more that was missing.

**Comment by ghost** [comment]
@rgbkrk, thanks for your answer. I'm pretty new to `lerna`, and it's not esay for me to hack on the nteract monorepo. I'm going to try to create a `@nteract/notebook-render` package that allow rendering notebooks in the server-side. I think i'm gonna handle maths directly on that package, and you'll see if it's possible to include it in the `mathjax` package.

**Comment by tlyon3** [comment]
I've tested this with my PR for environment rendering. Looking at the notebook source, the PR shouldn't affect the rendering of this notebook because 1) That block isn't in an environment and 2) it's already wrapped in a `$$` block. The PR only comes into play with environments that are not in a `$$` block.

It seems to be chopping off the left hand side of the equals sign. I'm looking into it a bit more to see what the problem is.

Because the math isn't inside an environment, I believe this is a different issue.

**Comment by tlyon3** [comment]
I've opened a new issue for this problem: https://github.com/nteract/nteract/issues/2924
