### ISSUE TITLE
Introducing Michelle Ufford

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2683]
Hey all! I want to introduce you to Michelle Ufford (@michelleufford). Michelle will be joining us to assist with project planning and communications. She's a seasoned data nerd and is also my manager at Netflix. For me personally (and generally within Netflix), Michelle has already made how we interface between our users & stakeholders at Netflix much better.

🎉 Welcome Michelle 🎉

**Comment by willingc** [comment]
Welcome Michelle :sunflower:

I'm looking forward to working with you.

**Comment by lgeiger** [comment]
Welcome to nteract 🎉

**Comment by MichelleUfford** [comment]
Thank you for the intro, @rgbkrk! And thank you @willingc & @lgeiger for the warm welcome! I'm excited to join the nteract community 🙂
