### ISSUE TITLE
Notebook Preview is not showing execution counts

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2684]
On commuter (and likely on notebook preview), execution counts aren't showing:

<img width="215" alt="screen shot 2018-03-16 at 10 01 56 am" src="https://user-images.githubusercontent.com/836375/37534112-15a08056-2901-11e8-8000-b06d87dc54cf.png">

Reported by @charsmith

**Comment by qzcool** [comment]
Is this because the kernal is not ready?

**Comment by rgbkrk** [comment]
commuter is a static only view, like nbviewer. Amusingly though, this is fixed now! There was a bit of an oversight in a previous release.
