### ISSUE TITLE
Enable HTML inside markdown on commuter

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2685]
Papermill creates little colored `<span>`:

![screen shot 2018-03-16 at 10 02 46 am](https://user-images.githubusercontent.com/836375/37534136-3303b050-2901-11e8-84a9-26ec35d1496c.png)

and they're not shown in papermill, commuter, etc. We should relax the markdown implementation to allow HTML inside (but likely disable scripting, using caja).

/cc @charsmith

**Comment by qzcool** [comment]
Labeled with `triage` because I am not sure about the difference between `Error UI/UX` and `bug: ui/ux`.

**Comment by captainsafia** [comment]
Re-opening this.

Agree that this should be deferred until security on cells has been implemented.

Is there a reason that papermill displays the information this way, @MSeal!

By the way, thank you for your work in tagging this, @qzcool!

**Comment by MSeal** [comment]
The html mixing is used to color the message so it is clear that an error occurred when loading the page. Without it the stack trace might be much lower down and off screen and it's harder to tell at a glance there is an issue without the large red text. We could likely give it a format pass for easier integration in tools, but it has worked well so far.

**Comment by captainsafia** [comment]
Gonna go ahead and close this since it is not needed and commuter is no longer in the monorepo.
