### ISSUE TITLE
What packages come preinstalled?

### ISSUE THREAD

**Issue by obeavers** [nteract/archived-desktop-app#2692]
I have no idea why this is so hard to find -- is nteract its own environment? Is it using my system's existing python installation? Which env? Will it work on a computer without python installed?

**Comment by rgbkrk** [comment]
nteract uses any jupyter kernels it can find in the standard jupyter kernelspec locations. If you're using conda, it won't pick up your environments though. You'll have to register the kernels like this:

```
python -m ipykernel install --user
```

Same thing applies to virtual environments. One way to see which kernels are installed is using `jupyter kernelspec list`.

Your issue highlights that we need to offer some transparency into what we see as kernels and point people to [docs on how to register more environments](https://nteract.io/kernels).
