### ISSUE TITLE
Add new themes

### ISSUE THREAD

**Issue by hugo-pires** [nteract/archived-desktop-app#2700]
Hello

How can I add a new theme? Using a CSS external file, for instance.

Thank you and congratulations

**Comment by rgbkrk** [comment]
We used to have many themes included then started to feel the pain of maintaining multiple themes, especially as we started changing the CSS structure. We now only support CSS variables in themes (and can introduce more).

**Comment by hugo-pires** [comment]
How can I use my "user defined" theme with CSS variables?

**Comment by rgbkrk** [comment]
There's not a way currently.

**Comment by danielgwilson** [comment]
Would be a cool feature to have user-defined and shareable themes similar to many text editors

**Comment by willingc** [comment]
I'm going to close this issue about themes. Please pass along any items that you wish to see documented in this issue for better documentation on customization and themes: https://github.com/nteract/docs/issues/46

Thanks :sunny:
