### ISSUE TITLE
Windows App cannot identify the iPython kernal

### ISSUE THREAD

**Issue by qzcool** [nteract/archived-desktop-app#2704]
How can I install the Python 3 kernal?

Is this because I installed nteract and Anaconda on different disks?

**Comment by rgbkrk** [comment]
You'll have to run the `ipykernel` install step like documented here: https://nteract.io/kernels/python

**Comment by qzcool** [comment]
Thank you so much, problem solved! Can we automate this for absolute beginners? :)

**Comment by rgbkrk** [comment]
I wish we could automate it. The only hope we have of automating it in a reasonable way is to bundle a python kernel with our app, because then we don't have to mess with people's systems.

**Comment by qzcool** [comment]
Considering the large group of Python users, it might be reasonable for this integration. Oh, god! I just noticed you are the main creator of nteract. Thank you, Kyle! I really enjoy nteract and I am developing a course to introduce nteract to Chinese users.

**Comment by rgbkrk** [comment]
> I really enjoy nteract and I am developing a course to introduce nteract to Chinese users.

That is super exciting! Hopefully we'll be able to make it better and better.
