### ISSUE TITLE
[jext] Automatically reconnect on websocket disconnect

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2720]
This is twofold:

* If the websocket gets disconnected for any reason, we should reconnect (assuming it wasn't because we asked the kernel to be killed)
* Evaluate if we're still connected to the server by polling an endpoint on the notebook server. We can provide an `/api/ping` as necessary

**Comment by captainsafia** [comment]
Re-opening.

This is relevant not only in Jext, but other contexts where our front-end components are used to connect to back-end compute.
