### ISSUE TITLE
Desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [nteract/archived-desktop-app#2738]
Desktop file does not pass `desktop-file-validate` on Ubuntu 14.04 LTS, saying `
nteract.desktop: error: value "application/x-ipynb+json" for string list key "MimeType" in group "Desktop Entry" does not have a semicolon (';') as trailing character
`

This currently prevents it from being listed in [AppImageHub](https://appimage.github.io/apps/).

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/361720274#L589

**Comment by willingc** [comment]
Closing this issue, related to 0.8.4, as it's been inactive for several months. Please feel free to request that we reopen this issue if you are still seeing this on release 0.12.3. Thanks! 🌻
