### ISSUE TITLE
Compatibility with pyecharts

### ISSUE THREAD

**Issue by yihengli** [nteract/archived-desktop-app#2743]
Pyecharts is a beautiful visualization tool that is somewhere similar to Plotly with a lot of powerful interactive javascript based charts. It's working well with Jupyter notebook and any modern browsers. 

More information could be found here https://github.com/pyecharts/pyecharts

However, on nterect, the visualization output is broken with following messages:

### Error
```
Uncaught TypeError: require.config is not a function
    at <anonymous>:2:13
    at t.value (app.js:1)
    at commitLifeCycles (app.js:1)
    at t (app.js:1)
    at w (app.js:1)
    at x (app.js:1)
    at m (app.js:1)
    at h (app.js:1)
    at Object.enqueueSetState (app.js:1)
    at a.m.setState (app.js:1)
assert.js:60 

Uncaught AssertionError: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
    at <anonymous>:2:5
    at t.value (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:6323640)
    at commitLifeCycles (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:1406159)
    at t (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:1392657)
    at w (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:1398104)
    at x (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:1397805)
    at m (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:1396937)
    at h (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1:1396341)
```

### Expected Output
On Jupyter (Chrome) and downloaded HTML
<img width="760" alt="screen shot 2018-04-04 at 12 32 49 pm" src="https://user-images.githubusercontent.com/13440386/38330017-52d06b8c-3804-11e8-8eff-6e82923e0093.png">

### Actual Output
On nteract
<img width="819" alt="screen shot 2018-04-04 at 12 33 22 pm" src="https://user-images.githubusercontent.com/13440386/38330048-690d025c-3804-11e8-93f8-049a61a87697.png">

Would like to know why this error triggered and how to fix it.

### Env
nteract: 0.8.4
system: mac 10.13.4
python: 3.6.2
pyechart: latest

**Comment by rgbkrk** [comment]
pyechart will need to switch to detecting if `requirejs` is available. Both nteract and jupyterlab don't support the old requirejs setup that the classic notebook used.

xref: https://github.com/pyecharts/pyecharts/issues/351

**Comment by chfw** [comment]
first of all, nice to know an alternative tooling exists after juyperlab. I managed to hack it and get it working:

![screen shot 2018-05-02 at 00 04 38](https://user-images.githubusercontent.com/4280312/39497701-75f2de26-4d9c-11e8-8687-6bb9337c57d6.png)

Please stay tuned from pyecharts further. Here are the question marks in my head:

1) does nteract support jupyter notebook extension? in which, we can install static javascript packages on local file system. [jupyter-echarts-pypkg](https://github.com/pyecharts/jupyter-echarts-pypkg) is an example. If not, it is not a big deal but it means no internet connection, no pyecharts in nteract: imagine you sit with your big data science project on infamous UK trains, where wifi/4G is laughable.

2) Continue with no answer, what are the native(javascript) way of contributing extensions to nteract.

**Comment by rgbkrk** [comment]
We don't support the classic jupyter notebook extensions and don't really have a paved path for including them.

My answer is a little bit different depending on if we're using the desktop app or the jupyter extension. With the jupyter server we can load arbitrary files that get served from `/static` or any other extension (assuming they're not requirejs based). Is the main dependency that `echarts` js lib?

**Comment by chfw** [comment]
javascript assets of pyecharts can be included without require.js. It is jupyter notebook which uses requirejs hence we altered our implementation to suit jupyter notebook. We are NOT married with requirejs.

I am interested in the way to place files in `/static` folder. To serve nteract desktop app user, how can I or your user get our files there? When nteract becomes jupyter extension,  does it mean that pyecharts packages can be installed to jupyter echarts in conventional way? And to display it, we in pyecharts team can remove requirejs in rendered result. 

Is there any flag to show that the script is ran in nteract environment? With jupyter, _repr_html_() is the unique signature. What about nteract?

Here are all js files(around 3,000 files) ever used in pyecharts:

https://github.com/pyecharts/assets

Yes, we do not force our user to take all files in one go. There are [separated in different packages](https://github.com/pyecharts/pyecharts/blob/master/images/map-extension-architecture.png). Just like python user could choose libraries they use, pyecharts user can do the same too.

**Comment by rgbkrk** [comment]
nteract responds to the same payloads that come from `_repr_html_`.

One thing we started adopting a few years ago (and jupyterlab eventually brought in) was custom payloads, particularly where there is a specific schema between a JS library and what the python side would send. We do this for vega, plotly, and others by allowing them to send their own data type + mimetype. For Plotly, they wrote a [versioned schema](https://help.plot.ly/json-chart-schema/) that we happily [send on to their JS library](https://github.com/nteract/nteract/blob/master/packages/transform-plotly/src/index.js#L39). In order to do this though, we bake in access to these visualization libraries as part of our shipped app. So long as pyecharts has their own schema that would be adhered to as well as maintenance work on supporting the React component that wraps it, then we can incorporate it. We don't have a dynamic way for users to add on new libraries in nteract yet.

**Comment by rgbkrk** [comment]
In summary, your method of pulling the JS from CDN is likely the only solution for _today_. Long term we'd have to do development work as mentioned above.

**Comment by chfw** [comment]
pyecharts 0.5.5, the next release will support nteract initially. Permanent solution down the line will be sought after.

Please call `enable_nteract()` before you draw anything, you will be fine. You may have problem with maps but the current solution is to use latter method in this text.

<img width="957" alt="screen shot 2018-05-16 at 22 56 49" src="https://user-images.githubusercontent.com/4280312/40146181-75652024-595c-11e8-9a63-44fcfb8959c2.png">

But when rendering as image, there is no difference with jupyter notebook. And it draws maps without any problems:

<img width="953" alt="screen shot 2018-05-17 at 10 06 43" src="https://user-images.githubusercontent.com/4280312/40167928-305385bc-59ba-11e8-9a23-56b5970f1a41.png">

More guidelines, please refer to [pyecharts documentation](http://pyecharts.org/#/zh-cn/jupyter_notebook).

**Comment by chfw** [comment]
@yihengli , pyecharts 0.5.5 is released.
