### ISSUE TITLE
Move comms state + reducers into core.entities

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2749]
Since comms has unique IDs and each entry is really associated with only one notebook document, we might as well move them up to entities.

**Comment by captainsafia** [comment]
Ruh-oh. Would've been good to do this when we moved `reducers` out of core. Ah well.

**Comment by Abhi58** [comment]
Hi @captainsafia . Please assign this issue to me. I will work on it. Thanks!

**Comment by captainsafia** [comment]
Sure! Feel free to post any questions about this issue here.

**Comment by Abhi58** [comment]
Hi @captainsafia. Sorry, I was busy with school work. So, couldn't update sooner. . I have worked with typescript in Angular before but haven't worked with react or redux. So, currently i am going through the resource links in the contribution guidelines. Will start working on the issue by today or tomorrow.

**Comment by Abhi58** [comment]
@captainsafia Also the comms state that needs to be moved is that the comms.ts file under the reducers directory? If that's the file i don't find the entities file under core directory.

**Comment by captainsafia** [comment]
> Hi @captainsafia. Sorry, I was busy with school work. So, couldn't update sooner. . I have worked with typescript in Angular before but haven't worked with react or redux. So, currently i am going through the resource links in the contribution guidelines. Will start working on the issue by today or tomorrow.

Sure. Take your time and feel free to post questions here.

> @captainsafia Also the comms state that needs to be moved is that the comms.ts file under the reducers directory? If that's the file i don't find the entities file under core directory.

Yes, the comms.ts file is the one that needs to be moved. 

The entities directory can be found [here](https://github.com/nteract/nteract/tree/e8b1b406bca584a0b0b79957aa1614f1299d5cd2/packages/reducers/src/core/entities). This directory is the new place where the `comms.ts` file will live.

We'll also have to update where the comms reducer is registered in the state [in this file](https://github.com/nteract/nteract/blob/master/packages/reducers/src/core/entities/index.ts).

**Comment by Abhi58** [comment]
Okay. Thanks a lot.

**Comment by Abhi58** [comment]
Hi @captainsafia . I have moved the comms.ts file to entities directory. 

I was going through other files in the directory to see if any changes need to be done in the comms file. What i saw was in all other files a reducer type object has been created to combine the methods of a particluar file.

**Comment by Abhi58** [comment]
And these objects are imported in the index.ts file in the core directory.

**Comment by Abhi58** [comment]
Whereas in the comms.ts file, a default function of CommsRecord class type is used to return state based on action type. I tried creating a reducer object for comms file by trying to import the methods in the file,but was getting errors. Can you please help me with this! Thanks!

**Comment by captainsafia** [comment]
@Abhi58 Sure! Can you open a work-in-progress PR so I can provide feedback on the code you've written this far and we can fix things up there?

**Comment by Abhi58** [comment]
Sure @captainsafia . I will create a work in progress PR. sorry for the delay in response. Thanks!
