### ISSUE TITLE
Create a base layer for jupyter extensions

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2758]
Now that we're about to have n ≥ 2 jupyter extensions, I'd love for common layers to be shared amongst these. If at all possible, I'd prefer they to be Python packages that are part of the monorepo. Bonus points if our lerna bootstrap will also do the python linking for us too. 😄 

/cc @yuvipanda

**Comment by yuvipanda** [comment]
we don't have 2 jupyter extensions anymore :D

**Comment by rgbkrk** [comment]
Nice, time to close this!
