### ISSUE TITLE
Fix Slack Inviter

### ISSUE THREAD

**Issue by tantrev** [nteract/archived-desktop-app#2786]
Right now navigating to https://slackin-nteract.now.sh results in the following error:

`402 | Payment Required`

Any help would be more than appreciated.  Thank you.

**Comment by rgbkrk** [comment]
Wow. Thanks for noting. That one was still running on my personal account.

https://slack.nteract.io/ should work, I'll fix that one up and also fix the links to the slacks.

**Comment by rgbkrk** [comment]
Thank you so much for reporting this. I've switched this over to the paid nteract account and was able to clean this out of my personal account (which got switched to a free plan, causing this problem)
