### ISSUE TITLE
Cell Protection from Wrongful Deletion

### ISSUE THREAD

**Issue by qzcool** [nteract/archived-desktop-app#2790]
Given nteract has not provided the un-do function for cell deletion, for very important code cell, wrongful deletion is such a big problem.

It would be great if we can provide cell protection function to allow users to determine which cell they want to protect from deletion unless unprotected.

**Comment by rgbkrk** [comment]
Thanks for raising this up as a potential option. Locking cells could be possible. 🤔

**Comment by willingc** [comment]
Closing this issue and tracking it in #1038
