### ISSUE TITLE
Title of document needs to be editable

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2809]
![screen shot 2018-04-28 at 9 15 25 pm](https://user-images.githubusercontent.com/836375/39403209-fa00cca2-4b29-11e8-9217-1026703ba84f.png)

Can't click to edit it. 😏

**Comment by yuvipanda** [comment]
Once #2846 lands, this should also update the <title> tag when the page title is changed. Perhaps change the URL too?

**Comment by rgbkrk** [comment]
Definitely.
