### ISSUE TITLE
[Data Explorer] Table view doesn't work after choosing a chart view

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2860]
On the [binder preview](https://t.co/xVK5uV0i6T), when doing the initial render you see the table view but after selecting any of the chart views clicking on the table view again does nothing and I see the below error in the JS Concole:

![image](https://user-images.githubusercontent.com/881019/39846342-74c7afd8-543e-11e8-8728-abea03c0dd0a.png)

**Comment by jdetle** [comment]
Thanks dave, it looks like there are no semiotic settings for the grid view.
