### ISSUE TITLE
Better python package building 

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#2864]
- [ ] check that local git repo is up to date with upstream 
- [ ] ensure everything is installed from root
- [ ] ensure that the python package includes the built assets from webpack
- [ ] ensure that webpack has been built in prod mode
    - [ ] one approach: write out a file to disk only when in prod mode, include git hash, remove that file if built in any other way

Bonus:
- [ ] simplify command for actually building

cc: @rgbkrk

**Comment by captainsafia** [comment]
This still needs to be done so I'll re-open. I tag it as a chore/ops work.
