### ISSUE TITLE
[DISCUSS] Hitting play button doesn't focus next cell 

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#288]
Should the next cell be focused on run by play button?

![runbybutton](https://cloud.githubusercontent.com/assets/836375/14120856/8c15fdde-f5a9-11e5-939c-e7eedf91969e.gif)

**Comment by jdfreder** [comment]
I think the play button should run in place as is.  I've always disliked mouse click induce scrolling

**Comment by ivanov** [comment]
I'm also :+1: on run in place and not focus the next cell/

A cell like this would lend nicely to being replayed in place multiple
times.

```
i+=1
plot_foo(x[i])
```

Focusing next cell would only work if you could move the mouse cursor to
the play button for that cell (Acme does this to great effect), but I don't
think there's a way to do that under X11, Os X or Windows.

**Comment by rgbkrk** [comment]
My opinion is as the same as above, that it runs in place and doesn't focus the next cell. I'll go ahead and close this since the opinions were uniform. If anyone ever wants a different behavior they can open a new issue or re-open this one.
