### ISSUE TITLE
New notebooks do not load kernel until kernel is selected from 'Runtime' menu

### ISSUE THREAD

**Issue by jdpigeon** [nteract/archived-desktop-app#2885]
Just noticed this when running the Linux alpha on a fresh install of Ubuntu 18.04 with Node v10 installed.

When opening a new notebook in the desktop app, code cells do not produce output and bottom bar indicates 'loading..' indefinitely.

However, I am able to get the kernel connected and continue working normally by manually selecting the Node.js kernel from the 'Runtime' menu

**Comment by fonnesbeck** [comment]
Perhaps related to this, if I specify a kernel as an argument, e.g.:

    nteract -k dev

the `dev` kernel does not load, as evidenced by import statements for libraries installed in that kernel failing. However, when I select `dev` from the dropdown menu, it loads.
