### ISSUE TITLE
Font setting

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#2902]
nteract is a beautiful desktop application for running Jupyter notebooks. However I would like to know how to edit it for setting custom themes. I want to set custom syntax colouring, font (say Menlo) and 
Lucida Grande (for Markdown).

thank you

**Comment by willingc** [comment]
Thanks @imadhusudan. I have opened a documentation issue https://github.com/nteract/docs/issues/46 to better improve our docs on customization.
