### ISSUE TITLE
'Can't resolve styled-jsx/style` when adding notebook-app-component to Electron project

### ISSUE THREAD

**Issue by jdpigeon** [nteract/archived-desktop-app#2905]
I'm trying to add just the `notebook-app-component` to my project (along with `@nteract-core`) and running into this error:
`Module not found: Error: Can't resolve 'styled-jsx/style' in '/home/dano/nteract-react-boilerplate/node_modules/@nteract/notebook-app-component/lib`

I've tried adding the package as both a dev dependency and normal dependency. Have tried cleaning the node_modules folder and reinstalling a bunch, but can't seem to get to the bottom of this.

It looks like `styled-jsx` might have some Webpack configuration needs. Is this Webpack related?

**Comment by jdpigeon** [comment]
When `styled-jsx` is added on it's own:
`Module not found: Error: Can't resolve 'styled-jsx' in '/home/dano/nteract-react-boilerplate'`

**Comment by jdpigeon** [comment]
Adding `styled-jsx` as a dev dependency and adding
```
"plugins": [
    "styled-jsx/babel"
  ]
```
To my .babelrc seems to fix this issue

**Comment by rgbkrk** [comment]
Ah... I see why here. I included `styled-jsx` as a peerDependency for that component (mostly so we can rely on having the same copy used by all components): https://github.com/nteract/nteract/blob/e3903d5f164ae202499641b924cbc051e45b3280/packages/notebook-app-component/package.json

We could make that a direct dependency. I'm not sure if the babel config would still have to be there unless you're also using styled-jsx inside your app.
