### ISSUE TITLE
Install grumpy about eslint

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#291]
I uninstalled and reinstalled node and npm.

I'm still getting this warning: 
<img width="643" alt="screen shot 2016-04-01 at 8 16 16 am" src="https://cloud.githubusercontent.com/assets/2680980/14211302/19307e26-f7e2-11e5-8767-6847bac653a2.png">

If I ignore the warning:
<img width="1115" alt="screen shot 2016-04-01 at 8 10 18 am" src="https://cloud.githubusercontent.com/assets/2680980/14211264/e376af1c-f7e1-11e5-981e-af546a8c3df7.png">

<img width="480" alt="screen shot 2016-04-01 at 8 09 34 am" src="https://cloud.githubusercontent.com/assets/2680980/14211312/29ee60fc-f7e2-11e5-8cdb-efa66d834598.png">

Installation is a :tada:

**Comment by kenwheeler** [comment]
Interesting. We don't have stage-0 explicitly defined in `.babelrc`. Are you on NPM 2 by chance?

**Comment by willingc** [comment]
npm 3.8.3

**Comment by rgbkrk** [comment]
I wonder if a prior failed build didn't run through the rest, maybe a new `npm install` after deleting `node_modules`?

(Sorry this is being painful)

> We don't have stage-0 explicitly defined in .babelrc

This seems like a dependency from electron-compile (which includes a bunch of defaults)

**Comment by willingc** [comment]
Victory!
<img width="801" alt="screen shot 2016-04-03 at 7 57 22 pm" src="https://cloud.githubusercontent.com/assets/2680980/14237277/77593d6c-f9d6-11e5-9a74-cfe995c28558.png">

@rgbkrk :runner: Very snappy and fast.

Still the `npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.` warning but meh.

**Comment by rgbkrk** [comment]
Woohoo! Yay. We'll get the eslint bits sorted out. Now that my brain is thinking clearly, it's because we bumped our version of eslint to 3.x. We likely need a bump of babel-eslint as well. I'll tackle that now.
