### ISSUE TITLE
Cell menu actions

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#294]
More for us to complete:

Contextual toolbar on the cell:
- [x] Split cell - allow the user to split the cell in two where the cursor is (right click menu?)
- [x] Change cell type (likely for the cell toolbar menu)
- [x] Collapse outputs on a cell
- [x] Collapse inputs on a cell

In between cells:
- [x] Merge cells #314 

Any others?

**Comment by rgbkrk** [comment]
All the cell ops from the jupyter notebook:

![screenshot 2016-04-21 09 07 05](https://cloud.githubusercontent.com/assets/836375/14711944/e6fe2592-07a0-11e6-9761-81651a111728.png)
![screenshot 2016-04-21 09 07 13](https://cloud.githubusercontent.com/assets/836375/14711946/e701533e-07a0-11e6-9865-8cf6713ba31a.png)
![screenshot 2016-04-21 09 07 21](https://cloud.githubusercontent.com/assets/836375/14711945/e7002f90-07a0-11e6-8c6e-3a5f8f13927f.png)

**Comment by rgbkrk** [comment]
Some of the Jupyter ones will collapse into common actions:
- Copy pasta will be the native buffer, not a separate cell menu action
- Merge cell is already folded into one action (since it lies between cells)
- Insert cell is also folded into one action (since it lies between cells)

The experience for run could be simplified. We should probably add some of the Run commands to the native menu. Run cell is already on the cell.

**Comment by Carreau** [comment]
What's the plan to attach keyboard shortcuts to that ?
Fight codemirror, or actually use Codemirror Keymaps ?

**Comment by rgbkrk** [comment]
If you're in favor of codemirror keymaps, I'm certainly open to it. Jon experimented with the atom keymap module (which was a pure node module) and it was very nice as a top level module for electron. Deep down into codemirror I have no idea.

**Comment by rgbkrk** [comment]
Looks like these got finished off by @captainsafia and @betatim! :tada:
