### ISSUE TITLE
dangling kernels?

### ISSUE THREAD

**Issue by SkyLeach** [nteract/archived-desktop-app#2941]
I'm not 💯 sure I haven't missed something, but it looks like nteract may be leaving kernels laying around after closing...

```
abuser         14997   0.0  0.0  2500316   7736   ??  S    Wed10AM   0:00.85 python -m ipykernel_launcher -f /Users/magregor/Library/Jupyter/runtime/kernel-0d844686-e8be-4aa0-b57a-3a2afbaea90c.json
abuser         49306   0.0  0.0  2451236   1996 s000  S+    4:15PM   0:00.00 grep --color -i python
abuser         47794   0.0  0.4  2532712  70012   ??  S     4:10PM   0:01.21 python -m ipykernel_launcher -f /Users/magregor/Library/Jupyter/runtime/kernel-9e4f78bb-53fb-4d1c-9d10-45e93db6209a.json
abuser         39931   0.0  0.4  2529868  69232   ??  S     3:43PM   0:01.42 python -m ipykernel_launcher -f /Users/magregor/Library/Jupyter/runtime/kernel-47fe1bd4-8186-4183-a824-e04bbc5aa73c.json
abuser         56292   0.0  0.1  2500316   9716   ??  S    11:14AM   0:00.84 python -m ipykernel_launcher -f /Users/magregor/Library/Jupyter/runtime/kernel-a0d09841-c4ac-4b98-8efd-21f44afa224a.json

```

**Comment by jdpigeon** [comment]
I think I'm running into this too. Working out of nteract notebooks and it seems like I've got a couple ghosts running that mess up some of my data streaming scripts

**Comment by rgbkrk** [comment]
Cleaning up the kernels definitely needs better handling in the main process.

I wonder though... in the meantime if it would be quicker for us to switch [`spawnteract`](https://github.com/nteract/spawnteract)'s `child_process` usage to [`execa`](https://github.com/sindresorhus/execa#cleanup) as it [cleans up spawned processes when the parent process dies](https://github.com/sindresorhus/execa#cleanup).

**Comment by jdpigeon** [comment]
That looks awesome!

**Comment by BenRussert** [comment]
> switch spawnteract's child_process usage to execa as it cleans up spawned processes when the parent process dies.

If that is the case, hydrogen uses `spawnteract` and could benefit from this as well.

**Comment by rgbkrk** [comment]
Would any of you be willing to try out a PR for spawnteract?

**Comment by BenRussert** [comment]
> Would any of you be willing to try out a PR for spawnteract?

I'll look into it tonight.

**Comment by willingc** [comment]
Closing as this seems addressed https://github.com/nteract/spawnteract/pull/31
