### ISSUE TITLE
Copy/Paste Keyboard Shortcuts Occational Failure 

### ISSUE THREAD

**Issue by qzcool** [nteract/archived-desktop-app#2949]
I have tested this occasional bug cases (after several code cells have been runned). For whatever the languages (Chinese/English tested) and input/output contents, keyboard shortcuts (Control+C) won't work but using right click and choose copy still works. 

This is not a big issue but might confuse newbies thus affects UX.

**Comment by rgbkrk** [comment]
Thanks for reporting issues so continuously, even though we haven't been able to address everything (mostly due to bandwidth). You've been so diligent on reporting these issues and categorizing them, would you like to join nteract with a role of labelling and triaging issues with us?

**Comment by qzcool** [comment]
Absolutely, that sounds good to me. Thanks for inviting, Mr. BDFL. How we do this so?

**Comment by rgbkrk** [comment]
By now you'll get an invite to join which you can accept by visiting https://github.com/nteract (look for a banner at the top). Being part of the org does require using GitHub's [Two Factor Auth](https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/).

Welcome to the nteract party! 🎉 

First steps I'd love to have:

1. Go through unlabeled issues
2. Mark it with `pkg:PACKAGE_NAME` and/or `app:APP_NAME`
  * If you don't know what app or package name, it's ok to mark it with `triage` and I can come back to label them
  * It's also ok to just label it with the apps you know it affects (desktop, jupyter-extension, etc.)

Separately, create a new issue, labeled `pinned` (that's a label to let the bots know not to mark it as stale or lock it), that outlines our issue triaging strategy above as a bit of a meta issue. Then we can all discuss the issue triage / label / maintenance efforts.

**Comment by qzcool** [comment]
Mostly done with 95 unlabelled issues TBD bit by bit. An interesting learning process!

**Comment by rgbkrk** [comment]
Woohoo!

**Comment by stormpython** [comment]
Closing as this has been stale for sometime.
