### ISSUE TITLE
[jext] Make "Start a New Notebook" collapsible

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2950]
From a user:

> "On my macbook it pushes my tree mostly below the fold."

**Comment by alexandercbooth** [comment]
Should default be expanded or collapsed?

**Comment by rgbkrk** [comment]
Probably default to expanded.

**Comment by captainsafia** [comment]
This will still need to be addressed. I'm gonna mark this as new contributor friendly/help wanted since it seems reasonable enough for a new contributor to approach.
