### ISSUE TITLE
New Cell Creation is hard to discover

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2953]
Users have voiced concern over trouble getting to the little hover area for creating new cells.

**Comment by captainsafia** [comment]
@fabric-8 Another bit of UI feedback to consider. In our current interface, you create new cells by hovering in between cells but this is a little undiscoverable for users.

**Comment by captainsafia** [comment]
Gonna close this because our new UX will address this. Stay tuned for this in mid-Summer 2020.
