### ISSUE TITLE
nteract's Issue Triaging Strategy

### ISSUE THREAD

**Issue by qzcool** [nteract/archived-desktop-app#2959]
First steps I'd love to have:
1. Go through unlabeled issues
2. Mark it with `pkg:PACKAGE_NAME` and/or `app:APP_NAME`

Reminder:
* If you don't know what app or package name, it's ok to mark it with `triage` and I can come back to label them
* It's also ok to just label it with the apps you know it affects (desktop, jupyter-extension, etc.)

**Comment by captainsafia** [comment]
Closing this in favor of https://github.com/nteract/nteract/issues/4363 to ensure that we capture this information in our documentation.
