### ISSUE TITLE
TItle Kernal Status Display Unrefreshable Error (macOS)

### ISSUE THREAD

**Issue by qzcool** [nteract/archived-desktop-app#2964]
<img width="800" alt="wx20180611-173954 2x" src="https://user-images.githubusercontent.com/10396208/41224302-b708cfb6-6d9e-11e8-9356-3bfc9e91a0e6.png">

**Comment by captainsafia** [comment]
Closing this as it has gone stale and I can't reproduce. If this issue still exists on the latest version of nteract, please reopen. Thanks for opening the original issue,  @qzcool!
