### ISSUE TITLE
Select multiple cells and move them

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#297]
We should be able to select multiple cells and move them. Would be super cool to move multiple cells at at the same time.

**Comment by cfljam** [comment]
Is it possible to move any cell?

**Comment by rgbkrk** [comment]
@cfljam On the left side of the cell (the input area) you can click to drag and drop cells. I'll chalk that one up to us needing better discovery of the drag and drop location and likely an alternate way of moving cells up and down.

**Comment by cfljam** [comment]
Cool but too subtle! The really clean interface is part of the attraction
