### ISSUE TITLE
command-line for opening a python or python notebook file in nteract?

### ISSUE THREAD

**Issue by matanox** [nteract/archived-desktop-app#2988]
Is there a command-line for opening a python or python notebook file in nteract from a unix terminal/shell? just wondering

**Comment by alexandercbooth** [comment]
Hi @matanster, thanks for using nteract!

In the menu bar, if you click "nteract", you will see the following:
![image](https://user-images.githubusercontent.com/15242567/41415265-2d9593a8-6fb6-11e8-83a7-be6afb99c33e.png)

Clicking "Install Shell Commands" will do what you are asking. After you have done that, from a new shell you can just `nteract mynotebook.ipynb`

**Comment by matanox** [comment]
Thanks! I actually wondered what "install shell commands" would do lol. Very helpful!

**Comment by matanox** [comment]
It should probably say somewhere though, that permissions need to be fiddled:

> EROFS: read-only file system, open '/tmp/.mount_nteraczExVgy/app/resources/bin/nteract-env'

**Comment by alexandercbooth** [comment]
That's a great point, thanks @matanster!
