### ISSUE TITLE
Installation requires jupyter serverextension enable...

### ISSUE THREAD

**Issue by nickynicolson** [nteract/archived-desktop-app#2991]
Installation instructions in the [nteract_on_jupyter article](https://blog.nteract.io/nteract-on-jupyter-53cc2c38290d) suggest that these steps would be sufficient:

    pip install nteract_on_jupyter
    jupyter nteract

In my environment (Python 3.6.1 :: Anaconda custom (64-bit), jupyter version 4.3.0, nteract_on_jupyter version 1.7.0) this starts a notebook server, spawns a browser at http://localhost:8888/nteract/edit which displays a 404
If I do:

    jupyter serverextension enable nteract
    jupyter nteract

... then all is well.

@rgbkrk thought that use of jupyter config.d would make this enable automatically (i.e. render the serverextension command redundant)

**Comment by rgbkrk** [comment]
At runtime, at the very least, we should check that we're on the right notebook version and that the serverextension is enabled. Since our registration of `jupyter nteract` is successful, we should be able to detect this on launch. 🤔 

cc @mpacer

**Comment by rgbkrk** [comment]
I've gone ahead and updated the article to make note of `jupyter serverextension enable nteract`:

![screen shot 2018-06-14 at 5 14 14 pm](https://user-images.githubusercontent.com/836375/41444200-6dc4dde0-6ff6-11e8-98af-187d06b3f335.png)

We should still do something for runtime though. Thanks for reporting this and for giving nteract a spin @nickynicolson!
