### ISSUE TITLE
Expand cell size for Data Explorer automatically

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2995]
The Data Explorer should not be subject to the display area collapsing. Otherwise it's "stuck in a fixed box", even if the user clicks to "expand cell":

![screen shot 2018-06-14 at 4 21 58 pm](https://user-images.githubusercontent.com/836375/41442980-1982670e-6fef-11e8-9259-a5a66bdf0352.png)

**Comment by yozlet** [comment]
Possibly related: Sometimes that box is too big, and there doesn't seem to be a way to shrink it. (Having manual control over sizing would also be useful, but that's a different issue.)

<img width="950" alt="__work_customer_data_classpass_2018-06-10_equity_ipynb_-_idle" src="https://user-images.githubusercontent.com/173848/41491227-b3a6b3c2-70ac-11e8-8ad0-b0602b862708.png">
