### ISSUE TITLE
Published modules require react-hot-loader

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#2998]
The new release of `@nteract/` packages requires `react-hot-loader` as a dependency due to the [babel config](https://github.com/nteract/nteract/blob/master/.babelrc#L4) used during publishing.

We should remove this babel plugin for the published packages.

Checkout https://github.com/nteract/hydrogen/issues/1335, https://github.com/nteract/hydrogen/pull/1336
Also related to #2977

**Comment by rgbkrk** [comment]
Darn it. I had to set these up in order for hot reloading to work within the monorepo on components that check children type:

```js
// react-hot-loader uses proxies to the original elements so we need to use
// their comparison function in case a consumer of these components is
// using hot module reloading
import { areComponentsEqual } from "react-hot-loader";

{React.Children.map(this.props.children, child => {
          if (areComponentsEqual(child.type, DropdownTrigger)) {
            return React.cloneElement(child, {
              onClick: ev => {
                this.setState({ menuHidden: !this.state.menuHidden });
              }
            });
...
```

I should have added react-hot-loader to these components as a direct dependency because of what they list:

> Note: You can safely install react-hot-loader as a regular dependency instead of a dev dependency as it automatically ensures it is not executed in production and the footprint is minimal.

In further thinking though, this is affecting _all_ components and _all_ libraries because of the babel config. I need to just set this react hot loader babel setup for the components that definitely need it.

**Comment by rgbkrk** [comment]
The packages and apps that _actually_ need this babel config:

* nteract-on-jupyter
* dropdown-menu
* notebook-app-component
* transform data resource

**Comment by jdpigeon** [comment]
Encountering this issue right now. The nteract package that throws the error is enchannel-zmq-backend.

This is a bit of a problem for my app, which uses a two package.json structure to seperate native dependencies. enchannel-zmq-backend requires react-hot-loader out of the blue (not in it's package.json), which caused `Cannot resolve module` errors until I surgically removed it from the package. 

It seems to work fine now without the react-hot-loader calls, so I think removing them would be best.

**Comment by rgbkrk** [comment]
Yeah, it's our babel config that's injecting these. We need the packages that require these (primarily using `areComponentsEqual`) to set a custom babel config and keep the rest with simple configs.

**Comment by rgbkrk** [comment]
I'm working on this now. It's tempting to further segment the components, which mostly have a need for both this and styled-jsx. I'll do my best to rectify this for the libraries first though.

**Comment by rgbkrk** [comment]
Fixed and published. The next thing we need to do is segment all the components so they include styled-jsx as a peer dependency.

**Comment by jdpigeon** [comment]
:raised_hands:  Thanks man! This'll make building to production so much easier
