### ISSUE TITLE
Notebook operations

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3]
- [x] Open a new notebook
- [x] Save a notebook
- [x] Load a notebook from disk

**Comment by rgbkrk** [comment]
Related: https://github.com/nteract/composition/issues/9

**Comment by rgbkrk** [comment]
Other questions:

## Where is a user's workspace?

When you launch a kernel, is it relative to the save path of the notebook? 

## Storing last session

We'll probably want to store data to the jupyter config directory. You can get this via:

``` javascript
require('jupyter-paths').configDirs()
```

**Comment by betatim** [comment]
loading and saving now work!

**Comment by ivanov** [comment]
I don't think saving works.
![screen shot 2016-02-15 at 1 15 02 pm](https://cloud.githubusercontent.com/assets/118211/13060431/3f9d924e-d3e6-11e5-922a-2abfaaf8f063.png)

**Comment by rgbkrk** [comment]
:boom: We're done here
