### ISSUE TITLE
Multiline output appears on one line

### ISSUE THREAD

**Issue by orenjiataronjat** [nteract/archived-desktop-app#3002]
I am using

```python
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
```

to get multiple lines to out put.

If I type:

```
a = 1
b = 2
a
b
```

I would expect to get:

```
1
2
```

Instead, I get:

```
12
```

Am I doing something wrong or should this not be happening?

**Comment by rgbkrk** [comment]
Interesting! I looked at what those are under the hood and each `execute_result` should be a block level element (in HTML parlance). I need to make this fix. Thanks for reporting!
