### ISSUE TITLE
Data explorer crashes with a notebook (that I think is ok)

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#3005]
I'm creating [this](https://gist.github.com/davidanthoff/f17f89736dc9016d209d66047ceefd45) notebook from within julia. It has the tabular data stored as a ``application/vnd.dataresource+json``, so I would have expected it to show up nicely in nteract 0.9.

Instead, I get the following error:

![error](https://user-images.githubusercontent.com/1036561/41558293-307851a4-72f5-11e8-889f-9bb90a728c17.png)

I guess either I'm output incorrect ``application/vnd.dataresource+json``, or there is a bug somewhere else? Any pointer would be greatly appreciated, I can't wait to fully enable this scenario!

**Comment by rgbkrk** [comment]
cc @emeeks

**Comment by rgbkrk** [comment]
I'm seeing the data and schema fields in the right place (I think). I'll look into this with Elijah to figure it out.

**Comment by davidanthoff** [comment]
Thanks! Did you see any problem so far?

**Comment by davidanthoff** [comment]
Bump, any update on this?

**Comment by emeeks** [comment]
Sorry I never saw this. I'll take a look now.
