### ISSUE TITLE
Export React components for use on the web

### ISSUE THREAD

**Issue by iamlaokui** [nteract/archived-desktop-app#301]
I made a react-based notebook which could work on browser-side, most of code, design is inspired from nteract though (store-dispatch, enchannel etc) . What I want to make is an react-components that can be used by more common ways, both desktop and browser-side.

Right now I have to share same code from nteract, it's not a good & right way to do it, is it possible to make a separated package from nteract just like react-jupyter-display-area.

Plz check the project, I'd love to hear your ideas.
https://github.com/kerwin/react-notebook

**Comment by jdfreder** [comment]
Hey @kerwin , very cool!  It's good to see that you were able to do this.  @rgbkrk and I were talking about doing the same thing at some point.  We want to be able to re-use the nteract interface in web/deployed contexts.  Ideally it would be a matter of swapping out the electron native components with web friendly analogs.

**Comment by iamlaokui** [comment]
Thanks @jdfreder, re-useable web-friendly react-based interactive notebook is exactly what I want.
I'd love to hear your thoughts about how to make it possible.

**Comment by rgbkrk** [comment]
Closing in favor of #1346.

**Comment by rgbkrk** [comment]
Just an update -- there is now a web version of nteract that runs on top of the jupyter server. You can [try it out on binder!](https://mybinder.org/v2/gh/nteract/vdom/master?urlpath=nteract/edit/example-notebooks)

The jupyter extension is called `nteract_on_jupyter` on PyPI and there are install instructions here: https://github.com/nteract/nteract/tree/master/applications/jupyter-extension

Beyond that, there are related packages for building your own using `@nteract/core`. I don't think the API is stable yet, so you'd have to build along with us.
