### ISSUE TITLE
AppImage of new version (0.9.0) doesn't work in Centos 7-5 when the previous worked

### ISSUE THREAD

**Issue by gbellefl** [nteract/archived-desktop-app#3014]
Hello,

the error message is Floating exception (core dump). The update was done on June 20.
Version 0.8.4 worked fine before.

**Comment by rgbkrk** [comment]
This should be closed by #3003. A release is coming out within minutes that you'll be able to upgrade to. The AppImage was definitely broken in 0.9.0.
