### ISSUE TITLE
R Kernel in Linux app image keeps dying

### ISSUE THREAD

**Issue by MilesMcBain** [nteract/archived-desktop-app#3020]
I just see 'ir | process exited' in the bottom left of nteract. It did actually start a couple of times, but I haven't been able to reproduce that reliably.

I see this in the console:
```
>>>> Logging kernel ir (ref 5ad82277-6730-46ad-b92d-2600f8bcc9d6) stdout and stderr to javascript console in this color    <<<<

app.js:218 Error: identical(signature, expected_signature) is not TRUE
Execution halted

app.js:218 
```

**Comment by BenRussert** [comment]
I tried this last night and did not have the same issue. The error is thrown from the IRKernel, are you using an up to date IRKernel install?

[This issue](https://github.com/IRkernel/IRkernel/issues/138 ) came up when I searched

**Comment by MilesMcBain** [comment]
It was a fresh install of the IRKernel, but my Jupyter could be a bit old. I had mistakenly thought the app image wrapped up the Python dependencies, but that is not so - correct?

**Comment by rgbkrk** [comment]
We don't wrap up any jupyter dependencies inside of nteract, it uses the protocols without having to run python (unless using a python backed kernel).

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if you are still seeing this with the latest R kernel and nteract versions. Thanks! 🌻
