### ISSUE TITLE
desktop file does not pass desktop-file-validate on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [nteract/archived-desktop-app#3022]
The desktop file in the AppImage does not pass desktop-file-validate on Ubuntu 14.04:

`nteract.desktop: error: value "application/x-ipynb+json" for string list key "MimeType" in group "Desktop Entry" does not have a semicolon (';') as trailing character`

Reference:
https://github.com/AppImage/appimage.github.io/pull/638

**Comment by BenRussert** [comment]
In order to fix we need to add a semicolon [here](https://github.com/nteract/nteract/blob/master/applications/desktop/package.json#L84) at the end?

**Comment by probonopd** [comment]
Possibly (not sure how electron-builder works internally); but what is important is that there is a semicolon on the resulting .desktop file.

**Comment by rgbkrk** [comment]
Amusingly, I believe that this was fixed in a newer version of electron builder. Since the latest version of breaks a different issue with AppImages (on Debian distros), we're in a tricky spot.

Thank you for maintaining AppImage Hub @probonopd!

**Comment by probonopd** [comment]
Not doing anything is never a good reason to close bug reports imho...

**Comment by captainsafia** [comment]
Hi @probonopd! A few releases of nteract have come out in the 10 months this issue was opened and we are on a newer version of electron-builder. Can you reproduce the issue on the latest release of nteract?

**Comment by probonopd** [comment]
Hi @captainsafia, where can the AppImage be downloaded? I don't see it on GitHub Releases (anymore?). Thanks.

**Comment by captainsafia** [comment]
Try it at this link: https://github.com/nteract/nteract/releases/tag/v0.13.0

I've been trying to figure out how to pin certain releases to the top of the release page for easy finding but haven't found an elegant solution thus far.

**Comment by probonopd** [comment]
Please reopen, as the problem persists in `nteract.0.13.0.AppImage`.

Log:
https://api.travis-ci.org/v3/job/522757670/log.txt

**Comment by captainsafia** [comment]
This issue was auto-closed with a PR. Can you verify if the problem persists in 0.14.0?

https://github.com/nteract/nteract/releases/tag/v0.14.0
