### ISSUE TITLE
Opening notebooks directly

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#303]
Users should be able to open notebooks from their native windowing environment straight into nteract.
- [x] OS X
- [x] Linux ~~(see [associator](https://github.com/nteract/associator))~~ Done with `electron-builder`
- [x] Windows

Nice to have:
- [ ] Quicklook plugin for OS X

---

I sat down with a computational journalist while I was in Oakland a couple weeks ago and asked him what problems he runs into with the current jupyter notebook.

One of the main points he described was the current workflow around searching for notebooks on the filesystem.

Use spotlight to search for a notebook

![screenshot 2016-04-12 19 21 46](https://cloud.githubusercontent.com/assets/836375/14479401/9cb2f60c-00e3-11e6-9831-30f2247dce03.png)

Go to click it

![screenshot 2016-04-12 19 22 29](https://cloud.githubusercontent.com/assets/836375/14479408/bd85d7aa-00e3-11e6-9db4-c4e7493dc387.png)

Oops, can't! Now you have to figure out where the file is located on disk then launch a notebook server relative to where it is.
## Native app flow

With a registered native app, the user can open the file directly. Native search brings the user to the file, then they click it. :tada:

Same thing goes for opening it from the command line, via Finder, or with "File -> Open" from nteract.
## An aside

As he described this, I started thinking about all the search and indexing of notebooks we've talked about in core, both for local indexing (spear headed by @szeitlin) and as part of nbviewer (terribly done by me). For the server side case we probably still need this (or so I assume). Seems like the native app can expose this by not doing anything at all other than handling files very cleanly.

**Comment by szeitlin** [comment]
fwiw, it would be awesome to be able to preview notebooks natively on mac. I suspect that might actually be harder than just making them open-able with a native application. I also still want to have a way to view & sort files by date, other than having to include the date in the filename or depend on the OS for that.

**Comment by rgbkrk** [comment]
Yay! Hi @szeitlin! Thanks for joining via my random summons there and welcome to nteract!

There is [a quicklook plugin for IPython/Jupyter](https://github.com/ihrke/IPythonQL), though I have not tried it yet:

![image](https://cloud.githubusercontent.com/assets/836375/14481209/6c4ffe2a-00f6-11e6-9638-29f45586314e.png)

The way we open notebooks natively from the nteract notebook right now is like this, which leaves viewing and sorting up to the folder you're in:

![screenshot 2016-04-12 21 23 00](https://cloud.githubusercontent.com/assets/836375/14481216/7d5b54e4-00f6-11e6-8ba2-82dd782f5a3d.png)

Does that help with the experience or are you looking for more?

**Comment by rgbkrk** [comment]
This now works well on OS X, still needs work for Windows and Linux.

**Comment by lgeiger** [comment]
Thanks to `electron-builder` this now _should_ work on Windows and Linux as well. Though testing is needed.

**Comment by rgbkrk** [comment]
Oh yeah, this should be good on Windows. I can try it tonight.

Really need to circle back on the whole Quicklook plugin.

**Comment by rgbkrk** [comment]
I'll go ahead and close this. We can re-open, though if it manifests as an issue I think it's something for us to help fix in `electron-builder`.
