### ISSUE TITLE
Under File->New menu group kernels by language

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#3036]
Moved over from https://github.com/nteract/nteract/issues/2010#issuecomment-339798146 so that it doesn't get lost.

It might be useful to have another level in the New Notebook menu which groups the kernels by language:
```
 * New Notebook
    * Python
      - Python Kernel 1
      - Python Kernel 2
    * R
      - R Kernel
    * Julia
      - Julia Kernel
```

**Comment by rgbkrk** [comment]
Did you mean to close this?

**Comment by dhirschfeld** [comment]
Nope, dunno how I did that. Reopened, thx!

**Comment by rgbkrk** [comment]
Sweet, this is a good suggestion.

**Comment by raymundogarfio89** [comment]
[](url)

**Comment by rgbkrk** [comment]
Oh ha, I added the pinned label a little late. This got marked as stale a while ago.
