### ISSUE TITLE
[OS X] Incorporate QuickLook plugin

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#305]
As brought up in #303, evaluate [IPythonQL](https://github.com/ihrke/IPythonQL) for including at nteract installation time to allow people to view their notebooks as a preview.

**Comment by jdfreder** [comment]
You meant add nteract rendering support to IPythonQL?  Shouldn't this be an issue in IPythonQL's repo?

**Comment by rgbkrk** [comment]
I mean that when we install, we want to have quicklook support for notebooks also installed so when they browse through they see:

![quicklook fisher](https://cloud.githubusercontent.com/assets/836375/14481209/6c4ffe2a-00f6-11e6-9638-29f45586314e.png)

**Comment by Carreau** [comment]
+1,  we might want a better theme for the QL plugin though.

**Comment by rgbkrk** [comment]
Yeah, that's true. We can also use the components we've been putting together here in it.

**Comment by Fil** [comment]
want! :)

**Comment by willingc** [comment]
Closing this issue given the UI updates the past 6 months.
