### ISSUE TITLE
Expand/collapse all cells (for print or PDF)

### ISSUE THREAD

**Issue by yozlet** [nteract/archived-desktop-app#3073]
I want to print a report, so only output, no code. In searching, I found #1610, but the "Expand All Cells"/"Collapse All Cells" menu items mentioned in that issue don't seem to be present in the current builds - are they gone now?

**Comment by willingc** [comment]
In version 0.12.3, the hidden cells are left hidden when creating a PDF. If Cell -> Unhide Input and Output in all Cells is selected before saving a PDF the previously hidden cells are displayed and output in the PDF.

There does not appear to currently be a "Collapse all cells" ability through the menu or keyboard shortcuts.

@rgbkrk Is there currently a way to collapse all cells?

**Comment by willingc** [comment]
This behavior to collapse and expand is desired for both code cells and markdown cells in #3273
