### ISSUE TITLE
unpin fonts from git release.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#308]
The following are making my npm install take **literally** more than 30 minutes on not-that great connection as it does clone the full repo:

```
  "source-code-pro": "git://github.com/adobe-fonts/source-code-pro.git#release",
   "source-sans-pro": "git://github.com/adobe-fonts/source-sans-pro.git#release",
```

Can we avoid that ?

**Comment by jdfreder** [comment]
I think we should move the static assets, fonts and icon fonts, into a separate npm package.  That way it will be a one and done affair.

**Comment by rgbkrk** [comment]
Once #417 is merged, this is completely finished off from the git based loading. Later we'll want to switch to only WOFF2 format for the fonts, which trims our size quite a bit.
