### ISSUE TITLE
Delete/Play/Settings overlaps with long cell content

### ISSUE THREAD

**Issue by emeeks** [nteract/archived-desktop-app#3103]
Presents an issue when you want to edit a long line in a cell and you accidentally click the trash can icon instead of the cell contents.

<img width="1587" alt="screen shot 2018-07-20 at 6 19 08 pm" src="https://user-images.githubusercontent.com/495634/43030738-7b0d628c-8c49-11e8-8354-6f68550026ef.png">

**Comment by willingc** [comment]
Closing and tracking in https://github.com/nteract/nteract/issues/3855
