### ISSUE TITLE
Add jupyter extension installation guidance to README

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3112]
Our base readme lists how to get the desktop app and go to play. We also need it to show how to install the jupyter extension.

**Comment by myounus96** [comment]
Please give details how can we install jupyter notebook extension(https://github.com/ipython-contrib/jupyter_contrib_nbextensions) for nteract or how can we make our own?
Thanks

**Comment by rgbkrk** [comment]
The instructions are now here: https://github.com/nteract/nteract/blob/master/README.md#installing-nteract-web

🎉
