### ISSUE TITLE
Publishing woes

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3114]
As I found out today, if we merge things (my bad) while we're in the middle of publishing it can mess up the process for lerna because the git tags portion relies on pushing to the repo (and can't be out of sync).

Not sure what to fix about this. I'm publishing again as a result. 😅

**Comment by willingc** [comment]
Close the issue perhaps?

**Comment by rgbkrk** [comment]
Ah yeah, thanks!

**Comment by willingc** [comment]
Love that we are under 300 issues now and its much easier to sort by label @rgbkrk
