### ISSUE TITLE
Update code of conduct

### ISSUE THREAD

**Issue by alexandercbooth** [nteract/archived-desktop-app#3119]
There are some valuable new additions to the latest version of the [covenant contributor code of conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct). We should update our `CODE_OF_CONDUCT.md` accordingly 😄

**Comment by lightsquared** [comment]
I would like to try this issue.

**Comment by lightsquared** [comment]
Ok, I cloned the nteract repository on my desktop.  I have updated the local COC as a markdown file.  I have created a new local branch called code_of_conduct.  Not sure what else I need to do.  Help would be appreciated.

**Comment by jdetle** [comment]
Happy to help, will be in here for the next ten minutes. https://zoom.us/j/743805539w

**Comment by jdetle** [comment]
Okay, after you do that, you should add the file with `git add <path_to_markdown_file>`, then `git commit -m 'Update code of conduct'`, and then `git push -u origin code_of_conduct`. From there, you should be able to open a pull request via github.

**Comment by lightsquared** [comment]
Shonns-MacBook-Pro:nteract skmcneill$ git push -u origin code_of_conduct
remote: Permission to nteract/nteract.git denied to lightsquared.
fatal: unable to access 'https://github.com/nteract/nteract.git/': The requested URL returned error: 403

**Comment by rgbkrk** [comment]
Hey all! I was in the progress of updating ours today actually. Glad to see this getting started. What I want to make sure we bring onto our code of conduct is our values statement of what we strive for as a project and how the code of conduct supports that.

Our vision:

> Create fantastic interactive computing experiences that allow people to collaborate with each other with ease.

Our CoC is about fostering this collaboration, interaction, and ease. It takes some recognizing that we must show empathy and understanding across various axes where we may not have the same perspectives.

------------

@lightsquared You'll need to fork this repository and [add your fork URL as a remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/).

**Comment by lightsquared** [comment]
I'll go ahead a fork the repository.  I use nteract all the time and hope to help more.  I went ahead and updated the file online and requested a pull request that way.  I'll figure out the "add your fork URL as a remote" in time.
