### ISSUE TITLE
AssertionError [ERR_ASSERTION]: path must be a string - Processing Kernel

### ISSUE THREAD

**Issue by rsrini7** [nteract/archived-desktop-app#3122]
AssertionError [ERR_ASSERTION]: path must be a string

Attached screenshot.
![2018-07-27 10_49_45-untitled - idle](https://user-images.githubusercontent.com/5178105/43302988-4d050588-918b-11e8-9c58-ef6c8a15960d.png)

Works fine in the browser.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if you are still seeing this behavior. Thanks! 🌻
