### ISSUE TITLE
Option to switch python location on the fly

### ISSUE THREAD

**Issue by rsrini7** [nteract/archived-desktop-app#3123]
Currently, it is picking from PATH. It's better to give the option to choose python folder on the fly.

**Comment by deeplook** [comment]
Yes, it would be definitely helpful to be able to point to a given Python installation when calling the command-line tool named `nteract` that I can install from the app.

**Comment by willingc** [comment]
If launching from the command line, you can use `nteract --kernel <kernel_to_launch>` to launch a specific kernel. You can use `jupyter kernelspec list` on the command line to see which kernels are installed.
