### ISSUE TITLE
Keyboard shortcut for documentation of function

### ISSUE THREAD

**Issue by zaeemnalla** [nteract/archived-desktop-app#3124]
What's the equivalent keyboard shortcut for shift-tab in a jupyter ipython notebook (running in a browser) that brings up documentation for the function that the cursor is at?

**Comment by alexandercbooth** [comment]
Hi @zaeemnalla, thanks for taking nteract for a spin!

The keyboard shortcut for this is control + period: "Ctrl-."

__Note__: you have to click the "X" in the upper right corner of the documentation to close.

**Comment by zaeemnalla** [comment]
Thanks for the help @alexandercbooth. Do you know where I can find all other available shortcuts for the app? I'd be keen on contributing a shortcuts view nested under the help menu item if there's interest.

**Comment by alexandercbooth** [comment]
You're very welcome. As far as I am aware, our only other non-menu-shortcuts are [here](https://github.com/nteract/nteract/blob/5254a26555814b327dacd0bfd0b908baaa4d2ebf/packages/editor/src/index.js#L110-L119).

We would love to have you contribute, @zaeemnalla! In fact, next week we will be having a [global sprint](https://github.com/nteract/global-sprint) (remote participation encouraged) and one major initiative is all about docs. This would definitely be good to have documented and is a great time to start contributing 😄 .

**Comment by zaeemnalla** [comment]
Fabulous 😆 Perfect timing! Thanks for mentioning it
