### ISSUE TITLE
Failed propTypes

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#313]
I get a few of these:

```
.../node_modules/fbjs/lib/warning.js:44 Warning: Failed propType:
Invalid prop `displayOrder` of type `List` supplied to `Display`,
expected instance of `List`. Check the render method of `CodeCell`
```

Why is that ? Got the same for `Map`, which should be `Map` .... so all seem correct, but still get warnings ?

**Comment by rgbkrk** [comment]
Hmmm, I'm not seeing that in my console. Do you have a notebook this is triggered on?

**Comment by Carreau** [comment]
Empty one, when you start nteract.

**Comment by Carreau** [comment]
Ok, cleaned reinstall, it works. Thanks.
