### ISSUE TITLE
Update READMEs across the repo to use yarn instead of npm

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3134]
Hey all! 👋 

We're on `yarn` (again...). You'll want to personally upgrade your `yarn` version locally.

As for the bigger issue though -- we need to give people good guidance on using `yarn`. It would be great to have folks go after cleaning up the README, contributing docs, etc. to take this into account. Any takers?

**Comment by ivanov** [comment]
"not on" you mean "now on"?

**Comment by hydrosquall** [comment]
Pushing a PR up for this shortly :)
