### ISSUE TITLE
Data-Explorer: Sort Legend to Match Chart

### ISSUE THREAD

**Issue by kainoa21** [nteract/archived-desktop-app#3146]
When I switch to a bar chart view, then the data looks to be sorted based on the category.  But the order of the categories in the legend does not match that.

**Comment by emeeks** [comment]
Could you post a screenshot. Looking at the bar chart I see the same order in the legend. Is it that the legend is a multiline HTML legend? If so, what's a better way to show the legend or signal the order?

<img width="1347" alt="screen shot 2018-07-30 at 11 18 01 am" src="https://user-images.githubusercontent.com/495634/43415409-528fd792-93ea-11e8-8161-77df3d3f27ff.png">
<img width="885" alt="screen shot 2018-07-30 at 11 17 48 am" src="https://user-images.githubusercontent.com/495634/43415410-52ac971a-93ea-11e8-806c-14a318cf8a80.png">

**Comment by emeeks** [comment]
Or it could be that since I'm running it locally it's something that got implemented in a more recent version that isn't released...

**Comment by emeeks** [comment]
I think this is no longer the case so I'm going to close this, feel free to reopen if you still see this behavior.
