### ISSUE TITLE
Data explorer: Educate users about hexbin value

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#3164]
Hexbins are cool. Explain to users why. 

Feedback from Elijah presentation (global-sprint).

**Comment by hydrosquall** [comment]
@captainsafia / @emeeks - these `global-sprint` tagged items might also be good to attract some `hacktoberfest` visitors

**Comment by rgbkrk** [comment]
Yeah I wonder where we need to do this in -- within the app? within our user guide? I guess both I suppose.
