### ISSUE TITLE
Support installation without Admin rights on Windows

### ISSUE THREAD

**Issue by ankostis** [nteract/archived-desktop-app#3189]
Many Windows users do not have administration permissions on their PCs, but still need to run scientific calculations.
If it is possible, please setup your packager not to require admin rights OR  gracefully degrade when these are not provided.

**Comment by willingc** [comment]
If a Windows 10 user can document what happens on installation with inadequate permissions, that would be helpful. Thanks.

**Comment by jerik** [comment]
> If a Windows 10 user can document what happens on installation with inadequate permissions, that would be helpful. Thanks.

If a user has no administration rights, he cannot install the application... A portable version of **nteract** would be great. So you could increase your userbase, especially in the company section. Where normal employes does not have admin rights.
