### ISSUE TITLE
nteract stays blank on notebook open

### ISSUE THREAD

**Issue by r-zip** [nteract/archived-desktop-app#3191]
When opening a notebook, nteract stays blank, never loading any of the content from the file (not even a code cell).

When opening the same notebook with `jupyter notebook`, there is no issue.

**Comment by rgbkrk** [comment]
Howdy! Is this in the jupyter extension or the desktop app? If it's the jupyter extension does it show the menu?

**Comment by r-zip** [comment]
This is the desktop app.

**Comment by BenRussert** [comment]
Hi @rzpilgrim, what platform are you on and how did you install?

Is the problem only when you try to open an existing notebook? Or does this happen with a new notebook at startup?

**Comment by BorisVarbanov** [comment]
Hello, just wanted to give some info, after I experienced the same issue today (desktop version) - it was due to the presence of an inline LaTeX equation embedded in a markdown cell (simply $\phi$). Removing this enabled the notebook to be shown and interacted with. This problem is more specifically referenced in a newly submitted issue #3226.

**Comment by rgbkrk** [comment]
Ok I'm taking a look at this one now.

**Comment by rgbkrk** [comment]
Closed by #3228 

We'll get a release out within the next 12 hours.

**Comment by r-zip** [comment]
I had some inline equations in mine as well, but unfortunately, removing them did not solve my issue.

I am on macOS High Sierra 10.13.6, and I downloaded the installer from your website. It only occurs when I try to open an existing notebook. Jupyter notebook has no issue viewing/editing the file.

**Comment by BenRussert** [comment]
Have you had a chance to try the new release @rzpilgrim?

**Comment by r-zip** [comment]
Just tried it. It opens fine now.

**Comment by BenRussert** [comment]
Excellent!
