### ISSUE TITLE
Contributor Guidelines for updating snapshots

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#3193]
So some of our tests involve jest snapshots which have a good amount of [best practices](https://jestjs.io/docs/en/snapshot-testing#best-practices) around how to work with them:[jest-docs](https://jestjs.io/docs/en/snapshot-testing).

We also have some conventions and best practices specific to nteract. 

For example, we are concerned with the declarative JSX after it has been processed by utilities like styled-jsx, not an actual DOM render. 

Also we should document how to update the snapshots:

```
yarn test --updateSnapshot
``` 

I'll be happy to make a PR once I know where such a PR should actually live… I'm thinking it might be in [CONTRIBUTING.md](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md) but it's already pretty complicated. 

@willingc I'm pretty sure you were working on some of the developer docs… is there somewhere else this info should go as well?

**Comment by rgbkrk** [comment]
There's a `doc` folder inside this repo that could certainly use more of what's currently in contributing.md. Maybe `doc/how-to-test.md`? Then that can include our own practices around it as well as links to jest docs + tutorials.

**Comment by willingc** [comment]
@mpacer I think it's fine for the moment to put docs for dev in this repo.

We can do a sweep of docs for devs at one time (in the near future for the docusaurus repo).
