### ISSUE TITLE
Scatter Plot X-Axis Can't Handle Small Values

### ISSUE THREAD

**Issue by lightsquared** [nteract/archived-desktop-app#3209]
I attempted to plot an explosion overpressure plot.  The x-axis data is measured in seconds.  The values are small on the order of 1E-4.  The time is increasing by 5E-6.  The chart just shows zeros in the x-axis.  Also, the pressure data on the y-axis appears random.  When it should be a step function.  It could be that I have too many points at 2 million.

**Comment by rgbkrk** [comment]
Are you using the data explorer or a plotting library?

**Comment by emeeks** [comment]
I can add some basic support for canvas rendering when the amount of points is over some reasonable threshold.

**Comment by rgbkrk** [comment]
On the axis issue -- I notice that we need more digits when using the happiness data and set standard error as one of the axes:

![screen shot 2018-08-08 at 2 33 05 pm](https://user-images.githubusercontent.com/836375/43865701-24e9220a-9b18-11e8-8cd7-a7ee1cb5ceed.png)

👀  Look at the Y axis

**Comment by emeeks** [comment]
I'll see what the options are for smarter formatting in numeral.

**Comment by emeeks** [comment]
Added 3 degrees of decimal precision as of #3322. I'm not sure I could add more but this all seems like a weirdish hack to set the numeral formatting to `"0.[0000000000]a"` or something so I'll try to see if there's an autoformatting approach that's a little more elegant.

**Comment by emeeks** [comment]
Leaving this open even though #3322 was merged because it would resolve either of the issues from @lightsquared. I'm going to do the following:

* Canvas rendering when there are more than 1000 points (and also disable hoverAnnotation because that's n voroni polygons)
* Implement the mythical "elegant numeral formatting" thing once I figure out what that is.

**Comment by emeeks** [comment]
#3330 adds some smarter rules for axis number formatting as well as canvas rendering for scatterplots with more than 1000 points.
