### ISSUE TITLE
Can't type formulas in the Markdown cell.

### ISSUE THREAD

**Issue by Inferno-P** [nteract/archived-desktop-app#3226]
Hello! 

Displaying any formula or Greek notations in Markdown requires the formula expression to be  in __$__ *my-formula* __$__.  But the initial <kbd>shift</kbd> + <kbd>4</kbd> works fine and prints a __$__ . 

But any subsequent combination of  <kbd>shift</kbd> + <kbd>4</kbd> just makes the nteract window go white and renders it inactve  with only the menubar in display.

I have tested it out with multiple iterations and gotten the same results. 

General Info : 
1. nteract Windows app - 0.11.4
2. Windows 10 
3. Background applications open were : Chrome, Notepad++, MS Excel

**Comment by rgbkrk** [comment]
Thanks for reporting this, I'm taking a look now.

**Comment by BorisVarbanov** [comment]
I experienced the same issue as well. Simply creating and closing the Latex environment (like $$) works for me, but as soon as you want to apply any command inside (such as $\phi$) I get some errors, resulting in a blank unusable notebook. Following the console output from the dev tools I was lead to this [React Error](https://reactjs.org/docs/error-decoder.html?invariant=254&args[]=node). Finally, as expected, this issue doesn't occur when opening notebooks through `jupyter notebook`.

Info:
nteract Desktop app - v0.11.4
kernel: python3
OS: MacOS High Sierra v10.13.6

Thanks in advance.
