### ISSUE TITLE
Open notebook with drag on dock.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#323]
related (but slightly different) from #303.

OS X ONly of course, I guess.

**Comment by jdfreder** [comment]
#322 doesn't fix this?  

Checkout master (as of a few minutes ago),  
`npm i` then  
`npm run dist:osx64`  
:boom: the `dist/nteract-...` folder will have a .app, I think it works with the .app.  Does it not?

**Comment by rgbkrk** [comment]
Oh hmmm, yeah it doesn't accept the file. There must be some handler that has to be specified on it. I can record a GIF later today.

**Comment by rgbkrk** [comment]
The current `npm run dist:osx` now builds with a plist that allows you to drag a file to the nteract app icon.
