### ISSUE TITLE
Provide an up-to-date commuter demo

### ISSUE THREAD

**Issue by shevelevs** [nteract/archived-desktop-app#3233]
If I click on the demo link, I get 404

**Comment by jdetle** [comment]
Thanks for opening your first issue in nteract! Can you specifically let us know which demo link is broken? It seems as though there are a few.

**Comment by shevelevs** [comment]
@jdetle, sorry about that. I meant the commuter project readme: https://github.com/nteract/nteract/blob/master/applications/commuter/README.md

**Comment by rgbkrk** [comment]
Ah yeah we need to deploy a new version. We should probably take that demo link out for now.

**Comment by rgbkrk** [comment]
Took out the demo link with #3234, we'll want to get a new version deployed soon.

**Comment by hydrosquall** [comment]
@rgbkrk @captainsafia  I'd be interested in picking this up :). What kinds of notebooks were in the old demo?

I was thinking of hosting it as a glitch.com app as that's what I've used before, but could investigate using `now.sh` to maintain parity with the original demo.

**Comment by captainsafia** [comment]
@hydrosquall Thanks for offering to take this on!

It would be great to host commuter on Glitch, especially with the reach it might get there. I'm not sure how well the environment variables needed to configure commuter would play with Glitch's environment but I think it should be possible.

As for demo notebooks, you can refer to the ones in the [example directory](https://github.com/nteract/nteract/tree/master/applications/commuter/examples).

I'm happy to pair with you on this on the Slack.

**Comment by hydrosquall** [comment]
@captainsafia I think got a basic instance working, and have joined the Slack group! Thank you for the generous offer - I will likely take you up on this for another issue.

**Comment by captainsafia** [comment]
@hydrosquall Wonderful! Looking forward to seeing the instance in action.
