### ISSUE TITLE
Gatsby Plugin Help

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3235]
I just noticed a question on StackOverflow on the gatsby transformer -- 

https://stackoverflow.com/questions/51904876/graphql-unable-to-locate-jupyter-notebooks-using-gatsby-and-nteract-gatsby-tran#

Since I wasn't sure what to do for it and still want to answer it, I'm posting it as an issue here. 😄 

cc @benjaminabel

**Comment by ghost** [comment]
@rgbkrk sorry for the delay... I'm in holidays. It seems that the question has been removed.

**Comment by rgbkrk** [comment]
Lame that it was removed. Oh well!

I'll go ahead and close this, thanks for taking a look.
