### ISSUE TITLE
nteract freezes when calling print in a loop

### ISSUE THREAD

**Issue by r-zip** [nteract/archived-desktop-app#3239]
I ran a loop with a tqdm progress bar and print statements. The nteract app freezes completely until the cell is done running.

**Comment by augdomingues** [comment]
Getting the same behavior here for prints inside loops. The app freezes until the execution is over. I'm running Python 3.5.2 on Ubuntu 16.04 

EDIT: Found this related issue: https://github.com/ipython/ipython/issues/6516

**Comment by jdetle** [comment]
Closed as a duplication of: https://github.com/nteract/nteract/issues/1737
