### ISSUE TITLE
 ImportError: cannot import name 'pre'

### ISSUE THREAD

**Issue by thomaspernet** [nteract/archived-desktop-app#3246]
Hi, 

I'm new to nteract. I installed nteract_on_jupyter in a conda environment and able to use nteract. I also install vdom (pip install vdom==0.1) but when I try to import the module `pre`, it fails

from vdom import pre
ImportError: cannot import name 'pre'

**Comment by rgbkrk** [comment]
Hey there! You'll want `vdom==0.5` (or greater).

**Comment by thomaspernet** [comment]
Thank you @rgbkrk 
It works now. I'm giving it a try with the adult dataset. It looks very nice and definitely useful for data explanatory. Thanks for the great works you are doing
