### ISSUE TITLE
nteract on jupyter passing token?

### ISSUE THREAD

**Issue by Data-drone** [nteract/archived-desktop-app#3248]
I installed nteract on top of my local jupytelab. When I launch with:

`jupyter nteract` 

as per the instructions it launches fine and I can open my notebooks but I get errors:

`403 POST /api/sessions (::1): '_xsrf' argument missing from POST`

this is due to jupyer token and password not being passed through from the nteract web. How can I get the token passed through?

**Comment by rgbkrk** [comment]
Awesome that you installed nteract as well! Thanks for trying it out.

This just got fixed at the JupyterCon sprints in #3259. Thank yous to @yangt!

🎉

**Comment by rgbkrk** [comment]
We'll get a release shipped within the next week. 😄
