### ISSUE TITLE
Undo the remove operation on nteract cell?

### ISSUE THREAD

**Issue by woraperth** [nteract/archived-desktop-app#3250]
Hi,

I love using nteract to analyze the data. The only problem is there seems to be no way to restore the code cell I just deleted. Please kindly let me know if there is a way to do that.

Cheers,
Perth

**Comment by eevleevs** [comment]
Same as #1038

**Comment by willingc** [comment]
Hi folks. Thanks for the report. I'm closing this as a duplicate of #1038
