### ISSUE TITLE
Error running Commuter: Cannot find module "react-hot-loader"

### ISSUE THREAD

**Issue by MarkAWard** [nteract/archived-desktop-app#3253]
Using docker for ease of reproducing the error. Here's the current Dockerfile I'm running

```
FROM node:latest

USER node

# resolving permission errors
RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

# attempted to fix: Cannot find module "react-hot-loader"
RUN npm install react react-hot-loader @nteract/commuter -g

WORKDIR /app
ENTRYPOINT commuter
```

The first error I hit is discussed and resolved [here](https://github.com/nodejs/node-gyp/issues/1236#issuecomment-309447800) related to permission errors from `node-gyp`. 

I was then able to install with `RUN npm install @nteract/commuter -g` and build the image with `docker build -t commuter .` But when running the container `docker run -p 4000:4000 -v /local/notebook/path:/app commuter` the UI flashes the expected result and then displays only a large `200 | OK.` in the middle of the screen. The browser console reveals `Error: Cannot find module "react-hot-loader"`.  Including `react-hot-loader` in the install then leads to `Cannot find module react`, add react in to the install and then back to cannot find react-hot-loader.

**Comment by ghost** [comment]
This worked for me
```
FROM node:8

RUN git clone https://github.com/nteract/nteract.git

WORKDIR /nteract

RUN yarn install

ENTRYPOINT ["npm", "run", "app:commuter"]
```

**Comment by MarkAWard** [comment]
That does work but @jquadrino are you able to get it running using just npm to install and avoiding the need for git clone'ing the whole repo?

**Comment by rgbkrk** [comment]
This is all fixed in the recently released version.

```
$ npm install -g @nteract/commuter
$ commuter
```
