### ISSUE TITLE
ZeroDivisionError on arange (Python 3 kernel)

### ISSUE THREAD

**Issue by nicocarbone** [nteract/archived-desktop-app#3262]
Hi.
I am testing nteract desktop app for python3/numpy development and I found a weird bug (I think).
The following code rises a ZeroDivisionError in the arange line:
```
z_min=0
z_max=4
z_size=20
arange(z_min,z_max,(z_max-z_min)/z_size)
```

The exact error is:

```
ZeroDivisionErrorTraceback (most recent call last)
<ipython-input-30-3d2d182121bf> in <module>()
      2 z_max=4
      3 z_size=20
----> 4 arange(z_min,z_max,(z_max-z_min)/z_size)

ZeroDivisionError: division by zero
```

The same code works perfectly in a jupyter notebook.

**Comment by rgbkrk** [comment]
This isn't an nteract issue as the desktop app calls out directly to the ipython kernel over the standardized jupyter protocol.

If the step size is set to `0` with numpy's `arange` then this will occur:

```
In [1]: from numpy import arange

In [2]: arange(2,2,0)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-12770fdc4f48> in <module>()
----> 1 arange(2,2,0)

ZeroDivisionError: division by zero
```

Based on your code, it appears that `z_min` was set to `4` at some point causing `z_max - z_min` to evaluate to 0.

**Comment by nicocarbone** [comment]
`z_min` is set to `0`, not `4`

The problems seems to be that in jupyter notebook z_min, z_max and z_size are considered float and in nteract the are int. When doing `(z_max-z_min)/z_size` it evaluates to 0, and not 0.2 because it is done in integer math.

Maybe this is the correct behaviour, but the difference seems to come from using nteract and not jupyter notebook

**Comment by rgbkrk** [comment]
This sounds like your kernel is actually running Python2. If you run:

```
import sys
print(sys.version_info)
```

What do you see?

**Comment by rgbkrk** [comment]
Also, run `jupyter kernelspec list --json` at the command line

**Comment by nicocarbone** [comment]
You are right. I am running python 2: `sys.version_info(major=2, minor=7, micro=15, releaselevel='candidate', serial=1)`
However, I should be running python 3 as this is a python3 notebook and nteract gui reports python 3 (on the lower left corner). Am I doing something wrong?

Here is the output of `jupyter kernelspec list --json`:

```
{
  "kernelspecs": {
    "python2": {
      "resource_dir": "/home/nicolas/.local/share/jupyter/kernels/python2",
      "spec": {
        "argv": [
          "/usr/bin/python2",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 2",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    },
    "python3": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}
```

**Comment by rgbkrk** [comment]
If you edit `/usr/local/share/jupyter/kernels/python3/kernel.json`'s `argv` section to be `python3` this will work. When the app loads (especially on Mac), we're subject to how your operating system views paths -- so when we run `python -m ipykernel_launcher -f {connection_file}` it's up to the system to evaluate it. Replace that with `python3` and it should be good to go. Even better is to specify the absolute path to the Python3 you want to work with.

**Comment by nicocarbone** [comment]
Great, that did the trick (I am on Ubuntu, not Mac, but I guess the problem is the same).

So, the bug is in whatever created that json file? I think it was created by pip when I installed pyhton 3.
Thanks you!

**Comment by rgbkrk** [comment]
Yeah, I suppose via ipython. Cc @Carreau

**Comment by Carreau** [comment]
Happy you figured it out. Not sure how you ended up with a Python 3 kernel pointing to a Python 2 one, sorry about that. 

@rgbkrk the classic notebook print the kernel info request when doing `help`>`about` would something similar in nteract help debug this kind of info ? Like when you hover the kernel name ?

**Comment by rgbkrk** [comment]
> Not sure how you ended up with a Python 3 kernel pointing to a Python 2 one, sorry about that.

If it's `python` then it's whatever the system thinks is `python`, because of how OSes run native apps. When a kernel gets installed on disk, it should use either the absolute path or include the python version number (at least the X in pythonX.Y).

We do shell out to use the user's general shell environment on startup -- if `python` is really `python2` though, we're stuck as we're just running directly what the `argv` is specified as.

> the classic notebook print the kernel info request when doing help>about would something similar in nteract help debug this kind of info ? Like when you hover the kernel name ?

We could do that. We show the kernel name in the lower left using that kernel info response and do have all that data.
