### ISSUE TITLE
Jupyter extensions in jupyter nteract notebooks

### ISSUE THREAD

**Issue by e184633** [nteract/archived-desktop-app#3269]
The work you have done is outstanding! Is there any way to include some jupyter extensions in nteract notebooks? Like codefolding or scratchpad or table of content? Thanks in advance for your time.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @e184633!

Unfortunately, at the moment, nteract doesn't support Jupyter extensions. We do have design work in mind to support the table of contents feature by default but nothing to address the others.
