### ISSUE TITLE
Toggle Markdown Cell Output

### ISSUE THREAD

**Issue by n-russo** [nteract/archived-desktop-app#3273]
Currently markdown cells have no ability to toggle their output to expand/collapse. The default behaviour seems to be to collapse large content cells and provide a scrollable cell. While this is useful for editing it is not useful for a final product and unusable for exporting to PDF.

I found a previous issue that provided a fix to expand all output when exporting to PDF but this doesn't seem to extend to markdown cells. The result is a snapshot of the collapsed cell exported.

Is it possible to introduce the ability to toggle output similar to the behaviour of code cells. I'm using ubuntu 18.04 and the latest .appimage file.

Very new to nteract so forgive me if I've failed to appreciate the reason for this.

**Comment by willingc** [comment]
Hi @n-russo,

I'm triaging open issues right now. I'm going to close this issue and track the behavior of markdown cells in #3073.

Thanks for the suggestion 👍
