### ISSUE TITLE
Ctrl+C in terminal which launches nteract yields orphaned kernel processes

### ISSUE THREAD

**Issue by jameskoch2** [nteract/archived-desktop-app#3275]
nteract 0.11.6

1. On Windows, launching nteract from a terminal, with a Python3 kernel, Ctrl+C will shutdown all nteract.exe processes but not python.exe
a. Notably - The terminal seems partially-connected to nteract in an odd way. It receives stdout/stderr. If I press ENTER one time, I get back to a command prompt. Then I can still Ctrl+C and it kills nteract.exe.
2. On Mac, terminal returns immediately after launching nteract via the shell extension, but using `kill -2` to send SIGINT I see the same behavior of an orphaned kernel process

Poking around the code, I noted execa is the subprocess library used inside spawnteract, and they seem to offer some support here - https://github.com/sindresorhus/execa#cleanup

**Comment by willingc** [comment]
Closing this issue as it seems to be addressed by: https://github.com/nteract/spawnteract/pull/31
