### ISSUE TITLE
"Need to implement a way to shutdown non-zeromq kernels on desktop" when closing a new/untouched notebook

### ISSUE THREAD

**Issue by jameskoch2** [nteract/archived-desktop-app#3277]
macOS - 0.11.6

Just closing the default "Unititled" notebook that opens when you launch the app is met w/ a msgbox "Need to implement a way to shutdown non-zeromq kernels on desktop"

https://github.com/nteract/nteract/blob/26a6a30bb9ee78713393c455fbdf1a442695e6fa/applications/desktop/src/notebook/global-events.js#L15-L28

**Comment by rgbkrk** [comment]
Thanks for reporting this so that I'd tackle it before today's release. "fixed" in #3312.

As a bit of a meta issue we need some tooling to help us discover kernels on disk and register them as available.
