### ISSUE TITLE
commuter show "200 | OK"

### ISSUE THREAD

**Issue by muik** [nteract/archived-desktop-app#3286]
I just install commuter on my mac.
```
npm install @nteract/commuter -g
```

and run commuter.
```
commuter
```

then browse commuter.
```
open http://127.0.0.1:4000
```

but I can see only this message "200 | OK".

<img width="529" alt="2018-09-04 3 24 32" src="https://user-images.githubusercontent.com/775121/45013773-546ef000-b057-11e8-8a26-5cc94901cf35.png">

What can I do for reading my notebooks by commuter?

**Comment by muik** [comment]
I found the error message. same https://github.com/nteract/nteract/issues/3253

**Comment by rgbkrk** [comment]
This should be good to go now, we fixed up the babel issues with commuter and shipped a new version.
