### ISSUE TITLE
Running commuter fails on windows

### ISSUE THREAD

**Issue by niderhoff** [nteract/archived-desktop-app#3292]
`npm run app:commuter` fails on windows due to the following error:

```plain
$ NODE_ENV=development node lib.index.js
The command NODE_ENV is either misspelled or could not be found.
```

This is because environment variables have to be set with `set NODE_ENV=development&& node lib/index.js` on windows.
I think there needs to be a platform check implemented and the environment variable set accordingly to the platform. However, I am not a node expert.

**Comment by rgbkrk** [comment]
I think what we have to do for windows with this is change the `dev` command to be:

```
    "dev": "cross-env NODE_ENV=development node lib/index.js",
```

within `applications/commuter/package.json`. The same goes for the `start` command. `cross-env` is already installed in the monorepo so this should be a nice new contribution to commuter. Would you like to try that and make a PR?

**Comment by niderhoff** [comment]
Hey, that particular error message is now gone due to your proposed change. Will file a PR when I ran some tests. However, there is still other errors when trying to run commuter (a lot of missing dependencies) such as

`@nteract/webpack-configurator @nteract/directory-listing @nteract/markdown @nteract/notebook-preview @nteract/presentational-components @nteract/transform-vega @nteract/transforms`

which are not installed when you run `npm install` on the repository-level. So the installation instructions in the [readme.md](https://github.com/niderhoff/nteract/tree/master/applications/commuter#quick-start) are not really accurate.

Shouldn't these be installed automatically?

Also a lot of the tests fail due to missing dependencies.

**Comment by rgbkrk** [comment]
Ah! We're now using `yarn` as it helps us manage workspaces within the monorepo effectively. From the root level, run `yarn`. I've updated the README in #3321.

**Comment by rgbkrk** [comment]
What I'd probably do, from the base of the repo is:

```
yarn clean # could be optional, yarn below may fix it up
yarn
```

**Comment by niderhoff** [comment]
So that makes sense, yeah. It worked when I manually installed the dependencies (kind of). I hope I'll get around to testing it again so we can implement this.

**Comment by satishvad** [comment]
What are the steps for running commuter on a windows system. I tried to follow the instructions, but first got an error saying npm was missing package.json. Then I used npm init to create the package.json. But, now I am getting  missing script: app:commuter. Please can you provide steps on how to run commuter on a windows machine.

**Comment by captainsafia** [comment]
Closing since it is stale and commuter is in a separate repo now.
