### ISSUE TITLE
Write up how to contribute to the styleguide (components.nteract.io)

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3294]
In the README and in other local docs of our monorepo, we need to show people how to contribute new documentation for components.

Two flavors I'm thinking of:

* I want to improve documentation for an existing component
* I want to document a new component that's not showing up

As a first pass the README should show the `yarn docs` command as well as references to the styleguide config + styleguidist docs.

**Comment by willingc** [comment]
Closing now that https://github.com/nteract/docs/issues/40 has been closed. Additional tips and docs that may be needed can be reported here: https://github.com/nteract/docs/issues
