### ISSUE TITLE
Title bar shows wrong name

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#330]
<img width="812" alt="title" src="https://cloud.githubusercontent.com/assets/1448859/14649547/ea4816b6-0667-11e6-8c29-5d2d561626d1.png">

Open notebook via File -> Open used it a bunch, used a lot of CPU, killed kernel, started new one, rinse and repeat. At some point I noticed that the title bar of the window had changed to this. Can't reproduce it though. There is some output in the console, unsure when during my usage it appeared.

<img width="799" alt="console" src="https://cloud.githubusercontent.com/assets/1448859/14649706/9797c5f0-0668-11e6-81c6-f23c53713dc4.png">

This is with 0034e2afdd5

Should we keep this open or close it because even I don't know how to reproduce the bug?

**Comment by rgbkrk** [comment]
Wowsers. We're going to have to learn how to profile electron apps.

**Comment by jdfreder** [comment]
I was able to reproduce the first error in the console once.  I haven't been able to reproduce it since.  Seems like a problem with kill kernel / launching a new kernel.

**Comment by jdfreder** [comment]
Killing a kernel, then starting a new one also doesn't update the title correctly.  I can reproduce that constantly.  For example

run 

``` python
while True:
    pass
```

Language->Kill Running Kernel
Language->Python 3

The title bar will still say `busy` even when executing other cells.

**Comment by jdfreder** [comment]
I've also noticed the title bar getting stuck on `not connected`, despite a connected kernel.

**Comment by rgbkrk** [comment]
I think this one has been sorted out with our current startup flows and epics. Feel free to re-open if you're still seeing it.
