### ISSUE TITLE
Desktop App Kernel Configuration Question

### ISSUE THREAD

**Issue by Walter0807** [nteract/archived-desktop-app#3303]
It's said that Jupyter kernels on local system are supported. But I'm having troubles deploying them.

I selected python3 but still get this:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/25319568/45252579-5f918b00-b38b-11e8-90f1-8966b48e9b39.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/25319568/45252587-89e34880-b38b-11e8-8916-11025ed2c2b7.png">

It seems that custom kernels are not recognised and I don't understand how to configure them manually. These kernels work well in the web version of nteract. 

Besides, is it possible to add tab bar support in the desktop version?

Thank you developers and designers for nteract is definitely the most elegant Jupyter application. I sincerely hope it would become better.

**Comment by willingc** [comment]
Hi @Walter0807, 

We've recently improved our kernel documentation: https://nteract.io/kernels 

This page also links to the following Jupyter information on installing kernels: https://ipython.readthedocs.io/en/stable/install/kernel_install.html

There's additional information available here: https://docs.nteract.io/#/concepts/kernels

Hope this helps.
