### ISSUE TITLE
Data Explorer: Data Table order changes on switching back from other data visualizations 

### ISSUE THREAD

**Issue by gokriznastic** [nteract/archived-desktop-app#3305]
**The order of rows in the Data Table view changes based on the order of data points in other visualizations like Bar Chart or Scatter Plot.** 

Here is an example:
Initially the notebook looks something like this:
![happiness ipynb nteract](https://user-images.githubusercontent.com/14166854/45258932-44e90180-b3df-11e8-97c4-e76168cfced3.png)

After using the Bar Chart view which looks something like this:
![happiness ipynb nteract2](https://user-images.githubusercontent.com/14166854/45258939-7530a000-b3df-11e8-8f65-de0440b078e1.png)

On switching back to Data Table view the rows get arranged in a similar fashion as in the previously used plot:
![happiness ipynb nteract3](https://user-images.githubusercontent.com/14166854/45258947-a7420200-b3df-11e8-9712-322188563d35.png)

This tends to happen only while the switch is made between Data Table and Bar Chart. The changes do not reflect on switching between Data Table and other plots like Scatter Plots, Hexbins etc. I realize that this is the result of keeping metrics consistent between different plots or visualizations. But, I believe this may be producing erroneous arrangements such as above sometimes.

**Comment by emeeks** [comment]
I didn't change anything with the sorting code but it seems like the change to react-table in #3322 seems to have fixed this behavior (likely because react-table is sortable and so has a default sort).
