### ISSUE TITLE
Data Explorer: Bug in Line Chart plot

### ISSUE THREAD

**Issue by gokriznastic** [nteract/archived-desktop-app#3306]
The labels in the legend of the Line Chart plot tend to overlap on the plot toggles and other elements of the cell when the labels are long strings. A horizontal scroll bar seems missing.

**Comment by emeeks** [comment]
Should be fixed with #3322 in that the viz area should be sized correctly now (no horizontal scrolling) and the viz type buttons are now rendered over the legend in case there's overlap.
