### ISSUE TITLE
Data Explorer: horizontal scroll bar missing in Data Table

### ISSUE THREAD

**Issue by gokriznastic** [nteract/archived-desktop-app#3307]
The horizontal scroll bar doesn't appear till an upward scroll is made in the vertical scroll bar or the table is clicked upon.

**Comment by emeeks** [comment]
Not sure that this is a bug, per se, though it should be better with #3322. The scrollbar not appearing until scrolling is just the way most browsers do it now, unless I'm misunderstanding the issue.

**Comment by emeeks** [comment]
(feel free to reopen if you feel like something is still not right)
