### ISSUE TITLE
Data Explorer: Bug in Data Table view on scrolling

### ISSUE THREAD

**Issue by gokriznastic** [nteract/archived-desktop-app#3309]
The column names remain static when the horizontal scroll bar is used resulting in a broken Data Table like this:
![happiness ipynb nteract4](https://user-images.githubusercontent.com/14166854/45259274-67cae400-b3e6-11e8-8780-4bb49c8ce6ee.png)

**Comment by emeeks** [comment]
Should be fixed with #3322
