### ISSUE TITLE
plotly tables not working

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3323]
I think there's an issue using plotly's table type in nteract.

Here's a Python example:
```
import IPython
import plotly
import json

layout = {}

# This is adapted from Plotly's example at https://plot.ly/javascript/table/
bundle = {}
bundle['application/vnd.plotly.v1+json'] = {
'data': [{
  "type": "table",
  "header": {
    "values": [["EXPENSES"], ["Q1"],
				 ["Q2"], ["Q3"], ["Q4"]],
    "align": "center",
    "line": {"width": 1, "color": "black"},
    "fill": {"color": "grey"},
    "font": {"family": "Arial", "size": 12, "color": "white"}
  },
  "cells": {
    "values": [
      ["Salaries", "Office", "Merchandise", "Legal", "TOTAL"],
      [1200000, 20000, 80000, 2000, 12120000],
      [1300000, 20000, 70000, 2000, 130902000],
      [1300000, 20000, 120000, 2000, 131222000],
      [1400000, 20000, 90000, 2000, 14102000]],
    "align": "center",
    "line": {"color": "black", "width": 1},
    "font": {"family": "Arial", "size": 11, "color": ["black"]}
  }
}],
'layout': {},
}

IPython.display.display(bundle, raw=True)
```

Here is the same JSON pasted into CodePen and working in plotly - https://codepen.io/anon/pen/yxEPNz

Not a big deal as I think we can fall back to use dataresource.

**Comment by rgbkrk** [comment]
Hmmm... this may require a newer version of plotly. I've not seen this table type before with plotly.js.

cc @jackparmer

**Comment by jackparmer** [comment]
Yes, SVG tables were introduced back in October 2017

https://github.com/plotly/plotly.js/releases/tag/v1.31.0
https://plot.ly/python/table/

Not sure which version of plotly.js is shipping with nteract currently

**Comment by rgbkrk** [comment]
Ah sure enough, I forgot we made a vendored copy of plotly so that we could have a trimmed down build. I'll post an issue over on nteract/minimal-plotly.

**Comment by willingc** [comment]
@jameskoch I'm going to close this here and I've opened https://github.com/nteract/minimal-plotly/issues/7 to move the release to npmjs along and to track the remaining item from this issue. Thanks for your patience.
