### ISSUE TITLE
Data Explorer: Multi-column primaryKey renders in table view with single "fixed" column

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3324]
Seems like it should render all primary keys as gray, shaded, "fixed"-looking.

Example:
```
import IPython
import json

layout = {}

# This is adapted from Plotly's example at https://plot.ly/javascript/table/
bundle = {}
bundle['application/vnd.dataresource+json'] = {
      "schema": {
        "fields": [
          {
            "name": "Key1",
            "type": "string"
          },
          {
            "name": "Key2",
            "type": "string"
          },
          {
            "name": "Value",
            "type": "number"
          },
        ],
        "primaryKey": [
          "Key1",
          "Key2"
        ]
      },
      "data": [
        {
          "Key1": "FOO",
          "Key2": "BAR",
          "Value": 0.8089744197263983,
        },
      ]
}

IPython.display.display(bundle, raw=True)
```

**Comment by rgbkrk** [comment]
Great idea, thanks for bringing that one up.

**Comment by emeeks** [comment]
Added in #3330

**Comment by rgbkrk** [comment]
I don't think this is fixed.

![screen shot 2018-09-14 at 5 09 11 pm](https://user-images.githubusercontent.com/836375/45579992-f0131400-b840-11e8-964c-bb135243fff8.png)

I have `Country` and `Region` set as primary keys here and they're not showing up fixed and gray on the left.

**Comment by emeeks** [comment]
Check to make sure you've reenabled the FixedColumnHOC component and it's not just rendering ReactTable.

**Comment by emeeks** [comment]
#3331 re-enables the fixed column wrapper HOC that will make fixed columns work again.
