### ISSUE TITLE
Automatic Code Completion in Julia

### ISSUE THREAD

**Issue by padmer** [nteract/archived-desktop-app#3340]
The suggested completions appear when I press Ctrl-Space. But when I want to accept a suggestion (pressing enter, tab or right arrow key) it doesn't overwrite the initial search string.
Example:

Type "pri" and press Ctrl-Space
Select "print" from the list using the down arrow key and hit Enter
autocompleted to: "priprint"

I have tried with Node.js and there is no problem, I have also tried julia in atom running hydrogen and there is no problem.

**Comment by jumerckx** [comment]
I've got the same problem in Julia on Ubuntu 18.04

**Comment by willingc** [comment]
If someone has time to reproduce with the latest nteract release 0.12.3 and the latest Julia kernel (1.0+), we would appreciate the help.

**Comment by jumerckx** [comment]
I can confirm this issue on my machine with Julia 1.0.1 and nteract 0.12.3.

**Comment by willingc** [comment]
Thanks @merckxiaan for the confirmation.

**Comment by willingc** [comment]
Closing this issue as it is a duplicate of #2929. I've also verified that this is a bug.
