### ISSUE TITLE
<Output> Picker

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3342]
Next steps for the `@nteract/outputs`:

* [x] Write our "official" output components that would handle all the output types just like what we previously handled in `packages/display-area/src/output.js`
  * [x] `<ExecuteResult>`
  * [x] `<DisplayData>`
  * [x] `<Traceback />` (or call it `<JupyterError />`
  * [x] `<Stream />`
* [x] Create `<Media />` components for all the transforms (or adapt them to the new style which only needs adding a `mediaType` key) 
* [ ] Extract styles out of `packages/presentational-components/src/components/outputs.js` that belong in the respective media or outputs, possibly packaged as:

```js
export userOutputStyle = css`
  .userOutput :global(table) {
    /* yay css */
  }
`;
```

then use them in `<Media.HTML />` and `@nteract/markdown`'s markdown.

* [x] Integrate the Output picker, RichMedia, and all these components into the notebook app component
* [ ] Deprecate `@nteract/display-area`

**Comment by rgbkrk** [comment]
The big "why" on this effort is to make it so that a cell effectively looks like this in the React Tree:


```jsx
<Cell>
  <Input>
    <Prompt counter={1} />
    <Source language="python">{`import pandas as pd\npd.DataFrame([1,2,3])\n\n# Alternate between hovering the cursor over this cell and outside of the cell`}</Source>
  </Input>
  <Outputs>
    {outputs.map(output => (
      <Output>
        <DisplayData>
          <DataExplorer onMetadataChange={handleMetadataUpdate} />
          <Media.HTML isolated />
          <Media.Image mediaType="image/gif" />
          <Media.Image mediaType="image/jpeg" />
          <Media.Image mediaType="image/png" />
          <Media.Text />
        </DisplayData>
        <KernelOutputError />
        <StreamText />
      </Output>
    ))}
  </Outputs>
</Cell>
```

This lets frontends pass in what they want to use for output types and for handling media types, including any `onChange` handlers.

**Comment by captainsafia** [comment]
Here's a breakdown of the transforms that need to be migrated to `Media` components that we can track.

**Components**
- [X] HTML
- [X] Image
- [x] JavaScript (@captainsafia)
- [X] JSON
- [x] LaTeX (@lgeiger)
- [X] Markdown
- [X] SVG
- [X] Plaintext

**Documentation**
- [x] HTML (@captainsafia)
- [X] Image
- [x] JavaScript (@captainsafia)
- [x] JSON (@captainsafia)
- [x] LaTeX (@lgeiger)
- [x] Markdown (@captainsafia)
- [x] SVG (@captainsafia)
- [x] Plaintext (@captainsafia)

I tagged myself in some of the stuff I'll be working on.

**Comment by lgeiger** [comment]
Thanks Safia! I'll tackle the LaTeX component.

**Comment by rgbkrk** [comment]
Now that commutable is all records and everything is typescriptified, I think we can adapt to this new API much more easily now.

The only big question we have is if we should convert from `snake_case` to `camelCase` (or the inverse). Right now `commutable` is using `snake_case` for outputs (matching up with jupyter format) and this new `@nteract/outputs` API uses `camelCase`.

**Comment by rgbkrk** [comment]
Wahoo!
