### ISSUE TITLE
Error Save ipynb

### ISSUE THREAD

**Issue by thomaspernet** [nteract/archived-desktop-app#3352]
Hi, 

I'm trying to save the notebook but it fails to save. There is an exclamation mark right beside "Last save x minutes ago". 

Although, I added codes to the file. How can I fix the issue? 

I read another issue saying there is an automatic save. Does this feature work for Nteract in the web browser? 

Thanks

**Comment by willingc** [comment]
Hi @thomaspernet,

Are you seeing this behavior with the latest release, 0.12.3 ? If so, it would be helpful to have additional information on what is happening.
