### ISSUE TITLE
Data explorer: Language agnostic API

### ISSUE THREAD

**Issue by kylebarron** [nteract/archived-desktop-app#3359]
@alexandercbooth

I could be interested in trying to get the data explorer to work with non-Python languages, at least R. I just wanted to start this issue to track progress in that regard.

**Comment by emeeks** [comment]
Let me know if I can help with anything.

**Comment by davidanthoff** [comment]
It used to work with all the packages in https://www.queryverse.org/ on the julia side, but right now is broken due to https://github.com/nteract/nteract/issues/3491. I assume that that should be a fairly simple fix and then things should work again on that end.
