### ISSUE TITLE
[menu] Add Runtime, Restart and Run All

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3367]
Coming from classic Notebook, this feature seems to be missing.

#2727 describes jupyter_extension variant of this

I'd like to take a swing at this myself.

**Comment by jdetle** [comment]
Happy to help with this if you want to pair on it.

**Comment by jameskoch** [comment]
I may take you up on that as my JS muscles have atrophied over a few years, and I'm new to redux-observable. Going to struggle through it a bit on my own then will reach out. Thanks!

**Comment by jdetle** [comment]
@jameskoch okay. You'll probably want to have a basic understanding around https://github.com/nteract/nteract/tree/master/applications/desktop/src and https://github.com/nteract/nteract/tree/master/packages/core/src to make the relevant changes.
