### ISSUE TITLE
Buffer cell evaluations while kernel is starting

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3368]
I've got a slow-to-start kernel (thanks, Scala!).

While the kernel is starting, evaluation of a cell using Command/Shift+Return seems to no-op. It would be better if it the cell were marked as running, and the request was queued up to be sent to the kernel once it's idle (this seems to be how classic Notebook works).

Imagine restarting your kernel and quickly queuing up recalculation of a chain of cells in the middle of your notebook; just whack Shift+Return a bunch while you're waiting for things to come alive.

This behavior might further be useful internally in implementing #3367 (Restart and Run All). With the disclaimer that I'm new to this stack, it seems like this would allow us to emit RESTART_KERNEL immediately followed by EXECUTE_ALL_CELLS, without needing to wait for a LAUNCH_KERNEL_SUCCESSFUL.

**Comment by jameskoch** [comment]
I've switched over to using the jupyter-extension, and can not reproduce this issue there. So either it's specific to desktop, or the issue has been resolved.

**Comment by captainsafia** [comment]
Closing this in favor of #4762 where a proposed implementation strategy is outlined.
