### ISSUE TITLE
Data Explorer not displaying any charts other than line

### ISSUE THREAD

**Issue by satishvad** [nteract/archived-desktop-app#3371]
All of a sudden, nteract data explorer will not switch between different chart views. It worked, but suddenly stopped. I do not recall upgrading any packages to throw thing out of sync. I click on them and do not do anything at all. I am using Python 3.7 and Windows 10.

![image](https://user-images.githubusercontent.com/12848729/46207291-d8359880-c2f4-11e8-9d5e-d394db9445f8.png)

**Comment by emeeks** [comment]
@satishvad do you have any more details about this? Could you post the `ipynb` that shows this issue?

**Comment by emeeks** [comment]
Going to close this based on lack of reproducibility and age.
