### ISSUE TITLE
Nteract native on Ubuntu does not work

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [nteract/archived-desktop-app#3373]
Hello,
I am running the Ubuntu AppImage version of nteract. I have jupyter install on my machine that works perfectly. If get the following error on nteract and no output from the cells

![image](https://user-images.githubusercontent.com/15908060/46219388-89651e80-c347-11e8-9ade-cf52bf61067b.png)
Any help?

**Comment by FrancescoSaverioZuppichini** [comment]
Also, I get the following error when I open nteract:
```
/usr/bin/python: No module named ipykernel_launcher
```

**Comment by step21** [comment]
For me, it just says "Python3 | launching" on startup and also when loading example notebooks.  This was the same with the native install and the appimage. No other output is given on console, in the developer console the error is the same as above. This was on Ubuntu as well. (18.04)
I really hope things like this get logged to the console/stdout in the future, that's what it's there for, without having to open the screen distorting dev console.

**Comment by FrancescoSaverioZuppichini** [comment]
I just remove it, it was never working!

**Comment by willingc** [comment]
In addition to installing nteract for Ubuntu appimage, one would also need to install the ipykernel. See additional information [here](https://nteract.io/kernels).

I'm going to close this issue. Thanks.
