### ISSUE TITLE
Remove that hidden vega optional dep

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3379]
As has been pain for us over the last year or so, all the vega dependencies rely on `canvas` as an optional dependency. It's been annoying because _sometimes_ it seems to trip up the CircleCI build and generally confuses contributors to the project as it mixes error messages in what's typically a successful build. For those of us with systems that `canvas` builds just fine on, it makes the build longer.

Since we currently have to have vega2, vega3, vega-lite 1, and vega-lite 2, due to supporting each of the vega media types, I've been thinking that we could just make our own trimmed down forks of each of these (as well as `vega-embed`). I think newer versions of vega (v4) no longer have this issue, as they use canvas-prebuilt.

I'm opening this issue to start tracking some of the relevant issues to this and come up with a plan to handle this.

* https://github.com/vega/vega/issues/1073
* https://github.com/vega/vega-embed/issues/15

**Comment by lgeiger** [comment]
This has been bugging me for a long time. I'll give it a shot.
