### ISSUE TITLE
Desktop status bar shows no feedback until kernel process is running

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3417]
I've got a slow-starting kernel for reasons I won't go into here.

The status bar in the bottom left doesn't actually change until the kernel process is up, which leaves users wondering if things are progressing.

The "launching" state set in [this reducer](https://github.com/nteract/nteract/blob/54c50e856930e9489e9b920365dacc3f10320af4/packages/core/src/reducers/core/entities/kernels.js#L47-L49) is never rendered.

A proximate cause is that that reducer's call to setIn just ends up creating an Immutable `Map` for our newly-generated kernelRef, rather than a full `LocalKernelRecord` (that gets set later). If I modify the status-bar to check `kernel.get("status")` for the Map case, in addition to the already-checked `kernel.status` for the record case, then I get _closer_ to the feedback behavior I desire. I am still looking around the code for a more redux-idiomatic way to resolve this (always generating the skeleton KernelRecord rather than creating a Map); hints are welcomed 😄 .

This surfaces another issue in that during launch I'm shown `Kernel Display Name | launching` and then once it's live I see `kernel-folder-name | idle`, yielding an odd bit of flicker. Actually, looks like there's already a [TODO in this space](https://github.com/nteract/nteract/blob/8ef408e7d2f2203cf6feb422f04da9f021837c3f/packages/notebook-app-component/src/status-bar.js#L87-L88).

**Comment by jameskoch** [comment]
I'll share a PR for this shortly where I patch up the core kernel reducer only, to produce an Immutable.Record w/ a state field instead of a Map, during launch.

This still feels sub-optimal, but I struggled to find a more elegant solution due to the many different ways in which kernels are launched, with different info available at slightly different times for websocket vs. ZMQ kernels, and the strong local-vs-remote type difference currently modeled. I'll will look at it w/ fresh eyes in the morning.

**Comment by captainsafia** [comment]
Sounds good! Looking forward to reading your PR.

**Comment by rgbkrk** [comment]
We definitely want to move away from `Immutable.Map` in favor of `Immutable.Record` so that's great. Thank you for finding and fixing these inconsistencies. Our transition over from desktop to web (and remote kernels) has not been a full clean sweep. 😬  I'm extremely grateful you keep coming back and making it better.

**Comment by jameskoch** [comment]
Closed by #3456
