### ISSUE TITLE
how run normal OS commands from the editor

### ISSUE THREAD

**Issue by veeramarni** [nteract/archived-desktop-app#3432]
I want to understand how we can run some `OS` commands from the editor and can see the ouput?
For example, I'm trying here with `ls` command and opening to see an valid output. Or run any commands that the OS that was hosting the `nteract` editor should work.

![image](https://user-images.githubusercontent.com/3382355/46871289-f3c59680-cdfe-11e8-9985-fb270f559649.png)

**Comment by rsnk96** [comment]
Hi @veeramarni . Running the shell command with an exclamation mark as the start should work, i.e. `!ls -ltr` instead of `ls -ltr`

![image](https://user-images.githubusercontent.com/10851575/46895190-fe326f80-ce94-11e8-905f-14acfea8730e.png)

Feel free to post here if you are still facing issues

**Comment by veeramarni** [comment]
Still, see the issue. 

![image](https://user-images.githubusercontent.com/3382355/46900170-06c28000-ce6c-11e8-98f9-a4dc47c68c71.png)

**Comment by rgbkrk** [comment]
If we don't detect a Python kernel installed, the default kernel is the built in node.js kernel. You may need to [install your conda and Anaconda environment as a kernel](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments).
