### ISSUE TITLE
Prompt to relaunch when saving notebook to new location not triggered in several cases.

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3433]
I've been unable to exercise [this](https://github.com/nteract/nteract/blob/639cca263105a947cfffbd9ea60f88ffd4f9a66d/applications/desktop/src/notebook/menu.js#L117) `promptUserAboutNewKernel` method on macOS.

Tried two workflows and neither worked:

1. `Save As`an already-saved notebook
  - Call stack here is `dispatchSaveAs` -> `store.dispatch`. I can't see how this would ever trigger the non-exported `promptUserAboutNewKernel` call path.
2. `Save` a brand new notebook
  - Call stack seems close to correct, `dispatchSave` intends to call `triggerSaveAs` (which in turn calls `promptUserAboutNewKernel`) if there's no current file path. However this fork of code only runs when the current filename is null and in my experience it is always an empty string, so I just get an error.

**Comment by rgbkrk** [comment]
I noticed that triggering save as broke within the last couple releases, this is definitely a regression.
