### ISSUE TITLE
No .bind() or Arrow Functions in JSX Props

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#3435]
We should remove the use of `.bind()` and arrow functions in JSX props:
> A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary. It may also cause unnecessary re-renders if a brand new function is passed as a prop to a component that uses reference equality check on the prop to determine if it should update.

This can be easily enforced by adding the [`react/jsx-no-bind` rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md) to our ESLINT config.

Arrow functions inside props can be avoided by using [class properties](https://reactjs.org/docs/faq-functions.html#class-properties-stage-3-proposal).

Arrow functions for assigning `refs` can be replaced by using the new [`React.createRef` API](https://reactjs.org/docs/react-api.html#reactcreateref).

These are some small improvements we can make to our components, in order to improve performance in some cases. See #3434

**Comment by showmeyourhits** [comment]
Howdy. I would like to work on this issue. Can i work on this issue?
~Little tautology never hurt nobody.~

**Comment by lgeiger** [comment]
> Howdy. I would like to work on this issue. Can i work on this issue?

That's awesome. Great to have you onboard @showmeyourhits 🎉 

Feel free to jump on our slack if you have any questions: http://slack.nteract.io

**Comment by Ankk98** [comment]
@showmeyourhits You are working on this issue?
If not I would like to work on it.

**Comment by lgeiger** [comment]
@Ankk98 Thanks for your interest in contributing to nteract.
Do you want to give #3471 a shot if @showmeyourhits is still working on this issue?

**Comment by showmeyourhits** [comment]
Howdy. @lgeiger, yep, still working.
Please, check #3474 for review.

**Comment by captainsafia** [comment]
This can be closed. While updating this issue for Hacktoberfest, adding the jsx-no-lambda and jsx-no-bind rules to tslint flagged no issues.
