### ISSUE TITLE
Add eslint-plugin-react-perf rules to our ESLINT config

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#3440]
Objects created at render time will often cause a re-render when passed down as a prop, even if they have the same content. We need to reduce this usage especially for critical paths. See #3434

To enforce this, we should add the [`eslint-plugin-react-perf`](https://github.com/cvazac/eslint-plugin-react-perf) rules to our ESLINT config. Which prevent patterns like `<Item config={{foo: "bar"}} />`.

**Comment by max-arias** [comment]
Hey @lgeiger , I'm interested in this one. Mind if I grab it?

**Comment by lgeiger** [comment]
@max-arias That's awesome! Welcome on board 🎉

**Comment by hydrosquall** [comment]
Whoa, didn't know about this rule! Thanks @lgeiger
