### ISSUE TITLE
Data Explorer table text not very readable in Dark theme

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3461]
I'd been toying w/ dark theme; no idea how seriously you folks wish to support it but...

**Application or Package Used**
nteract desktop, with dark theme enabled.

**Describe the bug**
Text foreground color (`rgb(217, 217, 217)`) is a bit pale/muted against the table's still-white background.

**Screenshots**
<img width="102" alt="screen shot 2018-10-18 at 2 39 14 pm" src="https://user-images.githubusercontent.com/168110/47176476-b0c66000-d2e3-11e8-90cc-0a8adbb93a6f.png">

**Desktop (please complete the following information):**
macOS

**Comment by aaronraff** [comment]
I would be interested in picking this one up if it is still open!

**Comment by jameskoch** [comment]
Go for it!  @emeeks would probably be your man for any questions specific to Data Explorer.

**Comment by emeeks** [comment]
@aaronraff Yeah just let me know if you have any issues, happy to review or jump in.
