### ISSUE TITLE
Add missing dependencies to our packages

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#3471]
One of the inherit problems when developing packages in a monorepo is that it's easy to forget to include all necessary dependencies in the respective `package.json` files. This often leads to bugs when people are trying to use  our packages outside the context of the monorepo.

We should enforce proper declaration of dependencies by adding the [`import/no-extraneous-dependencies`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) ESLINT rule to the repo and fix the issues it catches.
For this we probably need to ignore our `__test__` directories since, dev dependencies are currently declared in the root `package.json`.

Note: One convention we currently follow is to require `react`, `react-dom` and `immutable` as `peerDependencies` rather than `dependencies`.

**Comment by jamessral** [comment]
I'd love to take a crack at this if that's alright

**Comment by lgeiger** [comment]
> I'd love to take a crack at this if that's alright

That's awesome!

You might want to checkout #3472 since it already adds the plugin as a dependency. Thus you'd only need to add the rule to the config to get started.

**Comment by lgeiger** [comment]
@jamessral #3472 is now merged into master, all set to go 🎉
