### ISSUE TITLE
Idea to enhance nteract with js/css plugins

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/archived-desktop-app#3480]
There's an idea to create a new online publishing experience: [Idea to enhance nbviewer with js/css plugins to make nbviewer+ipynb secure, dynamic and mobile friendly (Jupyter notebooks as PDF, MS Word and others killer)](https://github.com/kiwi0fruit/misc/blob/master/src/pdf_and_word_killer.md) (related issue: https://github.com/jupyter/nbviewer/issues/778)

If it would ever come to existence then it would be nice to have same js/css plugins support in nteract. Nbviewer is a js+html when nteract is js+html+python.

Or may be somebody here would be interested in the idea...

**Comment by willingc** [comment]
HI @kiwi0fruit,

I'm going to go ahead and close this issue. Please feel free to open a more specific issue when a particular publishing platform would benefit from an nteract plugin. :sunny:

[ref](https://github.com/jupyter/nbviewer/issues/778#issuecomment-417873446)
