### ISSUE TITLE
blueprint styled jsx is affecting global styles

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3489]
**Application or Package Used**

nteract desktop & nteract web

**Describe the bug**

Any component that uses blueprint.js' css via styled-jsx will affect the rendering of markdown blocks.

**To Reproduce**

* Make a markdown cell.
* Display some data with the data explorer, use the heatmap.
* Watch the text rendering and other CSS change.

**Expected behavior**

CSS doesn't change globally due to outputs

**Screenshots**

<img width="1280" alt="screen shot 2018-10-22 at 12 43 24 pm" src="https://user-images.githubusercontent.com/836375/47315069-5c2f2780-d5f8-11e8-9d3d-d5c9c168705e.png">

**Additional context**

Was running through the example notebooks to test the desktop release and noticed this behavior.

**Comment by emeeks** [comment]
`:global(elijah-will-fix)`
