### ISSUE TITLE
Rendering of "application/vnd.dataresource+json" broken

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#3491]
As far as I can tell [this](https://gist.github.com/davidanthoff/e4a97e08b0f77b4be47ecf5c39b85a64) notebook should render properly. Note that it has a ``application/vnd.dataresource+json`` payload.

When I run it or open it in nteract, I get:
![image](https://user-images.githubusercontent.com/1036561/47321269-1f1f6100-d609-11e8-9890-777f13372ce1.png)

This is on nteract 0.11.9 on Windows.

**Comment by willingc** [comment]
Thanks for the report @davidanthoff. 

The current version of nteract is 0.12.3. If you wish to try it and report the results, that would be helpful.

Next step for maintainers: Try the reported notebook with a Julia 1.0 kernel and the latest release.

**Comment by willingc** [comment]
Hi @davidanthoff,

I had a chance to try your example notebook with nteract 0.12.3 and the IJulia 1.0.3 kernel.

I had similar behavior as you did until I set the dataset to the variable in the nteract notebook:

![screenshot 2018-12-18 15 25 47](https://user-images.githubusercontent.com/2680980/50189279-796f3200-02d9-11e9-97da-b1d36b5e5e44.png)

The same notebook displays the dataset in Jupyter notebook as you found.

![screenshot 2018-12-18 15 29 42](https://user-images.githubusercontent.com/2680980/50189448-10d48500-02da-11e9-95c5-dec14543a779.png)
![screenshot 2018-12-18 15 30 08](https://user-images.githubusercontent.com/2680980/50189465-2cd82680-02da-11e9-9275-bb799b5d304b.png)

@rgbkrk This leads me to believe this is not a kernel issue but instead how we are rendering dataset in nteract. Any ideas on the cause?

**Comment by willingc** [comment]
Here's the JS console output of the dataset cell
![screenshot 2018-12-18 15 38 04](https://user-images.githubusercontent.com/2680980/50189640-f8b13580-02da-11e9-8366-4829ff161532.png)

**Comment by willingc** [comment]
Going to try on master as a next step

**Comment by davidanthoff** [comment]
I think ``print(p)`` essentially means that you only get a text MIME output, not the ``application/vnd.dataresource+json`` MIME version. So, yes, I agree, I think this is a probably a bug in how nteract processes that MIME type.

**Comment by willingc** [comment]
Yes. I agree with you that it is the `application/vnd.dataresource+json` not being processed correctly.

Now to fix it :wink: If you see any other Julia issues (I went back and triaged last night), please do file them since we definitely want good support for Julia 1.0+

**Comment by willingc** [comment]
@rgbkrk @captainsafia FYI info from trying on master with IJulia 1.0. I also noticed a couple of warnings in the tests around vega (may or may not be related).

![screenshot 2018-12-18 15 38 04](https://user-images.githubusercontent.com/2680980/50191219-b17a7300-02e1-11e9-96b3-64ffc8e12be4.png)
![screenshot 2018-12-18 16 00 22](https://user-images.githubusercontent.com/2680980/50191220-b17a7300-02e1-11e9-9227-ef27adb675d4.png)

**Comment by rgbkrk** [comment]
Once we get out from under our typescript conversion muck, I want to take a full look at this. 😬

**Comment by BenRussert** [comment]
I'm going to try to repro and look into this morning, here is my hypothesis:

I can tell from above that IJulia is returning a bundle with the proper dataresource key, but nteract/data-explorer can't parse the data. either, 1.) IJulia is not providing the proper data resource format of the data set. or 2.) `data-explorer` is not handling the data properly (maybe treating an optional key as required)


Here is how we type the data payload in `data-explorer` based on the data resource spec:

```ts
interface DataProps {
  schema: Schema;
  data: [fieldName: string]: number | string;
}

export interface Schema {
  fields: Field[];
  pandas_version: string;
  primaryKey: Array<Field["name"]>;
}

export interface Field {
  name: string;
  //  types provided by the kernel, literal strings:
  type: "integer" | "datetime" | "number" | "string" | "boolean";
}
```

Example from the iris dataset:

```js
"schema": {
    "fields": [
      { "name": "index", "type": "integer" },
      { "name": "sepal_length", "type": "number" },
      { "name": "sepal_width", "type": "number" },
      { "name": "petal_length", "type": "number" },
      { "name": "petal_width", "type": "number" },
      { "name": "species", "type": "string" }
    ],
    "primaryKey": ["index"],
    "pandas_version": "0.20.0"
  },
"data": [
    {
      "index": 0,
      "sepal_length": 5.1,
      "sepal_width": 3.5,
      "petal_length": 1.4,
      "petal_width": 0.2,
      "species": "setosa"
    },
    {
      "index": 1,
      "sepal_length": 4.9,
      "sepal_width": 3,
      "petal_length": 1.4,
      "petal_width": 0.2,
      "species": "setosa"
    },
    // ...
```

**Comment by davidanthoff** [comment]
@BenRussert Let me know if I can help in any way! But I think for now the example file I posted originally should probably be enough to identify which of your hypothesis explains what is going on?

**Comment by BenRussert** [comment]
@davidanthoff I'm looked at this now and I think the problem is the schema doesnt have a 'primary_key' field required. I think you could [add this here](https://github.com/queryverse/TableShowUtils.jl/blob/master/src/TableShowUtils.jl#L219).

The primary key is expected to be an array of at least one field name. Pandas uses the `index` name for this, by default  `["index"]`.

On the data-explorer side maybe we should be providing a default primary key if its missing, basically just enumerating the rows? I think for sure we should validate the schema and provide a useful error message about it.

**Comment by davidanthoff** [comment]
Ah, yes, if I edit the file manually and add that, it works!

But, looking at the spec [here](https://frictionlessdata.io/specs/table-schema/) (and in particular the "Primary Key" section), it seems pretty clear that this field is optional, right? I also wouldn't know what to put there: many tables don't have a primary key, and adding a column that just has row numbers seems also undesirable, because then the grid would show a column that doesn't even exist in the source data, right?

It seems to me that right thing to do here is to make data-explorer be able to handle cases where there is no ``primaryKey`` field. I think it actually did in the past, because there was a time when all of this worked, and I didn't change anything in the meantime on the julia side.

**Comment by willingc** [comment]
Thanks @BenRussert for taking a look at this.

**Comment by BenRussert** [comment]
Based in discussion in the weekly meeting, the todos for the data-explorer package here are:

- [ ] Make `primaryKey` an optional property

    - Either by generating a default range index enumerating rows, or some other method

- [ ] Potentially add some schema validation that provides a useful error message if there is a problem.

**Comment by davidanthoff** [comment]
Great, thanks a lot!

**Comment by davidanthoff** [comment]
When can we expect this to ship in a version?
