### ISSUE TITLE
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

### ISSUE THREAD

**Issue by hugo-pires** [nteract/archived-desktop-app#3501]
Hello

When I am running the latest version (nteract-0.12.1-x86_64.AppImage) in Fedora i get the following error on terminal

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Could you help me?

Thank you

**Comment by willingc** [comment]
Hi @hugo-pires, Thanks for the report. To clarify, are you seeing the application load at all?

**Comment by willingc** [comment]
@lgeiger Do you think the change made here: https://github.com/nteract/nteract/blob/master/applications/desktop/src/main/index.js#L104 introduced this as well as the animation opening not loading in #3505?

**Comment by hugo-pires** [comment]
Hello @willingc . The application does not load at all. Thanks

**Comment by willingc** [comment]
Hi @hugo-pires,

We recently released v0.12.3 https://github.com/nteract/nteract/releases/tag/v0.12.3 .

If you are able to try it, we can see if it works better for you. Thanks.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. If the issue still persists, please feel free to request that we reopen this issue. Thanks! 🌻
