### ISSUE TITLE
Switch from react-notification-system to blueprint.js Toaster

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3503]
Now that we're using blueprint.js, I'd like to make use of their [toasts](https://blueprintjs.com/docs/#core/components/toast). We'd probably switch to having a `Toaster` in the store like we do with the notification system. It's either that or a singleton.

**Comment by captainsafia** [comment]
We'll still want to do this so we can standardize our UI on one component system.
