### ISSUE TITLE
Feature request: Prevent nteract from trying to elevate UAC and update on exit

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/archived-desktop-app#3517]
nteract tries to update every time I exit it. It's annoying. But I cannot update to version that halts and need to be shutdown in Ctrl+Alt+Del... But I find it a good idea - update on exit. But I guess it's better to ask for update first instead of trying to elevate UAC without notice. And also would be good to add somewhere deep in the menues the ability to supress the next update (such button **shoud not** be in the question for update I mentioned).

**Comment by jameskoch** [comment]
I'd been seeing some errors on shutdown when running under a very low-privileged account. I bet this is it.

**Comment by kiwi0fruit** [comment]
I guess not. I've got no errors concerning this feature request. My error was already fixed and hopefully the next release would be OK. So I wait for it and see annoying UAC prompts that would update nteract if I say yes.
