### ISSUE TITLE
Autocomplete icons not showing

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#3519]
The autocomplete results show a question mark instead of an icon:

![bildschirmfoto 2018-10-25 um 17 04 18](https://user-images.githubusercontent.com/13285808/47510287-25674480-d878-11e8-965f-5ff6c3e97dec.png)

**Comment by rgbkrk** [comment]
IPython ended up removing the type hint information, we should switch back to just a plain delimiter when not known.

**Comment by mike-seekwell** [comment]
@rgbkrk couldn't figure out why everything in `_jupyter_types_experimental` was `<uknown>`, thanks for the answer.

Do you know of any replacements? I saw some discussion around using `inspect` instead.

**Comment by captainsafia** [comment]
This appears to be resolved now. I'm able to see the icons for the same code snippet run above. I'll go ahead and close this. Please re-open if there is another regression.
