### ISSUE TITLE
remote kernel such as in hydrogen

### ISSUE THREAD

**Issue by erblast** [nteract/archived-desktop-app#3526]
Are there any plans on implementing a feature where I can connect my local nteract session with a remote jupyter kernel such as in [hydrogen](https://nteract.gitbooks.io/hydrogen/docs/Usage/RemoteKernelConnection.html) which is an awesome feature by the way.  I understand that there is juypter nteract now that could be run on the remote server that I could then connect to but it would be a lot easier to simply run nteract locally then convincing the admins of that server to do any updates.

This is probably a duplicate of [#1031](https://github.com/nteract/nteract/issues/1031) and [#822](https://github.com/nteract/nteract/issues/822), just wanted to upvote that feature request.

**Comment by willingc** [comment]
Thanks @erblast.

ref: https://github.com/nteract/nteract/issues/1346#issuecomment-378112282

I'm closing this issue as addressed.
