### ISSUE TITLE
Markdown list indention

### ISSUE THREAD

**Issue by pochoi** [nteract/archived-desktop-app#3529]
**Application or Package Used**
nteract desktop
Version 0.12.2 (0.12.2)

**Describe the bug**
nteract desktop does not render correct indention for ordered and unordered list in Markdown (compared to Jupyter notebook). It happens when the ``` code block is in the list.

**To Reproduce**
For example, put the following codes into Markdown cells
<pre>
1. First thing
```python
x = 1
```
This is an X
2. Second thing
</pre>

<pre>
- First thing
```python
x = 1
```
This is an X
- Second thing
</pre>
The python code block and the "This is an X" are not indented (while it is indented in Jupyter notebook).

**Expected behavior**
The python code block and the "This is an X" are indented.

**Screenshots**
<img width="621" alt="screenshot 2018-10-27 01 59 34" src="https://user-images.githubusercontent.com/10320603/47601928-0528aa00-d98c-11e8-94c1-618f589af981.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome (It is relevant?)
 - Version 10.10.5

**Comment by lgeiger** [comment]
Our behavior closely matches the [commonmark spec](https://commonmark.org).

You can check your example using the [reference implementation of commonmark](https://spec.commonmark.org/dingus/?text=1.%20First%20thing%0A%60%60%60python%0Ax%20%3D%201%0A%60%60%60%0AThis%20is%20an%20X%0A2.%20Second%20thing%0A%0A-%20First%20thing%0A%60%60%60python%0Ax%20%3D%201%0A%60%60%60%0AThis%20is%20an%20X%0A-%20Second%20thing%0A) or the markdown editor on github and you'll get the same result.

To achieve the indentation you're expecting [you'd need to indent the text also in the markdown code]( https://spec.commonmark.org/dingus/?text=1.%20First%20thing%0A%20%20%20%60%60%60python%0A%20%20%20x%20%3D%201%0A%20%20%20%60%60%60%0A%20%20%20This%20is%20an%20X%0A2.%20Second%20thing%0A%0A-%20First%20thing%0A%20%20%60%60%60python%0A%20%20x%20%3D%201%0A%20%20%60%60%60%0A%20%20This%20is%20an%20X%0A-%20Second%20thing%0A)
