### ISSUE TITLE
nteract help gatsby-transformer-ipynb not registering nodes 

### ISSUE THREAD

**Issue by tblazina** [nteract/archived-desktop-app#3543]
**Application or Package Used**
 gatsby-transformer-ipynb

**Describe the bug**
When I install this package and include the transformer in the gatsby-config.js file under plugins as suggested the no jupyter notebooks (files with .ipynb extension) are being registered. When i go to the GraphiQL console, there are no JupyterNotebook nodes (or allJupyterNotebook)

**To Reproduce**
1. Instantiate a new gatsby project using the gatsby client - `gatsby new project-name`
2. `npm install --save @nteract/gatsby-transformer-ipynb` in the new project folder
3. `gatsby develop`
4. Go to http://localhost:8000/___graphql in browser and make query

**Expected behavior**
When there are .ipynb files in the project folder, I expected the nodes to be registered in the graphQL

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox Quantum

**Additional context**
I also noticed that the 'See it in action' link on the  [Gatsby plugin page](https://www.gatsbyjs.org/packages/@nteract/gatsby-transformer-ipynb/) is broken.

**Comment by willingc** [comment]
Hi @tblazina 

Thanks for filing an issue. From the report, I think that the report should be filed with the maintainers of gatsby-transformer-ipynb.

The nteract project does not maintain the reported package. I'm going to close this issue.
