### ISSUE TITLE
Investigate tools for TypeScript documentation of source files

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#3553]
@captainsafia and I had a conversation yesterday where we discussed possible approaches to creating documentation for source files after the TypeScript migration. Opening this issue to capture ideas.

Several tools have emerged along with writing a custom tool or bridge. Some of the available tools:

- TypeDoc http://typedoc.org/
-  TSDoc https://github.com/Microsoft/tsdoc a doc comment standard
- Styleguidist with TS or JSON

Articles of interest
- https://blog.cloudflare.com/generating-documentation-for-typescript-projects/

One of the goals is to deliver visually appealing docs similar to the current components.nteract.io docs

**Comment by captainsafia** [comment]
I did some more research and as it turns out, we can get monorepo support for TypeDoc using this plugin (https://github.com/christopherthielen/typedoc-plugin-external-module-name) to dictate each source file as part of a particular module and render them under the same header in the navigation.

**Comment by captainsafia** [comment]
This is done now! packages.nteract.io is alive!
