### ISSUE TITLE
No kernel available on nteract make it bug

### ISSUE THREAD

**Issue by parleur** [nteract/archived-desktop-app#356]
Hi, I just installed nteract, on linux and tried to test it, but it appears ( after a while searching ..) that nteract can't locate any usable kernel.

That produce a "not connected" window on nteract without the language menu.
A bug is raise in the javascript, I think related with no working kernel found.

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at Promise.all.then.kernelInfos (/home/parleur/jupyter/nteract/node_modules/kernelspecs/lib/traverse.js:64:8)
```

I think, non working kernels or no kernel should raise explicit message or error.

**Comment by rgbkrk** [comment]
We've now got an explicit error dialog when no kernels are found, as well as instructions (#759, #716). It's also in the most recent alpha release. Closing!

Thanks for trying nteract out and opening this.

We'll keep #357 around as we need to figure out how to detect conda environments soon.
