### ISSUE TITLE
Conda environments should show up as kernels

### ISSUE THREAD

**Issue by parleur** [nteract/archived-desktop-app#357]
I have a anaconda3 install in my home with my python stuff.

launching `jupyter-kernelspec` I obtain:

```
jupyter kernelspec list
Available kernels:
  python3    /home/parleur/anaconda3/lib/python3.5/site-packages/ipykernel/resources
  xonsh      /home/parleur/anaconda3/share/jupyter/kernels/xonsh
```

launching in node:

```
 `require('kernelspecs').findAll().then(console.log)
Promise { <pending> }
> { xonsh: 
   { name: 'xonsh',
     files: [ '/home/parleur/anaconda3/share/jupyter/kernels/xonsh/kernel.json' ],
     resources_dir: '/home/parleur/anaconda3/share/jupyter/kernels/xonsh',
     spec: 
      { argv: [Object],
        codemirror_mode: 'shell',
        display_name: 'Xonsh',
        language: 'xonsh' } } }
```

I only get the xonsh kernel the second time.

**Comment by minrk** [comment]
nteract doesn't include non-installed kernelspecs. Jupyter special-cases the IPython kernelspec _if it hasn't been installed_, but nteract chooses (rightly, I think) to not do this. To install the IPython kernelspec, do:

```
ipython kernel install
```

If you want to specifically install it in the env, like xonsh has done, specify the prefix:

```
ipython kernel install --prefix=/home/parleur/anaconda3
```

**Comment by minrk** [comment]
If you install ipykernel from conda-forge, this will [already be done](https://github.com/conda-forge/ipykernel-feedstock/blob/master/recipe/meta.yaml#L17).

**Comment by parleur** [comment]
Thanks for reactivity.

After doing `ipython kernel install --prefix=/home/parleur/anaconda3`, the kernel appears when:

```
require('kernelspecs').findAll().then(console.log)
Promise { <pending> }
> { python3: 
   { name: 'python3',
     files: 
      [ '/home/parleur/anaconda3/share/jupyter/kernels/python3/kernel.json',
        '/home/parleur/anaconda3/share/jupyter/kernels/python3/logo-32x32.png',
        '/home/parleur/anaconda3/share/jupyter/kernels/python3/logo-64x64.png' ],
     resources_dir: '/home/parleur/anaconda3/share/jupyter/kernels/python3',
     spec: { language: 'python', argv: [Object], display_name: 'Python 3' } },
  xonsh: 
   { name: 'xonsh',
     files: [ '/home/parleur/anaconda3/share/jupyter/kernels/xonsh/kernel.json' ],
     resources_dir: '/home/parleur/anaconda3/share/jupyter/kernels/xonsh',
     spec: 
      { argv: [Object],
        codemirror_mode: 'shell',
        display_name: 'Xonsh',
        language: 'xonsh' } } }
```

But it still seams not be found by nteract at launch, and bug like in #356. 0o 
Installing by default in `/usr/local` works, but I really don't wish to include parts of my anaconda python distribution in `/usr/local`.

**Comment by rgbkrk** [comment]
Thanks for the detailed report @parleur. I haven't tried getting nteract to work with Anaconda, though I imagine it's related to the `sys.prefix` when it launches.

Within the console on nteract itself (it's chromium under the hood), run `require('kernelspecs').findAll().then(x => console.log(x))`. You'll probably get different results than plain `node`.

Additionally, I'd run

```
require('sys-prefix-promise')().then(x => console.log(x))
```

and in `ipython` run:

```
import sys; print(sys.prefix)
```

**Comment by parleur** [comment]
Oo indeed ... the electron console complain about reducing an empty array in `node_modules/kernelspecs/lib/traverse.js` line 64 (paste here).

```
function findAll() {
  return jp.dataDirs({ withSysPrefix: true }).then(dirs => {
    return Promise.all(dirs
      // get kernel infos for each directory and ignore errors
      .map(dir => getKernelInfos(path.join(dir, 'kernels')).catch(()=>{}))
    ).then(kernelInfos => Promise.all(kernelInfos
      .filter(a => a) // remove null/undefined kernelInfo
--> .reduce((a, b) => a.concat(b)) // flatten the results into one array <--
      .map(a => getKernelResources(a).catch(()=>{})) // convert kernelInfo -> kernelResources and ignore errors
    )).then(kernelResources => kernelResources
      .filter(a => a) // remove null/undefined kernelResources
      .reduce((kernels, kernel) => {
        kernels[kernel.name] = kernel;
        return kernels;
      }, {})
    );
  });
}
```

I 'd patch it myself, but this full of promises kind of js coding is unfamiliar for me.

**Comment by rgbkrk** [comment]
Here's the approach I'd like to take on startup (likely within kernelspecs):
- Check if `conda` is available on the PATH (which we now have thanks to #842)
- Run `conda env list --json`:

``` json
{
  "envs": [
    "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/envs/distie", 
    "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/envs/ipy", 
    "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/envs/another"
  ]
}
```

Note: This is missing the root environment (that you would normally see with `conda env list`) - https://github.com/conda/conda/issues/3541.

If this is the root environment, I expect to be able to run

```
python -m ipykernel -f {connection_file}
```

regardless, even if the kernel is not installed.

**Comment by damianavila** [comment]
You can use, alternatively, `conda info --json` to get all the data you need including the root environment. This is what I used originally in nb_conda_kernels: https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L47

**Comment by rgbkrk** [comment]
Ok, great. I've got a working setup for a conda-kernel provider to get all the sys prefixes by name.

I'm forming up an array of objects like this:

```
[{'name': 'distie',
  'prefix': '/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/envs/distie'},
 {'name': 'ipy',
  'prefix': '/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/envs/ipy'},
 {'name': 'microbots',
  'prefix': '/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/envs/microbots'},
 {'name': 'root',
  'prefix': '/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7'}]
```

The next problem is detecting installed jupyter kernels. Within those `sys.prefix`es, I'd want to look for `share/jupyter` to find kernels. If they're not in there, I have to slightly assume that I can run `python -m ipykernel -f {connection_file}` whether or not I know that ipykernel is in the env.

Then again, I can check for ipykernel, but this all impacts startup time for the user and making the logic a bit more crazy.

**Comment by betatim** [comment]
When launching nteract from the terminal with an active conda env I usually want to use that env. It would be good if that kernel ended up being the "default" in that situation.

I don't know if it is worth it/faster to detect this and in that case not search for other envs and whether they have kernels.
- active env -> look for kernels in that env and use them
- no active env -> global search

WDYT?

**Comment by rgbkrk** [comment]
Seems like something we can do, if theres an environment variable for the current conda environment that is stable to use.

**Comment by rgbkrk** [comment]
In #847, I'm pulling up all conda environments which have the IPython kernel installed. Eventually I'll move that to the main thread (since we want to populate the menu), and we can also make sure that the default notebook on launch case uses the current conda environment.

**Comment by betatim** [comment]
I used `$CONDA_DEFAULT_ENV` to decorate my prompt which has worked for a long time. Slightly confusing because the name makes you think it tells you about the default conda env, but in practice it tells you the currently active env.

**Comment by NHDaly** [comment]
Thanks for doing this! :) Is there any way I can help with it? this is a the main way I'd want to use `nteract`, because all my kernels are installed through `conda`.

I see you're making good progress at #847, is there something I could try to help with; i'd love to start contributing to nteract! :D

**Comment by rgbkrk** [comment]
@NHDaly Absolutely! I've been chasing down some other fixes and haven't been able to devote my time completely to this. Some changes generally need to be made to how we
- [ ] register kernelspecs in the menu, in the main process
- [ ] provide all the kernelspecs to a notebook process to use
- [ ] send a particular kernelspec to the notebook process

#847 completely creates all the kernelspecs necessary, most of what we need next is organization around how we handle actions for kernel start. Deep within our epics is a [little document/outline on how we can start to approach this](https://github.com/nteract/nteract/blob/d4cd3837e32bbc9c9a60a6bf66fbb31567d2c86b/src/notebook/epics/kernels.md#handling-multiple-ways-of-discovering-launching-and-destroying-kernels).

If you want to start off on a precursor PR, it would be to change our menu logic to sending the full kernelspec from the main process (instead of a kernel name). After that, we can set up the conda kernels in the main process (as a one time cost, since we now have a loading menu).

We also need a way to provide _all_ the kernelspecs, on startup, to the notebook process (since we load which kernelspec to launch from a notebook's metadata). Really happy to have you work on this with us!

**Comment by rgbkrk** [comment]
To start things off, I can extract a portion of that conda kernel finding setup to a module separate from my PR (which I'm happy to close and only refer to).

**Comment by rgbkrk** [comment]
Would love someone to resurrect this work. 😄

**Comment by willingc** [comment]
@rgbkrk I recommend we close this issue and flesh out a new issue related to conda kernel registration.
