### ISSUE TITLE
Use official timeago release instead of converting it to typescript

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#3582]

**Comment by lgeiger** [comment]
We forked this into the monorepo some time ago when we brought in `commuter`. I think we should look into using the [official release](https://github.com/nmn/react-timeago) again instead of converting it to typescript.

**Comment by rgbkrk** [comment]
Yeah I agree.

**Comment by willingc** [comment]
@jdetle I'm closing this since it seems from the project that this is done.

**Comment by jdetle** [comment]
Yes! Thank you. I need to get better at doing this myself.

**Comment by willingc** [comment]
No worries @jdetle. Trying to improve the workflow so it's easier to do. I think GitHub actions will help too.

**Comment by rgbkrk** [comment]
I think I was the one to delete the unused package so I probably should have done a `closes #3582` in it, I didn't realize this issue existed though 😅
