### ISSUE TITLE
Kernels Just Hang on Loading in Mac

### ISSUE THREAD

**Issue by psychemedia** [nteract/archived-desktop-app#3623]
Mac 10.13.6, nteract 0.12.2, first install onto a relatively clean machine.

I have notebooks running fine on commandline via `jupyter notebook` and `jupyter kernelspec list`  lists kernels as expected. `nteract` app shows kernels in `Runtime` menu but when I try to load or create a new notebook, I get a *- not connected* status in title bar and a hung message along lines of *Not saved yet - python3 | launching* in the status bar.

Running `Restart` menu item gives: `CORE/ERROR {}`.

**Comment by jameskoch** [comment]
If you select VIEW > TOGGLE DEVELOPER TOOLS, then select the CONSOLE tab, you'll likely see a more helpful error msg.

In my case I get `/usr/bin/python: No module named ipykernel_launcher`. I don't use Python all that much, so I'm not surprised that my Python envs are a mess and maybe missing some modules. That said, I don't think you're alone out there as I also see this error msg in these issues:

https://github.com/nteract/nteract/issues/3373
https://github.com/nteract/hydrogen/issues/730

I expect that some sort of install of the ipykernel module will resolve this, but I'm not particularly well versed in Python packaging.

**Comment by psychemedia** [comment]
Ah, thanks...

```
>>>> Logging kernel python3 (ref f12ee937-e011-451c-8870-ea1c514288a7) stdout and stderr to javascript console in this color    <<<<

app.js:141 /usr/local/opt/python@2/bin/python2.7: No module named ipykernel_launcher
```

So even though I am running a Py3 kernel, there is a dependency on a Py2 package to actually launch it that `nteract` doesn't install?

**Comment by brodock** [comment]
I tried using IRuby and I noticed that it only loads ruby after I open a new Python3 tab. Somehow one is depending on the other to trigger something to the GUI application.

This is what I did to enable IRuby:

Install nteract GUI interface:
```
brew cask install nteract
```
Install Ruby Kernel and dependencies
```
gem install iruby rbczmq
iruby register --force
```
Install Jupyter:
```
pip3 install ipykernel
python3 -m ipykernel install --user
```

Note: I'm using ruby 2.5.3 installed from RVM and defined as the default ruby version: 
```
rvm use 2.5.3 --default
```

And Python3 is from homebrew: 

```
which python3
/usr/local/bin/python3
```

**Comment by psychemedia** [comment]
I found if I installed `ipykernel` into py2, the py3 kernel worked fine...

```
python2 -m pip install ipykernel
python2 -m ipykernel install --user
```
