### ISSUE TITLE
JupyterLab not finding packages after installing ipykernel

### ISSUE THREAD

**Issue by brylie** [nteract/archived-desktop-app#3627]
Shortly after following the [instructions to install ipykernel](https://nteract.io/kernels), I noticed JupyterLab has had difficulty finding packages from virtual environments. I am not sure that this is exactly related, but cannot remember any other specific steps I would have taken to break my system path/virtual environments. 

Is anyone else having difficulty with environment packages after installing ipykernel?

**Comment by brylie** [comment]
I tried to remove ipykernel with the following command:


Now, Jupyter Notebook has trouble restarting:

```
KernelRestarter: restarting kernel (1/5), new random ports
/home/user/anaconda3/bin/python: No module named ipykernel_launcher
```

**Comment by brylie** [comment]
I just don't think it is a good idea to install ipykernel to the user environment. Things now seem to be breaking for other virtual environments.

**Comment by brylie** [comment]
This issue may be related:

https://github.com/jupyter/notebook/issues/2563

> For now, you can probably work around it by changing the first item in argv to 'python3' in the Python 3 kernel.json file.

**Comment by willingc** [comment]
Hi @brylie, If you are still having an issue with this, please file an issue at https://github.com/jupyterlab/jupyterlab. This doesn't appear to be an nteract issue (project is different than jupyterlab). Thanks.
