### ISSUE TITLE
Current working directory set to one level up on startup

### ISSUE THREAD

**Issue by douglasdaly** [nteract/archived-desktop-app#3630]
**Application or Package Used**
nteract desktop 0.12.3, .deb on Ubuntu

**Describe the bug**
nteract starting one directory above the current working directory when calling from the command-line in Linux

**To Reproduce**
1. Navigate to desired directory
2. Launch nteract (e.g. ```nteract``` from bash shell)
3. Run ```%pwd``` in new notebook and note it's one directory above the current working directory

**Expected behavior**
Working directory should be the directory nteract was launched from

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Version: ```nteract_0.12.3_amd64.deb```

* I've also noticed this on Windows

**Additional notes**
Might be helpful to have this (working directory) as a command-line option, I could see that being useful in workflows.

**Comment by willingc** [comment]
macOS 10.14.3 and nteract 0.12.3 opens the directory which nteract was launched from the command line.

Using the magics % or %%bash result in the root directory being displayed (2 up from the launch directory).

**Comment by mphuie** [comment]
I am seeing the same thing, using Python 

    import os
    os.getcwd()

Is showing the parent directory.  I'm unable to import anything from the directory I launched nteract. ( With command `nteract .`)

Nteract 0.12.3
MacOS 10.14.3
