### ISSUE TITLE
Is there a way to hide the menu bar in windows?

### ISSUE THREAD

**Issue by mayankwadhwa** [nteract/archived-desktop-app#3635]
I want to hide the menu bar in windows as it doesn't look good. Even in fullscreen the menu bar still persist.

![screenshot 15](https://user-images.githubusercontent.com/17674962/48251414-8faae800-e427-11e8-9dd7-3b2dc45f55c8.png)

**Comment by willingc** [comment]
Hi @mayankwadhwa,

I'm not seeing the same behavior on Mac. I don't currently have access to Windows. When you launch fullscreen, are you using the toggle in the View menu?
 
<img width="614" alt="screenshot 2018-12-17 20 15 01" src="https://user-images.githubusercontent.com/2680980/50131821-dbc42600-0238-11e9-90c1-69618c2a9d61.png">

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻
