### ISSUE TITLE
New Markdown Preview Cell Package

### ISSUE THREAD

**Issue by jefftrevino** [nteract/archived-desktop-app#3638]
**Motivating Problem**
Someone familiar with the classic notebook's dichotomy of markdown and input cells might expect a symmetric API with similarly prominent input and markdown cells, but the current one offers prominent input cells and relatively hidden markdown cell functionality. It would be nice to have a MarkdownPreviewCell component that lives with the other cell components.

**A Solution I'd Like**
*Interface*
The docs invite users to render a cell using the following pattern,
```
const { Prompt, Source } = require("@nteract/presentational-components");
<Input>
<Prompt/>
<Source/>
</Input>
```
which suggests that the API needs a sister component to Source named Markdown. Just as Source is a presentational component that renders syntax-highlighted source code, Markdown would be a presentational component that renders Markdown.
__
*Implementation*
@rgbkrk recommended in Slack chat to add something like a `packages/markdown-preview-cell` directory that includes a new MarkdownPreviewCell component, based on the 'markdown' case from the `AnyCell` component in `packages/notebook-app-component/src/markdown-preview.js`). It looks like the `MarkdownCell` component in `notebook-app-component/src/markdown-preview.js`)

**Considered Alternatives**
At first I was thinking of just adding a data prop to the Cell component, but I see from the docs that it's not supposed to do anything by itself, only in tandem with other components like Input and Source, so that's right out! 

On second thought, it might be easier to just check if the `<Source />` component's `language` prop is set to "markdown." If it is, it should be treated like a markdown cell. This makes more sense to me, as markdown is also pretty much a language, no? I took [a crack at drafting this solution](https://github.com/jefftrevino/nteract/blob/dev_markdown_preview_cell/packages/presentational-components/src/components/source.js), predicting that you all will soon explain to me why this is too simple a solution....

**Additional Context**
I started thinking about this when I went to add a markdown cell to the jupyter-demo-app project example and found it much more difficult and less documented than the task of adding an input cell.

**Comment by captainsafia** [comment]
This is addressed via https://github.com/nteract/nteract/pull/4704. Re-opening so that it can be called when that PR is merged.
