### ISSUE TITLE
There is no way to completely close nteract

### ISSUE THREAD

**Issue by nicocarbone** [nteract/archived-desktop-app#3656]
On linux, when I close a nteract window, the application remains open with an icon in the tray area. This icon doesn't have a "close" option.
If I open another document with nteract, it opens another instance, with another icon in the tray.
The only way I find to close nteract is to force quit it from System Monitor.

I am using Ubuntu 18.10 amd64

**Comment by BenRussert** [comment]
I think I see the bug in main/index.js of the desktop app. The app needs to quit if all windows are closed on non Mac platforms. I'll fix when I get home unless someone gets it first.

We should probably add a quit option to the tray menu too.

**Comment by mscipio** [comment]
Sorry to re-open this issue, but I am still experiencing this problem on Ubuntu 16.04 ... any way to solve this?

**Comment by BenRussert** [comment]
@kelleyblackmore this might be a good thing to dig into together next time we meet. At a minimum we could add the quit option to the tray menu.
