### ISSUE TITLE
nteract_on_jupyter: 404 not found

### ISSUE THREAD

**Issue by mr-tcan** [nteract/archived-desktop-app#3679]
**Package: nteract-on-jupyter**

I got an 404 error after running jupyter nteract. The terminal shows:

``` shell
[W 17:38:54.795 NteractApp] Error loading server extension nteract
    Traceback (most recent call last):
      File "/home/tscangussu/.local/lib/python3.6/site-packages/notebook/notebookapp.py", line 1573, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'nteract'
```

**Steps to reproduce the behavior:**
1. Go to terminal
2. Run `jupyter nteract`

**My system**
 - OS: Ubuntu 18.10
 - Browser: Firefox 63
 - Python: 3.6.7
 - jupyter: 1.0.0      
 - jupyter-client: 5.2.3
 - jupyter-console: 6.0.0 
 - jupyter-core: 4.4.0  
 - nteract-on-jupyter: 1.9.15

**Comment by jdetle** [comment]
I think there are some steps missing here, did you do `jupyter serverextension enable nteract_on_jupyter`?

**Comment by mr-tcan** [comment]
No, I did not. I just followed the README instructions and this step wasn't there.

Now it is working. Thanks.

**Comment by jdetle** [comment]
Can you point to which readme? I want to fix that so nobody has to go through your issues.

**Comment by mr-tcan** [comment]
> Can you point to which readme? I want to fix that so nobody has to go through your issues.

I'm sorry. I forgot that: https://github.com/nteract/nteract/blob/master/README.md#L35-L44

**Comment by willingc** [comment]
Thanks @tscangussu for raising the issue and @jdetle for the support and documentation fix. 👍
