### ISSUE TITLE
Install nteract on chromebook plus through linux beta

### ISSUE THREAD

**Issue by orenjiataronjat** [nteract/archived-desktop-app#3693]
I was wondering if it was possible to install nteract to run on a chromebook plus v2? I have linux beta apps enabled and it has an intel processor. The only package I see is an amd deb file not an intel deb file. Was wondering if there was anyway. Thank you.

**Comment by willingc** [comment]
Hi @orenjiataronjat, I'm not sure as I haven't tried it. Please let us know if you were able to run it. Thanks.
