### ISSUE TITLE
Update TSDoc strings on TypeScript packages

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#3707]
We need to add docstring-based documentation to the following packages.

- [x] commutable
- [x] enchannel-zmq-backend
- [x] messaging
- [x] rx-binder
- [x] rx-jupyter
- [x] selectors

**Comment by willingc** [comment]
Hello amazing @captainsafia. Ready to close?

**Comment by captainsafia** [comment]
Not quite, now that we've created more packages there are a few that need to be documented. Here's the new list.

- [ ] actions
- [ ] epics
- [ ] reducers
- [ ] types
