### ISSUE TITLE
missingno package support - missingno.matrix(df) does not output column names

### ISSUE THREAD

**Issue by abdelnoureldin** [nteract/archived-desktop-app#3709]
using nteract on some data exploration - the package missingno shows missing data in a dataframe.
input:

    %matplotlib inline
    import missingno as msno
    msno.matrix(df)

this produces the visualisation but does not show column names at the top (tried both light and dark themes)

**Comment by willingc** [comment]
@abdelnoureldin Were you able to resolve this issue? If it still exists, could you provide a bit more detail about what is going on. Thanks!

**Comment by abdelnoureldin** [comment]
Hey carol! thanks for getting back. 
The issue seems to be resolved now which is awesome
