### ISSUE TITLE
webpack builds not repeatable/reproducible

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3710]
Given repeated runs of the build in clean environments, from the same sources, the artifacts we generate are slightly different from one another.

**Issue 1:**
Webpack source maps include absolute paths to the original sources, requiring that reproducible runs occur in the exact same absolute path every time. This is already captured in https://github.com/webpack/webpack/issues/3603

**Issue 2**
Some functions in `vendors~vega-transform-[hash].bundle.js` appear in a different order across builds. There are two consecutive sequences of code that change places, flip-flopping with one another seemingly at random. I uploaded the ordering of the symbols in the problematic area [here](https://github.com/jameskoch/nteract/commit/978a8ea3002c6205738ba2afb4a60b207ca9bf78); load into your preferred diff tool to see, but basically `["Dataflow"..."randomUniform"]` sometimes comes before and sometimes comes after `["accessor"..."visitArray"]`.

**Comment by jameskoch** [comment]
I'm still learning how the many vega-related pieces fit together, but noted that the build prints this warning that just might be related:
```
[BABEL] Note: The code generator has deoptimised the styling of /path/to/nteract_sources/node_modules/@nteract/vega-embed-v2/dist/index.esm.js
```
_Update_: Resolved this warning by forcing `compact: true` on all files regardless of size; no change in reproducibility issue.

**Comment by jameskoch** [comment]
Experimentally, found that adding:

```
optimization: {
  occurrenceOrder: false,
  providedExports: false,
  usedExports: false,
  concatenateModules: false,
  sideEffects: false,
},
```

to the webpack config seems to get the job done. I briefly tried bisecting this list but gave up due to time constraints.

Filed https://github.com/webpack/webpack/issues/8435 with what details I have.

**Comment by rgbkrk** [comment]
This makes me wonder if there's more we can do on the bundling side of Vega with a separate package. We only use rollup for old Vega.

**Comment by jameskoch** [comment]
@rgbkrk I was worried that disabling these five optimizations would bloat my nteract-on-jupyter wheel.  Checked and found that my clean, deoptimized, build generated a 3.7MB wheel compared w/ 38MB for the [one published to PyPi](https://pypi.org/project/nteract-on-jupyter/#files). I think the big diff here is not the optimizations, but that my build was from a clean working folder. The larger jar appears bloated w/ a lot more `*bundle.js*` files, and I don't see the bloat when I run my clean build with the optimizations back on.
