### ISSUE TITLE
TypeScript Monorepo Regressions

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3713]
I've noticed that TypeScript is resolving based on built packages rather than what's in `src`. For example, I changed `@nteract/commutable` to export `ImmutableCell` so that I could rely on it in `@nteract/selectors`:

<img width="780" alt="screen shot 2018-11-27 at 3 34 59 pm" src="https://user-images.githubusercontent.com/836375/49118657-0b939580-f25a-11e8-9983-ff933cd8e798.png">

The message above makes it pretty clear there too, it's resolving from `commutable/lib/index`. With flow we had a mapping to have it resolve from `src` when in monorepo land. Is there a way for us to handle that in typescript so you don't have to (re)build packages?

**Comment by willingc** [comment]
@rgbkrk Can this be closed now?

**Comment by rgbkrk** [comment]
I think we're good here now. Thanks @willingc!
