### ISSUE TITLE
@nteract/commutable README docs link doesn't exist

### ISSUE THREAD

**Issue by chrnorm** [nteract/archived-desktop-app#3727]
**Describe the bug**
The [docs section in the commuter package README](https://github.com/nteract/nteract/blob/master/packages/commutable/README.md#docs) links to the old github pages website (https://nteract.github.io/docs/commutable/), giving a 404 error.

The new docs website (docs.nteract.io) doesn't have a commutable section - should the link in the README be removed for now?

**Comment by captainsafia** [comment]
Closed via https://github.com/nteract/nteract/pull/3743.
