### ISSUE TITLE
Combine CodeMirror completion with Jupyter completion

### ISSUE THREAD

**Issue by jdfreder** [nteract/archived-desktop-app#383]
It should combine CodeMirror completion information in addition to the Jupyter spec information.

Otherwise completion is a little counterintuitive:

```
import math
ma
```

Completion on the second line doesn't include math because the code has not been executed on the kernel yet.

**Comment by Carreau** [comment]
on the IPython side, once we have jedi, what is above should work, but +1 on combine. 
Though codemirror completion is not made for that.

**Comment by rgbkrk** [comment]
What do you think about this one now that jedi is integrated (or so I thought)?
