### ISSUE TITLE
Selecting text cut off in nteract desktop

### ISSUE THREAD

**Issue by MiroFurtado** [nteract/archived-desktop-app#3855]
**Application or Package Used**

nteract desktop mac  0.12.3

**Describe the bug**

Click to select text is blocked in far right of markdown cell. To be able to edit the far right text I have to click earlier in the cell and then use the right arrow key.

**To Reproduce**
1. Open runtime
2. Create new markdown cell
3. Paste in "$$\text{Check out the latex support!} \rightarrow f(x) = \int_{0}^\infty$$"
4. Change window size until dropdown arrow and trashcan are just to the upper right of the terminating text
5. Try to click on the terminating '$$' to select

**Expected behavior**

I should be able to put my cursor at the '$$' by clicking.

**Desktop (please complete the following information):**
 - macOS Mojave 10.14

**Comment by willingc** [comment]
Hi @MiroFurtado,

Thanks for the issue. I've been able to replicate the issue. We appreciate the detailed steps.

The behavior seems more pronounced on code cells than markdown cells. Though it definitely is an issue with both.

For now, the workaround is to click in the cell to the left of the dropdown arrow area, and use the right arrow to the end of the line.

It appears the element below mask and prevent the ability to click on the text.
<img width="341" alt="screenshot 2018-12-17 19 59 49" src="https://user-images.githubusercontent.com/2680980/50131393-c8b05680-0236-11e9-807b-200a7acfab12.png">

**Comment by willingc** [comment]
@captainsafia @rgbkrk Can you check if the Typescript changes fixed this in master? Thanks.

**Comment by rgbkrk** [comment]
This is a problem because of the cell menu's overlay like you noticed @willingc. Only solution that won't collide with codemirror is to move our cell menu above the cell itself, like a ribbon.
