### ISSUE TITLE
Migrate from styled-jsx to styled-components

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#3856]
Packages
- [x] presentational-components #3852 
  - [ ] Header editor's inclusion of blueprint styled-jsx #3893
- [x] connected-components #3871 
- [x] directory-listing
- [x] dropdown-menu
- [x] editor #3867 
  - [ ] Address #3872
- [x] notebook-app-component
- [x] notebook-preview
- [x] notebook-render
- [x] outputs
- [ ] transform-dataresource
- [x] transform (just the `Image` transform)
- [ ] styled-blueprintjsx #3893 

Applications
- [ ] commuter
- [ ] desktop
- [ ] jupyter-extension
- [ ] play #3842

**Comment by rgbkrk** [comment]
Grabbing editor as my next one.

**Comment by rgbkrk** [comment]
Editor done (as well as a little fix up). On to `notebook-app-component`.

**Comment by rgbkrk** [comment]
`notebook-app-component` done, on to fixing https://github.com/nteract/nteract/issues/3872 next.

**Comment by rgbkrk** [comment]
With #3893 only the data explorer changeover to styled-components remains for the packages. Next up is apps, which I don't want to touch until we fix `master` for applications

**Comment by rgbkrk** [comment]
This is all done.
