### ISSUE TITLE
Any asset on disk can be loaded from output areas

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#387]
This has slices of both "awesome" and "uh oh" as is typical with our environment. :wink:

Open up a new notebook from nteract (relative to the repo), with a Python kernel, and run

```
import IPython
IPython.display.HTML("<img src='../node_modules/urlgrey/urlgrey.png'>")
```

<img width="765" alt="screenshot 2016-04-23 16 01 07" src="https://cloud.githubusercontent.com/assets/836375/14763954/50546b7e-096c-11e6-9193-1e4f67ba3010.png">

This opens us up to opening any path `../../../../../../../tmp/whatever`. 😧 

Realistically, this is how we're loading assets anyways. The problem is that we don't necessarily know if the output of a notebook can/should open a file. After all, on a normal desktop environment, this is _exactly_ what we want for users. They should be able to load images that are relative to their work. The Jupyter notebook server does exactly this (though without implications of directory traversal).

The problem it poses is if asset loading can be used in a malicious way from a context like this in Electron. I'm not sure if, when we set things up in iframes in the "not node mode" for scripts, if it will give the same level of isolation to not fetch assets.

Is this acceptable behavior? I tend to think so, which implies that we have to do the notebook trust mechanics. I was really hoping we wouldn't have to.

**Comment by minrk** [comment]
Trust mechanics should only be relevant if the loaded output can execute code. Merely displaying a file shouldn't be an issue unless it's in a manner where it might be able to execute javascript. Showing the user their own private ssh keys isn't an issue unless there's js on the page where the notebook author could send that content to themselves, execute kernel code, etc.

**Comment by rgbkrk** [comment]
If/when we switch to non-node output areas (sandboxed iframes), users won't have any access to run code on kernels (nor node itself). The vector I'm thinking of here would look like:

```
<img src='/some/path' onload='' />
```

where `onload` gets access to the "image" itself.

It seems that normal `fetch` and `XHR` disallows a lot of sane defaults:

<img width="645" alt="screenshot 2016-04-25 12 38 04" src="https://cloud.githubusercontent.com/assets/836375/14793919/f56440aa-0ae6-11e6-9b10-3326f3d1c277.png">

Additionally, we can lock down our content security policy to a great degree, just like Atom currently does.

Meta: [@#(%_&@#(%_](https://twitter.com/rgbkrk/status/724654773543129088)

**Comment by rgbkrk** [comment]
Closing as "feature", deferring to #1067.
