### ISSUE TITLE
Extract the IPython mode from jupyter/notebook, make it npm installable.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#389]
Or contribute it back to codemirror.

And find a way to highlight magic correctly.

**Comment by mangecoeur** [comment]
FYI - the editor element from VSCode is on it's way to being released as a separate installable package. Might be an interesting alternative to codemirror? Python support is already good, not sure what would need to happen for IPython...  https://github.com/Microsoft/vscode/issues/446

**Comment by rgbkrk** [comment]
@mangecoeur Neat! I was talking to @nathansobo about extracting the editor component out of Atom a few days ago, so I think this in on their roadmap as well. Relatedly, I posted about it over in https://github.com/atom/text-buffer/issues/122 (though the wrong repo for that issue).

**Comment by rgbkrk** [comment]
@Carreau has this been exported as part of the JupyterLab effort at all?

**Comment by rgbkrk** [comment]
Done in #871. Magics not set correctly though.
