### ISSUE TITLE
Add configuration options for auto-complete

### ISSUE THREAD

**Issue by gersonjferreira** [nteract/archived-desktop-app#3904]
When typing code, I don't always like the auto-complete. In many editors and languages it sometimes pops up when unneeded and gets in the way. Trying to make everyone happy, I would suggest the following options for people to chose from:

1. Auto-complete always on, or only after pressing a key (e.g. TAB)

2. Auto-complete only after N=? characters. Let the user choose.

**Comment by willingc** [comment]
Thanks for the suggestion @gersonjferreira. We're happy that you are using nteract too. 👍

**Comment by psmaragdis** [comment]
Yes please, I'd like to second that. Autocomplete has become increasingly more distracting in nteract.

Aside from waiting for a fix, is there some simple hack that we can do to temporarily disable autocomplete in a notebook?

**Comment by rgbkrk** [comment]
I think we should disable typeahead in nteract. I'll do that over the next week since I'm cleaning up the editor right now.

There's not a way to temporarily disable it in the current release.
