### ISSUE TITLE
Skip Markup cells after shift+Enter

### ISSUE THREAD

**Issue by gersonjferreira** [nteract/archived-desktop-app#3905]
When running the code, it is annoying to enter the ML cell when unneeded. It would be nice if the ML cell would only open to be edited upon double-click, thus the shift+Enter on the previous cell should skip the ML cells.

**Comment by willingc** [comment]
Thanks for the feature suggestion @gersonjferreira.

**Comment by captainsafia** [comment]
This has been fixed. I'll go ahead and close out this issue.
