### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gomezdj** [nteract/archived-desktop-app#3918]
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nteract", line 7, in <module>
    from nteract_on_jupyter.nteractapp import main
  File "/usr/local/lib/python2.7/site-packages/nteract_on_jupyter/nteractapp.py", line 44
    classes = [*NotebookApp.classes, NteractConfig]
               ^
SyntaxError: invalid syntax
```

**Application or Package Used**
State which application or package this affects. For example: nteract desktop, nteract web, nteract on jupyter, play, etc.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by willingc** [comment]
@danielgomz Sorry about the delayed response here. If you are still having trouble, please let us know. We would be happy to help you on our Slack channel or here. Thanks.

**Comment by zachwill** [comment]
I've also run into this issue on Python 2.7.15 on Mac OS X 10.14.4.

**Comment by edgarrmondragon** [comment]
I'm having the same issue on Python 2.7.15. This syntax is incompatible with 2.7:

```
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> [*[1, 2, 3], 4]
  File "<stdin>", line 1
    [*[1, 2, 3], 4]
     ^
SyntaxError: invalid syntax
```

But works fine on [Python 3.5+](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations)

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> [*[1, 2, 3], 4]
[1, 2, 3, 4]
```

**Comment by gomezdj** [comment]
This is the error I would like to correct. I would like to run the shell command. I click on the “Install Shell Commnands” and I get this:

ENOENT: no such file or directory, symlink '/Applications/nteract.app/Contents/Resources/bin/nteract.sh' -> '/Users/danieljosephgomez/.local/bin/nteract’



Daniel Gomez
(925)418-2269
sfdanielgomez@gmail.com

**Comment by captainsafia** [comment]
Thanks for opening this issue, @danielgomz! For the original issue, does the problem persist when you run the nteract Jupyter extension in a Jupyter installed in a Python 3 environment?

Also, can you open a different issue for the problem regarding installing the shell command. It'll help make it easier to triage and search for that issue.
