### ISSUE TITLE
Documentation on how to add a package

### ISSUE THREAD

**Issue by samghelms** [nteract/archived-desktop-app#3921]
I'm trying to work on some new features and I can't figure out how to create a new package in the `packages` monorepo -- when I run "lerna create" it ends up creating a package in the `applications` folder, and when I add folders with `package.json` files to `packages`, they don't show up. Can someone please add some documentation on how to add a package?

**Comment by rgbkrk** [comment]
I recall @jdfreder figuring this one out, requiring some interesting `lerna` options. There's some strangeness in us having two lerna workspaces.

The way I tend to make new packages is to:

* create the directory in `packages/package-name`
* copy package.json over from another package, name this new package `@nteract/package-name`
* run `yarn` at the root to make sure all the steps happen, including the lerna bootstrap

Anything else we'll want to document @captainsafia?

-------

What packages are you looking to create?

**Comment by captainsafia** [comment]
That looks good as the first steps. I’d also include things like adding a README and checking that the package version is set correctly and so on.

**Comment by samghelms** [comment]
Thanks for the quick responses! I followed the instructions, and normal imports seem to be working. However, I'm still getting an error when I try to use a dynamic import, such as the one used for the monaco-editor in `nteract/applications/jupyter-extension/nteract_on_jupyter/app/contents/file/text-file.tsx`. Any idea why this would be occuring?

Sample import: (from `text-file.tsx`). 
```javascript
import(/* webpackChunkName: "monaco-editor" */ "@nteract/monaco-editor").then(
      module => {
        this.setState({ Editor: module.default });
      }
    );
```

The error message is as follows:

```
ERROR in ./app/contents/file/text-file.tsx
Module not found: Error: Can't resolve '@nteract/pymarkdownx-notebooks' in '/Users/shelms/Documents/git-repos/nteract/applications/jupyter-extension/nteract_on_jupyter/app/contents/file'
 @ ./app/contents/file/text-file.tsx 80:6-82:39
 @ ./app/contents/file/index.tsx
 @ ./app/contents/index.tsx
 @ ./app/app.tsx
 @ ./app/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8357 (webpack)/hot/dev-server.js ./app/index.tsx
```

It looks like the package is not symlinked, though I don't understand how this could be, given that the "normal" import works (normal == `import * as test from '@nteract/pymarkdownx-notebooks'`.

Note: I'm following the instructions in `nteract/applications/jupyter-extension` on how to develop the jupyter extension, and running `jupyter nteract --dev`.
--

I'm working on a markdown based notebook for the ipython kernel, built on top of Monaco.

**Comment by samghelms** [comment]
Here's the git diff: https://github.com/nteract/nteract/compare/master...samghelms:master

**Comment by rgbkrk** [comment]
Annoyingly we decided to bite the bullet on our final typescript conversions so `master` is not the best to work off of right now. If you'd like to get going on things, I recommend working from an earlier commit. Let me dig something up. Otherwise we should be in a good state in a couple days.

**Comment by samghelms** [comment]
Ahh I see. Thanks!

**Comment by samghelms** [comment]
Update: I updated `/Users/shelms/Documents/git-repos/nteract/packages/webpack-configurator/monorepo.js` with my new package. Things seem to be working now.

**Comment by captainsafia** [comment]
Closing this out and leaving the issue open for posterity as how to create new packages.
