### ISSUE TITLE
CONTRIBUTING.md has two broken links

### ISSUE THREAD

**Issue by CrystallineCat** [nteract/archived-desktop-app#3998]
There are two broken links in [CONTRIBUTING.md](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md):

- Section "JavaScript side", "[TypeScript in 5 Minutes](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.htmls)": the very last "s" in the URL shouldn't be there.
- Section "Jupyter and ZeroMQ", "[build your own REPL with enchannel](https://github.com/nteract/docs/blob/master/enchannel/build-your-own-repl.md)": the target branch doesn't seem to exist any more.

I'll make a PR momentarily which fixes the first issue above, but I've trouble identifying a proper target for the second link. The best fit appears to be [this document](https://github.com/nteract/docs/blob/safia/oct/nteract-play-tutorial/tutorials/building-nteract-play.md), which seems to be WIP; its cousin on the master branch is just an outline.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @CrystallineCat!

For the second link, you can reference [this url](https://github.com/nteract/docs-old/blob/master/enchannel/build-your-own-repl.md) for now. We'll probably need to fit this web page into the new docs repo but I think it is OK to link to the legacy document for now.

**Comment by CrystallineCat** [comment]
Thank you!

I've fixed both links now, and I think it should be ready to merge? [Edit: looks like you're faster than me :)]

**Comment by captainsafia** [comment]
Hahaha. Yeah. I saw the notification for the PR come in through Slack. Thanks again for fixing this.
