### ISSUE TITLE
Switch webpack back to babel-loader

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#4004]
As noted in https://github.com/gaearon/react-hot-loader/blob/master/README.md#typescript, in order to use `react-hot-loader` we have to use the `babel-loader`.

> As of version 4, React Hot Loader requires you to pass your code through Babel to transform it so that it can be hot-reloaded.

During the conversion process to TypeScript I thought that in order for us to have type checking, I thought we'd have to switch over to `ts-loader` (for the sake of handling project references). It seems that we can set things up in a dual mode: type checking gets done with a rigorous tsconfig that uses project references while our webpack setup is allowed to use `babel-loader` + `react-hot-loader`.

**Comment by lgeiger** [comment]
Would switching back to babel would reintroduce #3594 due to https://github.com/babel/babel/issues/8361?

There's a discussion on the next.js repo about this problem related to HMR: https://github.com/zeit/next-plugins/issues/306

**Comment by rgbkrk** [comment]
We took the next.js apps out of the repo, so we won't run into that anymore. They'll use the transpiled packages.

**Comment by captainsafia** [comment]
We'll still need to do this.

The work to introduce babel-loader has been introduced to our test workflows during the addition of ipywidgets support. We'll need to follow this through to the source code.

**Comment by captainsafia** [comment]
Closing this since we'll realistically not be able to handle this any time soon.
