### ISSUE TITLE
ansi-to-react varying licenses

### ISSUE THREAD

**Issue by James-Quigley** [nteract/archived-desktop-app#4030]
**Application or Package Used**
ansi-to-react

**Describe the bug**
The package.json of ansi-to-react lists MPL-2.0, but the README says BSD.

**Additional context**
The global LICENSE for nteract appears to be BSD, but it looks like that change didn't propagate into the README of ansi-to-react, causing MPL-2.0 to appear on on [npm](https://www.npmjs.com/package/ansi-to-react) for ansi-to-react

This was discovered during a package audit using the tool [license-checker](https://www.npmjs.com/package/license-checker)

**Comment by captainsafia** [comment]
Thanks for bringing this to our attention. I've fixed this in https://github.com/nteract/nteract/commit/75560cc6869b25b2bba64b0d866c5cdd0f757eb2.
