### ISSUE TITLE
CORE/FETCH_CONTENT_FAILED

### ISSUE THREAD

**Issue by MatthieuMayer** [nteract/archived-desktop-app#4034]
**Application or Package Used**
nteract desktop 0.12.3

**Describe the bug**
I was working on an open file. My laptop session (MacOS Sierra) locked for a bit (but no sleep mode), when I unlocked it the file was frozen. 
- I tried exporting to pdf to check last changes, but it did not work,
-  I tried to save the file, not working. 
- I finally tried to close the file, copy it just in case, and reopening doesn't load anything and gives me this message CORE/FETCH_CONTENT_FAILED.
- I can also not open the pdf file, claiming it is an empty file (was previously about 10-12 pages).
-  I tried opening the file with another software able to manage ipynb files, it opened a blank notebook ready to go on the first cell. When I reopen that file in NTERACT it now does the same (blank file ready to go on first cell).
-When I try to open the copy file, the error message reappears and the nteract state is no kernel / not connected. But other files open with NTERACT loads normally (kernel connected).

**To Reproduce**
Unclear

**Expected behavior**
Get back to work like I did the 500,000 times before that.

**Screenshots**
![capture d ecran 2019-01-14 a 14 46 09](https://user-images.githubusercontent.com/36240861/51147069-c0cfdc00-180d-11e9-89dc-c3bdf9b277cc.png)

**Desktop (please complete the following information):**

- OS: macOS Sierra 10.12.6
- Browser: Safari 12.0.2
- Version: 0.12.3

**Additional context**
I am hopeless, my skills are not developed to solve this myself, I NEED the content of that file back... please help me !

NOTE : I cannot upload the faulty file here.

**Comment by kelleyblackmore** [comment]
Can you open the .ipynb file with a text editor?

**Comment by MatthieuMayer** [comment]
Hi Kris, 

After further investigations, I indeed tried to open my file with various softwares included text editor, all resulting in opening a blank document.
Checking the size of my file, it actually is now 0 octet so completely empty. 

There is now nothing to do to get my work back, although it could still be interesting to understand how unlocking my session completely froze NTERACT (but not the rest of my laptop functionalities), somehow created that kernel connection problem, and somehow emptied my file of all contents when trying to save it once frozen. I believe I saved a document with no connection to kernel, so probably it saved it as blank document. I don’t know I’m just throwing ideas. 

Anyways thanks for coming back at me, I’m guessing this is a rare error, plus very vague to analyse.

**Comment by kelleyblackmore** [comment]
My suggestion for the future though would be to use git to save changes.
Since I don't think we have a good recovery feature, which should we might want to consider in the future.
let me know if you need help with anything, also sorry for your loss.

**Comment by willingc** [comment]
Hi @MatthieuMayer and @kelleyblackmore, Since this issue is not reproducible, I'm going to close this issue. I did open a new issue #4052 to keep on the radar that it would be nice to document recovery options.

Please do let us know if you see this behavior again. Thanks!
