### ISSUE TITLE
Document file recovery capability for nteract desktop

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#4052]
Related to #4034

If a file is unreadable, freezes, or becomes corrupted, document what are the user options, if any, to recover.

**Comment by kelleyblackmore** [comment]
Thank you for making this is issue. I'll try to tackle this one.

**Comment by willingc** [comment]
Do you want to assign it to yourself? Thanks!

**Comment by captainsafia** [comment]
Currently, our recovery strategy will rely on auto-save. Users can set the auto-save interval in the nteract configuration file.

I'm gonna go ahead and close this since I don't think we have a robust enough document recovery story to document.
