### ISSUE TITLE
Add support for colors

### ISSUE THREAD

**Issue by bnbarak** [nteract/archived-desktop-app#4069]
# What
Overwrite the default colors values in the ANSI terminal.

# Example
For exmaple
```
const colors = { red: 'rgb(255,0,0)', green: 'rgb(0,255,0)' }
<Ansi colors={colors}>{text}</Ansi>
```

# Contribute
I can submit a pr, please let me know if this is something the team would be intrested in.

Thank you,
@comet-ml

**Comment by rgbkrk** [comment]
I'm certainly a fan, though it'll basically be a remapping of the colors that anser creates. You may want to use `anser`'s `use_classes` option as part of it.

cc @IonicaBizau

**Comment by bnbarak** [comment]
https://github.com/nteract/nteract/pull/4081

**Comment by captainsafia** [comment]
I guess we can close this now. Thank you, @bnbarak!
