### ISSUE TITLE
yarn install fails in node 11 (ABI v67) due to missing canvas-prebuilt@2.0.0-alpha.14 at that ABI

### ISSUE THREAD

**Issue by CrystallineCat** [nteract/archived-desktop-app#4070]
The install of `canvas-prebuilt@2.0.0-alpha.14` (dependency added in #4058 by @willingc) fails in Node v11.6.0:

    node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v67-linux-glibc-x64.tar.gz

It seems `canvas-prebuilt@2.0.0` (proper) is the first version to support Node 11 (ABI v67), but that release (and future releases) are no longer directly available via npm:

> Actually you can just `npm install canvas@2.0.1` and it downloads prebuilds from here! I won't be publishing `canvas-prebuilt@2.x` since I don't think there's a reason to anymore.

_Originally posted by @chearon in https://github.com/node-gfx/node-canvas-prebuilt/issues/58#issuecomment-430808805_

I'm a bit confused by the commit message of the commit that added the dependency an `canvas-prebuilt` (f7ed180878112878ea847da5d775a2fb436b39d1). The message refers to the removal of a dependency on `canvas`, which neither the commit nor the PR appear to have done. The modified `package.json` doesn't/didn't contain such a dependency.

**Comment by rgbkrk** [comment]
Would node 10 work? We tend to stay on the latest LTS release of node for the project (otherwise we're always chasing upstream fires).

**Comment by CrystallineCat** [comment]
Ah, ok, that should be fine. ABI v64 exists.

Should I put that in the documentation? I looked through README.md, USER_GUIDE.md and CONTRIBUTING.md and didn't see any notes on this.

**Comment by rgbkrk** [comment]
😬 Yeah that's a great idea. Probably should tend everyone towards that and document it.

Thank you @CrystallineCat

**Comment by willingc** [comment]
@CrystallineCat Feel free to see if removing the canvas prebuilt impacts the tests. If it doesn't, please feel free to remove. This change was part of a larger test cleanup so it may not be strictly necessary. Thanks 👍
