### ISSUE TITLE
Layout thrashing in the jupyter nteract app.

### ISSUE THREAD

**Issue by samghelms** [nteract/archived-desktop-app#4089]
**Application or Package Used**
The jupyter extension.

**Describe the bug**
Codemirror layout thrashing when rendering the code cells.

**To Reproduce**

Type anything in the web application (especially with a big notebook).

**Expected behavior**
That the editor respond in a reasonably quick fashion.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome

**Comment by samghelms** [comment]
https://github.com/nteract/nteract/blob/42d000fbcea07d7cad38f36f30421387688915d0/packages/editor/src/vendored/codemirror.ts#L501

I think this line needs to be removed.

**Comment by rgbkrk** [comment]
Oooh, good call. Thank you.

**Comment by rgbkrk** [comment]
If I remove our `height: auto;` line I end up with a big cell when I have only one line:

![screen shot 2019-01-22 at 9 18 54 am](https://user-images.githubusercontent.com/836375/51553173-0cdeda00-1e27-11e9-91d5-071d8e0fbf3c.png)

I wonder if there is more to set within codemirror options.

**Comment by samghelms** [comment]
Ah shoot. Is there any reason code mirror is being used and not monaco? Monaco seems like it could be a better choice given it has a [built in completions provider](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) and automatically uses web workers for stuff like syntax highlighting.

**Comment by rgbkrk** [comment]
That's more legacy than anything else, since CodeMirror was the de-facto good editor to use years ago. We've just carried it on. I'd love to see Monaco integrated as the main editor. I've tinkered with it in the past and noticed that each instance was had a web worker running, resulting in a heavy memory profile.

**Comment by samghelms** [comment]
I might be interested in taking that on -- this issue from the monaco github makes it seem like you can use a single web worker. https://github.com/Microsoft/monaco-editor/issues/774. I'll start playing around with it.

**Comment by captainsafia** [comment]
We're no longer setting the height via `auto` in the CodeMirror component so we can go ahead and close this issue.
