### ISSUE TITLE
Create publishing workflow for nteract web ui

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#4094]
We've got a lot of the building blocks in place for in-app publishing, including the header editor and [bookstore](https://github.com/nteract/bookstore). Here's what we need to do to finish off bookstore's ambitions for publishing:

* [x] Integrate Header Editor to be able to set fields (hook up `onChange` to set notebook metadata)
* [x] API endpoint for bookstore publish
* [x] Set flag for if bookstore is enabled for the nteract UI
* [x] Show publish button if bookstore enabled

It's likely we could use the same setup for other kinds of publishing endpoints (like our gist publishing), however this should stay small and use the bookstore setup.

**Comment by stormpython** [comment]
I've created this [Project](https://github.com/nteract/nteract/projects/7) around this issue to track its progress.
