### ISSUE TITLE
Cell Operations

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#41]
### Pure Cell
- [x] render markdown when a markdown cell
- [x] editable markdown area
- [x] render all Jupyter mimetypes (mostly - https://github.com/nteract/transformime-react/issues/1)
- [x] handler prop to notify on change of inputs
- [x] indicates when cell is hovered over with the mouse
### Draggable Cell
- [x] _has a_ cell while working well as a dnd item

**Comment by rgbkrk** [comment]
![cell states](https://media.githubusercontent.com/media/nteract/mocks/b035014e316dce7bb35dcfb9232928bf16aa8557/cell%20transitions.png)

**Comment by rgbkrk** [comment]
Something I don't think I've put anywhere else, though is currently in the implementation.

We only support code and markdown cells. No raw nbconvert and certainly no headings (those are deprecated anyways). Cut down on complexities of the original notebook UI.

**Comment by jdfreder** [comment]
I like the spinning bracket idea- that's cool!

**Comment by freeman-lab** [comment]
also a big fan of the spinning bracket! spinning vertical line is my favorite progress indicator for terminals, this would be similar to that

**Comment by rgbkrk** [comment]
I'll put the "running" indication in a new issue.

**Comment by rgbkrk** [comment]
Closed since we have the draggable cells now thanks to @jdfreder
