### ISSUE TITLE
Keybindings: Add file shortcuts

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4104]
**Is your feature request related to a problem? Please describe.**
Add `File` shortcuts to nteract.

- [x]  save => `ctrl+s`
- [x] [#4126] save as => `ctrl+shift+s`
~- [ ] open => `ctrl+o`~

This issue is a child of #4101.

**Describe the solution you'd like**
- [x] ~*Before this can be solved, #4054 needs to be merged.*~

For information on how to add shortcuts to nteract, please see [4102](https://github.com/nteract/nteract/issues/4102#issuecomment-457790015). See the list of [nteract shortcut-key](https://docs.nteract.io/#/desktop/shortcut-keys).

**Comment by stormpython** [comment]
I am going to create another issue for the `open` keybinding since more work is needed with this one.

**Comment by glitch401** [comment]
Hi ! can I take up this issue?

**Comment by stormpython** [comment]
@indranilbiswas7, thanks for volunteering, but this particular issue has already been implemented. But there are other issues within Keybinding that can be picked up here: #4101.
