### ISSUE TITLE
autosave on Mac Desktop

### ISSUE THREAD

**Issue by patricksheehan** [nteract/archived-desktop-app#4108]
Just lost a bunch of work on the Mac Desktop version because I didn't realize you haven't implemented autosave and my notebook crashed. 

**Describe the solution you'd like**
Please implement autosave on the Mac desktop client

**Describe alternatives you've considered**
For now I will save my notebooks frantically

**Comment by captainsafia** [comment]
Hello, @patricksheehan! I'm so sorry this happened. We do have auto-save implemented but something might be buggy. Can you let us know your OS version and nteract version?

**Comment by MikeYuanMY** [comment]
Hi i have the same problem as auto-save does not work.

My MacOS version is 10.14.4 and neteract version is 0.13.0

Could you also tell me what is the default time for autosave ?

not sure if it is irrelevant, 
when i tired to use `%autosave 2`, I got  

ReferenceError: IPython is not defined  
    at eval (eval at runCodeHere   (file:///Applications/nteract.app/Contents/Resources/app.asar/lib/app.js:1200:608), <anonymous>:1:1)

**Comment by MikeYuanMY** [comment]
any update on this issue? I am still having trouble with autosave on the latest release

**Comment by captainsafia** [comment]
@Mikeymice Thanks for being patient for this reply.

The default auto-save time is 30 seconds. It looks like there has been a regression and auto-save is not currently working on the desktop app.

@jdetle Any clue what might be going on here?

**Comment by Algebrazebra** [comment]
Also experiencing the same issue. I am running 
- MacOS 10.14.5
- nteract 14.4

**Comment by willingc** [comment]
Thanks for the additional report @Algebrazebra.

**Comment by captainsafia** [comment]
I think I know why this might be happening. I'll see if I can work on a fix later tonight.
