### ISSUE TITLE
Version field in connection file

### ISSUE THREAD

**Issue by 314eter** [nteract/archived-desktop-app#4120]
The version field that is added here:
https://github.com/nteract/spawnteract/blob/6b512510fc56792f78f7e142813db91e1e471767/index.js#L53-L66
is not present in the [protocol specification](https://jupyter-client.readthedocs.io/en/latest/kernels.html#connection-files). This causes problems with the [ocaml kernel](https://github.com/akabe/ocaml-jupyter).

**Comment by rgbkrk** [comment]
We also need to re-integrate `fs-kernels` into desktop as well, since desktop is still using ye old spawnteract.

**Comment by rgbkrk** [comment]
I know that as Jupyter we're thinking of adding some new fields to the connection files. Is there any way for OCaml to loosen the typing to allow for additional fields it ignores?

**Comment by 314eter** [comment]
That was already done in akabe/ocaml-jupyter#96.

**Comment by captainsafia** [comment]
Gonna go close this for now since a patch has been applied to the OCaml kernel.

Work on fs-kernels was paused so this will still need to be done in spawnteract, if it needs to be done.

I'll close this and we can revisit if it surfaces in another kernel.
