### ISSUE TITLE
Markdown editor styling

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#4134]
The codemirror editor is missing the prompt buffer on markdown cells.

![screen shot 2019-01-28 at 4 21 08 pm](https://user-images.githubusercontent.com/836375/51875167-bd157c80-2318-11e9-8381-b0833085c6e5.png)

**Comment by willingc** [comment]
@rgbkrk I'm not sure what needs to addressed in this issue. Do we want the markdown cell input sentence to be in line with the start of print and hey above it?

**Comment by rgbkrk** [comment]
Yeah, somehow we're missing the `<PromptBuffer />` component styling that was on the left.

In the past all the text would be able to be read going down the page following an imaginary line:

![screen shot 2019-02-11 at 9 10 09 am](https://user-images.githubusercontent.com/836375/52580266-da4c4f80-2ddc-11e9-8bd1-946a57b5a95f.png)

**Comment by willingc** [comment]
Perfect. Thanks for the clarification @rgbkrk

**Comment by jarmokivekas** [comment]
The prompt buffer in markdown cells would also have practical use. Currently the part of the text editor where the prompt buffer should be is a drag handle for the cell, and you can't position the text editor cursor to the left edge of the editor by clicking.

![image](https://user-images.githubusercontent.com/3074453/57274578-5f759680-70a4-11e9-9c14-e113048ad9f2.png)

**Comment by jarmokivekas** [comment]
Closing as fixed by #4396

**Comment by willingc** [comment]
Awesome! Thanks again @jarmokivekas
