### ISSUE TITLE
Keybindings: Add keyboard shortcut to open a file

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4142]
**Is your feature request related to a problem? Please describe.**
Add a keyboard shortcut for opening a file. The keyboard shortcut is `ctrl+o`.

**Describe the solution you'd like**
First, follow the steps used in PR #4138 or #4139 for hooking up the keyboard bindings. Next, an `action` and `reducer` will need to be created for opening a file. Finally, we'll need to develop an interface for opening a new file or redirect the user to the `directory` view.

**Describe alternatives you've considered**
N/A

**Additional context**
Pulled from issue #4104.

**Comment by rgbkrk** [comment]
It's ok if the open keybinding just redirects to the directory listing in a new tab for now. That's what the menu does.
