### ISSUE TITLE
Menu: Gap between toolbar and dropdown

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4149]
**Application or Package Used**
nteract web

**Describe the bug**
There is a gap between the toolbar and dropdown.

**To Reproduce**

1. Open up a notebook file.

**Expected behavior**
There should be no gap between the toolbar and the dropdown.

**Screenshots**

![image](https://user-images.githubusercontent.com/3149785/52009101-ece29280-2486-11e9-9d6f-d9e0682b2dbd.png)

**Comment by stormpython** [comment]
This issue was created from #4148.

**Comment by rgbkrk** [comment]
I'm going to solve this by switching us to Blueprint's `<Popover>` + `<Menu>` components:

* https://blueprintjs.com/docs/#core/components/popover
* https://blueprintjs.com/docs/#core/components/menu

Which should allow the style of the menu to match that of the blueprint modal that comes up for editing to solve #4150

**Comment by captainsafia** [comment]
Closing this out now that we have switched over to Blueprint for our top-level menu.
