### ISSUE TITLE
Menu: toolbar menu shown when rename modal open

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4150]
**Application or Package Used**
nteract on web

**Describe the bug**
The toolbar menu does not fade out when rename modal is shown.

**To Reproduce**

1. Open a notebook file
2. Click on the file title in the header

**Expected behavior**
The toolbar menu should fade out.

**Screenshots**
![image](https://user-images.githubusercontent.com/3149785/52009279-6b3f3480-2487-11e9-80b6-348490521d9d.png)

**Comment by stormpython** [comment]
This issue was created from #4148.

**Comment by captainsafia** [comment]
Closing since were deprecating the Jupyter extension.
