### ISSUE TITLE
Directory Listing: should show directories, notebooks, then files

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4155]
**Is your feature request related to a problem? Please describe.**
The `Directory Listing` view should show directories, notebooks, and then other files in that order.

**Describe the solution you'd like**
Need to add sorting logic for display

**Describe alternatives you've considered**
N/A

**Comment by stormpython** [comment]
This issue was created from #4148.

**Comment by captainsafia** [comment]
This is something that can be addressed in the implementation of our upcoming UI overhaul.

**Comment by captainsafia** [comment]
Closing this since we are deprecating the Jupyter extension.
