### ISSUE TITLE
Reduce bundle size for nteract web

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#4160]
<img width="1552" alt="screen shot 2019-01-31 at 9 46 34 am" src="https://user-images.githubusercontent.com/836375/52073754-2b3a8900-253d-11e9-96c8-5c93343ff2b3.png">

<img width="1234" alt="screen shot 2019-01-31 at 9 48 06 am" src="https://user-images.githubusercontent.com/836375/52073833-5624dd00-253d-11e9-8c5a-970b0e9a75ca.png">

A few easy wins I see:

* Move to CodeMirror CSS and Blueprint CSS as static css files
* Move all the store setup to be asynchronously loaded with `import`
* Show the nteract animation on start

I'm seeing a few other areas in the bundle analyzer that are suspect:

* What's using `refractor`?
* What needs `moment` on startup?
* Does the interdependence on `@nteract/types` and `@nteract/commutable` make it hard to break the chunks up?

## Try it yourself!

```
cd applications/jupyter-extension/nteract_on_jupyter
```

Generate statistics with:

```
npx webpack --profile --json > stats.json
```

Generate HTML page with:

```
npx webpack-bundle-analyzer stats.json --mode static
```

**Comment by rgbkrk** [comment]
If you want to see the current bundle, I've also uploaded the report statically: https://report-kmhandtxkg.now.sh/

**Comment by lgeiger** [comment]
> What needs `moment` on startup?

I can tackle that on Saturday (maybe even earlier).
It's only used in the header component of the jupyter extension. We can remove it and use the same approach as in the desktop status bar which uses `date-fs` and is already included in the bundle.

**Comment by rgbkrk** [comment]
Note: with the latest changes on master that diagram should be updated.

**Comment by lgeiger** [comment]
> What's using `refractor`

It's used by `react-syntax` highlighter which we only need for the static version of the notebook.

**Comment by captainsafia** [comment]
Here's the latest data on this.

<img width="1177" alt="Screen Shot 2019-12-08 at 6 22 55 PM" src="https://user-images.githubusercontent.com/1857993/70402325-d5016680-19e7-11ea-8a5c-1cd512db20f5.png">

Our biggest culprits at the moment are Plotly.js and the Monaco editor.

**Comment by captainsafia** [comment]
Closing this since we will be deprecating the Jupyter extension soon.
