### ISSUE TITLE
404 loading MathJax fontdata.js

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#4175]
I don't use MathJax, but just wanted to report this error from the jupyter console in case anyone is more meaningfully impacted by it.

Error in the terminal which launched Jupyter:
```
[W 10:24:30.548 NteractApp] 404 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?V=2.7.4 (::1) 54.15ms referer=http://localhost:8888/nteract/edit/Test.ipynb
```

A similar error is shown in the Chrome console.

Notably I can see other MathJax components loading fine in Chrome's Network tab.

**Application or Package Used**
nteract_on_jupyter @ fba3ad9cf84c577d7ebdca496802f915fff119ac
Run using `jupyter nteract --dev`.

**Comment by rgbkrk** [comment]
We rely on the config value set for `NotebookApp.mathjax_url`, which is documented as:

```
NotebookApp.mathjax_url : Unicode
Default: ''

A custom url for MathJax.js. Should be in the form of a case-sensitive url to MathJax, for example: /static/components/MathJax/MathJax.js
```

I thought for sure there was a MathJax installation step for `jupyter notebook` you can opt in too, but my limited googling is having trouble. [Old documentation points to an old `IPython` entrypoint for it `python -m IPython.external.mathjax`](https://ipython.org/ipython-doc/3/install/install.html#mathjax). Any ideas here @mpacer?

**Comment by jameskoch** [comment]
Some of the MathJax URLs which load fine are:

http://localhost:8888/static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&delayStartupUntil=configured

http://localhost:8888/static/components/MathJax/config/TeX-AMS-MML_HTMLorMML-full.js?V=2.7.4

http://localhost:8888/static/components/MathJax/config/Safe.js?V=2.7.4

http://localhost:8888/static/components/MathJax/extensions/Safe.js?V=2.7.4

**Comment by captainsafia** [comment]
Closing this in favor of #3364 which captures issues with rendering MathJax in general. We should figure out what is going on here.
