### ISSUE TITLE
Kernel relay raises error if non-directory is found in a kernels directory

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#4187]
right now if you try to list all kernelspecs you get an error if there is a non-directory in the kernels directory.

Query:
```
query GetKernels {
  listKernelSpecs {
    name
  }
}
```

```
{
  "errors": [
    {
      "message": "ENOTDIR: not a directory, scandir '~/Library/Jupyter/kernels/.DS_Store'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listKernelSpecs"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errno": -20,
          "code": "ENOTDIR",
          "syscall": "scandir",
          "path": "~/Library/Jupyter/kernels/.DS_Store",
          "stacktrace": [
            "Error: ENOTDIR: not a directory, scandir '~/Library/Jupyter/kernels/.DS_Store'"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by mpacer** [comment]
I think that this likely is what needs to be modified (or earlier in the process so that the non-directories are filtered out earlier): https://github.com/nteract/nteract/blob/master/packages/fs-kernels/src/kernelspecs.ts#L79-L89

**Comment by emzeq** [comment]
Could `jupyter kernelspec list --json` be used for querying these kernel specs?

**Comment by captainsafia** [comment]
@emzeq Sorry just seeing this! That's certainly a good idea. Do you wanna take a stab at refactoring `kernels.ts` to invoke that command?

**Comment by emzeq** [comment]
@captainsafia Sure thing. Will take a crack at it this weekend.

**Comment by emzeq** [comment]
Can we assume users will have Jupyter installed? It looks like Nteract only requires a kernel: https://nteract.io/kernels

**Comment by captainsafia** [comment]
Yes, `jupyter` is installed as a dependency by the ipykernel.

**Comment by emzeq** [comment]
Great! Here's the PR: https://github.com/nteract/nteract/pull/4202
