### ISSUE TITLE
Pandas output table overflow

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#420]
Fat pandas! 🐼 

![screen shot 2016-05-02 at 12 23 33 pm](https://cloud.githubusercontent.com/assets/1857993/14961768/06c0e2fc-1061-11e6-806f-557f9df1ff6c.png)
![screen shot 2016-05-02 at 12 23 31 pm](https://cloud.githubusercontent.com/assets/1857993/14961767/06bf3fba-1061-11e6-837a-5bd68e70f457.png)

**Comment by betatim** [comment]
#407 might be related or at least worth thinking about if they can be fixed in a similar way

**Comment by rgbkrk** [comment]
That table is so fat.

**Comment by rgbkrk** [comment]
What do we need to do for this? What's the expected layout?
