### ISSUE TITLE
Cell execution is slow

### ISSUE THREAD

**Issue by jdfreder** [nteract/archived-desktop-app#422]
Both Ctrl-Enter and Shift-Enter cell execution seems to be really slow.  It's not clear to me at all why this is happening, but it wasn't happening in earlier commits and is even slower than jupyter/notebook.

**Comment by rgbkrk** [comment]
Just "figured out" one of our performance problems. React is always running in dev mode right now because we don't set `process.env.NODE_ENV` to `"production"`.

**Comment by captainsafia** [comment]
💩 ! This makes all our builds fail!

**Comment by jaredly** [comment]
execution doesn't seem slow at all to me :/ @jdfreder are you still experiencing this? And was it on a large, complex notebook, or did it also happen w/ a fresh notebook just evaling e.g. `2+2`?

**Comment by jdfreder** [comment]
Hey @jaredly , thanks for looking into this.  Actually, I think I may have "fixed" (maybe just covered up) the actual problem when I sped up nteract using the PureRenderMixin (in master).

**Comment by rgbkrk** [comment]
This seems to not be an issue right now, feel free to re-open.
