### ISSUE TITLE
Update Redux AppState for publishing to S3

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4228]
The `AppState` will need to be updated for publishing to S3. At least, the state will need to store whether publishing (to bookstore) is enabled.

**Comment by rgbkrk** [comment]
The S3 bucket address is stored serverside and the frontend doesn't need to know it: https://github.com/nteract/bookstore#configuration

I've updated the description above to reflect that.

**Comment by stormpython** [comment]
Thanks for the clarification @rgbkrk

**Comment by stormpython** [comment]
Ok, so the `AppState` only needs to know that `Bookstore` is enabled. Due to some [issues](https://github.com/nteract/nteract/pull/4144) around how `Bookstore` validations works on the server side, we decided as a work around for now, we will check for `Bookstore` validation on the frontend, in the nteract app.

So, when the app initialized, it should send an async request for bookstore validation, which should return an `object` as follows:

```javascript
{
  "bookstore_valid": bool,
  "archive_valid": bool,
  "publish_valid": bool
}
```

This will then be stored in `Appstate.core` as `bookstore`.

**Comment by stormpython** [comment]
In order to update the `AppState`, the `@nteract/types` needed to be updated.
`packages/types/src/index.ts`

```javascript
export interface BookStore {
  bookstore_valid: boolean;
  archive_valid: boolean;
  publish_valid: boolean;
}

export interface StateRecordProps {
  kernelRef: KernelRef | null;
  currentKernelspecsRef?: KernelspecsRef | null;
  entities: Immutable.RecordOf<EntitiesRecordProps>;
  bookstore?: BookStore | null;
}

export const makeStateRecord = Immutable.Record<StateRecordProps>({
  kernelRef: null,
  currentKernelspecsRef: null,
  entities: makeEntitiesRecord(),
  bookstore: null
});
```

And, I needed to update the reducers
`packages/reducers/src/core/index.ts`

```javascript
const bookstore = (state = "", action: Action) => {
  return state;
};

const core = combineReducers(
  {
    currentKernelspecsRef,
    entities,
    kernelRef,
    bookstore
  },
  makeStateRecord as any
);
```

**Comment by stormpython** [comment]
Change of plans, `bookstore` will now be saved at `Appstate.app.host` as an object with the following interface

```javascript
interface Bookstore {
  version: string;
  enabled: boolean;
}
```
