### ISSUE TITLE
Feature request: better support for virtualenvs

### ISSUE THREAD

**Issue by AlJohri** [nteract/archived-desktop-app#4245]
I've noticed Visual Studio Code has recently improved python + virtualenv + jupyter support by leaps and bounds. I wonder if some of those features can be ported into nteract. I'm particularly interested in better support for ipykernels isolated within virtual environments.

When I open VSCode and point it to a directory that uses a virtualenv, after clicking on my first python file, it automatically picks up that I'm using a virtualenv. 

<img width="679" alt="screen shot 2019-02-28 at 12 57 44 pm" src="https://user-images.githubusercontent.com/2790092/53587472-7786e200-3b58-11e9-85ab-adf53bdcba7f.png">

For example, in the screenshot above, as soon as I clicked on `test.py`, VSCode activated the Python extension and detected that the "closest" virtualenv in this case is from pipenv. On the bottom left hand you can see it says: `Python 3.7.2 64-bit ('diversity': pipenv)`.

Even nicer, is that I can click on the bottom left and it shows me several different `python` I can choose from.

<img width="634" alt="screen shot 2019-02-28 at 12 46 41 pm" src="https://user-images.githubusercontent.com/2790092/53586819-f7ac4800-3b56-11e9-8700-7dbb9451f3c7.png">

If I add `#%%` to signify that the python file is actually a notebook, a Run Cell button appears above it. Clicking `Run Cell` automatically starts a Juptyer server within that virtualenv.

<img width="1241" alt="screen shot 2019-02-28 at 12 54 39 pm" src="https://user-images.githubusercontent.com/2790092/53587356-1e1eb300-3b58-11e9-8444-e32c0f78a878.png">

-----------------------------

If nteract could allow 1) selecting which virtualenv to use within the GUI and then 2) later add some autodetection to figure out which virtualenv, I think this would greatly improve the user experience. 

Some autodetections strategies could be if a Pipfile or `.venv|venv` folder exists in the same or one directory above an ipynb file, defaulting to that virtualenv.

Apologies if this has been discussed in great length before! I'm just coming back to nteract and would love to just double click on notebooks in Finder and use them. Up until now I've had to activate the virtualenv and then run nteract from the CLI.

**Comment by sammdu** [comment]
Hey, @willingc 

Any progress on this feature yet?
I would love to start using nteract in place of Jupyter web interface, but it's hard to do since I work with virtualenv's a lot.

Thanks!

**Comment by captainsafia** [comment]
Hello @sammdu! There hasn't been any work on this feature yet. There's a related feature tracking the ability to resolve kernel dependencies when the user launches nteract.

@fabric-8 Bringing this up to your radar for design work. One of the user scenarios is to select the environment they would like to use for their kernel. Ideally, this would be some sort of picker. You can check out the screenshots of VS Code above for inspiration.

**Comment by captainsafia** [comment]
I think we'll have this resolved once we release the latest version of the nteract desktop app with the changes that were made in https://github.com/nteract/jupyter-paths/pull/33.

I'll go ahead and close this issue but now please re-open if you do run into the same problems in the April release of nteract.
