### ISSUE TITLE
Uncaught TypeError hangs desktop app when misusing $$.text

### ISSUE THREAD

**Issue by mstetson** [nteract/archived-desktop-app#4254]
**Application or Package Used**
nteract desktop 0.12.3 on macOS

**Describe the bug**
In a Node.js notebook, if you pass a number to `$$.text()`, the following error appears on the developer tools console:

```
Uncaught TypeError: Data for text/plain is expected to be a string or an Array of strings
    at app.js:35
    at h (app.js:35)
    at Array.reduce (<anonymous>)
    at m (app.js:35)
    at b (app.js:35)
    at app.js:16
    at app.js:16
    at e (app.js:16)
    at e (app.js:16)
    at e (app.js:16)
```

From that point, the notebook window cannot be closed. Its status always shows busy. The kernel cannot be killed or restarted. The only way forward is to force quit the application or otherwise kill its OS processes.

**To Reproduce**

1. Open a new notebook via *File > New > Node.js (nteract)*
2. Type the following in the first code cell: `$$.text(1)`.
3. Run the cell.

**Expected behavior**
I would expect the cell's output to show an error and the application to allow the code to be fixed without a restart.

**Screenshots**
![menubar_and_untitled_-_busy_and_new_issue_ _nteract_nteract](https://user-images.githubusercontent.com/1238707/53828817-ef2f8500-3f3b-11e9-9baf-4e83afad40d2.png)

**Desktop (please complete the following information):**

- OS: macOS 10.14.3
- Browser: n/a
- Version 0.12.3

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @mstetson!

I'm able to reproduce the issue in the release version of nteract, but not on the development branch. So it appears that this issue was resolved in the changes recently made to output rendering. I'll keep this open until a new desktop release is cut with the fix.

**Comment by mstetson** [comment]
That's great news, @captainsafia. Thanks!

**Comment by captainsafia** [comment]
Following up on this, @mstetson!

Do you run into this issue when using nteract v0.13.0?

**Comment by mstetson** [comment]
Thanks for the follow up, @captainsafia. I just retested in v0.13.0 and it looks fixed. Closing. Thanks again!
