### ISSUE TITLE
Data Explorer width is based on the viewport

### ISSUE THREAD

**Issue by dylanross3** [nteract/archived-desktop-app#4257]
**Application or Package Used**
Data Explorer

**Describe the bug**
Most of the views in the Data Explorer have CSS that sets the width according to the size of the viewport (e.g., `calc(100vw - 150px)`). This creates overflow issues when including the Data Explorer inside an application that has sidebars.

**Comment by BenRussert** [comment]
@dylanross3 Thanks for opening this issue! Was this also covered by #4259?

BTW, I'd be interested to see what you are working on with the data-explorer component if it's public!

**Comment by dylanross3** [comment]
@BenRussert Yep, that resolved it. Closing.

Sorry, but my project is very much closed source for now. :(
