### ISSUE TITLE
The gatsby nteract renderer/previewer have broken links!

### ISSUE THREAD

**Issue by choldgraf** [nteract/archived-desktop-app#4263]
This is related to the nteract Gatsby plugin for Jupyter Notebooks:

https://www.gatsbyjs.org/packages/@gatsby-contrib/gatsby-transformer-ipynb/?=ipynb

I'm looking into using the transformer to see if we could build a gatsby backend for jupyter-book. The nteract components page is so cool! And I'd love for the notebook to be a "first class citizen" in the build system, rather than having to convert it to markdown first.

However, it seems that this plugin is just for reading/representing the data of notebooks. 
There are links for a "renderer" (https://github.com/nteract/nteract/tree/master/packages/notebook-render) and a "preview" (https://github.com/nteract/nteract/tree/master/packages/notebook-preview) plugin, but they're both broken.

So I guess this issue is 50% bug report (those links are broken :-) ) 50% question: is the gatsby plugin still being worked on? Or are, e.g., the render and preview packages sunsetted?

(also apologies if these questions are super naive...I am a total react/gatsby n00b!)

**Comment by captainsafia** [comment]
Hi @choldgraf! I think @benjaminabel would be the best person to help with this. He created the Gatsby plugin.

It was recently moved to the gatsby-contrive package and I believe now uses a different preview system. You can read https://github.com/nteract/nteract/issues/4060 for more info. Let me know if this helps.

**Comment by ghost** [comment]
@choldgraf the notebook-render package has moved to @gatsby-contrib, so I open the issue there and close it here.

**Comment by choldgraf** [comment]
ahhh ok - thanks for noticing and doing that @benjaminabel :-)
