### ISSUE TITLE
Opening and saving a Jupyter Notebook changes the whole indentation

### ISSUE THREAD

**Issue by YtvwlD** [nteract/archived-desktop-app#4273]
**Application or Package Used**
nteract desktop

**Describe the bug**
Opening and saving a Jupyter Notebook changes the whole indentation

**To Reproduce**
1. Clone a Git repo containing a Jupyter Notebook.
2. Open the notebook with nteract.
3. Save the notebook.
4. Have a huge diff in git, because the JSON file is indented with two spaces instead of one.

**Expected behavior**
No or a small diff.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version 0.12.3

**Comment by captainsafia** [comment]
Hi @YtvwlD! Thanks for opening this issue.

We process and parse the JSON contents of the notebook using Node's default stringify and parse functions which affect the spacing in this way. Given that  2-space indentation is the standard for JSON, I don't think we will be changing this any time soon.

If you'd like to be able to diff notebooks, you might want to check out (nbdime)(https://github.com/jupyter/nbdime). It allows you to diff the contents of cells as opposed to the JSON and provides more meaningful feedback than a Git diff.

Let me know if this is helpful!
