### ISSUE TITLE
VDOM outputs are not being displayed

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#4274]
**Application or Package Used**
This affects nteract_on_jupyter. It probably affects nteract_desktop but I haven't tested for that

**Describe the bug**
Vdom outputs are not being displayed.

This may relate to them not being recognized and being given an `Unknown` output component.

![image](https://user-images.githubusercontent.com/2482408/54154458-2b148f80-43ff-11e9-92d6-d7b9e50b9ca2.png)

**To Reproduce**

```python
import vdom
display(vdom.p("show me anything"))
```

**Expected behavior**
It should display vdom outputs.

**Screenshots**
I linked it above but since this is hear
![image](https://user-images.githubusercontent.com/2482408/54154501-41225000-43ff-11e9-9c98-27c3adff3adf.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome, safari

**Comment by captainsafia** [comment]
Are you running this off master? VDOM support was recently added in https://github.com/nteract/nteract/commit/236c1baa94ac615c9042cf774aa160ad13088ed9#diff-1f2034f4b2d262ef2856991e9b5cc1f7 but may not be present in the version of the Jupyter extension that you are running.

**Comment by mpacer** [comment]
That was the issue — when run off master it worked but not on our deployed version.
