### ISSUE TITLE
Latest release of the Jupyter extension not yet on PyPi

### ISSUE THREAD

**Issue by BenRussert** [nteract/archived-desktop-app#4276]
v2.0.7 is not yet available on [PyPi](https://pypi.org/project/nteract-on-jupyter/#history). I see [the script here](https://github.com/nteract/nteract/blob/master/applications/jupyter-extension/package.json#L7), but don't know how the releases work for jext or if we intended to ship it.

I've been dogfooding this more at work with the recent progress, so I always like to stay up to date :arrow_up:

**Comment by captainsafia** [comment]
I'll publish this to PyPi tomorrow. I'll also be sure to include instructions on publishing to PyPi in the docs.

**Comment by BenRussert** [comment]
Cool, thanks Safia! I guess I assumed it was automatic with the github release, but now I see the npm script in there.

**Comment by captainsafia** [comment]
And done! Give it a go. By the way, do you want me to add you to our PyPi project so you can publish yourself as you're starting to use the extension more?

**Comment by BenRussert** [comment]
I'd love that, thanks!
