### ISSUE TITLE
Set python path for portable running

### ISSUE THREAD

**Issue by duytrung** [nteract/archived-desktop-app#4281]
**Is your feature request related to a problem? Please describe.**
I ran python in a university computer, it could run but not with Nteract
**Describe the solution you'd like**
Nteract requires a python environment that has been set up with system paths.

**Describe alternatives you've considered**
I expected an option in Nteract to allow users to show Nteract where the custom python folder located. Therefore, Nteract can use python without having to have admin rights to install.

**Additional context**
No screenshot needed, I have read similar thread such as "https://github.com/nteract/nteract/issues/1887" but I think my ideas travelled further than that thread.

**Comment by BenRussert** [comment]
What method did you use to install your [python kernel?](https://nteract.io/kernels)

**Comment by duytrung** [comment]
Hi @BenRussert ,

I copied the folder of Anaconda to my USB. It can run, for example, jupyter application in there. But not sure how to figure out the path to run nteract. 

My apologies for late reply.

**Comment by BenRussert** [comment]
Do you have an anaconda console? You should be able to launch nteract from a terminal that way and keep the same environment variables as that terminal. `nteract ./something.ipynb` for example
