### ISSUE TITLE
Don't focus on editor when cell clicked

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#429]
Currently when you click in the output area it focuses the cursor in the editor. This is great for the sake of focusing the cell. It's not so great when you want to select outputs (especially if the overall output is fairly large).

**Comment by jdfreder** [comment]
This is much harder to fix than it seems.  Simply not focusing the CM el on cell focus would break keyboard navigation.  We will need more state, specifically an "input is focused" boolean.

**Comment by rgbkrk** [comment]
This one definitely needs some thinking and iterating.

**Comment by rgbkrk** [comment]
Done in #1167.
