### ISSUE TITLE
Google Colab does not recognize the files edited by nteract

### ISSUE THREAD

**Issue by tofighi** [nteract/archived-desktop-app#4290]
MacOS, Version 0.12.3

I created a notebook using nteract and tried to upload to [Google Colab](http://colab.research.google.com), but Google Colab does not open it and complains:

> ### Notebook loading error
> There was an error loading this notebook. Ensure that the file is accessible and try again.
> Attempted to load an unsupported notebook format; version 4.4
> 
> https://drive.google.com/drive/?action=locate&id=1f_w4fBW-us5uR9SFvNXDRaxNndlMruZV&authuser=0
> 
> Attempted to load an unsupported notebook format; version 4.4
> CustomError: Attempted to load an unsupported notebook format; version 4.4
>     at new qy (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:1347:363)
>     at AB (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:1450:260)
>     at https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:1625:511
>     at e.onFulfilled (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:795:216)
>     at Vk (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:799:306)
>     at Rk (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:799:164)
>     at zk.executeCallbacks_ (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:798:359)
>     at rj (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20190320-085300-RC00_239405931:759:551)

**Comment by captainsafia** [comment]
Thanks for opening up this issue, @tofighi! Can you upload the notebook you attempted to load to a GitHub gist or repo so that we can diagnose what might have happened?

If the error message is accurate, this might be an issue with Google's Colab product. The latest supported version of the notebook format is 4.4 and has been so for a while. Seeing the content of the notebook might help us determine if it is a parsing issue or not.

Also, are you able to open the notebook you created in Jupyter classic or JupyterLab? If so, it might mean that the issue is with CoLab specifically.

**Comment by blois** [comment]
Thanks @tofighi- this is an issue that Colab should fix, I opened https://github.com/googlecolab/colabtools/issues/490, will try to get on it ASAP.

**Comment by captainsafia** [comment]
Thanks for chiming in, @blois!

I'm going to go ahead and close this issue so it can be tracked under the Colab project.

**Comment by blois** [comment]
I'd like to use nteract to generate a notebook for Colab's compatibility testing but using the latest published version (v2.0.7) I'm getting v4.2 notebooks which do open correctly. Looking at the code it looks like it's still generating v4.2- https://github.com/nteract/nteract/blob/08595712cc379dbb17797df35c543fb593e799e1/applications/jupyter-extension/nteract_on_jupyter/app/triggers/open-notebook.ts#L57

For what it's worth, I believe JupyterLab is sitll generating v4.2 as well:
https://github.com/jupyterlab/jupyterlab/blob/d5539206d9d8e45d1709c56cce46dd59d2fe9d58/packages/coreutils/src/nbformat.ts#L22

**Comment by jasongrout** [comment]
For what it's worth, there seems to be some confusion around exactly what the minor version of the notebook format spec is. See https://github.com/jupyter/nbformat/issues/138 where I tried to lay out some of the conflicting information.
