### ISSUE TITLE
Julia support

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#430]
I spent some time evaluating Julia support within nteract and noticed a few things:
- Lack of interactivity when using Gadfly. Plots look nice though:

<img width="660" alt="screenshot 2016-05-06 09 52 46" src="https://cloud.githubusercontent.com/assets/836375/15076578/08398b04-1370-11e6-916f-9a740efd6aff.png">
- Trying to execute code before the Julia kernel is fully started results in a broken notebook setup (can't execute further code).

There is an inconsistency in the name we're setting in the metadata on the notebook and what the original spec name is (I'll save a Julia notebook then when I open it, in the console it says that the spec is not available).

**Comment by willingc** [comment]
Which kernel were you using?

**Comment by rgbkrk** [comment]
IJulia

It's possible @jdfreder "fixed" this with a delayed startup from the kernel, waiting for the first idle status (done in widgets PR #487).

**Comment by willingc** [comment]
I haven't tried with gadfly but Julia looks good. In fact, all looks really good 👍

**Comment by rgbkrk** [comment]
The "don't execute too early" bug has been fixed by making our epics more resilient. We need some better UI/UX when a kernel is slow to start, which I'll outline in another issue.
