### ISSUE TITLE
Update RELEASING.md

### ISSUE THREAD

**Issue by stormpython** [nteract/archived-desktop-app#4301]
**Is your feature request related to a problem? Please describe.**
The information for how to release packages is scattered in the different README docs.

**Describe the solution you'd like**
Move all releasing related info with `lerna` from the project `README.md` to `RELEASING.mc`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by captainsafia** [comment]
This can be closed as I addressed this in https://github.com/nteract/nteract/commit/e734f3dc8c0a79a597a79cafaaa7831f7d15ecb9.
