### ISSUE TITLE
Data Explorer should not require importing react-table styles

### ISSUE THREAD

**Issue by dylanross3** [nteract/archived-desktop-app#4306]
**Application or Package Used**
Data Explorer

**Describe the bug**
Currently, the Data Explorer package README explains I must import the CSS for `react-table`.

```
// CSS for the grid view on the data explorer
import "react-table/react-table.css";
```

It goes against best practices in the NPM ecosystem to import transitive dependencies. This is because where NPM chooses to place a package depends on the whole dependency graph, so `react-table` may not be hoisted to the top level if two different packages depended on different versions of it for instance, meaning the consumer of the Data Explorer package may have to do `import "@nteract/data-explorer/node_modules/react-table/react-table.css"` to workaround. This scenario could easily occur to a consumer when they simply update some packages.

**Expected behavior**
The `react-table` dependency should either be listed as a peer dependency, meaning the consumer of the Data Explorer must bring it in, or the Data Explorer package should import the styles itself.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @dylanross3! We're currently in the process of revamping the Data Explorer and improving the way it handles style dependencies. @emeeks can share more on this if you are interested in helping with the effort.

**Comment by BenRussert** [comment]
The react-table styles could probably be vendorized the way we tried with blueprint without the performance issues. Blueprint's stylesheet was 7000+ lines of css where react-table's is more like 100-200.
