### ISSUE TITLE
Exception in https://semiotic.nteract.io/ demo page prevents the application from rendering

### ISSUE THREAD

**Issue by elmarquez** [nteract/archived-desktop-app#4308]
The page renders momentarily and then dies due to the following exception:

```
react-dom.production.min.js:198 DOMException: Failed to execute 'querySelector' on 'Document': '#/' is not a valid selector.
    at t.<anonymous> (https://semiotic.nteract.io/static/js/main.ec009d7e.js:1:50071)
```
The issue originates in the MarkdownPage component at line 40:

```
  const element = document.querySelector(window.location.hash)
```
because there is no match.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @elmarquez!

@susielu Do you know what might be going on?

**Comment by susielu** [comment]
Can you explain to me in what context it's dying for you? I haven't worked outside of the `semiotic-docs` repo and don't know how that code fits together with other code or commands run in nteract. I thought it was a standalone repo/deploy setup.

**Comment by elmarquez** [comment]
The publicly hosted page was not loading for me:

`https://semiotic.nteract.io`

I'm on a different laptop right now and its currently loading without any problems. Perhaps there is some kind of timing issue.

**Comment by captainsafia** [comment]
Thanks for the follow-up, @elmarquez!

Do let us know if you run into this issue again or if it occurred on a particular browser/operating system.

I'm going to go ahead and close this issue now but feel free to re-open if the problem persists.
