### ISSUE TITLE
Pinning cell

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#431]
Many times when a user is working on a visualization, they want to be able to see the results of one cell (the outputs), all the time, even while editing code far up in the notebook. We need to provide some way to pin a cell so it's in view constantly.

@jdfreder said that this was implemented in the jupyter/notebook at least as an extension sometime in the last year. We should revisit that here, make mocks, and explore what the user experience could be like.

**Comment by rgbkrk** [comment]
Looks like it was https://github.com/jupyter/notebook/issues/1116, which was a wholly different use case than I outlined above, also assisted by the frozen/pinned cell. Another semi-related concept is @minrk's scratch cell.

**Comment by captainsafia** [comment]
> @jdfreder said that this was implemented in the jupyter/notebook at least as an extension sometime in the last year. We should revisit that here, make mocks, and explore what the user experience could be like.

Yep. There was a working extension and I think there was great progress made on a sticky cell PR at some point in the Notebook.

**Comment by rgbkrk** [comment]
Sticky cell! I love that name.

**Comment by betatim** [comment]
Being able to pop-out a cell would be useful too. If the visualisation takes up a lot of screen space then it would be cool to have it in a separate window. Means you can see more than a few lines of the code that you are trying to edit.

**Comment by jdfreder** [comment]
I have a mock for this, I'll try to upload it later today

**Comment by rgbkrk** [comment]
Popping out a cell would be wonderful!

Doing so does completely break some features that people come to rely on:
- Globally defined JavaScript (from another cell) would no longer be defined/shared
- HTML templates (declarative widgets) would not work

That being said, we could do comms across to another window with no problem and would be a really good introduction to doing our model for realtime (just for yourself).

I'd start with only the local pinning for now and come back to the "separate window" idea.

**Comment by jaredly** [comment]
@rgbkrk popping out a cell in a separate window would also be weird because in electron, separate windows are separate processes, so communication is weird.
I'd be all for having a "popped out cell" that just floats above the other stuff, but not in a separate window

**Comment by rgbkrk** [comment]
I'd love to see that too!

**Comment by rgbkrk** [comment]
This was implemented sometime ago. The subtopic for popping out a cell should be opened as a new issue if folks are interested.
