### ISSUE TITLE
sos notebooks integration

### ISSUE THREAD

**Issue by KnutJaegersberg** [nteract/archived-desktop-app#4310]
Hi,
It would be handy to also work on multilingual notebooks in nteract, i.e. via the sos kernel. 

https://vatlab.github.io/sos-docs/index.html#content

When I install the sos kernel and open nteract, it only says that the sos is launching, but that never finishes.

**Comment by KnutJaegersberg** [comment]
Turns out, after a reboot it works anyway. Then you just need to switch the kernels manually with the %use command, %use R.

**Comment by captainsafia** [comment]
Thanks for posting the follow-up, @KnutJaegersberg! I will go ahead and close this issue.
