### ISSUE TITLE
Leaflet map overflows status bar

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4316]
**Application or Package Used**
nteract Desktop

**Describe the bug**
The Leaflet map overflows and is above the status bar when scrolling on macOS.

**To Reproduce**

1. Open the GeoJSON example notebook under Examples > Python.
2. Scroll down.

**Expected behavior**
The map should remain behind the status bar.

**Screenshots**
<img width="912" alt="Screen Shot 2019-04-01 at 10 12 04 PM" src="https://user-images.githubusercontent.com/1857993/55373769-d7f89e80-54cb-11e9-9a25-932f04010e36.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version nteract 0,13

**Comment by rganardi** [comment]
@captainsafia what do you mean by the map overflows? Is it just that it appears over the status bar, or is it supposed to be a scrollable element?

On a related note, it seems that I can't get the GeoJSON displayed (usually there would be marker for every point). Is this a known issue?

**Comment by captainsafia** [comment]
@rganardi That's what I meant by overflows. It appears over the status bar when it should really be behind it at all times and scroll with the page.

As for the maps not rendering, I believe there is an open issue around GeoJSON styling, although I'd have to confirm if it was recently closed or not.

Do you have a screenshot or notebook you can share? What version of nteract is this happening in?
