### ISSUE TITLE
sos notebook code completion

### ISSUE THREAD

**Issue by KnutJaegersberg** [nteract/archived-desktop-app#4320]
Hi,
When using sos notebooks kernel, I cannot use code completion in the r/python/julia kernel within the sos kernel. 
This works on jupyter notebooks without problems, I have the problem on two different machines. 
Since coding / experimenting in several languages is handy, I would like to use this feature in nteract, too, otherwise, I feel myself drawn towards regular jupyter. Code completion is too important, also in multilanguage environments. 

Examples:
![jupyter_works](https://user-images.githubusercontent.com/17965169/55555461-9b07f400-56e5-11e9-8277-8cc6e20588ea.png)

![nteract_sos_codecompletion_no](https://user-images.githubusercontent.com/17965169/55555478-9fcca800-56e5-11e9-863c-a28a6f85dd84.png)

**Comment by KnutJaegersberg** [comment]
and yes i know that for code completion you have to use not tab as in jupyter but control space!

**Comment by KnutJaegersberg** [comment]
Also, currently there is an issue with code completion in jupyter, so I needed to set 

c.IPCompleter.use_jedi = False
in my .ipython/profile_default/ipython_kernel_config.py

**Comment by captainsafia** [comment]
Hello @KnutJaegersberg!

Thanks for opening this issue! I'm only slightly familiar with the SOS experience in JupyterLab but I believe that it requires the installation of an extension? From my understanding, that extension adds a lot of functionality, like the language dropdown, that is needed for SOS.

nteract doesn't currently support these extensions so working with SOS in nteract desktop might be cumbersome. Thank you for sharing these workarounds with the community!

**Comment by KnutJaegersberg** [comment]
yes you need to install an extension for jupyterlab, and there is one for jupyter notebooks as well. As far as I can tell, sos is more reliable in jupyternotebook than in jupyterlab. The ones for notebooks is the required ones. 
pip install sos
pip install sos-notebook
pip install sos-r

and install the IRkernels for each kernel did the job for me, i.e. 

install.packages('IRkernel')
IRkernel::installspec() 

. Although sos is not explicitly supported and you do not get the language dropdown in interact, you can just use the 
%use R
%use Julia
commands to switch kernels, i.e. to R and then to Julia. It works in nteract, on my machine, assuming the sos-notebook python pip installs, altough only after a reboot. The dropdown menu is not so important to my user experience, as long as switching kernels is as easy as described above. 
I like working with nteract, even more casual than jupyter notebooks.
