### ISSUE TITLE
Theme preferences don't seem to persist

### ISSUE THREAD

**Issue by dougdenn** [nteract/archived-desktop-app#4322]
**Application or Package Used**
nteract desktop

**Describe the bug**
nteract doesn't seem to save theme preferences in some conditions

**To Reproduce**
1. open nteract
2. set theme to dark
3. close nteract
4. reopen nteract - theme is light

**Expected behavior**
Expected theme to always be dark for new nteract windows - this is the behavior on another machine (does this at work but not at home)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: electron? desktop app
- Version 0.13.0

**Additional context**
Python 3.7 is being used from the MS Visual Studio path, not sure if that matters or not

**Comment by captainsafia** [comment]
Hello @dougleville! Thanks for opening this issue.

There was a recent release of nteract so this seems to be a regression from that. I was able to reproduce this on my nteract desktop app in macOS.

I'll see if I can dig into it this weekend.
