### ISSUE TITLE
Remove kernel, status, and savetime from PDF export

### ISSUE THREAD

**Issue by eigenvivek** [nteract/archived-desktop-app#4346]
I am exporting a notebook as a PDF to I can share it with others. There is a bar at the bottom that contains information that I don't want to share, but I can't figure out how to hide this information.

Is there a way to hide this? If not, I would love if I could remove it! 

Here's an example of my problem:
![streaming_bayes](https://user-images.githubusercontent.com/29757116/56082609-c9be5280-5de8-11e9-8089-89c91275b802.png)

**Comment by captainsafia** [comment]
Hello @v715! Thanks for opening this issue and great notebook!

@jdetle Do you know if we can customize the `printToPDF` function to print only certain parts of the DOM?

**Comment by jdetle** [comment]
Yeah I can do this! All we need to do is add a media query in the css sheets.

**Comment by jdetle** [comment]
Looked into this today, it looks like some media queries from before styled components haven't got brought in yet. I can find the relevant components and move them over there.

**Comment by jdetle** [comment]
Closed by #4390
