### ISSUE TITLE
Line wrapping in PDF export

### ISSUE THREAD

**Issue by andrewfogg** [nteract/archived-desktop-app#4350]
**Is your feature request related to a problem? Please describe.**
Export to PDF results in unreadable code because cannot control whether lines wrap or font-size.  

**Describe the solution you'd like**
I would like to be able to control whether PDF export wrapped lines or not.  Additionally it would also be nice to control the overall font-size at which the PDF export occurs

**Describe alternatives you've considered**
Currently just "screenshotting" notebooks when I need to share with others who cannot open notebooks.

**Comment by captainsafia** [comment]
Hello @andrewfogg! Thanks for opening this thorough issue and apologies for the trouble you are having. The PDF export feature currently works in a fashion very similar to that on a browser, where you can't really control the look and feel of the output. We're in the process of redesigning the notebook view so we'll hopefully be able to take this into effect soon.

@fabric-8 Here's another issue to look into as we consider potential print designs for notebooks on nteract.
