### ISSUE TITLE
Altair plot doesn’t show up

### ISSUE THREAD

**Issue by Alalalalaki** [nteract/archived-desktop-app#4351]
I update nteract desktop to 0.13 and then altair plot doesn’t show up. Though I am not 100% sure it's related to the update.

**Comment by captainsafia** [comment]
Hello @Alalalalaki! Thanks for opening this issue.

I suspect that this is related to #4359, in that our output picker might be off. Updates were made to it between the the recent release and the one prior so it is not a farfetched hypothesis.

I'll investigate further and see if I can get a fix in for next week's release.
