### ISSUE TITLE
Windows installer is unsigned

### ISSUE THREAD

**Issue by ViralBShah** [nteract/archived-desktop-app#4353]
**Application or Package Used**
nteract desktop

**Describe the bug**
The installer is not signed, leading Windows to suggest to me that the application is from an unknown provider and I should not use it. You have to install it by ignoring the warning.

- OS: Windows 10

**Comment by ViralBShah** [comment]
The reason I filed this issue is that we are considering using `nteract` for all our Julia training materials for users to run their Julia codes in. This issue might confuse users installing nteract.

cc @mbauman

**Comment by BenRussert** [comment]
@ViralBShah that's awesome! Hearing this really gets me excited to work more on nteract desktop, we've been picking up some steam lately!

Lets prioritize this and hopefully fix for the release on Monday, what do you think @captainsafia ?

**Comment by captainsafia** [comment]
It can be done! Our last desktop release was done a new machine and it looks like the configuration for Windows releases wasn't in.

We are doing another desktop release Monday evening so we will look into addressing this then.
