### ISSUE TITLE
SVG outputs do not display on Windows

### ISSUE THREAD

**Issue by mbauman** [nteract/archived-desktop-app#4359]
**Application or Package Used**
On nteract desktop (v0.13.0), Windows 10, with a Julia Kernel

**Describe the bug**
SVG images do not display on Windows, but do on Mac.

**To Reproduce**
Run the following Julia cell:
```julia
foo = """
<svg  xmlns="http://www.w3.org/2000/svg">
    <rect x="10" y="10" height="100" width="200" style="fill: blue"/>
</svg>
"""
display("image/svg+xml", foo)
```

**Expected behavior**
A blue box is displayed

**Screenshots**

Mac works:
![Screen Shot 2019-04-18 at 6 19 11 PM](https://user-images.githubusercontent.com/154641/56396846-8019a180-6206-11e9-9021-5b7584e5890c.png)

Windows does not:
![Screen Shot 2019-04-18 at 6 19 36 PM](https://user-images.githubusercontent.com/154641/56396863-8f005400-6206-11e9-929b-64dc87136e09.png)

**Comment by captainsafia** [comment]
Thanks for opening this issue, @mbauman!

I was able to reproduce it on Windows, but not Mac, on nteract 0.13 as well. It appears that something might be off with the output picker that is causing it to not default to the richer output type. I'll dig into it.

![image](https://user-images.githubusercontent.com/1857993/56400304-d2fc5480-6218-11e9-8421-d0b5e7742678.png)

EDIT: I was also able to repro on Mac (on development branch, not release) so definitely something up with the picker.

**Comment by mbauman** [comment]
Thanks! I didn't realize my Mac app was stuck on 0.12.3.
