### ISSUE TITLE
Please reopen #2738

### ISSUE THREAD

**Issue by probonopd** [nteract/archived-desktop-app#4366]
Please reopen https://github.com/nteract/nteract/issues/2738 as it is still an issue in https://github.com/nteract/nteract/releases/download/v0.13.0/nteract.0.13.0.AppImage. Thanks.

Also, please do not lock conversations as "resolved and limited to collaborators", especially if no one ever has actually positively confirmed that the issue has been resolved.

Reference:
https://github.com/AppImage/appimage.github.io/pull/638#issuecomment-485263598

**Comment by captainsafia** [comment]
That problem is already tracked in https://github.com/nteract/nteract/issues/3022. It appears there are multiple issues opened for the same problem so let's resolve to make #3022 the authoritative one.

**Comment by probonopd** [comment]
Agree that we should track this in https://github.com/nteract/nteract/issues/3022 but that one got closed, too... please reopen that one then.
