### ISSUE TITLE
Why can't access jupyter api in browsers

### ISSUE THREAD

**Issue by feifeimao666** [nteract/archived-desktop-app#4378]
I open nteract desktop app,and it runs a jupyter notebook service on localhost:8888.
Why I can't access jupyter api in chrome browser?

**Comment by captainsafia** [comment]
Hello @feifeimao666! Thanks for opening this issue.

Can you clarify what you mean by this question? The nteract desktop app doesn't launch a server on localhost:8888. Are you referring to the Jupyter extension?

**Comment by feifeimao666** [comment]
> Hello @feifeimao666! Thanks for opening this issue.
> 
> Can you clarify what you mean by this question? The nteract desktop app doesn't launch a server on localhost:8888. Are you referring to the Jupyter extension?

I try to execute command yarn run app:jupyter-extension ,but it seems that webpack couldn't complete the task and show this in browser.
<img width="1433" alt="屏幕快照 2019-04-29 下午3 06 06" src="https://user-images.githubusercontent.com/18097924/56880798-c08fdf80-6a90-11e9-9843-aab06705ff1c.png">

**Comment by captainsafia** [comment]
This issue is a little bit old but I'll answer and close it off in case others have this problem.

The best way to run the Jupyter extension in development is by `pip install`ing the package then running `jupyter nteract dev` as outlined in the README for the jupyter-extension.
