### ISSUE TITLE
Can't find nteract from commandline

### ISSUE THREAD

**Issue by drewbo** [nteract/archived-desktop-app#4386]
**Application or Package Used**
nteract desktop (for mac v0.14.0), command-line tool

**Describe the bug**

When trying to run nteract from the command-line I see `zsh: command not found: nteract`

This is probably not a "bug" and more likely my `PATH` is wacky in some specific way but I couldn't find the installed location of the command line binary in the documentation or repo anywhere.

**Desktop (please complete the following information):**

- OS: 10.14

**Comment by xinpingwang** [comment]
By default, the `nteract` command is installed at `$HOME/.local/bin` directory, and you should add this directory to your `PATH`.

**Comment by captainsafia** [comment]
Thanks for taking the time to answer @drewbo's question @xinpingwang! Would you be interested in submitting a PR to update our desktop app user guide with this information?

**Comment by drewbo** [comment]
Thanks for the response @xinpingwang ; I actually don't see that directory (in `$HOME/.local` I only see `lib` and `/share` directories)

**Comment by drewbo** [comment]
@xinpingwang any thoughts on why this isn't appearing for me? I just tried a fresh install of the desktop application (0.22.0) for Mac but it still doesn't appear at `$HOME/.local/bin` for me. I also tried creating that directory and reinstalling but no luck

**Comment by captainsafia** [comment]
@drewbo Just to cover our bases, I assume you already installed the command line tools using the "Install command line" option in the menu?

**Comment by drewbo** [comment]
Welp...I thought it was installed by default 🤦‍♂. Thanks for your patience @captainsafia and help debugging

**Comment by libphy** [comment]
I have $HOME/.local/bin in my path, but I still have the same problem. Can nteract commands be in different folders? Can you suggest where to look?

**Comment by captainsafia** [comment]
@libphy The command is also installed into `/usr/local/bin/nteract`. Anything there?
