### ISSUE TITLE
ENH: Show run code in dock as well as results?

### ISSUE THREAD

**Issue by nickeubank** [nteract/archived-desktop-app#4388]
Would it be possible for the dock to show not just output of executed code, but also the code that was run to generate a given set of outputs?

Basically mimicking the behavior or spyder/JupyterLab/RStudio?

**Comment by BenRussert** [comment]
I wonder if you meant to post this on the Hydrogen repo?

**Comment by nickeubank** [comment]
Um... yes. Yes I did. :)

**Comment by BenRussert** [comment]
If I had a nickel for every time I did that I'd have at least $0.55
