### ISSUE TITLE
Nteract desktop statusbar exported to PDF

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#4389]
**Application or Package Used**

Nteract desktop, version 0.14.0 installed in Ubuntu using .deb installer from Github releases

**Describe the bug**

The status bar at the bottom of the Nteract screen is included at the bottom of every page in the PDF export. Sometimes the status bar overlaps with notebook content, making the text unreadable.

This is a regression introduced sometime after version 0.12.x release. I updated yesterday from that version to 0.14.0 and this bug is a new behavior after the update

**To Reproduce**

1. Open new notebook, add a code cell
2. Run something that produces losts of output, e.g.
```python
for i in range(0,100):
   print(i)
```
1. File -> Export to PDF
5. Open the exported PDF file, bottom of first the page will look something like this:

![Screenshot from 2019-05-04 10-01-53](https://user-images.githubusercontent.com/3074453/57175358-ac166300-6e53-11e9-9a8f-329bf3441072.png)

**Expected behavior**

The status bar should be hidden/removed. The number 45 in the screenshot should be visible.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.10
- Browser: does not apply, using desktop
- Version: 0.14.0 release using .deb installer. Occurs also on 0.14.1 from up-to-date master (commit f63a01c40)

**Comment by jarmokivekas** [comment]
I downgraded to previous versions. Seems v0.12.1 does not have this bug, but v0.13.0 does.

**Comment by jarmokivekas** [comment]
Selecting the status bar in the developer tools and running `$0.style.visibility= "hidden"` from the developer console before exporting works as a work-around (pdf looks fine).

On a related note, also tab-completetion dropdown lists are exported to pdf, although just pressing ESC before export gets rid of them.

![image](https://user-images.githubusercontent.com/3074453/57176328-8000df00-6e5f-11e9-857b-010321480839.png)

Might be worthwhile to see if adding  `@media print` css rules to these elements fixes this issue, similar to pull #1407.

**Comment by captainsafia** [comment]
This can be closed via https://github.com/nteract/nteract/pull/4390.
