### ISSUE TITLE
Install Shell Commands 

### ISSUE THREAD

**Issue by gomezdj** [nteract/archived-desktop-app#4391]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This is the error I would like to correct. I would like to run the shell command. I click on the “Install Shell Commnands” and I get this:

ENOENT: no such file or directory, symlink '/Applications/nteract.app/Contents/Resources/bin/nteract.sh' -> '/Users/danieljosephgomez/.local/bin/nteract’

**Comment by captainsafia** [comment]
Hello @danielgomz, can you add some more information to this post?

- What version of nteract are you using?
- What version of Mac OS?
- Any special OS configurations you might have?
- What have you already tried to resolve this issue?

**Comment by gomezdj** [comment]
0.12.3
macOS Mojave
Version 10.14.4

I haven't found a way into the directory. I couldn't inject the directory.

Essentially, what I understand is the I could not write shell script. I can open the nteract.sh 
Which could be the installation file.....

However, I'm still getting the ENOENT: no such file or directory.

The result that I'm expecting would be the command 'nteract' from the terminal. 
Not sure why this wasn't included in the installation.
