### ISSUE TITLE
Data Explorer: styled-components should be in peerDependencies

### ISSUE THREAD

**Issue by dylanross3** [nteract/archived-desktop-app#4395]
**Application or Package Used**
Data Explorer

**Describe the bug**
The [styled-components](https://www.npmjs.com/package/styled-components) package is listed in `dependencies` of the Data Explorer [package.json](https://github.com/nteract/nteract/blob/master/packages/data-explorer/package.json). This goes against guidance for library authors in the styled components documentation [here](https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library).

> If you are a library author, we recommend that you should not bundle and ship styled-components module with your library.

**Comment by captainsafia** [comment]
Hello @dylanross3! Thanks for opening this issue.

Would you be interested in submitting a PR to update the `package.json` file in the Data Explorer to use styled-components as a peer dependency?
