### ISSUE TITLE
Altair plots do not render

### ISSUE THREAD

**Issue by mattbit** [nteract/archived-desktop-app#4397]
**Application or Package Used**
nteract desktop v0.14.2 (Linux AppImage)
altair version 3.0.1
(Note: I get the same with Atom+Hydrogen)

**Describe the bug**
Altair (Vega) plots do not render properly. Instead, I get the following message:
```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```

**To Reproduce**
```python
import altair as alt
from vega_datasets import data

iris = data.iris()

chart = alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)

display(chart)
```

**Expected behavior**

Altair [should be working out of the box](https://twitter.com/nteractio/status/984257546985783297).

**Comment by captainsafia** [comment]
Hello @mattbit! Thanks for opening this issue. I was able to reproduce this issue in the nteract desktop as well.

It appears that there is a bug in our output rendering with respect to Vega outputs that will need to be resolved before the next release.

Thanks again for submitting this bug report.

**Comment by davidanthoff** [comment]
Any update on this? This is also affecting the julia side of things.

**Comment by davidanthoff** [comment]
Sorry to bump again, but it would be really helpful for us to get a vague sense of when a version of nteract might ship that has this fixed. I'm exploring nteract as an option for some workshops that I'm giving, but this is blocking for that. So, just a short update on whether a fix might make it into the next release would already be fantastic :) Thanks!
