### ISSUE TITLE
Data Explorer: Unexpected high contrast table styles

### ISSUE THREAD

**Issue by dylanross3** [nteract/archived-desktop-app#4401]
**Application or Package Used**
Data Explorer

**Describe the bug**
The styles of the Data Explorer changed in #4339. The light theme now has very high contrast for striped rows, which looks unpleasant in my opinion. I understand there are contrast guidelines for usability, but this seems to be more contrast than necessary. The left-most column also has a border that I'm not sure is needed.

![image](https://user-images.githubusercontent.com/10860657/56098466-1031b100-5ebe-11e9-8a35-69e45276079c.gif)

Expected:
![image](https://user-images.githubusercontent.com/2413692/57541195-52a2ae00-7303-11e9-8df6-9e0731de093a.png)

Actual:
![image](https://user-images.githubusercontent.com/2413692/57540997-e7f17280-7302-11e9-871b-912cccb9405e.png)

**Comment by BenRussert** [comment]
For anyone fixing this, the relevant colors to change are probably all [here](https://github.com/nteract/nteract/blob/master/packages/data-explorer/src/css/index.tsx#L14-L33) .

**Comment by captainsafia** [comment]
Thanks for pointing to the place for a fix, @BenRussert!

@dylanross3 Do you think you can resolve this one as well with Ben's guidance? Your contribution is appreciated!

**Comment by dylanross3** [comment]
Sorry, I don't think I can get to this one anytime soon.
