### ISSUE TITLE
Keyboard shortcut editor request

### ISSUE THREAD

**Issue by parthi2929** [nteract/archived-desktop-app#4406]
**Is your feature request related to a problem? Please describe.**
Not a problem but feature request

**Describe the solution you'd like**
I want to have keyboard shortcuts same as jupyter. If it cannot be default, I request an editor so I could manually map as much as I want. I am very used to A, B, DD, Ctrl+M, etc. It takes a lot of mind muscle power to be able to switch between notebook and nteract while remembering the shortcuts. The power of notebook is also being able to use keyboard for most of the documentation/code, without having to use mouse - like command utility. This creates a confusion havoc when we try to switch between notebook and nteract. Since notebook has kind of established the shortcuts, why not use the same? I sincerely request developers to implement this as this is such a great idea, Jupyter notebook has missed to do. I want to use nteract to its full potential. 

**Describe alternatives you've considered**
I really like this desktop idea, and want to use this app, not thinking of alternatives till I see these cannot be done here. 

**Additional context**
NA

nteract v0.14.2: Brave Born

**Comment by captainsafia** [comment]
Hello @parthi2929!

Thanks for opening this issue. I want to bring your intention to a master issue around keyboard shortcuts that has been created in https://github.com/nteract/nteract/issues/4781.

It's unlikely that nteract will support the exact keyboard shortcuts that Jupyter classic supports. In particular, those that require modal editing. We want to reduce the concept count for new users coming to notebooks and so our goal when it comes to keyboard shortcut design is to be as intuitive as possible to a larger group of audience.

I'll close this issue and we can track any other keyboard shortcut related comments in the issues referenced above.

Thanks for sharing your feedback!
