### ISSUE TITLE
Cell default height too big in nteract web

### ISSUE THREAD

**Issue by giux78** [nteract/archived-desktop-app#4408]
**Application or Package Used**
nteract web, nteract on jupyter https://github.com/nteract/nteract/blob/master/applications/jupyter-extension/nteract_on_jupyter/app/index.tsx

**Describe the bug**
The cell default height is too big with too many lines. When for example I want to create a chart of a dataframe normally i use cell of one or few lines.

**To Reproduce**
All cells on web apps are affected both new and old.

**Screenshots**
![Screen Shot 2019-05-14 at 08 02 10](https://user-images.githubusercontent.com/2806256/57836131-5ed5b200-77c0-11e9-8b93-876a273ac417.png)

**Expected behavior**
Cell should be flexible on the numbers of lines starting from one line

![Screen Shot 2019-05-16 at 09 54 40](https://user-images.githubusercontent.com/2806256/57836284-a65c3e00-77c0-11e9-966b-2dc582ead8a7.png)

- OS: [e.g. macOS]
- Browser [all]
- Version [e.g. last]

**Comment by jameskoch** [comment]
It looks like this regressed in https://github.com/nteract/nteract/commit/7fcb71fcbe1e81f35805e7229174fd2b20119b14#diff-ac4acad2081a1ced22ecae1d968c8ca7L9
