### ISSUE TITLE
Windows auto update doesn't seem to work

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#4410]
I'm on Windows and nteract version 0.12.2. In the past, nteract desktop auto updated whenever a new release came out, but that seems to no longer happen? I think there have been numerous releases in the meantime?

**Comment by PaulSoderlind** [comment]
My Win10 based nteract desktop 0.14.2 auto updated to 0.14.3 yesterday. Maybe just a coincidence, but the update was triggered when I ran nteract from the command line.
