### ISSUE TITLE
Julia vega-lite plot doesn't show

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#4411]
The notebook [here](https://gist.github.com/davidanthoff/b9ff6e31ac64788c1204e90cdda64ac1) shows correctly with a plot in jupyter notebook, jupyter lab and on github. But in nteract, I don't see a plot.

If you look into the notebook, it has the plot as a vega-lite JSON spec, a PNG or SVG MIME bundle, so I would assume that one of them should work :)

**Comment by mattbit** [comment]
May be related to the problem with the output rendering in #4397.

**Comment by davidanthoff** [comment]
Yes, that might well be the same issue!

**Comment by captainsafia** [comment]
Thanks for your patience folks! Hopefully #4442 will be merged soon and we can close this and related issues.

**Comment by CrystallineCat** [comment]
Should be fixed by 97721aa.
