### ISSUE TITLE
Raw HTML in MD cells

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#442]
Working on this but got stuck, so posting an issue.

Right now typing raw html into a MD cell will not do what you expect: render that HTML as HTML. Instead you see what you typed.

We use `remark-react` and `remark` for the MD cells. The [remark-react demo](http://mapbox.github.io/remark-react/) does the same thing as `nteract` in terms of raw HTML in MD.

I think what happens is that the `entities` option of `remark-react` escapes `&` to `&amp;` etc. There doesn't seem to be an [option](https://github.com/mapbox/remark-react#configuration) to disable that. Not quite sure yet how all this is meant to work with their `sanitize` option which looks as it if it is expressly for people wanting to allow HTML in their MD.

**Comment by jdfreder** [comment]
> Not quite sure yet how all this is meant to work with their sanitize option which looks as it if it is expressly for people wanting to allow HTML in their MD.

Seems like the default `sanitize=false` would mean `don't sanitize` and thus allow HTML.  Maybe this option isn't working as intended...

Okay, I just fiddled around with the demo a bit.  

input:
`hello wor<b>l</b>d`

sanitize: true:
`hello wor&lt;b&gt;l&lt;/b&gt;d`

sanitize: false:
`hello wor<b>l</b>d`

Looks like the render results need to be set using dangerouslySetInnerHTML or a document fragment.  I think this is something internal to the component itself.  The downside to this is that users can dump Javascript into the MD unless we use something like Google Caja.

**Comment by jdfreder** [comment]
Just to clarify, what I typed above is what the users sees.  For example, here is `sanitize: true` 

![clarification](https://cloud.githubusercontent.com/assets/3292874/15221378/0b255280-1820-11e6-8137-79c64e302098.jpeg)

**Comment by betatim** [comment]
`sanitize: false` is the default, and from what the docs say I'd expect that to do what we want it to do. 😕

Even more weird is that if you look at the "Elements" tab in the inspector for `nteract` it shows you exactly what you typed, but for some reason doesn't actually render it as HTML. This is what made me wonder if someone in the chain does some kind of escaping?

<img width="803" alt="screen shot 2016-05-12 at 20 09 16" src="https://cloud.githubusercontent.com/assets/1448859/15225174/80ffe60c-187d-11e6-9f4a-88eebc4c11c2.png">

It is really confusing to see what looks like valid HTML, but it does get rendered.

Is this a bug in `remark-react` then? Not sure I can see how we are using it wrong or doing weird things that break it.

Do you know what :octocat: uses? Seems like a common problem. Caja got mentioned before so 👍.

**Comment by rgbkrk** [comment]
We're now on commonmark again, issue still prevails.

**Comment by rgbkrk** [comment]
This works now! Not sure when it was fixed, just noticed though.

![screen shot 2016-09-05 at 9 22 32 pm](https://cloud.githubusercontent.com/assets/836375/18261597/e22c6ba8-73ae-11e6-9cc7-4a3639dbc996.png)
