### ISSUE TITLE
Inline Documentation Does Not Render Correclty

### ISSUE THREAD

**Issue by robertdefilippi** [nteract/archived-desktop-app#4421]
**Application or Package Used**
nteract desktop

**Describe the bug**
When I try to look at the documentation using the keyboard shortcut (CTRL + .) the documentation renders, but it is not opaque. Meaning the notebook code blends in with the documentation code. Additionally, the "X" to close the documentation is not clickable, so it cannot be closed.

**To Reproduce**
Launch documentation with keyboard shortcut.

**Expected behaviour**
Documentation launches in a form that is readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/9288605/58251996-0f98ff80-7d33-11e9-8386-041f73fd474e.png)

**Desktop Version

- OS: 10.14.4 macOS 
- Version: 0.14.3 (0.14.3)

**Comment by BenRussert** [comment]
> Additionally, the "X" to close the documentation is not clickable, so it cannot be closed

I had work started on these issues a few weeks ago. I'll see if I can revive that and get this fixed soon.

**Comment by yogevyuval** [comment]
Affects the webapp as well.

**Comment by robertdefilippi** [comment]
Great. I thought it might have just been my set up. Thanks for taking a look into it @BenRussert
