### ISSUE TITLE
LaTeX math is not rendered properly

### ISSUE THREAD

**Issue by Foadsf** [nteract/archived-desktop-app#4422]
**Application or Package Used**
State which application or package this affects: nteract desktop

**Describe the bug**
As I reported in [this tweet](https://twitter.com/fsfarimani/status/1131827926209581057) and this [Slack post](https://nteract.slack.com/archives/C08FBMK1T/p1558685536004300), In the text cells (MarkDown cells in Jupyter lingo) some of the LatEx equations are not rendered properly.

**To Reproduce**
example LaTeX code:

~~~latex
$$
    \begin{bmatrix} 
        \sin \phi \sin\gamma \\ \cos \phi\\ \sin \phi \cos\gamma 
    \end{bmatrix} 
    = R(\alpha) 
    \begin{bmatrix} 
        \sin\theta_2\\ \cos\theta_1 \cos\theta_2\\ \sin\theta_1 \cos\theta_2 
    \end{bmatrix} 
    \quad\text{where}\quad 
    R(\alpha) =
    \begin{bmatrix}  
        \cos\alpha  & \sin\alpha & 0\\ -\sin\alpha & \cos\alpha & 0\\ 0 & 0 & 1\\ 
    \end{bmatrix}
$$
~~~

and

~~~latex
$$  
\begin{cases}
    z_0 \rightarrow -\theta_2\\
    x_0 \rightarrow \theta_1\\
    z_0 \rightarrow -\alpha
\end{cases}
$$
~~~

**Expected behavior**
The LaTeX code to be rendered properly 🧐

**Screenshots**

![2019-05-24_09-42-15](https://user-images.githubusercontent.com/12762442/58332244-19a62580-7e3b-11e9-86e8-f978ed499631.gif)

**Desktop (please complete the following information):**

- OS: Windows
- Version 10 , 1809

**Comment by lgeiger** [comment]
I just tried the example you provide with nteract 0.14.3:
![Bildschirmfoto 2019-05-24 um 14 56 27](https://user-images.githubusercontent.com/13285808/58332938-3c810b80-7e34-11e9-85f3-12200eb3e690.png)

It looks like you are missing a linebreak after the `$$`.

**Comment by Foadsf** [comment]
That's strange. So the first `$$` should be on its own line. 🤔 now it works properly. Thanks.

**Comment by lgeiger** [comment]
Glad it's working now

**Comment by Foadsf** [comment]
@lgeiger I still would consider this as an issue. The fact that the first pair of `$$`s needs to be stand-alone is not LaTeX compatible.
