### ISSUE TITLE
Bokeh output_notebook()

### ISSUE THREAD

**Issue by hkmoon** [nteract/archived-desktop-app#4423]
**Application or Package Used**
nteract desktop

**Describe the bug**
When I tried to use bokeh in nteract desktop, it shows "Loading BokehJS ..." and keep busy.

**To Reproduce**
Just run the below code:

```python
from bokeh.plotting import figure 
from bokeh.io import output_notebook, show
output_notebook()
from numpy import cos, linspace
x = linspace(-6, 6, 100)
y = cos(x)

p = figure(width=500, height=500)
p.circle(x, y, size=7, color="firebrick", alpha=0.5)
show(p)
```

**Expected behavior**
It shows the result in Jupyter notebook without any problem.

**Screenshots**
<img width="774" alt="Untitled_-_busy" src="https://user-images.githubusercontent.com/3864647/58464247-a865bb80-8135-11e9-81ba-c4b54ac8ea3e.png">

Expected screen shot:
<img width="620" alt="Untitled" src="https://user-images.githubusercontent.com/3864647/58464411-ecf15700-8135-11e9-867e-37542be95797.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Electron
- Version 0.14.3

**Additional context**

**Comment by captainsafia** [comment]
Thanks for opening this issue, @hkmoon! I am able to reproduce the problem that you are experiencing.

It appears that Bokeh is returning an mimebundle with an HTML type and the `Loading BokehJS` text listed above. My suspicion is that the `output_notebook` method is not returning the appropriate media bundle when the front-end is not Jupyter classic.

Can you open an issue for this on the Bokeh repository to see if they might have any leads?

**Comment by CrystallineCat** [comment]
This appears to be a bug in `@nteract/commutable`.

When creating a frozen version of a media bundle, we currently expect JSON media types to be objects and just pass them to `deepFreeze`. Bokeh sends a key of `"application/vnd.bokeh...+json"` and a value that is a simple string, which `deepFreeze` fails on.

Fix incoming.

**Comment by captainsafia** [comment]
Thanks so much for the explanation and the bug fix, @CrystallineCat!

**Comment by hkmoon** [comment]
@captainsafia @CrystallineCat Thank you for handling this issue. Unfortunately, after updating to nteract 0.14.4, the issue still exists. Can you check it again?

**Comment by captainsafia** [comment]
@hkmoon I'm seeing that Bokeh isn't returning the `application/vnd.bokeh` mime bundle in its responses at all. All that is being returned in the execution reply is a media bundle with `text/html` as the type. I would follow-up with the Bokeh team to see if their `output_notebook` method is designed to return the right media bundle for nteract targets.

**Comment by CrystallineCat** [comment]
@hkmoon @captainsafia I don't think patch #4487 shipped with 0.14.4; I don't see it in the [commits for the tag](https://github.com/nteract/nteract/commits/v0.14.4).

Here's what I'm seeing when I execute the code in the OP (`nteract@master`, `bokeh@1.2.0`, `python@3.7.3`) and save the file ([full `.ipynb`](https://gist.github.com/CrystallineCat/d8629897d7dacef82f28ea4405733c8b?short_path=356bf5d)):

```javascript
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/html": [ /* ... */ ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "application/javascript": [ /* ... */ ],
            "application/vnd.bokehjs_load.v0+json": /* ... */
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/html": [ /* ... */ ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "application/javascript": [ /* ... */ ],
            "application/vnd.bokehjs_exec.v0+json": ""
          },
          "metadata": {
            "application/vnd.bokehjs_exec.v0+json": {
              "id": "1597"
            }
          }
        }
      ],
```

**Comment by captainsafia** [comment]
@CrystallineCat Thanks for investigating this. Looks like you are right about this not making it into the release. It looks like the branch was merged after the release went out. It'll be included in tomorrow's release though.

**Comment by hkmoon** [comment]
It's confirmed that nteract version 0.14.5 resolves this issue. Thank you so much! @captainsafia @CrystallineCat !
<img width="782" alt="__Untitled_ipynb_-_idle" src="https://user-images.githubusercontent.com/3864647/62370705-2c239600-b533-11e9-85ce-13d4e4113b9b.png">
