### ISSUE TITLE
Local images are not displayed in markdown cells

### ISSUE THREAD

**Issue by yogevyuval** [nteract/archived-desktop-app#4428]
Local images are not displayed in markdown cells. Probably related to the path not being relative to the current notebook.

![image](https://user-images.githubusercontent.com/962869/58816693-ad91a180-8632-11e9-8b28-608061711c7d.png)

Seems like it was already fixed by @captainsafia in https://github.com/nteract/nteract/pull/4326 but it does affect the web app.

This is crucial for long detailed notebooks.

**Comment by captainsafia** [comment]
To support this, we will need to add the `base` tag to our scaffold for the nteract web app. We'll also need to investigate if this has any ramifications on our configuration for the web app. Marking this as new contributor friendly since there is an existing implementation in the desktop app and an implementation solution.

**Comment by Madhu94** [comment]
I'm picking this up.

**Comment by schedutron** [comment]
Can I work on this issue?

**Comment by captainsafia** [comment]
@schedutron Yes, you can!

**Comment by schedutron** [comment]
@captainsafia Can you please provide a little more detail on how to solve this? The app/contents/notebook.tsx file already imports the notebook app which has the Helmet element with <base> you added in your PR. Why is the extension not working then for local files? Please guide me a bit on where would I need to make the necessary change.

**Comment by captainsafia** [comment]
This actually works now. I think this issue was reported because a new version of the desktop app had not been release with the changes mentioned above. I'll go ahead and close this issue.
