### ISSUE TITLE
Managing update dependency Renovate bot PRs

### ISSUE THREAD

**Issue by BenRussert** [nteract/archived-desktop-app#4436]
We have a distracting number of open PRs for package updates right now. I have commented on those I have an opinion on, but not tried the others because it seems like low reward most of the time.

Does anyone have ideas for cleaning this up, or is the current process working? Should we try to tag team these?

**Comment by captainsafia** [comment]
@willingc created a set of workflow labels to manage these kinds of things before. I think our strategy for this should be.

1. Minor/patch version updates with no conflicts and no failures in build: merge immediately
2. Minor/patch version updates with no conflicts and failures in build: tags as chore and comment with conflict, resolve any issues that come as a result of introducing the update and merge
3. Major version updates with no conflicts and failures in build: confirm with folks who have knowledge about the package and merge
4. Major version updates with conflicts/failures in build: close pull requests

How does this sound?

**Comment by BenRussert** [comment]
Thanks for this @captainsafia. This plans sounds good to me. The minor/patch ones alone will de-clutter our PRs significantly.

**Comment by captainsafia** [comment]
Closing this as we've been employing this strategy for a while now.
