### ISSUE TITLE
Support latest vega and vega-lite MIME types

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#4439]
Looking at [this](https://github.com/nteract/nteract/blob/29879454aa96d972549c51e87e185716010beed6/packages/transform-vega/src/index.tsx#L6), I think currently nteract supports the MIME types for v2 and v3 for vega, and v1 and v2 for vega-lite. It would be great if for vega v4 and v5 and for vega-lite v3 would also be supported.

I guess this would also require shipping the latest versions of those packages in https://github.com/nteract/vega-embed-v2, right?

**Comment by CrystallineCat** [comment]
Should be fixed by 97721aa.
