### ISSUE TITLE
Adapt to redux + redux-observable

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#444]
At the very least, I think we should investigate [redux-observable](https://github.com/blesh/redux-observable).
- [Blog post](https://medium.com/@benlesh/redux-observable-ec0b00d2eb52#.pp0on0hir)
- [redux-observable](https://github.com/blesh/redux-observable)

Looks approximately like our current Redux-like API, while aligned with proper Redux. Given the Observable store that @blesh added on to Redux itself, I'd say we're in a good position to adapt to it.

/cc @kenwheeler @jdfreder

**Comment by rgbkrk** [comment]
Some interesting little bits of inconsistencies we have here - `redux-observable` has a peer dep of `rxjs@5.0.0-beta.6` and a `require('rxjs/Rx')` import whereas the rest of our Rx stack is from the `@reactivex/rxjs` import/install.

**Comment by benlesh** [comment]
That's an interesting wrinkle. cc/ @jayphelps

Perhaps we need to remove the hard peer dependency and just document it clearly?

**Comment by jayphelps** [comment]
@blesh That won't solve the issue of us doing our imports from `rxjs` and not `@reactivex/rxjs`.

e.g. we do

``` js
import * as Rx from 'rxjs';
```

But that doesn't work with `@reactivex/rxjs`, it would need to be 

``` js
import * as Rx from '@reactivex/rxjs';
```

...but then we have the inverse problem of not working with `rxjs`.

**Comment by rgbkrk** [comment]
We don't have too much worry about the bundle size since this is an Electron app, so we can use the `var Rx = require('rxjs/Rx');` form to get all the core Rx functionality and work around the differing imports.

**Comment by jayphelps** [comment]
@rgbkrk you might have some odd bugs in the future mixing Rx implementations though, since the Observable you create in your action will be _your_ Rx version, but the Observable of future actions we pass to you will be from _ours; perhaps not super likely, but we also need to a solution for normal web users as well...though this might not the correct forum.

(`instanceof Observable` checks would fail too, but that's a pretty rare thing to do)

**Comment by rgbkrk** [comment]
That makes sense. For ease of development, I think we'll pin to match the version you're using in redux observable, 5.0.0-beta.6.

> we also need to a solution for normal web users as well...though this might not the correct forum

You're more than welcome here - we're happy consumers of RxJS 5. Thanks for chiming in.

**Comment by rgbkrk** [comment]
Very closed. :heart:
