### ISSUE TITLE
No code coloring - nteract - OSX 

### ISSUE THREAD

**Issue by drbh** [nteract/archived-desktop-app#4445]
There is no code coloring in nteract. Is there a custom theme I need to install? I followed the install instructions and the code execution is working fine. Did I miss some styling?

Versions:
```
Interact: Version 0.12.3 (0.12.3)
OSX: Version 10.14.3 Mojave
```

related ticket on gophernotes: https://github.com/gopherdata/gophernotes/issues/158

**Comment by drbh** [comment]
This is also true for the Rust kernel....

<img width="597" alt="Screen Shot 2019-06-12 at 2 56 53 PM" src="https://user-images.githubusercontent.com/9896130/59378469-5d959780-8d22-11e9-86a7-fcd3ab107606.png">

**Comment by SpencerPark** [comment]
Also curious about the proper route to package a codemirror mode or similar with a kernel, but oddly enough the in markdown _source_ the code fences are properly highlighted, but when rendered that highlighting is lost.

`go` does in fact appear to be in the codemirror standard languages but is missing when highlighting in markdown source. I also tried with `java` which was working in markdown source but not in code cells, nor in rendered markdown. Here is a screenshot:
![nteract-syntax](https://user-images.githubusercontent.com/9256594/59776019-1bb7a480-9280-11e9-801a-06d2e808f5a4.png)

This was on windows, nteract `0.14.3`. I'll also attach the notebook in case anything in there is interesting/helpful:

<details>
    <summary>Notebook JSON</summary>
    
```json
{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "for (int i = 0; i < 3; i++) {\n",
        "    System.out.println(\"i: \" + i);\n",
        "}"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "i: 0\n",
            "i: 1\n",
            "i: 2\n"
          ]
        }
      ],
      "execution_count": 2,
      "metadata": {
        "collapsed": false,
        "outputHidden": false,
        "inputHidden": false
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "```java\n",
        "for (int i = 0; i < 3; i++) {\n",
        "    System.out.println(\"i: \" + i);\n",
        "}\n",
        "```\n",
        "```python\n",
        "for i in range(0, 3):\n",
        "    print('i:', i)\n",
        "```\n",
        "```go\n",
        "package main\n",
        "```"
      ],
      "metadata": {}
    },
    {
      "cell_type": "markdown",
      "source": [],
      "metadata": {}
    }
  ],
  "metadata": {
    "kernel_info": {
      "name": "java"
    },
    "language_info": {
      "name": "Java",
      "version": "9+181",
      "mimetype": "text/x-java-source",
      "file_extension": ".jshell",
      "pygments_lexer": "java",
      "codemirror_mode": "java"
    },
    "kernelspec": {
      "name": "java",
      "language": "java",
      "display_name": "Java"
    },
    "nteract": {
      "version": "0.14.3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
```
</details>

The interesting information being:
```json
"language_info": {
  "name": "Java",
  "version": "9+181",
  "mimetype": "text/x-java-source",
  "file_extension": ".jshell",
  "pygments_lexer": "java",
  "codemirror_mode": "java"
}
```

**Comment by captainsafia** [comment]
For @drbh's issue, I believe that this is an issue with the `codeMirrorMode` selector that we use to extract the codemirror styling from either the notebook metadata being borked.

@SpencerPark Your issue might have something to do with the way Markdown rendering is configured in our Markdown preview component. Can you open another issue for that?

**Comment by SpencerPark** [comment]
Hi @captainsafia, thanks I can open another issue if necessary but the intention was to add information to this issue. The goal was to show that there are cases where some syntax highlighting is working in nteract (markdown editor) that is not necessarily supported in the code cells for some reason to help debug why go isn't working at all.

Could you direct us to where that selector is generated/what component it's in?

**Comment by captainsafia** [comment]
> Hi @captainsafia, thanks I can open another issue if necessary but the intention was to add information to this issue. The goal was to show that there are cases where some syntax highlighting is working in nteract (markdown editor) that is not necessarily supported in the code cells for some reason to help debug why go isn't working at all.

Understood. I want them to be tracked in a separate issue since the fixes for each of these issues will likely come in different PRs and touch different packages within the monorepo. Separating them will make the bookkeeping easier.

> Could you direct us to where that selector is generated/what component it's in?

The selector is located [here](https://github.com/nteract/nteract/blob/af570afbe21ac61aa7c1368cf45825b60e5dea81/packages/selectors/src/notebook.ts#L222) and is used within the [notebook app component](https://github.com/nteract/nteract/blob/af570afbe21ac61aa7c1368cf45825b60e5dea81/packages/notebook-app-component/src/editor.tsx).

**Comment by SpencerPark** [comment]
@captainsafia, understandable. Opened a new issue. 

In the selector I notice there is no fallback to the language info `name` as the codemirror mode which is the convention [jupyter/notebook uses](https://github.com/jupyter/notebook/blob/8b21329deb9dd04271b12e3d2790c5be9f1fd51e/notebook/static/notebook/js/notebook.js#L372). Again this fallback to the name should also apply when pulling the mode from the `kernel.info`.

**Comment by captainsafia** [comment]
@SpencerPark Good catch! Would you be interested in submitting a PR to fix this?

**Comment by captainsafia** [comment]
I'm going to go ahead and close this issue now since the original problem of no code coloring in Markdown renders has been fixed with our recent migration to use GitHub-flavored Markdown for Markdown rendering.

**Comment by daxian-dbw** [comment]
@captainsafia I'm trying out the dotnet-interactive with nteract on macOS (10.15.4), and I don't see the syntax coloring for c#/f#/powershell.

<img src="https://user-images.githubusercontent.com/127450/80020817-7c120680-848e-11ea-8ea2-df89a3fd7d26.png" width="300" height="200">

I found this issue after searching, but it's closed. Is there a setting that I should configure?

**Comment by daxian-dbw** [comment]
@captainsafia Just landed on this issue: https://github.com/nteract/nteract/issues/5055
I will submit a PR to add syntax highlighting for c#/f#/powershell

**Comment by vsivsi** [comment]
@daxian-dbw  Would you be willing to add golang support in your PR as well?  I think it's just one more line (per: https://github.com/codemirror/CodeMirror/tree/master/mode/go):

`require("codemirror/mode/go/go");`

Added in here somewhere: https://github.com/nteract/nteract/blob/master/packages/editor/src/index.tsx#L211

Thanks!!

**Comment by daxian-dbw** [comment]
@vsivsi sure :)
