### ISSUE TITLE
Implement UI support for collapsed property in notebook

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4448]
We currently parse and style collapsed cells outputs via commutable and our component but don't give users an interface for toggling the collapsed state from the notebook.

The ideal implementation would allow users to toggle this via the cell menu so that it has a little bit more visibility to the user than the classic Jupyter UI and co-exists alongisde our other visibility toggles.

Verification for this should include tests for the reducers and actions and snapshot tests for the output component.

**Comment by bnbarak** [comment]
@captainsafia I will take this one. Can you please provide a little more details?
Are we talking about cloning the toggle menu from the cell to the cell menu on the top?

**This:**

<img width="223" alt="Screen Shot 2019-07-14 at 6 05 07 PM" src="https://user-images.githubusercontent.com/6034194/61189903-0442c000-a662-11e9-8b8a-b10da071727c.png">

**Will be added to:**

<img width="318" alt="Screen Shot 2019-07-14 at 6 05 11 PM" src="https://user-images.githubusercontent.com/6034194/61189910-13297280-a662-11e9-9cc0-a76da632f647.png">

**Comment by captainsafia** [comment]
Hello @bnbarak! Thanks for offering to help.

To implement this feature we would need to add:

1. A `collapsed` property to the notebook metadata in commutable, similar to the way `inputHidden` and `outputHidden` are managed now
2. A set of Redux actions that will toggle the collapsed property given a `CellId` and a `ContentRef`
3. A dropdown menu element that will invoke the actions from #2 appropriately depending on what the collapsed state is

Let me know if you have any questions on the steps above!
