### ISSUE TITLE
Accessing Documentation From Cell (Using ?)

### ISSUE THREAD

**Issue by earlev4** [nteract/archived-desktop-app#4449]
Hello,

Good day! First off, I just want to thank you for all your efforts on putting out a great application. I sincerely appreciate it! Please forgive me if this is a known issue or a requested feature. I searched opened and closed issues and did not find a similar issue. I also scanned the nteract documentation (docs.nteract.io) but did not find anything addressing this issue. I am not sure if this is a bug request or a feature request but opened as a bug report.

**Application or Package Used**
nteract desktop 0.14.3

**Describe the bug**
In IPython and Jupyter Notebooks, a question-mark `?` after a method or function will bring up the documentation after the cell is run.

**To Reproduce**
In a cell, run the following with the python3 kernel.
First cell:
`from bs4 import BeautifulSoup as bs`
Second cell:
`bs?`

**Expected behavior**
After running the second cell, the expected behavior is an explanation of how the method or function works. Instead, the `bs?` cell runs without an error but does not produce any output.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04 LTS
- Browser:  Chrome
- Version: Version 74.0.3729.169 

**Additional context**
In place of `?` help works using `help(bs)`. However, the help() function is not as succinct as `?`. Jupyter Notebooks also offers the option of "SHIFT-TAB" in the cell which provides even a more succinct usage of the method or function. A similar feature would be very nice.

Thanks so much!!!

**Comment by hydrosquall** [comment]
Hi @earlev4 - thanks for the detailed writeup! There is a similar command as an alternative to `shift+tab` in Nteract, namely `ctrl + .`, which will open some "tips" about how the function under your cursor behaves. 

https://github.com/nteract/nteract/issues/3124

**Comment by earlev4** [comment]
Hi @hydrosquall!

Good day to you! I greatly appreciate the information. It was most helpful.

Thanks so much!!!
earle
