### ISSUE TITLE
Components Syntax error on Out-of-the-Box desktop app installation

### ISSUE THREAD

**Issue by MaggieAppleton** [nteract/archived-desktop-app#4455]
I'm a beginner dev and would love to use nteract to take notes but running into some problems. I'm probably just incredibly thick / doing something wrong...

But I just downloaded the nteract desktop app and opened it up.
Started trying to use components from https://components.nteract.io/ and get a syntax error immediately.

![image](https://user-images.githubusercontent.com/5599295/59564373-e885d300-903d-11e9-92ff-48a9e66596a4.png)

What am I missing?

**Comment by captainsafia** [comment]
Thanks for opening this issue, @MaggieAppleton! You're definitely not at fault for this.

I don't see the status bar for your nteract application but I assume you are running on the built-in NodeJS kernel. If so, then the kernel does not have access to packages downloaded from npm in your machine or the ability to import packages using ES6 syntax.

**Comment by captainsafia** [comment]
Closing this for now. Perhaps one day we can bundle nteract packages within Node in the sandbox but this isn't super high priority.
