### ISSUE TITLE
Insert Code Cell Above / Below icons

### ISSUE THREAD

**Issue by s-celles** [nteract/archived-desktop-app#4458]
Hello,

Using an other notebook system, I noticed that nteract UI could be improved to provide icons to insert code cell above (or below) current cell.

![ui_example](https://user-images.githubusercontent.com/109167/59598584-d028bd80-90fc-11e9-83c8-92b81406c1c9.png)

`+` on top of current cell insert code cell above
`+` at bottom of current cell insert code cell below
`...` displays a contextual menu

I found this kind of UI very intuitive and it will be nice if an open source notebook such as nteract could provide such a user interface experience.

What is your opinion?

Kind regards

**Comment by yogevyuval** [comment]
From my experience with Jupyter Notebook the most convenient way to add or remove cells quickly is with a keyboard shortcut. Jupyter allows adding cells before / after by pressing 'a' / 'b'.

**Comment by s-celles** [comment]
From my experience of teaching programing to 18-19yo students, neither menus nor keyboard shortcuts can replace a well designed user interface. But I can perfectly understand that more experienced users have their productivity increased using shortcuts.

**Comment by captainsafia** [comment]
Thanks for opening this issue @scls19fr!

@fabric-8 Bringing this on to your radar for future design work.

**Comment by msschwartz21** [comment]
I have also found that I cannot change between cells using arrow keys in execution mode. Unfortunately this has really hampered my ability to use nteract in my daily workflows. I would love to see this arrow key feature which is common in jupyter notebooks incorporated in nteract.

**Comment by s-celles** [comment]
I haven't seen this feature (Insert Code Cell Above / Below) in Jupyter but in a [Javascript notebook](https://www.google.com/search?q=javascript+notebook)

That's why I also opened a similar issue in Jupyter repository https://github.com/jupyter/notebook/issues/4687

This UI idea is simple and interesting as it improves workflow significantly.

**Comment by s-celles** [comment]
@msschwartz21 what you are looking for is ability to move from 1 cell to an other one, which is (to my understanding), a different feature request... (and so could be suggested in an other issue)... but I 100% follow your idea... being able to move from one cell to an other one using arrows could be a great feature also!

**Comment by captainsafia** [comment]
Closing this.

We've redesigned the nteract UX and have something else in mind for this based on our redesign.
