### ISSUE TITLE
Markdown Cell: Style left "prompt area"

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#446]
I would suggest to add an indication on MD cell that there is a prompt area, at least on focus:

<img width="408" alt="screen shot 2016-05-14 at 10 35 38" src="https://cloud.githubusercontent.com/assets/335567/15269801/a8ee6574-19bf-11e6-89b4-b098ae877086.png">

**Comment by rgbkrk** [comment]
We should at the very least color the left hand draggable margin too.

**Comment by jdfreder** [comment]
I forget in which PR I fixed it, but this is fixed in master now...
