### ISSUE TITLE
Keyboard Shortcut for helping

### ISSUE THREAD

**Issue by 123385918** [nteract/archived-desktop-app#4462]
in jupyter notebook i press shift+tab for brief help and press shift+tab+tab for detailed help.
it's very useful for new functions.
can nteract add this keyborad help ?

**Comment by hydrosquall** [comment]
Hi @123385918, I think this keyboard shortcut may do what you seek, the control key + period command is equivalent to `shift+tab`. `ctrl`  + `.` . Please feel free to re-open if this doesn't work for you.

https://github.com/nteract/nteract/issues/3124
