### ISSUE TITLE
Confusing metadata regarding the version of nteract-on-jupyter

### ISSUE THREAD

**Issue by ocefpaf** [nteract/archived-desktop-app#4469]
I'm trying to package https://pypi.org/project/nteract-on-jupyter/2.0.12/ but while the PyPI version is 2.0.12 the source distribution provides 0.0.1-dev and the source here is 0.0.o-dev, see https://github.com/nteract/nteract/blob/54c50e856930e9489e9b920365dacc3f10320af4/applications/jupyter-extension/setup.py#L8

Not sure if the package on PyPI was originated from the code above BTW, this repo is quite big and hard to navigate, so feel free to close if I'm in the wrong place.

**Comment by wadethestealth** [comment]
Go to our files. Go into applications and then jupyter-extension. This is a monorepo, so things are sectioned off in folders

**Comment by ocefpaf** [comment]
> Go to our files. Go into applications and then jupyter-extension. This is a monorepo, so things are sectioned off in folders

This one?

https://github.com/nteract/nteract/blob/ea1048408d78acbdc0a03f00e9a42911dc7dc52f/applications/jupyter-extension/setup.py#L8

Looks like it is the one on PyPI but the versino confusion remains.

**Comment by willingc** [comment]
@captainsafia @rgbkrk To make things easier for the conda-forge distribution of nteract on jupyter, we should probably update the packaging for Python for this extension: updated version numbering in metadata, adding LICENSE and README (perhaps from the repo root) to Manifest. cc/ @betatim @ocefpaf

**Comment by captainsafia** [comment]
Closing this since we are planning on deprecating the Jupyter extension pretty soon.
