### ISSUE TITLE
What is the license for the nteract_on_jupyter package on PyPI?

### ISSUE THREAD

**Issue by ocefpaf** [nteract/archived-desktop-app#4470]
I could not find the license information or license file for package https://pypi.org/project/nteract-on-jupyter/ in the published tarball or in the folder here. Is it the same as nteract? BSD-3-Clause?

**Comment by willingc** [comment]
@ocefpaf Thanks for the work over on conda-forge. The LICENSE file for nteract on jupyter is the same as the nteract project.

**Comment by ocefpaf** [comment]
Thanks! Using that license for the conda package.
