### ISSUE TITLE
[feature-suggestion] Add Static Analysis / Automated Code Review Github App

### ISSUE THREAD

**Issue by hydrosquall** [nteract/archived-desktop-app#4490]
The nteract codebase is large, and keeping up to date with everything can be difficult. I recently came across a static analysis tool which is used to detect vulnerabilities, and scans open source projects for free. The report for nteract's repo is here:

https://lgtm.com/projects/g/nteract/nteract/overview/

From an initial scan of the "alerts", many of the listings are things which can be changed automatically, such as unused imports or variable assignments that never get used again. Others, are more subtle, and might hint at state management related issues or help with being proactive with potential bugs that haven't been reported yet.

If people are interested in this, I can add the app to the `nteract` project via Github marketplace. I wanted to ask before adding this since it would add a short term burst of automated PRs to the repository, similar to what `renovate-bot` is doing, and would add to the "visible" maintenance load for a little while. However, hopefully over the long run, it would make the job of maintainers easier :).

**Comment by captainsafia** [comment]
@hydrosquall I like this idea! Something similar has been growing in the back of my head as well but I haven't had the time to work on it. I'm all for adding it to our organization and seeing what kind of impact it will have on our bug load.

**Comment by hydrosquall** [comment]
Glad to hear it, thanks @captainsafia ! This will take effect next time a new pull request is opened, I've just added the app to the `nteract` repository only. If we find it useful, it can be enabled for other repositories too.

For future readers, documentation about how managing the app works is [here](https://lgtm.com/help/lgtm/github-apps-integration).
