### ISSUE TITLE
saveAsContentEpic uses wrong filepath

### ISSUE THREAD

**Issue by rachelgshaffer** [nteract/archived-desktop-app#4496]
**Application or Package Used**
nteract/core 10.6.0

**Describe the bug**
The saveAsContentEpic does not use the correct filepath when saving - it uses content.filepath instead of action.payload.filepath

**To Reproduce**
n/a

**Expected behavior**
It uses the passed in filepath: action.payload.filepath

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Windows10
- Browser: Chrome 

**Additional context**
n/a

**Comment by captainsafia** [comment]
Thanks for opening this issue, @rachelgshaffer!

I've submitted a PR to fix this in https://github.com/nteract/nteract/pull/4498. It should be in the next patch release of @nteract/core.
