### ISSUE TITLE
Launching kernels

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#45]
Given a kernelspec, launch a kernel. This doesn't have to take into account the UI aspect and may end up being a node package in its own right.

**Comment by rgbkrk** [comment]
Now I recall that @willwhitney already broke this out into a package in [jupyter kernel launcher](https://github.com/nteract/jupyter-kernel-launcher). Have at it, work with it, submit patches, ship it.

**Comment by willwhitney** [comment]
:D

**Comment by rgbkrk** [comment]
Split this into two issues:
- Node packages for launching them
- UI for selecting a kernel for launch

**Comment by rgbkrk** [comment]
Done.
