### ISSUE TITLE
Feedback on execution timing proposal

### ISSUE THREAD

**Issue by saulshanabrook** [nteract/archived-desktop-app#4509]
A frequently requested feature in JupyterLab is to be able to record when a cell starts and stops executing in the notebook. In the process of exploring this feature, we have discovered that there are actually many different events  we could consider as the "start" of the cell execution. So we are proposing adding a `timing` object to the `metadata` of each cell to the notebook format: https://github.com/jupyter/nbformat/pull/144

I wanted to let you know about this proposed change and get any feedback you had on it. Feel free to close this as you wish.

**Comment by captainsafia** [comment]
Creating a ref from an earlier nteract issue https://github.com/nteract/nteract/issues/2660 to this.

**Comment by captainsafia** [comment]
Closing this as we now support setting execution times in the notebook document per the newly adopted standard.
