### ISSUE TITLE
nteract server?

### ISSUE THREAD

**Issue by maddukurisrinivasarao** [nteract/archived-desktop-app#4511]
Jupyter Notebook launches python based webserver, is nteract also uses the same? or it has it's own webserver?

**Comment by captainsafia** [comment]
Hello @maddukurisrinivasarao!

The nteract desktop app does not launch its own web server. Instead, it directly communicates with the file system and the kernel to fetch contents and execute code.

The nteract Jupyter web app is an extension on the Jupyter server and communicates with the Jupyter server it is connected to.

**Comment by maddukurisrinivasarao** [comment]
Thanks @captainsafia
