### ISSUE TITLE
Failed to minify ./node_modules/@nteract/commutable/lib/primitives.js:32

### ISSUE THREAD

**Issue by nlaille** [nteract/archived-desktop-app#4513]
**Application or Package Used**
@nteract/commutable package (version 7.1.3)

**Describe the bug**
When building a react application using create-react-app, running npm run build returns a “Failed to minify” error resulting from ./node_modules/@nteract/commutable/lib/primitives.js:32

**To Reproduce**
Build a react application using create-react-app with @nteract/commutable dependency 

**Expected behavior**
Build succeed

**Comment by captainsafia** [comment]
Hello @nlaille! Thanks for opening this issue. Let's see if we can figure out what is going on here.

Do you have a repo with a simple reproduction for this issue? It would help in diagnosing the problem.

**Comment by nlaille** [comment]
I was able to fix it. I had to upgrade create-react-app to v2 or v3 instead of v1.
https://github.com/octokit/rest.js/issues/828
