### ISSUE TITLE
Focus on next cell when executing code cell should not enter edit mode

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4524]
**Problem**
Currently, when a user executes a code cell that comes before a markdown cell, the focus will shift to the markdown cell and enter edit mode. This is jarring and not the flow that users are used to in classic.

**Solution**
When shifting focus, we should check to see if the cell that focus is being shifted to is a markdown cell and not focus on the editor if so.

**Comment by motin** [comment]
Great observation! To add to this, I would expect to be able to Shift+Enter my way throughout the notebook, so it'd be great if the "not focus on the editor" still maintained information about that we are essentially in edit/execution mode without actually rendering markdown cells in edit mode.

**Comment by captainsafia** [comment]
@motin Agreed! I created a PR for this and requested your review.
