### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by nikivdev** [nteract/archived-desktop-app#4527]
**Is your feature request related to a problem? Please describe.**
I would love to have dark mode support added. I searched existing issues and found no issue that addresses this feature request.

**Describe the solution you'd like**
Add dark mode support. No glaringly white blank canvas. There should be option to have it use darker colors.

**Comment by captainsafia** [comment]
Hello @nikitavoloboev! Thanks for opening this issue.

Dark mode is already currently supported under the "Theme" menu option in the "View" menu.

Please re-open if you are having trouble configuring dark mode.

**Comment by nikivdev** [comment]
Is it possible to turn the top bar black on macOS?

![2019-08-22 at 17 14](https://user-images.githubusercontent.com/6391776/63531401-58ae4a80-c500-11e9-941e-23b98b378575.png)

**Comment by 7k50** [comment]
It would be good if the "Theme" setting was referenced in the online docs somewhere. Although obvious in hindsight, I didn't see this setting when looking the first time, and spent more time than I should have searching online for how themes work in nteract.

**Comment by captainsafia** [comment]
@nikitavoloboev It is possible but we will need to update the version of Electron that the application is on per [these instructions[(https://electronjs.org/docs/tutorial/mojave-dark-mode-guide). cc: @BenRussert 

@winterflags Thanks for the feedback! Would you be interested in submitting a PR to add this documentation over on the [documentation repo](https://github.com/nteract/docs)?

**Comment by Ornataweaver** [comment]
I suggest you look at https://draculatheme.com/ color syntaxing.
Currently if you type >>> help() in the notebook, some blue text is so dark that is unreadable on the dark background.
