### ISSUE TITLE
Lost all my works after nteract got stuck

### ISSUE THREAD

**Issue by ceruleangu** [nteract/archived-desktop-app#4540]
**Is your feature request related to a problem? Please describe.**
please enable auto save, thank you

**Describe the solution you'd like**
please enable auto save, thank you

**Describe alternatives you've considered**
please enable auto save, thank you

**Additional context**
please enable auto save, thank you

please enable auto save, thank you , thank you, thank you

**Comment by captainsafia** [comment]
Apologies for the inconvenience, @ceruleangu!

This is a known issue that has been reported in https://github.com/nteract/nteract/issues/4108.

I've been trying to find time to dig into it but haven't had the chance. I'll close this issue in favor of the older one above. Please follow that one for updates on a bug fix. Thank you.
