### ISSUE TITLE
Nonexisting file in CLI arguments ignored

### ISSUE THREAD

**Issue by rendaw** [nteract/archived-desktop-app#4547]
**Application or Package Used**
nteract desktop 0.14.5

**Describe the bug**
When specifying a nonexistent file on the command line nteract should create a new notebook with that name.  Currently it ignores the argument and creates a new file named `Untitled.ipynb`.

**To Reproduce**
In an empty directory run `nteract a.ipynb`

nteract starts with the filename `Untitled.ipynb` in the titlebar.  Pressing ctrl+s creates the file `Untitled.ipynb` in the current directory.

**Expected behavior**
A new notebook is created with the name `a.ipynb` and not `Untitled.ipynb`.

**Desktop (please complete the following information):**

- OS: Arch Linux
- Version 0.14.5

**Additional context**
I searched with various terms to see if there's a duplicate issue anywhere and found nothing, I apologize if this is a repeat or is already fixed.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @rendaw!

Our initialization code currently will fallback to an new  unnamed file if the current file doesn't exist. I think it makes the most sense to add an explicit `--create` flag to the CLI that will create a file with the given name if it doesn't exist and preserve the existing functionality in all other cases.

Would you be interested in submitting a PR with this change?

**Comment by rendaw** [comment]
Thanks for the quick response!

Most command line editors will create a new file when presented with a nonexistent file name: Vim, Emacs, KWrite, Atom, VS Code, Lyx.  Similarly other CLI tools also treat filenames for existing and nonexisting files the same: `echo hi > x.txt`, `touch x.txt`, `sqlite3 x.db`.  I think requiring a `--create` flag would be counter convention, and the reason you'd specifying a filename on the command line is expediency and requiring extra flags defeats that.

If the user specifies a filename on the command line it could mean one of two things: 1. they wanted to open an existing file with that name or 2. they wanted to create a new file with that name.  In neither case would creating a new file named `Untitled` be in line with the user's intentions.  Other programs such as Krita provide do an error message at startup when passed the name of a nonexistent file, which while not great IMO is better than complete silence.  Presumably in Krita's case it does this because it needs additional information to create the new file.

My reason for trying nteract out was that Jupyter's conventions are awkward and fly in the face of (my) typical desktop application usage scenarios.  nteract's big win here is how it feels natural to use and I think this would be a step in that direction.

**Comment by captainsafia** [comment]
@rendaw That's fair reasoning. I was optimizing for reducing the likelihood of regressions and the scope of the change by preserving as much of the existing code-base as possible.

I'm not too opinionated on a particular approach.

**Comment by rendaw** [comment]
Okay, great!  If you aren't opposed to the behavior I'm pushing I'll go ahead and make a PR.

**Comment by captainsafia** [comment]
Yes, please!
