### ISSUE TITLE
Add `kernelForContent` to support multi-kernel scenarios

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4566]
Currently, our execution and kernel-related epics extract the kernel that is reference by the `currentKernel` selector and identified by the `currentKernelRef` state in our core state.

The `currentKernelRef` is updated whenever the kernel we are connected to changes, either when switching to a new notebook or connecting to a different kernel.

The fact that only one kernelRef exists at a time presents a sticky predicament for scenarios where multiple notebooks are open within a single application, for example a workspace-based application where users can open multiple notebooks in an nteract view and execute code in them simultaneously.

Most of our actions already pass a ContentRef, so instead of using `currentKernel` in our epics and reducers we should use a `kernelForContent` selector that uses the correct kernel associated with the ContentRef.

**Comment by rgbkrk** [comment]
I think `currentKernelRef` needs to go away, as we should be determining the kernel via the `content` itself. For a `MultiKernelNotebook` it should have a record of each kernel it uses. There can be multiple kernels in the `kernelByRef` portion of the store.

**Comment by captainsafia** [comment]
Agree on `currentKernelRef` going way, but why should we remove determining the kernel by the current content? IMO, it makes sense for the kernelRef to be something on content (as it currently is) since the content is responsible for spawning the kernel.

**Comment by rgbkrk** [comment]
> why should we remove determining the kernel by the current content

We want to keep that.

> IMO, it makes sense for the kernelRef to be something on content (as it currently is) since the content is responsible for spawning the kernel.

👍

**Comment by captainsafia** [comment]
This is now implemented. There will likely be some lingering bugs as we start to use this more frequently but I am going to close this and track those issues separately.
