### ISSUE TITLE
SAVE_FAILED when not saving file

### ISSUE THREAD

**Issue by javad94** [nteract/archived-desktop-app#4569]
**Application or Package Used**
nteract desktop

**Describe the bug**
When running code without saving notebook, this error comes indefinitely.

**To Reproduce**

1. Open nteract desktop for windows.
2. Write and run some code.
3. The error comes in.

**Expected behavior**
This Error shouldn't show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/7765309/64920507-bebf8200-d7cd-11e9-892a-83d5380d293b.png)

**Desktop (please complete the following information):**

- OS: Windows 10 x64 build 1903
- Browser: Chrome v77.0.3865.75 
- Version: nteract desktop v0.15

**Comment by captainsafia** [comment]
Thanks for opening this issue, @javad94!

This happens because the auto-save functionality kicks in and dispatches a `Save` event but the save fail because of the directory the file is in.

To resolve this, we can add a permissions check to the auto-save logic to prevent it from dispatching an auto-save if the notebook is not writeable for any reason.

Tagging this for hacktoberfest participation.

**Comment by javad94** [comment]
Yes exactly. but this issue arises just in the latest version. there was no issue with saving in the previous version.

**Comment by captainsafia** [comment]
Correct, auto-save was broken in previous versions and was not dispatching the event. It was recently fixed and as a result we are now seeing these issues.

**Comment by javad94** [comment]
Ah, I see. Thanks for the information.

**Comment by jarmokivekas-fmi** [comment]
This issue also applies to installs on Ubuntu using the .deb packages, which saves in `/opt/nteract/Untitled.ipynb`

**Comment by captainsafia** [comment]
For Hacktoberfest participants: to resolve this issue, we need to add some logic to the auto-save epic that will not emit the save action under the following conditions:

- If the file doesn't exist, which can be determined when by either using fs.exists or querying the contents API in the case of a WebSocket kernel

This logic should be added in contents.ts within packages/epics.

**Comment by jatinparmar96** [comment]
@captainsafia I have tried to fix this issue but I am not able to publish my branch, getting error Permission Denied.

**Comment by irvslyy** [comment]
i can

**Comment by captainsafia** [comment]
Closing this as it was resolved via #4585.
