### ISSUE TITLE
Expose API handles for disposing of a notebook

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4571]
**Problem**
Currently, we don't expose any Redux actions or epics that handle disposing of a notebook once we are done with it.

In both desktop and web app, we rely on the assumption that the user will either close the application window (or the browser tab) and hence dispose of the Redux store and any open WebSocket connections.

We cannot always rely on this assumption in multi-notebook scenarios, such as users who are rendering NotebookApp components within a tabbed or paneled view.

**Proposed Solution**
We need to expose a set of actions/epics for handling the proper closing and disposing of a notebook.

- A `CloseNotebook` action that takes a `ContentRef`
- A reducer that listens for the `CloseNotebook` action and clears the notebook with that ContentRef from the state model. It should also shutdown the kernel and clear out the kernel state for the the kernel associated with that ContentRef
- Update the epics to close out any open comms or kernel watchers

**Comment by languy** [comment]
Attempt to fix here: #4597
