### ISSUE TITLE
RFC: @nteract/jupyter-widgets Implementation Approach

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4573]
**Note:** I'll update this document as I get feedback and clarify more details of the design. You can [view a history of the edits via GitHub](https://help.github.com/en/articles/tracking-changes-in-a-comment).

## Problem Statement

Currently, the nteract project does not export a React component that renders ipywidgets. As a result, users who want to leverage the functionality of a comms-enabled interactive widget API cannot use the nteract desktop and web applications or the nteract core SDK.

## Goals

The nteract project should ship a React component that renders ipywidgets that adhere to the comms message protocol and the ipywidgets convention. Furthermore, React component should provide developers consuming the API with the ability to:

- Replace the default renderer for widget components with a custom renderer that allows developers to ship an experience where ipywidgets rendered within a notebook have a look and feel similar to that of the parent application. This is similar to the functionality support by the Google Colab project in their web-based Jupyter notebook application.
- Allow developers consuming the API to wrap the rendered widgets inside an iframe or another mechanism that provides an isolation boundary between the ipywidget and the notebook. This allows developers consuming the API to isolate ipywidgets, which have the potential to execute malicious JavaScript, behind a secure isolation boundary.

The initial ipywidget implementation that we will ship will not include these two features by default but will expose points were consumers can implement them.

## Design and Implementation

This component will be shipped as a single nteract transform that takes a prop which defines the `model_id` of the widget that will be rendered by the transform.

```
import { WidgetDisplay } from "@nteract/jupyter-widgets";

return <WidgetDisplay data={{'model_id': 'some_model_id_here', version_major: 2, version_minor: 0}}/>
```

Furthermore, we want to continue to support scenarios where a widget might be rendered outside the context of a notebook, such as in the nteract play application. In this scenario, the `WidgetDisplay` transform will take an optional kernel property that can be used to configure the comms setup with the component. This kernel property accepts an interface that matches that of a `KernelRecord` from the nteract core SDK.

```
import { WidgetDisplay } from "@nteract/jupyter-widgets";

return <WidgetDisplay data={{'model_id': 'some_model_id_here', version_major: 2, version_minor: 0}} kernel={remoteKernelInstance}/>
```

Under the hood, the `WidgetDisplay` component will leverage three subcomponents: a `Manager`, a `Renderer` and a `BackboneViewer`.

### The Manager

The `Manager` is a React component that consumes a `model_id`, inherited from the `WidgetDisplay` component above and sets the React context for all children components to the data model. The manager is responsible for the following:

- Listening to `comm_open` messages with the `model_id` associated with the `model_id` property that it is given to the component.
- Setting the value of the model to the serialized model representation that is sent when the widget is first rendered via a `comm_open` message.
- Listening to `comm_msg` messages with the `model_id` associated with the `model_id` property that is given to the component and updating the state that is set in the context.
- Handles restoring the state of the widgets by sending `comm_info_request` and `request_state` messages over the comms protocol.
- Providing an `updateState` method in the context that nested components can invoke to update the state of a Backbone model and in return send an update to the kernel.

The functionality above will be implemented in RxJS epics that are exported individually out of the @nteract/jupyter-widgets package for developers consuming the package. The following pseudo-code outlines how the `Manager` component will be implemented.

```
const WidgetContext = React.createContext({ model: null, state: null, updateState: () => {}});

class Manager extends React.Component {
	componentDidMount() {
		// Fetch the latest state of the widget here
		// Register widget-watch epics
	}
	
	componentDidUpdate() {
		// Fetch the latest state of the widget here
	}
	
	componentWillUnmount() {
		// Clean up the state stored about the current widget
	}
	
	render() {
		return <WidgetContext.Provider>{this.props.children}</WidgetContext.Provider>;
	}
}
```

### The Renderer

The `Renderer` is a React component that consumes a serialized representation of the BackboneJS model and the current state of the widget  model. This information is set in the context of the component by the parent `Manager` component.

The renderer will also accept an `updateState` property that is invoked whenever it needs to change the context, in particular the state. This `updateState` function is implemented in the manager and is responsible for dispatching a request to update the kernel-side model of the state to the kernel.

In the future, developers can override the `Renderer` component in order to implement their own custom UI that maps serialized BackboneJS models to a rendered view.

### The BackboneWrapper

The `BackboneWrapper` is an internal React component that understands how to take a serialized representation of a BackboneJS model and return a view rendered by React. This implementation can extend upon some of the principles that are outlined in the [backbone-react-component](https://github.com/magalhas/backbone-react-component).  Admittedly, this is the part of the design doc that is most ambiguous. I'm certain there is some way to do it considering there is precedence in the package above and have started experimenting to see if it is possible to build an ipywidgets-specific implementation in https://github.com/captainsafia/backbone-renderer.

In summary, when the `WidgetDisplay` component will have an internal implementation that roughly mimics the following structure. Note that although the model and state are passed as explicit props in the sample below, in reality, they will be set via the WidgetContext and not passed explicitly.

```
class WidgetDisplay extends React.Component {
	render() {
		return (<Manager model_id="some_model_id">
                         <Manager.Provider>
                         <Manager.Consumer>
			    <Renderer model={serializedBackboneJSModel} state={state}/>
                        </Manager.Consumer>
                        </Manager.Provider>
		</Manager>);
	}
}
```

## Testing

In addition to unit tests, we'll also need to add the following tests to ensure the quality and functionality of the transform.

### Integration Testing

To validate that this component works, we'll need to run the following validations:

- Ensure that the basic widgets listed in the [ipywidgets documentation page](https://ipywidgets.readthedocs.io/en/latest/examples/Widget List.html) can render in the @nteract/jupyter-widgets transform.

### Performance Testing

To validate that this component functions performantly, we'll need to run the following validations:

- Render a notebook with numerous widgets and ensure that overall notebook performance is not compromise.
- Make repeated state updates to a widget and ensure that the performance of the individual widget component.

cc: @jasongrout @rgbkrk @jdfreder @williamstein @SylvainCorlay

**Comment by filipmihal** [comment]
I'm a huge fan of this :heart: 
What is your time estimate to have it ready for public use?

**Comment by captainsafia** [comment]
@filipmihal The master branch currently has an implementation of ipywidgets that supports the default set. If you'd like to try it out, you can set up a development build of nteract.

This should land in a desktop release sometime soon.

**Comment by captainsafia** [comment]
Gonna go ahead and close this since the base implementation is pretty much wrapped up.

We've got a few bugs and lingering issues tagged with pkg:jupyter-widgets that we can monitor.

This hasn't landed in a desktop release yet. We should probably ship out a desktop release after the holidays.

**Comment by jdfreder** [comment]
Awesome!
