### ISSUE TITLE
Restart kernel yields a 500

### ISSUE THREAD

**Issue by languy** [nteract/archived-desktop-app#4575]
**Application or Package Used**
nteract on jupyter, nteract SDK.

**Describe the bug**
When issuing a restart kernel, either from the "Runtime" dropdown menu item in the nteract webapp or dispatching a `restartKernel` action, I'm observing:
a. a DELETE call on the current session 
b. a POST call on sessions
c. a POST call on /api/kernels/<current kernel id>/restart. This fails with a 500 response.

The jupyter console shows:
jupyter-lab     |         raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
jupyter-lab     |     tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 1ed91ae8-a636-41de-ad2b-4020987d1688)

I'm not the expert here, but I believe the DELETE call isn't necessary and causes the /restart call to fail, because the kernel has been previously removed by the DELETE call.

This problem isn't visible from the user's perspective (as the kernel is effectively restarted), but it always produces RESTART_KERNEL_SUCCESSFUL as well as RESTART_KERNEL_FAILED actions which show conflicting error/success messages to the user in my application.

**To Reproduce**

1. Open nteract on jupyter
2. Click on Runtime
3. Select Restart Kernel
4. Observe Network tab on developer console and Redux actions

**Expected behavior**
Jupyterlab just produces a single call to /api/kernels/<kernel id>/restart
KERNEL_RESTART followed by either KERNEL_RESTART_SUCCESSFUL or KERNEL_RESTART_FAILED.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @languy!

I'm tagging this one for our Hacktoberfest 2019 participation as it should be manageable for a new contributor.

For Hacktoberfest 2019 participants: the [restart epic](https://github.com/nteract/nteract/blob/master/packages/epics/src/kernel-lifecycle.ts#L214) will need to be updated to only dispatch a single call to the restart API when the kernel that we are connected to is a WebSocket kernel. You can do a search for "websocket" in the codebase to find if-statements where this casing is used.

If the kernel the application is connected to is a zeromq kernel, the restart epic should continue to function as is.
