### ISSUE TITLE
Change kernels doesn't get saved

### ISSUE THREAD

**Issue by languy** [nteract/archived-desktop-app#4576]
**Application or Package Used**
Using nteract on jupyter

**Describe the bug**
Changing kernel in notebook doesn't get saved.

**To Reproduce**

1. Open notebook
2. Select from the dropdown menu Runtime -> Change Kernel -> new kernel
3. Save notebook
4. Close notebook
5. Open notebook: the current kernel displayed at the bottom is not the newly selected kernel in step 2.

**Expected behavior**
I expect the opened notebook to show the newly selected kernel.
Changing on jupyterlab will display the new kernel.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
I debugged this and here's what I found out:
* In this [reducer](https://github.com/nteract/nteract/blob/0da75faefc6cef1bcf3ad86847a454b8f88d388d/packages/reducers/src/core/entities/kernels.ts#L92), CORE/SET_KERNEL_INFO sets `core/entities/kernels/byref/id/info`, but not `core/entities/contents/byRef/id/model/notebook/metadata/kernelspecs`
* The [SaveContentEpic](https://github.com/nteract/nteract/blob/0da75faefc6cef1bcf3ad86847a454b8f88d388d/packages/epics/src/contents.ts#L341) uses the `content`'s `metadata` field to persist to disk, so it will persist the wrong (old) `metatdata/kernelspecs`.
* When opening the notebook, the old kernel gets used.

**Comment by captainsafia** [comment]
We should update the `CORE/SET_KERNEL_INFO` to update both sets of kernel_info here.

I can take a look at this today.
