### ISSUE TITLE
Pop a notification while the gist is uploaded.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#458]
I just use the "publish > to gist.." I was confused as it took a few second and I had no visual feedback.

**Comment by rgbkrk** [comment]
A precursor notification, like "uploading"?

**Comment by Carreau** [comment]
Yeah. Or a random text like "compositing antimater artifact", "computing lowest energy state", "Prepare for FTL jump"

**Comment by rgbkrk** [comment]
omg, we need those for the loading screen. I forgot about that.

**Comment by Carreau** [comment]
Want to create a fake scifi scientific sentence generator package on npm ?

**Comment by Carreau** [comment]
https://github.com/kylestetz/Sentencer
