### ISSUE TITLE
SAVE_FAILED because of inaccurate last_modified property

### ISSUE THREAD

**Issue by languy** [nteract/archived-desktop-app#4583]
**Application or Package Used**
nteract on jupyter, nteract SDK

**Describe the bug**
I'm running a jupyter server with the nteract-on-jupyter extension from a docker container.
The first save of a notebook succeeds, but subsequent save attempts result in SAVE_FAILED emitted.
The failures happen [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnteract%2Fnteract%2Fblob%2F0da75faefc6cef1bcf3ad86847a454b8f88d388d%2Fpackages%2Fepics%2Fsrc%2Fcontents.ts%23L439&data=02%7C01%7CLaurent.Nguyen%40microsoft.com%7C4de5384c34d34a801b7b08d742d974bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637051374047481130&sdata=Q1mhQTtt39ZO%2FYL4COPd5ZrgbAMkg4RX%2Bt8QYULV4yw%3D&reserved=0): `diffDate` in my case is well over 600ms.

Looking into the issue, I found that the jupyter server returns an incorrect last_modified value on the PUT call to save content. I checked the jupyter server python source code and it seems correct AFAICT: it checks the file attribute after writing, but the last_modified field returned by PUT is definitely “earlier in time” compared to what File Explorer (or ls -la in my docker container) reports. Maybe the write is async and jupyter server is checking for last_modified before the write is finished. 
 
So it looks like this Math.abs(diffDate) > 600 test is a workaround for this jupyter problem. If we had an accurate last_modified date, we would be doing a strict === comparison to avoid any possible race condition. The first Save works, because fetching content gets the correct last_modified value and diff is 0ms.

I'm filing this to either be able to configure/overwrite this 600 magic number or to find a way to reduce the ms difference (for example by checking last_modified repeatedly [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnteract%2Fnteract%2Fblob%2F0da75faefc6cef1bcf3ad86847a454b8f88d388d%2Fpackages%2Fepics%2Fsrc%2Fcontents.ts%23L450&data=02%7C01%7CLaurent.Nguyen%40microsoft.com%7C4de5384c34d34a801b7b08d742d974bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637051374047491127&sdata=sxuKAA%2BEcUVsEQzjGFep7d5yKD5ewg86IYJt6GPn7xQ%3D&reserved=0) until is stabilizes (assuming the write async hypothesis is true)) and dispatch save_fulfilled with a more accurate last_modified value.

**To Reproduce**

1. Run nteract on docker container (or somewhere with a slow file system)
2. Open notebook. Save it.
3. See it again -> notice the save failure
4. Try again and it always fails

**Expected behavior**
Save should work.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**

**Comment by languy** [comment]
I figured out the following logic to repeatedly check until a value is stable:

```export const adjustLastModifiedOnSaveEpic = (
  action$: ActionsObservable<actions.SaveFulfilled>,
  state$: StateObservable<AppState>
): Observable<{} | CdbActions.UpdateLastModifiedAction> => {
  return action$.pipe(
    ofType(actions.SAVE_FULFILLED),
    mergeMap(action => {
      // Retry updating last modified
      const currentHost = selectors.currentHost(state$.value);
      const serverConfig = selectors.serverConfig(currentHost as JupyterHostRecord);
      const filepath = selectors.filepath(state$.value, { contentRef: action.payload.contentRef });
      const content = selectors.content(state$.value, { contentRef: action.payload.contentRef });
      const lastSaved = (content.lastSaved as any) as string;
      console.log("lastSaved", lastSaved);

      // Query until value is stable
      return interval(500)
        .pipe(take(4))
        .pipe(
          mergeMap(x =>
            contents.get(serverConfig, filepath, { content: 0 }).pipe(
              map(xhr => {
                if (xhr.status !== 200 || typeof xhr.response === "string") {
                  return undefined;
                }
                const model = xhr.response;
                const lastModified = model.last_modified;
                console.log("queried lastModified", lastModified);
                if (lastModified === lastSaved) {
                  return undefined;
                }
                // Return last modified
                return lastModified;
              })
            )
          ),
          distinctUntilChanged(),
          mergeMap(lastModified => {
            console.log("Final lastModified", lastModified);
            if (!lastModified) {
              return empty();
            }

            return of(
              CdbActions.updateLastModified({
                contentRef: action.payload.contentRef,
                lastModified
              })
            );
          })
        );
    })
  );
};
```

**Comment by captainsafia** [comment]
Thanks for opening this issue, @languy!

Context for readers: this piece of code carries over some logic that exists in classic to assert that the local_modified value is as expected. Notably, the Jupyter server can sometimes return a skewed value due to FS issues so this hard code value accounts for that.

Thanks for sharing your example solution!
