### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by wadethestealth** [nteract/archived-desktop-app#4601]
Documentation links inside the `README.md` of a couple of nteract package are broken (ex: commutable and rx-jupyter). To fix them it only requires a `.html` at the end, but I am unsure if you accidentally changed something on nteract.io where routing no longer works without `.html` so I am openning an issue for it

**Comment by captainsafia** [comment]
There was an issue with docs links for package names that had a dash in the name. I just fixed the path to the commutable docs in https://github.com/nteract/nteract/commit/412ee4276593343f74ba880377d42f440aa5aa4e.

Will go ahead and close this now.
