### ISSUE TITLE
Cannot assign a custom renderer in nteract/markdown

### ISSUE THREAD

**Issue by chenxinyanc** [nteract/archived-desktop-app#4609]
**Is your feature request related to a problem? Please describe.**
I want to add some extra spacing before and *after* rendered code fence. But I couldn't find a location where I can customize it.
```ts
const App: React.FC = () => {
  return (
    <div className="App">
      <div style={{ border: "1px solid red" }}>
        <MarkdownRender source={"test\n```ts\ncode fence\n```"} />
      </div>
    </div>
  );
}
```
![image](https://user-images.githubusercontent.com/50703224/66731221-df403200-ee88-11e9-82ac-61ca0f7d1df7.png)

The `margin: 0` is hard-coded in the generated HTML, so I actually cannot change it.
![image](https://user-images.githubusercontent.com/50703224/66731286-2cbc9f00-ee89-11e9-9cdb-1f26867804c5.png)

**Describe the solution you'd like**
Simply moving L27 (the spread operator) to L30 should do. I will at least be able to place all the code block inside a `<div>` that gives it extra spacing. This is only possible if I can set the renderer from outside the `MarkdownRender`.
https://github.com/nteract/nteract/blob/17b124e512e65c0094adfa402b521c439f677ec8/packages/markdown/src/index.tsx#L26-L31

**Describe alternatives you've considered**

**Additional context**

**Comment by wadethestealth** [comment]
Pretty sure your solution was how it was supposed to be created, but the implementer must have forgot that the last value takes precedence. You can submit a PR for this and the nteract contributors will make sure this doesn't break any of their packages, and then merge.
