### ISSUE TITLE
Client keeps reconnecting to the old kernel when there's a kernel switch

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#4612]
**Application or Package Used**
nteract web, nteract on Jupyter

**Describe the bug**
The client keeps reconnecting to the old kernel when there's a kernel switch.

**Expected behavior**
The client should dispose the old socket connection and switch to the new kernel

**Comment by captainsafia** [comment]
This should be resolved now. Please re-open if this is not the case.
