### ISSUE TITLE
where is the documentation?

### ISSUE THREAD

**Issue by Abdelkrim** [nteract/archived-desktop-app#4621]
**Where is the documentation?**

* nteract keeps stating : "SAVE_FAILED - EPERM: operation not permitted, open 'C:\Program Files\nteract\Untitled.ipynb'"
* bottom-left of the screen is 'no kernel|not connected'
* the menus do not contain any 'settings' kind of option

![nteract-jupyter-setup-cropped](https://user-images.githubusercontent.com/791663/67048922-631e4680-f135-11e9-8734-3d8fa2bd2869.png)

**the solution I'd like**

* Provide a clear, step by step documentation to setup a local environment including nteract and jupyter

**Describe alternatives I've considered**

* there is no alternative besides not using nteract

**Additional context**

not relevant

**Comment by captainsafia** [comment]
Hello @Abdelkrim!

The error you are seeing around the save failing is related to two things:

- When you open nteract it opens the default notebook at the install location, which often users don't have write permissions two
- nteract's auto-save logic is being triggered eagerly so the error occurs frequently

With regard to the settings option, there is currently an open PR to add a preferences window which should resolve this.

As for the kernel not being connected, does this still happen when you select the kernel from the `Runtime` menu?

**Comment by willingc** [comment]
Closing this issue as stale. If you are still experiencing this issue, please feel free to comment here. Thanks.
