### ISSUE TITLE
Default dark theme for JupyterHub web UI

### ISSUE THREAD

**Issue by TortelliniLeap** [nteract/archived-desktop-app#4634]
Is there a way to make the dark theme default for all JupyterHub users when using the Nteract web UI? In `~/.jupyter/nteract.json`, I have `{"theme": "dark"}`, but it doesn't seem to take effect.

**Comment by captainsafia** [comment]
It appears that the initial state for the nteract web app is not configured to read the chosen theme from the state.

I think that reading from the `nteract.json` config is only applicable to the desktop app and not the web app. @rgbkrk can you confirm?

If that is a case, we'd probably need to figure out a configuration story for the web app.

**Comment by rgbkrk** [comment]
That's correct, the nteract config only applies to the desktop app. It would be great for the web app to also use the config.
