### ISSUE TITLE
Support showing/hiding all cell inputs/outputs independently

### ISSUE THREAD

**Issue by alpaix** [nteract/archived-desktop-app#4665]
This issue affects `@nteract/actions` package. Currently, `UNHIDE_ALL` action unconditionally resets all cell inputs and outputs visibility. There is no support for independently changing visibility of inputs or outputs.

**Expected behavior**
We need a method of only changing visibility of all cell inputs or outputs independently. For instance, when getting asked to hide all cell outputs, the `UNHIDE_ALL` action should keep visibility of cell inputs untouched.

**Comment by captainsafia** [comment]
@alpaix This is now released in the latest version of @nteract/core.
