### ISSUE TITLE
The latest nteract/editor 9.2.10 depends on nteract/output 2.3.6 which is not published in npm yet

### ISSUE THREAD

**Issue by song888k** [nteract/archived-desktop-app#4668]
The latest nteract/editor 9.2.10 depends on nteract/output 2.3.6 which is not published in npm yet. Please fix asap.

https://www.npmjs.com/package/@nteract/editor
https://www.npmjs.com/package/@nteract/outputs

**Comment by captainsafia** [comment]
Hello!

A recent publishing problem has broken this dependency. It is resolved now. 

Apologies for the inconvenience!
