### ISSUE TITLE
nteract fails to start on Windows when it does not find python. 

### ISSUE THREAD

**Issue by aviks** [nteract/archived-desktop-app#4672]
**Application or Package Used**

nteract-desktop

**Describe the bug**

nteract fails to start, with an error message about not finding python

**To Reproduce**

1. Click the `nteract` item on the start menu. 
2. nteract fails to start 

**Expected behavior**

nteract to start and display its main window. 

**Screenshots**

![image](https://user-images.githubusercontent.com/378918/68086485-8a1e8d00-fe44-11e9-9aff-4e37d3e4f9e7.png)

**Desktop (please complete the following information):**

- OS: Windows 10 v1903

**Additional context**
nteract v 0.15.0
Python has *not* been installed on this system. 

I think this used to work earlier. Is there a new dependency on python?

**Comment by aviks** [comment]
cc: @captainsafia This is the issue we talked about. Thanks for a great product!

**Comment by captainsafia** [comment]
Thanks for opening this issue, @aviks!

After looking around, I believe that what you are experiencing is the same as #4637. It looks like we might have picked up a Python-dependency somewhere in the desktop app. I'll look around and see what when that happened.

**Comment by aviks** [comment]
Thanks for investigating. I agree, this looks to be the same issue. I'll close this as a duplicate of #4637
