### ISSUE TITLE
Same widget model not synced across different views

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4681]
In the `Widget Low Level.ipynb` example, the widget slider that is rendered in the notebook does not sync changes across the different views that are rendered. All widgets should update simultaneously.

![widget-sync](https://user-images.githubusercontent.com/1857993/68348667-6743e100-00af-11ea-8535-ea7012f0059f.gif)

**Comment by miduncan** [comment]
Just to give a little more detail on this, this only applies when `display(w)` calls are within milliseconds of each other. If you were to manually run two different `display(w)` cells, they would be synced.
