### ISSUE TITLE
RFC: Stateful Components and Theming

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4696]
### Problem

Currently, nteract's component and theming story is only partial implement. We started development a component ecosystem in the [@nteract/ion project](https://github.com/nteract/ion) but parked that work while we iterated on presentational components in the nteract notebook app. Our component system has evolved and we've got quite a few pieces of feedback in issues and direct reports about ways to improve this component API. This RFC is an effort to push this through.

What exactly is the problem?

Currently, it's rather difficult for user's to compose their own nteract-based applications. From my observation, this is the result of a few things.

- Our @nteract/presentational-components are opinionated about what styles are applied to them. Not all users building on top of nteract might want to adopt these tiles.
- Our @nteract/notebook-app-component is very monolithic and contains quite a few pieces that would make more sense factored out into their own units such as the `TransformMedia`, `Cell`, `CellToolbar`, and `CellCreator` components.
- Our theming story is limited and it is difficult for community members and developers building on top of our API to theme nteract-based applications.

### Goals

We need to solve this problem! I believe our goals for this solution should as follows:

- Improve the maintainability of the nteract component ecosystem between the components that are under @nteract/presentational-component, @nteract/connected-components and @nteract/notebook-app-component, our component story is quite difficult to reason about for contributors and maintainers.
- Create more atomic and composable units for developers building nteract-based components
- Make it easy for developers and community members to theme nteract components via styled-components or stylesheets
- Create documentation for developer building nteract-based applications to make it easier for developers to build maintainable UIs based on the nteract component ecosystem.

### Proposed Solution

The proposed solution largely rests in cleaning up how we export and document the presentational components, how we manage and load our stylesheets, how we connect Redux to presentation components, and how we expose class names as interfaces that users can extend with their themes.

Currently, most of the presentational components that we export are styled dependent on our styled sheets. This is fine for our scenario but we should also export unstyled components that set the appropriate CSS classes so that component consumers can style them independently. The components should still maintain their semantic structure but should be more meaningful to decouple from state.

Also, there is a monolithic `AnyCell` component that acts as the connected component that wraps all individual presentation components. This pattern should be decomposed so that the state and actions for inputs are mapped separately from the state and actions for outputs and so on. Instead of a singular `mapStateToProps` and `mapDispatchToProps` function for the entire cell, we should decompose it into smaller pieces.

With all of this, I anticipate that we'll be able to use the components a little something like this. Within nteract we export the following.

```
export class BareOutputs extends React.Component {}
const Outputs = connect(mapStateToProps, mapDispatchToProps)(BareOutputs);
export styled(Outputs)`${our CSS here}`;
export default Outputs;
```

L3 and L4 above can be invoked by developers building on top of the component system with their own styles. Another benefit of this is that we can increase the performance of our application by moving the connects from a top-level component to a lower-level component. ([ref](https://github.com/reduxjs/redux/issues/419#issuecomment-129188175))

On the topic of styles, our styling vars are currently a little opaque. While investigating accessibility issues a few weeks ago, I identified some improvements that we can make to our CSS variable guidelines to improve maintainability and the ability to create new themes:

- Reducing the number of aliases for colors
- Creating a common set of colors that are used in both the light and dark theme

### Implementation

While researching for this RFC, I found a couple of things that we can do right away to improve the experience of using our component system, including:

- [ ] Move the `TransformMedia` component out of `@nteract/notebook-app-component`
- [ ] Move the assembled `Cell` component out of the `@nteract/notebook-app-component`
- [ ] Move the `MarkdownPreview` component out of the `@nteract/notebook-app-component`
- [ ] Move the `Editor` component to a new `@nteract/editor-base` package

In the long-term, to execute on this work, we'll need to do the following.

- [ ] Update shadow level logic in Cell component to set CSS classname instead of applying styles
- [ ] Update className on source component
- [ ] Export `BarePrompt` component in `prompt.tsx`
- [ ] Set class names in Prompt component based on component states
- [ ] Parameterize `promptText` function in `Prompt` component
- [ ] Clean up and document CSS variables in nteract CSS to make them more semantic
- [ ] Export `BareImport` component in `input.tsx`
- [ ] Decompose `AnyCell` component to smaller connected components

With this in mind, below is the list of components that will need to be developed/moved, their corresponding top-level CSS classname and their various CSS class name based states.

| Component   |  Class Name   |  State Class Names                                    | 
|-------------|---------------|-------------------------------------------------------| 
| Cells       |  .cells       |  .focused - .error - .hover                           | 
| Cell        |  .cell        |  .focused - .error - .hover                           | 
| Input       |  .input       |  .focused - .error - .hover                           | 
| Prompt      |  .prompt      |  .focused - .error - .hover - .busy - .idle - .queued | 
| Source      |  .source      |  .focused - .error - .hover                           | 
| Editor      |  .editor      |  .focused - .error - .hover                           | 
| Pagers      |  .pagers      |  .focused - .error - .hover                           | 
| Pager       |  .pager       |  .focused - .error - .hover                           | 
| Outputs     |  .outputs     |  .focused - .error - .hover                           | 
| Output      |  .output      |  .focused - .error - .hover                           | 
| Toolbar     |  .toolbar     |  .focused - .error - .hover                           | 
| Cell Banner |  .cell-banner |  .focused - .error - .hover                           | 
| Status Bar  |  .status-bar  |  .focused - .error - .hover - .busy - idle            |

**Comment by CrystallineCat** [comment]
What's the difference between `@nteract/stateful-components` and `@nteract/connected-components`?

**Comment by captainsafia** [comment]
`@nteract/stateful-components` have no styling. The components in `@nteract/connected-components` use Blueprint.js for UI rendering.

Also, I wanted to be able to iterate on this new package without tampering in one that is already used.

**Comment by CrystallineCat** [comment]
Thank you!

**Comment by captainsafia** [comment]
Closing this since it has been implemented and shipped.
