### ISSUE TITLE
`TypeError: Cannot read property 'get' of undefined` when this.props.model is yet not defined

### ISSUE THREAD

**Issue by motin** [nteract/archived-desktop-app#4708]
**Application or Package Used**
nteract desktop

**Describe the bug**
`TypeError: Cannot read property 'get' of undefined` is thrown when this.props.model is yet not defined. 
The Jupyter widget [ipyfilechooser](https://pypi.org/project/ipyfilechooser/) demonstrates this behavior.

**To Reproduce**

1. Open nteract
2. Run `!pip install ipyfilechooser`
3. Run:
```
from ipyfilechooser import FileChooser

# Create and display a FileChooser widget
fc = FileChooser('/Users/motin')

display(fc)
```

4. No output is rendered. Error thrown in the console:
```
TypeError: Cannot read property 'get' of undefined
```

Source line in `nteract/packages/jupyter-widgets/src/manager/index.tsx`, in the `render` function:
```
model: this.props.model.get("state"),                
```

**Expected behavior**
The widget should display / render.

**Desktop:**

- OS: MacOS Catalina
- Browser: n/a
- Version: n/a

**Additional context**

This can be remedied (verified locally) by adding the following to the top of the render function in `nteract/packages/jupyter-widgets/src/manager/index.tsx`:

```
    if (!this.props.model) {
      return null
    }
```
The widget will then render properly. Seems to hackish to be a real solution though.

**Comment by captainsafia** [comment]
Hello @motin!

Is this on the latest master?

There's either a regression in our rehydration logic or this is a scenario that happens when the ipywidget is a custom widget (which are not supported at the moment).

cc: @miduncan

**Comment by motin** [comment]
Hi :)

> Is this on the latest master?

Yes it was at the time of the issue creation.

> There's either a regression in our rehydration logic or this is a scenario that happens when the ipywidget is a custom widget (which are not supported at the moment).

It doesn't require any lab extensions or similar, not sure if that is what defines a widget as a custom widget.

**Comment by captainsafia** [comment]
Hi @motin! Can you give it another try? We've been making a lot of changes to the ipywidgets implementation so there is churn in the active bugs.

As for the custom widget bit,, I took a look and it appears that ipyfilechooser is not a custom widget. It's a Python module that assembles the standard ipywidgets in a certain way.

Custom widgets are [defined here](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html).

**Comment by captainsafia** [comment]
I just tried this and I can see the ipyfilechooser widget rendered inside the nteract desktop app from the current master.

![image](https://user-images.githubusercontent.com/1857993/70167012-afd4c700-167a-11ea-9ba8-18100fef244d.png)

I'll go ahead and close this issue. Please re-open if you are still running into it.
