### ISSUE TITLE
Azure build pipeline fails

### ISSUE THREAD

**Issue by CrystallineCat** [nteract/archived-desktop-app#4727]
The Azure build pipeline [fails to build nteract](https://dev.azure.com/nteract/nteract/_build/results?buildId=6014). An exception occurs upon importing IPython, claiming unsupported python version.

The last successful build was with `ipython@7.9` (requires `python@3.5`).
The unsuccessful builds are with `ipython@7.10` (requires `python@3.6`).

I do not know how to fix this.

**Comment by captainsafia** [comment]
There appear to be some version incompatibilities here. I'm not sure how to fix it either.

Considering the Azure Pipelines build is not doing much for us, anyways. I've gone ahead and disabled it in this repo.
