### ISSUE TITLE
Add support for vega-lite v4

### ISSUE THREAD

**Issue by CrystallineCat** [nteract/archived-desktop-app#4750]
This probably involves:
- [ ] Maybe make an external repository for vega-lite@3?
- [ ] Update typescript (vega-lite@4 uses a newer version)
- [ ] Update vega/vega-lite/vega-embed

I'm going to take a look at this.

**Comment by domoritz** [comment]
Than you @CrystallineCat. I was about to file an issue for this. Let me know if you run into issues.
