### ISSUE TITLE
Remove "Save Successful" toast on autosave?

### ISSUE THREAD

**Issue by dougdenn** [nteract/archived-desktop-app#4768]
**Is your feature request related to a problem? Please describe.**
The "Save Successful" dialog pops up every time the notebook is auto-saved and it's really distracting, especially in dark mode where the toast has a white background.

**Describe the solution you'd like**
I think the toast makes sense on manual saves but not autosaves - for those I think the info in the bottom right (Last saved less than a minute) is good enough. Maybe it could say "Autosaved" to let new users know that autosave is implemented.

I saw the [issue here](https://github.com/nteract/nteract/issues/4567#issuecomment-561801711) that the auto save interval is going to be configurable, which is great, this might just be the last piece needed for that.

Would the team be interested in a PR for this?

![image](https://user-images.githubusercontent.com/30697943/70805128-d8954480-1d7d-11ea-9ef7-8e8f5c597e52.png)

**Comment by captainsafia** [comment]
Hi @dougleville!

Thanks for opening this. Funny coincidence -- I was thinking about something similar just last night.

I agree that it should be removed and am partial to removing all notifications in general and relying on in-app cues to notify users of when important things have happened (like a kernel restarting or a save completed). This will be resolved with our upcoming redesign of nteract. Stay tuned for the interactive mockups of this so you can share feedback there.

In the meantime, would you be interested in removing the notification system components out of the desktop app?

**Comment by dougdenn** [comment]
@captainsafia Sure thing 👍
