### ISSUE TITLE
es2017 target in TS build has incompatibilities with some browsers

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#4775]
It looks like rx-jupyter uses arrow functions which is not supported in IE. It would be great if we could use function declarations or something similar that worked with IE.

**Comment by captainsafia** [comment]
For more context, @virangai provided me some additional details offline. The fact that we target es2017 causes some issues in older browsers that don't have native support for certain features, like arrow-functions.

IMO, we should evaluate browser-compat for different ES versions and make a choice around what to target once we have evaluated that.

I'm hesitant to downgrade our build target if this is the only issue that exists with the current one.

But, we should do some research and see if there are best practices on what to set the target to.

**Comment by willingc** [comment]
This has been open for a few months without additional compatibility issues being filed. Given @captainsafia's response, I'm going to close this issue with the resolution that the current target is appropriate and we can continue to look at ES version targets in the future.
