### ISSUE TITLE
No search function available

### ISSUE THREAD

**Issue by libphy** [nteract/archived-desktop-app#4803]
I've looked in the keyboard shortcuts and could not find a way to search words. Please let me know if I missed where it is.. Otherwise, please consider adding that- in my personal opinion, without a search function, it feels limited as a coding tool.

**Comment by CrystallineCat** [comment]
Hi @libphy, thanks for opening this issue!

Unfortunately, there isn't a search function just yet. There's a previous issue suggesting one: #1817. I'm intent to tackle that soonish, but that might still be a while.
