### ISSUE TITLE
[META] Extensions

### ISSUE THREAD

**Issue by jdfreder** [nteract/archived-desktop-app#481]
I'd like to start the discussion of extensions.  I think there are some cool things we can do with the npm API to find locally or globally installed extensions and load them dynamically.   Both would provide a stellar user experience.  I think and we could build an in app UI on top of it too.  

I haven't thought much about React extension points, but I'm sure that's a well worn trail.  Seems like as an MVP, extension writers would need to be able to A) provide custom reductions B) provide components or override components for given extension points in the nteract React DOM.

**Comment by rgbkrk** [comment]
My favorite example of this is [hyperterm](https://hyperterm.org/), particularly in defining a structure for registering and relying on Redux as the plugin mechanism (actions, middlewares, etc.). I think we could build something pretty cool here.

**Comment by rgbkrk** [comment]
Oh, and the quintessential [nylas - building plugins for react apps](https://nylas.com/blog/react-plugins) post!

**Comment by rgbkrk** [comment]
Now that we've been at this for a bit, I think there are three main points of extensions we should aim for supporting:
- Themes
- Custom renderers #670
- Publication

**Comment by rgbkrk** [comment]
We currently have a simple configuration file so in lieu of letting us expand our scope too much, I'll close this and we can open it again at a later date.
