### ISSUE TITLE
All the "VIEW CODE" links are broken on the components documentation page

### ISSUE THREAD

**Issue by pnsvinodkumar** [nteract/archived-desktop-app#4811]
Can you please help fix?

![IMAGE 07-01-20 AT 6 30 AM](https://user-images.githubusercontent.com/8133035/71860152-c6f25300-3117-11ea-9a98-1b3df5971e9b.jpeg)

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @pnsvinodkumar! There was a recent deployment of the docs page so I suspect that is causing this issue. I'll look into it and see what is up.
