### ISSUE TITLE
<Ansi /> component should have optional linkify prop

### ISSUE THREAD

**Issue by twavv** [nteract/archived-desktop-app#4815]
Not following the issue template because I'm not quite sure how this fits in. I just wanted to point out that the `linkify` prop of the `Ansi` component (in `ansi-to-react`) should be optional in TypeScript (all of the examples show it as optional).

**Comment by captainsafia** [comment]
Thanks for opening this issue, @travigd!

Would you be interested in submitting a PR with a fix?
