### ISSUE TITLE
Issues running Julia code in nteract

### ISSUE THREAD

**Issue by logankilpatrick** [nteract/archived-desktop-app#4820]
macOS Catalina 

I am trying to run the code here:
<img width="931" alt="Screen Shot 2020-01-10 at 5 28 09 AM" src="https://user-images.githubusercontent.com/35577566/72146227-03b58880-336a-11ea-8963-dd2531d0c75e.png">
 
However, it says no kernel even though I have IJulia installed in Julia 1.2 and 1.3. What am I missing?

**Comment by logankilpatrick** [comment]
Why does it say not connected?

**Comment by captainsafia** [comment]
Hello @logankilpatrick! Let's see if we can resolve this. Some questions:

- How did you install the Julia kernel?
- What is the result of running `jupyter kernelspec list` in your console?
- Do you see any errors in the console when you do View > View Developer Tools?

**Comment by logankilpatrick** [comment]
```

Available kernels:
  python3      /Users/logankilpatrick/anaconda/lib/python3.5/site-packages/ipykernel/resources
  julia-0.6    /Users/logankilpatrick/Library/Jupyter/kernels/julia-0.6
  julia-1.2    /Users/logankilpatrick/Library/Jupyter/kernels/julia-1.2
```

**Comment by logankilpatrick** [comment]
The developer tools showed I needed to build a package so thanks for helping with that. The issue is resolved.  It is a bit weird that it doesn't say that on the top level and that I have to go into the dev tools to see the error.

**Comment by captainsafia** [comment]
Glad the issue was resolved, @logankilpatrick!

Did you get a notification stating that the kernel failed to launch?

If it showed up in the console, it likely happened deeper down in kernel launch flow (I suspect when launching the Julia kernel process) and didn't get bubbled up.

**Comment by willingc** [comment]
@logankilpatrick I'm going to close this. If there are further questions, please do let us know. Thanks.
