### ISSUE TITLE
Cell status doesn't update when "interrupted" by launchKernelByName

### ISSUE THREAD

**Issue by lbarons** [nteract/archived-desktop-app#4847]
**Application or Package Used**
notebook-app-component

**Describe the bug**
During cell execution, if LAUNCH_KERNEL_BY_NAME is emitted, the existing cell that was running will have its websocket connection reset, and (as expected) output may stop showing. But in the background the cell execution completes and the next cell can be run. But what is not expected is the cell's status (busy) stays stuck in the busy state even if it is completed running.

**To Reproduce**
1. Have a long-running cell (some sleeps and prints) that defines a variable in its last line
2. launch kernel by name while the cell is running
3. Wait long enough, and try to run a cell that prints the variable defined in previous cell.

This was reproduced in our code by refreshing our page, which hits the launchKernelWhenNotebookSet epic during a long execution cell. This should also be reproducible by a LAUNCH_KERNEL_BY_NAME action being emitted during cell execution.

**Expected behavior**
Expectation is that cell output will seem to halt, but when the behind the scenes execution completes, the status of the cell changes from busy state to completed state (showing execution count).

**Screenshots**
![image](https://user-images.githubusercontent.com/9374083/72831789-69422880-3c38-11ea-8709-20a4bed8ad23.png)

^As you can see from the above screenshot, after waiting long enough I was able to run the second cell that proved k was defined, and the previous cell completed execution, but the previous cell still looks like it is in the busy state.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**

**Comment by captainsafia** [comment]
Hello @lbarons! Thanks for reporting this issue and providing many helpful details.

This issue was resolved in #4849. From now on, whenever a kernel is successfully interrupted, the state of any queued or running cells will be cleared.

This fix will be in Monday's release of nteract. Please re-open this bug if you continue to run into the issue after upgrading your @nteract/core dependency.
