### ISSUE TITLE
Autosave could use a better reaction to write permission failure

### ISSUE THREAD

**Issue by kbasye00** [nteract/archived-desktop-app#4858]
Using the nteract desktop app (for which, much thanks!), I noticed that opening a read-only notebook results in an error box popping up on the screen about every 5 seconds.  That's pretty distracting.  Also the status bar says "Not saved yet" which is certainly true but not as informative as it could be.  

I think once there's been a permission failure on autosave, the autosave should just shut off.  Also the status bar should get something very noticeable like "Not saved - file is read-only"
Users can either use Save As to get a writable file or change the permissions and use Save for themselves (and then maybe turn the autosave back on? - I don't know here).  

I guess you could just move the error reporting to the status bar and leave the autosave on, that would be a lot less distracting than the current pop-up error.  

Thanks for reading, I like this app so far.

**Comment by captainsafia** [comment]
Hello @kbasye00! Thanks for opening this issue and glad you like the app so far.

This issue should've been resolved in the latest release of the nteract desktop app (nteract v0.21.0). Can you reproduce it in that version?

**Comment by willingc** [comment]
Closing as resolved. If you can reproduce in 0.22 or later, please let us know. Thanks.
