### ISSUE TITLE
Notification System problems

### ISSUE THREAD

**Issue by CrystallineCat** [nteract/archived-desktop-app#4870]
At the moment, `desktop` on `master` is generating a `SET_NOTIFICATION_SYSTEM` with a payload of
```typescript
{ notificationSystem: undefined }
```

This appears due to a mix of `ref` styles; changing `notebook/index.tsx` to
```tsx
<NotificationSystem ref={this.notificationSystem} />
```
will fix this issue. However, when a notification is then issued, I get errors in the console, which appears to be a often reported spurious bug, e.g.:
* https://github.com/igorprado/react-notification-system/issues/168
* https://github.com/igorprado/react-notification-system/issues/165
* https://github.com/igorprado/react-notification-system/issues/143

The core issue appears to be that when the elements inside the notification system's render function are created, the `owner` is set to undefined. I've stepped through with the debugger, and the static `ReactCurrentOwner.current` is set at the beginning of the render function, but is undefined at the time of the `createElement`-call.

The reason for this might be due to webpack splitting the object. It has several `ReactCurrentOwner`s, and I'm unsure how to trace that they all refer to the same object.

I guess this would prioritize #3503?

**Comment by captainsafia** [comment]
This one is quite a gnarly one! I'm not sure what triggered this issue. I  recently made some changes to the ref handling to fix some build issues but it was broken before those changes, if I recall correctly.

In any case, I'm cool with migrating to BlueprintJS and shipping that in the next release.

Thanks!
