### ISSUE TITLE
Will not connect to python virtual environment

### ISSUE THREAD

**Issue by mpcarter** [nteract/archived-desktop-app#4883]
Running nteract v0.21.0 desktop on Windows 10. No conda environment. Just using plain Python 3.8 venv environments. Followed instructions from your site to install kernel for virtual environments (modified for Windows). 
```
python -m venv main   
main\Scripts\activate.bat  
python -m pip install ipykernel        
python -m ipykernel install        
```
It installs kernel spec to `C:\ProgramData\jupyter\kernels\python3`. The kernal.json file looks like
```
{
 "argv": [
  "C:\\Users\\mcarter\\.venv\\main\\Scripts\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

When I start nteract I can see it correctly detects _Python 3_ among the available kernels. It says _not connected_. I try to run a simple command like `1 + 1` or `import sys`. Then it says _launching_. Then it never does anything after that. 

I have tried uninstalling (including removing `C:\Users\mcarter\AppData\Roaming\nteract` ) and reinstalling. Both to Program Files and in `C:\Users\mcarter\nteract\`. I've tried reviewing logs (that I could find) and nothing stands out. 

I just use virtual environments in my Python setup. My global environment is clean. So I cannot run `jupyter kernelspec list` from global. However, when I run it from my virtual environment I see
```
(main) $ jupyter kernelspec list
Available kernels:
  python3    c:\users\mcarter\.venv\main\share\jupyter\kernels\python3
```

The kernel.json file there is
```
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

I'm just providing as much info as I can think of because I am not sure what is relevant. If there are any steps I could perform to better diagnose what is happening please let me know.

**Comment by mpcarter** [comment]
Another bit of info to add. The first time I try to run a code cell, I get Windows Firewall asking if I want to grant nteract access over Private networks.

**Comment by goerz** [comment]
I have the same problem on macOS: a kernel that worked fine on the previous version started to just hang at "launching" after I installed nteract 0.21.0

**Comment by captainsafia** [comment]
Hello folks! Thanks for opening this issue. I'm going to go ahead and cross-ref this to https://github.com/nteract/nteract/issues/3862.

At some point, we had functional support for kernels in environments. That logic hasn't changed in years, AFAIK, so I suspect there has been an unintended upgrade to a dependency or a break in these packages.

@BenRussert @lgeiger @lgeiger I think you folks have the most amount of knowledge about kernel discovery and launch in the desktop app. Do you know what might be going on here?

Thanks for the patience and the bug report folks.

 > Another bit of info to add. The first time I try to run a code cell, I get Windows Firewall asking if I want to grant nteract access over Private networks.

Albeit alarming, this is expected. The nteract desktop app communicates with the kernels over TCP. Windows sees this and throughs an alert to the user. This particularly happens for the Windows desktop app because we don't have a certificate for it yet so Windows interprets the app as "unauthenticated."

Our goal is to get the app authenticated or add it to the Windows app store so that users will see less of these alarming messages.

**Comment by goerz** [comment]
It would be really nice if nteract had a log file with the kind of information that `jupyter notebook --debug` emits on the command line, just to get an understanding of what's actually going on.

**Comment by captainsafia** [comment]
Update: Just saw that @CrystallineCat did some debugging on this and cited the [nteract/kernelspecs](https://github.com/nteract/kernelspecs) package might need some polish.

Currently, there are two key packages that exist out of the monorepo but support the functionality of the desktop app:

- [nteract/kernelspecs](https://github.com/nteract/kernelspecs) for kernelspec discovery
- [spawnteract](https://github.com/nteract/spawnteract) which launches kernel processes

@CrystallineCat hypothesized that a bug in the kernelspecs package would affect all environment setups, not just conda. This issue does help validate that hypothesis.

> It would be really nice if nteract had a log file with the kind of information that jupyter notebook --debug emits on the command line, just to get an understanding of what's actually going on.

I think an nteract log file is a good addition to have. Mind opening a separate issue for that?

As for next steps for this, I think  it makes sense to have someone clone the nteract monorepo, set it up for development, and then debug the launch interaction in debug mode with debuggers/print statements/and so on. Would any of you be interested in doing that in your environments? Happy to help with setup.

Given the severity and longevity of the issue, I think we should prioritize it for the February release. That being said I'm not sure if this is a quick one-line fix or something that will be more involved.

**Comment by mpcarter** [comment]
Think this might be related to this issue with Python 3.8.0. 
https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8-notimplementederror

I upgraded to Python 3.8.1 and then upgraded notebook, ipykernel, etc. Now nteract working with my virtual environmen.

**Comment by captainsafia** [comment]
Thanks for adding this additional info, @mpcarter. I'm just starting to work on sorting out the conda detection issue so it is good to know that it is indeed an issue with just conda as opposed to virtual environments in general.

I'll go ahead and close this issue and we can continue focusing on resolving the conda-related issues.
