### ISSUE TITLE
0.21.0 Desktop | Markdown cell input visibility doesn't toggle

### ISSUE THREAD

**Issue by eimfach** [nteract/archived-desktop-app#4886]
**Application or Package Used**
nteract desktop 0.21.0 | macOS 10.15.2

**Describe the bug**
I noticed that input visibility for markdown cells does not collapse automatically when I double click another markdown cell (where editor section is initially closed) for editing. 

- Simplified, every input to a markdown cells stays visible.

**Screenshots**
De-collapsed markdown cells:
<img width="784" alt="Bildschirmfoto 2020-01-28 um 23 56 31" src="https://user-images.githubusercontent.com/6602910/73312796-e61d6580-4229-11ea-9fec-b7a606de14b7.png">

**Desktop (please complete the following information):**

macOS 10.15.2

**Comment by captainsafia** [comment]
Thanks for creating a separate issue for this, @eimfach!

I was also able to reproduce this yesterday when I was doing some writing work in nteract last night.

I suspect that the issue as a result of the recent changes to the `MarkdownPreviewer`component.

When the user double clicks on markdown cell B, the `editorFocused` property in the nteract state is set to that cell's ID. However, the React component for markdown cell A doesn't update to reflect this.

I suspect that the solution here is to add a `shouldComponentUpdate` function to the MarkdownPreviewer component to get it to respect changes in the editorFocused state that happen elsewhere.

I can tackle this for next month's desktop app release.
