### ISSUE TITLE
Desktop 0.21.0 | Should not require kernels to be installed to view notebooks

### ISSUE THREAD

**Issue by jamesmyatt** [nteract/archived-desktop-app#4894]
**Application or Package Used**
nteract desktop app

**Describe the bug**
As of nteract 0.21, the default mode is view-only, which should allow the user to view notebooks but not executre them. Hence, it should not be an error if there are no kernels available.

**To Reproduce**

1. Open nteract desktop v0.21 on a system with no kernels in global environment
2. See error

**Expected behavior**
User should be able to view and edit ipynb files, but not execute notebooks even if there are no kernels in the global environment.

**Screenshots**
```
[Window Title]
No Kernels Installed

[Main Instruction]
No kernels are installed on your system.

[Content]
No kernels are installed on your system so you will not be able to execute code cells in any language. You can read about installing kernels at https://ipython.readthedocs.io/en/latest/install/kernel_install.html
Full error: UNKNOWN: unknown error, lstat 'C:\Users\MYAJ\AppData\Local\Microsoft\WindowsApps\python.EXE'

[OK]
```
**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: N/A
- Version 0.21

**Additional context**
I only install kernels in virtual environments (e.g. conda or venv). My global Python environment is as clean as possible.

There are many issues about nteract not correctly detecting kernels, but this is a different angle.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @jamesmyatt!

This was an oversight during the validation of the feature since all the testing environments had Jupyter installed and as a result didn't hit this codepath.

This will be addressed for the February release.
