### ISSUE TITLE
Kernelspec name is being set to language name and they aren't an exact match

### ISSUE THREAD

**Issue by brism17** [nteract/archived-desktop-app#4895]
**Application or Package Used**
    "@nteract/core": "10.10.0-alpha.0"

**Describe the bug**
In kernel-lifecycle.js file in the acquire KernelInfo method the language name is being used to populate the kernelspec name field but this is incorrect. the kernelspec name returned from nteracts fetchkernelspecs call is more of an id. For example the langauge name is python and the kernelspec name is python3.  In jupyter classic the notebook metadata under kernelspec info uses the kernelspec name of python3 and its the expected behavior if you want to use a notebooks metadata to find the correct kernelspec match.

**To Reproduce**
1. Create a python3 notebook in jupyter classic. Look at the notebook metadata. 
2. Run the notebook in nteract and make sure this epic is called. 
3.  Save notebook and open the notebook metadata again
4. You will see that information about the notebooks kernelspec has been updated with the incorrect information . 

**Expected behavior**
Kernelspec name would be returned in the same format from the compute kernelspec and the notebook kernelspec.

**Comment by captainsafia** [comment]
Hello @brism17! Thanks for opening this issue.

There was a change made recently to support appropriately changing kernels in nteract-based applications. As a result, the `setKernelMetadata` reducer uses the kernel data stored in the kernelspecs record to fetch the details of the notebook. However, there wasn't a change to which properties from the kernelspecs record it mapped to which properties in the kernel metadata.

For example, here is the notebook metadata in a new Python 3 notebook made in Jupyter classic.

```
{
  "kernelspec": {
    "name": "python3",
    "display_name": "Python 3",
    "language": "python"
  },
  "language_info": {
    "name": "python",
    "version": "3.7.1",
    "mimetype": "text/x-python",
    "codemirror_mode": {
      "name": "ipython",
      "version": 3
    },
    "pygments_lexer": "ipython3",
    "nbconvert_exporter": "python",
    "file_extension": ".py"
  }
}
```

And here is the metadata from a new Python 3 notebook created in the nteract desktop app (after launching a kernel and running through the `setKernelMetadata` codepath.

```
{
  "kernel_info": {
    "name": "python3"
  },
  "language_info": {
    "name": "python",
    "version": "3.7.1",
    "mimetype": "text/x-python",
    "codemirror_mode": {
      "name": "ipython",
      "version": 3
    },
    "pygments_lexer": "ipython3",
    "nbconvert_exporter": "python",
    "file_extension": ".py"
  },
  "kernelspec": {
    "argv": [
      "/usr/local/opt/python/bin/python3.7",
      "-m",
      "ipykernel_launcher",
      "-f",
      "{connection_file}"
    ],
    "display_name": "Python 3",
    "language": "python",
    "name": "python3"
  }
}
```

As you can see, the `display_name`, `language`, and `name` properties under the kernel spec object are the same.

Can you share the metadata of the notebook affected by this issue and the payload the call dispatched action you suspect is causing this?

**Comment by captainsafia** [comment]
Quick follow-up: are you able to reproduce this using v10.11.0-alpha.0? I think you are running into an issue that was resolved in a PR in December.

**Comment by brism17** [comment]
Oh excellent! I will close this issue. We are in progress in updating to the latest version now. I will close the issue.
