### ISSUE TITLE
Provide error messages when no kernelspecs detected

### ISSUE THREAD

**Issue by rkpatel33** [nteract/archived-desktop-app#490]
When I run `npm run start` the app get's stuck on the "Loading..." screen below. Also, under the `File > New` menu, I only see `Bash` as an option and no `Python`. 

I don't see any error message in the terminal window. Any ideas on what I am doing wrong?

![image](https://cloud.githubusercontent.com/assets/3799489/15450369/87d18cf6-1f67-11e6-9126-11e315e8732f.png)

**Comment by captainsafia** [comment]
Hello, @rkpatel33! Thanks for opening this issue. Let's see if we can figure it out.

Can you try doing View > Toggle Developer Tools and see if there are any errors in the console?

**Comment by rkpatel33** [comment]
Hello. Here's what I get:

![image](https://cloud.githubusercontent.com/assets/3799489/15450566/79d0f380-1f6c-11e6-94eb-4b6173b0e5b7.png)

**Comment by captainsafia** [comment]
Hm. I see. It looks like you are working off the latest master and don't have everything set up properly since we've upgrade to Node 6.

Make sure that you have Node 6 installed, if you installed node using `brew` you will need to run `brew update` then `brew upgrade node` to get Node 6. After that, remove (`rm -rf`) your `node_modules` and run `npm install` again. Let me know if that works!

**Comment by rkpatel33** [comment]
Awesome, that worked! Thanks!

One more question -- now I get the message `The cell could not be executed because the kernel is not connected.` when I try to run a python command. How do I connect the python kernel?

**Comment by rgbkrk** [comment]
The IPython kernel is not installed into the kernelspecs directory that Hydrogen, nteract, and other non-Python frontends to Jupyter look for. Instead, Jupyter treats python as a default kernel. To install it yourself, use:

```
python3 -m pip install ipykernel
python3 -m ipykernel install --user
```

**Comment by robintw** [comment]
Thanks @rgbkrk, that fixed my problem with the Python kernel too :)

**Comment by rgbkrk** [comment]
Thanks for trying this out and rolling through the growing pains @robintw!
