### ISSUE TITLE
0.21.0 Desktop | what about Autocomplete ?

### ISSUE THREAD

**Issue by nweibel** [nteract/archived-desktop-app#4905]
**Application or Package Used**
 nteract 0.21.0 desktop

**Describe the bug**
I don't see any autocomplete suggestion anymore. How can I activate it ?

**To Reproduce**
type any code... no suggestion appears

**Expected behavior**
In previous version, I could see suggestions for instructions and functions or variables names

**Desktop (please complete the following information):**
- OS: macOS 10.14.6

**Comment by willingc** [comment]
Thanks for the report. Confirming that I see this behavior on 0.22 with the python kernel.

**Comment by karthik2k2** [comment]
Confirming the report in 0.22 with the python kernel.

**Comment by captainsafia** [comment]
To activate autocomplete, be sure that you have connected to a kernel then press Ctrl + Space to activate auto-complete.

Tangentially, like this comment if you would like us to revert https://github.com/nteract/nteract/pull/4712 and bring back the typeahead feature that activated autocomplete at certain tokens (equal sign for assigning variables, a period for function invocation, etc).

**Comment by willingc** [comment]
@captainsafia Confirming that autocomplete does work on 0.22 after pressing Ctrl + Space to activate for a line of code.

<img width="370" alt="Screen Shot 2020-03-29 at 5 00 32 PM" src="https://user-images.githubusercontent.com/2680980/77864745-3b9cd100-71df-11ea-8400-ec91ffe39fe0.png">


The autocomplete activation (Ctrl + Space) seems to be local to the cell not the entire notebook. Does that seem correct to you?

**Comment by karthik2k2** [comment]
yes.it works, but seems to be local to the cell..I wish there were some way to make it global

**Comment by captainsafia** [comment]
> The autocomplete activation (Ctrl + Space) seems to be local to the cell not the entire notebook. Does that seem correct to you?

Yes, this behavior is correct. This is because the keyboard shortcut is currently handled by the CodeMirror editor. As a result, it only works when the editor is focused.

If we wanted to make it global, we would have to do #4741 to move the completion logic out of the editor and make it triggerable via a global keyboard shortcut.

**Comment by willingc** [comment]
Linking to the documentation on Autocomplete Activation and Shortcuts https://github.com/nteract/nteract/blob/master/USER_GUIDE.md#general-shortcuts

I'm going to close this as resolved. Thanks @captainsafia for the explanation.

**Comment by vinbrule** [comment]
> > The autocomplete activation (Ctrl + Space) seems to be local to the cell not the entire notebook. Does that seem correct to you?
> 
> Yes, this behavior is correct. This is because the keyboard shortcut is currently handled by the CodeMirror editor. As a result, it only works when the editor is focused.
> 
> If we wanted to make it global, we would have to do #4741 to move the completion logic out of the editor and make it triggerable via a global keyboard shortcut.

Hi, however on jupyter notebook, no need to press Control + Space to have autocomplete. This behaviour is not consistent between application.  It should not be considered as `feature` but a bug.

**Comment by captainsafia** [comment]
> Hi, however on jupyter notebook, no need to press Control + Space to have autocomplete. This behaviour is not consistent between application. It should not be considered as feature but a bug.

nteract previously supported trigger completion at certain intervals but this feature was recently removed because many users reported it was more cumbersome than helpful. 

We might bring this back once we made some other improvements to the stability of overall completion logic, such as #4741.
