### ISSUE TITLE
arm64 debian package and/or appimage.

### ISSUE THREAD

**Issue by AdrianKoshka** [nteract/archived-desktop-app#4913]
**Is your feature request related to a problem? Please describe.**
I'm a user of an arm64 chromebook, and I use crostini to run linux applications. Sadly, nteract doesn't have a debian package or appimage for arm64 systems.

**Describe the solution you'd like**
An arm64 debian package and/or appimage, for use on arm64 systems.

**Describe alternatives you've considered**
Not using nteract.

**Additional context**
N/A

**Comment by captainsafia** [comment]
Thanks for opening this issue, @AdrianKoshka!

Supposedly, electron-builder can be [configured to support arm64](https://www.electron.build/cli) but we don't have this configuration enabled at the moment.

Would you be interested in submitting a contribution to add this support? It will require [editing the build configuration](https://github.com/nteract/nteract/blob/master/applications/desktop/package.json#L47) for the desktop app and validating that the nteract desktop app works on your OS.

Happy to help with the setup/testing for this contribution since I don't have an arm64 machine myself.

**Comment by AdrianKoshka** [comment]
Sorry about accidentally closing the issue. How would one install/setup electron-builder?

**Comment by captainsafia** [comment]
You'll have to fork and clone the repository per our CONTRIBUTING.md first. Once you've done that, you can install the dependency by running `yarn` in the root.

The `dist` command in the `package.json` for the desktop app runs the electron-builder command line using the configuration within that package.json.

[Here's a link to the package.json](https://github.com/nteract/nteract/blob/958b7bfef7820e2781124c5ea4641a150b64b484/applications/desktop/package.json).

Let me know if you have any follow-up questions.

**Comment by ramantehlan** [comment]
@AdrianKoshka, this seems to be answered in the issue [4943](https://github.com/nteract/nteract/issues/4943) | [Comment-5920084248](https://github.com/nteract/nteract/issues/4943#issuecomment-592084248)
 
> **nteract** recently published its first [**Snap**](https://snapcraft.io/nteract) to [Snapcraft](https://snapcraft.io), which should work with all the major Linux distros including Debian based distros. If you are new to Snaps, you can learn more about it from [here](https://snapcraft.io/docs/getting-started), and download it for your distro from [here](https://snapcraft.io/docs/installing-snapd).
> 
> For Debian based distro:
> 
> ```
> sudo apt update
> sudo apt install snapd
> ```
> 
> Once you have installed it, you can install `nteract` by:
> 
> ```
> sudo snap install nteract --edge
> ```
> 
> > Our **next release is on 30th March 2020** and since **Snaps are updated automatically**, you don't need to worry about updating it once downloaded.

**Comment by AdrianKoshka** [comment]
The snap only supports amd64.

**Comment by ramantehlan** [comment]
nteract snap only supports `amd64` systems right now, but the support for `arm64` Debian package is added and it will be available with the next release on **30th March 2020**.

I think you can really help with testing it. If you are interested in that you can join nteract slack channel [here](https://slack.nteract.io/), and I will send you the `arm64` `.deb` file to test.
