### ISSUE TITLE
Pagers import error

### ISSUE THREAD

**Issue by lynma01** [nteract/archived-desktop-app#4914]
nteract desktop version 0.21.0

**Hello, I'm having an issue displaying Pagers in nteract.**

**When I tried to import Pagers following the directions from this nteract.io documentation screen,**

![Annotation 2020-02-07 pagers](https://user-images.githubusercontent.com/11153510/74057014-0a5b0e00-49b1-11ea-9857-473ffa8b11a1.jpg)

**I received this error**

![Annotation 2020-02-07 original error](https://user-images.githubusercontent.com/11153510/74056920-e0a1e700-49b0-11ea-98d3-f501d3c480d6.jpg)

**I tried re-downloading the presentational components using the directions in github:**

![Annotation 2020-02-07 132856](https://user-images.githubusercontent.com/11153510/74057672-6c684300-49b2-11ea-9a14-0b9bbdd60327.jpg)

 **I installed both Chocolately and Yarn to do so:**

![Annotation 2020-02-07 choco install](https://user-images.githubusercontent.com/11153510/74057778-a0dbff00-49b2-11ea-83e8-00b3eb64c4e8.jpg)

![Annotation 2020-02-07 yarn + presentational components](https://user-images.githubusercontent.com/11153510/74057820-b3eecf00-49b2-11ea-85b0-53f1fd6cedb0.jpg)

**Nonetheless, I still have the same error trying to import Pagers, and many of the warning messages are indecipherable to me. Thank you for your help.**

- OS: Windows 10
- Chrome
- Nteract Desktop Version 0.21.0

**Comment by wadethestealth** [comment]
Pagers arent an ipython widget. They are apart of our special components package meant for people developing javascript applications. Ie you can't use them in your notebooks.
