### ISSUE TITLE
"nteract" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by gitjeff05** [nteract/archived-desktop-app#4915]
<img width="532" alt="Screen Shot 2020-02-07 at 6 15 13 PM" src="https://user-images.githubusercontent.com/548922/74072869-4a80b780-49d6-11ea-97da-ef0721a346f0.png">

I'm on OSX 10.15.3. I just clicked the link from your homepage:

https://github.com/nteract/nteract/releases/download/v0.21.0/nteract-0.21.0.dmg

Downloaded successfully but that is the error I got when I tried to open the app.

**Comment by ahmelsayed** [comment]
right click -> Open, instead of double click. 

non of the packages are signed as far as I can tell

**Comment by lschwetlick** [comment]
I had the same thing, but when I opened Security & Privacy after that popup appeared, under the General Tab, there was a little message saying "we blocked this app, click here to open anyway". After clicking that it worked.

**Comment by captainsafia** [comment]
Thanks for posting on this issue folks.

The nteract macOS apps are signed although it’s right around the annual renewal time for the certificates from Apple so I wonder if something is up with that. I’ll check and circle back here.

Slightly tangential, our Windows apps are not signed at the moment.

**Comment by willingc** [comment]
Confirming that I was able to download and install to 10.14.6 without a security warning. I will check on 10.15 when I am on my other laptop.

**Comment by captainsafia** [comment]
Tacking on to this. Our Apple certificate is still valid and I am working on renewing it today.

@gitjeff05 Are you able to reproduce this on nteract 0.22?

**Comment by gitjeff05** [comment]
@captainsafia Yes I am.

![nteract-err](https://user-images.githubusercontent.com/548922/77575035-48e95100-6ea9-11ea-8d52-ce7a1b6ccd26.png)

**Comment by willingc** [comment]
@gitjeff05 In addition to right-click open, you may need to adjust your System Preferences for Security. Specifically, make sure that you have selected Allow Downloaded Apps from App Store and Identified Developers.

<img width="661" alt="Screen Shot 2020-03-25 at 12 45 31 PM" src="https://user-images.githubusercontent.com/2680980/77578982-b8a21080-6e96-11ea-8d6f-ac1387cde8a8.png">

**Comment by gitjeff05** [comment]
Thank you @willingc and @captainsafia. I checked my settings and I do have "App Store and Identified developers" selected.

Just to be clear about why I opened this issue: I legitimately believe nteract has some cool and interesting things going on. It's exciting to see someone do something different at the data science notebook UI layer. This security warning for the desktop app was troubling to me, though. This is why I opened this issue -- _to make you all aware that many potential users could be seeing this warning_. It was meant as a courtesy, certainly not a complaint. I appreciate what you do.

If you think most your users are willing to bypass the warning, then please close this issue. I ran like a frightened cat in the night, but I scare easy.

_Aside_: In the most recent VS Code upgrade, I just happened to see this in their changelog:
https://github.com/microsoft/vscode/issues/74782. It appears they went through the same thing. Builds need to be notarized perhaps? https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Good luck, fellow campers. Looking forward to see where nteract goes from here.

**Comment by captainsafia** [comment]
@gitjeff05 Totally understand the intent behind opening the issue. Thanks for pointing the reference to the VS Code thread. It appears that Apple's requirements changes sometime in early 2020 and this is what is causing nteract to appear under the security flag now.

We probably won't be able to tackle this in time for the March release, but we can see if we can get a fix out for the April release.

nteract is a volunteer-run project, so if anyone on this thread is interested in making an open source contribution with the fix, that would be greatly appreciated!

**Comment by robertlagrant** [comment]
Just a confirmation: I'm on MacOS Catalina and I got the same warning with the latest nteract , which I could still click through when going into Settings and Privacy.

**Comment by captainsafia** [comment]
I still haven't had the chance to go through the notarization docs and get that set up yet. I believe myself and @rgbkrk are the only ones with Apple Dev program accounts who can do this so this process is a bit bottlenecked.

Marking this for the July release so we can get it sorted this month hopefully.

**Comment by captainsafia** [comment]
OK! The latest release of the nteract desktop app (0.25.1) is notarized. Try it out and let me know how it works. Setup for it is in the PR referenced above.
