### ISSUE TITLE
nteract on windows crashes upon startup

### ISSUE THREAD

**Issue by Monte-Christo** [nteract/archived-desktop-app#4916]
nteract crashes upon startup. Screenshot of error message is attached. I installed these .Net kernels. What am I missing?

`
(base) PS C:\src> jupyter kernelspec list
Available kernels:
  .net-csharp        C:\Users\EDKN\AppData\Roaming\jupyter\kernels\.net-csharp
  .net-fsharp        C:\Users\EDKN\AppData\Roaming\jupyter\kernels\.net-fsharp
  .net-powershell    C:\Users\EDKN\AppData\Roaming\jupyter\kernels\.net-powershell
  python3            C:\Users\EDKN\AppData\Local\Continuum\anaconda3\share\jupyter\kernels\python3
`

![nternact](https://user-images.githubusercontent.com/8224318/74141335-06203200-4bf7-11ea-83d8-d8457e843b86.PNG)

I reviewed the instructions below, but found them of no use to me:
https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments

Regards,

EK

**Comment by colombod** [comment]
Are you starting nteract from an anaconda prompt?

**Comment by Monte-Christo** [comment]
No. It’s a Windows application. There is a shortcut on the start menu. So you want me to get the full path and type that into an Anaconda CMD window?

 

EK

**Comment by Monte-Christo** [comment]
This does the trick in a Anaconda PowerShell window:

 

$pgm = $env:ProgramFiles + "\nteract\nteract.exe" ; start-process $pgm

 

But the instructions should be clearer.

 

Thanks,

 

EK

 

From: edgar.r.knapp@gmail.com <edgar.r.knapp@gmail.com> 
Sent: Monday, February 10, 2020 5:46 PM
To: 'nteract/nteract' <reply@reply.github.com>; 'nteract/nteract' <nteract@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [nteract/nteract] nteract on windows crashes upon startup (#4916)

 

No. It’s a Windows application. There is a shortcut on the start menu. So you want me to get the full path and type that into an Anaconda CMD window?

 

EK

**Comment by gitblit** [comment]
See #4957 for an alternate solution.

**Comment by willingc** [comment]
Thanks all. I'm closing this and we will keep #4957 open for tracking.
