### ISSUE TITLE
Top level Immutable.js for app state

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#493]
Our `state` should be an Immutable.js structure (especially since we use it everywhere else). Then we can nuke the whole `...state` return from reducers, opting for `.setIn`, etc. That object rest spread ends up doing an `Object.assign`, copying things along the way.

We can go full immutable, even though some branches of the tree are mutable objects. This includes, e.g., `channels`.

This is a follow up to #194

**Comment by captainsafia** [comment]
I think this was addressed in #518 and can be closed.
