### ISSUE TITLE
Dark Theme Markdown Text Unreadable

### ISSUE THREAD

**Issue by wctaylor** [nteract/archived-desktop-app#4940]
**Application or Package Used**
nteract desktop 0.21.0

**Describe the bug**
The font color used in Markdown cells is extremely difficult to see on the dark background and makes the text effectively illegible. The text while editing is fine, but the rendered text is not.

**To Reproduce**

1. Create a Markdown cell with text
2. Choose the dark theme with View-->Theme-->Dark
3. Struggle to read Markdown text

**Expected behavior**
Expected the text to be white or at least a bright color for better contrast on the dark background. I believe this was the case in previous versions.

**Screenshots**
![Screenshot from 2020-02-20 15-01-18](https://user-images.githubusercontent.com/8593481/74974956-279dcc80-53f4-11ea-9d00-73df9de37a15.png)

**Desktop (please complete the following information):**

- OS: Pop!_OS 19.10
- Version: nteract desktop AppImage 0.21.0

**Comment by captainsafia** [comment]
Thanks for opening this issue @wctaylor!

This was a regression in 0.21.0 and will be fixed in the 0.22.0 release which will come out today.

**Comment by captainsafia** [comment]
The new release is out so I'll go ahead and close this issue.
