### ISSUE TITLE
PPA please or Debian + Ubuntu repo

### ISSUE THREAD

**Issue by socialcyberdog** [nteract/archived-desktop-app#4943]
I can not find an Ubuntu ppa or debian repo - it would be very welcomed to not have to manually update / download things. I am used to "apt update && apt upgrade" for too long, manual _nteraction_ for software updates feels so backwards - using Linux for a reason!

**Comment by ramantehlan** [comment]
Thank for opening this issue @socialcyberdog! 

**nteract** recently published its first [**Snap**](https://snapcraft.io/nteract) to [Snapcraft](https://snapcraft.io), which should work with all the major Linux distros including Debian based distros. If you are new to Snaps, you can learn more about it from [here](https://snapcraft.io/docs/getting-started), and download it for your distro from [here](https://snapcraft.io/docs/installing-snapd). 

For Debian based distro:
```
sudo apt update
sudo apt install snapd
```

Once you have installed it, you can install `nteract` by:
```
sudo snap install nteract --edge
```

> Our **next release is on 30th March 2020** and since **Snaps are updated automatically**, you don't need to worry about updating it once downloaded.

**Comment by willingc** [comment]
Thanks for the question @socialcyberdog and response on using snap @ramantehlan.
