### ISSUE TITLE
None of Python examples work

### ISSUE THREAD

**Issue by socialcyberdog** [nteract/archived-desktop-app#4944]
After donwloading and executing the AppImage I want to play with the python example notebooks, but none of them seems to work. The status bar only shows "Python 3 | not connected" forever, no error message, no hint, nothing that would help me to solve that situation. 

JupyterLab generally runs fine on this machine.

**Comment by willingc** [comment]
Hi @socialcyberdog,

Thanks for reporting your question. Please try selecting the following menu item, "Python Interactive" to connect to the Python kernel:

<img width="429" alt="Screen Shot 2020-03-08 at 8 42 21 AM" src="https://user-images.githubusercontent.com/2680980/76166183-d55dea80-6119-11ea-9e91-cca9f51dab0f.png">

If that does not solve your issue, please try [reinstalling the kernel](https://nteract.io/kernels). Thanks.
