### ISSUE TITLE
Python example notebooks unreadable in dark mode

### ISSUE THREAD

**Issue by socialcyberdog** [nteract/archived-desktop-app#4945]
All the Python examples have not readable text in "dark theme" mode. I do not understand why there is a "dark theme" if notebooks do not support it. I do not know what to do to change that, no help, no hint, no information is provided that could help a user solve the situation, leaving the user with examples that are not readable.

**Comment by dsetzer** [comment]
This has been happening to me too lately, the text is there but the font color is dark. I'm not sure when this started happening but I know that it was working fine a few months ago and correctly showed light font on dark mode.. I haven't updated or changed my installation at any point between then and now so I'm not sure why this happened. Just thought I'd contribute this info, I might try reinstalling and see what happens.

**Comment by captainsafia** [comment]
Hello folks! Yes, this was indeed a regression in the 0.21.0 release. It will be fixed in the 0.22.0 release which is going out today.

**Comment by vsivsi** [comment]
Just installed nteract version 0.21.0 for the first time on MacOS 10.15.3 and I'm seeing the same issue.

**Comment by captainsafia** [comment]
I will go ahead and close this as the release is out.
