### ISSUE TITLE
Error "n is not a function" when trying to restart kernel

### ISSUE THREAD

**Issue by AndyTheFactory** [nteract/archived-desktop-app#4952]
**Application or Package Used**
nteract desktop Windows

**Describe the bug**
When trying to restart the kernel (Python 3) I get a notification Error n is not a function. And the kernel does not seem to restart

**To Reproduce**
1. Start a Python notebook
2. execute some commands
3. Menu Runtime, choose Restart

**Expected behavior**
Restarting the Kernel

**Screenshots**
https://i.vgy.me/ZdEJma.png

**Desktop (please complete the following information):**

- OS: Windows
- Browser -
- Version 0.22.0

**Additional context**
If you kill the kernel there seems to be no way to restart it (without restarting nteract or reopening the file)

**Comment by slink** [comment]
I run across the same issue with MacOS (does not appear to be Windows specific)

OS: MacOS 10.15.3
Version 0.22.0

**Comment by thomascamminady** [comment]
Same on Linux (Manjaro, Kernel 5.4, Python 3.8, nteract 0.22).

**Comment by captainsafia** [comment]
Thanks for opening this issue, @AndyTheFactory!

It looks like this was a regression in the February release. The exception seems to be a result of an undefined exception happening somewhere in the restart logic.

I'm going to go ahead and add this to the March milestone for this month's release.

**Comment by willingc** [comment]
@captainsafia Confirming that I saw the same issue on mac 10.14.6 nteract 0.22 when reproducing #4951
