### ISSUE TITLE
Ansi-to-react doesn't compile to ES5

### ISSUE THREAD

**Issue by ibrahima** [nteract/archived-desktop-app#4955]
**Application or Package Used**
`ansi-to-react`

**Describe the bug**

I've added `ansi-to-react` to my package.json and have been using it since around v3. After upgrading to v5 and v6, it seems that it's breaking the UglifyJS step in my build process. It looks like the distributed version of ansi-to-react is not being compiled down to ES5 so UglifyJS is unhappy.

```
ERROR in vendor-ee0bec9920209c414558.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./node_modules/ansi-to-react/lib/index.js:26,0][vendor-ee0bec9920209c414558.js:20987,39]
```

The relevant line is

```javascript
function ansiToJSON(input, use_classes = false) {
```

Default function arguments are an ES6 (or newer? not sure) feature and are not compatible with ES5. IDK if there's a way configure UglifyJS or upgrade it to get it to deal with ES6 but I think in general we are not running stuff in node_modules through babel or anything like that, and that generally works fine.

**To Reproduce**

1. Add ansi-to-react to package.json (e.g. `yarn add ansi-to-react@^6.0.0`)
2. Also be using UglifyJS (I am not totally sure how we're using it but we are using Rails 5.2/Webpacker v3)
3. Try to compile an uglified version
4. Get an error message

**Expected behavior**

It should compile

**Additional context**

Stack:

- Rails 5.2
- Webpacker 3.2.0
- Webpack v3.12.0
- uglifyjs-webpack-plugin@^0.4.6:
- uglify-js@^2.8.29

Hope that's enough detail! It seems like perhaps the TS compiler needs to be configured to output ES5 or something along those lines?

**Comment by ibrahima** [comment]
In the meantime I've worked around this by adding a rule to my webpack config to process the ansi-to-react package via babel, following an approach recommended in https://github.com/webpack/webpack/issues/2031#issuecomment-448119195

**Comment by willingc** [comment]
Hi @ibrahima. Thanks for the detailed report. Just to clarify this issue: 
- are you seeing this when working on nteract for development?
- or is this unrelated to nteract?

**Comment by ibrahima** [comment]
Hi! This is unrelated to nteract, I'm just trying to use the ansi-to-react npm package in a different application. Thanks!

**Comment by willingc** [comment]
Thanks for letting us know @ibrahima
