### ISSUE TITLE
nteract desktop 0.22 mac after update could not connect python

### ISSUE THREAD

**Issue by chaoyue729** [nteract/archived-desktop-app#4967]
**Application or Package Used**
State which application or package this affects. For example: nteract desktop, nteract web, nteract on jupyter, etc.
nteract desktop 
**Describe the bug**
could not connect python

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS] macOS 
- Version [e.g. 22] 0.22

**Additional context**

**Comment by firasm** [comment]
I had this happen to and I had to follow the appropriate steps [here](https://nteract.io/kernels/python) to reconnect my kernel to nteract. 

This seems similar to #3653 as well

**Comment by chaoyue729** [comment]
> #3653

I have followed the step to use Python3 globally, but I run Nteract which open python file at  ~/Document/untitled.ipynb and not like the 0.15 version open file at ~/ 
And I could not find which parameter could change it

**Comment by captainsafia** [comment]
Thanks for opening this issue, @chaoyue729!

Are you able to connect to a Python kernel even though the notebook is in a different location?

**Comment by chaoyue729** [comment]
> Thanks for opening this issue, @chaoyue729!
> 
> Are you able to connect to a Python kernel even though the notebook is in a different location?
yes ,notebook can connect python kernel in different location

**Comment by willingc** [comment]
Hi @chaoyue729.

Thanks for opening the issue. If you select the following "Python Interactive" from the menu, does the kernel connect?

<img width="429" alt="Screen Shot 2020-03-08 at 8 42 21 AM" src="https://user-images.githubusercontent.com/2680980/76166108-376a2000-6119-11ea-98a5-27632f1802ec.png">

If not, I would recommend [reinstalling the python kernel](https://nteract.io/kernels)

**Comment by willingc** [comment]
I'm going to go ahead and close this issue, but @chaoyue729, please feel free to continue to ask support questions related to this.

**Comment by chaoyue729** [comment]
> Hi @chaoyue729.
> 
> Thanks for opening the issue. If you select the following "Python Interactive" from the menu, does the kernel connect?
> 
> <img alt="Screen Shot 2020-03-08 at 8 42 21 AM" width="429" src="https://user-images.githubusercontent.com/2680980/76166108-376a2000-6119-11ea-98a5-27632f1802ec.png">
> 
> If not, I would recommend [reinstalling the python kernel](https://nteract.io/kernels)

thank you , my kernel has connected after your step
