### ISSUE TITLE
New document remains as Untitled after a "Save As" 

### ISSUE THREAD

**Issue by AndyTheFactory** [nteract/archived-desktop-app#4968]
**Application or Package Used**
nteract desktop

**Describe the bug**
When starting nteract or when creating new file, after "saving as" with a proper name and in a specific folder, the file in nteract remains the "Untitled" file. Subsequent saves do not save in the "saved as file"

**To Reproduce**

1. Create new File (I used Python)
2. Save as... (enter a valid filename)
3. The file in the window title remains unchanged (Untitled.ipynb)

**Expected behavior**
To edit the file under the new file name. Subsequent saves should store the content under the "Saved as" filename

**Desktop (please complete the following information):**

- OS: Windows
- Browser -
- Version 0.22.0

**Comment by captainsafia** [comment]
Thanks for opening this issue, @AndyTheFactory!

It appears that the `filepath` attribute in the core state model is not updated to the new file path after a save as. We recently refactored our content-provider setup so I suspect that the wiring of the filepath is not hooked up all the way.

Tagging this for the March 2020 release.

**Comment by yuchiuchao** [comment]
This is especially annoying because all the new changes to a file intended for the new target file of "Save As" got AUTO - saved into the old file, thus the old file is contaminated by these changes, which is not the intention.

**Comment by yuchiuchao** [comment]
It seems that not only "Untitled", but any active notebook does the same thing.  It is the purpose of a notebook for one to experiment and explore, and when one reaches a point with enough accumulated new and different results, one saves it into a new notebook using Save As under a **different** name, and the active notebook becomes the newly named one.  But what happens here is that the old notebook remains active, and after a couple of minutes all the new changes got **Auto saved** into the old notebook, thus overriding all existing proven results.  This logic led to confusion and lost work very quickly.

**Comment by captainsafia** [comment]
@yuchiuchao Thanks for posting this information! We've identified the source of the issue and will ship a fix in the March release.
