### ISSUE TITLE
autocomplete brakets?

### ISSUE THREAD

**Issue by microwolf** [nteract/archived-desktop-app#4974]
**Is your feature request related to a problem? Please describe.**
Maybe I'm not setting this up right? I found it very inconvenient to not have the autocomplete of (), [], {}, etc. while using nteract.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @microwolf!

The CodeMirror editor in nteract is currently not configured with the `closeBrackets` option enabled. If you are interested in adding support for this, I'd be happy to guide you through the process for contributing the change.

Tangent: Between this and other CodeMirror-config related requests that we get, we should consider adding a `codemirrorConfig` property to nteract's configuration so that users can set the codemirror configuration themselves.

**Comment by captainsafia** [comment]
@CindyPotvin is taking a look at this!

**Comment by CindyPotvin** [comment]
I'm working first on moving the existing `cursorBlinkRate` to a `codemirrorConfig` section so I have a place to put the new configurations. 
@captainsafia, do I need to be retrocompatibility with the old `cursorBlinkRate` config? I don't think it's that big of a deal to lose that configuration for users, and it would make that part of the code more complex for a single case.

**Comment by captainsafia** [comment]
> @captainsafia, do I need to be retrocompatibility with the old cursorBlinkRate config? I don't think it's that big of a deal to lose that configuration for users, and it would make that part of the code more complex for a single case.

Nope. Since we have a UI for configuring the cursorBlinkRate, we don't have to retrocompat here.

**Comment by captainsafia** [comment]
@CindyPotvin How is this going?

**Comment by CindyPotvin** [comment]
@captainsafia I have the new configurations on my branch, including the one to auto close brackets. A few of them are only applied when starting a new code block (or maybe restarting the editor, didn't check yet) so I'm taking a look at this before sending the pull request.

**Comment by captainsafia** [comment]
> A few of them are only applied when starting a new code block (or maybe restarting the editor, didn't check yet) so I'm taking a look at this before sending the pull request.

Sounds good! Feel free to ping on Slack if you need help with this.

**Comment by captainsafia** [comment]
This, and support for other CodeMirror options, will ship in tomorrow's April release!
