### ISSUE TITLE
Document how to install on Debian/Ubuntu using a snap

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#4979]
See response in #4943.

**Comment by willingc** [comment]
An example of the link is found in the [Desktop README](https://github.com/nteract/nteract/blob/master/applications/desktop/README.md#installation---users). 
It probably makes sense to add to:
- [ ] the Linux installation page in docs
- [ ] this repo's README

**Comment by ramantehlan** [comment]
This can be closed after #4982

**Comment by captainsafia** [comment]
Thanks for resolving this issue, @ramantehlan!
