### ISSUE TITLE
RFC: Saying goodbye to the monorepo

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4981]
Fair warning: I'm penning this issue in mild frustration after working through an nteract pre-release (#4980) and confronting the not-so-good aspects of our monorepo.

To put it simply: our monorepo is too gosh darn big (for our maintenance capacity and scenario).

The monorepo in this repo currently contains quite a few packages. Some UI focused, some core SDK focused, some transforms, and some odds-and-ends that seem to be there largely as a matter of convience.

While the monorepo makes the development process on the desktop and web apps easy, it's a huge burden when it comes to releases, users finding and exploring code, and new contributors being able to make contributions to the project.

I'm proposing that we break up the monorepo we have in this GH repo. I've mentioned it before, but I'd like to outline the seperation that I think should happen.

* Transforms and outputs should be moved to their own monorepo under nteract/outputs
* Component packages should be moved to their own monorepo under nteract/components
* CodeMirror and Monaco editors should be moved to their own monorepo under nteract/editors
* commutable should be its own package
* The packages under @nteract/core can remain under this repo in addition to the myths
* Generally useful packages like styled-blueprintjsx and ansi-to-react should be their own repos
* fs-observable should be its own package

Overall, I hope that this split will make it easier to release, contribute to, and understand our package ecosystem.

One thing we do lose with this splitting is the ability to do integration tests within the desktop app more seamlessly. For this, I think we should lean more heavily on unit tests for validations.

Also, there is a cost to pay up-front with setting up the ops for each new repo.

Any other pros/cons I am missing? Overall thoughts?

cc: @rgbkrk @ramantehlan @CrystallineCat @willingc

EDIT: Here is a checklist of least-frequently modified/well-isolated packages that I am working on moving out of the monorepo.

- [x] styled-blueprintjsx
- [x] octicons
- [x] logos
- [x] ansi-to-react
- [x] directory-listing
- [x] dropdown-menu
- [x] fs-observable
- [x] ironicons
- [x] mathjax

**Comment by rgbkrk** [comment]
The biggest pain point is likely commutable and `@nteract/core`, since they rely on the same data structures.

I agree with splitting out some of the super clear-cut packages like `ansi-to-react` and `styled-blueprintjsx`. Same thing with `@nteract/outputs` and the transforms.

**Comment by ramantehlan** [comment]
It will need some initial efforts, but I think in the long run that will be a good choice. I am not that familiar with the interdependencies between nteract packages but I do have some other suggestions: 


#### For multirepo management
Maybe, we can use [gitslave](http://gitslave.sourceforge.net/) to split standalone packages, while still use them in a meta repo. 

#### For Release
It wasn't clear from the RELEASE.md that if the process of releasing is automatic or not, but If it is not, I suggest using any of below-given method:
1. [Automatic Releases](https://github.com/marketplace/actions/automatic-releases) or similar Github Action.
2. Bash script to automate the process

**Comment by willingc** [comment]
Hey @captainsafia, I'm looking at #4980 and wondering if all those bumped versions were done by hand. Please tell me they weren't :wink:

This is one of those darned if you do and darned if you don't decisions. I'm inclined to say do it in Phases:
1. easily decoupled stuff that you and Kyle identified to move to their own repo
2. Do another monthly release (less painful then stop; if not)
3. Repeat with best prospects to decouple
4. Move, release, repeat

**Comment by captainsafia** [comment]
Hello folks! Thanks for sharing the feedback. Agreed that there are pros and cons to this decision.

> Hey @captainsafia, I'm looking at #4980 and wondering if all those bumped versions were done by hand. Please tell me they weren't

They were done by hand-ish. The lerna publish step has an interactive command line prompt that asks you to select the version for each package. You can imagine that answering 20 or so odd prompts can get rather tiresome and error-prone.

Currently, my plan is to follow the process that Carol outlined above. Today, I'll be working on moving packages like styled-blueprintjsx and octicons out of the monorepo. That should considerably reduce the clutter. After that, we can continue to factor out things incrementally.

**Comment by jdetle** [comment]
Is there a solid way to link packages with the develop-branch apps outside the monorepo?

**Comment by willingc** [comment]
> They were done by hand-ish.

Yikes! That's a lot of work.

**Comment by jasongrout** [comment]
> The lerna publish step has an interactive command line prompt that asks you to select the version for each package. You can imagine that answering 20 or so odd prompts can get rather tiresome and error-prone.

Thanks for doing that tedious work!

I *really* wish lerna had a more sophisticated ux for dealing with choosing version numbers. Something like a CLI that presented you with the list of packages, and you select multiple packages, then be able to act on the selected packages with their options (bump specific amount, custom prerelease, custom version), and then you could verify and change things iteratively before committing.

**Comment by captainsafia** [comment]
> Is there a solid way to link packages with the develop-branch apps outside the monorepo?

There's quite a few different solutions. @ramantehlan has done some exploring on this. My current thinking is we will move all of the least likely to be changed frequently packages out of the monorepo to kick this can down the road.

That should make the monorepo a lot more manageable and we might not even need to invest in a solution for multi-repo development if the most frequently modified packages are still in the monorepo.

**Comment by captainsafia** [comment]
Alright! I've opened PRs that migrate quite a few packages out of the monorepo. I'm stopping for today but will pick up tomorrow with the rest of the packages in the  checklist above.

Hopefully, before Monday's weekly prerelease we'll have enough of the extraneous packages moved out that we can evaluate how this improves the overall developer process.

**Comment by willingc** [comment]
@captainsafia When you have moved all the stuff out of the monorepo, thoughts on updating the README? Might make sense to include a table of stuff located elsewhere.

**Comment by captainsafia** [comment]
> @captainsafia When you have moved all the stuff out of the monorepo, thoughts on updating the README? Might make sense to include a table of stuff located elsewhere.

I've updated the README under packages/README.md.

**Comment by captainsafia** [comment]
Just finished this month's weekly prerelease.

We've definitely got to clean up more packages. After the items removed above, the release process involves releasing 32 packages. We were probably closer to releasing 40-ish packages before this.

I'll continue to tackle the list of packages outlined above. After that, I think that moving the outputs and transformers out of the monorepo will make a big dent.

As I'm typing this, I'm thinking it's better to outline what packages will be in the monorepo by the time this work is done instead of the other way around. Here is a list of packages that should be in the monorepo.

- actions
- commutable
- connected-components
- core
- epics
- fixtures
- mythic-notifications
- myths
- notebook-app-component
- reducers
- selectors
- stateful-components
- styles

**Comment by rgbkrk** [comment]
Thank you for all the maintenance work! I keep trying to catch up on understanding where things are at and where I should be lending my hand, it's so great that you all have outlined so much of it in issues. Thank you! 🙇

**Comment by willingc** [comment]
@captainsafia Do you want to bump this to August milestone or is this ready to close?

**Comment by captainsafia** [comment]
Let's move it to August. There are still a few more packages that need to be moved out.

**Comment by willingc** [comment]
@captainsafia Are you good with closing this now?

**Comment by captainsafia** [comment]
I think there's still packages that we need to move out but we can close this since most of the items in the original list have been done.
