### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by ZECTBynmo** [nteract/archived-desktop-app#500]
Hey! I would really love to have a CoffeeScript mode for the notebooks. Is that possible? Thanks!

**Comment by captainsafia** [comment]
Hello, @ZECTBynmo! Welcome to nteract and thanks for opening this issue.

I'm going to assume that when you say CoffeeScript mode, you mean you'd like to run CoffeeScript code in the executable code cells. If that is the case, you will need to install the [CoffeeScript kernel](https://github.com/n-riesco/jp-coffeescript) on your machine. Afterwards, you'll see CoffeeScript under the "Language" menu in the nteract application. Give that a go and let me know if you need help with anything.

**Comment by ZECTBynmo** [comment]
Ah! Awesome, thanks @captainsafia will give that a try

**Comment by captainsafia** [comment]
Hello, @ZECTBynmo! Checking to see if you got this working so I can close this issue if possible.
