### ISSUE TITLE
Crash on startup - cannot run

### ISSUE THREAD

**Issue by TotallyInformation** [nteract/archived-desktop-app#5040]
**Application or Package Used**
nteract desktop 0.22.4 for Windows running on Windows 10 latest on a Surface Book 2, 16GB RAM, i7. Tried both the installer and the zip download.

**Describe the bug**
On startup, the follow error occurs:
![image](https://user-images.githubusercontent.com/1591850/78606562-6e853b80-7855-11ea-8a9f-116ed09b2d18.png)

After that, the banner is displayed and remains on-screen unless the window is manually closed or the exe is cancelled via Task Manager.

**To Reproduce**

1. Download & install via exe or unpack zip
2. Run
3. Error is shown

**Expected behavior**
Should start up

**Screenshots**
See above.

**Desktop (please complete the following information):**

- OS: Windows 10 (latest)
- N/A (using desktop version)
- Version: 0.22.4-win

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @TotallyInformation.

This should've been resolved in the latest release as I made a fix in jupyter-paths to add exception handling in https://github.com/nteract/jupyter-paths/pull/31.

There's another fix that we can make within the launch logic in the desktop app to address this. I'll take a stab at this for the March release.

**Comment by TotallyInformation** [comment]
Thanks. Don't suppose there is a manual workaround to get this to work in the meantime?

**Comment by captainsafia** [comment]
Unfortunately not. The issue happens on Windows. When I dug into it, it turns out that some low-level filesystem APIs changed in a Windows that caused a change in the logic for the stat calls that the Node API wraps and nteract in turn calls.

Relatedly: how did you install Python and your kernels?

**Comment by TotallyInformation** [comment]
OK, worth a try anyway.

Python has been slightly problematic on this PC actually. I've been forced to update to Python 3 from 2.7 and that was rather painful. I don't really use Python usually. I'm more of a JavaScript/NodeJS person.

Perhaps I should try on a different device. I just needed to do some COVID related data analysis and manipulation in a hurry, some of the Python or Julia libraries would have helped.

In the end, I've just finished a gruelling few days bashing away with Excel instead. Not pretty but it got the job done in the end.

I'll look forward to your next release and probably try again then as it would be useful to have on my main PC.

Thanks for your responses.

**Comment by captainsafia** [comment]
@TotallyInformation Since you have a local repro would you be interested in verifying a fix that I just pushed to master? I'm unable to repro so I'm flying blind with it.

To run the development version of the nteract desktop app, you will need to clone this repository then run `yarn` to install dependencies and `yarn start` to launch the app in development mode.

**Comment by TotallyInformation** [comment]
Hi, apologies for not responding. I've been tied up with COVID-19 work. I will see if I can get some time this weekend to try it out and report back.

**Comment by TotallyInformation** [comment]
Good news. The current master version does seem to work OK.

**Comment by captainsafia** [comment]
Great to hear! The fix ended up being lots of tweaks to jupyter-paths, the underyling package used to retrieve Jupyter-related directories on the user's machine.
