### ISSUE TITLE
Cell type not updated in UI when converting between Markdown and code

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#5053]
**Application or Package Used**

nteract desktop v 0.22.4 

**Describe the bug**

The cell type is not updated as expected in the user interface when converting a cell between from markdown and code cell or vice-versa.

**To Reproduce**

1. open any notebook
1. create a markdown cell
1. write some markdown in it, eg. "# header1"
1. use the cell menu to convert the cell into a code cell
1. the cell still looks like a markdown cell (e.g incorrect syntax highlighting), as if it wasn't converted.
1. you need to activate another cell before the UI is updated. Or execute the cell with shift-enter, which updates it, because it automatically activates the next cell at the same time. 

**Expected behavior**

When you click the menu option to convert the cell, the UI should update right away to reflect that change.

E.g this is currently a _Markdown_ cell, even though it looks like a code cell. Note that the "convert to Code Cell" option is in the menu, because internal state is still a markdown cell, even though the UI is not.
![image](https://user-images.githubusercontent.com/3074453/79542700-bf3a3700-8094-11ea-9230-06a83b241f06.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Version: 0.22.4

**Comment by captainsafia** [comment]
It looks like the `shouldComponentUpdate` function in the `Cell` component should be updated to check if the cell type has changed between `nextProps` and `this.props`. ([link](https://github.com/nteract/nteract/blob/master/packages/stateful-components/src/cells/cell.tsx#L21))

Would you be interested in submitting a PR with this fix?

**Comment by jarmokivekas** [comment]
Thank for the pointer! I'll take a look at this today.
