### ISSUE TITLE
Markdown cells do not render local images (regression)

### ISSUE THREAD

**Issue by kubark42** [nteract/archived-desktop-app#5056]
**Application or Package Used**
nteract desktop, Version 0.22.4 (0.22.4), running on macOS

**Describe the bug**
Locally sourced images do not render, but images pulled from online sources do.

This is seemingly a regression from
https://github.com/nteract/nteract/issues/1242
https://github.com/nteract/nteract/issues/2127

**To Reproduce**

```
### Images
<img src="yaktocat.png"/>
```

**Expected behavior**
The image should show up equally well when sourced from online or local documents.

**Additional context**
Workaround by using URL for local access, i.e. `file:///Users/.../yaktocat.png`

**Comment by captainsafia** [comment]
Thanks for reporting this.

It looks like the regression occurred when the base href rule that was included in the desktop app was removed during a refactor.

This should be straightforward to fix for the April release.
