### ISSUE TITLE
Keyboard shortcuts not available in nteract desktop

### ISSUE THREAD

**Issue by Riezebos** [nteract/archived-desktop-app#5087]
**Application or Package Used**
nteract desktop

**Describe the bug**
When I click the Help menu, and the Keyboard Shortcuts, I am directed to the following webpage: https://docs.nteract.io/#/desktop/shortcut-keys
This web page does not display any shortcuts and I can't find them anywhere else in the docs.

**Expected behavior**
I expected to see an overview of keyboard shortcuts, specifically I would really like to know how to go to the cell above the one my cursor is currently in.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.23.1

**Additional context**
I like using jupyter as a sort of calculator but starting up jupyter and creating a new notebook just for this is too much work. I wanted to try replacing jupyter notebook with nteract for this use case. I am hoping there are keyboard shortcuts for quickly navigating between cells without a mouse.

**Comment by captainsafia** [comment]
Thanks for surfacing this, @Riezebos!

I opened https://github.com/nteract/nteract/pull/5097 to fix this.
