### ISSUE TITLE
New pypi release of nteract_on_jupyter

### ISSUE THREAD

**Issue by groodt** [nteract/archived-desktop-app#5088]
**Application or Package Used**
nteract_on_jupyter

**Describe the bug**
The published version of nteract_on_jupyter on PyPI is old and does not work with `bookstore` due to https://github.com/nteract/nteract/pull/4738

There should be a new release of nteract_on_jupyter that is compatible with newer versions of `bookstore`.

**To Reproduce**
1. pip install nteract_on_jupyter bookstore
2. jupyter serverextension enable nteract_on_jupyter
3. jupyter nteract

Try `publish` a notebook, there will be a 404.

**Expected behavior**
Bookstore publish should work and there should be no 404.

**Comment by captainsafia** [comment]
The nteract Jupyter extension hasn't been published to PyPi in a while for two reasons:

- The web artifacts for the Jupyter extension aren't optimized at the moment so it is too large to upload to PyPi.
- The nteract Jupyter extension is on a deprecation plan. We're currently focusing development on the nteract web app which should be easier to configure and deploy and more scalable. It'll include all the features that exist in the current Jupyter extension and more.

For now, I'd recommend getting setup with nteract_on_jupyter using the steps you used in your other issue.

Once the beta of nteract web is out (follow the repo or @nteractio on Twitter), you'll be able to use the publish feature there.

**Comment by groodt** [comment]
> For now, I'd recommend getting setup with nteract_on_jupyter using the steps you used in your other issue.

Ok, will do! I might submit a documentation PR to clarify this for users.

> Once the beta of nteract web is out (follow the repo or @nteractio on Twitter), you'll be able to use the publish feature there.

I'm looking forward to nteract_web. I'm just a little worried that it only supports Binderhub. I like the functionality of running a Jupyter with a managed container environment. I'm not really looking for a Binder experience that dynamically builds containers. Binder and Jupyter serve slightly different use-cases.

Never the less, thanks for your responses!

**Comment by captainsafia** [comment]
> I'm just a little worried that it only supports Binderhub. I like the functionality of running a Jupyter with a managed container environment

The plan is to allow you to connect to any endpoint with a Jupyter server. Binder already has the infrastructure set up to provide Jupyter server instances so that's why we build on it.

You'll also be able to provide a Jupyter endpoint and token and have things work. The heavy lifting in both scenarios is done by the `rx-jupyter` nteract package, which support connecting to local and remote Jupyter servers.

**Comment by groodt** [comment]
> You'll also be able to provide a Jupyter endpoint and token and have things work. The heavy lifting in both scenarios is done by the `rx-jupyter` nteract package, which support connecting to local and remote Jupyter servers

Ok, that's a relief. If I'm able to connect via localhost to an existing jupyter environment, or build a custom JupyterLab image that bundles `nteract_web` or runs it as a side-car it solves my use-case.
