### ISSUE TITLE
Keyboard shortcut docs are missing

### ISSUE THREAD

**Issue by szhorvat** [nteract/archived-desktop-app#5091]
**Application or Package Used**

nteract desktop

**To Reproduce**

 - Go to Help -> Keyboard shortcuts

**Expected behavior**

 - Available keyboard shortcuts are shown

**Actual behaviour** 

 - Opens https://docs.nteract.io/#/desktop/shortcut-keys which has no information about shortcuts

**Desktop (please complete the following information):**

- OS: macOS
- Version 0.23.1

**Comment by captainsafia** [comment]
Closing this as a dupe of https://github.com/nteract/nteract/issues/5087 which I put a fix for in https://github.com/nteract/nteract/pull/5097.

**Comment by CrystallineCat** [comment]
I think @captainsafia meant to close this with above comment...
