### ISSUE TITLE
Executing cell in new notebook removes syntax highlighting 

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#5093]
**Application or Package Used**

- nteract desktop, v 0.23.1
- Ubuntu 19.10

**Describe the bug**

Executing cell in python notebook removes syntax highlighting from the notebook.

**To Reproduce**

1. Open a new notebook:  _File_ > _New_ > _Python 3_
2. Write a some code in a code cell e.g. `import math` (completely arbitrary)
3. Execute the cell, _Ctrl-Enter_
4. The cell no longer has any syntax hilighting.

Some observations:

- If you create multiple cells, all cells lose highlighting when one of them is executed.
- I can't reproduce this by opening a file from disk, only in new notebooks.
- Focusing a new cell seems to restore the highlighting in the previously focused cell

**Expected behavior**

All code cell should have syntax highlighting all the time

**Screenshots**

Before executing cell:

![image](https://user-images.githubusercontent.com/3074453/81543722-25a63280-937f-11ea-9850-8ef12b8e4972.png)

After executing cell:

![image](https://user-images.githubusercontent.com/3074453/81543766-35be1200-937f-11ea-8348-c374ca984100.png)

**Comment by captainsafia** [comment]
Interesting bug! I would expect the syntax highlighting to be disabled altogether if there is some funkiness with it.

I suspect that the issue might be related to one of the follow-on actions that is dispatched when the cell is executed.

Would you be interested in investigating and submitting a PR with this fix?

**Comment by jarmokivekas** [comment]
Unfortunately I will not be able to allocate time for this within the next few weeks, I'll have to leave it for someone else.
