### ISSUE TITLE
Error: Electron compilers not found but were requested to be loaded

### ISSUE THREAD

**Issue by odewahn** [nteract/archived-desktop-app#51]
Howdy!  I was trying the install instructions in the readme and hit this error.  I'm on node v5.4.1 and npm 3.3.12.  Wondering if there are other dependencies that need to be installed before I can try this out?  

Here's a bit more detail:

```
$ npm run start

> composition@0.0.1 start /Users/odewahn/Desktop/composition
> electron main.js

App threw an error when running [Error: Electron compilers not found but were requested to be loaded
```

![screen shot 2016-01-20 at 3 34 56 pm](https://cloud.githubusercontent.com/assets/668868/12462310/8d85abfa-bf8b-11e5-8209-2f8b90967d9e.png)
]

**Comment by rgbkrk** [comment]
I'm assuming you ran `npm install` first?

Also... I see PipBoy in your errors, did you clone this one or robcoindustries/pipboy?

**Comment by rgbkrk** [comment]
Oh ha, nevermind. I see it in the package.json...

**Comment by rgbkrk** [comment]
Can you share your `npm install` output?

**Comment by odewahn** [comment]
Pulling the latest changes and doing a fresh `npm install` fixed this up.  Thanks!

**Comment by rgbkrk** [comment]
That did at least cause me to address #52. Thanks!
