### ISSUE TITLE
node 5.x apparently not recent enough? (`bindings` module version error)

### ISSUE THREAD

**Issue by jaredly** [nteract/archived-desktop-app#512]
I've got `5.0.0` and am getting this error:
![image](https://cloud.githubusercontent.com/assets/112170/15983887/674dec68-2fb6-11e6-8a50-0153966b0c36.png)

What's the actual minimum node version?

**Comment by jaredly** [comment]
hmm ok maybe it wants v6. attempting now

**Comment by rgbkrk** [comment]
Yep, we're on node 6 because we're using Electron 1.1.1. The reason it fails is because of our one native module, `zmq`. There is another workaround that we could add in, using `electron-rebuild`.
