### ISSUE TITLE
Additional function information does not load with ctrl + . but on the character press afterwards. It also does not close when pressing the X.

### ISSUE THREAD

**Issue by Ashton-Sidhu** [nteract/archived-desktop-app#5122]
**Application or Package Used**
nteract desktop - v0.23.1, ubuntu

**Describe the bug**
When trying to view the function defintion, ctrl + . does not display the function header. It tends to pop up after pressing another key following ctrl + ., and the key pressed is registered into the cell.

Once the function info appears, it does not have a scroll bar and goes down the page.

Finally, the pop up window for the function definition does not go away when pressing X, but when clicking into another cell.

**To Reproduce**

1. Go to a function.
2. Press ctrl + ., then press ctrl + ., then 'a'.
3. Click on X

**Expected behavior**
Upon clicking ctrl + . inside the function, the function definition should appear. The pop up should be able to close by pressing x.

**Screenshots**
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/9558507/82636099-df976d00-9bcf-11ea-82ee-9b61f7f80109.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu, Pop-os
- Browser N/A
- Version 0.23.1

**Additional context**

**Comment by captainsafia** [comment]
Thanks for the well-written bug report, @Ashton-Sidhu!

It looks like something might be funky with the handler registration in CodeMirror and the styles for the pop-out menu.

@jdetle Interested in taking a look at this?

**Comment by Ashton-Sidhu** [comment]
Hey @captainsafia not sure how high priority this bug is but if it's a lower priority bug, I can try taking a go at it.

**Comment by captainsafia** [comment]
@Ashton-Sidhu A community contribution is always welcome! If you have any questions about the contribution process, feel free to post on the nteract Slack which is linked in the repo's README.

**Comment by Ashton-Sidhu** [comment]
I found a fix + root cause and will submit a PR tomorrow.

**Comment by captainsafia** [comment]
@Ashton-Sidhu Thanks! I'll take a look at your PR today.
