### ISSUE TITLE
0.23.2 "loading...|not connected" indefinitely when open a file.

### ISSUE THREAD

**Issue by ryo1kato** [nteract/archived-desktop-app#5126]
**Application or Package Used**
https://github.com/nteract/nteract/releases/download/v0.23.2/nteract-0.23.2.dmg

**Describe the bug**
nteract shows completely white window with "loading ... | not connected    Not saved yet" on status bar when open a file (either by double click or from Open menu)

**To Reproduce**
1. Open an existing .ipynb file by double-click or from Open menu

**Expected behavior**
Shows a file content.

**Screenshots**
<img width="592" alt="Screen Shot 2020-05-25 at 17 44 22" src="https://user-images.githubusercontent.com/185990/82850767-7e62e880-9eb2-11ea-883f-f936679ce92b.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.4 (19E287)
- Version [e.g. 0.23.2]
- `conda install ipykernel`, `python -m ipykernel install`

**Additional context**
* The same file opens with **0.23.1** as expected, without any issue.
* With 0.23.2 I can create a new note book that works as expected, but once I save and reopen, it is just a blank window.

**Comment by captainsafia** [comment]
Just submitted a patch fix for this. Try now?

**Comment by ryo1kato** [comment]
Confirmed that release 0.23.3 can open files as expected, just like 0.23.1.
(I've verified 0.23.3 via auto-update by double-clicking an ipydb file, as well as an .app file from within the mounted .dmg file, using Open menu to open an ipydb file)

Thank you so much for prompt fix.

**Comment by captainsafia** [comment]
No problem! I'll go ahead and close this out now.
