### ISSUE TITLE
LaTeX no longer displaying

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#513]
Example notebook, first cell is Markdown and second cell uses `IPython.display.Latex`:

<img width="794" alt="screen shot 2016-06-11 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/836375/15987512/bcc5295a-2fe7-11e6-8e84-1d6129e5b753.png">

**Comment by rgbkrk** [comment]
Markdown cells are working again yet cells are not.

/cc @jdfreder @lgeiger

**Comment by lgeiger** [comment]
As far as I can tell, code cells are still using `katex` via `transformime-react`.

**Comment by rgbkrk** [comment]
Ohhhhh, we should switch that over then. Thanks for digging into it.
