### ISSUE TITLE
toggle output visibility not working

### ISSUE THREAD

**Issue by JohannaZ** [nteract/archived-desktop-app#5135]
Hi, 
I just updated the nteract Desktop App to get the new releases and had to determine that  'Toggle Output Visibility' is not working anymore.
If I select it nothing happens, this could be a similar issue like  y-chachan had with 'Toggle Expanded Output'. 'Toggle Input Visibility' however is still working.
Thanks for your help!

Application
nteract desktop

Describe the bug
 'Toggle Output Visibility' does nothing

To Reproduce
Try Toggle Output Visibility

Expected behavior
Cell Output not visible anymore

Desktop:
Windows

**Comment by captainsafia** [comment]
Thanks for reporting this issue. I've submitted a fix in #5142.
