### ISSUE TITLE
Adding custom metadata to cells

### ISSUE THREAD

**Issue by emeeks** [nteract/archived-desktop-app#5154]
I'd like to decorate cell metadata with custom attributes based on interaction. I noticed that among nteract's actions there's a `OverwriteMetadataField` and I was thinking of using that to set a new property value on the cell.

Is that the right approach?

**Comment by captainsafia** [comment]
Good question!

The `OverwriteMetadataField` actually overrides metadata at the notebook level. Typically, you'd use this for updating the title, author, or tags of a notebook.

For modifying cell-level metadata, you'll want to use the [SetInCell](https://packages.nteract.io/interfaces/actions.setincell.html) action which you can use to modify any property within the cell. For example, to change the `collapsed` metadata property.

```js
import { actions } from "@nteract/core";

actions.setInCell({
  id: "MyCellId",
  contentRef: "MyContentref",
  path: ["metadata", "collapsed"],
  value: true 
});
```

The `id` is the ID of the cell that you wish to modify and the `contentRef` is the `ContentRef` for the notebook the cell is in. The `path` is the keypath of the property within the cell that you want to set/update. The `value` is what value you want to set that property to.

**Comment by emeeks** [comment]
Wonderful, thanks so much!

**Comment by captainsafia** [comment]
Cool. Closing this now.
