### ISSUE TITLE
@nteract/mythic-configuration referenced in MarkdownCell doesn't exist

### ISSUE THREAD

**Issue by emeeks** [nteract/archived-desktop-app#5161]
MarkdownCell here references `@nteract/mythic-configuration` but this doesn't appear to exist as published module.

https://github.com/nteract/nteract/blob/master/packages/stateful-components/src/cells/markdown-cell.tsx#L1

**Comment by captainsafia** [comment]
The mythic-configuration package was introduced this week and hasn't been pushed out as part of our weekly release cycle.

It'll be shipped as part of a packages pre-release on June 15th.
