### ISSUE TITLE
Why is MakeMapXFromProps a thing?

### ISSUE THREAD

**Issue by emeeks** [nteract/archived-desktop-app#5173]
I've noticed throughout the codebase the same pattern used over and over again for the redux functionality (`mapStateFromProps` and `mapDispatchFromProps`) where it's in a wrapper called `makeMapDispatchFromProps` (or mutatis mutandis with `State`) and I don't see the value of it. It seems like it tries to isolate component props but that's available anyway.

For example, in index.ts of NotebookMenu:

```
export function makeMapDispatchToProps(
  initialDispatch: Dispatch,
  initialProps: { contentRef: ContentRef }
): any {
  const mapDispatchToProps = (dispatch: Dispatch) => ({
   yadda yadda
})
return mapDispatchToProps
```

It seems to me you could just move initialProps into mapDispatchFromProps and get exactly the same functionality.

**Comment by captainsafia** [comment]
In general, this is recommended behavior in Redux to support memoization. You can read more about this [here](https://redux.js.org/recipes/computing-derived-data#sharing-selectors-across-multiple-components).
