### ISSUE TITLE
`python3 | launching` forever

### ISSUE THREAD

**Issue by dimitry-ishenko** [nteract/archived-desktop-app#5175]
**Application or Package Used**
nteract desktop

**Describe the bug**
Trying to execute a simple `print("Hello world")` cell, the app says  `python3 | launching` forever and nothing happens.

**To Reproduce**

1. Open the app:
![Screenshot from 2020-06-23 16-35-14](https://user-images.githubusercontent.com/2858291/85459788-92ad0a80-b570-11ea-92cf-a348c51c6ba5.png)

2. Enter `print("Hello world")` in the empty cell.
3. Press Ctrl + Enter to execute.
4. Watch the app do absolutely nothing:

![Screenshot from 2020-06-23 16-35-37](https://user-images.githubusercontent.com/2858291/85459952-bd975e80-b570-11ea-8adc-0c7496f38690.png)

5. Become disappointed in the app, close it, uninstall and go back to using jupyter.

**Expected behavior**
A simple `Hello world` output would be nice...

**Screenshots**
See above.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: What does my browser have to do with the app???
- Version: 0.23.3

**Additional context**
`/dev/null`

**Comment by dimitry-ishenko** [comment]
Is this of any help? Not sure why it's trying to launch `/usr/bin/python` (aka `python2`) instead of `python3`.

![Screenshot from 2020-06-23 16-40-38](https://user-images.githubusercontent.com/2858291/85460544-53cb8480-b571-11ea-9326-c07c468ae661.png)

**Comment by captainsafia** [comment]
Some questions to help dig into this:

* Did you launch the nteract desktop app via your OS's app manager or from the CLI?
* Is Python 3 installed using conda or another version management tool?

**Comment by dimitry-ishenko** [comment]
Thanks @captainsafia.

- I've originally launched it using the `.desktop` file, but launching via the terminal makes no difference.
- I am using vanilla (`apt`-managed) Python 3.8.2 that came with Ubuntu.

Please note that I do also have Python 2.7.18rc1 installed (pulled in by a package) and this is what my `python` link points to. In other words:
```shell
dimitry@laptop:~$ ls -l /usr/bin/python*
lrwxrwxrwx 1 root root       7 May  5 17:56 /usr/bin/python -> python2
lrwxrwxrwx 1 root root       9 Mar 13 08:31 /usr/bin/python2 -> python2.7
-rwxr-xr-x 1 root root 3694632 Apr  7 08:05 /usr/bin/python2.7
lrwxrwxrwx 1 root root       9 Apr 24 11:38 /usr/bin/python3 -> python3.8
-rwxr-xr-x 1 root root 5457536 Apr 27 11:53 /usr/bin/python3.8
```

Subsequently, this succeeds on my computer:
```shell
dimitry@laptop:~$ python3 -m ipykernel_launcher
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-1020454.json
```
while this fails:
```shell
dimitry@laptop:~$ python -m ipykernel_launcher
/usr/bin/python: No module named ipykernel_launcher
```
Now, look at my last screenshot.

**Comment by captainsafia** [comment]
Got it -- one more question: what happens if you run the same cell again?

**Comment by dimitry-ishenko** [comment]
> Got it -- one more question: what happens if you run the same cell again?

SSDD

**Comment by dimitry-ishenko** [comment]
> Got it -- one more question: what happens if you run the same cell again?

@captainsafia more nothingness :smirk: Please see my earlier comment. I've added more data and hopefully it gives a clue.

**Comment by dimitry-ishenko** [comment]
@captainsafia is any of my data above helpful? Or do you want to do any other tests?

**Comment by willingc** [comment]
What is the output of `jupyter kernelspec list`?

Also try running `python3 -m pip install -U ipykernel`. Close nteract and restart nteract.

**Comment by dimitry-ishenko** [comment]
@willingc thank you. Here is what I get:

```shell
dimitry@laptop:~$ jupyter kernelspec list
Available kernels:
  python3                                           /home/dimitry/.local/share/jupyter/kernels/python3
  python38264bitc3f362f1ddd640bea0bf1140d3f9b43c    /home/dimitry/.local/share/jupyter/kernels/python38264bitc3f362f1ddd640bea0bf1140d3f9b43c
```

```shell
dimitry@laptop:~$ python3 -m pip install -U ipykernel
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: ipykernel in ./.local/lib/python3.8/site-packages (5.3.0)
...
```

**Comment by dimitry-ishenko** [comment]
FWIW `vscode` and straight up `jupyter` (`notebook` and `lab`) work totally fine on my box.

**Comment by dimitry-ishenko** [comment]
Also:
```shell
dimitry@laptop:~$ cat /home/dimitry/.local/share/jupyter/kernels/python3/kernel.json 
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```
```shell
dimitry@laptop:~$ cat /home/dimitry/.local/share/jupyter/kernels/python38264bitc3f362f1ddd640bea0bf1140d3f9b43c/kernel.json 
{
  "argv": [
    "/usr/bin/python3",
    "-m",
    "ipykernel_launcher",
    "-f",
    "{connection_file}"
  ],
  "display_name": "Python 3.8.2 64-bit",
  "language": "python",
  "env": {},
  "metadata": {
    "interpreter": {
      "architecture": 3,
      "path": "/usr/bin/python3",
      "version": {
        "options": {
          "loose": false,
          "includePrerelease": false
        },
        "loose": false,
        "raw": "3.8.2-final",
        "major": 3,
        "minor": 8,
        "patch": 2,
        "prerelease": [
          "final"
        ],
        "build": [],
        "version": "3.8.2-final"
      },
      "sysPrefix": "/usr",
      "fileHash": "915de0c4067d91ef19c3cee6d2b05e377d296312fa306ae9a043ee8438451be5c0465702f779ac8affb51fa9ad61e3240cc83e8a753832c4f07f0ef196b863a6",
      "type": "Unknown",
      "displayName": "Python 3.8.2 64-bit"
    }
  }
}
```

**Comment by dimitry-ishenko** [comment]
After running `ipython kernel install --user` I now have this:
```shell
dimitry@laptop:~$ cat /home/dimitry/.local/share/jupyter/kernels/python3/kernel.json 
{
 "argv": [
  "/usr/bin/python3",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```
and the problem is resolved. Feel free to close the issue.
