### ISSUE TITLE
Input disappears when choosing Monaco Editor

### ISSUE THREAD

**Issue by festim-deari** [nteract/archived-desktop-app#5195]
**Application or Package Used**
nteract Desktop

**Bug Description**
Input disappears when choosing Monaco Editor. You can't type or even see the input.

**Runtime tested on**
Dotnet

**OS**
Windows 10

**Comment by captainsafia** [comment]
@festim-deari Thanks for reporting this! We don't yet have full support for the Monaco editor but we hope to ship it as part of the July release.

**Comment by festim-deari** [comment]
@captainsafia Thanks for the information. I'd also like to contribute, if help is needed.

**Comment by willingc** [comment]
@festim-deari The August release was just posted as [0.25](https://github.com/nteract/nteract/releases/tag/v0.25.0). Addition of full Monaco editor is part of this release.

Closing as 0.25 addresses this issue.
