### ISSUE TITLE
Cells navigation with arrow keys

### ISSUE THREAD

**Issue by highandmighty** [nteract/archived-desktop-app#5196]
**Is your feature request related to a problem? Please describe.**
In previous versions of nteract Desktop I was able to navigate _between cells_ with arrow keys. It was extremely convenient. In the latest versions this functionality was excluded, now I am able to navigate with arrows only inside one cell. At first I thought this is a bug in my system, but I've checked it on other machines and OS and seems that this a standard behaviour now. 

**Describe the solution you'd like**
I hope that this functionality will be returned, it may be optional. Previous behaviour still exists in nteract jupyter plugin.

**Describe alternatives you've considered**
At least I would like to have keyboard shortcuts for navigation between cells without running them. I was not able to find them.

**Additional context**
I'm using nteract Desktop v0.24.0 on MacOS 10.15.3.

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @highandmighty!

It looks like this is a regression from our previous behavior. We should fix this for the July release.
