### ISSUE TITLE
Kernel Installation documentation could use improvment

### ISSUE THREAD

**Issue by step21** [nteract/archived-desktop-app#5201]
To me, the Kernel / environment documentation still unclear. I know it was discussed here https://github.com/nteract/nteract/issues/1513 but imo what is there does not always help.
Even as a seasoned python user, I am not sure in which environment nteract runs. Does it bundle its kernels? Does it use locally installed runtimes/kernels? which ones? Then I would know what to do with the info on that page.

**Describe the solution you'd like**
Ideally I think here: https://nteract.io/kernels it should be mentioned which environment nteract runs in, and what it uses. And then I know where to execute these commands. Does that make sense?

**Describe alternatives you've considered**
If kernels are not bundled, bundle them. Like have a built in conda environment, seperate from the system.

**Comment by willingc** [comment]
Hi @step21, Thanks for sharing this. I think it's been 1.5 years since the documentation was written and a refresh does make sense.

The [source for the website information for kernels](https://github.com/nteract/nteract.io/tree/master/components/kernels) would be a good starting point for changes to instructions.

We would welcome any help from the community to update these files.

**Comment by step21** [comment]
Hey, I would be happy to provide a PR. However before that, I would have to be sure how it actually works. So does nteract just use whatever it finds on the system? (that's what I am currently assuming) Does it look for kernels or pythong etc in $PATH or somewhere else?

**Comment by willingc** [comment]
Great! Yes, nteract uses the kernels that are installed for Jupyter.

**Comment by step21** [comment]
Thanks. One more question - the examples mention either a conda or venv environment - how does nteract know which environment to use or does it use whatever is activated in a certain shell/terminal emulator?

**Comment by MSeal** [comment]
Whatever is active on the terminal / process.

**Comment by step21** [comment]
Made a proposal to nteract.io. I also looked at the code - I saw that it runs `python -m ipykernel --version` and `conda info --json` to get the basics of the environment, but couldn't quite figure out how it gets installed kernels from there, as these are not included in either.

**Comment by captainsafia** [comment]
@step21 Thanks! I'll take a look at the PR.

> but couldn't quite figure out how it gets installed kernels from there, as these are not included in either.

We have some logic in the desktop app that looks through the environment for installed kernels. Jupyter places a JSON file that describes that installed kernels at a particular directory so we look there to figure out what kernels can be used.

**Comment by step21** [comment]
Thanks. Fixed in https://github.com/nteract/nteract.io/pull/297
