### ISSUE TITLE
Missing dataset for example python notebook "Go from Pandas to GEOJson"

### ISSUE THREAD

**Issue by programatt** [nteract/archived-desktop-app#5206]
**Application or Package Used**
nteract desktop

**Describe the bug**
The OpenAPI dataset referenced in the notebook is no longer available from https://data.cityofberkeley.info/resource/k489-uv4i.json?$limit=20 . This results in errors in further cells expecting to use the data from the api call.

**To Reproduce**

1. Open nteract desktop
2. Click on menu  (File -> Open example notebook -> python -> Go from Pandas to GEOJson)
3. Click on menu  (Cell -> Run All)
4. Observe error on cell 5 (KeyError: 'latitude') 

**Expected behavior**
The cells run without error

**Screenshots**
Api call to https://data.cityofberkeley.info/resource/k489-uv4i.json?$limit=20
![image](https://user-images.githubusercontent.com/547550/87626674-8db42480-c6f2-11ea-940e-6e0f673935e7.png)

nteract cell errors
![image](https://user-images.githubusercontent.com/547550/87626729-bb00d280-c6f2-11ea-9c4e-31bb3dd79cc3.png)

**Desktop (please complete the following information):**

OS: macOS Catalina
nteract desktop: 0.24.0

**Additional context**

**Comment by programatt** [comment]
I would be willing to make a version of the notebook that works. It's pretty obvious this is just an example to show off how a nice notebook looks in the application. It shouldn't be that difficult to modify the example to use a different dataset from the Berkeley datasets that has lat/long values that will show up on the map. I did a brief search of the repository and wasn't able to see where these example notebooks were being stored/referenced from. Is the source code for them hosted somewhere else and linked in the application? It looks like the file menu is being created from applications/desktop/src/common/commands/by-menu/file.tsx but that doesn't appear to create a menu option for `Open Example Notebook`.

**Comment by captainsafia** [comment]
@programatt Thanks for offering to help with this! Our example notebooks are actually in the nteract/examples repo.

https://github.com/nteract/examples/blob/master/python/pandas-to-geojson.ipynb is the affected notebook.

**Comment by programatt** [comment]
@captainsafia no problem! It looks like the 311 dataset just got moved to a different url and some of the columns were renamed. I opened a PR https://github.com/nteract/examples/pull/28 😄

**Comment by willingc** [comment]
Thanks for making the PR @programatt. I'm closing this now that your PR is merged.
