### ISSUE TITLE
RFC: Monaco Editor

### ISSUE THREAD

**Issue by vivek1729** [nteract/archived-desktop-app#5215]
Nteract desktop app and jupyter extension currently ship with CodeMirror as the default editor. 
Thanks to the [extensibility options](https://github.com/nteract/nteract/blob/515c7eeff9ade7813622c4cf040bec80083251d3/packages/stateful-components/docs/extensibility.md) provided by the project, we want to contribute MonacoEditor as an additional editor that would be available to the community.

## Motivation
MonacoEditor powers VSCode. The [project](https://github.com/Microsoft/monaco-editor) has received immense love from the open source community and provides a plethora of [features](https://code.visualstudio.com/docs/editor/editingevolved) some of which include helpful context menus, code navigation.

## Goals
* Flexibility - Nteract users and organizations incorporating nteract components into their projects would have the flexibility to choose an editor meeting their needs.
* Additional features - MonacoEditor provides a set of powerful features, accessibility and extensibility options. The community can adopt these components to take advantage of a richer code navigation experience and language support.

## Design and Implementation
The initial contribution would introduce a MonacoEditor connected component and aim to be at parity with current Code Mirror support. The monaco editor will have Jupyter kernel completion support and also dynamic resizing to adapt to available container space.

The initial contribution would entail the followign tasks to get to the "ship-ready" state for Nteract:
* `Connected-component` - We'll add a `monacoeditor` component to the available [`connected-editors`](https://github.com/nteract/nteract/tree/master/packages/stateful-components/src/inputs/connected-editors). The `monacoeditor` component would derive its configuration options and defaults from the state here and pass it as a construction option to the [`monaco-editor`](https://github.com/nteract/nteract/tree/master/packages/monaco-editor) component. We'd want to support all the default options currently in CodeMirror to be at parity. The current defaults for Codemirror are:
    ```
    codeMirror: {
      matchBrackets: true,
      autoCloseBrackets: false,
      indentUnit: 4,
      tabSize: 4,
      lineNumbers: false,
      smartIndent: true,
      cursorBlinkRate: 530,
      showCursorWhenSelecting: true
    }
    ```

Looking at the default options, one of the properties that is not supported in Monaco Editor is `cursorBlinkRate`. The editor has an option called [`cursorBlinking`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#cursorblinking) and its possible values are 'blink', 'smooth', 'phase', 'expand' and 'solid'. Besides the cursorBlinkRate, the other default options that I highlighted are supported by Monaco Editor's [`IEditorOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html) and [`ITextModelOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodelupdateoptions.html)

* Add resize logic so that the editor accomodates available space based on the container size. While the width of the editor component responds to the change in the container width, Monaco Editor doesn't shrink/expand its height automatically to accommodate text as it is removed/added. We're planning to address this issue by adding a method that would infer the expected height of the editor by getting the number of lines and current line height of the editor model
* Add support for Jupyter completions - A `completionItemProvider` that would fetch completion items suggested by the Jupyter kernel. The `completionItemProvider` would be a singleton that gets registered during the instantiation of the `monaco-editor` component. It's behaviour would be controlled by an `enableCompletion` boolean flag in the editor component.
* Theming - Align monaco editor themes to support the light and dark themes provided by Nteract
* Web Worker - Completions should ideally be handled in a web worker so we don't block the UI thread. This would involve investigation around web worker support in Electron. 
* Build support - Moanco Editor by default tends to fetch language specific syntax highlighting information in separate js chunk files. We'd want to update web pack configuration for `jupyter-extension` to support this chunking. For the `desktop` component, we'd want to explicitly disable chunking in webpack since the entire bundle is shipped together.

## Roadmap
While I have highlighted the features that will get us to the "ship-ready" state, I also wanted to highlight some important considerations for the future as we get more feedback and support from the community:
* Add config for all the monaco-editor options in the state - It seems like the config options for `CodeMirror` are stored in state and managed by the `mythic-configuration` package. We'd want to follow the same pattern and have the `monacoeditor` connected component retrieve the config options from the state. This would also involve exposing the full set of monaco editor configuration options, expanding from the initial default list highlighted above.
* Config update from UI - Exploring a solution to be able to update a common subset of editor configurations that'd be shared by all supported editors in Nteract.
* Unified completion item provider - Having a single completion item provider that would serve as a glue to hook into different supported editors instead of having every editor implement its own completion logic
* Perf improvements
* Localization support

## Testing

To validate the correct behavior of the various components added, we'll add unit tests for 2 specific items to start with:
* Monaco editor component
* Completion provider

**Compatibility**
Since we add the editor following the extensibility guidelines, there would not be any breaking changes to the core editor component causing any backward compatibility issues.

**User Impact**
This contribution does not make MonacoEditor, the default code editor for Nteract. It introduces the editor as an additional option. Users can opt-in to use the editor or continue using CodeMirror which is the default setting in the configuration.

## Open Questions
After the webpack build, the `monaco-editor` npm module spits out a bunch of assets. It seems non trivial to be able to link to these assets from the bundle especially in the context of the desktop app which is shipped as a single JS file. There are 2 specific types we'd want to wire up correctly in nteract:

- Font files: The package relies on a specific font file `codicon.ttf` to display the icons for completion items. The font file is referenced in a `css` file within the `monaco-editor` npm package. How should we link this generated font file in webpack so that it is referenced correctly in the project?
- Workers: The webpack output also contains a few web worker files like `editor.worker.js` and  `ts.worker.js`. I am not entirely clear how to wire up web workers in the nteract app. Additionally, we'd also want to carry out completions in a separate web worker. Is there some prior art in supporting this for nteract?

I see that there is a `static` folder for assets like images. Essentially, we'd want to understand how to package dynamic webpack assets (like fonts, web worker files, images etc.) that are output (both for desktop app and the web context).

**Comment by captainsafia** [comment]
Thanks for opening this RFC, @vivek1729!

> We'd want to support all the default options currently in CodeMirror to be at parity. 

Does the Monaco editor support all the configurations that CodeMirror supports?

> Add resize logic so that the editor accomodates available space based on the container size

How will this be done?

> It's behaviour would be controlled by an enableCompletion boolean flag in the editor component.

Will this flag default to `true`? Do we even need a flag to enable completions at all?

> Unified completion item provider - Having a single completion item provider that would serve as a glue to hook into different supported editors instead of having every editor implement its own completion logic

Yes, please! I opened an issue for this a while ago in #4743 

> The package relies on a specific font file codicon.ttf to display the icons for completion items. The font file is referenced in a css file within the monaco-editor npm package. How should we link this generated font file in webpack so that it is referenced correctly in the project?

Thanks for putting this in writing. We've actually had to do something similar for ipywidgets support. ipywidgets uses the FontAwesome font icon set. I added the Webpack-configuration for this using Webpack's font loader as documented [here](https://webpack.js.org/guides/asset-management/#loading-fonts). However, as I recall, the icons didn't end up working. I believe this was a result of the way that FontAwesome packaged their icons (some compressed data format).

I think for this we'll have to try out Webpack's font loading config and see if it works with the way the codicons.ttf is distributed.

Does Monaco provide guidance on this? Considering VS Code is also an Electron-based application, I assume that they would have some recommendation about how to get this working.

> Workers: The webpack output also contains a few web worker files like editor.worker.js and ts.worker.js. I am not entirely clear how to wire up web workers in the nteract app. Additionally, we'd also want to carry out completions in a separate web worker. Is there some prior art in supporting this for nteract?

This is the first time we'd be doing anything with workers in the desktop app. It looks like Electron does support creating workers in the renderer process ([ref](https://www.electronjs.org/docs/tutorial/multithreading)). We haven't done this before so we'll have to dig up some examples and find out how to do it.

I think there's two aspects to this:

- The guidance we provide to core SDK users about how to configure web works in nteract-based apps
- The work we do to get web workers working (lol, say that five times fast) in nteract's Electron-based harness

Finally, what are your thoughts on the timeline for this? It's probably too late for the July release. Upcoming releases are in August/September (last Monday of each month).

cc: @MSeal @emeeks @willingc @rgbkrk @CrystallineCat

**Comment by vivek1729** [comment]
Thanks for the feedback @captainsafia.

> Does the Monaco editor support all the configurations that CodeMirror supports?

I don't think so. The `cursorBlinkRate` is not supported as expected. I updated the RFC to reflect the same.
I also added details around the resize logic handler that we are planning to add in the Editor component.

> Will this flag default to `true`? Do we even need a flag to enable completions at all?

Yes, the flag will default to `true`. I think it adds some value to make completions a configurable option because some consumers might want to specifically opt out of it for based on their design decisions, perf optimizations etc. Happy to learn what has the feedback been from the nteract community regarding this piece.

About the font loading in webpack, how did you end up loading the icons for the ipywidgets then?
I will have to do some more investigation to understand the font support for monaco editor and webpack. 

Web workers could be an interesting challenge here. While, it seems like Electron should support them out of the box, I will try to understand how are these web workers expected to be packaged. This ties into the second aspect that you highlighted. Out of curiosity, what's the best way to verify that app that gets generated in `dev` environment will have its webpack outputs packaged the same way in `production` environment? To clarify, let's say we get the web workers and the fonts issue sorted out in the `dev` environment when we do `yarn start`. Is that a sufficient check that the webpack asset building/linking would work the correct way in the final `production` release package of the app as well?

I believe we should be able to track this contribution for the August release.

**Comment by MSeal** [comment]
First off, thanks for open the RFC with the thoughtful organization of thoughts around the change. Overall I think moving to Monaco editor provides a lot of benefits down the road as you outlined. A few naive questions on my end:

Will this differ from the Monaco editor integration in the jupyter-extension, or just make that a more generalized option?

Also, this may be out of scope of this conversation, but what's the expected package size difference? There's some desire to make sure we work on reducing web asset bundle sizes down the road and I know Monaco can be quite large out of the box. And will the webpack build include both editor packages by default or only the one that's enabled when building productionized assets?

**Comment by vivek1729** [comment]
Thanks for your feedback @MSeal. 

> Will this differ from the Monaco editor integration in the jupyter-extension, or just make that a more generalized option?

The Monaco Editor component would be the same for both the desktop and jupyter-extension products. The only difference would be the way it is getting bundled into the package. As per my understandind right now, the only difference should therefore only be the webpack configuration. 

As far as the package size difference is concerned, pulling in the `monaco-editor` package in our web project increased the overall bundle size by about 3 MB. Do you think packaging the module in the context of an electron app can cause some further increase? Let me highlight the main difference that I foresee in the web pack configuration as part of this initial contribution. You rightly pointed out that Monaco Editor comes with a lot of bells and whistles out of the box. Specifically, all the language specific  configuration are emitted by the module as different chunk files. I was hoping to disable chunking for the desktop app so that all the language configuration is contained within the editor bundle and enable chunking for the jupyter-extension. This will allow the editor in the web context to fetch language syntax configuration on demand thereby reducing the initial bundle size that gets loaded.

Some other approaches that can be considered for reducing web asset size:
- Dynamic imports : Fetching the monaco-editor package on demand and bundling it as a separate asset. 
- Registering only a subset of languages for Monaco Editor: Pre-defining this in webpack instructs the package to only fetch editor configuration files for those languages.

> Will the webpack build include both editor packages by default or only the one that's enabled when building productionized assets?

Yes. I think both codemirror and monaco would be bundled with the app since the user can switch editors at any time in the app right now. For jupyter-extension in the future, I think having a dynamic import of the monaco editor package only when the user actually selects it would alleviate the need to bundle both the editors together. I am not sure how that approach would work for the desktop app though.

**Comment by MSeal** [comment]
Thanks @vivek1729. 3MB is probably not an issue for the desktop app, but it might start making the web options less ideal. On a lower-end network if you're trying to reach an nteract host that could delay loading by a significant amount.

It might be interesting to include webpack build options that only provide one or the other editor so a deployment could choose one to reduce bundle size? Separate asset bundles in a dynamic configuration for the editors as a composition component could be used to achieve this if that is the route you're thinking we should go.

I understand less about language subset options for Monaco. That could be a possibility but it might lead to new kernels not having qol features out of the box when they are used in nteract.

Overall I don't see this as a blocker, but efforts to mitigate the issue would be appreciated. In the worse case a plan to mitigate in the future would be sufficient for me to avoid blocking progress but making sure we keep bundle sizes under control over time.

**Comment by vivek1729** [comment]
@MSeal, that's a great point. We'd definitely want to be cognizant about the bundle size for the web component. 

I like your idea of having a webpack build option to choose a specific editor at build time through some sort of a dynamic configuration.

> Separate asset bundles in a dynamic configuration for the editors as a composition component could be used to achieve this if that is the route you're thinking we should go.

Do you mind expanding on this? My understanding is that the `codeMirror` and `monacoEditor` packages would be referenced directly in let's say the `code-cell.tsx` component:

```
import CodeMirrorEditor from "../inputs/connected-editors/codemirror";
import MonacoEditor from "../inputs/connected-editors/monacoEditor";
...
render(){
...
	editor: {
	        codemirror: (props: PassedEditorProps) => (
	          <CodeMirrorEditor {...props} editorType={"codemirror"} />
	        ),
	        monaco: (props: PassedEditorProps) => (
	          <MonacoEditor {...props} editorType={"monaco"} />
	        )}
	}
```
What did you have in mind when you said we could use a composition component? 
Would be great if you can share some more details.

Do we have an example of using dynamic imports in the nteract project right now? The editor package seems like a pretty good candidate for that. Are there any other places where we load some specific package on demand (after the user changes a config for instance)?

**Comment by MSeal** [comment]
@vivek1729 That sounds like a reasonable path forward with a few options. I'm not as strongly opinionated on which would be easiest / best to do here.

> Do you think packaging the module in the context of an electron app can cause some further increase?

Probably not as I understand things.

**Comment by captainsafia** [comment]
Including both the CodeMirror and Monaco editor in the desktop app shouldn't be an issue as the user only pays a one-time download cost for the app.

As for how to package this for web hosts, we have to account for two things:

- We do not control the webpack configurations of end-user apps, in fact, we don't even control whether or not we use webpack
- Dynamic imports require some sort of code splitting feature to work

We already use code splitting in the Jupyter extension for loading transformers. This is the same strategy described in https://reactjs.org/docs/code-splitting.html.

We can use this but we'll have to make a note of the dependency on Webpack/other build tool to effectively use the packages. This shouldn't be problematic since we can safely assume that most end-users are using a modern build setup.

**Comment by vivek1729** [comment]
Thanks for the pointers @captainsafia. Apologies for the lengthy comment in advance. I thought it's important for me to share my understanding of the current architecture and then outline my thoughts in as much detail and clarity as possible right now.

### Dynamic imports in Nteract currently
I see that some transforms are loaded inside the `jupyter-extension` using the following pattern:

```javascript
import(
  /* webpackChunkName: "jupyter-widgets" */ "@nteract/jupyter-widgets"
).then(module => {
  this.props.addTransform(module.default);
});
``` 

### How is an editorType chosen currently?
Currently, both the editors : `codemirror` and `monaco` are already passed to the encapsulating `Editor` component when the app gets loaded. I am simplifying the actual code and highlighting the important pieces to understand how editors are loaded currently.

```typescript
//CodeCell component

import CodeMirrorEditor from "../inputs/connected-editors/codemirror";
import MonacoEditor from "../inputs/connected-editors/monacoEditor";

render() {
  
  const defaults = {
  ...,
  editor: {
    codemirror: (props: PassedEditorProps) => (
      <CodeMirrorEditor {...props} editorType={"codemirror"} />
    ),
    monaco: (props: PassedEditorProps) => (
      <MonacoEditor {...props} editorType={"monaco"} />
    )
  }
}

// EditorSlots are directly passed to the Editor component
const editor = children?.editor || defaults.editor; 

return (
  <div>
    <Source className="nteract-cell-source">
      <Editor id={id} contentRef={contentRef}>
        {editor}
      </Editor>
    </Source>
  </div>
  );
}

```

We can note that both the editors are passed here. This is the general pattern followed in Nteract. The Editor then decides which editor type to render by doing the following:

```typescript
// Editor component

render(): React.ReactNode {
  const chosenEditor = children ? children[editorType] : undefined;

  if (chosenEditor) {
    return chosenEditor({
      ...// Editor props
    });
  }

  return null;
}
```

### How can an editorType be loaded on demand?

Now when we are thinking of adding dynamic imports, we need to take care of two things:
- Splitting the bits into a separate chunk
- Loading those bits when they are actually needed

One approach that came to my mind was trying to dynamically import the stateful codemirror and monaco-editor components within the `CodeCell` component. This would require the `EditorSlots` to have a promise handler that would await the module and return them. The code could look something like this (untested):

```typescript
editor: {
  codemirror: (props: PassedEditorProps) => {
    codemirror = await import(/* webpackChunkName: "codemirror" */ "../inputs/connected-editors/codemirror")
    return codemirror({...props, editorType:"codemirror"});
  },
  monaco: (props: PassedEditorProps) => {
    monacoeditor = await import(/* webpackChunkName: "monaco-editor" */ "../inputs/connected-editors/monacoEditor")
    return monacoeditor({...props, editorType:"monaco"});
  }
}
```

However, I don't think this loads the monaco-editor or code-mirror package on demand because both these modules would get fetched regardless whenever the `CodeCell` component is rendered. It would however force the chunking so codemirror and monaco-editor would be output as separate js files.

The second way of doing this is within the `Editor` component itself because that's where the decision is made to actually render a specific editor type. Concretely, we'd want to do something in the `render` function:

```typescript
// Before
const chosenEditor = children ? children[editorType] : undefined;

// After
const chosenEditorPromise = children ? children[editorType] : undefined;
const actualEditorComponent = await chosenEditorPromise;
return actualEditorComponent({
   ...//EditorProps
})
```
Note that `children` refers to the `EditorSlots` that we pass inside the `CodeCell` component. For monaco-editor/code-mirror to be actually loaded when the `Editor` component chooses one by filtering on the `editorType`, we'd want some sort of promise mechanism. So, instead of directly getting the React Node from `children[editorType]`, it would now return a promise to dynamically import the connected monaco-editor/codemirror component. The module would only be fetched inside this `render` method. Loading the correct `editorType` within the `Editor` component ensures that the code is split and that we load the editors on demand when the user actually switches from one editor to another in the menu. It also doesn't special case CodeMirror.

### Open questions
1. We can note that code splitting to enable separate bundlig of monaco-edito (and codemirror) would require a code change within the package. So this would apply to both the desktop and jupyter extension. We'll have to explore web pack configurations to disable chunking for desktop app when we explicitly ask webpack to chunk within the code. You can see that this is a special case because currently the dyanmic imports in Nteract happen within the `jupyter-extension` folder so we know that those changes are self contained.
2. My proposal relies on changing the schema of `EditorSlots` interface. Is it even possible to add a promise in the interface? I have not been able to test out the actual feasibility of this code change.

It's important to reach a resolution here to be able to clearly outline the integration plan for monaco editor.
Please let me know what you guys think. @captainsafia @MSeal @rgbkrk @CrystallineCat @willingc @emeeks

**Comment by captainsafia** [comment]
I'm not sure that we'll be able to use async/await in the render method.

We can probably try something similar to what we do with the transforms in the Jupyter extension. In particular, we dynamic import the components, then store them in the Redux state, then read the components from the Redux state at render time.

This way, we maintain the separation of concerns that stateful-components is only responsible for rendering and we can move the dynamic import to the top level notebook app (in a decorator, for example).

**Comment by MSeal** [comment]
I generally agree with @captainsafia, though my opinions here aren't super strong beyond making sure the problem has been thought through and you all feel there's a reasonable path forward. Which appears to have been done well here imho.

**Comment by vivek1729** [comment]
@captainsafia  and @MSeal , thank you guys for the continued engagement. While I am adding the dynamic import functionality to load the editor components on demand, I'll add it so that it is a fall back and does not change the current functionality. This would allow current consumers to still be able to consume the stateful `editor` component using the pattern of EditorSlots. I have only removed the editors entry from the `defaults` in the `CodeCell`, `MarkdownCell` and `RawCell`. This enables Nteract desktop app and jupyter extension to leverage the dynamic import functionality while also affording the flexibility for consumers of the stateful editor component to continue using it the same way. So, it doesn't cause any breaking change in the stateful `editor` component :)  
As we get more feedback and transition to the lazy loading pattern in other parts of the product as well, we can think off deprecating the static import mechanism then.

**Comment by captainsafia** [comment]
Thanks for the update, @vivek1729!

> As we get more feedback and transition to the lazy loading pattern in other parts of the product as well, we can think off deprecating the static import mechanism then.

Agree with the approach of getting more feedback here. It'll help us make more confident decisions about how this part of the API will work. I also think we can build up to it incrementally since other aspect of the implementation (resize support and kernel completion support) aren't affected by it.

Cheers!

cc: @nathanieldeal This conversation around supporting an additional editor in nteract-based UIs might be of interest to you.

**Comment by willingc** [comment]
@vivek1729 @captainsafia Is this issue ready to be closed? Since Monaco is in the latest release :cake:, do we want to track improvements in individual issues or a roadmap issue?

**Comment by vivek1729** [comment]
I think the original intent with the RFC was to lay down the details for the initial contribution of Monaco Editor and highlight some of the potential improvements we can take up in the future. We've already unified the configuration and checked in some perf improvements for the Editor component. I imagine that the improvements are going to be an ongoing effort, so it might make more sense to track the issues individually. All the core contribution and improvements directly pertaining to Monaco Editor are already in.

**Comment by willingc** [comment]
Thanks @vivek1729. It's a fantastic addition. Let's track ongoing work in individual issues. 👍

**Comment by willingc** [comment]
I've added a Monaco editor label in case you wish to use it to tag issues. Thanks again @vivek1729.
