### ISSUE TITLE
Add undo option to Delete Cell keyboard shortcut

### ISSUE THREAD

**Issue by jarmokivekas** [nteract/archived-desktop-app#5221]
**Application or Package Used**

nteract desktop app v0.24.0 on Ubuntu

**Describe the bug**

Deleting a cell using the ctrl-shift-D shortcut deletes cell content without any way to recover it. 

**To Reproduce**

1. select any cell with content
1. press ctrl-shift-D 
3. cell is deleted 
4. there is no undo mechanism unavailable

**Expected behavior**

Either:

1. add the a undo button to the ui, the same way as when deleting using the cell toolbar
![image](https://user-images.githubusercontent.com/3074453/88362696-2d725200-cd86-11ea-91bb-9f51a0caa338.png)
2. remove the ctrl-shift-D shortcut, users can delete cells using ctrl-shift-X (cut cell) and recover them by pasting them back.

**Additional context**

Personally i keep typoing ctrl-shift-S as ctrl-shift-D and permanently deleting the work I've done instead of saving the notebook.

**Comment by captainsafia** [comment]
Ideally, we should show the undo UI when deletion occurs via a shortcut. The fact that it isn't happening currently is a head-scratcher. However, I suspect the root cause is related to an incorrect action being issued when deletion occurs via a keyboard shortcut.

**Comment by emeeks** [comment]
This is a pretty simple thing to fix, as @captainsafia said, the action being referred to is `deleteCell` and just needs to be replaced with `markCellAsDeleting`.
