### ISSUE TITLE
`yarn build:desktop:watch` broken

### ISSUE THREAD

**Issue by jruales** [nteract/archived-desktop-app#5222]
Commit "Fix WebPack" in PR #5115 actually fixed webpack for webpack.prod.js but broke it for webpack.dev.js (Now there's an error when running `yarn build:desktop:watch`). The "Fix WebPack" change should be reverted for webpack.dev.js.

In webpack.prod.js, the import is `const merge = require("webpack-merge");`, so it makes sense to use `merge.merge()`.

But in webpack.dev.js, the import is `const { merge } = require("webpack-merge");`, so only `merge()` should be used directly.

_Originally posted by @jruales in https://github.com/nteract/nteract/pull/5115#issuecomment-663809525_

**Comment by jruales** [comment]
Also seems like a regression of #5209

**Comment by CrystallineCat** [comment]
Thank you for bringing this up! I think I missed the change made by #5209 when rebasing #5115. I'll fix this momentarily.

**Comment by CrystallineCat** [comment]
Oops, didn't see you already made a PR. :cat:
