### ISSUE TITLE
Freshly installed nteract is stuck on splash screen 

### ISSUE THREAD

**Issue by atoav** [nteract/archived-desktop-app#5235]
Edit: Maybe this is a duplicate of #5190

**Application or Package Used**
nteract desktop 0.24.0

**Describe the bug**
Freshly installed nteract is stuck on splash screen.

**To Reproduce**

1. Download nteract
2. Run `nteract-Setup-0.24.0.exe` and install nteract
3. Splash screen opens and lets you wait (I waited at least 15 minutes)

**Expected behavior**
nteract should start up normally or at least display anything helpful

**Screenshots**

This is the output of running nteract with the verbose flag:
```
C:\Program Files\nteract>nteract.exe --verbose

C:\Program Files\nteract>
 10:13:22.879 > args { _: [], verbose: true, '$0': 'nteract.exe' }
10:13:22.915 > Checking for update
10:13:22.932 > launching an empty notebook by default
10:13:25.997 > Update for version 0.24.0 is not available (latest version: 0.24.0, downgrade is disallowed).
10:13:25.998 > checkForUpdatesAndNotify called, downloadPromise is null
```

Could it be that there is no proper timeout for a request in `checkForUpdatesAndNotify` and the server is unreachable? I don't know typescript and do not really understand what the function is doing so this is just a wild guess (and it belongs to the `electron-updater` dependency).

**Desktop (please complete the following information):**

- OS: Windows 10.0.18363
- Browser: Firefox
- Version: 78.0.2

**Additional context**
This is a quite fresh Windows 10 install. I have python3 for dev purposes installed, but as I didn't install the python kernels yet I don't believe this has any impact. Additionally I created explicit rules in the Windows Firewall to allow nteract to get out and in, so this should not be an issue.

**Comment by captainsafia** [comment]
Thanks for opening this issue!

This does indeed seem to be the hanging issue discussed in the other thread.

I'll close this now so we can keep the conversation on the issue cohesive.
