### ISSUE TITLE
nteract doesnt start on windows 

### ISSUE THREAD

**Issue by shishini** [nteract/archived-desktop-app#5254]
I installed interact
And it wont open, or in other words wont finish loading 

When I click nteract in the start menu, I get the logo screen, but the logo goes on forever 

I also need to add, that the site, doesnt have any installation instruction, 
And I came here from a julia academy course that required installing nteract 

Many on the julia academy course seem to have had a similar issue 

Please add more instruction on the site, and add requirements if there is any 
And finally, how can I solve this 

I am running windows 10 
And installed nteract 0.24.1

**Comment by logankilpatrick** [comment]
I am also getting the same issue on a fresh install of windows and nteract 0.24.1

**Comment by CrystallineCat** [comment]
nteract 0.24.x has a bug (#5190) where it isn't able to select a proper fallback kernel if the configured kernel isn't found. Without a kernel, it can't launch a window, so the splash screen just hangs, waiting for a window that never arrives. The default configured kernel is `python3`. The bug was fixed yesterday in the `main` branch by #5252.

If you don't want to build from the source, you can work around the issue by installing a `python3` kernel or changing the config file. The config file is in `%JUPYTER_CONFIG_DIR%/nteract.json`, and you can set it to the following to make julia the default kernel: 

```json
{
  "defaultKernel": "julia-1.0"
}
```
...if that doesn't work you can try the built-in javascript kernel instead:
```json
{
  "defaultKernel": "node_nteract"
}
```

If you have trouble finding the jupyter config dir, you can try executing `jupyter --config-dir`.

**Comment by logankilpatrick** [comment]
Thank you!!!

**Comment by shishini** [comment]
Just for the record to install a python kernel run the following commands

```
python -m pip install ipykernel
python -m ipykernel install --user
```
If you have python installed and added to your path, it should work

**Comment by NicholasWMRitchie** [comment]
I'm still puzzled.
As best I can tell, `%JUPYTER_CONFIG_DIR% = C:\Users\nicho\AppData\Roaming\jupyter` on my Windows 10 system.  I can add a file `nteract.json` containing the three lines
```
{
  "defaultKernel": "julia-1.5"
}
``` 
to this directory (or the `kernel` or `runtime` sub-directories).  nteract still locks on startup.
In the `kernel` directory, I only have one kernel installed `julia-1.5`.  I don't have any Python kernels installed.
What am I doing wrong?

**Comment by shishini** [comment]
> 
> 
> I'm still puzzled.
> ...
> I don't have any Python kernels installed.
> What am I doing wrong?

Personally, I just installed a Python kernel and it worked for me 
First install Python then run this 

```
python -m pip install ipykernel
python -m ipykernel install --user
```
then start nteract, it will work

**Comment by NicholasWMRitchie** [comment]
For me, one of the most compelling aspect of nteract is that it doesn't require me to install Python.  Not that I'm a Python hater, I just prefer to limit the software installed on my system and I otherwise don't use Python.

**Comment by NicholasWMRitchie** [comment]
It seems that if I create a directory `c:\users\nicho\.jupyter` and add one file, the file `nteract.json` into this directory, nteract will proceed past the splash screen.   I don't need to move any of the additional files or directories in `%JUPYTER_CONFIG_DIR% = C:\Users\nicho\AppData\Roaming\jupyter`.
This suggests to me that while Jupyter is using the `~/AppData/Roaming/Jupyter` directory for the Jupyter kernel configuration in WIndows 10, nteract might only be looking to the `~/.jupyter` directory.  
Maybe the `~/AppData/Roaming/Jupyter` directory needs to be added to the search path at startup?

**Comment by shishini** [comment]
@NicholasWMRitchie it is a bug that they will fix (or even fixed already), 
so long term this doesn't oppose your objectives 
you can install the newer version and uninstall python later 

short term, just install Python and make it work 👍 
just my opinion

**Comment by captainsafia** [comment]
> @NicholasWMRitchie it is a bug that they will fix (or even fixed already),

Fix will ship on Monday! Thanks for your patience folks.

> Maybe the ~/AppData/Roaming/Jupyter directory needs to be added to the search path at startup?

Can you open a new issue for this?
