### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by VarLad** [nteract/archived-desktop-app#5255]
I just downloaded the appimage today and its not working, neither is the snap build, nor is the .tar.gz one
Fedora 32 x86_6
![Screenshot from 2020-08-10 01-40-48](https://user-images.githubusercontent.com/51269425/89740922-d620f100-daaa-11ea-9894-2ad3930c7240.png)
4

**Comment by VarLad** [comment]
Update: the command nteract a.ipynb works fine though

**Comment by VarLad** [comment]
Also, the plots are showing with scrolling bar by default
For the full plot, I've to enable and then disable for every plot

**Comment by captainsafia** [comment]
@ChetanVardhan These issues are dupes of #5190 and #4994. Would recommend looking there for more info or to express your interest in the feature.
