### ISSUE TITLE
Stuck on loading in windows desktop version

### ISSUE THREAD

**Issue by robertwt7** [nteract/archived-desktop-app#5271]
Hey guys,

I came across this repo and was interested to try it. But I can't even load the desktop app

**Application or Package Used**.
nteract desktop

**Describe the bug**

Its loading forever, been 20 mins. I closed it with task manager then reopen but no luck

![image](https://user-images.githubusercontent.com/15647967/91113736-9d4b6380-e6c9-11ea-8aa1-9f2f6181e035.png)

**To Reproduce**

Download latest version from https://nteract.io/ front page
Install, open, then load forever

**Desktop (please complete the following information):**

- OS: Windows 10 pro build 19042.450 version 20H2
- Version 0.24.1

To be honest i'm not even sure what app is this, but after reading the docs i'm pretty interested in trying repl with jupyter notebook like extension.

Please let me know if I did anything wrong

Thanks

**Comment by captainsafia** [comment]
Hello @robertwt7 -- this is a known issue that we recently fixed. It was originally reported in #5190. You'll find a workaround in the thread. The fix will be shipped next Monday!

**Comment by robertwt7** [comment]
Ah alright thanks! I'll reinstall on monday then, in the meanwhile i'll try it on jupyter later
