### ISSUE TITLE
Nteract hanged on loading

### ISSUE THREAD

**Issue by arubhardwaj** [nteract/archived-desktop-app#5272]
Hi.
I just installed nteract for windows (I am using windows 10) and when I run it after installation, it is hanged on loading only. I tried multiple times by closing and restarting it but same issue is occurring. Could anyone help me why this is happening? 
Thanks in advance!

![image](https://user-images.githubusercontent.com/60003385/91130214-ed75f600-e6c8-11ea-910b-6a45de1efd13.png)

**Comment by NicholasWMRitchie** [comment]
See #5254

**Comment by captainsafia** [comment]
Thanks for opening this issue, @arubhardwaj! In addition to the issue that @NicholasWMRitchie mentioned, I would recommend taking a look at #5190 for more info and a work around for this issue.

A fix will be released on Monday.
