### ISSUE TITLE
IE 11 Compatibility

### ISSUE THREAD

**Issue by joshuali925** [nteract/archived-desktop-app#5291]
**Is your feature request related to a problem? Please describe.**
I'm working on a Kibana plugin that uses nteract. After this PR https://github.com/elastic/kibana/pull/59972 Kibana validates syntax of bundled node_modules to enforce IE compatibility and nteract fails the check. Specifically for 
```
@nteract/markdown
@nteract/mathjax
@nteract/outputs
@nteract/presentational-components
ansi-to-react
```

**Describe the solution you'd like**
Have nteract packages in ES5 and compatible with IE 11.

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @joshuali925!

Happy to welcome a contribution from you to add support for this. But considering the market share of IE11, I don't think this is something we'll be prioritizing.

**Comment by joshuali925** [comment]
I see, thanks for letting me know. I'll close the issue then.

For anyone running into this I believe adding a `postinstall` script in your `package.json` that runs babel on `node_modules/@nteract/*/lib` would be a workaround.
