### ISSUE TITLE
Diffing

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#53]
Earlier @captainsafia and I discussed the ability to do diffs on notebooks. With our immutable.js structure, this might turn out to be pretty simple. Hooking it up with git would be super slick.

There's already a diffing library for Immutable.js that produces RFC 6902 style patches, called `immutable-js-diff`:

``` JavaScript
var Immutable = require('immutable');
var diff = require('immutablediff');

var map1 = Immutable.Map({a:1, b:2, c:3});
var map2 = Immutable.Map({a:1, b:2, c:3, d: 4});

diff(map1, map2);
// List [ Map { op: "add", path: "/d", value: 4 } ]
```

It would be super cool to see what @smashwilson thinks about this one in terms of making custom diff tools for `git`.

**Comment by captainsafia** [comment]
Would be cool to think about the UI for diffing as well. Hm. 

Handy [link](https://github.com/intelie/immutable-js-diff) to immutable-js-diff.

**Comment by rgbkrk** [comment]
Closing, leaving it to be a research area and collaboration with nbdime.
