### ISSUE TITLE
Unable to load IpyWidgets

### ISSUE THREAD

**Issue by vivek1729** [nteract/archived-desktop-app#5313]
**Application or Package Used**
Nteract desktop app (v 0.25.1) and also on `main`

**Describe the bug**
Attempting to render an IpyWidget with the following code snippet throws an uncaught exception:

**To Reproduce**

1. Start a new notebook in the Nteract desktop app or local dev build from `main`
2. Make sure that you have the `ipywidgets` module installed. Add a cell with  `from ipywidgets import *` to import the ipywidgets module
3. Add another cell underneath to load  and render a widget : `IntSlider()`
4. You should see the following error:
![image](https://user-images.githubusercontent.com/1658576/94909622-4f5c1500-0458-11eb-8b3b-e7734923ad37.png)

**Expected behavior**
The Slider widget should render without any exceptions

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.25.1

**Comment by vivek1729** [comment]
@willingc , were you able to reproduce this bug?

**Comment by willingc** [comment]
@vivek1729 I haven't had time to do so. Tagged it to reproduce so others could try too. Just curious does it matter if the import doesn't use `*`?

**Comment by willingc** [comment]
Confirming @vivek1729 that I see on Mac released version. 
![Screen Shot 2020-10-16 at 9 36 39 AM](https://user-images.githubusercontent.com/2680980/96284902-19a84780-0f93-11eb-921f-b2a53500c25e.png)

**Comment by willingc** [comment]
Also tried
```
from IPython.display import display
w = widgets.IntSlider()
display(w)
```
The same error is thrown on the display call.

**Comment by captainsafia** [comment]
I have a hunch as to what is going on. Taking a look at it today! Thanks for investigating folks.
