### ISSUE TITLE
Account for Windows env in test suite

### ISSUE THREAD

**Issue by resaldiv** [nteract/archived-desktop-app#5325]
**Is your feature request related to a problem? Please describe.**
While I was following the contribute guide, I ran `yarn test` and one test failed. It happened because the test suite does not support the C drive file path style.

**Describe the solution you'd like**
Support C drive file path style.

**Additional context**
![image](https://user-images.githubusercontent.com/72623351/96070281-bb754a80-0e54-11eb-9f5c-9600016b45be.png)

**Comment by captainsafia** [comment]
Marking this issue as a test chore.

At some point, Node must've changed whether or not they include the drive letter in Windows-based paths and our tests haven't accounted for this. Tests will need to be updated accordingly.
