### ISSUE TITLE
execSync: Error: spawn node-gyp ENOENT

### ISSUE THREAD

**Issue by rornor** [nteract/archived-desktop-app#533]
I'm trying to install on Windows. All builds seem nice except execSync:

```
[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
```

Then, googling around I tried `node-gyp rebuild` inside execSync module:

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.11.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\vedar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Documents\\Git\\nteract\\node_modules\\execSync\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\vedar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\vedar\\.node-gyp\\5.11.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\vedar\\.node-gyp\\5.11.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\vedar\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Documents\\Git\\nteract\\node_modules\\execSync',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Documents\\Git\\nteract\\node_modules\\execSync\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  shell.cpp
..\src\shell.cpp(138): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(138): error C2143: syntax error: missing ',' before '&' [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(139): error C2248: 'v8::HandleScope::HandleScope': cannot access protected member declared in class 'v8::HandleScope' [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
  c:\users\vedar\.node-gyp\5.11.0\include\node\v8.h(889): note: see declaration of 'v8::HandleScope::HandleScope'
  c:\users\vedar\.node-gyp\5.11.0\include\node\v8.h(873): note: see declaration of 'v8::HandleScope'
..\src\shell.cpp(141): error C2065: 'args': undeclared identifier [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(141): error C2228: left of '.Length' must have class/struct/union [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
  ..\src\shell.cpp(141): note: type is 'unknown-type'
..\src\shell.cpp(143): error C2039: 'New': is not a member of 'v8::String' [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
  c:\users\vedar\.node-gyp\5.11.0\include\node\v8.h(2078): note: see declaration of 'v8::String'
..\src\shell.cpp(143): error C3861: 'New': identifier not found [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(142): error C3861: 'ThrowException': identifier not found [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(147): error C2065: 'args': undeclared identifier [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(147): error C2227: left of '->ToString' must point to class/struct/union/generic type [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(151): error C2039: 'Close': is not a member of 'v8::HandleScope' [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
  c:\users\vedar\.node-gyp\5.11.0\include\node\v8.h(873): note: see declaration of 'v8::HandleScope'
..\src\shell.cpp(151): error C2660: 'v8::Integer::New': function does not take 1 arguments [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(155): error C2039: 'NewSymbol': is not a member of 'v8::String' [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
  c:\users\vedar\.node-gyp\5.11.0\include\node\v8.h(2078): note: see declaration of 'v8::String'
..\src\shell.cpp(155): error C3861: 'NewSymbol': identifier not found [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
..\src\shell.cpp(156): error C2664: 'v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate *,v8::FunctionCallback,v8::Local<v8::Value>,v8::Local<v8::Signature>,int)': cannot convert argument 1 from 'v8::Local<v8::Value> (__cdecl *)(const int)' to 'v8::Isolate *' [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
  ..\src\shell.cpp(156): note: There is no context in which this conversion is possible
..\src\shell.cpp(156): error C2227: left of '->GetFunction' must point to class/struct/union/generic type [C:\Documents\Git\nteract\node_modules\execSync\build\shell.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\vedar\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14371
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vedar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Documents\Git\nteract\node_modules\execSync
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

OTOH, https://github.com/mgutz/execSync author deprecated usage.

?

**Comment by rgbkrk** [comment]
That appears to come from codecov, which is a dev dependency. There's a semi-recent PR to clean that up, though I don't think we're going to see a fix land anytime soon:

https://github.com/codecov/codecov-node/pull/14

**Comment by rgbkrk** [comment]
By the way, if you become successful in installing this and running it on Windows I will be super thrilled. I cleared through some of the hurdles for install on my Windows machine as written about in #388, haven't gotten the whole way through.

Separately, I made a PR to remove the `execSync` package from use in `codecov` in PR https://github.com/codecov/codecov-node/pull/22.

**Comment by rgbkrk** [comment]
Alright, `codecov` (node version) and therefore `execSync` are now gone from our packages. Can you try again and let me know how it goes? On a separate note, you'll need to use node 6 when building nteract.

**Comment by rornor** [comment]
Thanks @rgbkrk 

I added `"codecov": "git+https://github.com/rgbkrk/codecov-node.git#exec-sync-less" in dev packages,` (at the moment commit wasn't merged) and install procedure was w/o issues. However, when I launch I get error in electron:

> A dynamic link library (DLL) initialization routine failed.
>  \?\C:\Documents\Git\nteract\node_modules\zmq\build\Release\zmq.node

I guess that's because of my node version... I'll try to upgrade in next couple of hours

**Comment by rgbkrk** [comment]
If you want to try an alternate route, you can test out [`electron-rebuild`](https://github.com/electron/electron-rebuild), which should _hopefully_ build it for the right version of Electron.

**Comment by rornor** [comment]
All right, are you suggesting that instead electron-prebuilt?

**Comment by rgbkrk** [comment]
From the current clone that you have, try out:

```
npm install --save-dev electron-prebuilt
.\node_modules\.bin\electron-rebuild.cmd
```

**Comment by rornor** [comment]
A-ha :) Ok, on it...

**Comment by rornor** [comment]
I hit on this: https://github.com/electron/electron-rebuild/issues/15

As suggested in last comment `./node_modules/.bin/electron-rebuild.cmd  -w sqlite3 -p` resolves the issue. 

And now:

![clipboard01](https://cloud.githubusercontent.com/assets/3144780/16349904/af2fc01a-3a5b-11e6-8888-435c10782e88.png)

🎉 

Thanks for your help @rgbkrk  :)

Just one more question - why isn't Python listed in available languages? A get JavaScript and Xonsh.

**Comment by rornor** [comment]
> why isn't Python listed in available languages?

I had to do: `python3 -m ipykernel install --user` (as readme says)

**Comment by rornor** [comment]
After updating node to 6.2.2 above recipes does not work for me anymore. No errors, not even for `electron-rebuild` script.

It looks like it can not find a way to handle zmq node lib path, which it tries to load from here: `"\\?\C:\Documents\Git\nteract\node_modules\zmq\build\Release\zmq.node"`.

I tried to mangle, but it's just too frustrating for me and I give up with a taste that `electron` is major PITA on Windows.

**Comment by rgbkrk** [comment]
We found out there was a mismatch for later versions of electron-rebuild that affected the binaries for node zmq, including on Windows. We've gone back to a stable version. _However_, the state of our node zmq prebuilt setup is now written such that you probably can't get the Windows build working right out of the box. Since you were able to get it to work in the past, I'd love to pair with you so that this is done well for all Windows users.

**Comment by rornor** [comment]
Hi,

this happens after npm install: https://gist.githubusercontent.com/rornor/d99e47c91b1f188a89ea7a1491cd1911/raw/2d18900fae035f81be89cfab05385685650dfe49/gistfile1.txt

running:

```
npm install --save-dev electron-prebuilt
node_modules\.bin\electron-rebuild.cmd
```

can not resolve the problem obviously. 

So there seem to be a problem with zmq, as usual.
If you have other ideas I can try, let me know.

**Comment by rgbkrk** [comment]
We've now got a shipped release for Windows as well as testing on Windows and a plan for the future with building on Windows. I'll go ahead and close this. Feel free to re-open if the core problem is still there.

**Comment by rornor** [comment]
Nice!
Congrats @rgbkrk
