### ISSUE TITLE
Nteract not connecting with Julia

### ISSUE THREAD

**Issue by birrellwalsh** [nteract/archived-desktop-app#5336]
I have JuliaPro_v1.5.2 1.5.2 set as the default kernel when I run Nteract.  It is not finding it (though I am running Julia in that version), and I am sorry to say I do not see a way to connect it.

When I click restart, I get a msg from N. that says "

I have installed Julia as a kernel using the instructions on https://nteract.io/kernels.

Thanks!

**Comment by willingc** [comment]
Hi @birrellwalsh. The IJulia kernel is maintained by the greater Julia community. It looks as if they made a new release of IJulia a few hours ago. https://github.com/JuliaLang/IJulia.jl/releases/tag/v1.22.0

I will try to test on my system with the latest nteract version 0.26 that was released yesterday.

**Comment by willingc** [comment]
Hi @birrellwalsh. A brief update: I was able to get IJulia working within nteract.

Can you try updating the IJulia package at a Julia prompt:

```
julia> Pkg.update("IJulia")
   Updating registry at `~/.julia/registries/General`
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
```

You may need to reinstall the kernel using the `IJulia.installkernel` command. Only 1 parameter needs to be passed which is what you would like the display name to be (in this example `"Julia nteract"`):

```
julia> IJulia.installkernel("Julia nteract")
[ Info: Installing Julia nteract kernelspec in /Users/willingc/Library/Jupyter/kernels/julia-nteract-1.5
"/Users/willingc/Library/Jupyter/kernels/julia-nteract-1.5"

julia> 
```

I would make sure that you restart nteract once or twice and hopefully you will see `Julia nteract` (or the name you used) in the listing of available kernels. Select that option and then select "restart" from the same Runtime menu.

<img width="579" alt="Screen Shot 2020-10-27 at 1 03 02 PM" src="https://user-images.githubusercontent.com/2680980/97356140-0e87ce00-1855-11eb-8550-b7135ccdd842.png">

<img width="322" alt="Screen Shot 2020-10-27 at 1 04 33 PM" src="https://user-images.githubusercontent.com/2680980/97356078-f9ab3a80-1854-11eb-9930-274e79f24442.png">
