### ISSUE TITLE
Cannot render ipywidgets

### ISSUE THREAD

**Issue by anant-k-singh** [nteract/archived-desktop-app#5348]
**Application or Package Used**
nteract desktop v0.26.0
Python 3.8.6
ipywidgets 7.5.1

**Describe the bug**
Cannot use ipywidgets (e.g. _IntSlider_ widget) in an nteract notebook

**To Reproduce**

1. Open nteract desktop
2. Create new notebook with python3 kernel
3. Execute the following code
```python
import ipywidgets as widgets
from IPython.display import display
w = widgets.IntSlider()
display(w)
```
4. No output is generated

**Expected behavior**
Widget should render in output cell as per [this](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html).
![image](https://user-images.githubusercontent.com/22440924/98483066-9d202600-222b-11eb-9ad7-fc3628f73497.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/22440924/98482855-38b09700-222a-11eb-855a-a09aa5654019.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 86.0.4240.183

**Additional context**

**Comment by captainsafia** [comment]
Ugh. The fix placed in #5334 must've gotten reverted in the latest publish.

I was trying to put a more permanent fix for this by putting @nteract/core as a peer dependency in the widgets package but that caused some weirdness with Redux. We'll need to revisit this for the November release.

**Comment by willingc** [comment]
Nudge @captainsafia. Do you want to open a PR for your fix-ipywidgets branch? Verifying that it was working ;-)

**Comment by captainsafia** [comment]
@willingc Put in a fix or this in the PR above. Care to confirm on your end just so we're sure?
