### ISSUE TITLE
KernelStatus not matching with state being added to redux store

### ISSUE THREAD

**Issue by shibbas** [nteract/archived-desktop-app#5349]
**Application or Package Used**
nteract/packages/reducers

**Describe the bug**
The status of the kernel being set in the redux store does not seem to match the `KernelStatus` types. 

**To Reproduce**

State being set in store: 
`LAUNCH_KERNEL_BY_NAME` status is set to `"launching"`
https://github.com/nteract/nteract/blob/5d25c23fd23e2e20aa6abb43b84c37f8a60ebeea/packages/reducers/src/core/entities/kernels.ts#L42-L50

`KernelStatus` for launching == `"starting"` 
https://github.com/nteract/nteract/blob/49983455451c1038a59408537e8698ebca9f074a/packages/types/src/entities/kernels.ts#L40-L46

**Expected behavior**
KernelStatus should reflect the state being set in the redux store to enable comparisons. Not sure if this is intended and I'm just missing some intermediate step :)

**Comment by captainsafia** [comment]
Yep, this looks like an oversight. I don't think the introduction of the KernelStatus enum propagated to all the actions/reducers/epics/etc...

**Comment by shibbas** [comment]
Fast! Thanks!
