### ISSUE TITLE
PDF export just first page

### ISSUE THREAD

**Issue by pammacdotnet** [nteract/archived-desktop-app#5383]
The current version of nteract (0.27) just outputs the first page of a PDF export. Animation [here](https://tva1.sinaimg.cn/large/0081Kckwgy1gl8nws9nklg30dc0737ti.gif).

**Comment by willingc** [comment]
Thanks for the report @pammacdotnet. PDF support was partially fixed in https://github.com/nteract/nteract/pull/5338#issuecomment-718888160.

I'll leave this issue open in case someone wishes to open a PR to fix the multiple pages output.

P.S. Thanks for the animation too.

**Comment by captainsafia** [comment]
I believe we already have an issue tracking the single page problem at https://github.com/nteract/nteract/issues/5205. Closing in favor of that issue.
