### ISSUE TITLE
Create an alpha release including cell id for testing

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#5384]
Since cell id is a change that supports the recent jupyter JEP and its implementation 
at https://github.com/jupyter/nbformat/pull/189, let's create an alpha release for testing. cc/ @ryanlanciaux @MSeal

**Comment by willingc** [comment]
@captainsafia If you want to pair on this, we can see if I have permissions to cut a release and am up to date on the process just in case you need someone to release the monthly version for you.

**Comment by MSeal** [comment]
I can tackle this over the weekend. @rgbkrk for CI automation you were looking at I'm not positive if it will support alpha releases so I might do this release manually for now. Thoughts on that?

**Comment by captainsafia** [comment]
I believe @willingc already handled this.

**Comment by MSeal** [comment]
Got it, should we close this issue then?

**Comment by captainsafia** [comment]
Yep.
