### ISSUE TITLE
Nteract IJulia Installation Instructions lead to an error

### ISSUE THREAD

**Issue by marvingabler** [nteract/archived-desktop-app#5412]
Not a code bug, but an issue that might confuse beginners:

Currently, on the nteract website  https://nteract.io/kernels/julia IJulia installation says
```
julia> using Pkg  
julia> Pkg.update("IJulia")  
julia> IJulia.installkernel("Julia nteract")
```

what leads to a not defined error, since IJulia was not imported. Needs to be replaced with

```
julia> using Pkg  
julia> Pkg.update("IJulia")  
julia> using IJulia  
julia> IJulia.installkernel("Julia nteract")
```

**Comment by captainsafia** [comment]
@deepweather Are you able to submit a PR to address this? You'll need to modify the text here: https://github.com/nteract/nteract.io/blob/master/components/kernels/julia.js.

**Comment by marvingabler** [comment]
@captainsafia Sure, I created the PR [here](https://github.com/nteract/nteract.io/pull/352).
