### ISSUE TITLE
Sha512 checksum correct?

### ISSUE THREAD

**Issue by renatobellotti** [nteract/archived-desktop-app#5425]
Are you sure that the checksum of the 0.27.0 AppImage matches the sha512 sum in ``latest-linux.yml``? I get different checksums, but the program executes normally...

**Comment by captainsafia** [comment]
@renatobellotti The checksums are generated automatically by our build tool so there's not anything we do here specifically. Can you share the process you've identified to deduce the different checksums and we can sort out what might be going on?

**Comment by willingc** [comment]
Closing this issue as stale.
