### ISSUE TITLE
dlopen no suitable image found (runtime: nodejs)

### ISSUE THREAD

**Issue by loretoparisi** [nteract/archived-desktop-app#5433]
**Application or Package Used**
State which application or package this affects. For example: nteract desktop, nteract web, nteract on jupyter, etc.

**Describe the bug**
```
Error: dlopen(/Users/loretoparisi/Documents/Projects/node_modules/cld/build/Release/cld.node, 1): no suitable image found.  Did find:
	/Users/loretoparisi/Documents/Projects/node_modules/cld/build/Release/cld.node: code signature in (/Users/loretoparisi/Documents/Projects/node_modules/cld/build/Release/cld.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

and here
```
/Users/loretoparisi/Documents/Projects/musixmatch-ai-console/webservice/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/loretoparisi/Documents/Projects/node_modules/couchbase/build/Release/couchbase_impl.node, 1): no suitable image found.  Did find:
	/Users/loretoparisi/Documents/Projects/node_modules/couchbase/build/Release/couchbase_impl.node: code signature in (/Users/loretoparisi/Documents/Projects/node_modules/couchbase/build/Release/couchbase_impl.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**

- OS:`macos, 10.14.5`
- Browser `chrome, latest`
- Version [`0.28.0`
- NodeJS `v12.16.1`

**Additional context**
-

**Comment by captainsafia** [comment]
@loretoparisi Can you share the repro steps for this issue? Do they occur when you try to open nteract or when you edit a notebook?

**Comment by loretoparisi** [comment]
@captainsafia this happens when I try to run `nteract` cell that contains my Node library that has `couchbase` and `cld` among node dependencies.

**Comment by captainsafia** [comment]
I see.

Are you using the Node kernel that comes bundled with nteract?

If so, that kernel exists within the Electron context and doesn't have access to the same packages installed in Node on your system.

You might have more luck installing the ijavascript kernel on your machine.

**Comment by loretoparisi** [comment]
@captainsafia yes I'm using the embedded kernel in nteract. Please describe me how to use my local node installation. Thank you!

**Comment by n-riesco** [comment]
@loretoparisi 

The instructions to install IJavascript on macOS can be found [here](https://github.com/n-riesco/ijavascript#macos). Please, let me know if those instructions don't work, as I've recently noticed that [zeromq.org](https://zeromq.org/download/) recommends `brew install zmq` instead of `brew install zeromq`.

**Comment by loretoparisi** [comment]
@n-riesco thank you, I have successfully update `ijavascript` and `jupyter`. But within `nteract` I still get the same error. What is missing?

**Comment by n-riesco** [comment]
To use IJavascript, please select the runtime `Javascript (Node)`. If an error is still happening, please, post the new error message.

**Comment by loretoparisi** [comment]
So I do not see this option in the `nteract` menu after installing `ijavascript` and restarting the application.

**Comment by n-riesco** [comment]
What do you get when you run `jupyter kernelspec list` in a terminal?

**Comment by loretoparisi** [comment]
```
ip-192-168-178-22:~ loretoparisi$ jupyter kernelspec list
Available kernels:
  python2    /usr/local/share/jupyter/kernels/python2
  python3    /usr/local/share/jupyter/kernels/python3
```

that said I guess if `python3.9` that is also installed could be a problem...

**Comment by n-riesco** [comment]
That means that the IJavascript kernelspec hasn't been installed yet. To do so, you need to run `ijsinstall`.

**Comment by willingc** [comment]
Closing issue as resolved. Thanks for your help on this @n-riesco 👍🏼
