### ISSUE TITLE
Kernel message buffers should use Array instead of TypedArray

### ISSUE THREAD

**Issue by nicholaswold** [nteract/archived-desktop-app#5443]
**Application or Package Used**
nteract/messaging

**Describe the bug**
Ref: https://github.com/nteract/nteract/blob/main/packages/messaging/src/messages.ts#L98

Nteract uses TypedArrays (specifically Uint8Array) to represent file buffers in its kernel messaging. This becomes a problem when it is sent to the kernel via the usual rxJS method (`kernels.channels.next`) because rxJS uses `JSON.stringify` under the hood to serialize this data. TypedArrays aren't serialized into arrays, but instead as objects all their own. This causes an issue when using the `FileUpload` widget against a `jupyter_server` instance.

**To Reproduce**

1. Create a notebook with the following cell:

```python
import ipywidgets as widgets
from IPython.display import display
file_upload = widgets.FileUpload(accept="", multiple=False)
display(file_upload)
```

2. Use the FileUpload widget to upload any file.
3. You should see that your local Jupyter server fails to process the buffer.

**Expected behavior**
Instead, Nteract should use Javascript's Array object, which `JSON.stringify` will properly serialize into an array of bytes as the Jupyter messaging spec communicates.

NOTE: this may still fail on some `jupyter_server` versions because it may not convert the buffer into a `bytearray`, but that is something that cannot be fixed on Nteract's side (JSON has no way to represent bytes, I think?) I had to fix that locally by injecting the following code into my kernel websocket route:

```python
buffers = message.get("buffers")
message["buffers"] = [bytes(buffers)]
```

**Comment by captainsafia** [comment]
@nicholaswold Thanks for opening this issue.

I introduced this change [when we created the epics package and migrated to TypeScript](https://github.com/nteract/nteract/pull/3681#discussion_r239895074) to match some of the type conventions that existed in our actions/reducers. 

I believe ipywidgets uses the `ArrayBuffer` type for there buffers as in although I'm not sure how RxJS interacts with thatm

https://github.com/jupyter-widgets/ipywidgets/blob/367d3e193bd38593e3316b9420ec729bdc56f221/packages/base/src/utils.ts#L159-L161

Worst case scenario -- we can revert to using arrays as mentioned above although we might need to make some interface changes in our type definitions.

**Comment by nicholaswold** [comment]
In my tests it looked like RxJS was stringifying TypedArrays as JS objects in the style of `{index: byte, ...}` before sending them over the wire.

I've got another issue open in Jupyter Server to tackle the other side of this: https://github.com/jupyter-server/jupyter_server/issues/406, and @kevin-bates brought up the good point that this doesn't affect binary messages sent down the websocket. I didn't immediately see a way to send binary messages in RxJS, but if we can figure something out, then that would give Nteract some flexibility in supporting widgets that use buffers.

**Comment by rgbkrk** [comment]
This is one area where the initial implementation was the pure JSON jupyter protocol in as simple a way as possible. At the time I didn't want to have to worry about the buffers since they were less well-specified at the time. It's time to figure out the right way to handle it now!

**Comment by xinyi-joffre** [comment]
@rgbkrk, is there an ETA on supporting binary message data in nteract? We are trying to use nglview widget, but it passes binary data back and forth to support the visualizations:

https://github.com/nglviewer/nglview

The binary message currently causes a JSON exception to be thrown in nteract:

![nglview-binary](https://user-images.githubusercontent.com/20933017/136088573-6134ad5a-81ad-416e-a175-5935f12fc457.png)

**Comment by pwang347** [comment]
Also looping in @captainsafia @willingc  @MSeal for visibility!

**Comment by rgbkrk** [comment]
I'm using separate code from the nteract monorepo right now, but the quick fix for this is to switch up the `buffers` when RxJS processes the messages:

```
const buffer: Uint8Array = message.buffers;
message.buffers = Array.from(buffer);
```

**Comment by xinyi-joffre** [comment]
@rgbkrk , thank you for the response! I'm not sure I understand the suggestion and where those two lines of code would be added to fix the problem.

Is it that we need to fork nteract to make this change somewhere?
Or that we would need to fork nglview widget on the javascript side and make this change somewhere?

Thanks for your help!

**Comment by captainsafia** [comment]
@xinyi-joffre I think I have a fix for this issue. I've verified it with the code snippet in the original bug report. Do you mind sharing a notebook I can use to verify for your scenario? If it checks out there, we can merge and release the change.

**Comment by pwang347** [comment]
Thanks @captainsafia! The file we were testing with is the following IPYNB:
[nglviewer.txt](https://github.com/nteract/nteract/files/7429949/nglviewer.txt)
 
To install the extension:
```
pip install nglview
jupyter-nbextension enable nglview --py --sys-prefix
```

The current behaviour is that the cell does not render anything.

Edit:
It works with the latest change on main!
![image](https://user-images.githubusercontent.com/8560030/139166340-af4060d8-5a34-4e17-8f4a-979a60984787.png)
