### ISSUE TITLE
Unable to load mythic-configuration in browser due to node package reference

### ISSUE THREAD

**Issue by erem-stripe** [nteract/archived-desktop-app#5445]
**Application or Package Used**
mythic-configuration

**Describe the bug**
Importing mythic-configuration into a browser setting results in this stack trace:
```
ERROR in ./node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/mkdirp'
 @ ./node_modules/mkdirp/index.js 2:9-22
 @ ./node_modules/fs-observable/lib/index.js
 @ ./node_modules/@nteract/mythic-configuration/lib/backends/filesystem.js
 @ ./node_modules/@nteract/mythic-configuration/lib/index.js
 @ ./node_modules/@nteract/stateful-components/lib/config-options.js
 @ ./node_modules/@nteract/stateful-components/lib/index.js
```

**To Reproduce**

1. Start with a react application in the browser
2. Add `mythic-configuration` as a dependency
3. Attempt to import mythic-configuration
4. Note the stack trace

**Expected behavior**
I expect no stack trace. I expect mythic-configuration not to import any node-specific modules by default.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: chrome
- Version: 88

**Additional context**
The stack trace tells the story, but essentially by the root cause is that `mythic-configuration/index.js` imports `backends/filesystem.js` which imports `fs-observable`, which is node-specific and therefore breaks in the browser.

If index.js did a dynamic import of filesystem only as requested it would probably fix this ticket.

**Comment by captainsafia** [comment]
@erem-stripe Thanks for the PR! After taking a look at it, I decided it's best to remove the top-level export of `setConfigFile` from mythic-configuration altogether. Since it's backend specific (and really only used for the desktop app), it doesn't make sense to export this as part of the top-level API.
