### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [nteract/archived-desktop-app#545]
Is it possible to make this dual license with one license being the original BSD or a permissive license like ASL 2.0 or MIT. MPL can at times be problematic for us to use.

Also Jupyter uses BSD.

**Comment by rgbkrk** [comment]
This was BSD in the past and the most likely if we were to shift licenses again.

What's your intended use? What do you want to build?

**Comment by sirinath** [comment]
I am looking from a business perspective. ASL 2.0, BSD, MIT are the most commonly whitelisted licenses, hence if you use components this are based on these licenses the chances are that you do not have to go through lengthy legal evaluation  and license approval process if want to sell bespoke solutions.

**Comment by sirinath** [comment]
Any additional thoughts on this? It would be great if you can return to the original license. As number of contributors increase any license change will become impossible as you will have to contact all and get their consent.

**Comment by rgbkrk** [comment]
@sirinath Go ahead and create a checklist of all the authors in this issue and ask for their approval in changing the license. You can count me as a 👍 already.

Bear in mind that one reason that we're on MPL 2.0 (aside from the license itself) is that it's part of our contribution contract: [C4](http://rfc.zeromq.org/spec:42/C4/). We'll need to adapt that as well.

**Comment by sirinath** [comment]
C4.1 / C4 can be forked and edited to suit. In this case the edited doc will be under GPL. Alternatively you can say you adopt C4/C4.1 with exception of .... In which case you just say the license you are going to adopt is X and this overrides clause Y.

---

Please check the boxes below if you agree to a license change back to the [original license](https://github.com/nteract/nteract/commit/f62b657f6603e68adebb3f8d5814646ccdc10a28#diff-9879d6db96fd29134fc802214163b95a) which is also used in [Jupyter](https://github.com/jupyter) and other projects in [this organisation](https://github.com/nteract)

CC:
- [x] @rgbkrk
- [x] @captainsafia
- [x] @jdetle
- [x] @jdfreder
- [x] @kenwheeler
- [ ] @Carreau
- [ ] @betatim
- [ ] @karissa
- [ ] @StevenLangbroek
- [x] @freeman-lab
- [ ] @jaredly 
- [ ] @phfrohring
- [x] @ivanov 
- [x] @minrk 

---
- [ ] @andrewheusser 
- [ ] @andrewosh
- [ ] @arokem 
- [ ] @betatim
- [ ] @bkarlovitz
- [ ] @dalejung
- [ ] @IonicaBizau 
- [ ] @jeremiahrhall 
- [ ] @kelleyblackmore 
- [ ] @kevinrodbe 
- [ ] @knowbody
- [ ] @mangecoeur 
- [ ] @mcanthony
- [ ] @mimiflynn
- [x] @mmngreco
- [ ] @montazze
- [ ] @philpl
- [ ] @shawnheide
- [ ] @unix0000
- [x] @willingc

---
- [x] @smashwilson 
- [ ] @IonicaBizau
- [ ] @mathisonian
- [x] @tiangolo 

---
- [ ] @willwhitney
- [x] @lgeiger
- [ ] @aulneau
- [ ] @n-riesco
- [ ] @karissa

Please let me know if I missed anybody or missed classified anybody especially the contributors.

**Comment by ivanov** [comment]
I'm 👍  on whatever license changes Kyle's OK with. 

I'm opposed to classifying "major" "minor" and "micro" contributors by some arbitrary metrics. Furthermore, I'm strongly opposed to attaching "vote needed," "vote highly desirable," and "vote desirable" to those labels. 

A lot of people are pinged with this issue. And the majority of them are placed in the bucket of "can weigh in but vote is not mandatory" - I find that rather off-putting and anti-social.

Classifying contributors as major and minor is an anti-pattern.  Anyone who's made a contribution should have their say.

**Comment by betatim** [comment]
What was the thinking behind switching to MPL? Usually such choice are made with some reasoning behind them so we should check what that was.

As I understand it MPL does not stop you from selling a product based on `nteract` or even keeping your secret sauce secret. Doing the legal legwork seems like a small price to pay (both in terms of $$ and effort) in exchange for a high quality product like `nteract`. `nteract` receives support from [two companies](https://github.com/nteract/nteract#support) who have presumably found a way to give back under the current model and further their commercial goals. Another one supports the project by allowing staff to use work time.

The [0MQ guide](http://zguide.zeromq.org/page:all#toc145) ([it is about the community](http://zguide.zeromq.org/page:all#Care-and-Feeding)) contains some reasoning behind why a license that allows remixing is a good choice.

The question of how to make your open-source community sustainable has been getting a lot of attention lately, and has been a struggle for a long time.

Given all this I think a more detailed motivation of why this change would make the community/project better is needed. If only to avoid the slight aftertaste of "please make this easier to use in a commercial setting where we don't wish to contribute back".

**Comment by sirinath** [comment]
> ... where we don't wish to contribute back

Very rarely does any organisation make changes to active projects which they do not upstream as with each new release they have to integrate all changes. The 0MQ rationale as it is just arguments with not empirical or significant evidence to support their rationale. Share alike licenses do lead to fragmentation of open source projects due to license incompatibilities or asymmetric sharing as you cannot re license.

Also we have to be in line with reality. Many organisations have license whitelisting and also contractual clauses about code ownership and licensing. In these if the license is not whitelisted or incompatible with contractual obligation you cannot use it. This mostly affects outsourcing and contracting and more acute in outsourcing where contractual obligations are more stringent. In addition, more legal scrutiny and compliance on IP related issues become more costly depending of the dependencies you use. In case of prototypes and demos legal negotiation of these happen before entering into a contract hence upfront overheads increase before being assured of a contract hence it is more rationale to keep costs and potential of legal related questions to a minimum.

This is a minor annoyance with MPL and not the main issue. MPL can be used in commercial setting there you link to the compiled code. Issue comes in non compiled code like JS, HTML. Say you put a logo in the HTML what license coves this modified page. Since the image is separate it need not be MPL in which case what is the rationale of sharing the HTML without the image does the image need sharing also and becomes MPL? If you recreate the HTML with the logo then this is a form of copying hence the file you create is MPL. If you look into the source to see how X is done or integrate to implement / integrate new components Y then Y becomes MPL as you might have to use non trivial part in X to implement Y. Say I want to embed a cell evaluation into another application then studying how this is done and in the current file and implementing this by the same person will become copying unless a 3rd person comes in between to write a specification on how the integration is done. In an sharealike project it s a legal risk to look at the code learn how something is done as by implementing what you learned through looking at the code means the code will become tainted. If you use an IFrame or canvas to embed this will this combined canvas becovered under MPL? IFrame maybe not but forms of embedding / partial embedding this is problematic. None of these issues have be tested in court so lawyers can argue at length and then send you the bill. So best route is to have the option where you can use without have to jump over many hurdles or too costly or risky to use.

**Comment by sirinath** [comment]
> can weigh in but vote is not mandatory

I have included a list or other uses who might be interested in the project (contributors to sister projects and forks) but not contributors to this project. They have contributed to the project hence for the purpose of the license change their vote is not necessary in case they cannot be contacted or do not vote. They have begin CCed as a courtesy to make them aware of this issue than just limiting it to the project contributors so they can raise their issues or concerns if needed.

Anyway I removed the particular wording.

**Comment by willingc** [comment]
@sirinath I realize that you put time and effort into creating the lists and are following a typical open source process for switching a license. Like @ivanov, I'm a bit sad that contributors are being categorized by code contributions. How would you feel about removing the categories and just have one list of contributors?

One of the great things about @rgbkrk and others here is that we value each other as individuals who contribute to the project in a variety of ways (documentation, onboarding, spreading the word about the project, etc.). The goals of the C4 contribution contract are focused on inclusion and valuing each contribution.

I'm fine with any license being discussed. Let's try to keep the "community" cohesive, appreciative of all contributors. It's great to see the good stuff happening in the larger project. :smile:

**Comment by sirinath** [comment]
I removed the classifications. 

Also please record your vote by clicking on the relevant box.

**Comment by willingc** [comment]
Thanks @sirinath. Will do.

**Comment by betatim** [comment]
I agree with you that these are real issues for companies that do not wish or can not make their work available under a MPL compatible license. This is a difficult to navigate area for all of us who are trying to create software that uses open-source projects in a commercial setting. As a commercial entity with a business model that is incompatible with MPL like licenses it is in my interest to have work licensed under BSD.

(Speaking purely for myself here) To make `nteract` sustainable I think `nteract` needs to work out what is in its long term interest and put those interests first. Anything else makes no sense. These interests might not overlap 100% with those of any other organisation or company. IMO the fastest way to reach a mutually beneficial position is to openly discuss the needs of each party and then make an informed decision.

I would like to see some discussion and then conclusion on what `nteract` the community thinks is its long term goal and hence what is in its interest. Once this is clear it will be much easier for me to decide whether or not making this change to the license is a good move or not.

**Comment by sirinath** [comment]
Though `nteract` is open source for integration purposes if you look at the code there is a chance what you develop will become MPL. Also there are reasonable about of JS and HTML which will stay MPL.  E.g. Also there is a chance if https://github.com/nteract/hydrogen integrations similar to that of this project and no documentation on the contrary clear room process was followed the some of the code may become MPL without anybody thinking mainly due to the uses familiarity of code in `nteract` .  (I am just giving this as an example.) Similarly if this is integrate by studying some of the code into another project this might become tainted without a clean room design and worst without anybody's knowing. In commercial closed should projects involuntary training may not become an issue as there is little chance that this can be discovered and legally enforced. Bigger issue is if the code is open source or there is an intention or obligation to release under a different license (say ASL 2.0) where any similarities can easily be scrutinized and found in case of integration code and can be argued as copied. Also there is very difficult to ascertain if is any is actually "copied", could be legally held as copied or not copied, from external parties. Even in commercial closed source setting it always help to ensure the code is not encumbered by possible legally gray areas. In case there is a CLA and one party owns the code incase there is accidental tainting then you have to negotiate with only one party. In case there is no CLA these issues cannot be resolved as there might be many parties from whom you should get agreement. So permissive licenses work better greater good.

**Comment by minrk** [comment]
👍 from me for BSD/MIT. I don't think the share-alike license clause makes much sense to be included in C4, so I would support any fork of C4 that removes the license clause altogether, or loosens it to allow any open source license.

**Comment by sirinath** [comment]
@minrk I created a fork: https://github.com/sirinath/rfc/blob/master/42/README.md . Let me know your thoughts?

**Comment by tiangolo** [comment]
Here are my 2 cents, although I've been really involved is in Hydrogen.

I'm not an expert in licenses, but I like permissive licenses (ASL/BSD/MIT). 

I'm OK with a license like those :+1:.

If there are others (like me) checking this but aren't experts in licenses, I use this as a guide, it might help you: http://choosealicense.com/ (BSD is in the appendix: http://choosealicense.com/appendix/).

Nevertheless, the [C4 contribution contract](http://rfc.zeromq.org/spec:42/C4/#22-licensing-and-ownership) @rgbkrk posted says:

> The project SHALL use a share-alike license such as the MPLv2, or a GPLv3 variant thereof (GPL, LGPL, AGPL).

What I understand from that is that it wouldn't be possible to use a license that doesn't require disclosing the source.

Is that _contribution contract_ and the license modifiable by `nteract` or is it a requirement for using ZeroMQ?

I see that [ZeroMQ has a share-alike LGPL license, but it has a **static linking exception**](http://zeromq.org/area:licensing).

Does the source code of `nteract` modify parts of ZeroMQ or uses it statically?

I guess that if `nteract` uses ZeroMQ "as a client" there wouldn't be a problem in changing the license (and the contribution contract).

**Comment by jdetle** [comment]
I am okay with the BSD License!

**Comment by jdfreder** [comment]
BSD or MIT are okay with me too

**Comment by sirinath** [comment]
Awaiting response from. Please register your acceptance: 
- @captainsafia
- @Carreau
- @betatim
- @karissa
- @StevenLangbroek
- @jaredly 
- @phfrohring

---
- @andrewheusser 
- @andrewosh
- @arokem 
- @betatim
- @bkarlovitz
- @dalejung
- @IonicaBizau 
- @jeremiahrhall 
- @kelleyblackmore 
- @kevinrodbe 
- @knowbody
- @mangecoeur 
- @mcanthony
- @mimiflynn
- @mmngreco
- @montazze
- @philpl
- @shawnheide
- @unix0000

---
- @IonicaBizau
- @mathisonian

---
- @willwhitney
- @lgeiger
- @aulneau
- @n-riesco
- @karissa

**Comment by asdf8601** [comment]
I'm okey with BSD or MIT.

**Comment by captainsafia** [comment]
Closing this issue as it requires too much consensus and contains noise. Discussion will continue with relevant parties in an new issue. Thanks!

**Comment by sirinath** [comment]
@captainsafia  Can you link the new issue here as a pointer?

**Comment by rgbkrk** [comment]
#836
