### ISSUE TITLE
Installed nteract --edge v0.25.1 through snap on Linux. Had kernels installed already, working fine but only default javascript kernel shows up

### ISSUE THREAD

**Issue by ergomancer** [nteract/archived-desktop-app#5464]
###### I am kind of new to the development world but I am learning and I really want to contribute too. Maybe someday I'll be able to. 
________________
So I had python3, javascript and c kernels installed working fine with jupyter and Hydrogen but nteract doesn't seem to be able to find the python kernel or the c kernel for that matter.

I read various issues but most were old and didn't help me much. I tried the preliminary troubleshooting like `$PATH` adjustment, reinstalling nteract, changing python3 kernel installation between global and user, nothing seemed to work. I'd really appreciate help. 
______
# EDIT: FIXED
_______
so out of a hunch I uninstalled the snap version and installed the `.deb` package... That ran me into a problem that there was a dependency on `libappindicator3-1` which in turn depended on `libindicator3-7` and these were not in the repository so I had to manually install them via their `.deb` packages but then nteract installed properly and it works perfectly... Detects all kernels and everything.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @quantum-corn!

We've been running into issues publishing our Snap packages as of late, which might've contributed to this bug. I'm glad you got things resolved on your end.

We should probably sort out what to do with the snap packages...

**Comment by willingc** [comment]
Closing this issue and added #5498 to improve snap release publishing.
