### ISSUE TITLE
Ctrl Shift Shortcuts

### ISSUE THREAD

**Issue by vbardakos** [nteract/archived-desktop-app#5469]
In windows, some of the Nteract `Ctrl+Shift` keyboard shortcuts trigger the browsers' default shortcuts. For example,

| Notebook | Chrome | Shortcuts |
| ----------- | --------- | ---------- |
Copy Cell | Inspect Element Mode | Ctrl+Shift+C
Cut Cell | --- | Ctrl+Shift+X 
Delete Cell | Save open tabs as bookmarks | Ctrl+Shift+D 
Paste Cell(s) Below | --- | Ctrl+Shift+V
Convert Cell to Code Cell | --- | Ctrl+Shift+Y
Convert Cell to Markdown Cell | Login as User/Guest | Ctrl+Shift+M
Save As | --- | Ctrl+Shift+S
Redo changes in editor | --- | Ctrl+Shift+Z
Insert Cell Above | --- | Ctrl+Shift+A
Insert Cell Below | Show or hide the Bookmarks bar | Ctrl+Shift+B

I understand that most of the shortcuts are preoccupied by the browsers and there isn't much space to use unique keys as semantically meaningful shortcuts in the notebooks. Although, I suppose the importance of the above to be under the label `CTRL+SHIFT` doesn't really matter, if they are unpractical.

For example, if we need to insert a cell below while we keep our bookmarks bar, we actually need to use
`CTRL+SHIFT+B; CTRL+SHIFT+B; ArrowDown; Ctrl+Shift+D; ESC`

---
Request:

Some of the above are actually the most frequently used shortcuts for some users. Is it possible to add a second shortcut for those which are preoccupied by the browsers, until a better grouping solution is found?

Thank you in advance

**Comment by captainsafia** [comment]
@vbardakos Are you using the nteract desktop app or the Jupyter extension?

**Comment by vbardakos** [comment]
> @vbardakos Are you using the nteract desktop app or the Jupyter extension?

I suppose it's Jupyter extension since I installed with `conda install -c conda-forge nteract_on_jupyter`

**Comment by captainsafia** [comment]
@vbardakos Ah I see. The keyboard shortcuts documented above only work on the desktop app. We don't have keyboard shortcuts for the Jupyter extension and it is not actively maintained at the moment.

**Comment by willingc** [comment]
Closing as resolved.
