### ISSUE TITLE
nteract.io website down

### ISSUE THREAD

**Issue by dpgarrick** [nteract/archived-desktop-app#5479]
**Describe the bug**
The nteract.io website is reporting an internal server error and not loading

**To Reproduce**

navigate to nteract.io

**Expected behavior**
the website should work

**Screenshots**
![image](https://user-images.githubusercontent.com/59327926/113220502-c5461980-92df-11eb-8f71-55d0e108de3a.png)

**Desktop (please complete the following information):**

latest chrome on latest macOS

**Additional context**
Based in New Zealand if that is a factor.

**Comment by willingc** [comment]
Thanks for the report. I believe I resolved the issue in https://github.com/nteract/nteract.io/pull/367. Please let us know if you are still seeing the issue after reloading your browser. Thanks for using nteract :sunny:

**Comment by MSeal** [comment]
Thanks for addressing @willingc. The site is loading correctly for me atm if that helps with any additional reports.
