### ISSUE TITLE
Update docs releasing instructions

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#5481]
Now that we are building docs from this repo, we should update the `now` command to use a more recent command with `vercel`: https://vercel.com/docs/cli#commands/overview/project-linking

**Comment by willingc** [comment]
The docs are now live. Yay @jeromefv :tada: @captainsafia please double check the deploy config in vercel. I had to change some things now that the docs repo is not used.

**Comment by captainsafia** [comment]
I think we can probably remove the section about releasing the docs altogether now that we have automatic builds working for it.

We still need to sort out how we can get automated releases for the API doc working though, although I think that is less important.
