### ISSUE TITLE
Adding Open recently edited for File menu item

### ISSUE THREAD

**Issue by GarciaPL** [nteract/archived-desktop-app#5487]
It would be very beneficial for a user if a new option under 'File' menu item can be added like '**Open recently edited**' under 'Open' but above 'Open Example Notebook'. It will speed up a little bit loading of ipynb files in general

![openrecently](https://user-images.githubusercontent.com/1670370/114008152-dc45b800-9859-11eb-88e4-65e26725655e.PNG)

**Comment by captainsafia** [comment]
@GarciaPL It looks like you're on Windows. If the nteract app is pinned to your desktop, you should see the recently opened documents in the pane that pops up when you hover on a menu item.

We previously explored adding a recently opened item but Electron didn't have the APIs to implement this at the time.

**Comment by willingc** [comment]
Closing as resolved.
