### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#549]
In order to approach having more components available for an online version of the nteract components (in your friendly browser instead of Electron) we need to create a [monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md).

I'm in favor of exporting components _directly_ from nteract/nteract to assist with this so that's it's easy to work on the desktop app as a standalone in tandem with these core components. Especially since the API keeps evolving for actions, reducers, etc.

Motivation for "new wave modularity": http://www.macwright.org/2016/07/08/lerna-npm-organizations-new-wave-modularity.html

Sub-issues that make this easier for us:

* [ ] https://github.com/nteract/nteract/issues/1288

**Comment by captainsafia** [comment]
I'm down for monorepo.

![](http://i.giphy.com/5ev3alRsskWA0.gif)

**Comment by ivanov** [comment]
![monorail!](https://img.buzzfeed.com/buzzfeed-static/static/2014-08/4/8/enhanced/webdr04/anigif_enhanced-29437-1407154860-14.gif)

**Comment by rgbkrk** [comment]
Another component I think we'll want to bring into here is `enchannel-zmq-backend` as well as `spawnteract` (I'm guessing we'd make it based off of `spawn-rx` in here). `jupyter-paths` can likely stay separate though.

I've updated the issue description with this great article too: http://www.macwright.org/2016/07/08/lerna-npm-organizations-new-wave-modularity.html

Soon I'll provide a better outline of what we can do collectively. We'll likely want to turn our redux / context focused components into components that accept callbacks (`onExecute`, etc.)

**Comment by rgbkrk** [comment]
Here's how mapbox-gl-js organized it: https://github.com/mapbox/mapbox-gl-js/issues/3656

**Comment by rgbkrk** [comment]
Wish I had noticed this before:

> You can use `lerna import <package>` to transfer an existing package into your Lerna repository; this command will preserve the commit history. `lerna import <package>` takes a local path rather than a URL. In this case you will need to have the repo you wish to link to on your file system.

Could have used that rather than the way we did it in the rush for time.

**Comment by rgbkrk** [comment]
Closing this since we're now in a good setup with lerna.
