### ISSUE TITLE
@nteract/notebook-app-component (7.7.7) does not compile in a tsx app.

### ISSUE THREAD

**Issue by kenpu** [nteract/archived-desktop-app#5491]
**Application or Package Used**
@nteract/core
@nteract/app-component

**Describe the bug**
I am trying to include nteract components in a minimal `npx create-react-app --template typescript`  project.  The following @nteract npm packages are included using `yarn add ...`
```
    "@nteract/core": "^15.1.7",
    "@nteract/notebook-app-component": "^7.7.7",
```
But I keep running into compilation error:

```
./node_modules/@nteract/stateful-components/src/inputs/connected-editors/monacoEditor.tsx 14:0
Module parse failed: The keyword 'interface' is reserved (14:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
| 
> interface ComponentProps {
|   id: string;
|   contentRef: ContentRef;
```

**To Reproduce**

1. `$ npx create-react-app hello-world --template typescript`
2. `$ cd hello-world`
3. `$ yarn add @nteract/core @nteract/notebook-app-component styled-components`
    
   This installs @nteract/core^15.1.7 and @nteract/notebook-app-component^7.7.7

4. Simply change index.tsx with the following imports:

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

import {} from "@nteract/core"
import {} from "@nteract/notebook-app-component"

ReactDOM.render(
  <React.StrictMode>
    <div>
      <h1>Simple App</h1>
    </div>
  </React.StrictMode>,
  document.getElementById('root')
);
```

5. `$ yarn start` will result in the failure.

I'm using typescript `^4.1.2`.

I am expecting @nteract components can be used as npm modules, and after quite a bit of digging around, I can't seem to figure out why it's to process `monacoEditor.tsx`.

Any help will be greatly appreciated.

Thanks.

**Comment by kenpu** [comment]
Update: create-react-app (CRA) does not include ts-loader by default.  I found it rather difficult to modify CRA's webpack.config.js file.  Instead, I started a new npm project with webpack from scratch.

**Comment by captainsafia** [comment]
@kenpu Great! Glad you got this resolved.

@jeromefv This makes me think that we might want to have a "Meta" section in the docs that outlines things like needing to configure Webpack/TypeScript in your application if you are using the nteract packages.

**Comment by e8panse** [comment]
@captainsafia I know it's an old issue, but in documentation there's still nothing about webpack configuration and we are facing the same issue. Could you please briefly explain possible solution?

**Comment by captainsafia** [comment]
@e8panse This doc page might prove to be a helpful starter: https://webpack.js.org/guides/typescript/

**Comment by e8panse** [comment]
@captainsafia webpack correctly process all ts/tsx in node_modules except this package - connected editors

Creating simple app with:

1) create react app with typescript template ( yarn create react-app appname --template typescript )
2) install component from this library  (yarn add  @nteract/notebook-app-component  )
3) include import {
  Cell,
  Input,
  Prompt,
  Source,
  Outputs
} from "@nteract/presentational-components";
4) yarn start

gives that error.

this is webpack config:

`  test: /\.(js|mjs|jsx|ts|tsx)$/,
              include: paths.appSrc,
              loader: require.resolve('babel-loader'),`

Simple removing this connected editors .tsx files and commenting section load-editors in decorators / editor loader solve this error. 

But this is not a solution ;) it's just proving a fact that issue only in these files.

How correctly do it? Could you please help?

**Comment by captainsafia** [comment]
connected-editors have an app size optimization that takes advantage of chunking in WebPack so you'll need an analgous config to support it. The code below might help as a starting point.

https://github.com/nteract/nteract/blob/df958a94565520df1645b54ba7218b24be4e1a6a/packages/notebook-app-component/src/decorators/editor-loader/index.tsx#L15-L31

**Comment by kaminion** [comment]
@e8panse how to solve problem? could you help me?
I have same issue

**Comment by e8panse** [comment]
@kaminion We gave up using nteract and wrote full communication part and representation UI by ourselves. It's easier than to use nteract in our case. From all this experience I can tell that integrating nteract into next.js app much easier than into CRA.

**Comment by kaminion** [comment]
@captainsafia @e8panse I solved to problem,
I fixed configuration of the webpack

I added the resolve part of the webpack and modified the exclude of ts-loader.
it works well even in the react-client-app.

```
// webpack.common.js
const configurator = require('@nteract/webpack-configurator');


resolve: {
        alias: {
            ...configurator.mergeDefaultAliases(),
            react: path.resolve('./node_modules/react'),
            "react-dom": path.resolve('./node_modules/react-dom'),

        },
test: /\.tsx?$/,
exclude: path.resolve(__dirname, '/node_modules/'),
```

And lodash-isequal issue was fixed to install lodash.isequal module

ts-compile reference Link : http://blog.timwheeler.io/webpack-and/
