### ISSUE TITLE
Correct the failing tests

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#5506]
I believe that I have Electron running in CI. Now, we should correct failing tests or skip them temporarily.

<img width="855" alt="Screen Shot 2021-04-15 at 10 59 04 PM" src="https://user-images.githubusercontent.com/2680980/114978771-959a2400-9e3e-11eb-89f4-425e6eafe4b3.png">

**Comment by captainsafia** [comment]
Which tests are failing?

**Comment by willingc** [comment]
Closing this since the latest changes to CI has resolved these.
