### ISSUE TITLE
Fatal Error after Split Cell + Delete

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#552]
I don't know the actual name of the icon but to reproduce this error.
1. Start the notebook
2. Press the 'split cell' button of the toolbar for a cell (first time this is pressed this outputs a warning to the notebook:

```
Failed prop type: Required prop `outputStatus` was not specified in `CodeCell`.
    in CodeCell (created by Cell)
    in Cell (created by CellContextMenuLayer)
    in div (created by CellContextMenuLayer)
    in CellContextMenuLayer (created by DraggableCell)
    in div (created by DraggableCell)
    in div (created by DraggableCell)
    in DraggableCell (created by DropTarget(DraggableCell))
    in DropTarget(DraggableCell) (created by DragSource(DropTarget(DraggableCell)))
    in DragSource(DropTarget(DraggableCell)) (created by Notebook)
    in div (created by Notebook)
```

and

```
home/jdetlefs/github/nteract/build/notebook/components/cell/code-cell.js:47
Uncaught TypeError: Cannot read property 'get' of undefined
```
1. Press the 'delete' button.
2. You should see a draggable box that you can type in like this: 
   ![bug](https://cloud.githubusercontent.com/assets/10944582/17048204/f0c08418-4f98-11e6-8ef0-09bc0d4da473.png)
3. Attempting to delete the cell outputs NO error or message to the console:
4. Attempting to get a new markdown or code cell (in this case code) throws an error:

```
/home/jdetlefs/github/nteract/build/notebook/components/cell/code-cell.js:47 
Uncaught TypeError: Cannot read property 'get' of undefined
```

**Comment by jdetle** [comment]
This problem is fixed when
1. a user first presses hide  however many times they want
2. a user then presses the up arrow on the until no more cell space is hidden
3. a user deletes when all cell contents are shown

**Comment by jdetle** [comment]
#537, https://github.com/nteract/commutable/pull/41 might be relevant?

**Comment by captainsafia** [comment]
I've got the solve for this in an ongoing PR.
