### ISSUE TITLE
Use pyodide in nteract web

### ISSUE THREAD

**Issue by benabel** [nteract/archived-desktop-app#5531]
Hi dear nteract developers, sorry to disturb you in your work.

I would like to easily share playable notebooks with my students in a static site. I've tested the web application in this repo that seems really promising.

However I have already experienced issues with binder when used in a classroom with poor internet connections.

I'd like to know if you think it's possible to integrate [pyodide](https://pyodide.org/en/stable/index.html) as an option to run code inside the browser.

I tried to look at the code but I can't figure how to use the `notebook-app-component` from a given `ipynb` file.

Any help would be really appreciated.

**Comment by captainsafia** [comment]
Thanks for sharing this idea, @benabel.

At the moment, the notebook-app-component is a React component that is intended to be used within Javascript-based applications. Technically, it is possible to build a notebook UI that uses pyodide to provide the kernel execution support but that's not something nteract provides support for out of the box.

At the moment, we're still targeting running Jupyter notebooks where the kernel is executing on a virtual machine/Docker container/etc.

**Comment by benabel** [comment]
Thanks for your quick reply, I'll investigate in [jupyterlite](https://github.com/jtpio/jupyterlite).
