### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by anton-petrov** [nteract/archived-desktop-app#5536]
Hi! When is the next release expected? Best regards ;)

**Comment by willingc** [comment]
Hi @anton-petrov, It looks like 0.29 is available [here](https://github.com/nteract/nteract/releases/tag/nteract%400.29.0).

@captainsafia Is there another step that we need to take to get the packages for 0.29 out?

**Comment by anton-petrov** [comment]
<img width="1301" alt="Screenshot 2021-05-07 at 09 31 22" src="https://user-images.githubusercontent.com/2428315/117407789-bb838780-af17-11eb-8c87-d20bb8cd4cdf.png">

**Comment by captainsafia** [comment]
@anton-petrov Yeah, there hasn't been a desktop release because there haven't been any code changes that affect the desktop app that needed to be shipped out.
