### ISSUE TITLE
Importing compiled code for editors in notebook app component

### ISSUE THREAD

**Issue by pragyagarg642** [nteract/archived-desktop-app#5543]
In nteract notebook-app-component, for loading the editors, uncompiled versions of the packages are being used instead of compiled version. In a react app (without nextjs), it errors out saying "Module parse failed: the keyword 'interface' is reserved". Is there any reason as to why this is being done and is it possible to use compiled code (JS files) instead of uncompiled one?

Additional context
Package: notebook-app-component
[Referred code](https://github.com/nteract/nteract/blob/6ab7f80b3c7f4172dcb815dd9bff85561eb4b1fb/packages/notebook-app-component/src/decorators/editor-loader/index.tsx#L18)

Thanks!

**Comment by captainsafia** [comment]
Yes, this is part of a feature that will attempt to either load the CodeMirror or Monaco editor depending on what the app has been configured with.

This feature relies on Webpack's chunking support so you'll need to make sure that you're NextJS app is configured to support it correctly.

**Comment by kaminion** [comment]
how to solve problem? could you please help me?
