### ISSUE TITLE
Last nteract/commutable release has the wrong version number

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#5571]
It looks like commutable regressed in version number

![image](https://user-images.githubusercontent.com/836375/121713266-8677d100-ca91-11eb-91ee-d55249103155.png)

That or v1 was _also_ published due to automation. It's weird there's not an update to the package number though.

**Comment by captainsafia** [comment]
This was my fault. v1 got published due an issue with the new automation I was setting up. It wasn't reading the correct git tag format so it thought a new v1.0.0 release was due. I think we'll have to go through and remap what "latest" points to.

As for writing the versions back to the file, that's another change I need to make using the semantic-release/git extension.

**Comment by rgbkrk** [comment]
Strange, it happens. For what it's worth, this was the only package I ran across that had this issue.

**Comment by captainsafia** [comment]
Fixed now!
