### ISSUE TITLE
Linux distribution has no image for nteract shortcut.

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#559]
The title is self explanatory. Running `npm run dist:linux64` does not appropriately give the nteract shortcut its (very pretty) logo. I'm going to go ahead and try to fix this.

**Comment by jdetle** [comment]
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon

:( icon in the file manager is not yet supported.

**Comment by rgbkrk** [comment]
At the very least, you can add the icon for our `new BrowserWindow` call following the [native image](http://electron.atom.io/docs/api/native-image/) doc. You'll want to case it off so that on windows it uses the `.ico` and on linux it uses `.png` (or so I suspect).
