### ISSUE TITLE
Set up security.md policy for vulnerabilities

### ISSUE THREAD

**Issue by willingc** [nteract/archived-desktop-app#5603]
Let's set something up for where folks should report possible vulnerabilities.

**Comment by Anubha13kumari** [comment]
hi @willingc .first timer this side .i want to contribute on this issue please guide me .

**Comment by willingc** [comment]
Hi @Anubha13kumari, Sorry I missed your message when I was on vacation. Please read our CONTRIBUTING.md guide which should help you get started on finding an issue and making your first contribution. :sunny:
