### ISSUE TITLE
Add kotlin-jupyter kernel

### ISSUE THREAD

**Issue by holgerbrandl** [nteract/archived-desktop-app#5634]
It would be great if nteract could also support https://github.com/Kotlin/kotlin-jupyter

https://nteract.io/kernels could/should detail out how to setup the kotlin kernel so that is shows up in nteract.

**Comment by willingc** [comment]
Hi @holgerbrandl.

Great suggestion. The place to add this detail would be in the nteract.io repo [here](https://github.com/nteract/nteract.io/blob/main/pages/kernels.js) and in its `components/kernels` folder.

I would be happy to review any PR to that repo if you wish to make one. Just @-mention me there.

**Comment by holgerbrandl** [comment]
Could you @ileasile maybe create/delegate such a PR in your team?

**Comment by willingc** [comment]
Thanks @holgerbrandl. Pretty cool project that you have [here](https://github.com/holgerbrandl/kravis) too. FYI @emeeks. 

:wave: @ileasile Welcome and nice that the kernel is being worked on.

**Comment by ileasile** [comment]
@holgerbrandl @willingc I've made a PR
