### ISSUE TITLE
Address weird markdown cell duplication bug

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#564]
There is a weird thing that happens where markdown cells are duplicated. This doesn't seem to be a React bug as the cells are duplicated in the actual `cellMap` in the state.

This doesn't happen with code cells as far as I can tell.

EDIT: Looks like this happens with code cells too.

**Comment by rgbkrk** [comment]
Interesting. Any way of pulling this up?

**Comment by captainsafia** [comment]
This should be fixed now that we've moved copy-paste logic into the Notebook component. This means that the cell copy-paste key will not be inadvertently triggered when the person is typing in the cell.

We can close this for now and re-open if the issue persists for whatever reason.
