### ISSUE TITLE
Fix issue where long-open notebook doesn't save

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#565]
Don't ask me how I found this bug, but it appears that if a notebook is open for a long time some bug occurs where in the notebook does not save.

**Comment by rgbkrk** [comment]
If something fails catastrophically, it seems like reductions stop happening. We need some "oh shit" mode here.

**Comment by captainsafia** [comment]
I'll have to check again if this fails now that we've refactored save as into an epic.

**Comment by captainsafia** [comment]
Closing because I haven't been able to reproduce this.
