### ISSUE TITLE
CodeCell: "Warning: React.createElement: type should not be null, undefined, boolean, or number"

### ISSUE THREAD

**Issue by gnestor** [nteract/archived-desktop-app#576]
To reproduce:
- Clone repo
- `npm install`
- `npm start`
- Open `intro.ipynb`

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `CodeCell`.
```

![image](https://cloud.githubusercontent.com/assets/512354/17337769/1b74f564-5899-11e6-94d8-1bb93a2a064c.png)

**Comment by captainsafia** [comment]
Hi! Thanks for opening the issue. I couldn't reproduce this on my fresh clone of nteract.

When you start nteract does the window with a new notebook open up properly? Also, what version of Node are you on?

**Comment by gnestor** [comment]
Ya I get this for both the "new" notebook and the `intro.ipynb`. I'm running Node 6.3.

**Comment by captainsafia** [comment]
Bother — still can't reproduce. Something seems to be up with the way that `CodeCell` is imported. Did you get any Babel related errors when building?

**Comment by gnestor** [comment]
I wiped `node_modules` and installed from scratch and the error is gone! @captainsafia Thanks for looking into this...

**Comment by rgbkrk** [comment]
Yay, thanks!
