### ISSUE TITLE
Port from thunkservables to Epics

### ISSUE THREAD

**Issue by jayphelps** [nteract/archived-desktop-app#579]
redux-observable [switched to using Epics over thunkservables](http://redux-observable.js.org/docs/FAQ.html#why-were-thunkservables-deprecated) a little while back. We've since added [fairly decent docs](http://redux-observable.js.org/docs/basics/Epics.html) on these. Epics are a function that takes a stream of actions in and returns a stream of new actions out. The tl;dr is that instead of dispatching a thunk that returns an observable, you dispatch regular POJO actions and listen for them in process managers called Epics which can then do your side effects in response and then they emit other actions when they're done with any response or signal.

I briefly looked through the nteract source and found two thunkservables as examples, [save/saveAs](https://github.com/nteract/nteract/blob/master/src/notebook/actions/index.js#L57).

They would be ported over to something _like_ this (untested...sorry!):

``` js
// Extracted out for readability, but you don't have to or you can use
// something like the rxjs-fs package
const writeFileObservable = (filename, data, ...args) =>
  Observable.create(observer => {
    fs.writeFile(filename, data, ...args), error => {
      if (error) {
        observer.error(error);
      } else {
        observer.next({ filename, data });
        observer.complete();
      }
    });
  });

const SAVE = 'SAVE';
const SAVE_AS = 'SAVE_AS';

const changeFilename = filename => ({ type: CHANGE_FILENAME, filename });
const save = (filename, notebook) => ({ type: SAVE: filename, notebook });
const saveAs = (filename, notebook) => ({ type: SAVE_AS: filename, notebook });
const doneSaving = () => ({ type: DONE_SAVING }); 

const saveEpic = actions =>
  actions.ofType(SAVE)
    .do(action => {
      // If there isn't a filename, save-as it instead
      if (!action.filename) {
        throw new Error('save needs a filename');
      }
    })
    .mergeMap(action =>
      writeFileObservable(filename, JSON.stringify(commutable.toJS(action.notebook), null, 1))
        .map(doneSaving)
        // .startWith({ type: START_SAVING })
        // since SAVE effectively acts as the same as START_SAVING
        // you could just look for that in your reducers instead of START_SAVING
    );

const saveAsEpic = actions =>
  actions.ofType(SAVE_AS)
    .mergeMap(action => [
      changeFilename(action.filename),
      save(action.filename, action.notebook)
    ]);
```

I wish I could port everything over but I lost fairly quickly without diving super deep into how everything works. Instead, I'm happy to answer any questions you all may have and/or actually pair with one of you.

Since thunkservables are deprecated, we'd like to remove support for them ASAP so that people who can use other middleware together with it, like redux-thunk.

As a side note, your existing thunkservables don't seem to `(subscriber|observer).complete()` so the middleware's subscription will never finish so that might be a memory "leak".

---
## Remaining thunkservables to convert to epics
- [x] `save` #599
- [x] `saveAs` #599 
- [x] `newKernel` #605
- [x] `setNotebook` #609
- [x] `executeCell` #611

**Comment by captainsafia** [comment]
Thanks, @jayphelps! This has been on our radar since we made some upgrades in #571 but we haven't had the chance to get around to it. Your comment is really helpful. I'll work on taking some of your insights into a clean and tested PR and ping you on it for review/pairing.

🎉

**Comment by rgbkrk** [comment]
Are you suggesting https://github.com/trxcllnt/rxjs-fs or a different one?

Tackling this now that I've done a separate project with redux-observable and proper epics+actions.

**Comment by jayphelps** [comment]
@rgbkrk sorry, I should have checked first. It appears rxjs-fs hasn't been touched in years and depends on v4 instead of v5. There isn't any maintained alternative I can find. It's fairly simply to implement something similar to what I showed with `writeFileObservable`. You also don't really need to do that, just thought it was probable you would need to read/write multiple times in different places.

**Comment by rgbkrk** [comment]
This is now all done!

**Comment by rgbkrk** [comment]
Thanks again @jayphelps, filing this gave me the direction and extra motivation to finish this off quickly.

**Comment by jayphelps** [comment]
@rgbkrk AWESOME!!! 👯 nice work.
