### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#59]
We should start packaging this for pre-pre-pre-alpha releases to at least figure out a bit of the flow. Some things we'll need:
- [x] Icons!
- [x] Metadata about the built application across the other platforms

**Comment by rgbkrk** [comment]
Nice mini-tutorial/how-to for [Releasing for Windows](http://jbavari.github.io/blog/2015/09/09/releasing-electron-for-windows/).

**Comment by betatim** [comment]
I think for pre-pre-pre-alpha it is too early to try and work out how to bundle a kernel, but maybe for pre-pre-alpha that would be cool. I did a bit of searching for this and got the feeling that it is impossible to bundle this directly with the electron app :cry: so we would need an installer.

**Comment by rgbkrk** [comment]
Makes sense. We can package just the main app right now and rely on Jupyter kernels being installed. It would not be hard (or so I assume) to package ijavascript as a "bundled" kernel.

**Comment by rgbkrk** [comment]
This has since been done. Updating the top to reflect what we've done.

For auto-update, we'll want to hook into squirrel.
