### ISSUE TITLE
Prior Cell Art

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#60]
People have iterated on the cell design quite a few times.

There's the classic IPython/Jupyter notebook cells:

![screenshot 2016-01-25 10 56 30](https://cloud.githubusercontent.com/assets/836375/12557828/4246d338-c352-11e5-849b-9965cdbe8cc5.png)

In CoLaboratory, they took a lot of approaches that we should look back to, namely
- Cells have their own context menu
- Active and hovered cells are raised up as cards (material design)

![screenshot 2016-01-25 11 05 09](https://cloud.githubusercontent.com/assets/836375/12558058/58b28512-c353-11e5-9b33-7655c94087dd.png)

In https://github.com/jupyter/design/issues/10, the cell is very trim and clean:

![](https://cloud.githubusercontent.com/assets/136521/5786768/7dd7c2b0-9d9f-11e4-9cdb-51a8b43a7d57.png)

**Comment by rgbkrk** [comment]
Animated GIF of colaboratory in action:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/836375/12558829/568fa89c-c357-11e5-94fe-bed815b1af19.gif)

**Comment by rgbkrk** [comment]
Here's an iteration based on feedback from Kayur and Colaboratory's design:

![nteract notebook design](https://cloud.githubusercontent.com/assets/836375/12573323/3a1e7a56-c3bd-11e5-9ab7-0a98068e9c5f.png)

Cells not hovered over or active are flush on the page. That's the first cell you see here.

The second cell is hovered over and is raised slightly.

The last cell is the active one and raised the highest.

Context is king. Next up, the cell context menu.

**Comment by rgbkrk** [comment]
Cell context menu, shown when active in a cell:

![screenshot 2016-01-25 23 30 22](https://cloud.githubusercontent.com/assets/836375/12573198/c2c9d5be-c3bb-11e5-86fe-eaf5230de1bf.png)

That's Play, move cell up, move cell down, and delete.

When a Markdown cell I'd expect it to not have a run button, though it doesn't really hurt anything.

**Comment by rgbkrk** [comment]
Little bit smaller icons:

![screenshot 2016-01-25 23 37 19](https://cloud.githubusercontent.com/assets/836375/12573246/534c2b8c-c3bc-11e5-88c1-7f096bf009a2.png)

**Comment by rgbkrk** [comment]
In case it's not clear from above, those icons are totally from Font Awesome. :smile:

**Comment by rgbkrk** [comment]
![notebook_iterations](https://cloud.githubusercontent.com/assets/836375/12573608/8768e564-c3c0-11e5-9183-21d2430a048f.png)

**Comment by rgbkrk** [comment]
Fonts are the same fonts currently bundled with Composition:
- Source Code Pro
- Source Sans Pro

**Comment by rgbkrk** [comment]
Lowered the blur a bit on the context menu:

![screenshot 2016-01-26 00 09 39](https://cloud.githubusercontent.com/assets/836375/12573640/e18304d0-c3c0-11e5-80a7-123110d79200.png)

**Comment by rgbkrk** [comment]
Now with input numbering!

![numbering nteract](https://cloud.githubusercontent.com/assets/836375/12573780/cd7f7b74-c3c2-11e5-98a6-706bef15ef5e.png)

**Comment by jdfreder** [comment]
Nice!  Why the grey background?

**Comment by rgbkrk** [comment]
Ah, the grey comes from all the current notebook variants. Are you thinking full screen document?

**Comment by rgbkrk** [comment]
![nb_nobackground](https://cloud.githubusercontent.com/assets/836375/12655320/fb516e0c-c5bd-11e5-993e-7ed9b010e2dc.png)

**Comment by rgbkrk** [comment]
Closing now that we have the [UI mocks repo](https://github.com/nteract/mocks)
