### ISSUE TITLE
Configuration file for new notebook

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#622]
One feature that I and plenty of other notebook users would like would be able to write a simple configuration file to populate the first cell of a notebook with the usual imports.

Being able to say `nteract --default` in the command line and have it read from a default configuration file would be nice. For example alot of people might want to specify the first cell to say:

``` python
import pandas as pd
import numpy as np
```

**Comment by captainsafia** [comment]
Actually, this is a duplicate of #180 so closing.
