### ISSUE TITLE
Native right click menu

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#633]
Would we be able to use https://github.com/mixmaxhq/electron-editor-context-menu or implement it ourselves? It uses the same menu templating that our native menus use.

**Comment by captainsafia** [comment]
I like this in the fact that it has optional spell-check integration so we can kill two birds with one stone.

I wonder if we can move our cell-based functions into this menu as well. It looks like you can configure to act on textareas only but you can probably have it run on non-text areas as well.

Let me dig into this more. I think it would be really cool to have our cell functions in a native looking context menu.

**Comment by captainsafia** [comment]
This can be closed since we are no longer using context menus for cell actions.
