### ISSUE TITLE
new untitled notebooks get a kernel but do not record kernelspec

### ISSUE THREAD

**Issue by minrk** [nteract/archived-desktop-app#639]
The empty untitled notebook you get when you launch nteract gets hooked up to a default kernel, but that information doesn't get recorded in notebook.metadata.kernelspec.

**Comment by minrk** [comment]
New notebooks with a specific kernel from the menu get the right info.

**Comment by rgbkrk** [comment]
Done in #649.

**Comment by rgbkrk** [comment]
Thanks for alerting on this one Min, this also addresses the issue with new kernels launched from the "language" menu.
