### ISSUE TITLE
Create a bundled Python kernel

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#65]
We should have a Python kernel installed for users that relies on an Anaconda. Package it up, ship it.

**Comment by rgbkrk** [comment]
This should probably be incorporated as a new nteract project.

**Comment by jdfreder** [comment]
Nammmmmeeees?  
- pybox
- pykernel
- nteract-ipython

**Comment by rgbkrk** [comment]
- `packaged-python`
- `prepack-python3-kernel`
- `prepackaged-python3`
- `packernel`

Yeah I'm not sure. Seems like something we can be somewhat verbose in naming, since it's solely a vehicle for install by nteract.

**Comment by betatim** [comment]
:+1: for `prepack-python3-kernel`

**Comment by rgbkrk** [comment]
@ssanderson totally said he has the best ideas for doing this.

**Comment by rgbkrk** [comment]
Closing, tracking progress in [snakestagram](https://github.com/nteract/snakestagram).
