### ISSUE TITLE
Hover toolbar disappears after cursor exits cell

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#650]
Hi there, I'm opening this issue with the intention of submitting a PR to fix it. 

The current toolbar disappears when the cursor exits a cell, and this has to do with the logic in `cell.js`. I think the best way of fixing this is to change the logic such that we create a boolean `hot === hovered || other cells not hovered over`. 

I'll try to make a PR soon.

**Comment by rgbkrk** [comment]
Sounds like a good way to start approaching it.

**Comment by captainsafia** [comment]
We just got off a call and decided that we'll just make it so that the toolbar is always visible. Additionally, the context menu will be set as a dropdown on the toolbar.

**Comment by rgbkrk** [comment]
> we'll just make it so that the toolbar is always visible

👍 

> Additionally, the context menu will be set as a dropdown on the toolbar.

👍

**Comment by jdetle** [comment]
Closed by #653
