### ISSUE TITLE
Need a way to unhide input when both input hidden and no output

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#668]
If you toggle inputs, on a cell that either has output hidden or no outputs, 

<img width="774" alt="screen shot 2016-09-02 at 8 41 08 am" src="https://cloud.githubusercontent.com/assets/836375/18209553/1eb5c4de-70e9-11e6-9374-7ec26bfedf4c.png">

At first there's the cell menu, mostly as a leftover though

<img width="759" alt="screen shot 2016-09-02 at 8 41 24 am" src="https://cloud.githubusercontent.com/assets/836375/18209551/1e700e4e-70e9-11e6-94c2-5072bc940920.png">

As soon as you focus on another cell though, you can't get that cell back.

<img width="765" alt="screen shot 2016-09-02 at 8 41 39 am" src="https://cloud.githubusercontent.com/assets/836375/18209552/1e93b6f0-70e9-11e6-923a-60f62627ef7c.png">

Suggestions for "fixes":
- Top level menu option to show all
- Some sort of thin representation of the cell when you hover (?)

This probably seems like an edge case of usage - it's not. One of the main reasons to hide input is for others to consume as a whole document with no code (like a report). There will be cells that don't have outputs in those cases (getting data ready, etc.).

**Comment by aleury** [comment]
Hi, I'd love to help out with this for my first PR. 

A thin representation of the cell would replace `null` on this [line](https://github.com/nteract/nteract/blob/master/src/notebook/components/cell/code-cell.js#L68), right? 

Would you like both of the suggestions for fixes to be implemented? For the thin representation, should the toolbar show up on hover so you can toggle the visibility again? Thanks!

**Comment by rgbkrk** [comment]
> A thin representation of the cell would replace null on this line, right?

Yeah, that's where the thin cell would go.

> Would you like both of the suggestions for fixes to be implemented?

My initial read on this issue is that the menu one is far easier and will be the most stable to deal with. We should have the menu option no matter what - it's a failsafe with a single event to unhide everything.

> For the thin representation, should the toolbar show up on hover so you can toggle the visibility again?

Yeah, I think so. I'm not sure of the best approach -- it's ok to iterate on the design.

**Comment by aleury** [comment]
Awesome. I'll get to work on this and will write back if I get stuck on anything.

**Comment by aleury** [comment]
The main change I'm a little concerned with is in the [test utility file](https://github.com/nteract/nteract/pull/905/files#diff-ff2899c03c9e8e31a9b69d7621e08c83R30). I needed the `emptyCodeCell` to be initialized as hidden so my test could pass. Is there a better way to do this from inside the test case, or do you think it's okay?

**Comment by captainsafia** [comment]
> The main change I'm a little concerned with is in the test utility file. I needed the emptyCodeCell to be initialized as hidden so my test could pass. Is there a better way to do this from inside the test case, or do you think it's okay?

I think you meant to post this in the PR. If so, I answered this question there. 😄

**Comment by aleury** [comment]
Oh sorry about that!
