### ISSUE TITLE
Dropdown menu should respect/use theming CSS variables

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#669]
<img width="235" alt="screen shot 2016-09-02 at 8 47 43 am" src="https://cloud.githubusercontent.com/assets/836375/18210211/44783fdc-70ec-11e6-912f-eaf995794079.png">

I'm guessing it's using them, just needs some love for the dark theme.

**Comment by jdetle** [comment]
Oh, this should be relatively simple fix but it totally didn't occur to me when writing the CSS styling.

**Comment by jdetle** [comment]
@rgbkrk this should be taken care of?

**Comment by rgbkrk** [comment]
You're right, this is handled across all the themes. We can close this issue.

It still seems a bit off, in terms of typography and outline.

<img width="226" alt="screen shot 2016-09-14 at 4 25 12 pm" src="https://cloud.githubusercontent.com/assets/836375/18533466/d8b86334-7a97-11e6-934f-21c479dfe19b.png">

That's a further refinement though.

**Comment by rgbkrk** [comment]
What jumps out at me is that the borders don't match the soft glow of the cells and the menu is pure white.

**Comment by jdetle** [comment]
I can fix the menu being pure white, I don't want to add a shadow, but I'm open to suggestion to fixing the borders. cc @captainsafia

**Comment by rgbkrk** [comment]
Try borderless
