### ISSUE TITLE
Add slides options

### ISSUE THREAD

**Issue by juanfcocontreras** [nteract/archived-desktop-app#698]
Is it possible to add slide options to cells: slide, sub-slide, fragment...?

**Comment by rgbkrk** [comment]
I haven't looked into it yet, worth investigating a design for it here.

**Comment by juanfcocontreras** [comment]
Great! Thanks and congrats for the app!

**Comment by captainsafia** [comment]
@kenwheeler and I briefly discussed exporting Notebook documents to [Spectacle](https://github.com/FormidableLabs/spectacle), a presentation tool.

Markdown cells would be exported as Spectacle `Slide` component with the Markdown converted appropriately to JSX. Code cells would be exported as [`CodeSlide` components](https://github.com/thejameskyle/spectacle-code-slide).

It's not exactly what you are asking for but it's an idea that's been thrown out regarding getting presentation formats out of nteract.

**Comment by juanfcocontreras** [comment]
While @captainsafia approach is great, I think it could take longer to implement.

Meanwhile, "default" approach (together with reveal.js) could be just adding the following metadata to the notebook cells:

<pre>
   "cell_type": "...",
   "metadata": {
<b>    "slideshow": {
     "slide_type": "slide" (or subslide, fragment...)
    }</b>
   },
   "source": [...]
</pre>

**Comment by rgbkrk** [comment]
We respect the metadata if it was already on a notebook document, we don't have any UI to control it though.

**Comment by juanfcocontreras** [comment]
That was exactly my feature request, to have a simple dropdown component to add slide metadata information to cells (like Jupyter notebooks standard UI).

**Comment by rgbkrk** [comment]
Cool, yeah, we're certainly open to having the slides.
