### ISSUE TITLE
Refactor sticky cell

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#701]
Sticky cell is currently using some deprecated or unsavory bits of the React APIs, namely string-refs and `ReactDOM.findDOMNode`.

**Comment by aleury** [comment]
I made a PR for this where the sticky cell string refs were replaced with callback refs since string refs will likely be deprecated at some point in [future](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute).

**Comment by rgbkrk** [comment]
:tada: Thank you @aleury!
