### ISSUE TITLE
Move cellStatuses attributes to cells under cellMap

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#713]
The attributes stored in the top-level cellStatuses object should be stored in each cell at the cellMap level.

**Comment by rgbkrk** [comment]
Note: we'll also need to make sure these don't end up in the serialized notebook (on disk).

**Comment by captainsafia** [comment]
> Note: we'll also need to make sure these don't end up in the serialized notebook (on disk).

Most def.
