### ISSUE TITLE
[Request for Design] New or renamed file should ask about launching new kernel on save

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#721]
Right now if we rename a file (or save a new one in some location), the kernel is using the previous working directory. We likely want to launch a brand new kernel.

How should we give users a choice?

**Comment by captainsafia** [comment]
I think using a dialog box should do the trick.

```
It looks like you've saved your notebook file to a new location. The kernel 
executing your code thinks your notebook is still in the old location. Would 
you like to relaunch the kernel to synchronize it with the new location 
of your notebook?

[Don't Relaunch Kernel]     [Relaunch Kernel]
```

What are your thoughts on the explanatory text in this case?

**Comment by rgbkrk** [comment]
I like that text!

**Comment by rgbkrk** [comment]
Maybe swap:

> relaunch the kernel to synchronize it with the new location of your notebook?

with

> launch a new kernel to synchronize it with the new location of your notebook?

**Comment by captainsafia** [comment]
> launch a new kernel to synchronize it with the new location of your notebook?

Good point! Especially since it is not actually relaunching a kernel.

**Comment by rgbkrk** [comment]
Aiming for simple language, another revision:

> launch a new kernel to match it with the location of your notebook?

**Comment by rgbkrk** [comment]
> launch a new kernel to match the directory with that of your notebook?

**Comment by captainsafia** [comment]
I think "launch a new kernel to match it with the **new** location of your notebook?" works best.

**Comment by rgbkrk** [comment]
ok awesome, that looks great

**Comment by captainsafia** [comment]
Great! PR inbound!
