### ISSUE TITLE
File path type ahead max-width is a little bit too short

### ISSUE THREAD

**Issue by chriddyp** [nteract/archived-desktop-app#734]
It looks like there might be max-width on the type-ahead options:

![screen shot 2016-09-12 at 11 25 11 am](https://cloud.githubusercontent.com/assets/1280389/18441619/c085ba5e-78db-11e6-9f84-84829e6e78bf.png)

**Comment by rgbkrk** [comment]
Yuck.

The CSS part is definitely new contributor friendly.

The long term typeahead fixes likely are not as they involve either a custom component (might be the wisest) or digging deeply into CodeMirror.

**Comment by captainsafia** [comment]
> The long term typeahead fixes likely are not as they involve either a custom component (might be the wisest) or digging deeply into CodeMirror.

Wanna open another issue for the this?

**Comment by rgbkrk** [comment]
I've done the digging into the long term typeahead fixes and worked with a coworker on helping him patch this. Hopefully we'll see something soon.
