### ISSUE TITLE
overflow-y:scroll on output cells

### ISSUE THREAD

**Issue by chriddyp** [nteract/archived-desktop-app#735]
It looks like the output cells might be missing something like `overflow-y: scroll` causing big outputs (like tables) scroll across the app instead of the cell:
![overflow](https://cloud.githubusercontent.com/assets/1280389/18441860/914183c6-78dc-11e6-876a-88806ef61072.gif)

**Comment by captainsafia** [comment]
Huh. Are you running on the latest master? I pushed what should have been a fix for this in #711.

**Comment by chriddyp** [comment]
Oh woops, sorry! I'm running on the latest release but not on the latest master.

**Comment by rgbkrk** [comment]
Luckily I'll be shipping a new release today!

**Comment by captainsafia** [comment]
@chriddyp: Let me know if you can still reproduce on master, otherwise I'll close.

**Comment by chriddyp** [comment]
![image](https://cloud.githubusercontent.com/assets/1280389/18518184/fda83d5c-7a6c-11e6-8a13-564042305289.png)
looks good! thanks!
