### ISSUE TITLE
Conformance testing for beta app

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#737]
We need to run our app through some set of conformance tests with current notebooks to ensure sanity. We have [notebook test data](https://github.com/nteract/notebook-test-data).

Some component of this can be automated, but we also need to have people load a variety of notebooks to see how well they work.

**Comment by captainsafia** [comment]
Good thing I have a minion army!

![](https://media1.giphy.com/media/mPOGx4hJtOWSA/200_s.gif)

**Comment by captainsafia** [comment]
I figured I would add the Hacktoberfest tag to this to leverage the collective power of the OS community.

It would be great to have someone download our latest alpha releases, or build the software from scratch, whichever they're comfortable with and try to find bugs.

**Comment by rgbkrk** [comment]
We now have a conformance test that runs on Travis and our further flow typing is ensuring consistency at build time (at the very least). I'll go ahead and close this for now.
