### ISSUE TITLE
Support STDIN

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#741]
<img width="798" alt="screen shot 2016-09-12 at 11 33 52 pm" src="https://cloud.githubusercontent.com/assets/836375/18463792/678457ce-7941-11e6-9440-196b4f3ec631.png">

**Comment by andyndang** [comment]
Support for stdin() is crucial to support interactive debugging in IPython (using `%%debug` magic or `.set_trace()` approach)

**Comment by rgbkrk** [comment]
`stdin` support is now on master!
