### ISSUE TITLE
JupyterLab plugin

### ISSUE THREAD

**Issue by mangecoeur** [nteract/archived-desktop-app#756]
Just leaving this idea here: JupyterLab looks to be where Jupyer development is going. Currently (AFAIK) it uses the regular Jupyter notebook as a plugin to display notebook files. It seems to me that the notebook rendering part of nteract could be potentially be used as a plugin within the JupyterLab environment.

No while all projects involved are pretty new it's maybe a bit early, but perhaps it's worth keeping in mind to avoid actively making this _impossible_ even if not putting too much effort into making is possible right now. It's also important to maximise the overlap of developers to make sure things can stay supported - I speak as someone who tried a couple of jupyter/ipython desktop integration approaches and so a appreciate the effort involved (https://github.com/mangecoeur/ipython-desktop, https://github.com/mangecoeur/jupyter-chrome )

**Comment by rgbkrk** [comment]
Hey there! Great to hear your interest.

JupyterLab already has a notebook plugin. What does nteract's notebook solve that is not addressed in JupyterLab's notebook?

**Comment by mangecoeur** [comment]
The JupyterLab currently uses the 'vanilla' jupyter notebook. The thinking here is that through the effort of making nteracts notebook compatible with JupyterLab, this could help avoid a divergence between the two notebooks and surface issues in their respective APIs. This is particularly relevant to notebook extensions and JS widgets such as plotting tools (plotly, bokeh). Additionally, it might simply be nice to use nteract everywhere - it does benefit from a much more modern architecture than the Jupyter notebook for example.

**Comment by hadim** [comment]
A naive question : would it make any sense for nteract to actually ship jupyterlab ? Or am I totally wrong here ?

**Comment by jdetle** [comment]
Hi @hadim! I'm not exactly sure what you mean, but it would be difficult to integrate nteract components with Jupyterlab components, because nteract uses react and corresponding libraries in the react ecosystem, while Jupyterlab uses a similar-but-different library called PhosphorJS.

**Comment by rgbkrk** [comment]
The nteract desktop app's primary goal is to only serve as an editor for notebook files. This means that you have to use a text editor for your non-notebook scripts, a native terminal for the terminal experience, and your native OS file manager for navigating.

If you want a desktop app for JupyterLab itself, you should push for them to make an Electron app or lend a hand with them to package up an Electron app (what nteract relies on).

**Comment by hadim** [comment]
Ok it makes more sense now. Thank you for the clarification !

(And great work by the way)

**Comment by rgbkrk** [comment]
Closing since we're heading towards a path for shipping the components for a web app version (see #1346), which someone can use to build a jupyterlab plugin.
