### ISSUE TITLE
Relicense as Mozilla Public License v2

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#76]
In following with [C4.1](http://rfc.zeromq.org/spec:22), I'd like to propose that we relicense composition to [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/). 

In order to do this, I'd need a 'yay' from each contributor to relicense your contributions as MPLv2:
- [X] @rgbkrk
- [x] @kenwheeler  
- [x] @karissa 
- [x] @phfrohring 
- [x] @captainsafia 
- [x] @jdfreder 

Please let me know a yay or nay as soon as you can.

**Comment by jdfreder** [comment]
:heavy_check_mark:

**Comment by captainsafia** [comment]
![giphy-25](https://cloud.githubusercontent.com/assets/1857993/12805381/7ac4ba34-cac0-11e5-905f-0625ffc2e69d.gif)

**Comment by ghost** [comment]
![yes](https://cloud.githubusercontent.com/assets/10885649/12808163/2751ab50-cb15-11e5-9d51-12aa57d499ea.gif)

**Comment by okdistribute** [comment]
+1

**Comment by kenwheeler** [comment]
Yay
