### ISSUE TITLE
Enforce 2FA on all nteract members

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#760]
Hey all @nteract, I'd like to enforce 2FA for the entire org within the next week. Please setup 2FA for the sake of our users and our overall sanity. If you don't, you will (sadly 😢 ) be booted from the org until after you setup 2FA.
- [About GitHub 2FA](https://help.github.com/articles/about-two-factor-authentication/)
- [Security settings page](https://github.com/settings/security)
- [What it's like to be targeted](http://www.kennethreitz.org/essays/on-cybersecurity-and-being-targeted)

**Comment by jdetle** [comment]
More useful links 
- [using a token to authenticate commits](https://gist.github.com/wikimatze/9790374)
- [Verify your commits using GPG](https://help.github.com/articles/generating-a-gpg-key/)

**Comment by rgbkrk** [comment]
Whoa, whoa that's above and beyond man.

**Comment by slavaGanzin** [comment]
nobody should use neither HTTPS nor passwords. ssh keys are more secure.

Thanks f

**Comment by jdetle** [comment]
Confused with the negations going on here.... 😁

**Comment by rgbkrk** [comment]
GPG and 2FA are completely unrelated.

2FA is for login verification.

**Comment by rgbkrk** [comment]
This has now been done.
