### ISSUE TITLE
Hide scrollbars in output cell automatically

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#769]
Minor CSS thing:
<img width="792" alt="bildschirmfoto 2016-09-15 um 08 58 31" src="https://cloud.githubusercontent.com/assets/13285808/18541025/d86f47c2-7b22-11e6-968c-3e4c9d1568a3.png">
If the system preferences are not set to hide the scrollbars automatically, they appear in nteract even if there's nothing to scroll. This is also the default behavior on linux.

**Comment by rgbkrk** [comment]
Oh that's the extra jank I'm seeing on the outside of the map in #770.

**Comment by rgbkrk** [comment]
This was fixed recently wasn't it?

**Comment by rgbkrk** [comment]
Yeah this was totally fixed.
