### ISSUE TITLE
Style scrollbars according to theme

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#771]
[It can be done](https://css-tricks.com/custom-scrollbars-in-webkit/) and certainly needs to for the dark theme.

**Comment by prafful002** [comment]
@rgbkrk may I have this assigned to me ?

**Comment by rgbkrk** [comment]
@prafful002 Since you've posted the same across several issues - pick one, make a pull request, then we close the issue.

**Comment by prafful002** [comment]
@rgbkrk sure !

**Comment by kosmastsk** [comment]
Is this issue still open?

**Comment by rgbkrk** [comment]
Yes

**Comment by jkornblum** [comment]
Can be closed with pr #1184

**Comment by rgbkrk** [comment]
Thanks again @jkornblum!
