### ISSUE TITLE
packaged application ignores first argument of `argv`

### ISSUE THREAD

**Issue by darthoctopus** [nteract/archived-desktop-app#776]
After running `npm run dist`, the finished binary file ignores the first argument of `argv`. To open an ipynb file from argv I have to invoke `nteract dummy_argument thing.ipynb`

**Comment by captainsafia** [comment]
Hi! Thanks for opening this issue @darthoctopus. We've experienced something like this before and thought we had fixed it, but it looks like it might've popped back up again.

Are you currently running off the latest alpha?

**Comment by darthoctopus** [comment]
yup! on further inspection seems to have some overlap with #548, which remains open. My bad, sorry for duplicating :(

**Comment by captainsafia** [comment]
> yup! on further inspection seems to have some overlap with #548, which remains open. My bad, sorry for duplicating :(

No worries at all! We "fixed" the issue that you reference but there have been several changes to our launch process then so I suspect this new/old problem is a result of those changes.

I'll see if I can get a fix in for this in the next alpha.

**Comment by jdetle** [comment]
Thanks for pointing this out @darthoctopus!

**Comment by captainsafia** [comment]
We've fixed this in the current release (0.0.11) via #783 so I'll close this.
