### ISSUE TITLE
Internationalization of text

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#78]
![screenshot 2016-02-05 14 00 26](https://cloud.githubusercontent.com/assets/836375/12857618/d3c18396-cc10-11e5-9833-f9c3ae8c8a96.png)

As we progress, we should take some time to think about how we do internationalization of text. The current way that people appear to be doing this in React apps is with [react-intl](https://github.com/yahoo/react-intl), which relies on [formatjs](http://formatjs.io/). There are standard APIs for the easy ones:

```
> new Intl.NumberFormat().format(1000.0)
"1,000"
```

It's the string messages that I'm not sure of. What I do know we have to do is make it easy for others to provide translations as PRs. Seems like people are used to JSON files with things like templated dialog messages, etc. for all the languages. @twistedhardware suggested that there may be translations available for a lot of common things like `File`, `Edit`, etc.

Within jupyter/notebook, @twistedhardware is putting together an enhancement proposal for the current Tornado app and templates. We should make sure to learn from both efforts.
## Related resources
- [formatjs](http://formatjs.io/)
- [react-intl](https://github.com/yahoo/react-intl)
- [Video on Formatting with Format.js + react-intl](https://www.youtube.com/watch?v=Sla-DkvmIHY)

**Comment by rgbkrk** [comment]
Glaring omissions (on purpose, for scope):
- Keyboards
- Layouts (e.g. languages that flow right to left)

**Comment by rgbkrk** [comment]
Since I wasn't sure myself, I looked up [the definitions and difference between localization and internationalization](https://www.w3.org/International/questions/qa-i18n).

> **Localization** refers to the **adaptation** of a product, application or document content to meet the language, cultural and other requirements of a specific target market (a locale).
> 
> **Internationalization** is the design and development of a product, application or document content that **enables** easy localization for target audiences that vary in culture, region, or language.

**Comment by TwistedHardware** [comment]
@rgbkrk This is correct. regarding keyboard, is not something you should worry about. For any person who uses any other language, the keyboard sends the signals for which key is pressed and it doesn't care what language the user wants to how. This is an example of an Arabic keyboard:

http://www.buypcsupplies.com/images/cat/38558_xlargenss_ndo4203.jpg

Actually your OS takes care of that on its own and maps your keyboard codes to any other language. These is usually a language switch on your screen and/or a keyboard shortcut to to switch languages. This is a screen shot from ubuntu language switch:

http://i.stack.imgur.com/81nDH.png

This the same for all desktop and mobile OS so you really don't have to worry about this.

Regarding your second point about RTL (Right to left) layout, it is easier than what you think.

``` HTML
<body dir="rtl">
```

That's it. You might need to do some extra modifications to your CSS. Or you could even have to separate templates one for RTL and one for LTR.

**Comment by jdfreder** [comment]
One option is to have a set of asset folders.  We could have a common folder, then folders per language.  The loader would pick the correct asset folder and fallback to the common one for things that are missing.  ... this idea may complicate things with WebPack- we would have to have a static map of language name to `require (folder name)`

**Comment by rgbkrk** [comment]
Here at least we're not using webpack (yet), and we have access to the full file system (since it's an Electron app).

I'd love to find out what a common practice is for the messaging, hopefully finding some example JS apps that do this well.

Thanks for showing how easy the initial "rtl" setting is! I really hope we can make this work well for both layouts by default. What's the expectation for how the input cells and output area appears in right to left mode? Are code blocks still left to right? The markdown/text is simple since that should be rtl, love to see a mockup of what you expect.
