### ISSUE TITLE
Too many scrollbars on output

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#788]
Linux:

![image](https://cloud.githubusercontent.com/assets/836375/18612343/2e21806e-7d0c-11e6-8df6-c3c21fbd9503.png)

OS X:

![screen shot 2016-09-18 at 11 18 54 am](https://cloud.githubusercontent.com/assets/836375/18618002/cf35464a-7d91-11e6-881c-6b5051f15a66.png)

**Comment by rgbkrk** [comment]
I seriously need a video recording of cell drag and drop on linux. It's hilarious. It does the strangest thing. As you move the mouse, the `[ ]` get bigger and bigger. It works fine though.

**Comment by rgbkrk** [comment]
Oh you know what, it's not the `[ ]` itself, but the surrounding padding (margin?) around it. The most laughable bug I've seen in nteract so far.

**Comment by rgbkrk** [comment]
Not sure if it matters, but I'm running Linux off a bootable USB drive on a Mac.

**Comment by rgbkrk** [comment]
Oh wait, this is on master for OS X too. Something changed with the CSS.

**Comment by rgbkrk** [comment]
![screen shot 2016-09-18 at 11 18 54 am](https://cloud.githubusercontent.com/assets/836375/18618000/b7c28f9a-7d91-11e6-86c7-b4fcf44461bc.png)

**Comment by lgeiger** [comment]
`overflow: auto` instead of `overflow: scroll` somewhere in the CSS should probably fix this. But you need to make sure you don't break big outputs like #420. A least this is what we did in hydrogen (I think so).

**Comment by captainsafia** [comment]
I think this might have something to do with the "fix" I made in #771 for #420. I think the best setting is probably `overflow-y: auto`.

**Comment by rgbkrk** [comment]
Thanks!
