### ISSUE TITLE
Vertically Scrollable output cells

### ISSUE THREAD

**Issue by chriddyp** [nteract/archived-desktop-app#799]
![scrollable output cells](https://cloud.githubusercontent.com/assets/1280389/18647018/1a6fcc16-7e82-11e6-8f4c-ce91b94d3fa3.gif)

Would be awesome if the output cells had a toggle-able scroll with a `max-width` and `overflow-y: scroll`.

**Comment by rgbkrk** [comment]
Should we do the little output notch that's in Jupyter notebook or something else?

Default to big or default to small and expect the user to expand it?

I lean on the side of full output and a simple way to collapse.

**Comment by captainsafia** [comment]
> I lean on the side of full output and a simple way to collapse.

I actually thinking have a collapsed output and giving someone the ability to expand it is the more intuitive process (and also in line with how the notebook currently functions if I recall).

As a user, I wouldn't want to consume more information from an output unless I had to.

**Comment by rgbkrk** [comment]
As a user, for the tables I work with, I always have to click to expand that. Drives me bonkers, makes me feel constrained.

**Comment by chriddyp** [comment]
> As a user, for the tables I work with, I always have to click to expand that. Drives me bonkers, makes me feel constrained.
> 
> I actually thinking have a collapsed output and giving someone the ability to expand it is the more intuitive process

Yeah, I've definitely felt both ways. Sometimes it's nice to be able to scroll with the page on large outputs (e.g. when your looking for that 1 class method) but other times it's super overwhelming (when you accidently print out all 500k rows of a dataframe).

No strong preference from me.

> Should we do the little output notch that's in Jupyter notebook or something else?

Personally, I think:
- it should be at the top of the cell instead of at the side.
- you should be able to click and drag the height of the cell too

**Comment by rgbkrk** [comment]
> it should be at the top of the cell instead of at the side.

That's what I thought too, but what do you do when you're halfway through a long cell and you "just want it to go away"?

I guess I'd hit "up" and then click the collapse.

**Comment by captainsafia** [comment]
This was addressed in the latest release.
