### ISSUE TITLE
scroll behaviour when you execute a cell

### ISSUE THREAD

**Issue by chriddyp** [nteract/archived-desktop-app#803]
From what I understand, it seems like the notebook will auto-scroll to the next input cell on `shift-enter`.  

There are a couple common scenarios where I find this behaviour pretty frustrating:
- When the output takes more than 200ms to render. Jupyter will scroll to the next input cell, and then the output will render and the view will shift further downwards. This pushes the viewport in between cells which is pretty disorienting. 
- When I actually want to view the output of my cell. I press shift-enter and then I have to actively scroll upwards to see my output.
- When I'm happy with my viewport and I'm re-running the same cell over and over with different inputs. Running a cell isn't "idempotent" from a scroll point of view - I can't run a cell twice and preserve my viewport.

Here is an example:

![scroll-behaviour](https://cloud.githubusercontent.com/assets/1280389/18651185/c040ff42-7e97-11e6-9a13-e8edc7311f21.gif)

What if running a cell didn't adjust the scroll position?

**Comment by rgbkrk** [comment]
Wow. Thank you so much for writing this up with such great detail. I'm extremely frustrated with this behavior too.

> What if running a cell didn't adjust the scroll position?

We could do that. On first pass, that's the easiest for us to do - rip out the current scroll behavior.

Step 2 if we want a version of this that is a little bit more intelligent: We do actually know when outputs will finish coming in for _most_ kernels based on the busy --> idle response from the kernel. The scroll handling is some of our oldest code that hasn't been through a refactor.

**Comment by chriddyp** [comment]
Here's another scroll behaviour that I find a bit disorienting. When I click on a cell, the notebook scrolls to the top of that input cell.

![weird-scroll](https://cloud.githubusercontent.com/assets/1280389/18678740/1143038e-7f2b-11e6-8be3-fd462d800cb8.gif)

Frequently, the output of my previous cell informs the input of the next cell - I like to have the previous output and the next input in the same viewport. In this case, I would prefer if the notebook wouldn't autoscroll and would prefer the viewport that I have set up.

**Comment by captainsafia** [comment]
> Here's another scroll behaviour that I find a bit disorienting. When I click on a cell, the notebook scrolls to the top of that input cell.

I believe this is a consequence of #429 which is on the beta milestone.

**Comment by rgbkrk** [comment]
Thank you so much for reporting these in such great detail. It beats my light reports, so I'll stick this on the beta milestone too.

**Comment by captainsafia** [comment]
@chriddyp: To what extent do expandable outputs (#972 and #1010) and disabling of focus on input (#1055) address this issue?

I suppose the one case where it would still happen is if you have an input expanded that you are rerunning the scroll to next would constantly get you. Hmmm. 🤔

**Comment by chriddyp** [comment]
> To what extent do expandable outputs (#972 and #1010) and disabling of focus on input (#1055) address this issue?

Wow, those are awesome. It seems like there were two issues that I found disorienting:
- Auto-scrolling when executing a cell 
- Auto-scrolling when clicking on a cell

I'm not sure if those issues end up fixing these but 

> if you have an input expanded that you are rerunning the scroll to next would constantly get you

sounds like the behavior that I'm thinking about.

**Comment by rgbkrk** [comment]
Done in #1167.

**Comment by rgbkrk** [comment]
Actually, this discussion has more nuance, re-opening.

**Comment by dhirschfeld** [comment]
***Note:*** In the existing notebook `shift-enter` will execute and move focus to the next cell (possibly creating one in the process) whereas `ctrl-enter` will execute the cell, leaving focus in the same cell but displaying the newly calculated output below.
