### ISSUE TITLE
JS error prevents startup on Applicative Apgar alpha...

### ISSUE THREAD

**Issue by fperez** [nteract/archived-desktop-app#805]
Wanted to take it for a spin, but after downloading the app, once I try to open it I get a window to pop up with this error info (sorry for the screenshot, OSX lets me select the error but not copy it. Boy, do I miss unix-style copy-on-select for text!):

![image](https://cloud.githubusercontent.com/assets/57394/18658609/6ef116e6-7eb9-11e6-88ea-fd9f488de5fc.png)

Am I doing something wrong?

**Comment by rgbkrk** [comment]
Yikes. Definitely not your fault.

That's happening on launch, let me give the release a try again now that I'm on a different machine.

**Comment by jdetle** [comment]
Hi @fperez @rgbkrk , I'm getting the same issue on my end.

**Comment by rgbkrk** [comment]
This release works when you run it from the CLI like `open ~/Downloads/nteract-darwin-x64/nteract.app`, yet not when opened from the icon. Admittedly, that's the only way I tested it after I made the release. 😢

**Comment by rgbkrk** [comment]
This also has an annoying bug of only failing on the first launch from the app icon.

**Comment by fperez** [comment]
Cool! It works if I open it from the cmd line. This looks great, awesome job! I'm going to play with it :)

BTW, kind of ironic that `interact` doesn't work in `nteract` ;)  But I imagine widgets will come later, no rush.

In any case, congrats! Looking forward to continued development.

**Comment by rgbkrk** [comment]
I'd really love to see a spec form from the widgets dedicated to object synchronization from JS <--> kernel before tackling widgets again (we had support for it for a little while then took it out).

**Comment by rgbkrk** [comment]
Basically, I'd love to see widgets carved up in to separate pieces that are currently unsolved specifications:
- Object Synchronization over the messaging protocol
- Frontend asset loading (or expectations)
- UI toolkit

I realize that ipywidgets has an implementation of these, all in one (slightly by necessity), and that there were IPEPs and implementations in flux (as a writer of a custom DOMWidget, I felt that pain).

**Comment by rgbkrk** [comment]
My [current thinking on synchronized objects](https://github.com/rgbkrk/synchronized-object-diff-spec).

**Comment by rgbkrk** [comment]
Wow @jdetle I found out something weird that "explains" what's happening. I went ahead and created a release with some more logging with the arguments and this is what they were:

```
[ '/Users/kylek/Downloads/nteract-darwin-x64/nteract.app/Contents/MacOS/nteract',
  '-psn_0_8046508' ]
```

Only shows up on first launch. It makes me think it's a launchctl thing on OS X. 
¯\_(ツ)_/¯

**Comment by rgbkrk** [comment]
Tempting to go ahead and do a regex to ensure the paths given are sane. We should also be checking that the files exist from the main process too. Anyways, PR incoming.

**Comment by rgbkrk** [comment]
This is [apparently the Process Serial Number](http://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder) and we only see it on first launch.

**Comment by captainsafia** [comment]
I think we can close this now that we have 0.0.12 out?

@fperez — Hope you enjoy trying nteract! 😄
