### ISSUE TITLE
Tabs vs Spaces

### ISSUE THREAD

**Issue by chriddyp** [nteract/archived-desktop-app#808]
I use the tab key instead of the space key for my indentation. It looks like nteract auto-completes with 2-spaces which ends up conflicting with my `\t` tabs.

![tabs](https://cloud.githubusercontent.com/assets/1280389/18680398/89670396-7f31-11e6-9de4-16e1494580fd.gif)

**Comment by rgbkrk** [comment]
Yikes! Thanks. Should we turn our aggressive typeahead off?

Also, if you feel liking daring into our hackery for triggering autocomplete based on change events, it's here: https://github.com/nteract/nteract/blob/master/src/notebook/components/cell/editor/index.js#L106-L115

That's admittedly some of the sketchiest code here, very heuristic driven.

**Comment by chriddyp** [comment]
And a related issue is that pressing `cmd-]` and `cmd-[` (which I use a lot to indent blocks of code) defaults to 2 spaces instead of tabs! so it's very easy for me to get mixed up:
![tab-spaces-2](https://cloud.githubusercontent.com/assets/1280389/18685790/779cb186-7f47-11e6-85c8-59ec72f69887.gif)

**Comment by jdetle** [comment]
Hey, so I have a fix for this. Should we default to auto indent and tabbing being == 3 spaces, or allow for some sort of easy customization?

**Comment by rgbkrk** [comment]
Are you trying to start a fire with 3 spaces?

The rub is going to be that "most" JS is 2 spaces and "most" Python is 4 spaces.

We definitely need to have our own CodeMirror config. Sounds like I need to lay the foundations for the config file and you can make the codemirror setup part of that. Want to start figuring out what we'll need to pass through for a CodeMirror config that is JSON serializable?

**Comment by jdetle** [comment]
Can do cap'n

**Comment by rgbkrk** [comment]
Whoa whoa, @captainsafia is the captain.

**Comment by captainsafia** [comment]
What is this?!!? Insubordination on my own ship?!!?

Unacceptable!

**Comment by jdetle** [comment]
`react-codemirror` passes the codemirror options specified [here](https://codemirror.net/doc/manual.html#config) as a prop. It should be easy enough to parse in a json and pass it to [`const options`](https://github.com/nteract/nteract/blob/master/src/notebook/components/cell/editor/index.js#L170). Is there anything I should get started on here or hold out until you tackle a config file?

**Comment by rgbkrk** [comment]
I think it's ok for you to start proving out what the top level config is in the app, which can later assume we'll load it from a JSON file on disk.

**Comment by rgbkrk** [comment]
@jdetle do you have a fix that can be put in place without doing the custom config setup?

**Comment by jdetle** [comment]
I think so, PR incoming.

**Comment by rgbkrk** [comment]
Fixed in https://github.com/nteract/nteract/pull/873.

**Comment by rgbkrk** [comment]
A new release just went out, let us know how it is @chriddyp!
