### ISSUE TITLE
Autosave running notebook

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#814]
Currently we lack any autosave functionality. Jupyter handles this with the use of a ipynb_checkpoints folder, and for the time being we should probably do the same. 

Per @rgbkrk's suggestion we can do a bit more when it comes to this and save state history as well? Opening this to create a public discussion regarding the best way to tackle the problem. This is probably the next large-ish project I want to tackle after github oauth.

**Comment by captainsafia** [comment]
It's probably better to target this for RC than for beta.

**Comment by rgbkrk** [comment]
Totally agree about the RC or later sentiment.

**Comment by rgbkrk** [comment]
I think with where things are now, we could run autosave with an epic that is just emitting the save event every N seconds or so, assuming they've already saved at least once (or we opened a saved file).
