### ISSUE TITLE
CodeMirror does not have paren matching

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#816]
I think this could be a new-contributor friendly CSS fix.

The notebook currently does not provide paren matching — a useful feature that exists in the Jupyter Notebook.

Here's a gif that shows CodeMirror not paren matching in a case where it might be useful.

![nteract_no_paren](https://cloud.githubusercontent.com/assets/1857993/18715940/a2ae7ac8-7fe0-11e6-9f61-ecdbe4d4ee1c.gif)

**Comment by alainakafkes** [comment]
I'm interested in tackling this as a part of Hacktoberfest. Where might I take a look at the paren matching in Jupyter?

**Comment by captainsafia** [comment]
Woot! Added the tag so you can get your free shirt. 😉 

The configuration that you will need to change is in our [Editor React component](https://github.com/nteract/nteract/blob/master/src/notebook/components/cell/editor/index.js). We utilize a JavaScript library called [CodeMirror](http://codemirror.net/) that takes care of syntax highlighting and tabbing and all that good stuff. However, paren matching doesn't seem to be configured properly. You'll have to read through the docs to find the correct configuration for paren matching and update the Editor component appropriately.

Let me know if you have any other questions, Alaina!

**Comment by jdetle** [comment]
Welcome @alainakafkes!

**Comment by ivanov** [comment]
> Added the tag so you can get your free shirt.

There are shirts?!

**Comment by captainsafia** [comment]
> There are shirts?!

Yes! Check out [the webpage](https://hacktoberfest.digitalocean.com). You bring up a good point, I should tweet out that nteract is participating...
