### ISSUE TITLE
Users environment not picked up on OS X

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#820]
When launching from the dock/finder, my environment isn't picked up.

![screen shot 2016-09-22 at 10 10 01 am](https://cloud.githubusercontent.com/assets/836375/18758444/fcb36aac-80ac-11e6-8332-e705c400043a.png)

This is the same problem we run into in atom, where we need people to launch from the CLI rather than from the launcher. We do have a way to populate the user's environment variables which is a little icky but useful -> we have to open a shell session and get `PATH` and others.

**Comment by kitten** [comment]
There already seems to be a good npm package to handling all the different possible shells: https://www.npmjs.com/package/shell-env

I'm not aware of any other way to do this, since I've ran into the same problem with the team at neovim-dot-app where bash is just used to extract them: https://github.com/rogual/neovim-dot-app/blob/master/src/app.mm#L84

**Comment by rgbkrk** [comment]
Open to exploring it, even if a bit ugly. It only has to be cased off for Darwin though, which is nice.

**Comment by kitten** [comment]
@rgbkrk I think it's a fine hack. And it gets rid of the reliance on the CLI to delegate the environment variables.

Edit: I can attempt to add this if you'd like. I'm unsure where to put it though.
Edit 2: Should probably add a module that takes `process.env` and modifies it based on the shell env. Then it needs to be passed to every spawn that we're doing as an `env` option.

**Comment by rgbkrk** [comment]
Yup, we'd love it.

**Comment by rgbkrk** [comment]
Closed by #842!

Verified this works with a packaged app.

Startup is a bit slower (to be expected). Probably a good time to make a standalone watermark BrowserWindow with the animated logo.
