### ISSUE TITLE
Remote kernel registration API

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#822]
I'd love to be able to target a running JupyterHub, tmpnb, or whatever magical process some internal company has for accessing instances (auth + the notebook api). We've got decent plugin paths carving out for transforms and theming. Time to think on the kernel connection aspect.

/cc @parente who I talked to yesterday about this.

**Comment by rgbkrk** [comment]
A generic remote kernel would have to implement these functions (TBD: how these are named, loaded):
- `getKernelspecs() : Promise<KernelSpecs>`
- `newKernelObservable(kernelSpecName: string, cwd: string): Rx.Observable<Kernel>`

Where `Kernel` is an `Object` with these fields:

```
{
  channels: Rx.Subject // just like our ZMQ one, can be over websockets using a WebSocketSubject
  kernelSpec: string // to have again while using this observable
  kernelSpecName,
}
```

At least in nteract right now we also have `connectionFile` and `spawn` (child process), when it should probably be some sort of cleanup function (?).

**Comment by rgbkrk** [comment]
This side-steps auth, which we'll need to think on for all the remote cases.

Perhaps the Observable has access to the store (I'd rather it not)?

See:

https://github.com/nteract/nteract/blob/e25986ac4b6269bb468c3e931559a91d9e885d9c/src/notebook/epics/kernel-launch.js#L124

**Comment by parente** [comment]
> A generic remote kernel would have to implement these functions (TBD: how these are named, loaded):

The kernel? Or the kernel provisioner? (I'm probably learning nteract lingo.)

**Comment by rgbkrk** [comment]
Ah, the kernel provisioner. This is intended to be carving out a plugin space (in JS) to interact with remote kernels via nteract.

**Comment by parente** [comment]
Got it. We're talking about the client side API. So more like a kernel proxy.

**Comment by rgbkrk** [comment]
Yeah. Same kernel APIs, which means it can come from the gateway like we planned long ago.

**Comment by rgbkrk** [comment]
While not remote, this is helping me think about non-local-jupyter kernelspecs: https://github.com/nteract/nteract/pull/847

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/jupyterlab/jupyterlab_app/issues/48

**Comment by rgbkrk** [comment]
Now that our channels (our term for connection and messaging to the kernel) are the same between jupyter and raw zeromq, the only thing that has to be tackled is the UI for this!

**Comment by rgbkrk** [comment]
Since we now have epics for local vs. remote hosts, the next step for this is Host Discovery and UI.
