### ISSUE TITLE
Create an icon for .ipynb files

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#823]
What users currently see:

<img width="462" alt="screen shot 2016-09-22 at 1 51 17 pm" src="https://cloud.githubusercontent.com/assets/836375/18765816/323e2760-80cc-11e6-8597-96edc38cae12.png">
<img width="646" alt="screen shot 2016-09-22 at 1 53 05 pm" src="https://cloud.githubusercontent.com/assets/836375/18765817/32412f0a-80cc-11e6-98ee-c8bb5ce583e4.png">

What an Atom users sees in their app bar (as a suggestion here):

<img width="129" alt="screen shot 2016-09-22 at 1 52 11 pm" src="https://cloud.githubusercontent.com/assets/836375/18765827/3cd02d86-80cc-11e6-9963-c92be8207490.png">

**Comment by rgbkrk** [comment]
@fabric-8 it would be really great to have a document icon, likely with our current logo + some representation of a page (like Atom has).

**Comment by danoventa** [comment]
I'm doing some mockups, to see what style works best. I can line up a few, and get a vote on the style, then refine the winner.

**Comment by fabric-8** [comment]
Argh sorry missed this issue here - Can crunch something out upcoming weekend :)

**Comment by danoventa** [comment]
Whoops, sorry @fabric-8! Wasn't sure if this one was taken. :)

**Comment by rgbkrk** [comment]
All good, we weren't sure if you were too busy @fabric-8. Happy to get an icon whenever, I only opened the issue to request and track it. :smile:

@temogen - for context - the person who created all our logo assets and site design ([nteract.io](https://nteract.io)) is @fabric-8. We're big fans of the fabriverse, having found out about it via @philpl's [fluorine](https://github.com/philpl/fluorine):

![popping bottles like its hot](https://raw.githubusercontent.com/philpl/fluorine/master/docs/fluorine-flasky-2x.gif)

That being said, it's _totally_ ok to make mockups @temogen. I've done the same in collaborating with @fabric-8. That's how the notebook cube logo came to be, after iteration.

Other cool related repos:
- [nteract logos](https://github.com/nteract/logos)
- [nteract mockups](https://github.com/nteract/mocks)

**Comment by danoventa** [comment]
I was wondering who did those icons. Very beautiful work! Lemme know if you want to do any brain storming @fabric-8! Don't want to step on your creative juices, doe! Otherwise I'll just keep my focus on documenting.

**Comment by rgbkrk** [comment]
We now ship a basic little icon crafted from our main logo, I'll go ahead and close this.
