### ISSUE TITLE
Revert license to BSD

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#836]
Let's revert our license back to BSD for a couple of reasons.
- We are now a part of NumFOCUS and other projects in the org use this license.
- We can use code from jupyter/notebook more easily.
- People can build on top of the awesome work we have done more easily.

We will need to modify our C4 contribution model appropriately.

cc: @rgbkrk @jdfreder

**Comment by rgbkrk** [comment]
Since we have all the copyright holders for the MPL-code in favor, we can now make a PR to change it.

**Comment by sirinath** [comment]
Website still reads MPL: https://nteract.io/

> nteract is completely open-source and licensed under the Mozilla Public License. We love getting pull requests and issues from our users, if you're interested in opening one check out our contributor documentation.

**Comment by captainsafia** [comment]
> Website still reads MPL: https://nteract.io/

Feel free to submit a PR to fix.

**Comment by rgbkrk** [comment]
Done.
