### ISSUE TITLE
Prepare documentation for beta release

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#838]
We've got create test coverage, let's see if we can improve our documentation coverage! We'll need to add documentation for the following.
- React components
- Redux actions/reducers
- Epics

We can comment the actions and reducers per the JSDoc specification. I found [this article](http://davidboyne.co.uk/2016/05/26/automating-react-documentation.html) that recommends some ways to document React, but it looks like we can be more creative about documentation format there.

Marking as new-contributor-friendly.

cc: @willingc

**Comment by jdetle** [comment]
I would love to hear input from people with more experience regarding an idea. It would be really great to have a collection of slides that onboard new developers to how the app is organized. 
The  idea being that one could go through a collection of annotated slides starting out with something along the lines of:

```
1. "Here is the base electron app. It is launched in `main/index.js`. This is a part of the main process." 
2. "This is the menu, it communicates with various components, which are all part of the electron Renderer process..."
3. "This is a code cell, it communicates with the kernel through these epics..." 
```

This is not meant to be a tutorial, but a visual collection of relevant links and tangible examples of areas where the tech stack is used in nteract.

**Comment by rgbkrk** [comment]
As part of this, if it turns out to get easier to document React components if we're using flow for our proptypes, I'm happy chasing that down.

[Great presentation that made me realize how wonderful flow + PropTypes can be.](https://www.youtube.com/watch?v=dV8K6fsjDCQ)

**Comment by rgbkrk** [comment]
Now that we're in less flux I think we could create that presentation. Just plain writing it would likely help firm up the why of the infrastructure. Want to start writing it and see where you get?

Could even use [spectacle](https://github.com/FormidableLabs/spectacle) to create the presentation. :wink:

**Comment by jdetle** [comment]
Yeah I'll get to working on it tonight. Its bound to help me actually understand things as well.

**Comment by willingc** [comment]
@jdetle Pro tip: Work on small sections as a WIP PR and iterate with feedback from others. Much easier and you will learn more ;-) Feel free to ping me as needed for review.

**Comment by jdetle** [comment]
Thanks so much @willingc!

**Comment by captainsafia** [comment]
> This is not meant to be a tutorial, but a visual collection of relevant links and tangible examples of areas where the tech stack is used in nteract.

A consequence of using a presentation is that it general requires a lecturer to augment the material presented. Lacking this, I imagine we'll have a lot of people approaching us with questions or falling victim to information overkill early on, especially with links and jargon they might not understand yet.

I think the better route to go is to clean up/finish the how to build a notebook documentation that Jon and I started. It presents the same information that you provided but in a more tutorial style which is a more effective way of on-boarding new devs.

The best combination in my opinion is light documentation around what parts of the code base contains what ("src/notebook/actions.js contains our action-creators") and the notebook documentation that will inform new devs what an action-creator is by having them build it.

The documentation for building a notebook is [here](https://github.com/nteract/docs). I have an open PR (that can probably be merged at this point) [here](https://github.com/nteract/docs/pull/12).

**Comment by danoventa** [comment]
I'd like to do some research on documentation. Then create a task list to identify the different components that need documentation. This should make it easier for new contributors to take a bite sized piece of this issue. :)

@jdetle want to work together on compiling a task list? And maybe take a few out in the process?

**Comment by jdetle** [comment]
Of course I'd love to help. I've been pretty swamped with worky-work so I can't commit to any deadlines. But I'd love to work with you and help you figure everything out.

**Comment by jdetle** [comment]
In `src/notebook/menu.js` we have plenty of functions that could be documented but dispatch to the redux store rather than return something. How should we handle this with JSDoc?

**Comment by captainsafia** [comment]
You can use JSDoc syntax -- they just wouldn't have a returns field.

**Comment by danoventa** [comment]
No worries @jdetle, I have some catching up to do!

**Comment by danoventa** [comment]
- [ ] **main**
  - [ ] cli.js
  - [x] index.js (some documentation, not all consistent)
  - [x] kernels.js (one thing documented)
  - [ ] launch.js
  - [ ] menu.js
  - [ ] prepare-env.js (no functions, only constants, evaluate how to doc, if needed)
- [ ] **notebook**
  - [ ] **components**
    - [ ]  **cell**
      - [ ] **display-area**
        - [ ] display.js (maybe)
        - [ ] index.js (nothing much here, how to need to?)
        - [ ] output.js 
        - [ ] richest-mime.js
      - [ ] **editor**
        - [ ] codemirror-ipython (maybe?)
        - [ ] complete.js
        - [ ] index.js (has some documentation, standardize)
      - [ ] cell-creator-buttons.js
      - [ ] cell-creator.js (standardize)
      - [ ] cell.js (more standardize)
      - [ ] code-cell.js (yes)
      - [ ] draggable-cell.js
      - [ ] inputs.js
      - [ ] markdown-cell.js
      - [ ] pager.js (standardize?)
      - [ ] toolbar.js
    - [ ] **transforms**
      - [ ] geojson.js
      - [ ] html.js
      - [ ] image.js
      - [ ] index.js (some standardization)
      - [ ] javascript.js
      - [ ] json.js
      - [ ] latex.js
      - [ ] markdown.js
      - [ ] plotly.js
      - [ ] text.js
    - [ ] latex.js
    - [ ] notebook.js
    - [ ] status-bar.js
  - [ ] **components**
    - [ ] **cell**
      - [ ] **display-area**
        - [ ] display.js
        - [ ] index.js (no?)
        - [ ] output.js
        - [ ] richest-mime.js
      - [ ] **editor**
        - [ ] codemirror-ipython.js
        - [ ] complete.js
        - [ ] index.js
      - [ ] cell-creator-button.js
      - [ ] cell-creator.js (some standardize)
      - [ ] cell.js (some standardize)
      - [ ] code-cell.js
      - [ ] draggable-cell.js
      - [ ] inputs-source.js
      - [ ] markdown-cell.js (standardize)
      - [ ] pager.js (?)
      - [ ] toolbar.js
    - [ ] **transforms**
      - [ ] geojson.js
      - [ ] html.js
      - [ ] image.js
      - [ ] index.js (standardize?)
      - [ ] javascript.js
      - [ ] json.js
      - [ ] latex.js
      - [ ] markdown.js
      - [ ] plotly.js
      - [ ] text.js
    - [ ] latex.js
    - [ ] notebook.js 
    - [ ] status-bar.js 
  - [ ] **epics**
    - [ ] comm.js (looks documented)
    - [ ] config.js (maybe ? )
    - [ ] execute.js (done?)
    - [ ] github-publish.js (also done?)
    - [ ] index.js (no need?)
    - [ ] kernel-launch.js (yes?)
    - [ ] loading.js
    - [ ] saving.js
  - [ ] **kernel**
    - [ ] messaging.js (mostly done?)
    - [ ] shutdown.js
  - [ ] **reducers**
    - [ ] app.js
    - [ ] comms.js ( ? )
    - [ ] config.js ( not sure what this is )
    - [ ] document.js (possibly)
    - [ ] index.js (no?)
    - [ ] metadata.js
  - [ ] actions.js
  - [ ] constants.js (no? or group?)
  - [ ] global-events.js
  - [ ] index.js
  - [ ] logger.js
  - [ ] menu.js
  - [ ] middlewares.js (maybe...)
  - [ ] native-window.js
  - [ ] path.js (standardize)
  - [ ] records.js (not sure...)
  - [ ] store.js (standardize)
- [ ] **utils**
  - [ ] fs.js
- [ ] Tests ?

**Comment by rgbkrk** [comment]
The way we document our components nowadays is through [react styleguidist](https://github.com/styleguidist/react-styleguidist). We're even live at https://components.nteract.io/ for the presentational ones! 😄 

Since this issue is fairly out of date with regards to the current structure I think we can close it and open new issues for specific areas.

For those who stumble on this issue later, [check out the user guide repo](https://github.com/nteract/user-guide) and [the docs website](https://docs.nteract.io/).
