### ISSUE TITLE
Add a theme with the nteract color scheme

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#848]
Currently we have two default themes, light and dark. As a project for new contributors, it would be nice to have a theme that incorporates the color scheme of nteract's logo into the background and/or cell aesthetic. Changing CSS, although not a programming heavy task, is a good way to get started making contributions after installing.

**Comment by stephymiehle** [comment]
I've got a start on this one! Building on top of Light, but with a few details to make focusing on a specific cell easier.

![image](https://cloud.githubusercontent.com/assets/6765732/19009066/d9bdbed2-8735-11e6-8b67-18cbc2cde819.png)

**Comment by captainsafia** [comment]
Oh wow, Stephy! That's an absolutely gorgeous design. I'm really looking forward to your PR.

Welcome to the nteract community! 🎉

**Comment by jdetle** [comment]
😍 This looks so awesome!!!!

**Comment by rgbkrk** [comment]
wooooooooooooooooow
