### ISSUE TITLE
Enable configurable default cell type

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#85]
From some of the classes I have taught and some observations at conferences, I've noticed that people tend to use the notebook in two ways, as a note-taking tool and as the "traditional" interactive programming tool. Simply put a note-taking user will mostly be writing text with occassional code cells. On the other hand, a "traditional" user will mostly be writing code with occassional text cells.

As mentioned by @rgbkrk in #41, composition will only support the Markdown and code cell types so we are dealing with a binary toggle. I'm imagining the following implementation option.
1. Add a `defaultCellType` property to the [Notebook class](https://github.com/nteract/composition/blob/master/src/components/Notebook.jsx).
2. Configure the cells to render with the `defaultCellType` by default.
3. Add a toggle, either as a menu item or as a literal toggle, although I am leaning towards the menu item that will allow the user to set the default cell type.

There might be more details to flesh out on this but this is my cursory impression based on user observations and code reading.

**Comment by rgbkrk** [comment]
Taking a step back here, we need to draft up some mocks and specs for creating new cells in general.

How does a user create a cell in between two cells?

For a mouse based flow, the way colaboratory did it in the past was a hover between cells:

<img width="232" alt="screenshot 2016-02-08 15 44 54" src="https://cloud.githubusercontent.com/assets/836375/12901841/faaade5a-ce7a-11e5-9457-14f19af7ffca.png">

while also having buttons for adding text and code in the toolbar

<img width="128" alt="screenshot 2016-02-08 15 45 42" src="https://cloud.githubusercontent.com/assets/836375/12901871/0ae08a18-ce7b-11e5-846b-27a4993f635e.png">

In fact, the whole toolbar is trimmed down:

<img width="442" alt="screenshot 2016-02-08 15 46 20" src="https://cloud.githubusercontent.com/assets/836375/12901881/1ebab590-ce7b-11e5-87e1-482cfd073e3c.png">

That can be refined further of course, I'm only posting those as prior examples.

The current notebook has a single button for add (+), which you then have to toggle to make it a text cell.

<img width="453" alt="screenshot 2016-02-08 15 48 09" src="https://cloud.githubusercontent.com/assets/836375/12901931/62759cc8-ce7b-11e5-85a0-ee6397865d9a.png">

Once you round out that workflow, does default become more simple? Maybe not all the way.

As for that one, I'm imagining a menu item that flows like:

```
Cell
  Default Cell ➡ [x] Code
                 [ ] Markdown
```

**Comment by captainsafia** [comment]
Now that I think about it this should be something that is set globally in nteract's preferences.

Then this gets into how preferences are handled within nteract... _thinks_

**Comment by rgbkrk** [comment]
I still like the idea of this.

**Comment by rgbkrk** [comment]
What do you think about this now, given where we're at as well as our current UI?

I'm noticing myself just click the "new markdown" cell on the cell creator toolbar really fast to get new markdown cells.

**Comment by captainsafia** [comment]
I think it's a good new-contributor-friendly issue. I cannot speak to everyone's workflows but I've seen the issue brought up quite often on the Jupyter list so it doesn't hurt to have it.

**Comment by rgbkrk** [comment]
How would someone go about implementing this? What would you want to see for config/menus, UX flow?

**Comment by captainsafia** [comment]
To start (read: beta), we would have all our configuration options "hidden" in the `nteract.json` file. We would have them documented in a release README but there would be no preferences panel for users to graphically change their configuration. Similar to what I did with the theme configuration, we would have a `defaultCellType` attribute in the `ConfigRecord`. The Add New Cell keyboard shortcut would be replaced so that instead of adding a new code cell by default it would add a new `defaultCellType` cell. Also, we would read from the config when the notebook component is mounted to figure out what the first cell in the notebook should be (right now, it is a code cell).

Later, perhaps for RC, we could add a visual configuration panel where someone could hit nteract > Preferences and a new BrowserWindow would pop out with our preferences pane. Considering the kind of events we want to make configurable now (default kernel, default cell type, theme) the preferences pane will likely just be set up as a form with select dropdowns or whatever other form input makes sense for the data type of the configuration.

Then we would just hook up the onChange event for each select with a dispatch to the SET_CONFIG_KEY  action.

**Comment by rgbkrk** [comment]
We currently use a model of "Whatever the last cell type was is the next cell type" when using shift-enter or repeatedly holding down in the notebook. Would you say this suffices or should we still have a configurable default?

**Comment by willingc** [comment]
Closing as stale. Feel free to reopen or open a newer issue.
