### ISSUE TITLE
Add a theme for visually-disabled users

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#851]
This starts us off thinking about accessibility for the notebook, something that we should tackle early on.

The easiest issue to take on is accessibility for visually-impaired users. We'll need to create a new theme for the application (ala `static/styles/light.css`) that includes some of the following modifications.
- High contrast text-background color combination (for example, yellow text on a black background)
- Larger font-sizes on all elements
- Test how nteract behaves with screen magnifiers and identify possible bugs

**Comment by jdetle** [comment]
Somewhat related, support for screen readers would be awesome.

**Comment by captainsafia** [comment]
> Somewhat related, support for screen readers would be awesome.

A brief test of VoiceOver on Mac shows that it works decently well. It doesn't recognize some things, for example if I click on an output area it just reads out what it says without saying it's an output which can be confusing. This is a good time to run our app through react-a11y.

**Comment by rgbkrk** [comment]
> This is a good time to run our app through react-a11y.

Most definitely.

**Comment by AbhishikthaReddy** [comment]
hello, can I get more info related to this issue. I am planning to work on this issue, thanks!

**Comment by captainsafia** [comment]
@AbhishikthaReddy: A new theme will need to be created in `static` styles that styles the components on the page per the things I outlined above.

Is there a specific question that you'd like answered about the issue?
