### ISSUE TITLE
Audit nteract behavior under screenreaders

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#852]
A brief test of nteract's behavior when used with a screenreader exposes several bugs. It'd be great to have an accessibility specialist or a visually-impaired individual give the application an audit for its behavior on different screen-readers.

Furthermore, we should run our application through [react-a11y](https://github.com/reactjs/react-a11y) to find other accessibility issues that might contribute to making nteract play nicer with screen readers.

**Comment by jdetle** [comment]
Edited: I was talking with a family friend at edX and she was saying that they don't let any product into the edX platform doesn't comply with [WCAG](https://www.w3.org/WAI/intro/wcag).

**Comment by captainsafia** [comment]
> I was talking with a family friend at edX and she was saying that they don't let any product through that doesn't comply with WCAG.

Product through for what?

**Comment by rgbkrk** [comment]
From https://medium.com/@addyosmani/accessible-ui-components-for-the-web-39e727101a67#.jbzfgni08:

![image](https://cloud.githubusercontent.com/assets/836375/22666324/f196d9c0-ec6c-11e6-8311-65c910585da6.png)
