### ISSUE TITLE
Remove loading gif from notebook interface

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#854]
Follow up on #853.

Now that we have a splash image, we can remove the gif that shows within the notebook window when the application starts. This is present in `static/index.html`.

**Comment by rgbkrk** [comment]
Funny thing though: new notebooks or loading new notebooks won't have a conflicting splash though - they'll be showing the splash for their own loading. Perhaps it's time to think about another loading screen within the notebook window. 😕

**Comment by captainsafia** [comment]
Perhaps a spinner?

**Comment by captainsafia** [comment]
Closed in #856.
