### ISSUE TITLE
Startup issues with developer install on Linux

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#864]
## Current Versions

_node_=6.6.0
_npm_=3.1.0
_nteract_= fresh installed latest commits on master
## Behavior

`npm run start` yields

```
> nteract@0.0.12 start /home/jdetlefs/github/nteract
> cross-env NODE_ENV=development electron .

[03:08:48:0607] [info] args [ '/home/jdetlefs/github/nteract/node_modules/electron-prebuilt/dist/electron',
  '.' ]
[03:08:49:0270] [info] launching an empty notebook by default
```

Which shows the loading gif, seems to show the beginnings of a browser window, and then is instantly closed. 

When I run `npm run start example-notebooks/intro.ipynb` an Untitled - Unconnected notebook shows up on the screen and cannot connect to the kernel in spite of the availability of python 3 in the filemenu.

**Comment by rgbkrk** [comment]
Oh I bet this is the "all windows closed when not Darwin" logic.

**Comment by rgbkrk** [comment]
Resulting from the splash page being closed.
