### ISSUE TITLE
Adjust styling to accomodate to poorer screen resolution.

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#868]
Checking out some of the changes I've made, especially the dropdown menu, the text looks kind of pixelated and weird. Also, the menu toolbar background color seems like it should be less conspicuous on my screen now that I have higher contrast. We should probably attempt to audit these things and try to get the visuals looking right across multiple platforms. 
## Changes that could be made that would fall under this issue:
- Change menu toolbar background color to something less prominent, this involves some CSS styling in the themes and main.css
- Change the menu dropdown content font size, perhaps even make these properties resolution dependent? (This should be weighed in on by people with more experience) 
- More ideas welcome.

**Comment by captainsafia** [comment]
Can you add screenshots of the things you discussed above?

**Comment by jdetle** [comment]
Yeah I was in a rush to get to work but I'll get to it tonight when I get back to my linux machine.
