### ISSUE TITLE
Custom Observable for our zmq and websocket subjects

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#874]
# Creating custom Observables for our kernel subjects

Two weeks ago I had a conversation with @jayphelps and @SomeKittens which led to [wrapping some of our Observable creation methods with the originating `send`](https://github.com/nteract/nteract/blob/181b2f08337b25f62020c3de90267608e1395faf/src/notebook/epics/execute.js#L200), which roughly looks like this:

```js
function executeCodeObservable(code: string) {
  const executeRequest = createExecuteRequest(code);

  // All the message handling for responses gets wired up...
  const cellAction$ = Rx.Observable.merge(bunchOfCellAction$);

  // On subscription, send the message
  return Rx.Observable.create(observer => {
    const subscription = cellAction$.subscribe(observer);
    channels.shell.next(executeRequest);
    return subscription;
  });
}
```

That works pretty awesome.

In quite a few cases we want a message sent as soon as someone subscribes to a resulting observable. @jayphelps' suggestion was to create a custom observable that overrides `_subscribe` and handles this stuff in a custom subscriber a la [AjaxObservable's _subscribe](https://github.com/ReactiveX/rxjs/blob/e20cdb73e9a6255d704e39c2e867b3227207b4b0/src/observable/dom/AjaxObservable.ts#L171). WebSocketSubject is also a good example of that, which we should learn a bit about when we start using nteract with websocket based kernels.
## Background on nteract's channels

Our primary channels that we care about are `shell` and `iopub`. They're built on top of ZMQ sockets (though they could also be transported over websockets).
### `shell`

This is a `DEALER` socket, in ZMQ parlance, with the backend kernel/runtime being the ROUTER socket that accepts messages. Frontends send messages like `execute_request`.
### `iopub`

This is a `SUB` socket. Messages are never sent on this socket - it's only a receiver. Responses from the `execute_request` will end up on this channel.
### Next steps

Both of these channels stay alive up until they connect to a new backend. Roughly, this:

``` js
export const newKernelEpic = action$ =>
  action$.ofType(LAUNCH_KERNEL)
    .switchMap(action => Observable.of(newKernelAction(action.channels))
```

When we do execution, we rely on the channels being part of the state tree to use throughout the app (it also gets used for autocompletion, separately from redux but still with Rx and CodeMirror).

**Comment by benlesh** [comment]
@rgbkrk I would definitely create a custom Subject that extends Rx.Subject for this. Be sure to override `lift` if you want to add custom operators. Otherwise all operators will return `Subject`, which is probably fine.

**Comment by jdetle** [comment]
A related (possibly tangentially related) issue was the discussion of a 'fuse'-like mechanism (https://github.com/nteract/nteract/issues/1452) to prevent the subject from producing too much data such that the data-consumption+rendering can't keep up. I don't know if this could be solved by a custom observable, but @blesh, you certainly seem like the right person to ask.

**Comment by rgbkrk** [comment]
With our current multiplexed channels that keep the session ID and username, I think we're in a good state and this can be closed!
