### ISSUE TITLE
Handling old message specs

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#879]
When faced with a kernel that uses the old message spec (or doesn't implement it properly), we either need to try to upgrade to v5 (or latest) as best we can _or_ provide an error that states that we "can't support this kernel reliably because of version".

**Comment by captainsafia** [comment]
I'm in favor of throwing an error instead of adding backwards compatibility because:
- it reduces the amount of complexity that we have to manage
- it encourages kernel maintainers to stay up-to-date with the latests fixes and modifications in the spec
