### ISSUE TITLE
Add Flow typings to React components

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#887]
We've got several React components stored under `src/notebook/components` in our codebase. These React components contain a `propType` property that defines the types of the different props the component takes. We'd like to use [Flow](https://flowtype.org/) to make these typings.

Pick one of the React components in our codebase and integrate Flow into it. [This](http://www.robinwieruch.de/the-soundcloud-client-in-react-redux-flow/#reactComponents) article provides good information on how to set up Flow and integrate it with React components.

**Comment by alexandercbooth** [comment]
Hi @captainsafia, 

First, thank you for helping to create a great tool (particularly enjoying the Halloween theme right now)!

Just to make sure that I understand the problem: in a particular react component, say for example,  status-bar.js, instead of the current situation,

``` js
static propTypes = {
    notebook: React.PropTypes.any,
    lastSaved: React.PropTypes.instanceOf(Date),
    kernelSpecName: React.PropTypes.string,
    executionState: React.PropTypes.string,
  };
```

We could setup flow by including the flow script in the package.json, add a `// @flow` at the top and replacing the above with: 

``` js
  props: {
    notebook: any,
    lastSaved: Date,
    kernelSpecName: string,
    executionState: string,
  };
```

When I do that and run the flow script, it creates no new errors. 

Am I understanding this correctly?

**Comment by captainsafia** [comment]
> First, thank you for helping to create a great tool (particularly enjoying the Halloween theme right now)!

Thank _you_ Alexander and welcome to the nteract community! 😄 

And I just realized it is October so our Halloween Easter Egg has been revealed! 🎃 

> When I do that and run the flow script, it creates no new errors.

Yep! That's exactly right.

**Comment by estevanjantsk** [comment]
@captainsafia =DDD Just created a PR for this issue =)
https://github.com/nteract/nteract/pull/890

Is this right?

Btw, thanks =))))).

**Comment by captainsafia** [comment]
> @captainsafia =DDD Just created a PR for this issue =)
> #890
> 
> Is this right?
> 
> Btw, thanks =))))).

Thanks for submitting that PR, @estevanjantsk! Let's continue our conversation on there.

@alexandercbooth: It looks like you've got a strong understanding of Flow so feel free to submit a PR adding typings to another one of our React components if you'd like.

Thanks, all!

**Comment by alexandercbooth** [comment]
@captainsafia Thanks for the feedback! 

I just wanted to confirm this so that I could avoid submitting a problematic PR. I guess I'll have to be faster next time.

Thanks again, I appreciate it

**Comment by captainsafia** [comment]
> I just wanted to confirm this so that I could avoid submitting a problematic PR. I guess I'll have to be faster next time.

Absolutely and no problem! Feel free to submit PRs at whatever pace you're comfortable with. We've got plenty of components that need typing! 😉 😄

**Comment by captainsafia** [comment]
I think we can close this one thanks to the wonderful work of @peggyrayzis, @alexandercbooth, and @estevanjantsk! Thanks all! 🎉 🌮
