### ISSUE TITLE
Add tutorial resources to CONTRIBUTING.md

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#888]
We've amassed a ton of tutorial content in our Slack channel covering the technology that we use. Although the technology that we use is mentioned in our CONTRIBUTING.md, we don't provide resource for individuals to learn about these technologies.

We should add links to tutorials and videos that explain React, Redux, RxJS, and Electron.

**Comment by rgbkrk** [comment]
Our [frontend background](https://github.com/nteract/nteract#frontend-background) section has a bunch of this that could be moved over into CONTRIBUTING.md

**Comment by captainsafia** [comment]
> Our frontend background section has a bunch of this that could be moved over into CONTRIBUTING.md

Turning that bit into a new-contributor-friendly/hacktoberfest tag.

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.

**Comment by captainsafia** [comment]
> I would like to claim this. This would be my first open source pull request.

Wonderful, Sumant! Welcome to the nteract community!

Feel free to ask us questions if you have any either on this issue or on [our Slack community](http://slack.nteract.in/).

**Comment by prafful002** [comment]
@captainsafia May I take this up if no one is working on it currently ?

**Comment by rgbkrk** [comment]
@Subway19 is there another issue you would be interested in? Some of this was already completed and I just finished off the rest in #960.
