### ISSUE TITLE
Handle nbformat cell attachments

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#889]
nbformat 4.1 introduced [Cell attachments](https://nbformat.readthedocs.io/en/latest/format_description.html#cell-attachments)

``` json
{
  "cell_type" : "markdown",
  "metadata" : {},
  "source" : ["Here is an *inline* image ![inline image](attachment:test.png)"],
  "attachments" : {
    "test.png": {
        "image/png" : ["base64-encoded-png-data"],
    },
  },
}
```

We need to support it. To be extra stellar, we could probably support drag and drop. On Windows surface devices, we could probably even support a scratch pad area to draw in. :wink:

**Comment by Jaykul** [comment]
Yeah, it causes an error when I open a notebook from Jupyter, and a broken image 

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
attachment:2016-06-08_18-04-58.png
```

**Comment by Jaykul** [comment]
Yeah, it causes an error when I open a notebook from Jupyter, and a broken image 

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
attachment:2016-06-08_18-04-58.png
```

**Comment by kiwi0fruit** [comment]
Pandoc 2.6 ipynb output works well in jupyter lab but doesn't work well in nteract because of this issue.

**Comment by kiwi0fruit** [comment]
So pandoc side won't add support for attachements turned off.
