### ISSUE TITLE
Make our about dialog awesome

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#899]
<img width="396" alt="screen shot 2016-10-03 at 10 06 07 pm" src="https://cloud.githubusercontent.com/assets/836375/19063294/510444ac-89b6-11e6-8211-cbf013c2833e.png">

Our releases are missing the release name and we could definitely provide a link back to github within the about dialog. I'm assuming this can be filled in with more options from electron-packager  (or other configuration).

**Comment by grantjames** [comment]
I'm looking to start contributing to open source software and really like the look of this project!

Can I claim this issue so I can use it as my first pull request? :-)

**Comment by rgbkrk** [comment]
Take it while it's hot, feel free to ask questions.

**Comment by prafful002** [comment]
@rgbkrk May I get this assigned to me if no one is working on it currently ?

**Comment by jdetle** [comment]
@prafful002, you do not need to be assigned to start working on any of these tasks. PRs are very welcome and if you have trouble with anything don't hesitate to reach out on [slack](http://slack.nteract.in/)

**Comment by rgbkrk** [comment]
It's hard to tell if anyone is working on it without a PR. You're free to explore the space. Make a pull request, even if partially done, and set the title to include `[WIP]`. People will be happy to help you work through it.

**Comment by jdetle** [comment]
@prafful002 if you need help, I'm almost always available on [slack](http://slack.nteract.in/)

**Comment by jkornblum** [comment]
Does this exist any more? 

I see a Help > Learn More but no Help > About or File > About anywhere.

**Comment by rgbkrk** [comment]
On a Mac, this menu is under nteract > About nteract (and in dev mode Electron > About Electron).

**Comment by rgbkrk** [comment]
Luckily we have `Help > Release Notes`, so I think it's fine that no one is working on this for now.
