### ISSUE TITLE
Notebook storage

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#9]
Where do notebooks get saved by default? What's your workspace area (your `cwd` if you will)?

Since this is an electron app that can run from clicking a shortcut on someone's Windows Desktop or Apple Applications menu, we have to make sensible defaults (while clearly allowing for file browsing).

**Comment by captainsafia** [comment]
Not sure if this is what you are asking but for me specifically, the setup looks like this.

```
- home
    - jupyter-notebooks
        - dev
        - data
        - test.ipynb
```

Inside `dev` I have notebook files that I use to test things out (widgets, new extensions, verifying bug reports), `data` is where I keep CSVs, and I keep all notebooks scattered about in in `~/jupyter-notebooks` folder.

**Comment by rgbkrk** [comment]
Well, I'm thinking more about if we have a workspace view like the notebook does. When you open the notebook, there's a dashboard view with all your files (relative to where the notebook was opened)

Home folder is an easy choice to just get started, unless they opened it from the command line.

**Comment by rgbkrk** [comment]
`cwd` is currently set to be the location of the file itself

**Comment by rgbkrk** [comment]
Interesting problem I just realized on creating a new notebook. Steps:
1. Create new notebook (kernel cwd now defaults to process)
2. Save notebook somewhere other than `cwd`
3. Re-open, and the kernel is in a new spot

It's a bit late so I'm not sure I conveyed that well.

**Comment by rgbkrk** [comment]
Notebooks now get saved... where you save them with the dialog.
