### ISSUE TITLE
Split pane/tabs

### ISSUE THREAD

**Issue by osdf** [nteract/archived-desktop-app#910]
Hi,

is there a way to have two notebooks open next to each other (or in tabs) in one nteract frame (for example as in jupyter lab)?

**Comment by rgbkrk** [comment]
Hey there!

We take the approach of relying on native windowing. To put two notebooks next to each other on your screen, open two windows. Each window maps to one file.

Options for multi-pane right now include Atom and JupyterLab. The atom plugin for notebooks needs love, and I'm hoping we can tackle it after we've solidifed nteract, likely post-beta.

**Comment by rgbkrk** [comment]
Longer form answers, which is more architectural in nature:
- nteract can be viewed as a single document editor, where you can double click `.ipynb` files from your desktop or in search to open them
- We need a consistent state tree (in terms of the document state) in order to approach real-time collaboration later.

**Comment by osdf** [comment]
Hi @rgbkrk thanks for your answer. I understand that the multi-pane idea would add unnecessary complexity, given that a window manager does this already. Having said that, the question was more out of curiosity---is this the right place to ask these or are there other preferred channels?

**Comment by rgbkrk** [comment]
You can absolutely ask here! We're not drowning in questions yet - if we ever are, we would probably create an AMA or help repo (a la [nodejs/help](https://github.com/nodejs/help) or [jupyter/help](https://github.com/jupyter/help)).

This also _is_ a legitimate feature request, even if I personally think it's out of scope. Thanks for posting!
