### ISSUE TITLE
Provide an application/json transform

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#931]
Use https://github.com/alexkuz/react-json-tree, have an awesome navigable object.

**Comment by aleury** [comment]
I'd be happy to take on this one.

**Comment by rgbkrk** [comment]
Sweet, this should be pretty simple. I'd start with looking at the text transform:

https://github.com/nteract/nteract/blob/master/src/notebook/components/transforms/text.js

and then import and add it to the list of transforms + display order:

https://github.com/nteract/nteract/blob/master/src/notebook/components/transforms/index.js#L21

**Comment by aleury** [comment]
Awesome, thanks!

**Comment by aleury** [comment]
So I have a `JsonDisplay` component made but am unsure on how to make sure that it's used. Is the plan to check if the data returned is able to be parsed by `JSON.parse` and return the `application/json` mime type if so, or will this be communicated in some other way?

**Comment by jdetle** [comment]
@aleury can you submit a work in progress PR so people can take a look at what you've done?

**Comment by aleury** [comment]
Submitted the WIP PR.
