### ISSUE TITLE
Make Travis happier to work with

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#94]
I'm not sure what limits we're running into right now (disk space, memory?). Travis seems to be stalling out on the regular while I'm able to build and run this all locally on Linux and OS X.

**Comment by rgbkrk** [comment]
I've taken Travis down for now, going to start investigating Strider for our workflow.

**Comment by captainsafia** [comment]
Oh, Travis...

@rgbkrk — Fix your issue title!

**Comment by rgbkrk** [comment]
Now that zmq-prebuilt is out, I can't wait to re-enable Travis. :smile:

**Comment by rgbkrk** [comment]
Super done by @jdfreder, complete with zmq artifact caching.
