### ISSUE TITLE
Map ⌘-0 to reset zoom

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#942]
At least on Chrome, ⌘-0 resets the zoom. I'm not sure what the generic binding is, but I'd love to be able to reset the zoom level to 100%.

**Comment by alexandercbooth** [comment]
I'm happy to try and tackle this.

**Comment by alexandercbooth** [comment]
For the commit message, is this considered a chore?

**Comment by alexandercbooth** [comment]
or perhaps feature?

**Comment by rgbkrk** [comment]
This is a feature - it's something new exposed to users.

**Comment by alexandercbooth** [comment]
Makes sense, silly of me, thanks!

**Comment by rgbkrk** [comment]
It's ok, not silly at all. Keep asking questions, happy to work with you.

**Comment by lgeiger** [comment]
Closed by #948 

@alexandercbooth Thanks for your work 🎉

**Comment by alexandercbooth** [comment]
You're very welcome!
