### ISSUE TITLE
Provide right-click -> Inspect

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#944]
This helps two groups:
- Those hacking on nteract
- Those hacking _in_ nteract (outputs they want to inspect)

**Comment by jkornblum** [comment]
Would incorporating this module (electon-context-menu) be acceptable?
https://github.com/sindresorhus/electron-context-menu

It comes with context aware cut, copy, paste, image-save menu items.
It comes with inspect-element menu item.

It has two dependencies, electon-dl and electron-is-dev. Both from the same author and all under MIT license.

---

If this is too much I can modify the source to just include cut, copy, paste, inspect-element. It would not require any dependencies then.

Let me know what you guys think and I can submit a PR

![ss1](https://cloud.githubusercontent.com/assets/5368903/19463033/73e202c4-94b6-11e6-9857-ace7846aa066.png)
![ss2](https://cloud.githubusercontent.com/assets/5368903/19463037/87c78656-94b6-11e6-81cc-69955a85f00b.png)
![ss3](https://cloud.githubusercontent.com/assets/5368903/19463040/8ad02c86-94b6-11e6-9335-521e4f1a87e0.png)
![ss4](https://cloud.githubusercontent.com/assets/5368903/19463043/909920b4-94b6-11e6-8bc2-98a656f203c5.png)

**Comment by rgbkrk** [comment]
@jkornblum Absolutely! Feel free to make a PR. I'd love to use this.

**Comment by rgbkrk** [comment]
Done in #1044.
