### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#95]
It's been suggested that we either rename to:
- nteract/nteract

or
- nteract/notebook

The first presumes that the Electron based notebook will be the primary byproduct of the nteract org (similar to Atom). Considering how many people refer to Jupyter as `JupyterHub | jupyter/notebook | tmpnb`, I'm fairly tempted to go along with that. One other issue we've run into in the past is that "the notebook" can refer to the notebook document, the notebook server (python), or the frontend application that is the jupyter notebook.

The composition name came from me thinking of a different way to say notebook; @karissa and I rolled with it and all was happy.

/cc @jackparmer

**Comment by jdfreder** [comment]
+1 for nteract/nteract

**Comment by jackparmer** [comment]
I also like nteract/nteract. It implies nteract _is_ the notebook, one less
ontological concept to keep sorted and explain!

**Comment by rgbkrk** [comment]
Alright, let's charge ahead with nteract/nteract!
