### ISSUE TITLE
Store version of nteract in the notebook metadata

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#950]
Similar to how [colab (at Google) provides metadata for version](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/docker/notebooks/1_hello_tensorflow.ipynb) (amongst other things), we should provide metadata about the notebook being written by nteract as well as the version.

**Comment by rgbkrk** [comment]
I think we could add this to our `toJS` stage or do it on notebook load.

**Comment by rgbkrk** [comment]
Just a minor note on this since there are many things labeled "metadata". This will belong in the metadata of the notebook document `state.document.getIn(['notebook', 'metadata', 'nteract', 'version'])`.

**Comment by raygesualdo** [comment]
I can work on this issue.

**Comment by Madhu94** [comment]
Closing, now that #1747 is pulled in
