### ISSUE TITLE
Notebook does not automatically connect to a kernel

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#956]
I'm running to this issue on Linux. Opening an empty notebook does not connect to a kernel by default. I have two available kernels, python2 and python3, both of which work after selecting Language >> Kernel. On my mac the notebook starts up and connects to the first available kernel. I'm trying to confirm that this a bug that should be fixed on linux.

**Comment by rgbkrk** [comment]
I'm going to go ahead and close this unless there's a way to reproduce it.
