### ISSUE TITLE
Create a terminal command/wrapper for the nteract app

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#961]
I want to be able to navigate to a directory (from the command line) and run `nteract analysis.ipynb`. Our app already handles command line arguments - we need to ship a standalone script that, at least on OS X, passes through to `open nteract.app ARGS`.

**Comment by lgeiger** [comment]
#999 
- [x] OS X
- [x] Linux/Ubuntu
- [x] Windows
