### ISSUE TITLE
Autoexpanding application/json

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#962]
As I use nteract's new `application/json` mime type, I wish that by default the entire tree is fully expanded. I'm guessing the component we use has a way to expand them automatically. They start out collapsed.

![screen shot 2016-10-09 at 11 54 09 am](https://cloud.githubusercontent.com/assets/836375/19221746/1adf86ba-8e17-11e6-9bf3-3cc270cdaf7a.png)

<p align="center">⬇️</p>

![screen shot 2016-10-09 at 11 54 27 am](https://cloud.githubusercontent.com/assets/836375/19221748/27b65e2c-8e17-11e6-9a6f-9dbddc92f36b.png)

Similar to how we handle image metadata:

``` js
metadata: {
  'image/png' : {
    width: 640,
    height: 480
  }
}
```

I'd love to make metadata for application/json expanded with:

``` js
metadata: {
  'application/json' : {
    expanded: true,
  }
}
```

which would expand the entire JSON tree.

---

Steps to take (in mostly any order):
- [x] Accept this metadata on our current JSON transform (on `this.props.metadata`)
- [x] Make a PR to ipython/ipython to accept metadata directly _as well as_ an `expanded` parameter
- [x] Make a PR to jupyter-client with this metadata (for the docs)

/cc @aleury

**Comment by aleury** [comment]
Making the json tree fully expanded by default was actually as easy as passing `shouldExpandNode={() => true}`  as a prop to the `JSONTree` component. 

Do you still think we'll need to use the metadata? Will the metadata prop enable the expansion of the `JsonDisplay` component to be configurable by the user? I'm still very new to how the ipython messaging spec works.

**Comment by rgbkrk** [comment]
If we support metadata, then the user could write:

``` python
IPython.display.JSON(myData, expanded=True)
```

When they explicitly want to see it all and

``` python
IPython.display.JSON(myData, expanded=False)
```

When they don't (maybe a lot of data to take in, all at once.)

**Comment by rgbkrk** [comment]
As for the spec, if we want something nice for kernels and frontends to provide to users, we have to  adapt the message spec in Jupyter (we don't run our own specs here in nteract, we keep collaborating in Jupyter -- several of us are devs there too).

**Comment by rgbkrk** [comment]
> as easy as passing `shouldExpandNode={() => true}` as a prop to the JSONTree component

Yeah I'd make it:

``` js
shouldExpandNode={() => {
  if (this.props.metadata && this.props.metadata.expanded) {
    return true;
  }
  return false;
}
```

Under the assumption that we would want to hide by default. We can do this before we propose changes in Jupyter to specify this.

**Comment by aleury** [comment]
Oh okay! Awesome. That makes perfect sense. 

I can make the change to the `JsonDisplay` component. Would you, or someone else more experienced with Jupyter, like to make the changes to the Jupyter project if this is time sensitive? If not, I'd be happy to begin contributing to those projects as well.

**Comment by rgbkrk** [comment]
Definitely not time sensitive. I only outlined it so that we know what our next actions are.

**Comment by aleury** [comment]
Okay, that sounds good!

**Comment by aleury** [comment]
Hi @rgbkrk! Looking at the IPython source code I found that we can currently do

<img width="611" alt="screen shot 2016-10-10 at 6 47 55 pm" src="https://cloud.githubusercontent.com/assets/1060558/19253579/2198b7b6-8f1a-11e6-89b0-85de1390ddea.png">

But inorder to enable 

``` python
IPython.display.JSON(myData, expanded=True)
```

I think I would need to modify the  [JSON class](https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L514) to accept the appropriate parameters and call the constructor of the base class. However, I'm not sure where to go from there. Where would the expanded property of the JSON class instance be used for metadata in the response? Thanks! 😄

**Comment by aleury** [comment]
Looking at the `Image` class as a reference. I think I have a clearer understanding now. Would need to add a method like `_data_and_metadata(self)` and return the result of that from  `__repr_json__`?

**Comment by aleury** [comment]
Looks like I have something working! 😃 

<img width="562" alt="screen shot 2016-10-10 at 8 43 33 pm" src="https://cloud.githubusercontent.com/assets/1060558/19255307/8d1bbf00-8f2a-11e6-87a8-07441f7ea164.png">

<img width="530" alt="screen shot 2016-10-10 at 8 43 03 pm" src="https://cloud.githubusercontent.com/assets/1060558/19255326/ac83f98e-8f2a-11e6-9caf-7bb8cdfae272.png">

**Comment by rgbkrk** [comment]
Awesome!

**Comment by rgbkrk** [comment]
> I think I would need to modify the JSON class to accept the appropriate parameters and call the constructor of the base class. However, I'm not sure where to go from there. Where would the expanded property of the JSON class instance be used for metadata in the response? Thanks! 

The only other display class that relies on custom metadata is `Image`, which defines a constructor that accepts metadata. Based on what I'm seeing, it appears like you can

```
self.metadata = metadata
```

in the constructor. If you wanted to add the `expanded` arg, you would need to form the metadata object:

```
self.metadata = metadata
self.metadata['expanded'] = expanded
```

**Comment by rgbkrk** [comment]
[The Image class init](https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L641-L650)

**Comment by aleury** [comment]
Awesome! That's pretty much what I did. Thanks! I'll go ahead and open an issue and make a PR to the IPython repo.

**Comment by rgbkrk** [comment]
Silly me, I answered your questions well after you already answered them yourself. Sorry about that! Looking awesome.

**Comment by aleury** [comment]
Oh no problem at all! I appreciate the confirmation that I was on the right track. 😄

**Comment by aleury** [comment]
Looks like this issue is ready to be closed! Thanks for your help @rgbkrk! 🎉

**Comment by rgbkrk** [comment]
Woo! Excellent work, you completed this in `nteract`, `ipython`, _and_ `jupyter_client`. 🎉 Bravo!

Ready for a related hard problem to solve?

**Comment by aleury** [comment]
Of course! 😃
