### ISSUE TITLE
configurable keybindings

### ISSUE THREAD

**Issue by tacaswell** [nteract/archived-desktop-app#963]
In particular, to ship with the default emacs keybindings :smiling_imp: .

https://github.com/rmcgibbo/jupyter-emacskeys maybe relevant?

**Comment by rgbkrk** [comment]
That definitely helps. We have a config setup that we're planning to expose for CodeMirror. Part of the resulting config for you includes loading CodeMirror's built in emacs mode `'codemirror/keymap/emacs'` and then setting up the config.

In the meantime, here's a diff you can apply on master (probably to be out of date soon):

``` diff
diff --git a/src/notebook/components/cell/editor/index.js b/src/notebook/components/cell/editor/index.js
index 7742614..e82204f 100644
--- a/src/notebook/components/cell/editor/index.js
+++ b/src/notebook/components/cell/editor/index.js
@@ -17,6 +17,8 @@ import 'codemirror/addon/edit/closebrackets';

 import 'codemirror/addon/dialog/dialog';

+import 'codemirror/keymap/emacs';
+
 import 'codemirror/mode/javascript/javascript';
 import 'codemirror/mode/css/css';
 import 'codemirror/mode/julia/julia';
@@ -245,9 +247,15 @@ export default class Editor extends React.Component {
           Right: pick,
         },
       },
-      extraKeys: {
+      extraKeys: Object.assign({
         'Ctrl-Space': 'autocomplete',
-      },
+      }, CM.keyMap.emacs, {
+        'Ctrl-Y': (cm) => {
+          const originalBehavior = CM.keyMap.emacs['Ctrl-Y'];
+          originalBehavior(cm);
+          cm.setSelection(cm.getCursor(), cm.getCursor());
+        }
+      }),
       indentUnit: this.props.tabSize,
       tabSize: this.props.tabSize,
     };
```

(@tacaswell and I sat down at PyData DC to figure this out)

This definitely motivates that we need a js based config on the desktop app, similar to ~~hyperterm~~ hyper.app so that people can write custom functions for codemirror.

**Comment by rgbkrk** [comment]
I guess if it's just a package plugin with namespace `nteract-codemirror-emacs`, then the user could add it to their plugins list... 🤔

**Comment by rgbkrk** [comment]
Definitely need an expansion on how we do our config file, likely to take a raw javascript file.

**Comment by rgbkrk** [comment]
I _think_ this is much easier to support now that the codemirror component and our other components have become more compound. If folks are interested and want to lend a hand, I'll happily put together what to do for this.

**Comment by jletey** [comment]
Hello everyone, I'm currently working on this!

You can take a look at my branch ([john/keybindings](https://github.com/johnletey/nteract/tree/john/keybindings)), which I'm working out of.

I'm starting with Vim keymaps, but then I'll move onto Sublime as well as Emacs.

**Comment by captainsafia** [comment]
Thanks for taking this on, @johnletey!

**Comment by captainsafia** [comment]
This is implemented now as part of our config customizations in the desktop app.

**Comment by heiwiper** [comment]
Is this feature shipped in the version 0.27.0 ? I cannot seem to find it.

**Comment by captainsafia** [comment]
@HeiWiper You can read about how to customize them here: https://github.com/nteract/nteract/blob/990fa64f9526b3bd022b777d4e44d7411ce15758/docs/kbd-shortcuts.md#customizing-keyboard-shortcuts

**Comment by heiwiper** [comment]
@captainsafia I can't figure out how to set vim keybidings from that guide.

**Comment by captainsafia** [comment]
@HeiWiper We don't currently support vim keybindings since that requires implementing a command/edit mode and we don't support that. Only standard meta-key based keyboard shortcuts are supported.
