### ISSUE TITLE
High DPI splash screen

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#969]
The splash screen looks very blurry on high DPI screens.

There are a few ways we could fix this:
1. Make it half the size
2. Use something like [Bodymoving](https://creative.adobe.com/addons/products/12557#.V_uqfpOLSHo) to export the animation from [After Effects](https://github.com/nteract/logos/blob/master/nteract_logo_cube_book/source_files/animation/composition/nteract_logo_motion.aep) to HTML or SVG (no more GIF)
3. Use a static ~~high resolution~~SVG splash screen

**Comment by rgbkrk** [comment]
~~We do scale it right now (which might be part of the cause for blur).~~ We have an SVG version of a static logo. I wonder if we could create a full CSS animation for this... 

/cc @fabric-8

**Comment by lgeiger** [comment]
> We do scale it right now (which might be part of the cause for blur)

I don't think so:
https://github.com/nteract/nteract/blob/master/static/splash.html#L14

**Comment by rgbkrk** [comment]
😨 Fixed.

**Comment by fabric-8** [comment]
css version of this might turn out somewhat hardcore to produce - could web video be an option? compression can be really good and I could simply render it @2x

**Comment by rgbkrk** [comment]
Web video is definitely an option.

**Comment by lgeiger** [comment]
I don't know if web video would load fast enough. This would defeat the purpose of a splash screen.

**Comment by rgbkrk** [comment]
It's a local file at least, so there's not much of a bandwidth issue.

Beyond that, videos are _much_ smaller than GIFs and can also be autoplayed.

Ref: http://rigor.com/blog/2015/12/optimizing-animated-gifs-with-html5-video
