### ISSUE TITLE
Kite Plugin ?

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#971]
I just got an invitation to [kite](https://kite.com) which  seem to have already a few plugins ([vim, sublime, atom](https://github.com/kiteco/plugins)). The plugin API seem to be relatively straightforward (read-write json to a unix socket). 

Just suggesting writing a plugin for nteract would be cool.

**Comment by alexandercbooth** [comment]
Hi @Carreau,

Kite looks really cool! I'd be happy to give this a shot if you would be open to some mentoring (I suspect I could learn a lot from this). 

Thanks!

**Comment by Carreau** [comment]
I haven't poked that much at nteract in a while, I'm currently writing an IPython plugin, and can try once I understand the architecture of Kite better. In particular they seem to have an http (!) endpoint which is undocumented.

**Comment by alexandercbooth** [comment]
OK, I appreciate that. I'm still waiting for my invite from kite for now.

**Comment by rgbkrk** [comment]
My feeling on this is that we should integrate with the language server spec and go from there. Thoughts?

**Comment by willingc** [comment]
Closing this issue as kite seems better suited for integration with the editors.
