### ISSUE TITLE
LaTeX/MathJax no longer works inside Markdown cells

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#979]
![screen shot 2016-10-11 at 9 28 09 am](https://cloud.githubusercontent.com/assets/836375/19272047/10cc6678-8f95-11e6-9de2-8371e826b7b2.png)
![screen shot 2016-10-11 at 9 28 14 am](https://cloud.githubusercontent.com/assets/836375/19272048/10d33e80-8f95-11e6-9279-2a6be2952cef.png)

**Comment by lgeiger** [comment]
This worked in `v0.0.13`

**Comment by captainsafia** [comment]
This is closed in #1016.
