### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by chendaniely** [nteract/archived-desktop-app#983]
I made an AUR package for Arch to install `nteract`: https://aur.archlinux.org/packages/nteract-bin/
This is probably the only contribution I can make for the project since I know **zero** javascript :stuck_out_tongue_winking_eye: 

install with: `pacaur -Syyu nteract-bin`

run with `/opt/nteract-linux-x64/nteract`

there's a `.desktop` file in the package, but I'm not sure how to 'install' it in the build.  **HELP NEEDED HERE**

Here's the `nteract.desktop` file you can use to place in `/usr/share/applications/`

```
[Desktop Entry]
Comment=nteract: Interactive literate coding notebook
Exec=/opt/nteract-linux-x64/nteract
GenericName[en_US]=nteract
GenericName=nteract
Icon=/opt/nteract-linux-x64/resources/app/static/icon.png
MimeType=
Name[en_US]=nteract
Name=nteract
Path=/opt/nteract-linux-x64/
StartupNotify=true
Terminal=false
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-KDE-SubstituteUID=false
X-KDE-Username=
Categories=Science;Development;
```

**Comment by rgbkrk** [comment]
Awesome! @lgeiger is prepping installers for OS X and Windows in #952. I wonder how this all works with Linux.

**Comment by tacaswell** [comment]
I do not know if this is a 'blessed' way to do it, but if you echo that desktop to disk in `build()` and then copy it where ever it needs to go in the `package()` step.

**Comment by chendaniely** [comment]
If it's going to packaged up for Linux users, can we add a `.desktop` file to this repository? maybe under `static`, I can copy it to the necessary location from there.

We can probably update the `MimeType` so `nteract` is associated with `.ipynb` files too

**Comment by lgeiger** [comment]
In #952 we are exploring [`electron-builder`](https://github.com/electron-userland/electron-builder/). It even has support for [desktop files](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions).
Feel free to try the PR and take a look at `electron-builder`. It supports a lot of formats for linux and also outputs a unpacked version.

**Comment by rgbkrk** [comment]
Yes please! I _think_ that would go with the other OS specific stuff that's in `static/` (`extend.plist` is for OS X). Not sure how we need to present it, though it sounds like we can adapt it for electron-builder after you submit the `.desktop` file @chendaniely.

**Comment by lgeiger** [comment]
@chendaniely Sorry I lost track of this issue.

[`electron-builder`](https://github.com/electron-userland/electron-builder/) handles all of our packaging very well and supports a lot of different [targets (including `pacman`)](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions).
It should be a matter of editing our [build config](https://github.com/nteract/nteract/blob/master/package.json#L42) to make it work.

It would be really great to have you on board since we don't have much experience with publishing for linux (especially ARCH).

**Comment by rgbkrk** [comment]
How's this now? I'm _guessing_ the apt packaging in #1299 probably made this a bit easier for us to also have an Arch Linux release.

**Comment by ConorIA** [comment]
@chendaniely, I maintain a couple of PKGBUILDS for Electron-based apps that are built with `electron-builder`. Please see the attached PKGBUILD. Note that I have also included a `LICENSE` source file since the BSD-3-Clause is not included in `core/licenses`. Note that there may still be some dependencies missing in the attached PKGBUILD. 

~~I should also note that I haven't yet gotten v 0.1.0 to run properly. I get stuck on a blank screen. Not sure if it will work better for other folks.~~ Nevermind, it is running fine.

Note, please remove ".txt" for both of these files (GitHub wouldn't let me upload without an extension).

[PKGBUILD.txt](https://github.com/nteract/nteract/files/880094/PKGBUILD.txt)
[LICENSE.txt](https://github.com/nteract/nteract/files/880095/LICENSE.txt)

Pasted below for good measure: 

```
# Maintainer: chendaniely <chendaniely@gmail.com>
# Contributor: Conor Anderson <conor@conr.ca>

pkgname=nteract-bin
_pkgname=${pkgname%-bin}
pkgver=0.1.0
pkgrel=1
pkgdesc="Interactive literate coding notebook"
url='https://nteract.io'
arch=('x86_64')
depends=('alsa-lib' 'gconf' 'gtk2' 'libxss' 'libxtst' 'nodejs' 'nss' 'python')
makedepends=('gendesk')
license=('BSD-3-Clause')
source=("${_pkgname}_${pkgver}_amd64.deb::https://github.com/nteract/nteract/releases/download/v$pkgver/nteract_0.1.0_amd64.deb"
        "LICENSE")
sha256sums=('38d56954443a1debad628d1d76750e9c20f32932bfcb6eb632651211c3f6e1b2'
            '9810f3d57c552d3b3f6c82cb3b6f3402d6faf94fc5a63067fe28360fb3b8b688')

prepare() {
  gendesk -f -n --name="${_pkgname}" --pkgname="${_pkgname}" --pkgdesc="${pkgdesc}" --exec="${_pkgname}" --categories="Development"
}

package() {
  cd "$srcdir"
  ar xf "${_pkgname}_${pkgver}_amd64.deb"
  tar xf data.tar.xz

  # Place files
  install -d "${pkgdir}/usr/lib/${_pkgname}"
  cp -a "${srcdir}/opt/${_pkgname}/"* "${pkgdir}/usr/lib/${_pkgname}"
  
  # Symlink main binary
  install -d "${pkgdir}/usr/bin"
  ln -s "/usr/lib/${_pkgname}/${_pkgname}" "${pkgdir}/usr/bin/${_pkgname}"

  # Place desktop entry and icons
  desktop-file-install -m 644 --dir "${pkgdir}/usr/share/applications/" "${srcdir}/${_pkgname}.desktop"
  install -dm755 "${pkgdir}/usr/share/icons/hicolor/"
  cp -R "${srcdir}/usr/share/icons/hicolor/"* "${pkgdir}/usr/share/icons/hicolor/"

  # Place license files
  for license in "LICENSE.electron.txt" "LICENSES.chromium.html"; do
    install -Dm644 "${pkgdir}/usr/lib/${_pkgname}/${license}" "${pkgdir}/usr/share/licenses/${_pkgname}/${license}"
    rm "${pkgdir}/usr/lib/${_pkgname}/${license}"
  done
  install -Dm644 "${srcdir}/LICENSE" "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE"
}
```

**Comment by chendaniely** [comment]
@ConorIA do you have an AUR account? I can add you to the co-maintainer list there.
I've tried to fix up the PKGBUILD the other day, and completely messed it up and reverted it back.

But I've updated the AUR with your files. THANKS! :+1:

**Comment by ConorIA** [comment]
Yep. I'm ConorIA on the AUR too.

**Comment by rgbkrk** [comment]
Since the AUR package exists, I'll go ahead and close this. If I'm wrong on this, feel free to re-open!

**Comment by JMurph2015** [comment]
@ConorIA Hi! I don't have an AUR account yet, so I figured I'd drop this here:
I don't think the icon should be getting dropped in /usr/share/icons/hicolor/0x0.  At least for me that makes the icon unusable (aka the icon loader won't find it).  Perhaps /usr/share/icons or /usr/share/icons/hicolor/256x256 would be a better place to put the icon.

**Comment by ConorIA** [comment]
Thanks @JMurph2015. The issue is in the `.deb` that the PKGBUILD is based on. I hadn't noticed until you pointed it out. [Fixed!](https://aur.archlinux.org/cgit/aur.git/commit/?h=nteract-bin&id=e079f7ce9dcf3070c25f89372ab8ba94e88cd1dc)
