### ISSUE TITLE
Provide feedback when conda environments can't be found

### ISSUE THREAD

**Issue by chendaniely** [nteract/archived-desktop-app#984]
When I open `jupyter notebook` I see:

![selection_024](https://cloud.githubusercontent.com/assets/5782147/19286667/858a2766-8fcc-11e6-9841-039aaa4e36b0.png)

When I launch nteract, I only connect to (and only see) the R kernel. I don't see any of my Python Kernels.

Until #357 is resolved, there needs to be some feedback to users about their environment. Ideas/TODOs:
- [ ] Pop up a dialog with "Apologies, we don't have conda environment detection yet - we're still working on it in https://github.com/nteract/nteract/pull/847"
- [ ] Provide a way to do diagnostics from the released app (no access to node at command line)
- [ ] Provide a way to report an issue that encapsulates the diagnostics report

**Comment by jdetle** [comment]
Hey Daniel, I think the issue is that we do not yet have support for Conda kernels. (Coming soon!) If you run `npm run diagnostics`, this should list all the kernels available to you.

**Comment by chendaniely** [comment]
Oh boy... pardon my ignorance (I don't do anything javascript-ey). what's this `package.json` file I need for `npm`?

```
$ npm run diagnostics
npm ERR! Linux 4.7.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "diagnostics"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! path /home/dchen/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/dchen/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/dchen/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dchen/npm-debug.log
```

```
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'diagnostics' ]
2 info using npm@3.10.8
3 info using node@v6.7.0
4 verbose config Skipping project config: /home/dchen/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/dchen/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/dchen
7 error Linux 4.7.6-1-ARCH
8 error argv "/usr/bin/node" "/usr/bin/npm" "run" "diagnostics"
9 error node v6.7.0
10 error npm  v3.10.8
11 error path /home/dchen/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/dchen/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/dchen/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]
```

**Comment by rgbkrk** [comment]
I'm working on this in https://github.com/nteract/nteract/pull/847. We've got a bit of a ways to go to make conda kernels show up.

**Comment by rgbkrk** [comment]
@jdetle - @chendaniely is working with the released app, not in dev mode

**Comment by jdetle** [comment]
Ah I should have asked, so @chendaniely, if you open the dev console in nteract (View -> Toggle Developer Tools) on an open notebook page then run:

``` js
require('kernelspecs').findAll().then(console.log.bind(console)).catch(console.error.bind(console))
```

the kernels available to nteract will be listed. I think this does relate to #956 in that you should connect to an available kernel by default.

**Comment by rgbkrk** [comment]
To make at least one conda kernel show up in nteract, you can install a kernelspec from the environment:

```
source activate envName
conda install ipykernel
python -m ipykernel install --user
```

**Comment by chendaniely** [comment]
woo....! @rgbkrk that got it working.

I guess I must've installed the R kernel manually and not through `conda`

**Comment by rgbkrk** [comment]
I see a couple of action items we can address to make our user experience better here until we solve the core issue in #357:
- [ ] Provide a way to do diagnostics from the released app (no access to node at command line)
- [ ] Provide a way to report an issue that encapsulates the diagnostics report
- [ ] Report a simple message noting "hey I see you have conda installed - we're still working on it"

**Comment by rgbkrk** [comment]
Instead of me closing the issue and saying that this is reported in #357, would you be alright if we change the issue to be about reporting better messages for conda users (it can use my current bullet list, feel free to add on)?

**Comment by chendaniely** [comment]
@rgbkrk sounds good.

I didn't scroll down far enough in the issue search to see #357 :x

**Comment by rgbkrk** [comment]
With the work that wasn't merged in #1384, we could have had conda support. I couldn't finish that up given some other priorities, it would be great if someone looked into where I started it to finish it off.

**Comment by blob42** [comment]
Hi guys, I was looking for a simple native jupyter notebook reader and stumbled on nteract. I installed it on Arch using @chendaniely AUR package.

I'm using pyenv (same as conda) but the python kernel is not detected although it's installed on my environment ant the env is activated. On launch I have a js error with `kernelspecs` lib. 

@rgbkrk  Is #1384 what needs to be finished for virtualenv support ? I could take look into it

**Comment by rgbkrk** [comment]
#1384 will get you partway, in that it will find your base python installation and pave the way for exposing environments. For _detecting_ virtualenvs though, we'd have to have a way to find them on disk. @minrk has voiced that trying to hunt around on disk for virtualenvs that have `ipykernel` is rife for disaster as opposed to [setting up a named kernel](https://github.com/ipython/ipython/blob/b133a709842e32d838c24dd2b22f9c622bc37992/docs/source/install/kernel_install.rst#kernels-for-different-environments) within a virtualenv using e.g.

```
python -m ipykernel install --user --name other-env --display-name "Python (other-env)"
```

**Comment by rgbkrk** [comment]
Closing as duplicate of #357
