### ISSUE TITLE
Provide better error if no kernelspecs are found

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#988]
The current situation isn't nice for users:
![nteract](https://cloud.githubusercontent.com/assets/13285808/19303775/3fa8e446-906a-11e6-9d21-299448750a07.gif)

The full error messages are:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at Promise.all.then.kernelInfos (/home/lukasgeiger/code/nteract/node_modules/kernelspecs/lib/traverse.js:64:8)
```

and

```
No kernels installed on your system

No kernels are installed on your system so you will not be able to execute code cells in any language. You can read about installing kernels at https://ipython.readthedocs.io/en/latest/install/kernel_install.html
Full error: Reduce of empty array with no initial value
```

**Comment by captainsafia** [comment]
Huh. That's weird. You first get the JavaScript traceback and _then_ the message that we created. I think perhaps we've added something in our code that tries to loop through the kernelspecs before the app is ready though I'm not sure where that might be...

**Comment by lgeiger** [comment]
Close by https://github.com/nteract/nteract/pull/1053
