### ISSUE TITLE
how to use nteract

### ISSUE THREAD

**Issue by hainm** [nteract/archived-desktop-app#995]
hi

sounds dummy question but how users would use nteract?

quote from README
`Edit code cells, write markdown, visualize!`

> Double click a .ipynb on the desktop, use Spotlight on the Mac. It Just Works™

What do you mean 'It just Works'? 

thanks.

**Comment by hainm** [comment]
``` bash
npm run start some_notebook.ipynb
```

seems do the trick but took me quite long time to realize that. :D

**Comment by jdetle** [comment]
Hi @hainm! Thanks for trying it out. You bring up a good point, I think this might be meant for releases rather than developer installations, and perhaps we should make that clearer.

**Comment by rgbkrk** [comment]
The "just works" line is likely aimed at how you can treat jupyter notebooks as native files using finder, etc. (For the built release).

This brings up an even more pressing issue - how does a complete beginner to jupyter get introduced at the beginning of the readme? You're a well practiced user of Jupyter @hainm so if we confused you, we confused way more people.

/cc @willingc

**Comment by captainsafia** [comment]
I think the blog post on our Medium is a solid run through.

**Comment by willingc** [comment]
@rgbkrk Perhaps:

It wraps up the best of the web based Jupyter notebook and embeds it as a desktop application. Now, you can open notebooks natively on your system. Double click on an`.ipynb` file to open and begin using the notebook.  It Just Works™

I found the Spotlight reference confuzzling.

**Comment by captainsafia** [comment]
> It wraps up the best of the web based Jupyter notebook and embeds it as a desktop application. Now, you can open notebooks natively on your system. Double click on an.ipynb file to open and begin using the notebook. It Just Works™

That sounds solid. I also think this issue falls under the general need for a User Guide for nteract that outlines things like opening/savings, using the cell dropdown to change cells, adding new cells, etc. I think that can be added as a new-contributor-friendly issue for people who are willing to do some self-testing of that app.

**Comment by captainsafia** [comment]
This is closed via the addition of a user guide in #1032. Let us know if you have any other questions about using the app, @hainm!

**Comment by hainm** [comment]
cool. thanks.
