### ISSUE TITLE
Add user guide for nteract

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#996]
This is a follow-up on the question raised in #995.

nteract has an interface that's very different from other interactive notebook applications. We need to create a User Guide that outlines.
- [x] What nteract is
- [x] How to create/open/save files
- [x] How to run, move, and add cells
- [x] How to use the cell dropdown

This guide can reside in a USER_GUIDE.md file at the top directory of this repository.

cc: @willingc

**Comment by rgbkrk** [comment]
Pertinent easy to start part for this issue is updating the [user installation of nteract in the readme](https://github.com/nteract/nteract#installation---users).

**Comment by alexandercbooth** [comment]
I'm happy to work on this. I'll submit a [WIP] PR for some feedback from everyone later tonight.

**Comment by rgbkrk** [comment]
Awesome, looking forward to it.

**Comment by captainsafia** [comment]
This was closed in #1032.
